### ISSUE TITLE
AAPS/NSClient Temporary Targets incorrectly set if in mmol

### ISSUE THREAD

**Issue by Tornado-Tim** [MilosKozak/AndroidAPS#1009]
Version: AAPS-rc3 but applies to older builds of AAPS/NSClient

AAPS seems to not convert Temporary targets when the unit is set in mmol.

Since nightscout deals with Temp targets in mgdl, any value in mmol is pushed to Nightscout as mgdl, so a temporary target of 4.4 gets translated to 4.4mgdl.

I had a situation where I set a temp target in NSClient then later tested in AAPS with a temp target of 4.8mmol, the temp target synced to nightscout but was not visible in the Nightscout page, till I found it right under the date slider in Nightscout WebUI, ultimately meaning it Nightscout treated this as a temporary target of 4.4mgdl.

I then re-tested another scenario to confirm my suspicions. Entering a temp target in NSClient/AAPS at 4.8mmol, then checked my openaps rig, the temp target that OpenAPS was using 4.4 not 4.8 (the min safety guard of 4.4 for min temping in openaps). I then entered the 4.8*18 (86.4) into the Nightscout WebUI then later checked in AAPS, the temp target line jumped from previous target in mmol to 48.

So it seems the syncing of temp target data from NS needs to be converted to mgdl in AAPS/NSClient if mmol units are set. 
The opposite also needs to be done when getting temp target data from Nightscout and reconverting it to mmol when re-seting it back into AAPS/NSClient.

The screenshot attached shows this issue well, when temp targets are set in NS WebUI (at 86.4mgdl )and then synced back to AAPS (in mmol).
![screenshot_20180505-171828_androidaps](https://user-images.githubusercontent.com/2896311/39660657-f3881682-5097-11e8-8c68-b8f4ff86870c.jpg)

**Comment by MilosKozak** [comment]
should be resolved
