### ISSUE TITLE
AAPS Sensitivity cutting off before expected time

### ISSUE THREAD

**Issue by MarkMpn** [MilosKozak/AndroidAPS#1024]
Using RC3 (not tested in other versions, so not sure if this is a regression or not)

Using Sensitivity AAPS, after entering meal carbs, the COB chart shows them decaying at a constant rate using the minimum impact indicated by the dots along the chart. Although the `Meal max absorption time [h]` is set to 8, the chart shows the COB reaching zero at about 4 hours later.

As an example, see the carbs starting from just before 13:00 here:

![screenshot 1 - aaps](https://user-images.githubusercontent.com/31017244/39676522-075b81b8-5164-11e8-8e64-18c29e242b7e.png)

Switching to Sensitivity Oref0, a more more extended COB decay curve is shown, which is more in line with my expectations.

![screenshot 2 - oref0](https://user-images.githubusercontent.com/31017244/39676524-0a9c37d2-5164-11e8-97a8-d4be13012f5d.png)

Log file showing both versions is here:
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1977907/AndroidAPS.log)

**Comment by AdrianLxM** [comment]
8h max time, 200, 5 hours back, 70g remaining ->
5*200÷(200−70) -> 7.7 hours. That's close enough to 8 assuming some rounding and one or two
![screenshot_20180506-212505](https://user-images.githubusercontent.com/9692866/39677041-122b89ec-5175-11e8-949f-25a058db8003.png)

If I delete the entry and enter a 100g treatment it has 31g of carbs left. That's a little bit less than half of 70g as now it more often was "dynamic":
![screenshot_20180506-212725](https://user-images.githubusercontent.com/9692866/39677068-58f42e56-5175-11e8-87cf-fbaa865c3de0.png)


If I then enter another 100g treatment 5 hours back I now have two treatments just a minute or two apart. It again gives me a COB of 70g as if both treatments were entered as one.
![screenshot_20180506-212658](https://user-images.githubusercontent.com/9692866/39677069-59155cf2-5175-11e8-9d9a-cbbd35a07ad7.png)

This looks right to me. Hard if it is not reproducable :/

**Comment by MarkMpn** [comment]
Yes, that all looks good. I’ll do some more digging and see if I can figure out what’s different about my setup.

**Comment by AdrianLxM** [comment]
Sensitivity plugins have been rewritten. Closing. Please open again, if it still applies.
