### ISSUE TITLE
Cannot generate signed apk

### ISSUE THREAD

**Issue by 397Seth** [MilosKozak/AndroidAPS#1027]
Hi,

I tried the whole last night to genere a signed apk but whatever I do I only get wear-release.apk which is not working.
If I use the non signed apk I get the correct apk but cannot install it.

Can you help with this issue? Main reason I want this is to push the dexcom readings to xDrip since the alarm function is rather bad on the dexcom.

**Comment by triplem** [comment]
Do you look into the correct folder? Do you use the "Locate"-Button, shown in the Popup in AS after generating the APK?

If you just would like to have the Dex readings in xDrip you could also use xDrip with the G5 Native Algorithm. The you don't need a separate App just for forwarding your readings

**Comment by AdrianLxM** [comment]
Did you look at "full/release" and not only "release"?

**Comment by 397Seth** [comment]
Hi,




yes I clicked on the pop up and the folder that opened always contains an apk that is not working.


What do you mean with native g5 algorithm?


Has xdrip the same algorithm as g5?


Meaning the readings are identical?


That would be interesting, problem is that my doctor uses clarity to look at my data. Can xdrip push to clarity?




Thanks for your help 


 




Von: Markus M. May


Gesendet: Montag, 7. Mai, 16:50


Betreff: Re: [MilosKozak/AndroidAPS] Cannot generate signed apk (#1027)


An: MilosKozak/AndroidAPS


Cc: 397Seth, Author






Do you look into the correct folder? Do you use the "Locate"-Button, shown in the Popup in AS after generating the APK?


If you just would like to have the Dex readings in xDrip you could also use xDrip with the G5 Native Algorithm. The you don't need a separate App just for forwarding your readings

**Comment by swissalpine** [comment]
As Adrian wrotes: If you click on `locate` after building the app, Android Studio will not link to the right folder.
Please navigate to the `app/full/release` folder! There you will find the working `full-release.apk`.

**Comment by 397Seth** [comment]
After reinstalling the software it worked, Thanks for your help guys

**Comment by swissalpine** [comment]
Fine to read.
Please can you close the issue then?
Thanks.
