### ISSUE TITLE
Battery drainage

### ISSUE THREAD

**Issue by Oekonom2** [MilosKozak/AndroidAPS#1035]
Hi everyone,

I have just installed the app on my S7 2 days ago. At the moment I don't use the loop yet, only the G5 to Xdrip push. My problem is, that this drains roughly 20% battery power.
Is this normal? After 14 hours the battery is completly dead. 
Do you also have such a high drainage?

Cheers

**Comment by AlexD97** [comment]
Hi,
which Android version do you use? I recognized high battery drain after updating my phone to Android Oreo. With Android Nougat everything was fine.

**Comment by Oekonom2** [comment]
I have Anroid 7, last update 1st of April.

**Comment by triplem** [comment]
Since AAPS is doing calculations in the background, thee is a battery drainage involved. Some preferences can be set to avoid a too huge battery drain. Eg you can disable sending all Treatments to NS without WiFi connections or even do this upload only if the phone is charging.

**Comment by Oekonom2** [comment]
I have turned all of those off. I don't even use connection to the pump. I have started only with pushing Dexcom G5 to xDrip. And only this drains 15-20% of my battery.
Might be that the battery is dying anyway.

**Comment by MilosKozak** [comment]
it's still APS doing all calculations
