### ISSUE TITLE
[RC3] „OpenAPS Offline“ event bar does not end in OVERVIEW graph

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#1049]
When I press „Disable loop“ then „OpenAPS Offline“ is shown in the graph. But when I press „Enable loop“ after that, then the bar doesn‘t fit to the timerange the loop was offline. The bar is streched over the hole timerange, shown in the graph.

![39a13a7d-c3ca-4ec8-a57d-1313f45965c4](https://user-images.githubusercontent.com/6819067/40190062-2cfaf9c4-59fe-11e8-8a8d-d0924d23654b.png)

**Comment by tanja3981** [comment]
This is still open in RC4.

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/de2273836efa8e55fefb45ca0b2970872b5896dd
