### ISSUE TITLE
Value sens 

### ISSUE THREAD

**Issue by dedeshkoau** [MilosKozak/AndroidAPS#1051]
Please help. 
Value sens is out of hard limits 1800 limited to 900
I don t know hav to solve it

**Comment by AlexeyDedeshko** [comment]
It's problem in android aps aplication on my phone. Does anybody know how to solve it?

**Comment by MilosKozak** [comment]
i believe you have wrong units in active profile

**Comment by AlexeyDedeshko** [comment]
But where I can find it for change?
