### ISSUE TITLE
NSClient: The Overview Tab screen contains wrong format of information about changes

### ISSUE THREAD

**Issue by dagobyj** [MilosKozak/AndroidAPS#1052]
NSClient 1.60e-dev
Build: 953128ffe-2018.05.21-19:18
Flavor: nsclientdebug

I instaled this version on Sony Xperia Z5 Compact (Android 7.1.1, screen 1280x720). The Overview screen appears:
![screenshot_20180521-213153](https://user-images.githubusercontent.com/37915176/40328387-7af495a4-5d46-11e8-8749-9c59856fd953.png)
After the rotation left is the screen OK:
![screenshot_20180521-220845](https://user-images.githubusercontent.com/37915176/40328479-d0e6b082-5d46-11e8-97af-03569ac1f2b7.png)

I instaled this version on SGS5 NEO (Android 6.0.1, screen 1920x1080). There is screen OK.
Many thanks.

**Comment by MilosKozak** [comment]
redesigned here https://github.com/MilosKozak/AndroidAPS/commit/a3fafa521b2a23f03f022b39eae2548103986fb2
