### ISSUE TITLE
Setup Wizard only 2 small points

### ISSUE THREAD

**Issue by blocklist** [MilosKozak/AndroidAPS#1053]
Where:
In the Setup-Wizard.
Version:
1.60e-dev (fa2c0ab-2018.05.23-08:49)

1. When you have do same step "next", and you go back (prev-Button), on "Language" you have a "Prev-Button", but the Setup is not going to the previsly "import settings"-Page.

2. i missed a "cancel"-Button, so at the moment, you need to finish the setup wizard.

thats all, what i found ;-)
And if you take an outdated settings file, where the connection settings were not yet included, it is of course clear that these are then at default after the setup process :-)

**Comment by AdrianLxM** [comment]
The Skip/Exit button is on the upper left corner. Should we add text to the icon to make it clearer?

**Comment by MilosKozak** [comment]
return to 1st page fixed

**Comment by MilosKozak** [comment]
you can exit wizard 3 way now:
- Exit icon
- Finish on last page
- Press back on first page

**Comment by blocklist** [comment]
:-) i dont have seen the exit icon and dont understand is as "cancel/exit" :-) thx
yes, i find a text with "exit" to the icon is better.
