### ISSUE TITLE
Entries performed via the care-portal page disappear from time to time.

### ISSUE THREAD

**Issue by savek-cc** [MilosKozak/AndroidAPS#1054]
Using 2.0 RC2 - but observed that behaviour in the past.
I'm entering pump-site changes and catrige changes into nightscout using the careportal page within AndroidAPS - they are accepted and correctly displayed within AAPS.
After a while (maybe after restarting AAPS? not verified yet), those entries disapear (e.g. pump site is 5 days old while it should be 2). Apparently these entries also were not transmitted to Nightscout. (Since NS also shows the old change times and completely missed the new one entered in AAPS).
This does only happen from time to time - not on every entry.
Thus: Sorry, no logs, no data - but maybe others have observed this, too?

**Comment by MilosKozak** [comment]
closing as we have no logfiles
