### ISSUE TITLE
Locale switching problem

### ISSUE THREAD

**Issue by infoneo** [MilosKozak/AndroidAPS#1060]
When the Polish translation I have switched language to Polish. After some tests I decided to switch back to English. Since then AAPS switches automatically (one or twice a day) to Polish, then to English and again. (without any interaction). Switching never ends.
In Prefs "English" language is selected, but interface is translated...

![](https://i.imgur.com/Bcna7dV.jpg)

**Comment by CaptainBalou** [comment]
I see that too with German/English

**Comment by CaptainBalou** [comment]
Still there in RC4

**Comment by quizzmaster** [comment]
The locale is set correctly, but doesn't get set for all parts of AAPS on a restart (not resume) of the app. For example: The tab titles are displayed in the device language, but the showed strings within the preferences are displayed in the selected language.

**Comment by hartlijn** [comment]
issue is also present in 2.0-rc7

**Comment by quizzmaster** [comment]
This might be a problem with Android 8 simce I saw other apps having the same issue.

**Comment by infoneo** [comment]
I have android 7.1.2

**Comment by infoneo** [comment]
The same problem on android 9 Pie, different phone.

**Comment by 2flea** [comment]
Issue is present in Master 2.0 and latest dev from 04.11.2018. 
My settings are in English but the app menu randomly switches back to German. Some screens are even a mixture of both. 
Settings:
language::en
Locale.Helper.Selected.Language::en

App cache deleted, several restarts of app and phone did not help. Android 8.1.

![image](https://user-images.githubusercontent.com/38214111/47967131-805c2100-e05a-11e8-814c-0867081525fb.png)

**Comment by Snowli1710** [comment]
Also ich konnte das Problem so nicht lösen! Mit keiner App habe ich diese Probleme. Nur unter AAPS funktionieren die Sprachen nicht.

**Comment by winni67** [comment]
Same Problem to me on Android 7.x and Android 9.0 with AAPS 2.5.1. It is not possible to switch the AAPS language to english. The preferences are still in german language and most of the submenus. Even the OVERVIEW page is in both languages. The menus are in english, the buttons are in german language. Please switch back to the old behavior. This was very helpful for supporting AAPS in different languages. Thanks in advance and kind regards.
