### ISSUE TITLE
[dev] SW: first impressions

### ISSUE THREAD

**Issue by th122** [MilosKozak/AndroidAPS#1062]
Updated test phone from aaps master to today's dev. Upon start. despite of the previous configuration, I was greeted with the setup wizard, hooray! 
(I think this is a brilliant idea, especially considering that someone upgrading from master to dev will have a few choices to (re) consider).

So I'm starting to write up my impressions as I go through the screens.

What I immediately liked was that the presentation as a setup wizard allows for some explanations, and also offers the ability to link to the documentation. 👍 

On my first attempt, I'm going through the steps in English.

- **APS selection** could profit from some explanations on the difference of the algorithms. The cathegorization "oldest to newest" could lead some users to believe that "newest" is best, similar to the "dev gives more features faster" train of thought which is difficult to cure.
Each algorithm could have a short characterization and a link to a more detailled explanation (Also involving the openAPS pages where appliable?), for example 
  - [ ] OpenAPS MA uses TBRs to make adjustments. Slowest and safest of the algorithms. 
  - [ ] OpenAPS AMA requires carbs to be entered reliably. Tries to compensate for slower/faster meal absorption.
  - [ ] OpenAPS SMB uses series of small bolus to address rising sensor glucose, taking a "loan" from the basal rate to deliver that amount upfront as bolus. 
         Requires a reliable and "smoothed" svg curve to avoid overreaction. 
         Requires a comfortable understanding of the parameters and workings of the algorithm to operate safely.
         Requires thoroughly tested parameters.

- Configure APS plugin:
      explanations of limiatations.
        advanced: good: there's a link to the while you wait page. Some explanations could also be given directly.

- LOOP only has enable loop. once it's enabled, `<prev>` doesn't undo that.  Doesn't differenciate between open and closed loop (may be by design, the profile for master had the virtual pump enabled anyway)

That's it so far leaving the wizard open for the commute back home...

darn. it keeps making suggestions while in the wizard ;-p I'll have a humming and vibrating phone along with me...

**Comment by triplem** [comment]
One more thing with the Wizard, which I do think is a great improvement. 

If I did import all settings, I do not want to see the wizard a second time. Therefor, after importing settings successfully, the wizard should not be shown another time. Or if new settings are needed, then do show only the ones, which I should set.

**Comment by gregorybel** [comment]
:+1
