### ISSUE TITLE
Graphing of sensitivity (white line)

### ISSUE THREAD

**Issue by LongboatAline** [MilosKozak/AndroidAPS#1074]
I have been wondering why the sensitivity as graphed 

- doesn't really show much variation, even when I would have expected it to (according to the results of autosens)
- jumps to different y-axis offsets depending on the range-in-view
- sometimes even gets drawn at a negative y-axis 

It seems to me that the scaling the y-axis is often subjected to doesn't get applied to the display of the sensitivity line?

I've tried my luck with master, dev at different versions, rc3, rc3 with PR #992 applied, and dev as of 2018-06-03.

Here's an example at 6,12,18 and 24hour view from RC3 patched with PR #992 :
![rc3-991_20180604-0746-06h](https://user-images.githubusercontent.com/35570803/40922628-feaae8e0-6812-11e8-937f-8fbfa0523088.png)
![rc3-991_20180604-0746-12h](https://user-images.githubusercontent.com/35570803/40922649-08adb804-6813-11e8-9531-bdcac52a59de.png)
![rc3-991_20180604-0746-18h](https://user-images.githubusercontent.com/35570803/40922670-0f78b350-6813-11e8-958f-294fe723792e.png)
![rc3-991_20180604-0746-24h](https://user-images.githubusercontent.com/35570803/40922689-1cb9a592-6813-11e8-8835-836bbd261005.png)

**Comment by AdrianLxM** [comment]
The charting library is a bit of a mess when adding multiple lines with different scales each.
Does it plot correctly if only plotting the sensitivity?

**Comment by LongboatAline** [comment]
The last days things seem to be in a range where the glitch isn't triggered (didn't update to rc4 yet to maintain conditions). I'll try to isolate the sensitivity line as soon as I can reproduce the "below zero in 6 hour view only" case - I think that's the only one that might merit attention. 
Or should it just be added to the documentation that the sensitivity line follows its own scale that doesn't get displayed when other graphs are added to the display? (I'd volunteer to do that)

**Comment by LongboatAline** [comment]
Yesterday I've had a similar situation, were the sensitivity graph was plotted on a "negative" y-axis at the shortest timeframe, and around 10 everywhere else. Turning off all other graphs confirmed your suspicion - in that case the graph was in a consistent range all around.
So maybe it's enough to document for the time being that for sensitivity, the position on the graph can vary depending on the range of the other graphs, and while the position/scale be disregarded, the graph itself is sound.

**Comment by MilosKozak** [comment]
it has  been improved in dev now. reopen if needed
