### ISSUE TITLE
TDD wrong date

### ISSUE THREAD

**Issue by CaptainBalou** [MilosKozak/AndroidAPS#1075]
Working on RC3 build. Dana RS. Dexcom G5 with xdrip.

Since today 00:00 o'clock I noticed that I do not see any SMBs in the graph anymore. But I see them in Nightscout and they are in fact injected. Screenshots attached.

![screenshot_20180604-093503_firefox](https://user-images.githubusercontent.com/17015872/40935453-8605b25a-6838-11e8-95a4-4b71d94d1e06.jpg)
![20180604_203900](https://user-images.githubusercontent.com/17015872/40935456-868aa0f0-6838-11e8-94ea-a3fbc4cd68eb.jpg)

I also noticed that Dana's TDD don't show the current date on top of the list. The last few days was 31.05., 01.06., 02.06., 03.06. so I assumed to see 04.06. today which in fact is the current date. But the top of the list shows 03.05. which seems odd to me. Screenshot is included as well.

![20180604_203827](https://user-images.githubusercontent.com/17015872/40935454-864d8508-6838-11e8-84c7-43aeaaa2d0a8.jpg)

Because these two things deal with boluses I think it could be the same issue. Therefor I opened just one ticket.

**Comment by CaptainBalou** [comment]
...and because I have no idea if this happens with non-RC3 builds as well I have _not_ marked it with an RC3 flag.

**Comment by jotomo** [comment]
I think you're mixing up extended carbs (currently displayed on the BG line) and SMBs displayed as blue triangles at the lower end of the first graph.

**Comment by CaptainBalou** [comment]
Oh yes that could be true. I used NSclient until Friday evening and I have never heard of SMBs in triangles.
So there is just the TDD thing left. Or is that also a misunderstanding on my side?

**Comment by AdrianLxM** [comment]
You do have a new pump? Could it be that there is a TDD entry in the future? Wrong date?

**Comment by CaptainBalou** [comment]
Yes the pump is new. Got it on Friday. The TDD view started with just 31.05. and after midnight a second line came up. That continued until 03.06. but then a new line 03.05 was there suddenly. So now we had another day change and the result is that I see 04.06.and over that the 03.05. as before.

A TDD entry in the future? Hmm, is that something I could have done by accident? I don't know if I did it nor how to check this. But the 03.05. was definetely not in the list from the beginning.

**Comment by CaptainBalou** [comment]
After day 10 the wrong entry disappeared. I don't know if this is worth analysing it further...?!

**Comment by MilosKozak** [comment]
TDD in R pumps may be wrong when pump date is adjusted

**Comment by JimZam** [comment]
Good morning. I'm having a similar problem. In TDD there are a lot of entries in the future. I had problem with my phone date but I realized the date was wrong in a couple of hours, so I don't know why there are so many entries in different days (reported it here):
https://github.com/MilosKozak/AndroidAPS/issues/1866
And now that I see them, all TDD are wrong, I haven't had 65% on 11/7 nor 74% on 12/7...
Any help?
Thank you and regards
![Screenshot](https://user-images.githubusercontent.com/23319786/61202033-b623d000-a6e6-11e9-90d1-40168ba47295.png)
