### ISSUE TITLE
Remote bolus not allowed

### ISSUE THREAD

**Issue by viktor200** [MilosKozak/AndroidAPS#1082]
Hi everyone,

I recently started again to use AndroidAPS for my 6-year-old son.

My problem is, that sometimes when I try to Bolus him with a text message, I receive the answer 

"Remote bolus not allowed"

This can happen once, twice, sometimes couple of times in a row. 

Is there something I can do to prevent this?

Thank you very much,

Viktor

**Comment by MilosKozak** [comment]
there must be a 15 min distance between remote boluses
