### ISSUE TITLE
Remote Bolus different phone numbers not working

### ISSUE THREAD

**Issue by viktor200** [MilosKozak/AndroidAPS#1083]
Hi everyone,

I recently started again to use AndroidAPS for my 6-year-old son.

I put in the AndroidAPS 3 different phone numbers (my wife, grandmother and me), which are allowed to give the remote bolus.

Mostly it works only from one the numbers.

Is there any way to solve this issue?

Thank you very much,

Viktor

**Comment by MilosKozak** [comment]
it should work with all of them. if not reopen this issue with log files from phone controlling pump
