### ISSUE TITLE
Android Studio build error

### ISSUE THREAD

**Issue by oschumac** [MilosKozak/AndroidAPS#1088]
Hi,

within a new installation of Android Studio, i got this . 

**Could not find runtime.aar (android.arch.lifecycle:runtime:1.0.3).
Searched in the following locations:
    https://jcenter.bintray.com/android/arch/lifecycle/runtime/1.0.3/runtime-1.0.3.aar
**

and yes this is deprecated and not longer available.

Only if i try to compile master branch. if i try for excample aaps20_RC4 everything whent fine.
I tried to google this android studio build issue, but looks a like nobody has an solution.

CU Oliver

**Comment by triplem** [comment]
Hm, probably you could try:

https://stackoverflow.com/questions/50584437/android-studio-3-1-2-failed-to-resolve-runtime
