### ISSUE TITLE
AAPS ignores carb entries intermitently

### ISSUE THREAD

**Issue by vickirouse** [MilosKozak/AndroidAPS#1094]
Reporting bugs
--------------
-Today after lunch AAPS "forgot" my COB. I bolused for 37g carbs using the bolus wizard in AAPS at 13.41. At 14.27 I set a temporary target for activity, and before that also added an extra 7g carbs via careportal, backdated to 14.07. A short while later I saw that the COB were 0 & AAPS was running a zero TBR. I posted a picture in the facebook group. I checked in treatments & the TBR time was in red text, so I deleted it & the carbs returned. 
On 4th June at 09.37 I entered breakfast carbs and insulin via bolus wizard. On this occasion, AAPS did not show the carbs in the treatments tab, instead it showed 2 boluses, so AAPS was thinking I had twice the insulin but zero carbs. The DANA RS pump only showed 1 bolus in it's history. This has occurred before a few times, maybe 6 since I started closed looping at the end April. On the occasion on 4th June, I had not recently done a profile switch or set any temp target
- I'm using v1.58 with DANA S & dexcom g5
- 
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2087044/AndroidAPS.log)

**Comment by MilosKozak** [comment]
resolved in RC
