### ISSUE TITLE
Export Settings from Dev to RC4/RC3: Deviation Slope

### ISSUE THREAD

**Issue by MarieT1D** [MilosKozak/AndroidAPS#1096]
If "Deviation Slope" is enabled in Dev Version and the settings are exported and imported to RC4/RC3 (I don't know about RC1/RC2), Deviation Slope will also appear in RC4/RC3 without being able to remove it unless you switch back to Dev and turn it off there.

**Comment by AdrianLxM** [comment]
Danke
