### ISSUE TITLE
RC4 / Combo

### ISSUE THREAD

**Issue by bboi61** [MilosKozak/AndroidAPS#1098]
Would it be possible to visualize an alarm (low) IE or reservoir that has already been confirmed on the pump in AndroidAPS?
TBR cancellation, I confirm several times a day directly at the pump. But three warning was empty reservoir.
Or a display Battery and Reservoir on Home Screen?

**Comment by jotomo** [comment]
@bboi61 
> TBR cancellation, I confirm several times a day directly at the pump

Given you keep pump and phone in range, you should see "TBR cancelled" messages only once every couple of days, which should be automatically confirmed most of the time. If you see it as frequently as you describe, it seems the phone's BT isn't very well suited for the Combo.

**Comment by bboi61** [comment]
I will recompile ruffy and look again.
Phone: Samsung Galaxy S4 mini
Many Thanks

**Comment by schmitzn** [comment]
@bboi61 I'm using combo with Galaxy S4 mini, too. Without having any trouble. So basically it should work with this phone.

@gregorybel Ideas and suggestions go here #1097

**Comment by bboi61** [comment]
@schmitzn Vielen Dank. Mein S4 mini funktioniert soweit auch ohne Probleme. Ich hatte mir dummerweise angewöhnt den "TBR Abbruch" ungesehen an der Combo zu bestätigen, wohl wissend das es hierbei auch noch andere Hinweise/Warnungen geben könnte. So hatte ich dann ein Reservoir Low und empty auch bestätigt und musste dann schnellstens Heim fahren. Mein Fehler!!!
Ich würde mich sehr freuen die Reservoir Menge, nach Vorschlag savek-cc auf dem Home Screen zu sehen. Mir ist die Plazierung bisher nicht geglückt.
@gregorybel Battery, wäre natürlich auch noch toll.

**Comment by jotomo** [comment]
Fixed via https://github.com/MilosKozak/AndroidAPS/pull/1107, battery and reservoir indicators are no on my screen.

**Comment by parapenT1sta** [comment]
@MilosKozak I think this Issue can be closed or not?

**Comment by bboi61** [comment]
Yes

**Comment by parapenT1sta** [comment]
@bboi61
Close the ticket if the issue is fixed.
