### ISSUE TITLE
Warn the user before a basal profile is written to the pump for the first time

### ISSUE THREAD

**Issue by jamorham** [MilosKozak/AndroidAPS#1103]
A new user can find that the basal profile of their pump gets overwritten without clear warning in the software that this is going to happen. 

I find this a bit of a dramatic feature and inconsistent with the step-by-step objectives to walk a user slowly in to understanding the app from a safety point of view. For an inept user it is very easy to significantly change insulin dosing via the basal rate in a way which doesn't stop when the app is uninstalled.

In an example situation, a user installs the application, goes through the setup wizard, creates a lazy inaccurate profile for testing using the virtual pump. Later they switch to the real pump to see if communication works at which point the basal profile of the pump is overwritten.

A notification in the overview section appears after this has happened, but by then it has already occurred. 

In some circumstances a user may have tuned their basal profile on their pump through small adjustments over time without noting the details and then that data is lost when it is overwritten by AAPS. More significantly it could happen to a new user who then uninstalls the software and potentially does not realize that the active basal profile on the pump has been changed.

Suggested solution:

Before an operation is done within the app which could cause the pump settings to be updated, the user should receive a yes/no dialog to approve the action. 

Whether this is when the profile is configured or ideally before the data is written to the pump I am not sure the best solution within AAPS architecture, but in english I would suggest a message something like the following:

## ATTENTION:

**AndroidAPS intends to manage the basal profile of any connected pump.**

**The basal profile you have defined within AndroidAPS will be sent to a connected pump and immediately become active. This will overwrite whatever current basal profile is there.  The new daily basal rate is XX.XX U**

**Please confirm that you wish this to happen and understand the consequences.**

**YES / NO**

**Comment by jamorham** [comment]
@AdrianLxM as discussed on gitter

**Comment by MilosKozak** [comment]
👍 thx

**Comment by AdrianLxM** [comment]
Solution here: https://github.com/MilosKozak/AndroidAPS/pull/1168
