### ISSUE TITLE
AAPS RC3:  comma / point problems 

### ISSUE THREAD

**Issue by papalendro** [MilosKozak/AndroidAPS#1105]
Hi,

if had in RC Open loop a big problem with a writing a point or a comma. 

in the careportal i wrote an meal bolus with comma 9,7ie but the system took it as 97ie for the next calculations. 
in the careportal or at the home site the system don´t take comma´s, it take only piont´s    

at the lokal profil the system want a comma and at the most automatic calculations the system write comma´s 

could it not be better that the system accept both or 
we have in the console only comma´s.

This should minimise the mistakes  

Thanks

Alexandros

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/52830f620f3b60d2b8f3b0e74dc6aabae4f76402
