### ISSUE TITLE
AAPS RC 4 / Android Wear / Confirm buttons are not working

### ISSUE THREAD

**Issue by BastianBickelhaupt** [MilosKozak/AndroidAPS#1106]
With the RC4 installation of the wear app, the confirmation icon does not perform any action. It just closes the app without doing anything.

Also when you open Status -> Loop or other options, the app is just closed without showing anything.

I am using the Huawei Watch (Version 1). But also other loopers have these kind of issue. 

Let me know if you need more information.

**Comment by tanja3981** [comment]
Same here with Sony Smartwatch 3!
