### ISSUE TITLE
Feature or enhancement for wear Wizard

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#1112]
Using aaps 2.0 RC4, I find really cool now that the wizard takes all parameters into account.

One idea as enhancement: could be nice if we could get a short summarry how bolus has been calculated, for example:
Carbs: 10g
Bolus: 4U
0,4 (BG) + 0,1 (15T) + 1 (COB) + 1,5 (Bo IOB) + 1 (Ba IOB)

**Comment by LongboatAline** [comment]
I thought the last column in the bolus wizard did just that?
Image from an older Version, but compared to the current version, I find the Display unchanged 

![screenshot_20180601-220838](https://user-images.githubusercontent.com/35570803/41559946-e7248792-7345-11e8-8cc6-bbdf8bfee358.png)

**Comment by gregorybel** [comment]
@LongboatAline thanks for remark, I referred to the wear Wizard 😀 my mistake, forgot to click save when editing title.

**Comment by AdrianLxM** [comment]
Wear wizard does exactly that. Always did, still does. Even updated for new factors taken into account.

**Comment by AdrianLxM** [comment]
![15294178522531077199630712759994](https://user-images.githubusercontent.com/9692866/41603001-55b49c74-73dc-11e8-8581-7f831a5dc5f2.jpg)

**Comment by gregorybel** [comment]
cool! sorry then, I simply close it.

**Comment by gregorybel** [comment]
so actually there is in fact an issue on my watch, see screenshot:

![screen](https://user-images.githubusercontent.com/24234385/41682123-19c5cfd4-74d7-11e8-9d38-4c86051d20ea.png)

One line is missing.

**Comment by jotomo** [comment]
It's a wear 2.0 issue.

**Comment by gregorybel** [comment]
ok. but As far as I can see there are a lot of lost room: 
- carbs and bolus could be in same line
- separation line could be removed
- IC and ISF could be removed
- or simply a smaller size could be used

or what do you think?

**Comment by gregorybel** [comment]
can you point to me where code is so that I try by myself?

**Comment by AdrianLxM** [comment]
I see no advantange in putting things in one line.
Just klick the notification and it will expand and you can scroll.

In case you already have a 2.0 watch (not fully compatibel with AAPS yet but many things do work): The adaption would be to write an activity with two elements. One with a scroll-pane for the notification text and one to accept. That would be similar to the one's where you enter a bolus.

**Comment by AdrianLxM** [comment]
escalating to [2.0].
Not because of how the notification looks on wear 2.0 but because you can confirm a bolus with just one tap e.g. when trying to turn on the screen light.

**Comment by AdrianLxM** [comment]
Fixed in https://github.com/MilosKozak/AndroidAPS/pull/1163
