### ISSUE TITLE
Feature request: Merge additional features into the dexcom app

### ISSUE THREAD

**Issue by Arakon** [MilosKozak/AndroidAPS#1113]
Hi.
As you're probably aware, there is a patched, current version of the dexcom app available:
https://redd.it/8ja38m

It disables the phone model check and supports several other features, and is available for both the US and EU app.
It would be awesome if some sort of cooperation was possible to integrate those patches with the AndroidAPS compatible version, and/or vice versa. It would enable a lot more people to use the software.

**Comment by Arakon** [comment]
For me at least, it does. I need the Clarity diagrams for my diabetologist,

**Comment by jotomo** [comment]
Dexcom Share and Clarity aren't integrated? (xDrip can upload to Share).

**Comment by Oekonom2** [comment]
afaik no. Share is used to push to followers and Clarity for data analysis. I think these are 2 different servers

**Comment by Arakon** [comment]
They're seperate, I believe. Clarity only updates every 6 hours or so when using the app.
