### ISSUE TITLE
Watchface not updated

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#1114]
AAPS 2.0 RC4 as NSClient
Running xDrip Collector Service on Androud Wear 2.0 because of BT problems with miaomiao and Samsung.
Using NSClient

xDrip shows current BG.
The NSClient Watchface is not up to date until starting NSClient at the phone.
Then it's reading and updating.

No power optimation for NSClient

**Comment by MilosKozak** [comment]
@AdrianLxM do you understand

**Comment by hartlijn** [comment]
as far as I understood, @jroth-haj, the NSClient watchface (AndroidAPS watchface) is not an Application itself but a - let's say - mirror of the application that is running on the phone. Kill the app on the phone; the watchface will not get any updates anymore.

my suggested solution if you want the AndroidAPS watchface; start AndroidAPS on the phone. If you don't want double BG info on you phone you could de-activate the 'ongoing notification'.

**Comment by jroth-haj** [comment]
Yes, you're right.
I was thinking the app stays in Background like the AAPS Version of this App.
Thanks for support.
