### ISSUE TITLE
CounfigBuilder displays wrong profile plugin

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#1115]
![image](https://user-images.githubusercontent.com/11146458/41624140-0a04890e-7415-11e8-8949-8594f88140bd.png)
@TebbeUbben

**Comment by TebbeUbben** [comment]
Which method must be invoked to get the right plugins there?
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/ConfigBuilder/ConfigBuilderFragment.java#L123

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/ConfigBuilder/ConfigBuilderFragment.java#L248
you need to query enable status for specific type, not the default one

**Comment by TebbeUbben** [comment]
Can bei closed

**Comment by AdrianLxM** [comment]
Closing as to @TebbeUbben wish :)
Thanks.
