### ISSUE TITLE
Nightscout upload only at Wifi

### ISSUE THREAD

**Issue by Dave2526** [MilosKozak/AndroidAPS#1130]
When I set the nightscout upload only with wifi connection and I set a ssid the nightscout client will not work with the log entry "not allowed". When I set the ssid wrapped with "" then it works. Androidaps version rc4.

**Comment by triplem** [comment]
I will have a look on this one.

**Comment by MilosKozak** [comment]
solved in https://github.com/MilosKozak/AndroidAPS/commit/0d48cc8770e65d2963d129515aa94c52fe4c32c6
thanks
