### ISSUE TITLE
non-consistent singleton-pattern in DanaRPump

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#1145]
The DanaR pump has a singleton pattern that it only holds one instance and with `instance()` you can get that instance.

The method `reset()` does set the private instance reference to `null` so next time that `instance()` will be called, a new Object is generated.

Other components like  the `DanaRSService` that still hold a reference to the old object.

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/9a2df7b04cf847f12e068ae051a1a4dfff7364e1
