### ISSUE TITLE
Plugin descriptions to Wizard

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#1150]
@TebbeUbben

**Comment by TebbeUbben** [comment]
I never had a look at the setup wizard part, so I don't know what's the best way to add them.

**Comment by MilosKozak** [comment]
done in https://github.com/MilosKozak/AndroidAPS/commit/520f2e1518d88797d1a03a5811ee2a1df48a282e

**Comment by TebbeUbben** [comment]
I'd rather reuse the existing PluginViewHolder.
