### ISSUE TITLE
Wizard for extended bolus / multiwave bolus

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1151]
It is described as tips and tricks for the combo pump how to define extended bolus or multiwave bolus.

Why couldn't this be implementet as wizard. In part 2 I first have to calculate the percentage. Wouldn't this be possible to do that in a wizard an start the profile change automatically ?

Here are the tips and tricks for solving extended boluses:
Extended bolus, multiwave bolus
The OpenAPS algorithm does not support a parallel extended bolus or multiwave bolus. But a similar treatment can be achieved by the following alternatives:

Before eating, on the Actions tab in AndroidAPS set as a temporary Eating Soon goal with target glucose 80 for several hours. The duration should be based on the interval you would chosse for an extended bolus.
Then use the CALCULATOR to enter the full carbs of the meal, but do not directly apply the values ​​suggested by the bolus calculator. If a multiwave-like bolus is to be delivered, input the carbohydrate share as a bolus. Depending on the meal, the algorithm now has to deliver a very high temporary basal rate to counteract the increase in blood sugar. Here, the safety limitation of the basal rate (Max IE / h, Maximum basal IOB) should be very carefully experimented with and, if necessary, temporarily changed.
Temporary goal

**Part 2:**
Alternatively, on the Actions tab in AndoidAPS a profile change can be made with the duration of the delayed bolus and an increased percentage. There is no need for another profile (eg in Nightscout). The correct percentage can be calculated from the average basal rate over the selected period and the amount of insulin needed. Thus, a desired extended bolus of 4 IU for 4 hours at a basal rate of 0.5 IU / h would require a temporary basal rate of 300% .
Temporäre Basalrate

**Comment by AdrianLxM** [comment]
Hi, do you have a link to where it is described how to give extended bolus?

We should definitely remove that from the documentation as extended bolus does not fit the model of the closed loop and is not needed. (Extended carbs as input parameter is what you would use in the upcoming version.)

**Comment by thomasmenges** [comment]
Here is the link:

https://github.com/MilosKozak/AndroidAPS/wiki/Accu-Chek-Combo-Tipps-and-Tricks

Then is the upcoming version with extended carbs coming?
