### ISSUE TITLE
2nd graph: Numbers are incorrect

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1153]
Yesterdays updates introduces the following issue (look at the numbers at the left side of the graph):

![image](https://user-images.githubusercontent.com/12517693/41823209-8921306c-77fc-11e8-99e6-e3bd4da374ba.png)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/44cf82abdeeacebaeaa4ba94c86b36de40deb42f
