### ISSUE TITLE
SW: "File not found" on import settings due to missing storage permission

### ISSUE THREAD

**Issue by schmitzn** [MilosKozak/AndroidAPS#1158]
I had exported my settings and uninstalled AAPS. With the new installation, the import function in the setup wizard returned "file not found". Manually assigning the storage permission in the system settings solved the problem. I think the permission should be checked when clicking on "import settings".

**Comment by MilosKozak** [comment]
resolved inhttps://github.com/MilosKozak/AndroidAPS/commit/2b799d9f71a4449327fc509cece90281a97af046
