### ISSUE TITLE
[dev] Graph with additional information has wrong scaling

### ISSUE THREAD

**Issue by TebbeUbben** [MilosKozak/AndroidAPS#1166]
The lower chart at the overview seems to have the wrong scaling on the latest dev.

Some discoveries I made:
* Having only COB selected results in an empty graph
* Having IOB results in the scaling below:

![36284754_2154524701489081_7557160524006293504_n](https://user-images.githubusercontent.com/8694925/42049977-f7e904b2-7b07-11e8-9643-056a029aa434.png)

**Comment by swissalpine** [comment]
I can confirm that the following commit has fixed the described/shown issue:
https://github.com/MilosKozak/AndroidAPS/commit/44cf82abdeeacebaeaa4ba94c86b36de40deb42f
