### ISSUE TITLE
Loop not enacted

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#1169]
With 268dec0059d211c1148794d80c8801df9f0503d5 Loop won't be enacted automatically for me, reverting these changes solved the problem for me, but I don't know where exactly the problem is.
I am using xDrip+ with native mode, so it would have to be allowed to loop.
Setup: G5 native/AAPS/Galaxy S8 with security patch 1.june

@jotomo

**Comment by jotomo** [comment]
Does this also happen with NSClient paused?

**Comment by McHoffi** [comment]
Just tried and it worked with NSC paused

**Comment by AdrianLxM** [comment]
should be solved in latest dev
