### ISSUE TITLE
Deleting treatments doesn't effect COB

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1174]
I deleted a treatment of 42 g carbs and entered a new treatment of 48 g one minute later instead, followed by a treatment of 36 g.
COB wasn't effected by the deleted treatment and shows 126 g what I realised half an hour after the deletion! 
![image](https://user-images.githubusercontent.com/12517693/42129333-566ed8b6-7cc2-11e8-85e9-e1c44a8b4db0.png)
![image](https://user-images.githubusercontent.com/12517693/42129344-a3def09a-7cc2-11e8-899d-14079732c29b.png)

**Comment by MilosKozak** [comment]
unable to reproduce this issue. open this issue with log files if this happen again
