### ISSUE TITLE
[RC4] AndroidAPS crashes sometimes after clicking on OpenAPS MA

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1185]
I use AndroidAPS (beta candidate) to control my combo pump.

CGM is freestyle libre (GLIMP to read the BG).

The actual BG is directly shown in AndroidAPS after scanning via Glimp.

The overview page in AndroidAPS is shown correctly. 

If I want to know if APS creates a temporary bolus I switch to OPENAPS MA and sometimes (not always) the app crashes and has to be startet again (Bluetooth connection every time). Now the last actual BG is not shown anymore and APS can't do anything.

Has anyone else noticed a similar behavior? I couldn't notice this behavior in "MASTER".

![androisaps](https://user-images.githubusercontent.com/37514390/42277488-cf94b648-7f97-11e8-9f94-c57de8f5593c.jpg)

**Comment by AdrianLxM** [comment]
Should already be fixed for in the next RC.

**Comment by AdrianLxM** [comment]
Please reopen if it reappears in RC5 (that we hopefully have in the next week's)
