### ISSUE TITLE
INSIGHT: Bolus calculator - can't add + correction by click on plus symbol

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#1196]
When using Insight plugin, can't use "+" icon in calculator for insulin correction. When i "click" + , message "Bolus constrains applied" is show. I can entry any number manual.
![img_1848](https://user-images.githubusercontent.com/16052233/42422543-90009728-82e8-11e8-9068-72a24a123f8c.JPG)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2173963/AndroidAPS.log)
Tested on version 2.0RC4 and 1.60e-dev (today builded (8.7.2018)

**Comment by JimmyFoks** [comment]
Similar problem with Insight and AAPS version 2.2.2. Unable to add over plus button - and manually entered correction +0.02 - +0.04. Higher values (0.05+) can be entered.

**Comment by MilosKozak** [comment]
@TebbeUbben
