### ISSUE TITLE
On objectiv 2 (Open loop, TBR confirmed by user) aaps offered SMB

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#1197]
On objecti 2 , when i confirm some TBR , in one moment aaps offered SMB (screen shot included). I don't now how replicate. This is why the screenshot is in Czech. Algoritmus si selected MA.  Version is 1.60e-dev today (8.7.2018) build.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2173974/AndroidAPS.log)
![img_1843](https://user-images.githubusercontent.com/16052233/42422688-0f4d2274-82eb-11e8-868e-94523a676a95.JPG)
![img_1844](https://user-images.githubusercontent.com/16052233/42422689-0f6784b6-82eb-11e8-9789-50e8cd532d1c.JPG)

**Comment by MilosKozak** [comment]
it's a bug in insight plugin https://github.com/MilosKozak/AndroidAPS/pull/1213
