### ISSUE TITLE
Build problem - Could not get unknown property 'packageForR' 

### ISSUE THREAD

**Issue by sarsonj** [MilosKozak/AndroidAPS#1198]
Hi,

I am having problem with building master branch using clean install of Android Studio 3.1.3 (both Windows and Mac). During build I got Gradle error:

Could not get unknown property 'packageForR' for task ':app:processFullDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.

Any idea where could be the problem?

Thanks,

Jindrich

**Comment by maskac** [comment]
Don't update gradle.

**Comment by opal06** [comment]
I am facing the same problem. Which Android Studio version should I use?

**Comment by MilosKozak** [comment]
latest. when compiling master do not let studio update gradle
