### ISSUE TITLE
EventNewSMS.java in wrong directory

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#120]
EventNewSMS.java is in package info.nightscout.androidaps.plugins.SmsCommunicator.events but in directory "Events" (with capital E)
https://github.com/MilosKozak/AndroidAPS/blob/master/app/src/main/java/info/nightscout/androidaps/plugins/SmsCommunicator/Events/EventNewSMS.java#L1

The directory seems duplicated as it also exists with a small "e".

**Comment by MilosKozak** [comment]
i see it correctly .... probably i did the mistake trying to change the capital in the past ....
make it troubles for you?
the onlu solution i found is to move it to another directory

**Comment by AdrianLxM** [comment]
Github has it as two: https://github.com/MilosKozak/AndroidAPS/tree/master/app/src/main/java/info/nightscout/androidaps/plugins/SmsCommunicator

It hasn't caused any problems so far for me, no.
As far as I remember: Windows sees them as the same; Mac/Linux as different.

Newer versions of Android/JDK/AndroidStudio seem to be quite forgiving now. Kapital letter packages alone caused us trouble on older (4.4 and older) phones with NightWatch.
