### ISSUE TITLE
Temporary Target in Objectives

### ISSUE THREAD

**Issue by MarieT1D** [MilosKozak/AndroidAPS#1200]
What do you think about adding Temporary Targets to the objectives (2 or 3) in AAPS 2.0 ?
I think, some people, might not know how useful they are, so I think it might be good, to at least mention them in the objectives so that they think about them or look them up in the wiki

**Comment by AdrianLxM** [comment]
With SMB I think they are not only useful but also sometimes mandatory to prevent SMB when recovering from hypoglycemia.

Would you be willing to add that to the Text?

**Comment by MarieT1D** [comment]
Sure. I'll try to. Do you think: 'Run in Open Loop mode for a few days, and manually enact lots of temp basals. Use and set up temporary and default temporary targets (to prevent wrong temp basals for predicted events like activity or hypo carbs)' (Objective 2) is ok? Is the long version with the text in  the () to much or should I add, too

**Comment by AdrianLxM** [comment]
I would switch the order to "Set up and use...".
Instead of the long text in () I would add thed two examples "(e.g. for activity or hypo treatment carbs)".

**Comment by MarieT1D** [comment]
Sounds good

**Comment by MarieT1D** [comment]
I hope it worked, so exciting to make a first pull request. I hope it was the right way to do it
