### ISSUE TITLE
Extended Bolus not working in 2.0-RC4

### ISSUE THREAD

**Issue by yeagerm** [MilosKozak/AndroidAPS#1206]
I'm using RC4, openloop, OpenAPS AMA. When I setup an extended bolus in the Actions tab it shows up correctly in that tab, then will disappear (cancel?) after about 5 seconds. It was working OK in RC3.

**Comment by MilosKozak** [comment]
what pump driver?

**Comment by yeagerm** [comment]
I am Openloop so “Virtual pump”
Thanks

**Comment by yeagerm** [comment]
Still a problem in RC5

**Comment by MilosKozak** [comment]
i'm unable to reproduce this issue. we need log files

**Comment by yeagerm** [comment]
Log file. Anything else please let me know.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2243204/AndroidAPS.log)

**Comment by MilosKozak** [comment]
the record get messed up by NS. i'd try NS restart

**Comment by yeagerm** [comment]
I did a “Restart all Dynos” in my Heroku app, rebooted the phone, still have the problem.

**Comment by yeagerm** [comment]
It seemed to be problem of Xdrip+ synching with NS and downloading treatments, then uploading again. Once I turned off everything in Xdrip+ other than uploading blood glucose readings the problem is solved. Thanks
