### ISSUE TITLE
danaRv2 carbs not uploaded to NS

### ISSUE THREAD

**Issue by PoweRGbg** [MilosKozak/AndroidAPS#1217]
After using the Wizard at 13:04 carbs are available in pump history, but not uploaded to NS and don't show in treatments. AAPS is 1.58 
[AndroidAPS._2018-07-15_15-42-28_.txt](https://github.com/MilosKozak/AndroidAPS/files/2195766/AndroidAPS._2018-07-15_15-42-28_.txt)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/97d9f7866cefcb8da8bdd591a85ab5d12c0f7b80
