### ISSUE TITLE
Parallel SMB visually overrides manual bolus

### ISSUE THREAD

**Issue by T-o-b-i-a-s** [MilosKozak/AndroidAPS#1218]
I am using AndroidAPS 2.0 RC4
Build ace89f7d8
With Combo Plugin

When submitting a bolus of approx 4 insulin units using the calculator, I wondered why the popup with the progress bar indicating the delivery of the bolus only showed a delivery of 0.1 units and then disappeared.

When checking the Combo Tab, it showed that the delivery of the 4 iu bolus was still in the queue and I could feel by the pumps vibration that the bolus was delivered. However, the progress bar did not appear again.
Checking the SMB tab revealed, that an SMB of 0.1 had just been submitted with the last arrival of a blood glucose value.

I guess the progression bar popup somehow showed the SMB delivery an the bolus delivery was not indicated.
While this is not a critical issue, as insulin dosage was correct, it can confuse users and maybe make them re-deliver the larger bolus, as they only saw the super micro bolus was delivered.

Unfortunately, I do not have any logs.

**Comment by swissalpine** [comment]
I can confirm this behaviour. Saw this yesterday too.

**Comment by jotomo** [comment]
Proposed fix: #1228. Feel free to test. Issuing a bolus while pump is connecting for an SMB should trigger the behaviour, where the SMB takes over the progress dialog of the bolus. With the fix, the progress dialog should stay open and wait until SMB completes and then show progress normally for the bolus.

**Comment by T-o-b-i-a-s** [comment]
Hello @jotomo, thank you for the fast fix. It will be a little hard to test, because you must be fast enough to submit your manual bolus while the SMB is being prepared. Even with the slow combo, this is hard. Is it possible to somehow trigger an SMB or predict it will occur soon?
If you have successfully tested your fix with the virtual pump, I am happy to close it from my side.
