### ISSUE TITLE
Graph not individually scrollable in history browser

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#1220]
The slider at the bottom of the history browser unfortunately has no effect. Regardless of the chosen time range (6,12,18 hours) and the position of the slider the graph starts at midnight.

I expected to be able to move the graph along the time axis.

Version: 2.0-rc4

**Comment by MilosKozak** [comment]
it's still not implemented. removed for now

**Comment by wootmasterslick** [comment]
Is this scheduled for inplementation?
