### ISSUE TITLE
Build issue: `app-full-release-RC4.apk` not appearing in proper directory

### ISSUE THREAD

**Issue by yeagerm** [MilosKozak/AndroidAPS#1222]
After building a "full-release" with Android Studio, there is only a popup link to the "wear-release". However, the full-release can be found in `AndroidAPS-aaps20_rc4/app/full/release/app-full-release-RC4.apk` which is different from `AndroidAPS-aaps20_rc4/app/release/wear-release.apk` .  So the build for full-release probably has to be fixed to be in `/app/release/` instead of `/app/full/release/`
![image](https://user-images.githubusercontent.com/3998204/42791687-e018d862-893f-11e8-8fc0-e4b2b6c71981.png)

**Comment by AdrianLxM** [comment]
Could you please do a PR directly to the documentation. You can find it here: http://en.androidaps.org

**Comment by yeagerm** [comment]
No I think myself and at least one other get confused when the build popup link does not show the full-build only the wear-build. There is a bug in the gradle build I think.
