### ISSUE TITLE
Changed basal local profile not used in OPENAPS SMB until AAPS is restarted

### ISSUE THREAD

**Issue by bertroode** [MilosKozak/AndroidAPS#1233]
After changing the basal volume in the local profile and activating the adapted  profile, the new total daily basal is shown on the overview screen. However OPENAPS SMB does not use the new values until you restart AAPS. 
Is this a small bug or do I do something wrong?

Running on RC4

**Comment by MilosKozak** [comment]
review it on RC 5.1 pls

**Comment by MilosKozak** [comment]
open it again with log file included if this reappear
