### ISSUE TITLE
SMB 0.0

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#1234]
In treatments tab there are shown SMBs with 0.0, also in nightscout.
Using DanaR with Galaxy S8 and testing "last-2.0-something-stuff-update1" e6baf3ff4
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2208936/AndroidAPS.log)
![screenshot_20180719-095930_androidaps](https://user-images.githubusercontent.com/24695277/42929776-56b1595c-8b3b-11e8-9797-b56cbf2a2bbe.jpg)

Also autosens isn't working I will try reverting the fix for oref1 autosens, and see if it will work again with weightedaverage.

**Comment by MilosKozak** [comment]
there is more looging added now. please reopen if this appear again

**Comment by McHoffi** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2300622/AndroidAPS.log)
Happened again, at 21:59 and 20:34.
