### ISSUE TITLE
RC5 - Loop alway deactivated

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1240]
After installing      the new app   app-pumpcontrol-release_2.0rc5.apk     I have the problem that looping is deactivated. (I'm using the combo pump). With RC4 everything was OK.
There can I start looping ?

That looping is deactivated is always shown on the watchface and on the app the button loop is missing

**Comment by jotomo** [comment]
You need to compile the APK yourself, like you did with RC4. Pre-built APKs are not enabled for looping.

**Comment by thomasmenges** [comment]
Thanks,
I did so and now it's working
