### ISSUE TITLE
[RC5] Update issues from NS profile

### ISSUE THREAD

**Issue by JustinWalkerMDPL** [MilosKozak/AndroidAPS#1247]
RC5 maybe found small bug? Thanks to all developers for great effort and hard work. I’m currently running a NS profile @ 130% - due to mild mid-winter (NZ) cold/flu. Moderate insulin resistance… Following update to RC5/dev yesterday, I reset temp to ND profile 120% (getting over resistance) needed to avoid repeated lower BG’s… All good so far with RC5. However following disconnect from pump for shower (long press LOOP, disconnect from pump for 15min) @ conclusion the RC5 resumed my previous 130% tempo rates? I suspect that maybe it pulls rate from previous hour or at midnight? I expected it to resume the 120% set rate?
BTW - now sittng at Airport - soon to test time travel forward 4 hrs :-)

**Comment by MilosKozak** [comment]
provide log files if this bug appear again pls. closing for now
