### ISSUE TITLE
RC5 - time shift

### ISSUE THREAD

**Issue by JustinWalkerMDPL** [MilosKozak/AndroidAPS#1248]
hey crew,  Moving backward in time is not yet correct?  I've just flown AKL - Tokyo - backward about 3hrs.  Upon arrival I went into Engineer mode in DANA - deleted history completely.  Then turned phone off airplane mode.  Upon connection to network - AAPS requested a manual change to pump time, which I completed.  Then I log into NightScout and delete all events in future.  
About 30minutes later I bolused 6units with carbs.  However 15minutes later IOB is showing in AAPS as -0.18u?   Even following small suspension - following 6u IOB should be at least 5units?

**Comment by MilosKozak** [comment]
@JustinWalkerMDPL was the treatment recorded in AAPS?

**Comment by JustinWalkerMDPL** [comment]
Hey team,

Upon arrival into Tokyo - I leave the phone in flight mode.  I enter the engineering mode in DANA - delete history.  Then turn flight mode off.  About 2 minutes the phone automatically connects to cell network and updates to new time zone.  I then restart phone - upon opening AAPS - it advises that the time shift is greater than 1.5hr - please adjust manually on pump.  Upon completion - the phone and pump sync - however there is no real IOB data until after 4 hrs (the period of time that the zone moved backwards).
I sent Adrian some screen images of AAPS - displaying -0.6u IOB.  As soon as the 4hr period of time was complete - AAPS suddenly displayed about 10units IOB - even though only small SMB's and 6unit bolus maybe 1 hr earlier.  10u was accurate/close enough - its simply very unusual that it suddenly appears when working after the period of time shift?

I'm feeling quite relived I'm not Marty McFly or Dr Emmett (Doc) Brown.  Time shift back to 1955 would be a long wait for AAPS to effectively work again :-) 

Regards,
Justin



On Jul 23, 2018, at 10:11 PM, AdrianLxM <notifications@github.com> wrote:

@MilosKozak could that be this? dd687fb
As the internal time depends on unix time it is unlikely. It might still be that for some reason there is a jump in the internal time of the phone and as we store the date when we last read the history, it will only "read back to a time in the future"?
@JustinWalkerMDPL, thanks! Did you set the time of the phone or change the time zone/location?

**Comment by MilosKozak** [comment]
I did following test right now:
* **phone switched for manual time zone change**

now i did "virtual" travel 4h forward

* turned off pump
* changed timezone on phone
* turned off phone, on pump
* cleared history
* turned on phone
* let phone connect to the pump and got a warning about too large  time change (just to prove it works)
* changed time in pump

now pump connected well. IOB was correct all time.
i added more boluses and carbs
and travelled back by 4h

* turned pump off
* changed timezone on phone
* turned off phone, on pump
* cleared history
* turned on phone
* got a warning ontime diff
* changed time on pump
* AAPS resynced time to match seconds too

IOB, COB perfect all the time

what could be wrong with your steps? maybe phone and pump connected in middle of time until you changed everything. try to repeat my steps

**Comment by MilosKozak** [comment]
i'm not sure if you could make SOOIL add timezone support but maybe only command for clearing APS history in pump would allow automate lot of things

**Comment by MilosKozak** [comment]
@JustinWalkerMDPL how about your test?

**Comment by JustinWalkerMDPL** [comment]
Hey team,

Sorry - due to Tropical cyclone off coast of Shanghai - my flight changed to Tokyo (no time backwards from Korea).

Next test I can help with is Sunday after next (19th August), traveling from NZ - Buenos Aires (17hrs backwards).

Kind regards 
Justin
