### ISSUE TITLE
Do not allow two mobile phones (two AndroidAPS apps) runing in parallel

### ISSUE THREAD

**Issue by StefanGermany** [MilosKozak/AndroidAPS#1250]
I have set up a new mobile phone,  installing AndroidAPS and Dexcom app. Copying the AndrodAPSPrefernces from the old to the new mobile phone. Although Bluetooth connection for the DANA RS  pump was deactivated the AndroidAPS of the new mobile phone started to work in parallel to the existing mobile phone. E.g. bolus from two different mobile phones to the same DANA RS pumps was possible.
I suggest to set a flag that only one AndroidAPS app can work towards the insulin pump. If two are working then e.g. a warning message in AnroidAPS should appear.
There could be a contradiction because the wear(s) can operate the pump in parallel?
System: 
Master 1.58
old Phone: Sony Xperia Z3 compact, D5803, Android 6.01
new phone: Sony Xperia XZ1 compact, G8441, Android 8.0.0

**Comment by AdrianLxM** [comment]
In order to delete any previously paired phone you can enter the password setting on the pump and simply change the password.
