### ISSUE TITLE
[RC5.1] Bolus delivered screen keeps hanging

### ISSUE THREAD

**Issue by tanja3981** [MilosKozak/AndroidAPS#1266]
After delivering a bolus from action menu, the progress bar keeps hanging (> 30 minutes)
Returning to any other AAPS screen wasn't possible. Only killing the app and restarting it fixed it.

Version: RC 5.1

Screenshots from a couple of days ago:
![screenshot_20180713-143454](https://user-images.githubusercontent.com/7403966/43341596-4a394d78-91e0-11e8-8872-fdce641d6d01.png)

Attached the log file from the time the bolus was delivered until I killed/started the app. If anything else is helpful, let me know.
[HangingBolus.log](https://github.com/MilosKozak/AndroidAPS/files/2236998/HangingBolus.log)

**Comment by tanja3981** [comment]
Trying to reproduce this issue with more logging info. :-/

**Comment by tanja3981** [comment]
This problem didn't happen again since newly compiled version - maybe the additional logging statements changed timing issues?

**Comment by MilosKozak** [comment]
added more detailed logging. reopen if needed
https://github.com/MilosKozak/AndroidAPS/commit/8cc7fb03d122de6c6c0f3bbe9272d04d13200858
