### ISSUE TITLE
Canceling temp target from NSClient doesn't cancel the Master

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1268]
If a temp target is set, Master and NSClient see this target at the top right corner. If "long-press" + Abort on masrer, the temp target cancels and updates the NSClient one (as expected). This does not work the other way around. Cancelling using the NSClient, the new target range updates on the NSClient, but the Master still uses the old temp target..

**Comment by MilosKozak** [comment]
do you see the event synced to master on treatments tab?

**Comment by Mackwe** [comment]
I believe so, yes. "Received 1 treatment ".

**Comment by MilosKozak** [comment]
could you upload log from master from that time?

**Comment by Mackwe** [comment]
It guess this is the switches:
-----------------------
13:00:06.649 [main] DEBUG [DataReceiver.onReceive():19]: onReceive Intent {
act=info.nightscout.client.NEW_TREATMENT flg=0x20 (has extras) }
13:00:06.714 [IntentService[DataService]] DEBUG
[DataService.onHandleIntent():69]: onHandleIntent Bundle{ treatments =>
[{"_id":"5b5c4cb37bc2fd00133c0a0e","eventType":"Temporary
Target","duration":0,"targetBottom":0,"targetTop":0,"created_at":"2018-07-28T11:00:04Z","units":"mmol","enteredBy":"AndroidAPS","NSCLIENT_ID":1532775604271,"mills":1532775604000,"mgdl":163}];
delta => true; android.support.content.wakelockid => 2084; }Bundle
13:00:06.715 [IntentService[DataService]] DEBUG
[DataService.handleNewDataFromNSClient():350]: Got intent:
info.nightscout.client.NEW_TREATMENT
13:00:06.720 [IntentService[DataService]] ERROR
[DatabaseHelper.createTemptargetFromJsonIfNotExists():679]: Unhandled
exception
org.json.JSONException: No value for reason
    at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
    at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
    at
info.nightscout.androidaps.db.DatabaseHelper.createTemptargetFromJsonIfNotExists(DatabaseHelper.java:674)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.handleTreatmentFromNS(DataService.java:561)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.handleNewDataFromNSClient(DataService.java:451)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.onHandleIntent(DataService.java:173)
~[na:0.0]
    at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:105) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
    at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
13:00:06.723 [IntentService[DataService]] DEBUG
[DataService.onHandleIntent():179]: onHandleIntent exit Intent {
act=info.nightscout.client.NEW_TREATMENT
cmp=info.nightscout.androidaps/.Services.DataService (has extras) }
13:00:30.946 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: DATA Data packet #154 delta
13:00:30.978 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: DATA received 1 treatments
13:00:30.981 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: LAST 2018-07-28 13:00
13:00:31.033 [main] DEBUG [DataReceiver.onReceive():19]: onReceive Intent {
act=info.nightscout.client.NEW_TREATMENT flg=0x20 (has extras) }
13:00:31.096 [IntentService[DataService]] DEBUG
[DataService.onHandleIntent():69]: onHandleIntent Bundle{ treatments =>
[{"_id":"5b5c4ccc7bc2fd00133c0a0f","eventType":"Temporary
Target","duration":10,"reason":"Manuell","targetBottom":5.1,"targetTop":5.1,"created_at":"2018-07-28T11:00:19Z","units":"mmol","enteredBy":"AndroidAPS","NSCLIENT_ID":1532775627093,"mills":1532775619000,"mgdl":163}];
delta => true; android.support.content.wakelockid => 2085; }Bundle
13:00:31.097 [IntentService[DataService]] DEBUG
[DataService.handleNewDataFromNSClient():350]: Got intent:
info.nightscout.client.NEW_TREATMENT
13:00:31.107 [IntentService[DataService]] DEBUG
[DatabaseHelper.createOrUpdate():608]: TEMPTARGET: New record from:
NIGHTSCOUT TemporaryTarget{date=1532775619000date=2018-07-28 13:00,
isValid=true, duration=10, reason=Manuell, low=91.8, high=91.8}
13:00:31.108 [IntentService[DataService]] DEBUG
[DataService.onHandleIntent():179]: onHandleIntent exit Intent {
act=info.nightscout.client.NEW_TREATMENT
cmp=info.nightscout.androidaps/.Services.DataService (has extras) }
13:00:31.634 [EventThread] DEBUG [NSClientPlugin.onStatusEvent():158]: PING
received
13:00:32.108 [pool-3-thread-1] DEBUG
[DatabaseHelper$2PostRunnable.run():636]: Firing EventTempTargetChange
13:00:45.238 [main] DEBUG [KeepAliveReceiver.onReceive():51]: KeepAlive
received
13:00:50.133 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: DATA Data packet #155 delta
13:00:50.167 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: DATA received 1 treatments
13:00:50.169 [NSClientServiceHandler] DEBUG
[NSClientPlugin.onStatusEvent():158]: LAST 2018-07-28 13:00
13:00:50.220 [main] DEBUG [DataReceiver.onReceive():19]: onReceive Intent {
act=info.nightscout.client.NEW_TREATMENT flg=0x20 (has extras) }
13:00:50.283 [IntentService[DataService]] DEBUG
[DataService.onHandleIntent():69]: onHandleIntent Bundle{ treatments =>
[{"_id":"5b5c4cde7bc2fd00133c0a10","eventType":"Temporary
Target","duration":0,"targetBottom":0,"targetTop":0,"created_at":"2018-07-28T11:00:47Z","units":"mmol","enteredBy":"AndroidAPS","NSCLIENT_ID":1532775647291,"mills":1532775647000,"mgdl":163}];
delta => true; android.support.content.wakelockid => 2086; }Bundle
13:00:50.284 [IntentService[DataService]] DEBUG
[DataService.handleNewDataFromNSClient():350]: Got intent:
info.nightscout.client.NEW_TREATMENT
13:00:50.286 [IntentService[DataService]] ERROR
[DatabaseHelper.createTemptargetFromJsonIfNotExists():679]: Unhandled
exception
org.json.JSONException: No value for reason
    at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
    at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
    at
info.nightscout.androidaps.db.DatabaseHelper.createTemptargetFromJsonIfNotExists(DatabaseHelper.java:674)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.handleTreatmentFromNS(DataService.java:561)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.handleNewDataFromNSClient(DataService.java:451)
~[na:0.0]
    at
info.nightscout.androidaps.Services.DataService.onHandleIntent(DataService.java:173)
~[na:0.0]
    at
android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:105) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
    at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
-----------------------

2018-07-28 13:44 GMT+02:00 Milos Kozak <notifications@github.com>:

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/22881e17a291ef2ad0e30b6386d96de5bdd0d72a

**Comment by mountrcg** [comment]
could be that there ist still some work regarduing this issue. I want to cancel TempTargets via IFTTT 
`{"enteredBy": "IFTTT", "eventType": "Temporary Target", "reason": "cancel", "duration": 0}`
and Nightscout. Also if I do it directly in Nightscout it won't get populated into AAPS.  However in Nighscout the target will revert to the standard. Population to AAPS & Xdrip+ etc. works fine with specific tempTargets.
