### ISSUE TITLE
Suggestion: make it possible to go back to previous objectives

### ISSUE THREAD

**Issue by Pallesauka** [MilosKozak/AndroidAPS#1269]
Im relatively new to AAPS and accidently accepted objective 4 while still open looping. With objective 4 the maxiob is hardcoded to 0 which stops the loop from suggesting correction TBR. It would be great if you could add a feature to reverse to a lower objective.

Luckily for me, I had a previous exported settings file on objective 3 that I could reload. However it would be really good to clarify both in the wiki and in the objectives tab in AAPS that:

NOTE: Open loop will not be possible during the course of objective 4. Starting this objective will disable open looping until the objective is completed.

In Swedish:
Notera: Det går inte att köra open loop under tiden mål 4 pågår. Genom att starta mål 4 upphör möjligheten till open loop tills dess att målet är slutfört.

**Comment by tanja3981** [comment]
Work started.

**Comment by MilosKozak** [comment]
thx @tanja3981

**Comment by tanja3981** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/1420
