### ISSUE TITLE
Carb absorption error

### ISSUE THREAD

**Issue by dalilith** [MilosKozak/AndroidAPS#1271]
Yesterday I was wondering why my carbs are longer active as they normally where. Meal absorption time was at 6h,i changed it to 4h but nothing happens. 
So i was asking Adrian if something changed in rc5, he said i should press exit and start again.
Before restart i had 20g cob in the overview display, after there where 3g cob. We talked about this between 22:50-22:55. I can't define it exactly because my screenshot function did not work.

I was using rc5 with smb always, uam and sensitivity oref1 plugin. 

[AndroidAPS._2018-07-28_22-52-38_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2238697/AndroidAPS._2018-07-28_22-52-38_.0.zip)
[AndroidAPS._2018-07-28_22-52-38_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/2238698/AndroidAPS._2018-07-28_22-52-38_.1.zip)

**Comment by MilosKozak** [comment]
your problem is permanently reconnecting NSClient which is causing calculation restart all the time
