### ISSUE TITLE
Probable bug switching DanaR(S)-based profile

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#1272]
AbstractDanaPlugin: on state change, a profile change is never done, since _newState_ is checked to be in two different states at the same time:
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/PumpDanaR/AbstractDanaRPlugin.java#L70
The DanaRSPlugin overrides the method and checks if _newState_ is _DISABLED_
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/PumpDanaRS/DanaRSPlugin.java#L129
However, the _onStateChange_ method is always called with _newState_ set to _ENABLED_, so the code doing the profile change never triggers in either class.

**Comment by tanja3981** [comment]
Agree. Shouldn't that be like this
`if (type == PluginType.PUMP && (newState == State.ENABLED || newState == State.DISABLED) && isProfileInterfaceEnabled)`

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/6544191c7824b041096f1c135248b4dd9503d7f4
