### ISSUE TITLE
loss of Iob and cob 

### ISSUE THREAD

**Issue by dalilith** [MilosKozak/AndroidAPS#1273]
Iob and cob are totally lost, both where zero. But i ate carbs and gave insulin. Waiting for smb i was wondering why aaps does nothing and looked at it. Restarting the app fixed this problem.
Screenshots and log below.
Version: rc5
Using smb with combo and ns at 10be.de
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2239070/AndroidAPS.log)
![screenshot_20180729-203532](https://user-images.githubusercontent.com/35224007/43369524-5dc8d688-9370-11e8-8076-41b954294478.png)
![screenshot_20180729-203727](https://user-images.githubusercontent.com/35224007/43369525-5f71e448-9370-11e8-8974-fd48a5c325c1.png)

**Comment by MilosKozak** [comment]
this happened because of constant connection/disconnection of nsclient. there was no time to calculate it to the end
