### ISSUE TITLE
AndroidAPS RC5-1: Save User Options in DanaR-Menu

### ISSUE THREAD

**Issue by Rutil** [MilosKozak/AndroidAPS#1277]
When  trying to save changes within the user-options-menu (e.g. warning Low reservoir)  the pump displays an error message and begins to beep. 

![image](https://user-images.githubusercontent.com/34680263/43442465-4e73cb6e-949e-11e8-8dfd-05ad059f8116.png)

![image](https://user-images.githubusercontent.com/34680263/43442482-5ba4b078-949e-11e8-8eef-5451b3ccb92c.png)

![image](https://user-images.githubusercontent.com/34680263/43442504-6d40b64c-949e-11e8-9f8c-8c702d55ff50.png)

**Comment by MilosKozak** [comment]
@RoumenGeorgiev can you try it?

**Comment by PoweRGbg** [comment]
I just had the time to look at this problem. My pump doesn't fail, but it's language is EN in user options and if I change it manually to DE it returns it to EN after saving settings. @Rutil  could you try with EN language on pump ?

**Comment by PoweRGbg** [comment]
@Rutil  I also noticed that you are using the DanaR pump plugin, isn't your pump firmware upgraded to v2 ? @MilosKozak

**Comment by Rutil** [comment]
@PoweRGbg I tried to use Englisch and a new battery,  but the same happend. Firmware of the pump is really 1.0.  The changes are written to the pump.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/1357

**Comment by MilosKozak** [comment]
now see it. that's newer pump than i have

**Comment by typ1-brods** [comment]
I have the same issue with German DanaR using AAPS RC7

**Comment by PoweRGbg** [comment]
@typ1-brods  Could you please provide screenshot of the DANAR tab?

**Comment by typ1-brods** [comment]
![screenshot_20180830-101450_androidaps](https://user-images.githubusercontent.com/32912987/44838908-aec61600-ac3d-11e8-8f18-30a326b56f3c.jpg)

**Comment by MilosKozak** [comment]
looks like we have to disable it for 03 too. do you send PR?

**Comment by PoweRGbg** [comment]
#1377
