### ISSUE TITLE
RC6 stopping after reading preferences

### ISSUE THREAD

**Issue by bertroode** [MilosKozak/AndroidAPS#1303]
Reinstalling RC6 brings you to a point that stored settings can be imported. It then reloads AndroidAPSPreferences. After import the system starts with the message"no profile set" and then starts cycling start/stop before you are able to activate the profile.

**Comment by MilosKozak** [comment]
could you describe steps how to simulate this issue?

**Comment by bertroode** [comment]
I have firgotten to mention that I am using the Insight pump. May be that is the reason why the system fails because I have read a post on gitter about it.

**Comment by MilosKozak** [comment]
did you have enginnering_mode enabled?

**Comment by bertroode** [comment]
No, I changed line 160 in the MainApp as the comment stated

**Comment by bertroode** [comment]
At first sight it seems to me that the cause of the problem might be the fact that the profile is not activated.
Before I can get to the activate button the system stops.

**Comment by bertroode** [comment]
I think this bug can be closed. After fixing the DatabaseHelper the problem is no longer there.
