### ISSUE TITLE
[RC 6.1] Showing 39COB directly after installing RC6.1 over master

### ISSUE THREAD

**Issue by Pallesauka** [MilosKozak/AndroidAPS#1309]
I just installed RC6.1 over my previous v.1.58 master. I exported settings from my previous setup and imported into RC6.1. I had no meals or added treatments for at least 4-5 hours and still AAPS is showing 39g COB. They seem to be distributed evenly over a long period of time.

![screenshot_20180806-224048_androidaps](https://user-images.githubusercontent.com/34350745/43740426-7a1fbbce-99cb-11e8-89c1-416e50dc0b4a.jpg)

![screenshot_20180806-224408_androidaps](https://user-images.githubusercontent.com/34350745/43740428-7cb4e9c2-99cb-11e8-8bb7-beac3d71914c.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2264045/AndroidAPS.log)

**Comment by MilosKozak** [comment]
did you review setup of sensitivity and APS plugins?

**Comment by Pallesauka** [comment]
What settings are you referring to?
Min_5min_carbimpact was 8, now 11.
What else can I check?

**Comment by MilosKozak** [comment]
do you have log files?

**Comment by MilosKozak** [comment]
from the picture the problem is in carbs absorption. is the problem still there?
