### ISSUE TITLE
[RC6.1] No COB added after meal bolus

### ISSUE THREAD

**Issue by Pallesauka** [MilosKozak/AndroidAPS#1310]
We used the bolus calculator to give a meal bolus for breakfast. 32g of carbs and 1.65u of insulin. The treatment is showing in the treatment tab, the insulin is registered in IOB but no COB is showing.

![screenshot_20180807-084436_androidaps](https://user-images.githubusercontent.com/34350745/43759418-75d9d8b6-9a1f-11e8-921a-eadea9121d2a.jpg)
![screenshot_20180807-084448_androidaps](https://user-images.githubusercontent.com/34350745/43759420-78287bea-9a1f-11e8-89b4-bfa0f62358a4.jpg)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2265348/AndroidAPS.log)

**Comment by MilosKozak** [comment]
display COB graph only

**Comment by Pallesauka** [comment]
@MilosKozak I cant now since the COB were added like 2h after the meal. COB are added in the above view.

**Comment by MilosKozak** [comment]
log files from that time?

**Comment by MilosKozak** [comment]
should be resolved in dev now
