### ISSUE TITLE
[Regression] Splitting bolus/carb treatment in NS leads to multiple records with same pumpID

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#1314]
- User enters a treatment with the calculator, thereby creating a treatment record with carbs, insulin and a pumpId
- Record is uploaded to NS
- User defers carb intake and to reflect that, uses NS-editing mode to split carbs and insulin, so carbs are recorded later
- This create two records out of one and NS apparently copies the pumpId to the newly created record
- AAPS retrieves the new record and adds it to the DB
- Pump driver, when next reading pump history, uses _TreatmentService.getRecordByPumpId_ to check if a record already exists in the DB.
- The method sees multiple records with the same pumpId in the DB, views this as an illegal state and throws a RuntimeException which is not caught, leading the app to crash

1) _TreatmentService.getRecordByPumpId_ should not throw a RuntimeException, this will break the app for users which use such a workflow: https://github.com/MilosKozak/AndroidAPS/pull/1313 (best-effort workaround for "2.0"). This change was introduced as part of an effort to temporarily work around id clashes.
2) Decide if any further action is needed, e.g. removing/not copying pumpId from incoming treatments from NS, only add if record is created by pump (if the consequences of such a change can be known).

Fabric: https://fabric.io/nightscout3/android/apps/info.nightscout.androidaps/issues/5b6754206007d59fcdea9bc6?time=last-twenty-four-hours

@LongBoatAline

**Comment by jotomo** [comment]
Issue was observed with a Combo, though Fabric also has stacktraces showing this issue with the Insight, which does history handling differently, so the root cause my different with the Insight.

**Comment by MilosKozak** [comment]
close?

**Comment by jotomo** [comment]
yup
