### ISSUE TITLE
[RC 6_1] long press on target overview screen malfunctions with mmol/L

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1315]
When selecting a Temporary Target via the Overview screen (long press on the blue button) if you are in mmol/L the preset Temp Targets are divided by 18 when selected. This is the same issue as was identified before but in a different place.

Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by jotomo** [comment]
If the user has set default values in the preferences (which override application defaults), the conversion from mmol/l to the internally used mg/dl was wrong.
I've created a patch you can test if you like: #1316
A workaround for RC6.1 is to enter the defaults in the preferences in mg/dl (and then revert back with RC7).

**Comment by roppenheimer** [comment]
Thanks for the update
