### ISSUE TITLE
[RC6.1 and dev] Notifications should be pushed to AndroidWear (also with ControlsFromWatch=OFF)

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#1318]
On RC6.1 notifications (with suggestions for basal changes) are not sent to Watch anymore. Works fine on production versions and RC4. Clear uninstall and reinstall gives same result.
Android Wear 2
Android 8.1

[UPDATE] Notifications to Android Wear should be pushed with setting CONTROLS FROM WATCH=OFF

**Comment by BastianBickelhaupt** [comment]
I can confirm this as well. I reinstalled AAPS and also restarted Phone and Watch. I have the Huawei Classic Watch.

**Comment by quizzmaster** [comment]
It works for me without any problems using Android 8.0, Wear OS 2 and RC6.1.

**Comment by hartlijn** [comment]
Thanks @quizzmaster; I decided to dive a little deeper into this issue...

it works, but you to enable CONTROLS FROM WATCH  (preferences >> Wear settings ) to receive notifications. In RC61 (and DEV as well)  you have to enable that setting.

In RC4, RC5.1 and master you receive notifications without this setting enabled, which makes more sense to me. The notifications are giving information and should be allowed to come through also with CONTROLS FROM WATCH off (since you are not controlling AAPS by showing notifications).

**Comment by BastianBickelhaupt** [comment]
@hartlijn I have that option enabled, but i still dont see the progress on my watch.

**Comment by AdrianLxM** [comment]
@hartlijn the notifications now are part of the controls. You can accept a treatment via the watch. If you have your pump connected to AAPS it will enact the TBR and (if already higher in the objecitves probably even) the SMB.

**Comment by hartlijn** [comment]
@AdrianLxM; yes nice features! *if* you have the pump connected. My pump is not compatible to connect, so I am open looping and always had the ControlFromWatch set to off.
anyway - I know how to receive the notifications now, so I don't bother much :)

@BastianBickelhaupt; I think your issue is not the same. My pump isn't connected so can't help that much further.

**Comment by BastianBickelhaupt** [comment]
@AdrianLxM Hi Adrian, do you have an idea why i dont see the progress notification anymore after upgrading to 6.1?

**Comment by quizzmaster** [comment]
@hartlijn  Yes, you are right. @AdrianLxM already mentioned why this happens. Maybe a check should be made if ControlsFromWatch is off and than just distribute the normal notification to the watch.

**Comment by AdrianLxM** [comment]
@quizzmaster are you working on this?

**Comment by quizzmaster** [comment]
Since I don't have much time right now and currently no access to my smartwatch it would be nice if someone could confirm that my PR really fixes this issue.

**Comment by hartlijn** [comment]
would love to @quizzmaster 
I am not an expert in AndroidStudio yet, but i just did a refresh project on my DEV project. Is it correct that your changes have date 2018-07-25 and 2018-07-26? Thought the changes had to be from today??
or is there a better way to check out your changes to my DEV or RC61 project

**Comment by quizzmaster** [comment]
If you aren't really familiar with how to check out pull requests, you can use my fork and checkout the fix1358 branch.

**Comment by hartlijn** [comment]
@quizzmaster thanks for solving the issue. It works now with your PR.

**Comment by hartlijn** [comment]
with CONTROLS FROM WATCH =  OFF, the notification vibrates very shortly compared to when it's on. So there is a difference. But the notification is there!

**Comment by quizzmaster** [comment]
I assume that android wear use a standard vibration pattern for the mirrored notifications. If controls from watch is on, the notification is generated on the watch itself and uses the defined vibration pattern copied from the one used for the phone app.
