### ISSUE TITLE
COB:N/A shown

### ISSUE THREAD

**Issue by kraftm1989** [MilosKozak/AndroidAPS#1330]
COB showns "N/A" in Homescreen, although its visible in the treatment-list. After restart of aaps IT hast been shown.
Noticed arround 11:24 in logfile.

Error in Logfile:
"11:23:58.150 [Thread-15033] ERROR [IobCobThread.run():201]: Unhandled exception
java.lang.NullPointerException: Attempt to read from field 'double info.nightscout.androidaps.plugins.IobCobCalculator.AutosensData.avgDeviation' on a null object reference
at info.nightscout.androidaps.plugins.IobCobCalculator.IobCobThread.run(IobCobThread.java:187) ~[na:0.0]"

[AndroidAPS._2018-08-12_11-30-13_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2281113/AndroidAPS._2018-08-12_11-30-13_.0.zip)

AndroidAPS 2.0 RC 6.1 - Build: NoGitSystemAvailable-2018.0.8.10.-9:36
Flavour: fulldebug
Nightscout-Version: 0.10.3.-master-20180805

![screenshot_20180812-112456 1](https://user-images.githubusercontent.com/41928733/44004093-d9f281b8-9e5c-11e8-840b-66c184856ec7.png)
![screenshot_20180812-112530 1](https://user-images.githubusercontent.com/41928733/44004097-e2946c78-9e5c-11e8-888a-e3b60aaf9b9d.png)
![screenshot_20180812-182109 1](https://user-images.githubusercontent.com/41928733/44004098-e6f6d166-9e5c-11e8-9d00-7e3a45852377.png)

Thanks a lot for your efforts!
Max

**Comment by MilosKozak** [comment]
what bg source do you use?

**Comment by kraftm1989** [comment]
MiaoMiao via xDrip+

**Comment by MilosKozak** [comment]
i hopefully fixed this in dev now. Update AAPS and reopen this issue if you see it again
