### ISSUE TITLE
entering canula change and insulin change at the same time in careportal makes the last entry overwrite the first

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#1331]
Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
Today 11:00 AM we entered an insulin change (with time performed yesterday 09:00 AM) in careportal of AAPS master branch
Upon check in Ns the change was registered
After this we entered canula change also performed yesterday 09:00 AM. 
Problem that occured is that the insulin change was not registered anymore in NS and the Canula change was instead.

For testing we entered again the insulin change at the same time.
Check of NS shows that the insulin change replaced the canula change.

Eventual workaround was to enter the canula change at different time so there was no overwrite.

Preferred function is that both entries are logged to NS and do not get deleted

- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
1.58-combo-phantom-fusion
Build: NoGitSystemAvailable-2018.06.15
Nightscout version: 0.10.3-master-20180805

- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKo
[logs info.nightscout.androidaps.zip](https://github.com/MilosKozak/AndroidAPS/files/2281322/logs.info.nightscout.androidaps.zip)
zak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
fixed in AAPS 2.0
