### ISSUE TITLE
Temp target BG of 10 mmol/l is set as 3207.60 in nightscout

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#1332]
Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
When setting temp target of 10.0 mmol/l in AAPS the software shows error MinBg out of allowed limits. 
Also errors for MaxBg and. target Bg The errors are displayed on the BG line (but unreadable there).
Upon check in Nightscout I see that the temp target was uploaded to NS as 3207.60. Since it is out of range it is limited to 180.0. 
Possbily a conversion error is happening between mmol/l and mg/dl

- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
1.58-combo-phantom-fusion
Build: NoGitSystemAvailable-2018.06.15
Nightscout version: 0.10.3-master-20180805

- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

[logs info.nightscout.androidaps.zip](https://github.com/MilosKozak/AndroidAPS/files/2281328/logs.info.nightscout.androidaps.zip)

**Comment by MilosKozak** [comment]
fixed in AAPS 2.0
