### ISSUE TITLE
Graphics / Text Display Error Overview NS Client 2.0 rc6.1?

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#1333]
1.  In the vertical view you can not see the "OAPS" and the "UPLD". It can be seen in the horizontal view.

2.  Does not it have to be called "OAPS" and not "OASP"?
![screenshot_nsclient_20180814-105316](https://user-images.githubusercontent.com/32514747/44082550-dbd72032-9fb1-11e8-8bfa-179e743d44c8.png)
![screenshot_nsclient_20180814-105413](https://user-images.githubusercontent.com/32514747/44082556-e0ea2844-9fb1-11e8-8f6c-ef4a587e9b1f.png)

**Comment by MilosKozak** [comment]
1) what aps system do you use?
2) fixed in dev, thanks!

**Comment by MilosKozak** [comment]
1. resolved in dev
https://github.com/MilosKozak/AndroidAPS/commit/653a98fd5b50d61154bebdb9721d434ec76cf3e2
