### ISSUE TITLE
RC 6.1 Crash(es) of AAPS

### ISSUE THREAD

**Issue by cheers2** [MilosKozak/AndroidAPS#1338]
This is my second (I call it) Major Crash. AAPS could not be restarted. I deactivated and then stopped the App. And I restarted the phone. I had several times the error message "AndroidAPS has stopped working", clicked "ok" and then it reappeared. After 10 minutes I was able to restart AAPS.

It occurred during normal Operation of the phone. I put in silent mode for three hours and switched off xdrip Alarms (Meeting)

Atteched is the log file of today.
[AndroidAPS_16_08_18_HTCOneM8.log](https://github.com/MilosKozak/AndroidAPS/files/2294165/AndroidAPS_16_08_18_HTCOneM8.log)

**Comment by MilosKozak** [comment]
the app crashes during initialization without any crash report. i'm unable help in this case. if this happen again reninstall and import config
