### ISSUE TITLE
New version notification broken

### ISSUE THREAD

**Issue by savek-cc** [MilosKozak/AndroidAPS#1339]
![aaps](https://user-images.githubusercontent.com/13501427/44271113-90bde600-a239-11e8-9904-ea1e3d8fbc3b.png)
Version is given as xml tag for utf8...

**Comment by MilosKozak** [comment]
i need log file from that time

**Comment by savek-cc** [comment]
Not possible since not a debug build

**Comment by savek-cc** [comment]
What part of the log do you need? It includes this:

```
16:02:32.109 [Thread-3444] DEBUG [VersionChecker.lambda$check$0$VersionChecker():52]: Version outdated. Found <?xml =1.0 encoding=utf-8?>
16:02:32.115 [Thread-3444] DEBUG [NotificationStore.add():56]: Notification received: Version <?xml =1.0 encoding=utf-8?> ist verfügbar.

```

**Comment by MilosKozak** [comment]
ok, i added more loggging. please update and provide logs again if this repeat
