### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#1340]
I noticed that when using nightscout as profile source it is unclear to novice users that a profile switch actually loads the profile from nightscout and makes this active in AAPS with preset conditions.

I suggest to change the term “profile switch” to “Load profile”.  
This way for me it is more clear what the software is actually doing when using this option. Eventually with changes like this the software can become more intuitive.

**Comment by MilosKozak** [comment]
loading profile would we nice only for first use. then profile switch is much more adequate

**Comment by wootmasterslick** [comment]
Looks

**Comment by wootmasterslick** [comment]
Look like it is clear in 2.0 with option to activate profile!
