### ISSUE TITLE
[RC6.1] NS-profile in AAPS not updated after profile switch with % increase

### ISSUE THREAD

**Issue by Pallesauka** [MilosKozak/AndroidAPS#1344]
At 16.55 we tried to do a percentage increase of an existing NS-profile named "Sjuk". The profile switch came through but under the NS-profile tab a completely different profile was shown and it didnt have any percentage added.
When pressing the profile on the overview screen and selecting view profile it seems to be the correct profile with a percentage increase. Log and some screenshots are provided below

[AndroidAPS (1).log](https://github.com/MilosKozak/AndroidAPS/files/2299631/AndroidAPS.1.log)
![screenshot_20180818-165646_androidaps](https://user-images.githubusercontent.com/34350745/44300548-12c91000-a309-11e8-8aa3-04eb6b4bd91c.jpg)
![screenshot_20180818-165634_androidaps](https://user-images.githubusercontent.com/34350745/44300549-152b6a00-a309-11e8-978f-c7f8fd5a845b.jpg)
![screenshot_20180818-165640_androidaps](https://user-images.githubusercontent.com/34350745/44300551-165c9700-a309-11e8-882c-bee05018d410.jpg)

**Comment by MilosKozak** [comment]
on nsprofile page you have displayed Basal 1

**Comment by MilosKozak** [comment]
Nsprofile doesn't show running profile but profiles stored in NS. check wiki
