### ISSUE TITLE
Insulin pump spirit combo

### ISSUE THREAD

**Issue by Bodzio992** [MilosKozak/AndroidAPS#1348]
Hello, I have questions. I have spirit combo. This pump this time can use safe for androidaps? My pump have 4years. I think too about buying new pump. Your opinion what pump are best choice? 

https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by AdrianLxM** [comment]
Both questions are answered in the wiki at http://wiki.androidaps.org
