### ISSUE TITLE
rc4: Nightscout upload not working

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#1350]
Hi,

I have more than 40 000 events for nightscoot to be uploaded but queue did not get empty.
See logs.

[AndroidAPS._2018-08-18_20-41-44_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2300644/AndroidAPS._2018-08-18_20-41-44_.0.zip)

There are sevral NPE, maybe the reason for the problem?

Version: cc7d7b3-2018-06-17

Maybe issue is alread fixed so please ignore, if not then maybe interesting.

Thanks
Gregory

**Comment by MilosKozak** [comment]
you need to fix constant reconnecting of nsclient

**Comment by gregorybel** [comment]
what does this mean?
how should I do that?

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/EN/Usage/Troubleshooting-NSClient.html
