### ISSUE TITLE
extended bolus (as part as combo bolus) from nightscout not registered

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#1353]
A combo bolus only shows the normal bolus and not the square part as Extended Bolus. In example below the 5.8U given as a combo bolus does result in 0 insulin. Only as a Normal bolus with 0 insulin, but not as an Extended BOlus. And as a result it does not increase the IOB.

![image](https://user-images.githubusercontent.com/28272471/44344556-4d5db480-a491-11e8-9e6b-20b05a3a094d.png)

![image](https://user-images.githubusercontent.com/28272471/44344716-a9c0d400-a491-11e8-8d67-13867a88c618.png)

Log:
`{"_id":"5b7a8fe13d9b8e16f59cf3a3","carbs":47,"created_at":"2018-08-20T11:51:28+02:00","duration":30,"enteredinsulin":"5.8","eventType":"Combo Bolus","key600":"BOLUS85758357","notes":"Square Bolus: 5.8U, duration 30 minutes : carb 47g 5.8U, {4.5~6.0} 0.0U, iob 0.2 0.0U (8g\/u, isf 2.7\/u)","relative":2,"splitExt":"100","splitNow":"0","mills":1534758688000,"mgdl":123}]; delta => true; android.support.content.wakelockid => 1455; }Bundle`

The bolus did not came in as ExtendedBolus; that list is empty.
P.S. potential relation with https://github.com/MilosKozak/AndroidAPS/issues/615
600series NS uploader 0.6.1
Nigthscout 0.10.3
AAPS RC61

**Comment by MilosKozak** [comment]
NS is displaying data correctly?

**Comment by hartlijn** [comment]
as displayed in screenshot is correct yes.
if it helps; this is how 600seriesuploader puts it in mlab

`{ "_id": { "$oid": "5b7a8fe13d9b8e16f59cf3a3" }, "carbs": 47, "created_at": "2018-08-20T11:51:28+02:00", "duration": 30, "enteredinsulin": "5.8", "eventType": "Combo Bolus", "key600": "BOLUS85758357", "notes": "Square Bolus: 5.8U, duration 30 minutes : carb 47g 5.8U, {4.5~6.0} 0.0U, iob 0.2 0.0U (8g/u, isf 2.7/u)", "relative": 2, "splitExt": "100", "splitNow": "0" }`

**Comment by hartlijn** [comment]
I think it has something to do with the 'EnteredInsulin' vd 'Insulin'
two examples directly entered in Nightscout
**(square bolus) of 5.8u 100% spread over 30 minutes**
--> result in AAPS is a normal bolus of 0 and no ExtendedBolus.

`enteredBy:Nightscout
eventType:Combo Bolus
glucose:7
reason:
targetTop:0
targetBottom:0
glucoseType:Finger
carbs:47
insulin:0
duration:30
percent:
preBolus:0
notes:combo entered in Nightscout
units:mmol
eventTime:Tue Aug 21 2018 09:00:00 GMT+0200 (West-Europa (zomertijd))
splitNow:0
splitExt:100
enteredinsulin:5.8
relative:11.6`

**(square bolus) 70% as normal bolus (7u) and 30% (3u) spread over 30 minutes. Total of 10u insulin**
--> result in AAPS is a normal bolus of 7u (only the 70%) _without_ an ExtendedBolus
`enteredBy:Nightscout
eventType:Combo Bolus
glucose:7
reason:
targetTop:0
targetBottom:0
glucoseType:Finger
carbs:23
insulin:7
duration:30
percent:
preBolus:0
notes:combo bolus (Normal + square) entered in Nightscout
units:mmol
eventTime:Tue Aug 21 2018 10:00:00 GMT+0200 (West-Europa (zomertijd))
splitNow:70
splitExt:30
enteredinsulin:10
relative:6`

**Comment by MilosKozak** [comment]
so if you create in NS it's still wrong in AAPS?

**Comment by MilosKozak** [comment]
AAPS supports only 0:100% isn't it the issue?

**Comment by hartlijn** [comment]
Yes if I create it in Nightscout it's still wrong.
Could be that AAPS doesn't support it and that it should not be an issue but an enhancement request ;)

It actually is a normal bolus ('insulin') ánd an extended bolus ('enteredinsulin' - 'insulin').

**Comment by MilosKozak** [comment]
the reason why aaps doesn't support it is because it's not easy. aaps holds boluses and extended boluses in separate dbs because they are processed very different. and syncing 2 records vs 1 in NS is not easy

**Comment by MilosKozak** [comment]
you may ask uploader developer to split the record on upload

**Comment by mountrcg** [comment]
Wich repo would be the one to post this to? The 2 that come to mind seem to be long time without updates:
 nightscout/android-uploader
 nightscout/NSClient-Android
