### ISSUE TITLE
[insightfix] Duplicate treatments are being uploaded to nightscout.

### ISSUE THREAD

**Issue by dmelliott20** [MilosKozak/AndroidAPS#1355]
Raising issue as requested.

I am running the insightfix branch 2018.08.17-19:32

Duplicate treatments are being uploaded to nightscout.
1) the issue is exponential - more and more duplicate entries are being created over time for TBR's that have occurred in the past as well as new ones.
2) this does not appear to affect boluses
3) Nightscout performance is affected by the volume of TBR entry's present in the DB

Thanks 

[NStreatmentReport.xlsx](https://github.com/MilosKozak/AndroidAPS/files/2303064/NStreatmentReport.xlsx)melliott

[AndroidAPS._2018-08-20_16-26-49_.0[1].zip](https://github.com/MilosKozak/AndroidAPS/files/2303043/AndroidAPS._2018-08-20_16-26-49_.0.1.zip)

**Comment by MilosKozak** [comment]
do you use xdrip?

**Comment by dmelliott20** [comment]
Yes. Ive disabled the upload of treatments via xdrip

Sent from my iPhone

On 20 Aug 2018, at 19:56, Milos Kozak <notifications@github.com<mailto:notifications@github.com>> wrote:


do you use xdrip?

**Comment by ecorman** [comment]
I'm not sure if that was the case for you, in my case I found if mongo and rest api were active in xdrip, then some treatments were duplicated. I disabled mlab uploads and then no more duplicities were found. If rest api is disabled also then BG values are not uploaded into NS,  I'll be good if nsclient can also uploads bg's so that we can disable all xdrip uploads and only one app is then uploading data.

**Comment by wootmasterslick** [comment]
> 
> 
> I'm not sure if that was the case for you, in my case I found if mongo and rest api were active in xdrip, then some treatments were duplicated. I disabled mlab uploads and then no more duplicities were found. If rest api is disabled also then BG values are not uploaded into NS, I'll be good if nsclient can also uploads bg's so that we can disable all xdrip uploads and only one app is then uploading data.

How did you disable these?
I still have the problem, in the meantime I have collected many many copies of treatments and I think it is now also causing problems for the NS server.
