### ISSUE TITLE
[RC5.1, RC6.1, insightfix] Crash AAPS

### ISSUE THREAD

**Issue by JimmyFoks** [MilosKozak/AndroidAPS#1356]
After installing and running AAPS, the application crashes. Mostly immediately, sometimes with a few minutes delay. My last functional version was RC4. Versions RC5.1, RC6.1, InsightFix are unstable and fall. I have the Insight pump and the Xiaomi Redmi Note 4X phone. Is there a problem with AAPS, SightRemote, MIUI, or "between the chair and the keyboard"?

Timeline:
10:20 instal AAPS insightfix
10:35 crash AAPS

The log file is attached
[AndroidAPS._2018-08-22_10-35-26_.0.txt](https://github.com/MilosKozak/AndroidAPS/files/2309631/AndroidAPS._2018-08-22_10-35-26_.0.txt)

**Comment by kraftm1989** [comment]
I am also facing several AAPS crashes, using SightRemote.
Couldn find Errors in AAPS Log.
