### ISSUE TITLE
2.0e crash

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#1362]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2320431/AndroidAPS.log)

AAPS won´t even start, Logcat shows me this exception: 08-25 09:43:45.910 32067-32142/? E/AndroidRuntime: FATAL EXCEPTION: Thread-17
    Process: info.nightscout.androidaps, PID: 32067
    java.lang.NullPointerException: Attempt to read from field 'double info.nightscout.androidaps.plugins.IobCobCalculator.AutosensData.avgDeviation' on a null object reference
        at info.nightscout.androidaps.plugins.IobCobCalculator.IobCobOref1Thread.run(IobCobOref1Thread.java:194)

Setup:
- Dana R
- xDrip with native G5 (there only with xDrip Plugin)
- Galaxy S8 with 8.0

I can´t look at which commit I am, but it´s the most current.

**Comment by MilosKozak** [comment]
do you have following log file?

**Comment by MilosKozak** [comment]
and previous too

**Comment by McHoffi** [comment]
I did after that a clean install, so all files are gone. Maybe it will happen again, then I can send more logs.

**Comment by MilosKozak** [comment]
:( reopen if you get new date
