### ISSUE TITLE
SMB 0,0

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#1363]
https://github.com/MilosKozak/AndroidAPS/issues/1234

SMB with amount 0,0 in treatments tab at 21:59 and 20:34.

Not sure about exact version, happened on 19.08.2018 and should have been very current dev branch.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2320918/AndroidAPS.log)

**Comment by MilosKozak** [comment]
i believe this was fixed on Aug 21, 2018
is you build newer?

**Comment by McHoffi** [comment]
Current build yes, but this happened already at 19., didn´t know, that it was already fixed, so this issue can be closed.
