### ISSUE TITLE
2.0-RC6.1 - Careportal temp basal adds 100% to entered value

### ISSUE THREAD

**Issue by wwwired** [MilosKozak/AndroidAPS#1367]
Build: 201.08.11-16:26
Flavor: fullrelease
Setup: Open looping on Google Pixel XL (Android 9.0)

Observed behaviour:
Temp basals have 100% added to the value entered, so unable to manually set basal <100%.
Set basal 10% = 110%, 30% = 130%, etc.

Steps to create issue:
1. Careportal > Temp Basal Start = 80% for 90 minutes
2. Overview > (blue text above graph & IOB/COB) "180% @xx:xx PM 0/90' (0.70Uh)"

![screenshot_20180822-164036](https://user-images.githubusercontent.com/36865255/44657624-5e5c7780-a9f5-11e8-8899-2a6f9dd6ca1e.png)
![screenshot_20180822-164106](https://user-images.githubusercontent.com/36865255/44657625-5e5c7780-a9f5-11e8-9880-99eeed423593.png)
![screenshot_20180822-164115](https://user-images.githubusercontent.com/36865255/44657626-5e5c7780-a9f5-11e8-949f-8ff29181feec.png)

**Comment by MilosKozak** [comment]
careportal is an interface to NS and NS is using different notation to AAPS
0..200% in AAPS is equal to -100..+100% in NS

but you are right there was an bug in AAPS not allowing to set percentage < 0
it's fixed now
