### ISSUE TITLE
VirtualPump selected pump, doesn't limit TBR suggestions to specific value (rc7)

### ISSUE THREAD

**Issue by sethgagnon** [MilosKozak/AndroidAPS#1372]
Currently running rc7, although I noticed this issue on the dev branch last week.

After installing, I selected the Virtual Pump in the Config Builder and then selected Insulet Omnipod in the settings there. However, when the app is making suggestions for TBRs and for Boluses using the calculator, it is not using the delivery dosage increment of 0.05 as Omnipod uses. I have received TBR recommendations of 2.97, 0.61 and I have received bolus recommendations using the calculator of 2.47.

I would expect that the app would round appropriately and provide recommendations based on what omnipod can actually deliver (0.05 increments).

Thanks!
Seth

**Comment by andyrozman** [comment]
Is fixed now. Amount given is rounded to correct value. After release I will take another look, and perhaps try to use Constraints to also round recommendeation (not just treatments).
