### ISSUE TITLE
[RC7] nsclient Build failed

### ISSUE THREAD

**Issue by blocklist** [MilosKozak/AndroidAPS#1375]
Rc7 and Dev: nsclient and nsclient2 apk build failed with:

---------------------------------------------------------
Information:Gradle tasks [:app:assembleNsclientRelease]
Information:BUILD FAILED in 6s
Error:FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:handleNsclientReleaseMicroApk'.
> The main and the micro apps do not have the same package name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

Information:1 error
Information:0 warnings
Information:See complete output in console
---------------------------------------------------------

Build generated signed apk, 
 Modul: app, 
   key, 
     Build-type: release, 
       flavors: nsclient

**Comment by Mackwe** [comment]
Same here.

**Comment by Mackwe** [comment]
The main app and the wear modules must be using the same productFlavor names. I am guessing this is a restraint in the latest version of the compiler, which would explain why it works on earlier versions.

I seem to have made it work by adding this to the "android {..." part of the build.gradle for the wear app:

-----------------------------
publishNonDefault true

    productFlavors {
        flavorDimensions "standard"
        full {
            applicationId "info.nightscout.androidaps"
            dimension "standard"
            versionName version
        }
        pumpcontrol {
            applicationId "info.nightscout.androidaps"
            dimension "standard"
            versionName version
        }
        nsclient {
            applicationId "info.nightscout.nsclient"
            dimension "standard"
            versionName version + "-nsclient"
        }
        nsclient2 {
            applicationId "info.nightscout.nsclient2"
            dimension "standard"
            versionName version + "-nsclient"
        }
--------------------------------

Please try this and let us know if it works.

**Comment by Mackwe** [comment]
This is what my file looks like now:
![skarmklipp](https://user-images.githubusercontent.com/6748615/44786099-5c301f80-ab93-11e8-8497-8e3b35d587ee.PNG)

**Comment by MilosKozak** [comment]
create PR

**Comment by Mackwe** [comment]
@Milos: I would love to. Just two things; I would like it to be confirmed. And I would _love_ if I can find someone who can spend half an hour and explain exactly how to do a PR, so that I can understand the Git system. I've tried more than once, but the only one wanting to help is you, and I sincerely believe you have too much work as it is.

**Comment by MilosKozak** [comment]
pushed to dev. THANKS!
