### ISSUE TITLE
[RC7] treatments tab->calc in bolus entries crashes the app

### ISSUE THREAD

**Issue by CaptainBalou** [MilosKozak/AndroidAPS#1380]
In treatments tab, bolus tab there is a green "calc" on some boluses. Clicking that will crash the app on each try.
[AndroidAPS._2018-08-30_22-54-16_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2337938/AndroidAPS._2018-08-30_22-54-16_.0.zip)

--------------
- Time 22:54 CEST
- 9cd16db33-2018.08.29-23:08

**Comment by typ1-brods** [comment]
![20180831_071232](https://user-images.githubusercontent.com/32912987/44893884-649c6d80-aced-11e8-8119-e1a0ad0fc856.jpg)
![screenshot_20180831-071209_samsung experience home](https://user-images.githubusercontent.com/32912987/44893885-649c6d80-aced-11e8-8c18-1df24812a8ea.jpg)

**Comment by MilosKozak** [comment]
resolved in dev. please test

**Comment by CaptainBalou** [comment]
Tested. Fixed in dev. Perfect job.
