### ISSUE TITLE
Software Crashes while Click in Treatsment-Tab on "Calc"

### ISSUE THREAD

**Issue by kraftm1989** [MilosKozak/AndroidAPS#1388]
When in Click on "Calc" in the Treatment-Tab, the App crashes completely and reproduceable.
Happens at system time arround 15:57.

RC 7, Build 2018.08.28
Android 7.0

![screenshot_20180903-155819](https://user-images.githubusercontent.com/41928733/44991079-51aac700-af93-11e8-96ad-a8b9fc7208b4.png)
![screenshot_20180903-155844](https://user-images.githubusercontent.com/41928733/44991080-51aac700-af93-11e8-8c03-b56ecd837645.png)
![screenshot_20180903-160023](https://user-images.githubusercontent.com/41928733/44991082-52435d80-af93-11e8-9944-797b2e0c6433.png)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2345820/AndroidAPS.log)

[AndroidAPS._2018-09-03_15-56-18_.txt](https://github.com/MilosKozak/AndroidAPS/files/2345823/AndroidAPS._2018-09-03_15-56-18_.txt)

**Comment by MilosKozak** [comment]
resolved in dev
