### ISSUE TITLE
Wrong Profile shown in Prof-Tab, when Percentage is used

### ISSUE THREAD

**Issue by kraftm1989** [MilosKozak/AndroidAPS#1393]
If I do a ProfileSwitch in Homescreen with %-Rating, it won't be visible in the "Prof"-Tab. 
There'll be one of the other Profiles visible.
If I do a ProfileSwitch in Homescreen without %-Rating, the correct Profile is visible in the "Prof"-Tab.
If I do a ProfileSwitch in "Prof"-Tab, the correct Profile is visible in Homescreen.

Happens arround 10:50 Systemtime

RC 7, Build 2018.08.28
Android 7.0

Screenshots:
![screenshot_20180905-105001](https://user-images.githubusercontent.com/41928733/45084317-58a21880-b0fe-11e8-99ee-5638426c2acb.png)
![screenshot_20180905-105009](https://user-images.githubusercontent.com/41928733/45084323-5a6bdc00-b0fe-11e8-9ad1-92d8c4b2ed6e.png)
![screenshot_20180905-105036](https://user-images.githubusercontent.com/41928733/45084328-5b9d0900-b0fe-11e8-88c6-1c3e8eb9b85e.png)
![screenshot_20180905-105048](https://user-images.githubusercontent.com/41928733/45084334-5dff6300-b0fe-11e8-876f-3d720cbec6dc.png)
![screenshot_20180905-105144](https://user-images.githubusercontent.com/41928733/45084339-5f309000-b0fe-11e8-8185-58654ffe19c1.png)

Logs:
[AndroidAPS._2018-09-05_10-51-14_.txt](https://github.com/MilosKozak/AndroidAPS/files/2352125/AndroidAPS._2018-09-05_10-51-14_.txt)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2352126/AndroidAPS.log)

Thanks for checking and your effort!
Max

**Comment by MilosKozak** [comment]
i'm not sure if i understand it right but my feeling is it behaves exactly like described here
https://androidaps.readthedocs.io/en/latest/EN/Usage/Profiles.html

**Comment by MilosKozak** [comment]
Profile tab is not running profile but some kind of "Profile store"

**Comment by kraftm1989** [comment]
Of Course, Profile Switch with % Rating works, but may this shows my "Problem".

Scenario 1 - Switching Profile in Home-Tab:
Tab Home                                -    Tab Profile
Switch to Rate A with 100%    -    Shows Rate A
Switch to Rate B with 100%    -    Shows Rate B
Rate A with =!100%                -    Shows Rate X (random) (The Question is: why not Rate A?)
Rate B with =!100%                -    Shows Rate X (random) (The Question is: why not Rate B?)

Scenario 2 - Switching Profile in Prof-Tab:
Tab Profile                                -    Tab Home
Switch to Rate A                      -     Shows Rate A
Switch to Rate B                      -     Shows Rate B

Does that make my problem understandable?
It's confusing if you get a different profile than the currently set one (with % rating) displayed in the Prof-Tab.

**Comment by kraftm1989** [comment]
I can't read that out of the linked part of the doku. Sorry.
no matter if i am unable to interpret the document correctly, wouldn't it still be "nice" if the profile-tab displays the currently used profile by default? that's what i intuitively hope for from this tab.

**Comment by MilosKozak** [comment]
it cannot because this is the base profile you are taking percentage and time shift from
