### ISSUE TITLE
[AAPS 2.0 RC7]Extended Bolus -> Square Bolus

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#1394]
Below the tab "Careportal" the entry of the extended bolus is correct at 1.25U in 180 minutes.
Under "Extended Bolus" it will be displayed with 6U in 180 minutes. Thus unfortunately the IOB is wrong and AAPS makes wrong suggestions for the adapted TBR.

![screenshot_androidaps_20180905-162257](https://user-images.githubusercontent.com/32514747/45099944-c2371c80-b128-11e8-99dd-de0bd1429ba1.png)

![screenshot_androidaps_20180905-162236](https://user-images.githubusercontent.com/32514747/45099955-c82cfd80-b128-11e8-97c4-b7cc5bce7281.png)

**Comment by MilosKozak** [comment]
where is this record comming from?

**Comment by st0ber** [comment]
The record is from the AndroidSeriesUploader.

{
    "_id": {
        "$oid": "5b8fcc1f1f148767d8b4459f"
    },
    "created_at": "2018-09-05T14:25:30+02:00",
    "eventType": "Note",
    "key600": "BOLUS80E18D7ENOTE",
    "notes": "Square Bolus: 1.25U, duration 180 minutes"
}

**Comment by MilosKozak** [comment]
it's a bug in uploader
