### ISSUE TITLE
Make priming amounts from prime/fill button not to appear in pump dosing history

### ISSUE THREAD

**Issue by xour** [MilosKozak/AndroidAPS#1397]
Not sure if this is the right place to post this suggestion, as this is not a bug or critical issue. Excuses in advance if it is not the place and please tell me the right place to post then.
As suggested by a post in the Facebook group, it would be nicer if the insulin amounts used for priming as given by the prime/fill button in the Actions tab would not appear in the dosage history as seen from the DanaRS tab, "DanaR stats" button. Otherwise people will keep using pump controls for priming/filling as the history then looks clean from priming amounts. The whole purpose of the prime/fill button in AAPS seems then obscured.

**Comment by MilosKozak** [comment]
RS doesn't support it. If you don't want it in TDD stats, you have to use priming on pump
