### ISSUE TITLE
[Feature request] Reset autosens on profile change

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1398]
I would like the autosens data to be reset when I change basal profile. I gather it would be best to only reset on profile switches with no duration, since you may want to set a temp profile during excersise. 

If not, can there be a button in Actions or similar, where I can manually reset autosens? 

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/ecae6af151a4b9aed93645510ee73f2c0764e5de

**Comment by Mackwe** [comment]
Darn, that was fast! Thank you!
