### ISSUE TITLE
[DEV] Applying constraints to a bolus with 0.6 or 0.7 U 

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1404]
I get the following strange confirmation message when entering a bolus of 0.6 U or 0.7 U in the NewInsulinDialog. Any other bolus is (0.5/0.8) isn't affected.

![image](https://user-images.githubusercontent.com/12517693/45267998-b0ca7900-b476-11e8-96ec-27f726eadcf3.png)

AndroidAPS 2.0g-dev

**Comment by Mackwe** [comment]
Just realised I have the same issue here: https://github.com/MilosKozak/AndroidAPS/issues/1405

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/0f2a620ebe2773712c88b5640c2f058c1ac4e064
resolved in dev
