### ISSUE TITLE
[RC8] NewInsulinDialog confirmation dialog seems broken

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1405]
Insulin dialog > added 0.15u bolus. The confirmation dialog says 0.1500000000002u requested and with red text: Bolus constraint applied. I can still just press OK and the bolus gets administered. 

See picture.
![img_20180909_233623](https://user-images.githubusercontent.com/6748615/45269171-7e764700-b489-11e8-81da-9726cf3adf81.jpg)

**Comment by kraftm1989** [comment]
I had this issue, too.
This Morning I had also an Error wich told me "bolus delivery error
beschränkungen wurden verletzt, oder limit erre
Restrictions have been violated, or limit reached. Change your input!"
but neither the maximum bolus nor the maximum kh were reached. i don't find an entry in the log at that time. 5min later it works.
maybe the errors are related?

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/0f2a620ebe2773712c88b5640c2f058c1ac4e064
create another issue for wizard with more info
