### ISSUE TITLE
Bolus Calculator Bug

### ISSUE THREAD

**Issue by kraftm1989** [MilosKozak/AndroidAPS#1408]
In Bolus Calculator, I get a "bolus delivery error".
"restrictions were violated or limit reached. change your input!"
but neither the maximum bolus (set to 12ie) nor the max kh (96g) were reached.
when reopening the bolus calculator everything works again.
I only entered the 48g kh and wanted to give the result as an injection.

i've had this problem twice already. at the time of the screenshots (7:08) i don't find an entry in the log.

![screenshot_20180910-070837 1](https://user-images.githubusercontent.com/41928733/45321974-33bb0480-b547-11e8-8185-eb8abeaa40fe.png)

[AndroidAPS._2018-09-10_00-00-06_.log](https://github.com/MilosKozak/AndroidAPS/files/2368252/AndroidAPS._2018-09-10_00-00-06_.log)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2368253/AndroidAPS.log)

AAPS2.0 RC8
![screenshot_20180910-221817_2](https://user-images.githubusercontent.com/41928733/45322150-b348d380-b547-11e8-8681-951932911f55.png)

**Comment by kraftm1989** [comment]
no, when clicking "OK" in Bolus Calculator.

**Comment by bertroode** [comment]
I noticed the same problem today after compiling the latest Insightfix. The calculator tells that there is a bolus constraint, whereas I can give the needed amount as a correction bolus.

**Comment by MilosKozak** [comment]
unfortunately i didn't have enough logging on wizard. added to dev (+insightfix) now . please reopen with new log

**Comment by MilosKozak** [comment]
fixed in dev
