### ISSUE TITLE
[RC] Sensitivity can't be imported/exported in settings 

### ISSUE THREAD

**Issue by MarieT1D** [MilosKozak/AndroidAPS#1410]
In RC7 and RC8 (probably also earlier), I can't export or import the settings of the sensitivity:
what I tried:
sensitivity oref1 enabled; Export Settings; Change sensitivity to sensitivity AAPS; import Settings

sensitivity was still on sensitivity AAPS.

**Comment by MarieT1D** [comment]
I made another test on another phone:
it also concerns OpenAPS MA/AMA/SMB
Importing older objectives worked, but not sensitivity and OpenAPS Options

**Comment by MilosKozak** [comment]
confirmed. i look on this issue

**Comment by MilosKozak** [comment]
fixed https://github.com/MilosKozak/AndroidAPS/commit/53389fea3b9999fbfdb5178404072080a7020d77

**Comment by MarieT1D** [comment]
thanks :)
