### ISSUE TITLE
[RC8] eCarbs not replicated properly

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1412]
AAPS Master and NSClient both on RC8.

Issue: Entered 30g carbs over 2 hours. Data replicated to NS Client. Realised it should be over 3 hours. "Remove Future Treatments" from master removed the data from master. Added same amount over 3 hours (on master). Master has correct data. Client picked up both eCarb arrays and showed a LOT of COB. Went into Treatments on Client and press Refresh from NS. All updated and working. Tell me what to switch on logging for and I can probably reproduce this.

**Comment by MilosKozak** [comment]
tested a few times without any problem. there is different handling when nsclient is online and when not .... test whitch case is causing the issue

**Comment by Mackwe** [comment]
I will try to replicate. Both phones was on home wifi, though. Any suggestions on what to log before I start?

**Comment by MilosKozak** [comment]
all "DATA"

**Comment by Mackwe** [comment]
Checked this now. I cannot reproduce. The eCarbs disappear from the NSClient as they should. It just takes a long time, it seems. Almost a full minute. When I had the error it however was more than 15 mins after, so there was an actual error. Will keep a lookout for this in the future. Will close the issue and re-open if it appears again.
