### ISSUE TITLE
[RC8] NSClient: BG arrows don't fit

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1416]
Since introducing the AS percentage top middle on NS Client, the BG direction arrow doesn't fit within its space. Phone is Huawei Honor 8, Android 7.0.

![pic](https://user-images.githubusercontent.com/6748615/45376652-a7691a00-b5f8-11e8-8f44-c7b9b5d8137d.png)

**Comment by Mackwe** [comment]
I honestly feel I am complaining about tiny stuff here. But since you asked for RC bug hunting.. ;-)

**Comment by MilosKozak** [comment]
improved in dev
