### ISSUE TITLE
[RC8] BG sms command not working.

### ISSUE THREAD

**Issue by Lexsus** [MilosKozak/AndroidAPS#1417]
When I send sms command BG to AndroidAPS  I do not get an answer.

**Comment by MilosKozak** [comment]
you didnt setup everything properly 
https://androidaps.readthedocs.io/en/latest/EN/Usage/SMS-Commands.html

**Comment by Lexsus** [comment]
I  setup everything properly. I received answer from BOLUS, LOOP START and other. But not recevied answer from BG.

**Comment by MilosKozak** [comment]
ok,test it again and provide log files. and add time of test

**Comment by MilosKozak** [comment]
no response, closing
