### ISSUE TITLE
[RC8] 24h time display/Regional settings issue

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1419]
This has been a problem in NSClient for a loong time; My Huawei Honor 8, Android 7.0 running NSClient always shows the time (top right corner in app) using 12h (AM/PM) regardless of my phone's regional settings or the app language. In Sweden we always have 24h displayed but I can't get AAPS to do that no matter what I try. I know another user with the exact same issue and I have looked at it a while back. If I remember correctly, the app calls the OS setting, but I guess it fails under certain conditions..

Can we implement a 12/24h switch just by the language setting and force it correct?

**Comment by MilosKozak** [comment]
I'm using system calls to generate time
i tested it rigth now. When I change Android to Czech, turn off/on 24h format and restart NSClient it start appear in 24h format

**Comment by Mackwe** [comment]
I am sure I have tried this before, but now it works just as you described. Even tried restarting the phone. Still works.
