### ISSUE TITLE
[Dev] NSClient: Quickset targets cannot contain point or comma

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1421]
Running today's dev in mmol, Swedish and on Huawei Honor 8, Android 7. Quicksets (hypo, eating soon etc) are now available for NSClients, but the target BG cannot contain decimal comma or point..

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/45387252-cde97e00-b615-11e8-9be7-95bec2cb99b6.png)

**Comment by Mackwe** [comment]
I must be tired or there are trolls around. It seems to work for me too now. Nevermind me..
