### ISSUE TITLE
Calculator views from previous treatments show wrong profile

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#1425]
Yesterday evening I added another nightscout profile, but don't use it yet. All calculator views from the treatments tab from treatments after the addition of the new profile don't show the correct used but the newly added profile.

I'm currently using the dev branch.

**Comment by MilosKozak** [comment]
can you provide screenshots and steps to reproduce this issue?

**Comment by bertroode** [comment]
![screenshot_2018-09-13-08-42-53](https://user-images.githubusercontent.com/3540901/45471600-de8f1680-b731-11e8-9a2e-8c3d184e3a9d.png)
May be this is the same kind of problem I encountered this morning. Entering Carbs result in extra entry in the treatment section.

**Comment by MilosKozak** [comment]
sorry i don;t undestand the issue at all

**Comment by MilosKozak** [comment]
looks like you activated extended carbs feature

**Comment by quizzmaster** [comment]
Steps to reproduce:
Add another Profile on Nightscout and don't switch to it. Use the wizard and look at the resulting treatment.

Here you can see my last profile switches and the calculator view from a previous treatment, which was made after the addition of a new profile called "circadian test" without activation.
<img src="https://user-images.githubusercontent.com/2745710/45484163-8c5eed00-b753-11e8-9f8a-9228e6b30489.jpg" width="49%"> <img src="https://user-images.githubusercontent.com/2745710/45484166-8e28b080-b753-11e8-9156-5d3f509bd1d3.jpg" width="49%">

@bertroode  Sorry but your description already shows a completely different issue. Yours isn't even about profiles.

**Comment by MilosKozak** [comment]
so the issue is that in Wizard Settings dialog is displayed another profile than used in calculation?

**Comment by quizzmaster** [comment]
That's correct. The profile shown in the Wizard Settings dialog also was never used in AAPS.

**Comment by quizzmaster** [comment]
Additional informations:
I looked into the Code and found, that the wrong ProfileName is saved as "defaultProfile" in the json object within the ProfileStore. The store itself contains the correct names, but "defaultProfile" seem to be always the name of the last added profile.

**Comment by quizzmaster** [comment]
My PR #1431 fixes this issue. Nevertheless the ProfileInterface of the "active" profile shouldn't address the NS defaut profile but the real active profile used by AAPS.
