### ISSUE TITLE
[DEV] Alert: unknown. Please check your Pump History...

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#1426]
![screenshot_20180913-090404](https://user-images.githubusercontent.com/32514747/45473447-66c3ea80-b737-11e8-947b-a6e7af589c98.png)

German: 
Basalabgabe fortgesetzt um 03.29 nach Unterbrechen durch Sensor-Alarm. BZ prüfen.

Google Translate:
Basal delivery continued at 03.29 after interruption by sensor alarm. Check BG.

**Comment by MilosKozak** [comment]
what pump?

**Comment by st0ber** [comment]
Minimed 640g

**Comment by MilosKozak** [comment]
then this is generated by uploader. open issue there
