### ISSUE TITLE
[1.58] Superbolus Error

### ISSUE THREAD

**Issue by heba29** [MilosKozak/AndroidAPS#1427]
Following incident: Basal rate plus superbolus selected. When connecting with the DANA-R pump, an error message occurred after about 15 seconds. Then APPS reestablished the connection, gave off the bolus, but did not set the temporary basal rate to 0% for 2 hours.

I have noticed since 2-3 days that the connection to the pump took a little longer. The battery is now already 17 days in the pump. Maybe this is also a reason.

In NightScout the Superbolus shows correctly.

![grafik](https://user-images.githubusercontent.com/33902762/45480997-ac3de300-b74a-11e8-9fdf-db0418bba5c2.png)

Not in APPS.

![grafik](https://user-images.githubusercontent.com/33902762/45481173-2d957580-b74b-11e8-8831-458eff04e686.png)

I had to stop the pump for 2 hours now. Let's see what happens. 

APPS Version 1.58, DANA-R

**Comment by MilosKozak** [comment]
this is already fixed in 2.0
