### ISSUE TITLE
Open loop TBR limited by safety constraint after higher rate suggestion enacted

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#1429]
AndroidAPS 2.0g-dev (2018.09.12-10:03) - running virtual pump Cellnovo (open loop)

AAPS requested a TBR of 175%. Confirmed the suggestion and applied in pump then observed that the Overview screen showed that the temp basal enacted was 170%. See screenshot of AAPS loop tab below:

![img_8490](https://user-images.githubusercontent.com/33720345/45480835-db9c2200-b741-11e8-883a-77c9d84d25d5.jpg)

Have checked logs and it appears that I had the pump limit set too low which caused the system to limit the rate to 170% after I confirmed 175%.

When open looping I believe the safety limit should be checked prior to the TBR suggestion appearing to avoid this situation where a TBR is enacted at a higher rate on the pump and then tracked at a lower rate in AAPS.

See log extract below:
17:11:52.292 [main] D/APS: [APSResult.isChangeRequested():347]: TRUE: Outside allowed range 116.66666666666667%
17:11:52.293 [main] D/APS: [LoopPlugin.applyTBRRequest():514]: applyAPSRequest: Rate: 175.00% (1.14 U/h)
Duration: 30.00 min
Reason: COB: 1.3564130718954328, Dev: 70, BGI: -11.63, ISF: 8.5, Target: 5.5; Eventual BG 7.7 >= 5.5, temp 0.975<1.17U/hr
17:11:52.294 [main] D/APS: [LoopPlugin.applyTBRRequest():545]: applyAPSRequest: tempBasalPercent()
17:11:52.297 [main] D/CONSTRAINTS: [Constraint.set():47]: Setting value 175 -> 170 (Limiting max percent rate to 170% because of pump limit)[Safety]
17:11:52.299 [main] D/PUMPQUEUE: [CommandQueue.add():122]: Adding: CommandTempBasalPercent - TEMPBASAL 170% 30 min
17:11:52.301 [main] D/PUMPQUEUE: [CommandQueue.notifyAboutNewCommand():163]: Starting new thread
17:11:52.303 [Thread-6962] D/PUMPQUEUE: [QueueThread.run():137]: connection time 0s
17:11:52.316 [Thread-6962] D/PUMPQUEUE: [QueueThread.run():143]: performing TEMPBASAL 170% 30 min
17:11:52.318 [Thread-6962] D/DATABASE: [DatabaseHelper.roundDateToSec():326]: Rounding 1536768712318 to 1536768712000
17:11:52.350 [Thread-6962] D/DATABASE: [DatabaseHelper.createOrUpdate():885]: TEMPBASAL: New record from: USER TemporaryBasal{date=1536768712000, date=9/12/18 17:11, isValid=true, pumpId=0, _id=null, percentRate=170, absoluteRate=0.0, durationInMinutes=30, isAbsolute=false, isFakeExtended=false, netExtendedRate=0.0}
17:11:52.366 [Thread-6962] D/NSCLIENT: [DbLogger.dbAdd():29]: DBADD dbAdd 1 receivers {"eventType":"Temp Basal","duration":30,"percent":70,"rate":1.105,"created_at":"2018-09-12T16:11:52Z","enteredBy":"openaps:\/\/AndroidAPS"}
17:11:52.368 [Thread-6962] D/PUMP: [VirtualPumpPlugin.setTempBasalPercent():306]: Settings temp basal percent: Success: true
Enacted: true
Comment: OK
Duration: 30 min
Percent: 170%

**Comment by MilosKozak** [comment]
for cellnovo is in description basal step 10%

**Comment by dansuk** [comment]
oh that's incorrect. It should be 5%

**Comment by dansuk** [comment]
I think this is something else as the basal step is showing ok in the virtual pump tab:

![image](https://user-images.githubusercontent.com/33720345/45512584-0dd86e80-b798-11e8-9d7e-26edd3daafd0.png)

**Comment by dansuk** [comment]
Cellnovo went into administration and all users migrated to other pumps - no longer need to support.
