### ISSUE TITLE
[RC8] Oref1 Autodsense does not return to 100% after a period dominated by carbs

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1434]
![screenshot_20180913-063648](https://user-images.githubusercontent.com/179086/45548712-39516c80-b81d-11e8-9068-658df1ee7ef6.png)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
point me pls what's wrong on graph, what sensitivity ...

**Comment by roppenheimer** [comment]
The white Autosense line has remained low during a period dominated by carbs rather than returning to the neutral (100%) position. Thus AAPS has not responded strongly enough to the period of high BG from around 12 noon until 03 am

**Comment by AdrianLxM** [comment]
The line changes by two things:
regarding new values
disregarding old values that fall out of the time frame

If you don't produce new values as time without COB are disregarded, the white line should not change as much - only from the disregarded old values dropping out.

**Comment by AdrianLxM** [comment]
BTW the text you have sent as bug-report is just the default text without filling in anything. Hard to guess anything from that ;)

**Comment by MilosKozak** [comment]
the behaviour is expected. if you want faster follow sensitivity changes use weighted average plugin

**Comment by roppenheimer** [comment]
My understanding is that the sensitivity algorithm inserts neutral values into the deviation data during long periods dominated by carbs so that the sensitivity will gradually return to 100% and not remain stuck at its previous value. I have just been looking at the OpenAPS notes and I can't find that reference again.
