### ISSUE TITLE
strange bolus restrictment when using insulin button

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#1436]
I get the message " bolus: 0.300000000000000004U ; bolus restriction used" when entering a manual bolus (0.3 U) by using the bolus button. No such message when using the calculator. This occurs always when using the button. If you press "ok" the bolus is given correctly.
Using AAPS rc 8 , build 84a79b30f-2018.09.10-19:30; fullrelease, 
logs send via email from app 

![screenshot_20180915-094617_androidaps 1](https://user-images.githubusercontent.com/22258719/45584542-cf48ce00-b8d5-11e8-8872-f555241e3c65.jpg)

**Comment by quizzmaster** [comment]
Same as #1404, which is already fixed. Also RC9 is already available :wink:

**Comment by CaroGo** [comment]
Yes...thanks..just saw it and updated! Sorry for beeing late! ;-)
