### ISSUE TITLE
Delta Values are always zero

### ISSUE THREAD

**Issue by zreptil** [MilosKozak/AndroidAPS#1437]
can be reproduces everytime the glucose is raising or falling
AndroidAPS 2.0-releasecandidate8
build version: e755b3b-2018.09.10-10:44

I sent the logs to logs@androidaps.org

The delta values on the mainscreen are always 0, but the arrow points to the correct direction. On the watchface the arrow always is horizontal. I think this will be corrected automatically when the delta values on the phone show the correct values.

![heavy raising](https://lh3.googleusercontent.com/i_V-R68YvJKWvJ5ICba-p5cxthP67304OuXK5Rpu3LUwnaGYFMJwElgX0zJAXfe2phEsRDGuiWyKuwDg48q5w1B20rrhZBf4HPs08_Z-h0SXPe8g9hbTBT31l7JgFsU1ki1rw25bWgAwDwIuvzBXxHBhsdXw2yh1nVGbPa0m1lol_ZkBjTYbjI2mo7YgMYhKt1ZWbyjSVB2oEArmFhasMb4WL9hq8NFAOpx9744_x418Tu3ehzy3klgOgli-Inr_1P8MyF2GEc-I1gvCdY0uD2Llpf3Vfu2hFFPpMgiE6rkoivn2Y4Se-1gwnrVU6BISDO-jBIXR4Pk4378y5Wb2FroIC9UZrZ4sABGVlCJEdjOJwKBjnyhoYs6MRV6GAG_twPFLcHVeiKxnTQVwjnAx1xdEjhsz81fViXfVtJYQDuPnEYnqDRNl1Wrt2A0oRgvUEhYbX5sWynWjTVqPskDBH3lACWYXjBeswO9RoUr4d1wkQ7QunIUxlgfFrglkRLiHQU5wVN6U3BD8Olh6j4jziDTnVTqUslg_vNnJ_WbhzQmE4gw6cOWUv_YgVNYgIXDQb7ItHcYYTWwNdkRt8sfU1I5GC9oaqhxUdkG_goesJhx0rchmkmMMrq6LfepjyJrv=w508-h903-no)

![heavy falling](https://lh3.googleusercontent.com/lnIun7aI0SEJpz2-JoI88q96Zzkqq1rV9aGHw73WGYzxr1t2hlmQoMfV7aRsLCfEkZKfCmeHNICx3cN0Om49qxpty37SjplsIMpiv6SwCrlZ9d_gzWxLEigsAm6SQogkDfDfAboIMycaUvAobokAwURvm8n_jhy7MofauccoVMkpI9jk08x8e3J-OFIawLJjYU6Uqcl3x-z0Qfg0Xbx8q7IEwr0tQ3QTR0KoFe8kU4lzUFzVdXuAsMyij_TRTudJn8FOm5Rp9xUubmDuVfsPi2mEYSFptWRLNsAT7odznWB6Y2S9WPBC21LTRaqWp89JCMOvA3kGTEEFX4AvyaN4dlQnUy15o8uBsU4za6VcDKqgjys9lmFAfX4Lze4V802dSEMejAOOG2xng0Kv_Q8zj7dn7fyyEwhaXpX6NVCZCSPDN2k9AsKc_AkkpZJ-NhvRIx3WaVCkjl38qO4ccKih52gl8RiXVi-hDQIp09siRwmDgpX1ArEW3MSrVc5PNgYnmydW_IHFwcPoqY1Dk-PqUTUT0vevzoBGntDYvDC3q2fJcatoo2gsG0Nk4sRWfWinXfiR_8laY8lfjvqTrP2TDIUxpycvYxh0y_eQoi2gIM6MFLZz8xEbaMP9tArSmm6B=w508-h903-no)

![Falling](https://lh3.googleusercontent.com/MIRzSyFVb9Kjq99VnqkorGc_q8Rj5uvJzLOAfqiUZlQIYFzoV-6L8rYN1HlvJUSZUY8YS5ElBes0JIqNwvWg4ubiR9mUifw2IerTSBKTofixtzQGebnlfIehPPfT3SfqICTJUHTevrYOgEYPx-u-ff1pITE-bRM8h9GmofLQG5c2XhnE8ZV_dxUNo3PiZzP7HArrbHATAQFWUjIWytjxCOxd-dEgICjSwt6N41Nz7rfTWBLGDfcqE8nhVeax7JhRjspA9IRZEsvHNocl08vUTGOaHRvanQEfUjRGgx8yLRg_nykWqhDl04eVDnSaci1z2xFwxbVj7gR8TjQzxAbVCrRsj7UyZ4lrfL5nU55_4glyDF4rzn3pc0yiUJNptvC-egdwrrZGFJLchxFP0tJX-QCBgGT4EkBd6arr2_5xtM3I9_TM1mxAXhp82seZM1m6W6Q6IDInmrpAbMSC-arhF45BzK9QrUcf7mUMWXjpNE7j1FH-VgnbPbvdqPzT4lT5Ljec3OcKKFEPMBJXN8nFQE-ovf46ahckYV7_zMVgQvEzK0bgeUDLyWv5NZViA5guLfSaH8Va09MfSZih2A_Lk0x1ZrCnfmiDvZQS2g6MsmGLsvmVWdCZRNbaJaPE5AV3=w508-h903-no)

**Comment by AdrianLxM** [comment]
What CGM source do you use?
What is the frequency of new values generated by that source?

Does the same thing happen if you disable Nightscout?
Does the same thing happen when you disable other sync features (like sendig Data to xDrip)?

The arrow has no meaning. It will just show whatever your CGM source sends together with the value.

**Comment by zreptil** [comment]
Hi Adrian,

i use glimp with MiaoMiao as CGM source every 5 minutes.

I disabled nightscout and then there are delta-values that matched the
arrow.
After that i enabled nightscout again and the values were 0 again. So maybe
nightscout-synchronization is the problem?

Am So., 16. Sep. 2018 um 12:15 Uhr schrieb AdrianLxM <
notifications@github.com>:

**Comment by AdrianLxM** [comment]
@MilosKozak do you know what could cause this?

**Comment by MilosKozak** [comment]
in NS there is CGM data for every minute

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/issues/1448
