### ISSUE TITLE
[Enhancement]: Show Comments on Treatments Tab

### ISSUE THREAD

**Issue by triplem** [MilosKozak/AndroidAPS#1450]
Currently on the Treatment Tab the amount of insuline and of carbs are shown, but not the given comments. This would be a great feature.

**Comment by Mackwe** [comment]
Preferences > Overview > Buttons. Turn the bottom one (show notes field is treatment dialogs) to  On. Is that what you were missing?

**Comment by Mackwe** [comment]
I see. They should be located in the Treatments tab under Careportal. Aren't they?

**Comment by triplem** [comment]
Ah, close. Even better would be, to see these notes in the Bolus list. Carbs and IUs are already listed there, so the notes would be an additional information.

**Comment by triplem** [comment]
There is already an implementation, which I would like to propagate as soon as 2.1 is in development. See https://github.com/triplem/AndroidAPS/tree/treatments_comment.
