### ISSUE TITLE
[Enhancement]: Allow to invalidate already given insuline doses

### ISSUE THREAD

**Issue by triplem** [MilosKozak/AndroidAPS#1451]
While a site is not working and insuline is given, this insuline is used to calculate the IOB. Since the site is/was not working, I would like to invalidate this insuline. Right now, I do have to delete those doses. An even better approach would be to be able to mark those doses as "invalid due to site problems".

**Comment by MilosKozak** [comment]
if driver uses pump history, record is only invalidated
