### ISSUE TITLE
[Enhancement]: Add support for "Custom" commands/actions

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#1455]
When we start integration of Omnipod, we will require Custom command(s)/action(s) (which should be visible together with other Actions (Profile switch, Temporary Target, Prime/Fill, etc). 

There is at least one Command that Omnipod will have: Init Pod, and maybe some others too.

I would propose extending PumpInterface, with following methods

```
List<CustomCommand> getCustomCommands();

PumpEnactResult executeCustomCommand(String key);
```

Class CustomCommand would need following fields: Name, Icon, Key

And of course Tab "Actions", will need to check if currently selected pump has custom commands and if yes display them (and execute them if clicked).

**Comment by AdrianLxM** [comment]
I like that approach!

**Comment by MilosKozak** [comment]
👍

**Comment by andyrozman** [comment]
Should we name it Custom Actions or Custom Commands? Which would be better? 

Also  instead of using key here, we could go with CustomCommandType interface (containing getKey method), so that we could create enums with it.

**Comment by MilosKozak** [comment]
it's up to you

**Comment by andyrozman** [comment]
I started working on this issue and have solution. Its not 100% done yet, but about 80%. i will post a PR as soon as it is ready.

**Comment by andyrozman** [comment]
Since this was merged, I imagine we can close this?

**Comment by andyrozman** [comment]
This was done and merged long time ago, so I am closing this.
