### ISSUE TITLE
[RC10] NS Profile not loaded when only DIA is changed. 

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1464]
Can someone please confirm if you can reproduce?

* Using NS profile
* Change (only) the DIA in NS
* Make profile switch in AAPS
* Check the profile an AAPS and see if the new DIA is reflected.

**Comment by quizzmaster** [comment]
For me everything works as expected.

**Comment by Mackwe** [comment]
I tried numerous times to to avail. When I changed the DIA _and_ CR, both changes occurred.

**Comment by Mackwe** [comment]
Closing this in lack of information, hoping I am the only one affected and/or it was a one-timer.
