### ISSUE TITLE
[dev 2018.09.13] Autosense strange behaviour

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#1467]
I used RC4 for a long time and since I moved to dev, I wonder if autosense works properly because 
I have really often lows.

Some screenshots:
![2018-09-23 04 11 50](https://user-images.githubusercontent.com/24234385/45932492-3c66fe00-bf7d-11e8-8f26-85e06a3f53bb.png)
![2018-09-23 04 12 57](https://user-images.githubusercontent.com/24234385/45932493-3c66fe00-bf7d-11e8-8441-2db18f844f05.png)
![2018-09-23 04 31 33](https://user-images.githubusercontent.com/24234385/45932494-3c66fe00-bf7d-11e8-891f-1a704420f37d.png)
![2018-09-23 04 31 48](https://user-images.githubusercontent.com/24234385/45932495-3c66fe00-bf7d-11e8-9dee-6f27da3c8a7d.png)
![2018-09-23 04 32 51](https://user-images.githubusercontent.com/24234385/45932496-3c66fe00-bf7d-11e8-97fb-a1119876a000.png)
![2018-09-23 04 58 03](https://user-images.githubusercontent.com/24234385/45932497-3cff9480-bf7d-11e8-91c4-bd4a520dccf1.png)

I would expecte that when I BG values where good again, that there would be no more resistance detected but it seems that because of this then I got a low? Or maybe ISF simply wrong?

Otherwise Loop calculate a rate of 0% but on main screen rate is at 10%, could it be a bug?

Thanks
Gregory

**Comment by MilosKozak** [comment]
AS is not related to absolute BG value but to changes compared to insulin impact.
because you have only positive deviations from about 22h AS goes up.
i don't see anything unusual on these screenshots

**Comment by gregorybel** [comment]
ok, thanks Milos! 
any idea then how to avoid low BG?
