### ISSUE TITLE
[RC12] UI bug: User can be locked out during Setup Wizard

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1476]
If you choose not to enter a Nightscout URL in the Setup Wizard, still choosing NS Profiles and NS BG, you have nowhere to enter the URL afterwards. And have no chance to set up profiles, since the NS Client plug-in doesn't load..

As far as I can see, the user needs to completely uninstall and re-install to fix it.

I know this is a tiny bug, but since we are so close to the new Master version, I thought it might be mendable.

**Comment by MilosKozak** [comment]
you can always press "Back" or?

**Comment by Mackwe** [comment]
Not once the Setup Wizard is finished. You then go right into the app and there is no option to add a URL anywhere I could see..

**Comment by AdrianLxM** [comment]
If you open the config builder and click on the settings item next to NSClient. Isn't there the possibility to enter a URL?

**Comment by Mackwe** [comment]
Adrian: You are right. I _can_ enable the plugin (checkbox) from there, activating the settings "gear".  From there I can add the URL.  I also realized you could go to the Top-right menu and re-run Setup Wizard. Closing this as that is a much smaller issue.
