### ISSUE TITLE
Doubling the brackets in profile name when timeshifting

### ISSUE THREAD

**Issue by PoweRGbg** [MilosKozak/AndroidAPS#1480]
When I switch profile with timeshift - it's ok, and after some time ( less than 24 hours usually ) I notice that the brackets after the profile name have doubled. (Screenshots attached )
Version is 2.0g-dev, but It's been for like that for a long time.
![screenshot_20180927-074227_androidaps](https://user-images.githubusercontent.com/21143443/46193950-8eef4400-c308-11e8-9e0c-71cd33fd6df8.jpg)
![screenshot_20180928-070740_androidaps](https://user-images.githubusercontent.com/21143443/46193951-8f87da80-c308-11e8-81f9-3759976a0098.jpg)

**Comment by jotomo** [comment]
@PoweRGbg Hm, I missed the negative timeshift in the regex. If you like, you can test the fix here: https://github.com/jotomo/AndroidAPS/tree/upstream-1480

**Comment by PoweRGbg** [comment]
@jotomo Nice work! My fix is not as elegant as yours :
https://github.com/PoweRGbg/AndroidAPS/commit/87c13da6f619ac5e27c78079f9923a949e279e4a
