### ISSUE TITLE
[RC12] Wrong alarms of 1-2 day old treatment issues

### ISSUE THREAD

**Issue by tKostka** [MilosKozak/AndroidAPS#1482]
AndroidAPS made an unnoticed restart at 2018-09-30 11:24 CEST (for whatever reason). At this restart an Alarm appeared. AndroidAPS now shows that 3 treatments from the day before could not be saved, that did not show up before, so I was assuming everything was fine. See screenshots.

The first and second treatments were OK – data used in all systems and Pump did the Bolus.
The third treatment (22:52) was not OK – Pump did no Bolus, that explains my high bloodsugar with the peak about 01:30 because AAPS did not accept the carbs. I did not get alarms for this errors in time, otherwise I would have checked if it was ok.
**EDIT: also the third treatment (22:52) was ok, i've missread the alarm and checked at the wrong date (28.09. is correct, not 29.09.)**

I did check all my systems if the treatments were saved:
1.	2018-09-29  12:54
2,6 U Insulin, 24g carbs
Error in treatment Tab
Treatment shown in AAPS Overview: YES
Treatment shown in AAPS-Treatment-Tab: YES
Treatment shown in Nightscout: YES
Treatment shown in Pump: YES
Treatment shown in xDrip: YES

2.	2018-09-29  16:32
3,1 U Insulin, 24g carbs
Error NOT in treatment Tab, just in overview at start
Treatment shown in AAPS Overview: YES
Treatment shown in AAPS-Treatment-Tab: YES
Treatment shown in Nightscout: YES
Treatment shown in Pump:YES
Treatment shown in xDrip: YES

3.	2018-09-29  22:52 **EDIT: 2018-09-28 instead of 2018-09-29**
5,1 U Insulin, 25g carbs
EDIT: Treatments OK

AndroidAPS RC 12
Motorola G5 Plus, LineageOS 14.1
Accu-Chek Combo

EDIT: The issue here is that AndroidAPS gave 2 old Alarms at the startup, the treatments itself  were all OK.

I will send logfiles in AndroidAPS.
![screenshot_20180930-112505](https://user-images.githubusercontent.com/11375777/46257201-4aa1a680-c4b6-11e8-8bcc-d87416e2e47b.png)
![screenshot_20180930-112536](https://user-images.githubusercontent.com/11375777/46257202-4aa1a680-c4b6-11e8-86d2-f82df62f291d.png)
![screenshot_20180930-112629](https://user-images.githubusercontent.com/11375777/46257203-4aa1a680-c4b6-11e8-9ea6-d0a8f685480c.png)
![screenshot_20180930-122701](https://user-images.githubusercontent.com/11375777/46257204-4b3a3d00-c4b6-11e8-98e4-ec81983da851.png)
![screenshot_20180930-123128](https://user-images.githubusercontent.com/11375777/46257205-4b3a3d00-c4b6-11e8-8b88-7bb633a318c5.png)
![screenshot_20180930-132612](https://user-images.githubusercontent.com/11375777/46257206-4b3a3d00-c4b6-11e8-8298-f41703ef286f.png)

**Comment by tKostka** [comment]
I have to edit this issue as i have noticed i have missread the date of the first alarm, it is from 28.09. not 29.09.  So i have checked the correct date (28.09.2018 22:52), there AndroidAPS did give the Bolus and this is OK.

The only issue left is the wrong Alarm at startup, the treatments are all correctly given and stored in AndroidAPS.
Sorry for the confusion.

Attached the AndroidAPS logs.
[Logs-AndroidAPS_1482.zip](https://github.com/MilosKozak/AndroidAPS/files/2446056/Logs-AndroidAPS_1482.zip)

**Comment by MilosKozak** [comment]
do you have screenshot of these alarms?

**Comment by tKostka** [comment]
They are attached here. In fact it was one alarm (the first picture) and the other was one of theese organge info-textboxes (second picture). The screenshots were made at 2018-09-30 11:25.

**Comment by MilosKozak** [comment]
do you mean notification regarding bolus?

**Comment by tKostka** [comment]
Yes, the alarm and notification regarding bolus and carbs. They did not come at the time of treatments happend, the first screenshot shows an alarm of an event 2 days in the past, the other notification shows an event 1 day in the past. 
Both events were ok and there were no notifications/alarms at the moment of generation.

**Comment by jotomo** [comment]
```
11:24:49.501 [Thread-14] D/DATATREATMENTS: [TreatmentService.createOrUpdate():294]: 
Pump record already found in database: 
Treatment{date= 1538218465000, date= 29.09.2018 12:54:25, isValid= true, isSMB= false, _id= 5baf59fad01655c9d1dd9730, pumpId= 0, insulin= 2.6, carbs= 24.0, mealBolus= true} 
wanting to add 
Treatment{date= 1538218465000, date= 29.09.2018 12:54:25, isValid= true, isSMB= false, _id= null, pumpId= 1538218465000, insulin= 2.6, carbs= 0.0, mealBolus= false}
11:24:49.519 [Thread-14] E/DATATREATMENTS: [TreatmentsPlugin.addToHistoryTreatment():527]: Treatment could not be added to DB
```
Observations:
1) The record coming from the pump is determined to be different to the one in the DB (in _TreatmentService:264/290_), since the DB record has carbs, but the pump record has not (since the Combo doesn't store carbs). Best guess, a carb record and a pump history record were merged in _TreatmentService:273_ (a somewhat recent change, https://github.com/MilosKozak/AndroidAPS/commit/b435c09771f29ad4ded750fd77230876ddf3b75e#diff-aeb9212f46d07b69ff2020f52b8979feR261 @AdrianLxM )
2) _TreatmentsPlugin:520_: return value should probably be checked (or just be logged for debugging), might be related to the second issue: the pumpId of the existing record being 0 (I'm rather certain the ComboPlugin never created a record with such a pumpId), which triggers the ComboPlugin to add the record read from history to the DB, calling _TreatmentsPlugin.addToHistoryTreatment_ with parameter _allowUpdate_ set to false.
This parameter was added a few months back, before that, all existing records were simply overridden (likely without changing anything). Currently, the errors produced are false negatives. So to allow for the carb/insulin record merging (which effectively means DB-side records differ from pump records) and without further complication the merge logic, the ComboPlugin could be changed to make the invocation with _allowUpdate=true_ (if doing so, please add a comment/link explaining the behaviour to keep the code maintainable; also setting the _updated_ field to _true_ if the call returned _true_, indicating a new record was created. Basically reverting to the previous state: https://github.com/MilosKozak/AndroidAPS/blob/combo/app/src/main/java/info/nightscout/androidaps/plugins/PumpCombo/ComboPlugin.java#L1160).

**Comment by MilosKozak** [comment]
this is probably comming from NS sync

**Comment by andyrozman** [comment]
I have similar problem. I upgraded from AAPS 1.58 Combo to 2.0_dev (rc12) and on every start I get this errors that entries couldn't be added:
`10:50:26.371 [Thread-28] D/DATATREATMENTS: [TreatmentService.createOrUpdate():294]: Pump record already found in database: Treatment{date= 1538991788000, date= 8 DFómh 2018 10:43:08, isValid= true, isSMB= false, _id= e828f11a2ab542adb0bb24af, pumpId= 0, insulin= 0.9, carbs= 0.0, mealBolus= false} wanting to add Treatment{date= 1538991788000, date= 8 DFómh 2018 10:43:08, isValid= true, isSMB= false, _id= null, pumpId= 1538991788000, insulin= 0.9, carbs= 0.0, mealBolus= false}
10:50:26.383 [Thread-28] D/DATATREATMENTS: [TreatmentService.createOrUpdate():294]: Pump record already found in database: Treatment{date= 1538952401000, date= 7 DFómh 2018 23:46:41, isValid= true, isSMB= false, _id= 3df1f4c76d6d4489868eaae0, pumpId= 0, insulin= 4.2, carbs= 0.0, mealBolus= false} wanting to add Treatment{date= 1538952401000, date= 7 DFómh 2018 23:46:41, isValid= true, isSMB= false, _id= null, pumpId= 1538952401000, insulin= 4.2, carbs= 0.0, mealBolus= false}
10:50:26.393 [Thread-28] D/DATATREATMENTS: [TreatmentService.createOrUpdate():294]: Pump record already found in database: Treatment{date= 1538942579000, date= 7 DFómh 2018 21:02:59, isValid= true, isSMB= false, _id= ed5d93b1076a4ebabb6d7df3, pumpId= 0, insulin= 10.2, carbs= 40.0, mealBolus= true} wanting to add Treatment{date= 1538942579000, date= 7 DFómh 2018 21:02:59, isValid= true, isSMB= false, _id= null, pumpId= 1538942579000, insulin= 10.2, carbs= 0.0, mealBolus= false}
10:50:26.399 [Thread-28] E/DATATREATMENTS: [TreatmentsPlugin.addToHistoryTreatment():527]: Treatment could not be added to DB
java.lang.Exception: null
	at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.addToHistoryTreatment(TreatmentsPlugin.java:527) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.updateDbFromPumpHistory(ComboPlugin.java:1162) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.checkHistory(ComboPlugin.java:1239) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.runOnConnectChecks(ComboPlugin.java:956) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.runCommand(ComboPlugin.java:865) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.initializePump(ComboPlugin.java:362) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpCombo.ComboPlugin.getPumpStatus(ComboPlugin.java:341) ~[na:0.0]
	at info.nightscout.androidaps.queue.commands.CommandReadStatus.execute(CommandReadStatus.java:31) ~[na:0.0]
	at info.nightscout.androidaps.queue.QueueThread.run(QueueThread.java:145) ~[na:0.0]
10:50:26.424 [Thread-28] D/DATATREATMENTS: [TreatmentService.createOrUpdate():294]: Pump record already found in database: Treatment{date= 1538914212000, date= 7 DFómh 2018 13:10:12, isValid= true, isSMB= false, _id= aa1de23b879a467e86a0f2f4, pumpId= 0, insulin= 1.3, carbs= 0.0, mealBolus= false} wanting to add Treatment{date= 1538914212000, date= 7 DFómh 2018 13:10:12, isValid= true, isSMB= false, _id= null, pumpId= 1538914212000, insulin= 1.3, carbs= 0.0, mealBolus= false}`

**Comment by tKostka** [comment]
OK with AAPS 2.0
