### ISSUE TITLE
[RC 12] COB seems to have problems + SMB was delivered when falling BG

### ISSUE THREAD

**Issue by BastianBickelhaupt** [MilosKozak/AndroidAPS#1483]
Yesterday at dinner i entered eCarbs with 1h. You can see the history of added carbs inside the treatment screenshots. I also bolused for 40gr directly. So it was 2x20gr eCarbs (1h) and 40gr bolus via calculator. Later that evening i also entered 24gr more eCarbs with no duration.

Another thing which is very strange: I have carb absorb 4h. My last entered carbs were at 22:10 (24gr) 
At 00:41 i still had 41 COB. At 1:09 I had 5 COB left

Another strange thing was that SMB was delivering multiple Boluses even if the BG was falling.

Logs were send to you via email. Thank you! Let me know if you need more information.
![screenshot_20181002-091412](https://user-images.githubusercontent.com/14124112/46335567-2bc32180-c628-11e8-9d4a-2ff8f8decb84.png)
![screenshot_20181002-091441](https://user-images.githubusercontent.com/14124112/46335568-2bc32180-c628-11e8-8b18-31417f189e56.png)
![screenshot_20181002-094237](https://user-images.githubusercontent.com/14124112/46335569-2c5bb800-c628-11e8-8589-194ce5604b55.png)
![screenshot_20181002-094245](https://user-images.githubusercontent.com/14124112/46335571-2c5bb800-c628-11e8-9b80-f18feb22a5fe.png)

**Comment by MilosKozak** [comment]
what sensistivity model?

**Comment by BastianBickelhaupt** [comment]
Oref1

**Comment by MilosKozak** [comment]
sorry logs files received not contain interrested time range. can you send it manually please?

**Comment by MilosKozak** [comment]
logs are zipped every few hours. date is in the name of the file

**Comment by BastianBickelhaupt** [comment]
i think i am ok for now, i will keep an eye on that. i guess it was correct behaviour ...
