### ISSUE TITLE
[Enhancement]: Alarm when battery is getting low

### ISSUE THREAD

**Issue by AlexD97** [MilosKozak/AndroidAPS#1486]
Would it be possible to alarm the user when (DanaR) battery has only e.g. 2 bars left? #589 #1057

**Comment by schmitzn** [comment]
Have a look at https://github.com/MilosKozak/AndroidAPS/pull/1107

**Comment by andyrozman** [comment]
I think you can set that in Nightscout too (to get battery warnings)

**Comment by TebbeUbben** [comment]
Duplicate of #1486
