### ISSUE TITLE
[Safety Enhancement] In the release branch, restrict the combinations of usable factors for an algorithm. 

### ISSUE THREAD

**Issue by tim2000s** [MilosKozak/AndroidAPS#1491]
The master & RC versions of a release should only contain settings that have been confirmed to work during the testing process, and it should not be possible to set combinations that are know to have unusual outcomes or unknown outcomes. 

For example, when using the  oref1 algorithm, oref1 sens and UAM should be the only configuration that can be used, due to other sens settings resulting in incorrect attribution of UAM as deviations.   

Likewise, unless combinations of settings have been properly tested and documented in the documentation, they should not be possible to set in a master release version. 

Anyone building the dev version may have access to whatever they

**Comment by Mackwe** [comment]
In my opinion, the option to use Superbolus should not be available using the SMB algorithm, since superbolusing is implicitly used anyhow. Using superbolusing with SMB might deliver a bigger bolus (unsafe) than the user might have wanted.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/c1bbaab8e139d64f4254ef03f859bc7e4a120e99
thanks!
