### ISSUE TITLE
Carb update missed in OverviewFragment and WizardDialog resulting in wrongly calculated bolus

### ISSUE THREAD

**Issue by kuchjir** [MilosKozak/AndroidAPS#1493]
**Problem description:**
Sometimes new carbs are entered in WizardDialog and the calculated bolus gets delivered. But then the new carbs are not propagated into refreshed OverviewFragment and also when WizardDialog is started again the carbs are not present there. 

If I understand correctly the existing carbs (aka cob) is obtained by calling IobCobCalculatorPlugin.getLastAutosensData(). There is also synchronized version of this method named getLastAutosensDataSynchronized() but it is used very little. To me it is not clear why the unsync method is used so often. It could be really problem as the autosense data are accessed/modified from different threads so the synchronized version should be used all the time. Otherwise each thread is using different version of autosense data resulting in weird behavior. I am curious if there is some reason why the data are accessed without synchronization. 

I am still on v1.55 but I see the same code in the latest v2.0.

**Comment by MilosKozak** [comment]
try rc13

**Comment by kuchjir** [comment]
I can see the same pattern in rc13. The autosens data are accessed without synchronization from different threads. Can you please clarify why IobCobCalculatorPlugin.getCobInfo(boolean _synchronized, String reason) is often invoked with _synchronized parameter set to false. It does not make sense to access shared data and use synchronized only sometimes.

**Comment by jotomo** [comment]
IobCob calculations are performed only when a new BG arrives, so carbs entered are only taken into account after the next BG arrived. Thus, in v1.55, the calculator will be out-of-date for up to 5m after entering carbs. In v2.x, the class _CobInfo_ has been added and is returned from _IobCobCalculatorPlugin.getCobInfo_ to deal with this.

**Comment by kuchjir** [comment]
Thanks for the explanation. But it is still not clear why synchronized is not used all the time when autosens data are accessed. I am talking about pure java concurrency problem. When a value is accessed by different threads then some memory barrier must be in place all the time. But  IobCobCalculatorPlugin.getCobInfo uses memory barrier (java synchronized keyword) only sometimes. It leads to nasty bugs, hard to catch as they happen randomly. Especially with quad/octa core processors used in nowadays phones this is a real issue. I think it is a bug. But as I have no experience with Android I would like to hear reasoning why this conditional memory barrier was introduced in IobCobCalculatorPlugin.getCobInfo(). Maybe there is a valid reason.

**Comment by MilosKozak** [comment]
The code in 2.0 is by 80% new (specially in IOB-COB code).
Update to RC13 and provide log files in new issue  if you can reproduce it.
Closing for now as it is not enough info to resolve it

**Comment by jotomo** [comment]
@kuchjir _synchronized_ should be avoided when called from UI thread, to not block the UI (and where returning an older value isn't critical, so not whet gathering data for oref0). Though _OverviewFragment:1367_ does just that ...
