### ISSUE TITLE
[RC13] Carb absorption calculated wrong with SMB

### ISSUE THREAD

**Issue by iversenshotrods** [MilosKozak/AndroidAPS#1497]
Possible same issue as 1478. 1:39pm entered  93g meal. Max meal absorption time set at 4hr. At approx 5pm COB still showed 51g. 

Running LG V20 Lineage 15.1 with AAPS RC13

[AndroidAPS._2018-10-09_00-00-04_.9.zip](https://github.com/MilosKozak/AndroidAPS/files/2463277/AndroidAPS._2018-10-09_00-00-04_.9.zip)
[AndroidAPS._2018-10-09_17-52-50_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2463278/AndroidAPS._2018-10-09_17-52-50_.0.zip)

**Comment by MilosKozak** [comment]
there is no bug. it works like expected.
you problem is that your profile do not match reality and algorithm always fallbacks to min carbs absorption rate. you set it to 3 which is value recommended to AMA. but for SMB it should be at least 8.
All this leads to slow decreasing of COB
@AdrianLxM

**Comment by iversenshotrods** [comment]
App has consistently been set at 8 for min_5m_carbimpact and verified again yesterday it was at 8 while running autotune. 

As of today I am running 10 for min_5m_carbimpact and it seems to be keeping my numbers more stable than when set at 8 previously.
