### ISSUE TITLE
[RC13] 'Bolusing interrupted' error but pump has delivered the whole previously chosen bolus

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#1500]
I asked AAPS RC 13 for a meal bolus of 10.10 IE using Wizard. An alarm was given: bolus not completely deleivered. Furtheron, IOB was only calculated by a part of asked meal bolus. DanaR statistics say that the asked bolus of 10.10 was completely given. I did not bolus twice and BG was OK, so I'm pretty sure the "not completely delivered" alarm was wrong.

![20181012_101243](https://user-images.githubusercontent.com/32912987/46856933-055f6c00-ce08-11e8-98c6-4a5095e87176.jpg)

11T15:33:10Z"}},"uploaderBattery":6,"created_at":"2018-10-11T15:35:00Z"}
17:35:00.358 [Thread-32932] D/PUMPQUEUE: [CommandReadStatus.execute():34]: CommandReadStatus executed. **Reason: bolusingInterrupted**
17:35:00.361 [Thread-32932] D/PUMP: [DanaRExecutionService$1.run():347]: Bolus amount in history too old: 11.10.18 17:34:00 Mitteleuropäische Sommerzeit
17:35:00.366 [Thread-32904] D/PUMP: [DanaRPlugin.deliverTreatment():178]: deliverTreatment: OK. **Asked: 10.100000000000001 Delivered: 2.100000000000001**
17:35:00.367 [Thread-32904] D/DATABASE: [DatabaseHelper.roundDateToSec():328]: Rounding 1539272100367 to 1539272100000
17:35:00.462 [Thread-32932] D/PUMPQUEUE: [QueueThread.run():168]: waiting for disconnect
17:35:00.514 [Thread-32904] D/DATATREATMENTS: [TreatmentService.createOrUpdate():372]: New record from: USER Treatment{date= 1539272100000, date= 11.10.2018 17:35:00, isValid= true, isSMB= false, _id= null, pumpId= 0, insulin= 2.100000000000001, carbs= 0.0, mealBolus= false}

**Comment by MilosKozak** [comment]
This is usually caused by interrupted communication with pump. AAPS try some recovery but this is not 100% possible.
Upgrade your pump to v2 and use v2 driver. v2 driver uses history so issues like this are covered

**Comment by typ1-brods** [comment]
Thanks milos. How to Upgrade to V2? I ever thought this only SOOIL can do

**Comment by MilosKozak** [comment]
Search in FB group
