### ISSUE TITLE
[RC14] two BG sources mixed over each other

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#1509]
RC14.
Today I changed BG source from Nightscout to xDrip.
I got the two sources mixed over each other (see screenshot). time I noticed: 20:45 (time of screenshot)
[AndroidAPS_LOG_1539801929862.log.zip](https://github.com/MilosKozak/AndroidAPS/files/2488847/AndroidAPS_LOG_1539801929862.log.zip)
[AndroidAPS._2018-10-17_14-50-28_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2488870/AndroidAPS._2018-10-17_14-50-28_.0.zip)
[AndroidAPS._2018-10-17_14-52-26_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2488871/AndroidAPS._2018-10-17_14-52-26_.0.zip)

![screenshot_androidaps_20181017-204506](https://user-images.githubusercontent.com/28272471/47109912-cf7b1700-d24f-11e8-8660-3bd7ede1b664.png)
![screenshot_androidaps_20181017-204522](https://user-images.githubusercontent.com/28272471/47109913-d013ad80-d24f-11e8-80b4-f8a8ca751b1b.png)

**Comment by jotomo** [comment]
The NSClient plugin has an option "Autoback-fill BG", which is likely enabled in your setup, which causes readings from NS to be imported alongside values received from xDrip. Disable it to only receive values from the new BG source (xDrip).

**Comment by hartlijn** [comment]
@jotomo you are right. I disabled this function. thanks
little bit confusing, but not an issue to me. #closed
