### ISSUE TITLE
[DEV branch from 20181018] Loop stopped working - Potential issue?

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#1514]
Phone: Unihertz ATOM (all updates installed, all energy savings disabled)
AAPS version: DEV date 18.10.2018
No recent changes to settings. Phone with AAPS was working successful for the last couple of days without issues. 

Last night Loop stopped working out of nowhere, last activity was around midnight 00:00 (setting basal to 0). AAPS was running all night, receiving BG values, OpenAPS pill was making suggestions but Loop process was not acting. 

![image](https://user-images.githubusercontent.com/38214111/47338131-0f4e5e00-d697-11e8-9e44-b8b59c9d8f13.png)
![image](https://user-images.githubusercontent.com/38214111/47338139-137a7b80-d697-11e8-991d-af76599df6bf.png)
![image](https://user-images.githubusercontent.com/38214111/47338145-17a69900-d697-11e8-98eb-51b09acb88d7.png)
![image](https://user-images.githubusercontent.com/38214111/47338148-1a08f300-d697-11e8-8228-b8200ee7be48.png)
[logs.zip](https://github.com/MilosKozak/AndroidAPS/files/2504642/logs.zip)

This morning 06:00 I closed AAPS and did a restart. Loop is working again since. 

Not sure if it is possible and if then how to re-produce the behaviour, maybe it was a one-time issue but still perhaps someone is able to read something out of the logs?!

**Comment by 2flea** [comment]
![image](https://user-images.githubusercontent.com/38214111/47338705-39a11b00-d699-11e8-82e8-6df3ad51eb6e.png)

**Comment by 2flea** [comment]
I just had a look in the logs to try to understand what might be the problem. 
I found several logs indicating that the communication to the pump (Dana RS) was not working. 
Starting 00:09:44 (hh:mi:ss) the only logs related to PUMP, PUMPBTCOMM, PUMPQUEUE were like following:

00:58:37.076 [pool-6-thread-1] D/PUMPQUEUE: [CommandQueue.setProfile():356]: Correct profile already set

No PUMPBTCOMM using BLEComm any more. Last log message for PUMPBTCOMM was a warning:

00:09:42.523 [Thread-10808] W/PUMPBTCOMM: [BLEComm.sendMessage():645]: Reply not received APS_HISTORY_EVENTS

I have attached two files with the results of searching for "/PUMP" and "BLEComm." in my log file set uploaded. 

Anyone an idea why the connection to the pump did stop and was not re-tried?

[SearchResults_BLEComm.xlsx](https://github.com/MilosKozak/AndroidAPS/files/2506638/SearchResults_BLEComm.xlsx)
[SearchResults_PUMP.xlsx](https://github.com/MilosKozak/AndroidAPS/files/2506639/SearchResults_PUMP.xlsx)

**Comment by 2flea** [comment]
I close this issue for now as I think it is phone related. Others have similar problems with Atoms Bluetooth. We are in contact with the manufacturer.

**Comment by 4rT0X** [comment]
I quickly dig up that issue to ask if it has been really solved and if @2flea has encountered anyother issue using unihertz atom.

**Comment by 2flea** [comment]
@4rT0X I don't use Atom any longer since 11 months, never managed a stable BT connection over days. Switched to a one-phone solution rather than two phones. 
There were several firmware updates for the Atom in the meantime, also Android 9. No idea if it is working now though.

**Comment by 4rT0X** [comment]
@2flea too bad, I was seriously considering it as a good candidate for that usage. Have you sold the Atom or just did not take the to check if it has been fixed?

**Comment by 2flea** [comment]
Sold it

**Comment by 4rT0X** [comment]
Ok, and by the time did you consider some other tiny android solution?
