### ISSUE TITLE
RC14/DanaRV2: TBR differs between AAPS and pump

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#1524]
The Dana display says TBR 20%, RC14 says TBR 0%. Refreshing using BT symbol several times was successful. The TBRs differ. Pump is connected.
DanaRV2, AAPS RC14, G5, xDrip+

![44882428_2003677246344895_4260478906181615616_n](https://user-images.githubusercontent.com/32912987/47601039-01684800-d9cb-11e8-8aed-3e2ec27a1507.jpg)
![44830453_2003676889678264_4499151673339412480_n](https://user-images.githubusercontent.com/32912987/47601040-01684800-d9cb-11e8-968b-bc7c3094ae26.jpg)

**Comment by typ1-brods** [comment]
I have sent the logfiles via AAPS/Email

**Comment by MilosKozak** [comment]
I need earlier logs

**Comment by typ1-brods** [comment]
You got mail

**Comment by MilosKozak** [comment]
Pump was not providing history at all. And it happened right after you switched to westafrican time.
Looks like we have to warn people next time not to do this.
@AdrianLxM

**Comment by MilosKozak** [comment]
Update. It happened when you switched to african time and then back to CET

**Comment by MilosKozak** [comment]
update 2: when playing with timezones you switched your time to the future. and that was the main reason

**Comment by typ1-brods** [comment]
Thank you, Milos ! Sorry for that, I had no idea that this could be the reason.
