### ISSUE TITLE
[RC14] NSClient. Deleting carbs from treatments tab remain in NSClient

### ISSUE THREAD

**Issue by pedroll** [MilosKozak/AndroidAPS#1533]
Deleting carbs from treatments tab in AAPS full release, remain in NSClient. Treatments correctly deleted in NS but NSClient doesnt delete treatments.
Treatments entered from bolus wizard.

**Comment by MilosKozak** [comment]
master version?

**Comment by MilosKozak** [comment]
provide log files pls

**Comment by pedroll** [comment]
Logs sended by app.
13:13 deleted treatment in AAPS - 13:43 40g at 13:43 - Marked as invalid remains in nsclient
13:26 deleted from NSClient phone 2 Deleted fron NS and aaps
at 19:45 aprox opened another Nsclient phone3 treatment still remains in this phone do you ned this phone log?
I do not know if it is related to this problem, but some SMB boluses are not synchronized at the time of opening NSclient, and I have to restart the application to be able to see IOB updated
