### ISSUE TITLE
[AndroidAPS 2.0] Problems with profil switches and constantly updating pump profil

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1552]
I had the problem that AAPS always showed the information that the pump profil was changed (every 10 minutes.... ) although I'm using the local profil.  (see facebook entry https://www.facebook.com/groups/loopedDE/permalink/710435772667581/ ).

I found some points that can be helpful finding the error and make a solution.

The main problem is caused of profil switches in AAPS. They are tranfered to the pump as well as to NS. And here is my problem --> after making a profil switch the day to day report in NS cannot be used any more.
Besides that the default NS profile sometimes is fetched from APPS instead of the local profil

To solve this problem I did these solutions:
1) First I had to change the default NS profil so that it is the same as the local one
2) I deletet all profile treatments in NS 

After that the day to day report in NS can be used again but the problem is now that in APPS a warning is coming that no profile is activated any more (why ????? --> I'm using the local profil and don't want the NS profile any more).

I will attach my log files but I'm sorry that after my business trip the problems don't seem to exist anymore. I'm not sure wyh?

What did I change although. I'm mnot using XDRIP anymore because of connecting problems to the CGM miaomiao. Instead I'm using Glimp.

[AndroidAPS_LOG_1541704962634.log.zip](https://github.com/MilosKozak/AndroidAPS/files/2563566/AndroidAPS_LOG_1541704962634.log.zip)

**Comment by AdrianLxM** [comment]
If you delete the profile switches in Nightscout and download the data to AndroidAPS ("upload only" deactivated), it is only logical that you don't have a profile switch in AndroidAPS.
