### ISSUE TITLE
[AndroidAPS 2.0] local profil --> dana profile DANAR-1

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1553]
I'm using the DANA RS pump but use a local profil.

The local profile is automatically transfered to the dana pump (profil DanaR-1). That's perfect.

But only the basal values are saved in the dana pump. IC, ISF are missing or are incomplete. That can be a problem if you have to use the pump manually because of smartphone problems. 

Is this an error or enhancement ??
![screenshot_20181108-220223_androidaps](https://user-images.githubusercontent.com/37514390/48227435-a3f8d180-e3a2-11e8-9d4a-38819cc61e81.jpg)
![screenshot_20181108-220304_androidaps](https://user-images.githubusercontent.com/37514390/48227446-a9561c00-e3a2-11e8-80ea-619c91d0ffcd.jpg)

**Comment by AdrianLxM** [comment]
The Dana-RS firmware does not support IC/ISF over 24 hours. There is no way we can change that. Only Sooil could change their firmware on the pump.
