### ISSUE TITLE
Implement Android default notification behavior

### ISSUE THREAD

**Issue by opal06** [MilosKozak/AndroidAPS#1573]
Currently, I see two issues with the notifications e.g. for "pump unreachable". In both cases, the app does not follow the Android default behavior for notifications which creates some problems imho. Here is why:

First, I have noticed that the app seems to use the media audio channel for its alerts. This comes with the problem that it essentially bricks features like vibration only and Do Not Disturb (DND), as media audio is not always muted by default on these settings. So while the user might think that he will not be disturbed (e.g. at school, library, meeting etc.) alerts will still be played. This behavior can be quite annoying especially as users should be able to wear the system everywhere. 
Second, the app does not show a notification in the notification shade but only in the app itself. This is a strange behavior, as it makes it impossible for the user to quickly locate the reason for the alert, as well as dismiss it quickly by deleting the notification. 
I think that by adopting the Android default behavior for notifications would add both to usability as well as safety. It would allow the user to more intuitively control when sounds are played and how to mute them. At the same time it would keep the user safe and aware of alerts offering a visual notification that can also be mirrored to smart watches. For example, if the user is in an important meeting or in class and does not want any alarms to go off, they can use DND or vibration. Yet, they will get informed by a visual alert that something with their set-up is wrong.

**Comment by tanja3981** [comment]
Regarding your second comment: Go to preferences, scroll down to "Other" and select "Use system notifications for alerts and notifications".

**Comment by opal06** [comment]
@tanja3981 This is true, thank you.

**Comment by BenoMeno** [comment]
For the first part I tought maybe when the "Use system notifications for alerts and notifications" is selected, the in-app notification should be turned off (or at least muted) so there would be no alarm when the phone is in DND and the media volume is higher than 0. I have no experience with android apps but I'm trying my best to understand the notification part of the app.
