### ISSUE TITLE
[Enhancement] Automatic profile switch in response to high BG

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1576]
High BG can be associated with a marked difference in insulin sensitivity, leading to the loop having difficulty in returning out of range BG to the normal range due to algorithm constraints.

This enhancement requests that there is a user configurable BG threshold which will cause AAPS to enact a profile switch to a second Nightscout profile named in the preferences. When BG drops back below the threshold BG the switch will be reversed back to the default profile.

This will allow the user to define a “recovery” profile more suited to gaining control over stubbornly high BG events.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by gempickfordwaugh** [comment]
I feel it would be safer to do a % profile switch rather than a named profile switch, given how often people choose a setting in their preferences then have good enough bloods to not use it for a while then are surprised when it happens. As profile changes may be frequently done in day to day management it would be safer to just make adjustments to current profile rather than default to a new/different profile that may no longer be relevent to the person's needs.

**Comment by roppenheimer** [comment]
A % profile switch may be useful to some people, but it does not give the same flexibility that a switch to a different profile would. It certainly wouldn't do what I need it to do as it would constrain the proportions between the various parameters in the profile.

**Comment by jigme** [comment]
I support this feature request.  i definitely experience increased IR at higher BG.  i have only just started to use a pump; i specifically chose a DanaRS to be able to loop.   on MDI, for many years I've been using about 150% of my usual correction dose at BG >10mmol/l – in fact, I was taught to do this when i first learned about carb-counting and MDI many years ago, and i always thought it was standard practice.  i've been very surprised to find that it doesn't seem to apply to everyone!  in my case, if i'm *really* high, like 18+, then the % i need is even higher.  i was quite concerned when i discovered that this isn't yet a part of the APS systems and i guess, once i've started looping and worked through the objectives, that i'll create a different, more aggressive profile to switch to manually if my BG goes high.  it would certainly be easier for me if this was an automatic feature available to be enabled or not by users in AAPS.
many thanks indeed for all your hard work on this life-changing - probably life-saving - system.

**Comment by AdrianLxM** [comment]
This imho should be addressed in the loop algorithm and not in the underlying settings.
-> OpenAPS

**Comment by Heiner1** [comment]
@AdrianLxM  I understand you, but the algorithm has to be as safe as possible **for all**; so I think there's no way to integrate such (for some people unsafe) features; with dasiglucagon as a hypo controlling hormon there would be a chance; on the other hand my testing experience with automation branch showed me good results in that resistance BG-ranges

**Comment by MilosKozak** [comment]
Resolved in Automation
