### ISSUE TITLE
SMS confirmation codes

### ISSUE THREAD

**Issue by maba76** [MilosKozak/AndroidAPS#1578]
The SMS command feature is really great, but would it be possible to exclude capital 'i' and lower case 'L' from the autogenerated SMS confirmation codes?! As both letters look identical it is impossible to know which one to use, which can cause quite annoying 'wrong replies'. 
Many thanks!

**Comment by cascer1** [comment]
Looks like this was implemented in https://github.com/MilosKozak/AndroidAPS/commit/e1a82cc78eb6621342046c3e532e7f8dd2cc5faf

**Comment by maba76** [comment]
That is fantastic news! Many thanks.
