### ISSUE TITLE
[Enhancement] - deprioritisation of far future predictions 

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#1583]
The existing algorithm contains a number of parameters such as minGuardBG which are designed to prevent the loop sending the user into a low BG status in the duration of DIA. However, when using the newer exponential insulin profiles this can be up to 7 hours in the future by which time the forecasts will have a very low confidence level. Even so, they may override near term events, such as persistent high BG states and suspend insulin delivery. This enhancement proposes that these forecast events are ignored if they occur more than (say) three hours in the future thereby only triggering loop decisions when there is a reasonable degree of confidence.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by AdrianLxM** [comment]
1) Where do you get the DIA assumption from?
2) Does the lower part of your bug report have any relevance or is just the standard text?

**Comment by roppenheimer** [comment]
AFAIK the decision point for these safety features is measured along the entire length of the COB and/or UAM forecast which stretches to the end of DIA. There is nowhere that these forecasts are truncated and therefore a decision can be made based on an event which is far in the future. If I am wrong please can you point in the code where this truncation occurs.

**Comment by jotomo** [comment]
>  point in the code where this truncation occurs.

The code block generating predictions: https://github.com/MilosKozak/AndroidAPS/blob/master/app/src/main/assets/OpenAPSSMB/determine-basal.js#L530

**Comment by roppenheimer** [comment]
That is helpful, thank you
