### ISSUE TITLE
Feature request: If AAPS prediction curve outcome in next <2 hours is below low range, then zero temp irrespective of carbs on board

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#1590]
At the moment when the eventual BG is predicted to be in range and there are carbs on board, AAPS does not suggest a zero temp if the short-term BG prediction (as illustrated by the orange prediction lines) goes into hypo range before eventually rising due to the presence of COB.

Often the carb amount can be entered incorrectly or other factors. If BG is predicted to be low even where eventually predicted to be in range, a zero temp suggestion at the earliest possible opportunity would help prevent a hypo.

Feature request:
If AAPS prediction curve outcome in next <2 hours is below low range, then zero temp irrespective of carbs on board.

**Comment by AdrianLxM** [comment]
I see this rather as a bug report, not as a feature request. Please provide data.

**Comment by tim2000s** [comment]
The algorithm is designed to issue a zero temp until there is no value in the prediction line below the threshold level, which in minBG- 0.5*(minBG-40). MinBG is your target BG sonic your target is five, your threshold is 65 or 3.6. 

The visualisation shows the four components used to create the prediction so while any one of those may show below your low level, it doesn't mean that the prediction is there.

**Comment by MilosKozak** [comment]
alg change should be suggested to OpenAPS. we keep code alligned witn OAPS repo
