### ISSUE TITLE
[feature request]: allow SMB-always with G5 xdrip algorithm

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#1592]
As a G5 CGM user with xDrip I would like to be free to choose for the xDrip algorithm (and not forced to use native mode), so that I can use the full potential of the AAPS SMB functionality ánd so that I have the benefits of a more stable and accurate CGM with the xDrip algorithm.

currently OB1 + Native mode is requied in xDrip to support full SMB features with Dexcom G5 as CGM.
often the xdrip algorithm is more accurate and connection more stable. 

- [ ] receive from xDrip the noise-level (startup/low/high/very high)
- [ ] remove current restriction on SMB-always and SMB-aftercarbs, when noise level is LOW
- [ ] show in SMB status/log the actual noise level (to understand if a SMB feature is disabled due to too high noise)

(OpenAPS seems to have this in place as well in this way)

**Comment by AdrianLxM** [comment]
Here the discussion is rather if we should make it a hidden setting like in OpenAPS or not.

The issue with non-native G5/G6 data is simply: we don't know if it stops being sent when the sensor gets noisy. So it's a safety issue.

If xDrip would add to the broadcast that the data is good - and blocking of noise at a lower level than "extreme" is activated, we could do that.
