### ISSUE TITLE
Quick Wizard doesnt work with Insight Pump

### ISSUE THREAD

**Issue by Dave2526** [MilosKozak/AndroidAPS#1594]
When I want to get a Bolus by Quick WIzard, I get the following Error. 
AndroidAPS 2.0 Build c7ab2ae47-2019.01.04

Logfile is below the screenshots

![screenshot_20190105-103645](https://user-images.githubusercontent.com/36053025/50723146-012aae00-10da-11e9-95dd-d091e36df5df.jpg)
![screenshot_20190105-103657](https://user-images.githubusercontent.com/36053025/50723148-05ef6200-10da-11e9-90e2-e58ee608defc.jpg)
![screenshot_20190105-103811](https://user-images.githubusercontent.com/36053025/50723150-08ea5280-10da-11e9-9bcf-80271ef30b4e.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2729401/AndroidAPS.log)

**Comment by wootmasterslick** [comment]
That is odd, we are using AAPS also with insight pump and don't have this problem. Are you using sightremote and did you enable engineering mode for AAPS? After that you get the option to select the insight pump in the config section.

**Comment by Dave2526** [comment]
Yes I use sightremote, and I use all features. All works but this one not. My loop works in closed mode since a halve year

**Comment by Dave2526** [comment]
i have searched in the log files for the error, i hope it will help.
by the way, the wear wizard doesn´t work too. but only when i entered more than 18gr carbonhydrats
[quick wizard error.txt](https://github.com/MilosKozak/AndroidAPS/files/2770582/quick.wizard.error.txt)
[wear wizard error.txt](https://github.com/MilosKozak/AndroidAPS/files/2770584/wear.wizard.error.txt)
