### ISSUE TITLE
BT connection between Dana RS and smartphone not constant

### ISSUE THREAD

**Issue by kadu-64** [MilosKozak/AndroidAPS#1595]
I have noticed, that the BT connection between my Dana RS and my smartphone Xiaomi Redmi 4x (Android version 7.1.2) has been interrupted again and again for a few days.
Previously, there were no disconnects between AAPS 2.0 and the Dana RS. BT Watchdog is enabled in Android APS. I have not made any changes in the settings lately.
After restarting the phone, the BT connection is restored.

**Comment by kadu-64** [comment]
ttps://drive.google.com/open?id=12Eko1aIX2-RKsZ5OivHVQizym4T8neYu

**Comment by kadu-64** [comment]
https://drive.google.com/open?id=12Eko1aIX2-RKsZ5OivHVQizym4T8neYu

**Comment by 2flea** [comment]
From Kat Rin
![image](https://user-images.githubusercontent.com/38214111/51021209-32dfc100-1581-11e9-904a-4834e364f3f7.png)

**Comment by kadu-64** [comment]
https://drive.google.com/open?id=1GlCUjaVI8tUmjMJaOy4TdXvgmQIZ2-6V

**Comment by kadu-64** [comment]
https://drive.google.com/open?id=1xnDJwXNBiyk81A2ClBuUruv47eY7oNDF

**Comment by kadu-64** [comment]
![image](https://user-images.githubusercontent.com/46000462/51036502-95e74d00-15ad-11e9-9317-5464bef23070.png)

**Comment by kadu-64** [comment]
![image](https://user-images.githubusercontent.com/46000462/51036550-bca58380-15ad-11e9-8ed9-b54af827aa0a.png)

**Comment by kadu-64** [comment]
![image](https://user-images.githubusercontent.com/46000462/51036578-d777f800-15ad-11e9-8c3f-c8d249b4f6db.png)

**Comment by kadu-64** [comment]
https://drive.google.com/open?id=1QV1KbjHbgD0Wc9M6ilQ7XJpIgzV6K0oE

**Comment by MilosKozak** [comment]
this is phone issue

**Comment by AlexD97** [comment]
Did you find any solution?
