### ISSUE TITLE
Feature request: Enable SMB in Open Loop mode

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#1598]
Allow SMB to run in Open Loop mode in the same circumstances it is supported when closed looping. This would bring the benefits of SMB to open loopers and would be particularly beneficial because many pumps have limitations to maximum temp basal multipliers that can be used which means that corrections take a lot longer to be completed.

In the same way that a Temp Basal request is currently suggested, pop up an SMB request with details of the amount of bolus requested.

In addition to the current safety constraints of using SMB, require that there are no outstanding temp basal suggestions which have not been enacted on for an SMB to be requested.

When SMB is running in open loop mode, the end user has further control to restrict it by using the existing "Maximum minutes of basal to limit SMB to setting".

**Comment by yeagerm** [comment]
I agree- this would be a great benefit for open-looping.

**Comment by MilosKozak** [comment]
if SMB is requested simply do a bolus a and record it. and it's not necessary to use exactly recommended amount

**Comment by dansuk** [comment]
SMBs are not requested in Open Loop mode unfortunately.

**Comment by liamawhite** [comment]
My only alternative here is to guess at an extended bolus in order to prevent post-prandial hyperglycaemia caused by protein on low carb.
