### ISSUE TITLE
Feature request: enabling autosens for open loopers

### ISSUE THREAD

**Issue by zwackelfuss** [MilosKozak/AndroidAPS#1604]
Autosens is only available after starting Objective 6 (see https://androidaps.readthedocs.io/en/latest/EN/Usage/Objectives.html).  (Thanks to @jotomo for helping!)

Therefore: AAPS should indicate this under Constraints in the OpenAPS tab. 

Or even better: is it possible to use autosens also for open loop users?

**Comment by MilosKozak** [comment]
autosens is good for open loopers too. just pass objective 6
