### ISSUE TITLE
COB displaying incorrectly following long period without CGM. 

### ISSUE THREAD

**Issue by tim2000s** [MilosKozak/AndroidAPS#1605]
Logs uploaded. Seeing COB from carbs 4+ hours after they were consumed. CGM was missing for 5 hours so carbs should have been decayed at minimum rate of 24g per hour. 

This doesn't appear to have happened. 
![screenshot_androidaps_20190118-120433](https://user-images.githubusercontent.com/14833174/51387823-67262500-1b1f-11e9-8755-af32edde6425.png)

**Comment by MilosKozak** [comment]
1) without CGM data there is no COB
2) here were carbs decayed at minimum rate (orange dots)
