### ISSUE TITLE
Minimed 640G suspend before low not logged correctly for Autotune results

### ISSUE THREAD

**Issue by JuthRo** [MilosKozak/AndroidAPS#1608]
Minimed 640G function of suspend before low get logged to the AndroidAPS but when using the Autotune feature its does not interpret the situation that insulin lever are at zero level. Result giving wrong basal rate suggestions.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem 10:43 29.01.2019
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner). 2.0 release candididate14
- Obtain the app's log files, which can be found on the phone in
[AndroidAPS._2019-01-26_18-44-33_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2806874/AndroidAPS._2019-01-26_18-44-33_.0.zip)
![screenshot_20190129-105901](https://user-images.githubusercontent.com/34601082/51896916-2a2b1f80-23b6-11e9-8114-88bc8dff841a.jpg)

  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
autotune is using NS data. 640g uploader must upload them in proper format
