### ISSUE TITLE
[Enhancement] 

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#1615]
Select TT box in bolus calculator as default if a TT is actually running.
![grafik](https://user-images.githubusercontent.com/13958493/52168118-153bec80-2726-11e9-94dd-e9af3769a7b9.png)

As the TT box is not in the vertical row with the other checkboxes it can easily be overseen and too much insulin could be issued. Would also by comfy if box would be check by default as long as a TT is active.

**Comment by jotomo** [comment]
And if the user is near the end of an _Eating Soon_ TT, bolusing for a meal, having the checkbox checked by default would deliver too much insulin.
So there is no default that is always right (which would make a checkbox superfluous), hence the decision was made to require the user to activate this _if_ it is needed in the given situation.

**Comment by wootmasterslick** [comment]
Regarding the checkboxes overall I think itnwould be a nice improvement to make it more intuitive. It is difficult to make it so the selections can be made with little thought but would make the system more pleasant to use in the long run. My girlfriend is now using AAPS and I see she often makes errors in the selection of the boxes. She is not always aware what is taken into account formtue calculations. Perhaps we should put some thought also into the presentation of these options.

**Comment by TebbeUbben** [comment]
We are aware of the issues regarding to our UI and keep improving, however, it will take time due to the refacturing that is needed.
