### ISSUE TITLE
Comma/dot issue when entering local basal profile in localized German version

### ISSUE THREAD

**Issue by UlricusR** [MilosKozak/AndroidAPS#1616]
Build version: c7ab2ae-2019.01.31-20:56

Problem description:
When trying to enter a value e.g. in the basal as local profile in a German localized version, the app requires a comma as decimal separator. However, on the keyboard the comma is inactivated.

The only possible workaround is to use the +/- symbol to enter the value, then a comma will appear and one can modify the value with the keyboard without deleting the comma.

See also screenshot.
![img_2414](https://user-images.githubusercontent.com/44271004/52168149-a4490480-2726-11e9-8e8a-76e04f4e2d2d.JPG)

**Comment by MilosKozak** [comment]
sorry this is android behavior, we cannot change it . but both "," and "." should be accepted. test it
