### ISSUE TITLE
In overview screen scale and units for Basal rate and IOB graph are not displayed

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#1618]
Currently in AAPS 2.0 there are 2 graphs with this problem, the graph to display basal rate automatically adjusts the scale to show the highest basal rate given in the time frame as max of the graph. This leads one time that the full BR on the graph is 0.6U while another with another time frame it is 3.0U. since there is also no scale displayed this to me is confusing. It is leading me often to think I am getting a high BR while it is actually very low. 
Possible solutions could be to display a dynamic scaling next to the graph or to fix the scaling for the entire day to the max calculated possible BR.

This problem is the same for the IOB graph.

**Comment by swissalpine** [comment]
I'm wondering why you couldn't see the dynamic scale (latest dev):
![image](https://user-images.githubusercontent.com/12517693/52438432-89f19b00-2b19-11e9-9f6e-32e4b8ec25ef.png)

**Comment by wootmasterslick** [comment]
Ok, will update and check again. This was observed on master branch

**Comment by swissalpine** [comment]
No, there is no scale for br. You see a dotted line for your programmed br, My actual programmed br is written in the second line: 0,76 U/h.

**Comment by swissalpine** [comment]
For me iob is interesting - and there is a scale.

**Comment by wootmasterslick** [comment]
Well, Id consider this more of an enhancement then.

**Comment by MilosKozak** [comment]
current libraries doesn't allow more
