### ISSUE TITLE
Unexpected Behaviour - Upload data only while charging

### ISSUE THREAD

**Issue by YPOC** [MilosKozak/AndroidAPS#1619]
In the Nightsout connections settings when I enable "use only wifi connection" and "only while charging" I expect AAPS to upload data when the phone is connected to any wifi and it is charging. But instead AAPS never uploads any data.
The Nightscout page then says "Status: Not allowed", even if I try different combinations of plugging in the charger and enabling this feature. The setting "use only wifi connection" seems to have no influence on this behaviour.

Right now AAPS absolutely drains my battery if it uploads every few minutes, therefore I'd like to upload data only while charging - or even better - only at a specific interval, e.g. every hour.

AAPS 2.0 on a ZTE Eaxon 7 with Android 7.1.1

**Comment by tanja3981** [comment]
Workaround: Restart the app helps! After the restart the status is detected correctly and the upload starts.

Note to developers: the event that mobile was plugged in seems to get lost somewhere.
