### ISSUE TITLE
AAPS lost IOB data

### ISSUE THREAD

**Issue by tKostka** [MilosKozak/AndroidAPS#1620]
AAPS lost IOB and custom targets, shows wrong Basal (100% instead of 0) and therefore gave too much insulin. Happend two times until now.

08.02.2019 00:09 (first screenshot)
I noticed several high SMBs in a short time (2.8u in 25min). At this time i had quite a lot COB but AAPS forgot the IOB, IOB in the screenshot is only from SMB. BG was going down because i had more IOB than AAPS was thinking. I did restart my phone and opened AAPS again - second screenshot at 00:11.
Now AAPS displays the right (higher) amount of IOB. Also Basal and custom targets are noticed correct again. I had to take some glucose and tried a higher custom target for the night.

08.02.2019 09:11 (third screenshot)
AAPS forgot the 1 unit insulin (manual correction via AAPS) and was giving me 200% Basal. After a phone restart everything was ok again IOB and 0% Basal (additional i did a disconnect pump in AAPS) - screenshot at 09:15.

AndroidAPS v2.0, Motorola G5 Plus, LOS 14.1, Combo, Dex G5 with xDrip (latest nightly).

**Comment by tKostka** [comment]
Will attach screensots and logs when on Desktop (can't find the buttons here on mobile).

**Comment by tKostka** [comment]
![screenshot_20190208-000916](https://user-images.githubusercontent.com/11375777/52484387-7ba58c80-2bb6-11e9-937c-973e5b94845c.png)
![screenshot_20190208-001113](https://user-images.githubusercontent.com/11375777/52484402-83fdc780-2bb6-11e9-9cb4-590a91c1175b.png)
![screenshot_20190208-091138](https://user-images.githubusercontent.com/11375777/52484421-8fe98980-2bb6-11e9-90b5-e2129c57041a.png)
![screenshot_20190208-091507](https://user-images.githubusercontent.com/11375777/52484431-98da5b00-2bb6-11e9-8eb2-300dc42c0ee8.png)

**Comment by tKostka** [comment]
[AndroidAPS._2019-02-08_09-12-53_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/2845722/AndroidAPS._2019-02-08_09-12-53_.1.zip)
[AndroidAPS._2019-02-08_09-12-53_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2845723/AndroidAPS._2019-02-08_09-12-53_.0.zip)
[Uploading AndroidAPS._2019-02-08_00-09-15_.0.zip…]()

**Comment by t1dast** [comment]
I had a similar problem just today. My AAPS forgot carbs and temp target. (IOB probably, too). It all returned once I force killed AAPS and started it again.

I'm running AAPS 2.0 on a Nokia 5, Android 9, Dexcom G6, fairly recent nightly xDrip+, Insight pump
Sent log by email.

**Comment by tKostka** [comment]
Happened again. Maybe because of too many ecarbs? I'm trying and using more ecarbs the last days.

![screenshot_20190212-230535](https://user-images.githubusercontent.com/11375777/52671486-872ce680-2f1b-11e9-9ecc-1694486aba3e.png)
![screenshot_20190212-230805](https://user-images.githubusercontent.com/11375777/52671502-901db800-2f1b-11e9-99ed-63e3a3d347a1.png)



[AndroidAPS._2019-02-12_23-05-51_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/2857880/AndroidAPS._2019-02-12_23-05-51_.0.zip)

**Comment by MilosKozak** [comment]
the problem is NS and sync to NS. if this is still happening try to disable NS sync

**Comment by tKostka** [comment]
Thanks. Did not happen again since changing AAPS settings to only upload to NS. For me it is OK now, but i guess this is only a workaround? What if treatments from NS are needed?
