### ISSUE TITLE
[Enhancement] Automatically run loop when TT is changed

### ISSUE THREAD

**Issue by harispoljo** [MilosKozak/AndroidAPS#1626]
When I set a new TT the loop will run when next bg comes, therefore worstcase you have to wait 5min for a new tbr. I currently do it manually by going to the loop tab and pressing "run loop" but I figured it can be a automatized. 

I thought about adding this bit of code in the method that changes the TT but couldn't find a good way to implement it. 
```
new Thread(() -> LoopPlugin.getPlugin().invoke("TT changed", true)).start();
        FabricPrivacy.getInstance().logCustom(new CustomEvent("TT_Loop_Run"));
```

**Comment by wootmasterslick** [comment]
This isnt in yet? Deninitely an improvement and easy win.

**Comment by harispoljo** [comment]
I changed it to tt_loop_run
