### ISSUE TITLE
Implementation of Superbolus using absolute values for Medtronic driver

### ISSUE THREAD

**Issue by peterlynton** [MilosKozak/AndroidAPS#1631]
Log attached, it appears that Superbolus needs to be able to check pump settings and decide on absolute or % TBR of 0 for 120 mins dependent on pump.  Medtronic driver requires absolute values, whereas Superbolus sends a 0% TBR which the Medtronic driver cannot implement.

Wizard used to calculate Superbolus at 22:54:07.379, and failing in setting 0% TBR for 120min at 22:54:10.042.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2867239/AndroidAPS.log)

**Comment by MilosKozak** [comment]
medtronic driver is not in main repo yet. report it to developer

**Comment by peterlynton** [comment]
This was reported and closed in https://github.com/andyrozman/RileyLinkAAPS/issues/107 and discussed in RileyLinkAAPS/Lobby.

The issue was explained by @andyrozman: 
Each driver has 3 options how to use TBR: Absolute, Percent or Both. While MDT pumps support both types (not at the same time), if using %, you can do max of 200%, but if you do absolute you could do a lot more (up to 35 U/h), which means you can easily do 500%...
When we set which type is used, all implementations through AAPS always check this settings and then execute TBR in correct format, but it seems that when Superbolus is used, that code doesn't check TBR type and just execures TBR in %... They just need to fix this and Superbolus will work again.

**Comment by andyrozman** [comment]
This is not problem with my code... 
Before Superbolus is sent to pump, you would need to check (in PumpDescription) if your TBR is set as Absolute or Percent and then call correct method. 

This is not just a problem with Medtronic. This wouldn't work for any pump that has TBR Type set to just Absolute (and doesn't implement both methods for TBR)

**Comment by MilosKozak** [comment]
where is possible get info about mode?

**Comment by andyrozman** [comment]
PumpDescription.tempBasalStyle I would imagine.
