### ISSUE TITLE
Target min blood sugar not flexible

### ISSUE THREAD

**Issue by GlennCoco** [MilosKozak/AndroidAPS#1632]
When using NS profile there is a limitation on min blood sugar that can be entered. 5.0mmol is the lowest target which can be set, once you go below this errors occur and a message regarding the minimum being 5.0mmol.

I understand for some people this is a safe blood sugar, however when blood sugars are really stable utilising a low carb approach or fasting it would be great to be able to set it at around 4.5mmol as during a fasted state this is somewhat normal for a non diabetic.

Flexibility is important as everyone manages diabetes and responds to treatment differently.

**Comment by kallnap** [comment]
@GlennCoco, unfortunately I assume it is safer for most people. If really needed you could always change the settings in the source code yourself.  In addition 5.0 seems okay. If the HbA1c seems to reflect much higher values, then i would think that the highs during the day are a bigger issue than sitting around 5.0 at night times.

**Comment by MilosKozak** [comment]
sorry. it's too dangerous to have this in public code. You can patch your version

**Comment by fra-orolo** [comment]
If you have a look at the code, you will notice that actually the 'green band' with minBg=90mg/dl is used to create 'reaction boundaries' below minBg (threshold). 
For minBg=85 you will get a hard threshold of ~65, which the predictions are checked for. Therefore using lower boundaries can bring you in really dangerous areas for T1D or you would need a different control algorithm.
