### ISSUE TITLE
Invalid feedback SMS on SMS bolus 

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#1633]
After sending bolus over SMS, feedback SMS has 0 applied bolus with 0 time (screenshot included)
Bolus in pump history are applied, Bolus in NS written correct.
Using new insight driver, insight pump (insight branch).

![52602551_1108045569367628_4484262400408682496_n](https://user-images.githubusercontent.com/16052233/52903291-6d411b80-321b-11e9-80a1-1778c204711c.jpg)
![51794283_325150718123722_5457726938594410496_n](https://user-images.githubusercontent.com/16052233/52903292-6d411b80-321b-11e9-8ac2-f8143e2d8bfb.jpg)

**Comment by ondrejdiabetes** [comment]
![screenshot_20190217_160819](https://user-images.githubusercontent.com/25035153/52917297-18200b00-32ea-11e9-925a-f388c1f028e1.jpg)
the time was shown today

**Comment by MilosKozak** [comment]
Yeah it's genereal problem .... changed subject

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/1521
