### ISSUE TITLE
Big Letters

### ISSUE THREAD

**Issue by dclaassen1** [MilosKozak/AndroidAPS#1638]
Hello, is it possible to display larger numbers in the notification on the lock screen? When I look at the lock screen at night, the values are so small that I always have to search for glasses to decipher my blood glucose value.

Thank you

dclaassen

**Comment by quizzmaster** [comment]
Unfortunately, that is not possible, because AndroidAPS uses the native Android notifications.

**Comment by RalfCGM** [comment]
On most Android phones there are options to generally change the font size under accessability. I don't know whether this affects notification size, but maybe you can give it a go?

**Comment by ShaggydogUK** [comment]
Nightscout has a clock view which is much larger.

**Comment by jotomo** [comment]
xDrip has what you're looking for: go into the preferences and navigate to _Number wall on lock screen_ (use search or via _xDrip+ display settings_). Here you can configure the glucose value to be displayed on the wallpaper of the lock screen.

**Comment by dclaassen1** [comment]
Thanks a lot.  Dclaassen
