### ISSUE TITLE
Feature request: profil switch

### ISSUE THREAD

**Issue by papalendro** [MilosKozak/AndroidAPS#1640]
Hello, 

it would be a nice feature fore the next AAPS version, if we could decide in the keypad "profilswitch" to switch only BSR or ISF or IC or all together. We could find faster the right setup of our factors.

Example ISF

I use a tested circadian BSR an i want to test a circadian isf.
1.  i took the circadian ISF from Circadian Spreadsheet and write it to my profile
2. at the first tests i see my bloodglucose is like an rollercoster and have very much low temp bsr and hight temp bsr, my isf is to low.
3. i set only the isf 10 % softer, then i look at regulation. 
4. i  would go up and down with the ISF, till i have no more rollercoster and the low and hight temp bsr are around the 50 and 150 % percent.

Example IC

i would do the "same" like in example ISF

At least i would write my tested ISF/IC to my nightscout profil. 

i think we could easier give an instruction in the wiki with example pictures like good regulation / bad regulation.

Thanks

https://scontent.xx.fbcdn.net/v/t1.15752-0/p280x280/52537845_2177901542523825_5665973401513099264_n.jpg?_nc_cat=103&_nc_ad=z-m&_nc_cid=0&_nc_zor=9&_nc_ht=scontent.xx&oh=4f0cd082bcc23b6db6b707e468f850f4&oe=5CE8B7E9

**Comment by TebbeUbben** [comment]
This feature is not meant to be used for adjusting factors and adding these checkboxes would only make the UI more complicated.

**Comment by MilosKozak** [comment]
I agree with Tebbe. Clone profile in NS and adjust values there

**Comment by osodebailar** [comment]
I can’t agree that the GUI would be more complicated. Look at the Bolus wizard . This is comlictated .
But 3 additional checkboxes would not be .

It is a feature that can help in many situation. 
It is usable to do this with  a nightscout profile , but you must do it manual .
In aaps we can do this automatically .
