### ISSUE TITLE
Feature request: option to reset autosens after sitechange instead of mandatory reset 

### ISSUE THREAD

**Issue by RalfCGM** [MilosKozak/AndroidAPS#1644]
Resetting autosens after sitechange: for me there's logic with resetting the resistivity to 100% after site change, but don't really understand why excess sensitivity also resets to 100%.  Have discussed on FB with Tim Street and suggestion is to have an option for resetting sensitivity and resetting resistivity after sitechange, instead of mandatory reset of both.

**Comment by winemug** [comment]
I don't agree with "it's OK for resistivity but not for sensitivity." If it's not OK (and it probably is) it should be not OK for both.

Assuming the site change effects sensitivity in a way that it creates insulin resistance, the sensitivity value should be increased (towards more sensible) after a site change, regardless of whether it was in the resistant range or sensitive range. After all if you were sensible before site change, you should be even more sensible afterwards.

Same logic applies to resistance.

**Comment by TebbeUbben** [comment]
If insulin is delivered into a capillary, it could have a bit more and faster impact in your blood sugar.

**Comment by Mackwe** [comment]
For me, I have removed the reset for site change, as we have other issues and cannot wait another 8 hours for autosens to catch up. On profile switch it is definitely a feature, since we want to control the insulin flow there.

**Comment by MilosKozak** [comment]
changing site definitely change insulin absorption speed and will affect autosens. reset is on the right place here. and another thing is that this behavior is equal to OpenAPS
