### ISSUE TITLE
Improvement suggestion, do not auto select BR entry when opening localprofile

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#1647]
Situation:
Currently when I select the localprofile tap in AAPS the tab will be opened and automatically the cursor is moved to the first basal rate value, this then prompts the keyboard to open.

Problem statement:
The opening of the keyboard takes up half of the screen and disallows you to instantly view the local profile and/or scroll to select the value you wish to edit. In order to view the profile one needs to select anything outside of the data entry boxes or click the keyboard to display the full profile.
With this additional action you risk changing a value.

Suggested solution:
Adapt the code so that no selection is automatically made when the local profile tab is opened.

**Comment by MilosKozak** [comment]
sorry i cannot repeat thi behavior
