### ISSUE TITLE
[AAPS 2.1.1] wrong BG values --> from 10minutes ago

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1660]
I'm using AAPS 2.1.1 and for the first /two hours everything worked well.
After this time I was surprised that the shown value on the watch was different to AAPS and the BG source.

The time difference is about 10 minutes. 
If I'm looking at hte BG values in APPS the shown BG value belongs to an earlier entry.

Some miutes later also AAPS is using the wrong BG entry. 

AAPS is using the value which was stored 10 minutes before. The watch even some miutes earlier of that.

**Comment by Oekonom2** [comment]
Having the same issue, mostly with the watch. Resending all data to watch fixes that for a short time but it will occur again afterwards

**Comment by BastianBickelhaupt** [comment]
Same on my side, following

**Comment by typ1-brods** [comment]
Same issue here. SWR50 and AAPS 2.1.1. With 2.0 it was fine

**Comment by zehnBE** [comment]
i think it comes from this change:
https://github.com/MilosKozak/AndroidAPS/commit/94d96cb#diff-6d1ecbc4c204479b9917a677ef4838f1L73

i dont know, if there a function, ala "is data null, but bg-value is not too old, try it again" or in IobCobCalculatorPlugin.getPlugin().getBgReadings(); it is not correctly updated?

**Comment by TEbinger** [comment]
Same here ... Didn't notice that until I saw it here / on facebook.

**Comment by MilosKozak** [comment]
@AdrianLxM can you test it?

**Comment by ChrisFletch** [comment]
Looks like I'm affected too on 2.1.2

**Comment by fra-orolo** [comment]
This seems to happen for me too. We are using BG-Values collected with one phone to NightScout, APS and PumpControl running on another phone using values from NightScout. As far as I can tell from UI observation: the value  on the Main Tab is outdated sometimes, but the table with the NightScout BG values is always showing current values.

**Comment by fra-orolo** [comment]
I found some race condition:
---
13:26:44.709 [pool-2-thread-1] D/AUTOSENS: [IobCobCalculatorPlugin.runCalculation():596]: Starting calculation thread: onEventNewBG to 11.03.19 13:26
13:26:44.752 [Thread-4402] D/AUTOSENS: [IobCobOref1Thread.run():84]: AUTOSENSDATA thread started: onEventNewBG
13:26:44.757 [main] D/info.nightscout.androidaps.data.GlucoseStatus: [GlucoseStatus.getGlucoseStatusData():81]: GlucoseStatus: data too old Mon Mar 11 13:16:47 GMT+01:00 2019
13:26:44.862 [Thread-4402] D/AUTOSENS: [IobCobCalculatorPlugin.loadBgData():129]: BG data loaded. Size: 431 Start date: 10.03.19 08:26 End date: 11.03.19 13:26 success 11.03.19 13:21
13:26:44.981 [Thread-4402] D/AUTOSENS: [IobCobOref1Thread.run():148]: Processing calculation thread: onEventNewBG (0/347)
---
The BGdata in IobCobCalculatorPlugin. is used all over the place, but it is fetched in the calculationThread. Apparently reading from DB takes longer and the GlucoseStatus is asked for, before the fetching from DB finishes.
With the old code the GlucoseStatus took data from DB diectly, without the race.

**Comment by fra-orolo** [comment]
There is also a problem, if times on different machines drift for some seconds.
The bgValues are loaded with the current time of the phone as end-date.
If the bg sender phone lives drifted 10 seconds in the future, we will always miss the last entry for 5 mins.

**Comment by Oekonom2** [comment]
The issue also presents on the notification area of the phone.
In AAPS the readings are correct, on the notification area it takes much longer to get updated.
