### ISSUE TITLE
2.1.1 Feature request - when using xDrip+ it would be nice to be able to select 7 or 10 day wear to avoid the red alert on both care portal and overview screens after 7 days when using G6.

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#1666]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by quizzmaster** [comment]
Please don't use the title for a long description but use the body of the issue.

The warning levels used for the cannula age, insulin age, sensor age and battery percentage are set for your nightscout instance. You can freely change them there and AndroidAPS will show the warning levels accordingly.

**Comment by ShaggydogUK** [comment]
Apologies.  Ok, I'll find that in Nightscout.
