### ISSUE TITLE
AAPS 2.1.2 Wrong profile updated on Insight Pump

### ISSUE THREAD

**Issue by bertroode** [MilosKozak/AndroidAPS#1668]
Five basal profiles can be set on the Accu Chek Insight pump. Assume that profile 3 is active and that a local profile is used on AAPS.
As soon as a change is made to this local profile, this is uploaded to the pump. However, not to the active profile of the pump, but to profile 1.
This could have nasty consequences for the calculation of a temp basal.
Either the active profile should be updated or the user should be notified to only use profile 1 for AAPS as the active profile.

**Comment by quizzmaster** [comment]
This fact is clearly mentioned in the [wiki](https://androidaps.readthedocs.io/en/latest/EN/Configuration/Accu-Chek-Insight-Pump.html#hardware-and-software-requirements).
This is the case for all supported pumps.

**Comment by bertroode** [comment]
Sorry, could not find the latest information, may be the link in https://github.com/MilosKozak/AndroidAPS/wiki is not up-to-date.
