### ISSUE TITLE
[AAPS v 2.11] G6 sensor change is auto updated in NS as a future event. 

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1677]
When enabled the AAPS functionality (in Dexcom G6 plug in) to automatically log sensor changes, the sensor change time is way in the future. Did one today (2016-03-07 ~16:30). It displays correctly in AAPS but the log in NS says 2106-02-07 07:28. Yes, 2106, almost 90 years into the future.. App is latest G6 modified, AAPS 2.11, NS 0.11.1, Samsung A3 (2017). Same thing happened 10 days ago at sensor restart.

**Comment by MilosKozak** [comment]
@TebbeUbben it seems to be G6 app bug

**Comment by Mackwe** [comment]
Can the solution be: "If datestamp+5mins > time(now), then datestamp = time(now)"? Or just always add it at time(now)?
