### ISSUE TITLE
unhandled exceptions when performing TEMPBASAL 0.0 U/h 30 min

### ISSUE THREAD

**Issue by bertroode** [MilosKozak/AndroidAPS#1678]
With my type of diabetes the basal flow is very often set to 0.0 U/h for 30 minutes, very often for more then 1 hour. In that situation there are a lot of unhandled exception errors issued by the DatabaseHelper program. I entered a couple of statements to get more information about the records.
Because of the line: Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: TemporaryBasals.date (code 1555), it seems that there are more records in the database with the same date.

[Error.txt](https://github.com/MilosKozak/AndroidAPS/files/2945944/Error.txt)

Using AAPS 2.1.2 with Insight plugin

**Comment by bertroode** [comment]
Further analysis learned that the problem also sometimes occurs when there is one record with that specific date in the database. I wonder of timing problems may have a role here. For me that will be hard to examine. The error messag is always the same.

**Comment by bertroode** [comment]
Finally I may have found the cause of the problem. The DatabaseHelper program checks wether a record with a pumpId existst in the database. If so it leaves the routine and otherwise a record will be created. However in that case there should not be a record with the same date/time present in the database. Apparently there is one present and that is the reason for an error message.
Subsequently the NightScout processing seems to correct the omission by deleteing the record and submitting a new one woth the correct information.
So in fact the rather frequent errors in the log seem to be quite harmless, However it would be better to get a fix for the problem because it can distract the attention to other, more serious, things.

**Comment by TebbeUbben** [comment]
As you said: These exceptions are harmless and will be fixed when re-structure our database.
