### ISSUE TITLE
Combo losing connection every 1-2 weeks

### ISSUE THREAD

**Issue by emielmiddel** [MilosKozak/AndroidAPS#1679]
On average every 1-2 weeks, AAPS loses connection to my combo. It does not reconnect until I restart my phone, and switch off and on bluetooth on my Combo.

Build: both in 2.0 and 2.1.

Now running:
AndroidAPS 2.1.2
Build: NoGitSystemAvailable-2019.03.08-18:03

Time and date: On 9 march 2019 08:45 it says that it was not connected fof 100mins. See log files

[AndroidAPS_LOG_1552117325260.log.zip](https://github.com/MilosKozak/AndroidAPS/files/2948242/AndroidAPS_LOG_1552117325260.log.zip)

**Comment by gregorybel** [comment]
which Phone and OS?

**Comment by emielmiddel** [comment]
LG Nexus 5x, Android 8.1

Verstuurd vanaf mijn iPhone

**Comment by gregorybel** [comment]
ok, does Ruffy ignore battery optimization?

**Comment by MasterPlexus** [comment]
And in addition , go to recent Apps list, scroll to Ruffy, and put the icon of the Lock on Top right to closed.

**Comment by emielmiddel** [comment]
Ruffy battery optimalisatie was on, now switched it off.

This last one I don't understand, I do not see any locks in my recent apps list?

Verstuurd vanaf mijn iPhone

**Comment by MasterPlexus** [comment]
So just check if the optimization setting helps. If not come back, and we can examine the last point. (The menu looks like not identical on all phones unfortunately)

**Comment by emielmiddel** [comment]
Thank you very much for your help. I will give it a try, and let you know if it works :)

Verstuurd vanaf mijn iPhone

**Comment by emielmiddel** [comment]
Unfortunately I just received a new 'pump unreachable...

Any suggestions?

Verstuurd vanaf mijn iPhone

**Comment by swissalpine** [comment]
Sorry to say, but some phones have problems to establish a stable connection over weeks. It has nothing to do with the software but with the bluetooth stack of the phone.
I know what I say: My loved Sony Z3c lost the connection every 5-6 days, my xiaomi Redmi 4x never ... (same AndroidAPS build).

**Comment by MilosKozak** [comment]
try another phone
