### ISSUE TITLE
GlucoseStatus calculates incorrect deltas for 1 minute spaced data

### ISSUE THREAD

**Issue by rob-andy** [MilosKozak/AndroidAPS#1698]
When using glimp with a miaomiao sensor to feed data into nightscout, the deltas displayed on the overview (average,short&long) are not correct.

This can be traced to the getGlucoseStatusData method of the GlucoseStatus class.

By modifying the unit test to use data such as 
```java
    List<BgReading> generateLibreTestData() {
        List<BgReading> list = new ArrayList<>();
        try {
            double start_time = 1514766900000d;

            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":100,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));

            start_time -= 1000d * 60; // 1 minute ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":100,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 2 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":100,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 3 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":110,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 4 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":110,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 5 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":110,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 6 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":110,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));
            start_time -= 1000d * 60; // 7 minutes ago
            list.add(new BgReading(new NSSgv(new JSONObject("{\"mgdl\":110,\"mills\":" + start_time + ",\"direction\":\"Flat\"}"))));

        } catch (JSONException e) {
            e.printStackTrace();
        }
        return list;
    }
```

You can see all the deltas are calculated to 0.

I believe the root cause of this issue is from averaging the now_date value for each reading within the 2.5 minute boundary.  The now_date should not be changed.  It should remain the time of the latest reading.  By continually updating the now_date value, the algorithm never moves on to the > 2.5 minute checks because each successive 1 minute reading is within 2 minutes of the new averaged now_date value.

Thanks

**Comment by MilosKozak** [comment]
@AdrianLxM @TebbeUbben this is openaps design. should we support 1min interval?

**Comment by rob-andy** [comment]
I would argue that this isn't a design change, because the delta's would remain in the units of mg/dl/5 minutes as per the openaps design.  The deltas would just be an average of the available data samples (instead of assuming that since each sample is spaced 5 minutes apart, it is already in the mg/dl/5 minutes unit).  Once I have updated the UnitTests, I will submit a pull request.

I view this as fixing a bug in the current implementation of getGlucoseStatusData.
