### ISSUE TITLE
AAPS isn't starting ruffy

### ISSUE THREAD

**Issue by jgslade** [MilosKozak/AndroidAPS#1699]
-Time: 21:35:54.954 
-Problem: My phone won't connect with my pump through AAPS, though it does if I manually connect with Ruffy
- Build: b4220592e-2019.03.28-19:06
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3025162/AndroidAPS.log)

My Primary phone right now is an lg g5 running LineageOS 14.1 since support for lineage 14.1 has stopped I am wanting to move to a different phone. I have a LeEco LePro 3 running lineageos 16. Ruffy is working perfectly on it, pairing with the pump is much quicker than on the LG with the LeEco. Ruffy will also connect to the pump if I tap the connect button on it, however AAPS seems to be unable to start the ruffy service on the LeEco phone.

**Comment by jotomo** [comment]
Please disable battery optimization for AndroidAPS and try again.

**Comment by jgslade** [comment]
I disabled the battery optimization for AndroidAPS and Ruffy,  AAPS is still not starting Ruffy.
[AndroidAPS2.log](https://github.com/MilosKozak/AndroidAPS/files/3025485/AndroidAPS2.log)

**Comment by jotomo** [comment]
Hm, not sure what's going on at this point, sorry. If you used the _pairing_ branch of ruffy, did you switch back to _master_ or _combo_ branch and installed the APK again (overriding the existing installation)?
I'm running with LineageOS 16 (Pocophone F1) as well, but I am not seeing the issue there. Are you running a recent version of LOS? Given that it's relatively new, there might be some unfixed issues with the LeEco phone ROM maybe.

**Comment by jotomo** [comment]
What is strange about the error message (which states the app is not allowed to call ruffy in the background) is that Android doesn't show the info about the calling app correctly (the _uid null_ bit in the message). Maybe try wiping the (dalvik) cache to see if the flash wasn't totally clean.

**Comment by jgslade** [comment]
Sorry for the delay I went out of town for a while. 

Thank you, I cleared the dalvik cache and that seemed to do the trick.
