### ISSUE TITLE
Insight bugs

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#1702]
- [ ] show queue like we do on dana fragments
- [ ] when i request nonsence parameters to insight driver like TBR with duration zero etc it returns success
- [x] driver is not filling result.bolusDelivered with real delivered value

**Comment by TebbeUbben** [comment]
> * driver is not filling result.bolusDelivered with real delivered value

Fixed by #1704.

> * when i request nonsence parameters to insight driver like TBR with duration zero etc it returns success

It will actually still send a TBR command with zero duration to the pump which will interpret this as a cancel request.

> * show queue like we do on dana fragments

No a bug, but okay, I can do that.
