### ISSUE TITLE
Add ability to skip objectvies

### ISSUE THREAD

**Issue by cascer1** [MilosKozak/AndroidAPS#1708]
I am a long-time OpenAPS user switching to AndroidAPS. While I believe the objectives offer a valuable new-user experience (I enforced similar limits on myself when I first started using OpenAPS), I also believe that always enforcing these limits is quite unfriendly towards experienced users.

Is there some way to skip or disable the objectives? I tried looking around in the code but I'm not experienced enough with Android development to create a stable output (even removing the `Objectives.add` statements in `ObjectivesPlugin#setupObjectives` seems to make the app unstable).

Thanks

**Comment by MilosKozak** [comment]
you may pm some developer for hint. you need a proof you were looping before (for example NS history data)
