### ISSUE TITLE
AndroidAPS show always mmol not mg/dl

### ISSUE THREAD

**Issue by aendes** [MilosKozak/AndroidAPS#1709]
Hello,

i have an issue with installing AndroidAPS. I upload my data to Nightscout from 640GUploader. In Nightscout all Values are in mg/dl.
But in AndroidAPS all the Values are shown in mmol. I have not found any possibility to change the mode from mmol to mg/dl.
If i watch the Download-Logs there it already show the values in mmol.

Is there a possibility to switch back or force mg/dl?

Thanks in advance

Andreas

PS: I had this issue also with an older version, but there i changed from nightscout profile to local profile which solved this...

**Comment by aendes** [comment]
After playing around with deleting all the profiles on nightscout and uploading these to nighscout again from the pump, i have no the correct values in the log files.
But the values itself are still shown in mmol...

**Comment by aendes** [comment]
Some additional Details:
Android 8.1
AndroidAPS: 2.2
Nightscout: 0.11.1
CGM Medtronic 640g Uploader: 600SeriesAndroidUploader (Uploader to nightscout, no local transfer, different phone)

**Comment by MilosKozak** [comment]
units are taken from active profile

**Comment by aendes** [comment]
In Nightscout the active Profile shows:  Units: mg/dl 
In Nightscout Log on Phone it also shows the value in mg/dl.

Where else can i adjust the units?

**Comment by aendes** [comment]
After playing with the profile
And setting DIA to different values the problem is gone.
I tried to recreate the problem, but without success
