### ISSUE TITLE
Allow configuring of allowed SMS commands

### ISSUE THREAD

**Issue by cascer1** [MilosKozak/AndroidAPS#1711]
Instead of allowing either all or no SMS commands, I believe it would be valuable to have the ability to select which commands are enabled.

For example, I would like my parents (who have access to the SMS commands) to be able to check on status and BG but I would not like them to issue bolus commands.

**Comment by MilosKozak** [comment]
it's already there :
Allow remote commands via SMS
without this ON only reading status from allowed numbers is possible
