### ISSUE TITLE
BolusWizard dialog - popup keyboard missing decimal point

### ISSUE THREAD

**Issue by rob-andy** [MilosKozak/AndroidAPS#1712]
Using the latest release version 2.2 (same problem existed in prior versions) when you open the bolus wizard/ calculator dialog and tap in the manual correction box, the popup keyboard does not have a decimal point.  To enter a value with a decimal you need to use the up/down scroll buttons.

Pump is an accu-check combo.

**Comment by MilosKozak** [comment]
try it with different languages setting

**Comment by rob-andy** [comment]
If i change the language within AndroidAPS itself, it makes no difference.  I should add, for the BG entry (which is set to be in mmol) the decimal point appears correctly.  The step size from the pump is obviously okay because the increment/decrement buttons are in the step size of 0.1

I was thinking the problem could be in the actual input control for the enabling/disabling of the decimal point.  The only difference I can see between the BG control and the Correction control is the BG control also gets .setStep explicitly called on it, whereas the Correction control just relies on the initial setParams call.

All the controls on the Local Profile tab also work as expected when in mmol mode.

**Comment by rob-andy** [comment]
After a software update on my phone, the keyboard is now different for all the entry controls.  I'm putting this down to being a device issue not a software issue. Thanks
