### ISSUE TITLE
Full App Crash On Insight Pair 

### ISSUE THREAD

**Issue by notlistening** [MilosKozak/AndroidAPS#1716]
Release 2.2 - On Android OnePlus 5T running Lineage 15.1

Expected Behaviour:
Clicking on Insight Pairing brings up device selection screen.

Actual Behaviour:
Full App Crash with auto restart. 

Steps to reproduce:
Download and install 2.2
Run through initial setup wizard selecting the insight and trying to pair.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3050821/AndroidAPS.log)

**Comment by notlistening** [comment]
Further testing just upgraded to Lineage 16. Same behaviour full app crash.

**Comment by TebbeUbben** [comment]
You are using 2.1.2, not 2.2.2. Please update.

**Comment by notlistening** [comment]
Nope it's 2.2.2 now updated 2 hours after release. Same crash can provide logs if required. I have not compiled this directly in Android Studio I have just installed the apk directly from GIT.

**Comment by notlistening** [comment]
Same issue on a stock Sony Xperia Z5 Compact

**Comment by notlistening** [comment]
Planning to compile it from GIT tonight and get it installed. Will let you know.

**Comment by notlistening** [comment]
Okay now picking up information from Facebook I can see I had to do a full build under Android Studio to get a fully featured version of AndroiAPS. All working apart from Bluetooth sometimes not wanting to play nicely.
