### ISSUE TITLE
SMS nach Profilwechsel

### ISSUE THREAD

**Issue by kgotts** [MilosKozak/AndroidAPS#1736]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3071520/AndroidAPS.log)
[AndroidAPS._2019-04-11_00-00-13_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3071521/AndroidAPS._2019-04-11_00-00-13_.2.zip)

Ein Profilwechsel löst unzählige SMS aus.
Letzter Profilwechsel am 11.04.2019 15:21 über NSClient.
Wechsel des aktiven Profils von 90 auf 85%.
AAPS und NS Client Version 2.2.2

![Screenshot_20190412-052802](https://user-images.githubusercontent.com/49544889/56012368-84b4f600-5cec-11e9-9665-42e17e910b3e.jpg)

**Comment by MilosKozak** [comment]
this is issue of NS. restart NS. if it not helps you'll have to clean treatment collection

**Comment by osodebailar** [comment]
If it is a issue of the night scout server , isn't it ? .
Milos  you have a link to the issue ?
What can we do until we have a solution ? 
The only way i see, to avoid expensive costs , is to deactivate sending sms in code fragment.
