### ISSUE TITLE
Problem with delta not showing

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#1739]
Problem noticed at 13.18 on 12th April 2019 

Looked at watch using steampunk face and noticed that delta was flat, although I felt it was rising.  Looked at APS on phone and noticed that it too was showing 0 delta, for immediate, 15 minute and 40 minute, which is not right.  I looked at xDrip (getting info from APS, using patched Dexcom G6 app) and it is showing +0.1 for immediate delta.  I have attached screenshots and log.  Version info: 2.2.2  Fullrelease Nightscout version 1.1.1
Build c2cf6d100-2019-04-07-19.54

Problem is not constant, but delta not accurate - now showing immediate and 15 min as -0.1 but 40 as 0, which is wrong, the 40 minute delta should be around +2.  Back at 13.38 and everything showing 0 again. 

Although I haven't noticed the problem specifically in the past, I know I have recently been looking at my watch and thinking that I've been level for much more time than usual.

I'm using Insight pump
Dexcom G6
Patched Dexcom app
Feeding xDrip Nightscout

I am feeding Nightscout and xDrip from APS, but noticed I was also feeding Nightscout from xDrip, which I have now stopped.  I will let you know if that has made a difference.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3073244/AndroidAPS.log)

![Screenshot_2019-04-12-13-18-32](https://user-images.githubusercontent.com/30231246/56037430-2d804700-5d27-11e9-9a85-186f9f272577.png)
![Screenshot_2019-04-12-13-18-10](https://user-images.githubusercontent.com/30231246/56037431-2e18dd80-5d27-11e9-919e-fb86b67c3800.png)

**Comment by ShaggydogUK** [comment]
Looking at the patched Dexcom setting in APS I see that I can also set "upload to Nightscout" there, which was turned off, now turned on.

**Comment by ShaggydogUK** [comment]
So, with APS and patched Dexcom app set to upload to nightscout, and xdrip not things still appear odd.  At 15.01, with  BG probably dropped by 1.0 or so in the last 40 minutes all three are showing -0.1.  Logs attac
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3073609/AndroidAPS.log)

hed again.

**Comment by ShaggydogUK** [comment]
Just noticed that the readings around when this is happening are noisy - does that affect the delta that is shown?

**Comment by ShaggydogUK** [comment]
Swapped the patched Dexcom app for xDrip today, still the same problem.  Sometimes an immediate delta of 0.1, with a 15 minute delta of 0.1 is shown, but the 40 minute delta always shows as 0.  Using the calculator to work out a dosage shows that the deltas in the calculator are also showing as 0 which means that incorrect doses are being calculated and SMBs are working on a 0 delta, even if BG is rising or dropping sharply.

**Comment by ShaggydogUK** [comment]
I just switched on my phone to see a delta of 0.1 for immediate and 15 minutes suddenly turn to 0, even though the BG reading was 2 minutes old, nothing else on the screen changed, but the two delta value changed from 0.1 to 0 as I watched.

**Comment by ShaggydogUK** [comment]
Here is a gif of the screen showing that the delta changes as the time from last CGM reading goes from 1 minute to 2 minutes.
![delta](https://user-images.githubusercontent.com/30231246/56090570-ba4c1180-5e9b-11e9-9750-012f95538764.gif)

**Comment by ShaggydogUK** [comment]
Reinstalled 2.1.2 to see if it was the version causing the problem.  The numbers are showing now, but are showing wrong - although BG has been dropping rapidly for 30 minutes, 15 minute delta show less than immediate delta. Image attached. 
![Screenshot_2019-04-14-11-44-37](https://user-images.githubusercontent.com/30231246/56091792-313cd680-5eab-11e9-923d-3c1c0e1f7fd4.png)

**Comment by ShaggydogUK** [comment]
Turns out that 0 delta is being used in all calculations as well, making SMB dodgy, especially if BG is rapidly dropping.  Will keep using 2.1.2 for the moment, I know the problem!

**Comment by MilosKozak** [comment]
can you verify what deltas are passed to OAPS?

**Comment by ShaggydogUK** [comment]
Main screen, on BG change, showing immediate -0.1, 15 min -0.1, 40 min 0.1 and OpenAPS is showing delta: -2, short_avgdelta: -1.44 long_avgdelta: 2.36.  If, when the delta on the main screen has gone all to 0 and I press "run now" on the OpenAPS SMB screen, all the deltas there are showing 0 as well, so running a quick conversion it seems like the values are similar.

**Comment by MilosKozak** [comment]
I'm unable reproduce this issue
i added more logging to dev branch. Please update, test and provide screenshot + log file
You need to enable "GLUCOSE" logging in maintenance plugin.

**Comment by ShaggydogUK** [comment]
Ok, two sets of images, one just after BG changed with values for delta on both front screen and OpenAPS (wrong values), and a second set taken shortly after when the front screen changed to 0 and the OpenAPS had a run now performed.  Also logfile attached.
![!-Screenshot_2019-04-15-16-39-51](https://user-images.githubusercontent.com/30231246/56146391-097a6b00-5f9e-11e9-8a22-5174ea0c6915.png)
![2-Screenshot_2019-04-15-16-40-00](https://user-images.githubusercontent.com/30231246/56146404-0da68880-5f9e-11e9-8fda-f7bb76cb221e.png)
![3-Screenshot_2019-04-15-16-40-09](https://user-images.githubusercontent.com/30231246/56146408-10a17900-5f9e-11e9-838a-5a368847e351.png)
![4-Screenshot_2019-04-15-16-40-21](https://user-images.githubusercontent.com/30231246/56146415-139c6980-5f9e-11e9-9dce-da94cb1cc16a.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3080970/AndroidAPS.log)

**Comment by ShaggydogUK** [comment]
I am now doubting my own eyes and memory.  Just checked v 2.1.2 which I was running, and the deltas on that are incorrect too.  This means that the problem is not just 2.2.2 but all versions I have available to me.  Head spinning!

**Comment by jotomo** [comment]
@ShaggydogUK Check that xDrip's _Inter-app-Settings->Broadcast locally_ is off. In AAPS, use config builder to make Dexcom plugin visible and check what readings AAPS has received.

**Comment by ShaggydogUK** [comment]
Good call - I had left inter-app settings turned on after moving from xDrip to patched Dexcom app.  The readings that AAPS received were all showing as two readings for every minute, I guess that would confuse things!  I'll leave it for an hour or so and make sure that I've got deltas that are accurate, and then I'll close the item if all fixed.

**Comment by ShaggydogUK** [comment]
Still getting the problem - I'll remove xDrip and see what that does.

**Comment by ShaggydogUK** [comment]
xDrip removed and now only getting single readings for each minute under G6 menu item, but delta is still not correct - images attached.
![Screenshot_2019-04-16-11-13-55](https://user-images.githubusercontent.com/30231246/56201871-b5bd5f80-6039-11e9-9ef0-c7cc5636fee6.png)
![Screenshot_2019-04-16-11-13-27](https://user-images.githubusercontent.com/30231246/56201872-b5bd5f80-6039-11e9-88dd-2926dd334c70.png)
![Screenshot_2019-04-16-11-13-33](https://user-images.githubusercontent.com/30231246/56201873-b655f600-6039-11e9-94c0-09a1922e114f.png)

**Comment by ShaggydogUK** [comment]
Whereabouts is the delta information taken from?  Is it calculated directly from past readings or is it a more complex method?

**Comment by jotomo** [comment]
Calculated from last 3 (15m delta) 8 (40m delta) readings. The above deltas seem about right (some rounding happening).

**Comment by ShaggydogUK** [comment]
I can see that the 15 and immediate look right allowing for rounding, but on the main screen 40 minute showing as 0.1 but is actually 0.8 or 0.9.  At ehe present time my home screen is showing 0.1, 0.1 and 0.2, but the actual values from the G6 table are 0.1, 0.4 and 0.7.  If I look on the calculator screen I get +0.4 for the 15 minute trend and on the OpenAPS page I get 2, 2.11 and 2.7 in mg/dl or 0.1, 0..1 and 0.15, so it seems immediate and 15 min delta are close, but the 40 minute is off.  I realise the 40 minute doesn't have much impact, but I don't like the fact that somehing is wrong (although it appears that I'm the only one affected, which is good) which means it must be a setting problem somewhere.  Things have definitely improved since I removed xDrip, although when I earlier removed the patched G6 app and only used xDrip it was still happening.  Unfortunately my coding experience doesn't take me into Android Studio (I stopped coding when I was using C++) otherwise I'd dive in and run some tests!

**Comment by ShaggydogUK** [comment]
Showing from now:  
![Screenshot_2019-04-16-14-02-58](https://user-images.githubusercontent.com/30231246/56211966-f5dc0c80-6050-11e9-947c-8b43e049a31c.png)
![Screenshot_2019-04-16-14-02-47](https://user-images.githubusercontent.com/30231246/56211967-f5dc0c80-6050-11e9-97ff-7fb8a71679fc.png)

**Comment by ShaggydogUK** [comment]
![Screenshot_2019-04-16-14-02-47](https://user-images.githubusercontent.com/30231246/56212195-713dbe00-6051-11e9-8280-c4cd8c040c50.png)
![Screenshot_2019-04-16-14-02-58](https://user-images.githubusercontent.com/30231246/56212196-713dbe00-6051-11e9-847f-36f7131d0b01.png)
![Screenshot_2019-04-16-14-02-40](https://user-images.githubusercontent.com/30231246/56212197-713dbe00-6051-11e9-9bed-eaefe5e7be41.png)
