### ISSUE TITLE
Local Broadcast to xDrip+ broken?

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1740]
After installing the actual dev build this morning I lost the connection to xDrip+, no sgv are transmitted to AAPS. I controlled the settings but nothing has changed. Reinstalling an older version reenables the communication.

**Comment by st0ber** [comment]
After I installed the last Dev version, I did not get any blood glucose levels from the patched Dexcom G5 (not the 2018 version). Is this possibly the same problem? Afterwards I installed the master version again and it worked again.
