### ISSUE TITLE
Bolus Calculator and OpenAPS SMB suggestions do not tally up

### ISSUE THREAD

**Issue by tim2000s** [MilosKozak/AndroidAPS#1751]
High glucose level caused by cake. 

16.20 - 18/04/19

I opened the the bolus calculator to see what it suggested. It gave data suggesting missing carbs as shown in the photo below. 

I then compared to OpenAPS SMB output. This suggested max insulin requirement was 3.176u of insulin. 

This is quite a significant mismatch between the two screens and algorithms in use, and suggests that one of them is not operating optimally. I would expect the bolus calculator to use the same logic as oref0/oref1 in determining required insulin. 

![Screenshot_AndroidAPS_20190418-161931](https://user-images.githubusercontent.com/14833174/56372446-ec8ca480-61f6-11e9-8e9a-7dc3165690eb.png)

![Screenshot_AndroidAPS_20190418-162002](https://user-images.githubusercontent.com/14833174/56372464-f57d7600-61f6-11e9-9e31-c875916c323a.png)

**Comment by AdrianLxM** [comment]
@tim2000s do you have a Medtronic pump running in parallel to show the difference?
Be aware that the Medtronic pump cannot factor in COB and IOB, so please disable it in the AAPS bolus calculator before comparison.

**Comment by MilosKozak** [comment]
bolus wizard doesn't take sensitivity ratio 1.5 into a count

**Comment by tim2000s** [comment]
@MilosKozak - why not? Wouldn’t it make sense to have the bolus calculator beingninternally consistent with what the algorithm sees at the time you’re using it?  It doesn’t need to adjust CR but if it’s taking a higher sens ratio into account if there’s a profile switch, it should from an autosens calculation. 

Even then, if you were to take the sens ratio into account on ISF and work it out manually, the calculator would still end up requiring carbs, and not the insulin that is calculated in the algorithm.
