### ISSUE TITLE
Care Portal Temp Basal Rate Does Not Match Value Entered

### ISSUE THREAD

**Issue by timmy354321** [MilosKozak/AndroidAPS#1753]
When I manually input a basal rate the actual basal rate displayed on the dashboard is 100% higher than entered. For example if I input a temp basal rate of 150% it shows I'm set to 250% however if i use units entered instead of the percent the units match the dashboard (set to 0.5 u/hr= 0.5 u/hr) I've attached some images of the issue.
I'm using the open loop function since I have a tandem T-slim pump so i'm manually entering the suggestions for now.

This is a reproducible bug. I'm using AndroisAPS 2.2.2 full release. 

![Screenshot_20190419-060232](https://user-images.githubusercontent.com/48967293/56422048-2f885f80-626b-11e9-8f4d-97b4e64a36fc.png)
![Screenshot_20190419-060246](https://user-images.githubusercontent.com/48967293/56422049-2f885f80-626b-11e9-96ef-eeda0dcc3421.png)
![Screenshot_20190419-060303](https://user-images.githubusercontent.com/48967293/56422050-2f885f80-626b-11e9-8cd6-819de541e5ee.png)

**Comment by MilosKozak** [comment]
careportal is an interface to NS and NS uses different notation
0 - 100% in NS is 100-200% in AAPS
