### ISSUE TITLE
New Dev 2.2.3 (0231395) break closed loop

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#1754]
New Dev 2.2.3 (0231395) break closed loop
After i installed the latest Dev Version, i only can Open Looping.
![Screenshot_20190420-112725](https://user-images.githubusercontent.com/32514747/56455767-e74c6880-6362-11e9-8fda-1f9a794f7fee.png)

**Comment by AdrianLxM** [comment]
Yes, that is still under development. Thanks!

Make sure to re-import your settings saved before updating to that version after switching back to master branch.
