### ISSUE TITLE
Version Checker not working correctly

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#1755]
After updating to latest dev (2.2.3-dev) I see an irritating message: My version is since 18006 days outdated. The consequence for not updating over years is a fallback to open loop. ;-)
![image](https://user-images.githubusercontent.com/12517693/56457067-cb9e8d80-6375-11e9-8db8-68cf8d9e6304.png)
![image](https://user-images.githubusercontent.com/12517693/56457059-b164af80-6375-11e9-871c-1a2b0750cea7.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3100097/AndroidAPS.log)

**Comment by st0ber** [comment]
See https://github.com/MilosKozak/AndroidAPS/issues/1754

**Comment by AdrianLxM** [comment]
This is still under development. I structions on how to switch to master in referenced issue
