### ISSUE TITLE
error gradle androidaps 2.3

### ISSUE THREAD

**Issue by JoanoToxo** [MilosKozak/AndroidAPS#1763]
I had updated gradle ans I get the error:
ERROR: No such property: dir for class: org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection
AndroidAPS sync

**Comment by nitroks14** [comment]
Idem for me.
![image](https://user-images.githubusercontent.com/43478520/56751218-d4340100-6785-11e9-9527-0411eeb38cde.png)
![image](https://user-images.githubusercontent.com/43478520/56751277-f3cb2980-6785-11e9-845c-0bed551f17c1.png)

**Comment by twain47** [comment]
I believe this is the result of upgrading to gradle 5.1.1 (if not please ignore below)

I was able to resolve this by downgrading to gradle 4.10.3. You can do this by editing `gradle/wrapper/gradle-wrapper.properties` and updating the distributionUrl to:

distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.3-all.zip

I then had to sync gradle (File > Sync Project with Gradle Files).

**Comment by otormaigh** [comment]
Looks like its an [issue](https://github.com/arturdm/jacoco-android-gradle-plugin/issues/54) with the `jacoco-android` plugin. They have it fixed in their latest release (0.1.4)

**Comment by MilosKozak** [comment]
do not allow gradle update
