### ISSUE TITLE
Accu-Chek Insight pairing crashes app

### ISSUE THREAD

**Issue by Txger** [MilosKozak/AndroidAPS#1764]
When I try to pair my Accu-check Insight to the Pumpcontrol app it instantly crashes.
--------------
It reopens the first 1 or 2 times, but after the 3rd time the app just closes completely
This began when i first tried it with version 2.2.2 this morning (25th of April 2019) and is still continuing with 2.3
Build is 420fe12ef-2019.04.25-09:23
Phone is a Galaxy Note 8 running Android 9 no root
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3116073/AndroidAPS.log)

**Comment by TebbeUbben** [comment]
Fixed
