### ISSUE TITLE
Difference between TBR on NS graph and treatment history

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#1765]
I'm using Insight pump and AAPS 2.1, using extended TBR's

Pump history is as follows:

![image](https://user-images.githubusercontent.com/2260419/56732454-b05cc500-675d-11e9-942f-4c217ca1ed15.png)

This is rendered as follows. The suggested return to basal was enacted on the pump and shows up in the treatment history as well. For some reason NS does not look at duration but at start of the next temp (eg at 20:33:29)?

![image](https://user-images.githubusercontent.com/2260419/56732871-db93e400-675e-11e9-93a8-1c3768c5338e.png)

**Comment by Paulusma** [comment]
BTW: not related to insight security issue, i did not do a DB reset or install a new AAPS version

**Comment by Paulusma** [comment]
Yesterday i upgraded to AAPS 2.3 but the problem persists, see below:
![image](https://user-images.githubusercontent.com/2260419/56848730-a4533d80-68ec-11e9-92ed-cb197a28c37f.png)
![Screenshot_20190427-123835](https://user-images.githubusercontent.com/2260419/56848753-cb117400-68ec-11e9-8b4f-069f63addff6.png)
![Screenshot_20190427-123857](https://user-images.githubusercontent.com/2260419/56848754-ccdb3780-68ec-11e9-889e-2bef2c7ba346.png)
![image](https://user-images.githubusercontent.com/2260419/56848763-ef6d5080-68ec-11e9-8855-b7eb7b013dff.png)

**Comment by MilosKozak** [comment]
you have to resolve first so many TBRs starting at the same time
