### ISSUE TITLE
Github relese names does not match docs

### ISSUE THREAD

**Issue by CarnageMarkus** [MilosKozak/AndroidAPS#1769]
Hello, [releases](https://github.com/MilosKozak/AndroidAPS/releases) apk naming does not match [docs](https://androidaps.readthedocs.io/en/latest/EN/Installing-AndroidAPS/Building-APK.html?fbclid=IwAR0KlBNwnwXXI7kBaX7fq3-esn6k_SM7PgSy2Dafz5Hk5B7WztSyARpN2B4), which makes me allways question which one of the "ns-clients" do I need. 

`app-nsclient2` option is not in the docs, and does not indicate whats the **difference** between `app-nsclient` and `app-nsclient2`.

Also wiki describes 4 build types:
* full (i.e. recommendations automatically enacted in closed looping)
* openloop (i.e. recommendations given to user to manually enact)
* pumpcontrol (i.e. remote control for pump, no looping)
* nsclient (i.e. looping data of another user is displayed and careportal entries can be added)

while [ilustration](https://androidaps.readthedocs.io/en/latest/_images/Installation_Screenshot_4415.png) right bellow indicates 5 possible builds.

I suggest to change the release apk naming and/or update wiki, so that is clear what release do I need. Also if possible generate all possible builds ?

Cheers, Mark

**Comment by quizzmaster** [comment]
None of the APKs under releases provides the loop functions, but only the nightscout client or the pumpcontrol. `app-nsclient2` is the same as `app-nsclient` but with a different package name to allow parallel instalation in case you want to monitor to different loops.

**Comment by CarnageMarkus** [comment]
Well, that is interesting. I think this information should be either on the wiki, or part of release description.

**Comment by triplem** [comment]
You could edit the wiki docs and pay it forward. 👍
