### ISSUE TITLE
v 2.3 issue with deltas

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#1776]
At 22.43 I had two phones using AndroidAPS both with the same problem  The BG changes had actually been 0.0 for the last change, 0.1 for the 15 minute change and 0.4 for the 40 minute change, however, on both phones, the deltas shown on the main screen were -0.1 (immediate), -0.0 
 (15 minute) and 0.0 (40 minute). One phone has been running aps for months, with no problem until a couple of weeks ago (see #1739), BG source patched Dexcom app (although it happens with xDrip as well), and an Insight pump,  and the other I set up this afternoon, I didn't load preferences, set BG to be sourced from Nightscout, and a generic AAPS virtual pump.  Although there are, at times, differences of */- 0.1 between the shown delta values (I assume rounding errors) the deltas are still a long way from what they are in reality.  The only common ground I can see between the two systems  is that they both connect to Nightscout (although I changed to main phone to not download from Nightscout for a while, with no difference) and the fact that the apk was built on the same PC, although a number of versions of aaps, 2.2.2, 2.1.2, dev, 2.3 have all had the same problem.
[AndroidAPS_newphone.log](https://github.com/MilosKozak/AndroidAPS/files/3119022/AndroidAPS_newphone.log)
[AndroidAPS _mainphone.log](https://github.com/MilosKozak/AndroidAPS/files/3119023/AndroidAPS._mainphone.log)

**Comment by ShaggydogUK** [comment]
Further information, the calculator appears to use the correct delta, but having done a quick calculation in my head it would appear that the OpenAPS uses the incorrect delta - I've turned autosens and SMB off.  My Nightscout site is https://simonnightscout.herokuapp.com

**Comment by ShaggydogUK** [comment]
Looking at the way that the deltas are showing, it seems that the immediate delta is correct, the 15 minute delta is showing the difference between BG 15 minutes ago and 10 minutes ago, and the 40 minute delta is showing the difference between 40 minutes ago and 35 minutes ago.  I have always assumed that they should be showing the difference between 15 minutes ago and now, and 40 minutes ago and now - am I wrong, or is my system doing its own thing!?

**Comment by ShaggydogUK** [comment]
I have now set up a new set of databases in Mongo for Nightscout, which has made no difference, I have tried a new Nightscout site, which made no difference.  It seems that the only constant is the apk - but I have downloaded an entirely new copy of the code from Github.  I will reinstall Android Studio, and see if that makes a difference!  The only change I have ever made to the code withing Android Studio is changing the look of two of the wheels in the Steampunk watchface, and I don't believe that that could cause this!  I'll try rebuilding with brand new code, new keys and everything else.  I'll save importing the setting until after I've had a few readings.

**Comment by ShaggydogUK** [comment]
I've just had a thought, looked at a few of the screenshots posted in the facebook group, and the deltas all look dodgy on them as well!

**Comment by ShaggydogUK** [comment]
It appears (at the momnet, anyhow) that the immediate is showing within +/- 0.1 o f what the immediate should be, the 15 minute is showing the difference between 10 minutes and 15 minutes ago, not between 15 minutes and now, and the 40 minute delta is showing the difference between 40 and 35 minutes, not 40 and now.  Have I misunderstood what the delta should b showing - the differences between the last two readings, the last 4 readings and the last 9 readings is what I understand to be a useful number!

**Comment by jotomo** [comment]
https://openaps.readthedocs.io/en/latest/docs/While%20You%20Wait%20For%20Gear/Understand-determine-basal.html?highlight=short%20delta#openaps-decision-inputs

**Comment by ShaggydogUK** [comment]
@jotomo thank you for that, I had misunderstood what the deltas are supposed to be.  However, looking at my levels and what they have done over the last hour, where they have dropped from 8 to 6.1, each of the deltas is showing 0.1 or 0.2, which is not what is described in the documents.  It could be showing the average change between adjacent readings from the last 15 minutes or so and the average _change_ between values from around 17.5 and 42.5 minutes ago, but the long delta is certainly not the average of values between 17.5 minutes and 42.5 minutes ago less the present value - that is, at present, -0.88, not 0.2 as shown. 

In the example pictured above the average of the value between 17.5 and 42.5 minutes ago is 6.0 which, subtracted from the present value showing of 7.5 give a rise of 1.5,, not 0.2 as shown.

I may still be mis-understanding, but I would really like to know if something is not working right - either the system or my logic - I'm hoping my logic!

**Comment by AdrianLxM** [comment]
(6.1-8)÷60×5 is about 0.15333.

It should show MINUS 0.1 or MINUS 0.2.
Can you confirm that?

**Comment by ShaggydogUK** [comment]
@AdrianLxM yes, 0.2 is being shown, but can you tell me where the /60*5 comes from?

**Comment by AdrianLxM** [comment]
Maybe the misunderstanding comes from: It is the change rate, not the difference. The Unit is not `mg/dl` or `mmol/l` but `mg/dl per 5 minutes` or `mmol/(l *5 min)`

**Comment by ShaggydogUK** [comment]
@AdrianLxM thank  you, I have indeed misunderstood - I hadn't taken the per 5 minutes into account.  I'll close this now.  As a side note, does this mean that the information shown in the link to OpenAPS docs is not as clear as it could be, as I didn't get the "per 5 minutes" idea from that?

**Comment by AdrianLxM** [comment]
I highly appreciate when people check what their system does :)

Do you have ideas? Usually Dana is quite open to PRs that make the documentation clearer :)

**Comment by ShaggydogUK** [comment]
I'll have a look and see if I can make it clearer!  Thanks for being understanding.

Simon
