### ISSUE TITLE
Error Kotlin on AndroidStudio to buid AAPS 2.3

### ISSUE THREAD

**Issue by nitroks14** [MilosKozak/AndroidAPS#1778]
![image](https://user-images.githubusercontent.com/43478520/56862170-5ef44600-69a8-11e9-9926-bb3235e40a06.png)

**Comment by quizzmaster** [comment]
There are only 2 warnings. You can ignore them for now.

**Comment by nitroks14** [comment]
Indeed, I can create the APK in 2.3, but this version crash on my Galaxy S5 while previous versions are installed correctly.
That's why I thought that this comes from this Kotlin error that there is not with the previous versions of AAPS.

**Comment by nitroks14** [comment]
I will try again with AndroidStudio v3.4 ...

**Comment by nitroks14** [comment]
For a first temp, already no build error with version 3.4 of Android Studio.

![image](https://user-images.githubusercontent.com/43478520/56864399-1fd2ee80-69c2-11e9-820b-13687e91164d.png)
