### ISSUE TITLE
BG result stop updating when battery is < 15%

### ISSUE THREAD

**Issue by notlistening** [MilosKozak/AndroidAPS#1782]
Hi,

When my phones battery drops below 15% AAPS no longer receives blood sugar data from xDrip+. Xdrip is still getting updates.

I have observed this twice and after putting the phone on charge and restarting AAPS the data is again available. 

AAPS version 2.3
Android 9 (Lineage)
xDrip+ (Nightly from a week ago)

**Comment by jozzi05** [comment]
@notlistening Try disabling app optimization for androidAPS. [Here](https://support.endomondo.com/hc/en-us/articles/115000384453-Android-Disabling-App-Optimization) are steps for a different app, but the idea is the same.

**Comment by notlistening** [comment]
This has been fixed in the latest builds of AAPS (2.3) / xdrip+ (21 May 2019) and can be closed.
