### ISSUE TITLE
openaps AMA not reporting DIA correctly in 2.3

### ISSUE THREAD

**Issue by gavinhouston** [MilosKozak/AndroidAPS#1784]
I recently migrated from v1.58 to v.2.3 and have noticed inconsistency in the reporting of the DIA used.  

DIA=6hrs in NS Profile.  Confirmed in NS and "NS profile" tab in androidAPS. "Rapid Acting Oref" tab (openAPS) also  reports DIA=6.0h.
But "OPENAPS AMA" tab reports a DIA of 3hrs in the profile section.

Steps taken:
- switched NS profile with DIAs of 4,5 & 7 hours. "OpenAPS AMA" profile always reports DIA=3
- switch to simple profile with DIA of 5 & 7 hours.  "OpenAPA AMA" profile reports DIA=3

The 3hrs seems to be hardwired, below the "hard limit" of 5 hours.  Is this just a reporting issue in the profile section of "OpenAPS AMA" or are the IOB and temp basal calculations using a 3 hour DIA?

**Build details**
AndroidAPS 2.3
Build: c0cbaafe0-2019.04.28-11:45
Flavor: fullrelease
Nightscout version: 0.11.1

**Config**
AndroidAPS 2.3 (build details given below) 
  Profile: NS profile
  Insulin: Rapid Acting  0ref for Humalog & Novorapid
  BG Source: patched Dexcom G5
  Pump: Dana RS
  Sensitivity detection: Oref0
  APS: OpenAPS AMA
  Loop: closed

**Comment by MilosKozak** [comment]
openaps AMA doesn't support DIA > 3. No worry everything is working fine
