### ISSUE TITLE
Error Code 0 (Version 2.3) 

### ISSUE THREAD

**Issue by Bastelfee** [MilosKozak/AndroidAPS#1785]
Since the version 2.3 I have (2 - 3 mal pro Tag)  the message "Requested: x IE. Delivered: 0,00 IE. Error code 0 ALARM STOP OK".

I've inserted a new battery into the Dana R 5 times and it's still happening. 

I then changed the smartphone. It continues to happen. 

I have reset the databases in both smartphones.

G5, xdrip+ (14fecb8-2019.01.10 Code 1901102241), AAPS 2.3

**Comment by MilosKozak** [comment]
provide logs from this time pls

**Comment by Bastelfee** [comment]
Nach Eröffnung des Issues ist der Fehler nicht mehr aufgetreten. Ich denke, dass es doch an meinen Smartphones lag oder an Störungen durch weitere Bluetooth-Geräte im Haus. Sorry.
