### ISSUE TITLE
Combo or Insght?

### ISSUE THREAD

**Issue by Antonio2001** [MilosKozak/AndroidAPS#1792]
Good morning from Spain. Fist of all, I'm sorry for the off-topic, I've been reading everywhere but I'm still quite confused...
Next week I will have to choose a pump and, since the Roche ones don't need additional hardware, I'll take one instead of a Medtronic. The question is, a Combo or an Insight? Combo seems to have quite a lot of "Limitations" in the documentation, but it allows me to use Fiasp. On the other hand Insight is easier to configure (not a big problem, I'm on Android 7 but LineageOS 14 is already installed in my computer :-) )
Thank you in advance for your help and, again, sorry the off-topic.

Antonio

**Comment by ShaggydogUK** [comment]
I use the Insight without a problem.  If you want to use fiasp then you'll need to choose the combo, but I've been fine without it!

**Comment by Antonio2001** [comment]
Thank you for your help :-)
Regards

**Comment by DigitalDan1** [comment]
I personally prefer the Insight. It’s easier to refill (using pre-filled novorapid cartridges, we can’t get fiasp cartridges here in the UK).

One downside is it vibrates when bolusing (most noticeable at night when looping with SMB enabled), which can only be disabled on older Insight models.
