### ISSUE TITLE
App should (optionally) work in background when bolusing from smartwatch

### ISSUE THREAD

**Issue by TEbinger** [MilosKozak/AndroidAPS#1793]
I have a feature request: When bolusing from the smartwatch it should be possible to let the app on the mobile work in background mode. For example when driving with google maps and bolusing from the watch I always lose my navigation view. I had the situation now that my son was playing a game on my smartphone and I disturbed him with my bolus. Maybe there are safety reasons for that behaviour? Could be an option ... Maybe it's not difficult to add?

**Comment by MilosKozak** [comment]
this is a safety feature to be able stop the bolus if needed
