### ISSUE TITLE
This morning at 07.15 I received 2 SMBs, one immediately after the other. 

### ISSUE THREAD

**Issue by vickster1** [MilosKozak/AndroidAPS#1804]
AAPS gave 2 SMBs in the same minute
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by vickster1** [comment]
This am I set a “eating soon” temp target at 07.09. At 07.15 AAPS gave a SMB of 0.3u & immediately after gave another of 0.3u. I was only aware because I’ve not turned of vibrate for bolus on my Dana RS. Pump history showed both had been given, but the calculations on the Loop & SMB pages only mentioned one 0.3u bolus. I’m using v2.3.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3194897/AndroidAPS

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/8290d5a95443613bc56013c4526b05ab36e89274
