### ISSUE TITLE
Feature Request: Remove white bar from Wear OS face

### ISSUE THREAD

**Issue by jamespaulley** [MilosKozak/AndroidAPS#1806]
The white bar on the Wear OS face is flickering in Always On Display Mode. I believe this is because there are too many illuminated pixels for when the display is being given less power by the watch. Can we simply make it black? xDrip+ can do this.

**Comment by dlvoy** [comment]
Implemented for Main, Large and New watchfaces, configurable via settings

![matching_divider_setting_on](https://user-images.githubusercontent.com/5094588/68224965-ea056700-ffef-11e9-828d-14093a7854dc.png)
![matching_divider_on](https://user-images.githubusercontent.com/5094588/68224971-ed005780-ffef-11e9-8a58-71d655866a07.png)

**Comment by jamespaulley** [comment]
Amazing, thank you. Another request: There is currently no difference between the Always On Display and Active Display versions of the watch face. Basically it's very hard to tell if the watch face is active or not. Could we have a low/no colour version for the AOD, perhaps with thinner line weights and less detail?

**Comment by dlvoy** [comment]
It will be lot more of work - but nice idea! Please add another Feature Request / Issue to have discussion on topic there.

**Comment by boc-the-git** [comment]
@dlvoy have you seen any significant battery improvement with this change?

**Comment by dlvoy** [comment]
> @dlvoy have you seen any significant battery improvement with this change?

did not made measurements - my specific watch can handle that amount of white in dim mode, but i like it without - for me it is easier to read
