### ISSUE TITLE
Insight Cartridge Change Resets cannular Age to 0

### ISSUE THREAD

**Issue by notlistening** [MilosKozak/AndroidAPS#1809]
Expected behaviour:
A cartridge change when not changing a cannular should not reset to 0

Actual:
Changing cartridge resets cannular age back to 0

**Comment by TebbeUbben** [comment]
Are you are reporting right? For me it works perfectly. The expected behavior is:
- Log cartridge changes when the pump has found the plug.
- Log cannula changes when you made use of the venting program.
You need to explicitly turn these on in the settings.

**Comment by fra-orolo** [comment]
We use both events (cartridge change and cannula fill) in our daily workflow on 2.3 and both log the correct events to CarePortal. Cartridge changes only reset Insulin Age and Catheder Age is reset when the Catheder flush is used.

**Comment by notlistening** [comment]
I have cheeked this again today and it is working as expected. Closing. Will reopen if I can get it to do it again
