### ISSUE TITLE
Minor flaw in SMB logic?

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1810]
Hi guys,

I'm a bit puzzled. Can someone help me think here? Looking at:
https://github.com/MilosKozak/AndroidAPS/blob/master/app/src/main/assets/OpenAPSSMB/determine-basal.js

Line 1094+1095 will initiate an SMB. Wouldn't it be necessary to add below:

insulinReq = round(insulinReq - microBolus,3);
rate = round_basal(basal + (2 * insulinReq), profile);

To remove the SMB amount from insulinReq when setting the new temp basal rate?

Don't know if it makes any difference in practice. Just think I saw a minor flaw in the logic and even minor flaws can be worth fixing at some point. =)

**Comment by MilosKozak** [comment]
changes to determine_basal.js should go through oref0

**Comment by Mackwe** [comment]
Can you please elaborate your answer? Do you mean I should contact the
OpenAPS crew and ask them to change?

// Marcus

Den tors 27 juni 2019 16:14Milos Kozak <notifications@github.com> skrev:
