### ISSUE TITLE
[2.3] Safety enhancement on setting temp targets?

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#1811]
This is not a bug. It's a security feature request.

I have noticed that as soon as there is a change in NS (i.e. setting a temp target) triggers the loop to run. That's a great feature! But it think it needs a fix to prevent user errors. 

We have accidentally clicked the Eating Soon target instead of Hypo target. Even if we immediately switch back, the loop will run to completion, issuing a high temp or SMB. This can be easily prevented by:

* If NS temp target is set, start a timer for 5-10 seconds
* If the target is still set, run loop

**Comment by MilosKozak** [comment]
sorry this would make too many thing complicated
