### ISSUE TITLE
Question about error message AAPS en accu check combo pump

### ISSUE THREAD

**Issue by Gosee1960** [MilosKozak/AndroidAPS#1816]
Hello i am jose, and after some problems etc, i installend, AndroidAPS, Nightscout, ESEL, Ruffy en Xdrip+. I also have the Smartpix 360 software, where i make neccessary changes en save the file on pump and in a file

AFter some connection problems between my combo en S9 en problems with Ruffy, now it is oke. When i started Ruffy i see the menu from my pump and ik can use it as a remote controller.
But when i restart my phone and AAPS is started i get a error message 
"Invalid pump settings, check the documents and check whether the Quick Info menu is called QUICK INFO using the 360 ​​software"
Can somebody help me and give me some advice? Thanx so far

![Screenshot_20190528-193742_AndroidAPS](https://user-images.githubusercontent.com/50959947/58514121-5ce8f700-81a1-11e9-8a70-dfbbb21fe664.jpg)

**Comment by jotomo** [comment]
- Did you check the Quick Info menu name? (Press the check mark button on the pump and verify the menu showing the remaining units has the title/name _QUICK INFO_). If not, use 360 software to change the name
- Recheck the setup steps from the docs
- Attach log file to issue, see https://androidaps.readthedocs.io/en/latest/CROWDIN/nl/Usage/Accessing-logfiles.html

**Comment by Gosee1960** [comment]
> * Recheck the setup steps from the docs
> * Attach log file to issue, see https://androidaps.readthedocs.io/en/latest/CROWDIN/nl/Usage/Accessing-logfiles.html

Jotomo,

Thank you so much,
> * Did you check the Quick Info menu name? (Press the check mark button on the pump and verify the menu showing the remaining units has the title/name _QUICK INFO_). If not, use 360 software to change the name

I have done this, and it realy helps me, problem solved 
Thanx you so much, i am really happy

I still have one question the last 2-3 nights i get error with a very loud sound. 
![Screenshot_20190528-055445_AndroidAPS](https://user-images.githubusercontent.com/50959947/58587493-d9d9a680-825d-11e9-9c59-12e818f34a9b.jpg)
![Screenshot_20190526-230024_AndroidAPS](https://user-images.githubusercontent.com/50959947/58587494-d9d9a680-825d-11e9-92c6-7f8d82db0850.jpg)
![Screenshot_20190528-035303_AndroidAPS](https://user-images.githubusercontent.com/50959947/58587495-d9d9a680-825d-11e9-972e-2fb3b31ca156.jpg)

What can i do to avoid this?
Thanx so far

**Comment by jotomo** [comment]
Those are alarms AndroidAPS receives from Nightscout. The NSClient plugin in AndroidAPS has preferences to enable/disable those alarms on the phone. Alternatively, if you do want these alarms (but at different levels), you can configure them in Nightscout, see https://github.com/nightscout/cgm-remote-monitor#alarms. If you're using xDrip I'd recommend configuring alarms there instead, as alarms from Nightscout only work with an internet connection.

**Comment by Gosee1960** [comment]
Jotomo,

Thanx again, i changed it. I set off the alarm in Nightscout and set the alarms in xDrip more specific for me.
I hope that i have a silent night :-)

Wish you also a good night 
Greetzzz

**Comment by Gosee1960** [comment]
Hi Jotomo,
I disabled the alarms and i also have a tip to delete bwp by enable. Both i have done
But last night still have 3 alarms one of these (see picture).
Do you have more tips?

![Screenshot_20190530-031458_AndroidAPS](https://user-images.githubusercontent.com/50959947/58616940-315c2e80-82bf-11e9-970d-4b900fc80448.jpg)
![Knipsel](https://user-images.githubusercontent.com/50959947/58616944-33be8880-82bf-11e9-8242-1dceec6f5b95.JPG)

**Comment by jotomo** [comment]
Sorry you got woken again. It's indeed a bit tricky to understand how these alarms are configured.
The settings in a browser only apply to that browser. To change alarm settings globally (so that it applies to every "viewer", whether it is a browser or AndroidAPS) you need to adjust the environment variables (see link in my earlier comment).
Also check in AndroidAPS' preferences, under _NSClient_, there's the section called _Alarm options_. If you disable those, these alarms shouldn't ring either (independent of how Nightscout is configured).

**Comment by Gosee1960** [comment]
You don't to say sorry :-) I am happy with your information. And i know what you mean with the variables. They are in heroku and under config vars
See picture van all my config vars. Can you help me with which one give that warning ?
Because i read the explanation about these vars but i really don't know which one i must use/not use
Thanx sofar

![configvar-2](https://user-images.githubusercontent.com/50959947/58624556-cca9cf80-82d0-11e9-8e72-36b5c6eaddab.JPG)
![Configvar-3](https://user-images.githubusercontent.com/50959947/58624557-cca9cf80-82d0-11e9-87d8-d8221d6a4548.JPG)
![configvar enable](https://user-images.githubusercontent.com/50959947/58624558-cca9cf80-82d0-11e9-861b-9b561530e31d.JPG)
![Configvar-1](https://user-images.githubusercontent.com/50959947/58624559-cca9cf80-82d0-11e9-8368-a9e2d53f34c3.JPG)

**Comment by jotomo** [comment]
Hm, it's been a while since I configured a Nightscout instance. Your last alarm seemed to come from the _predict_ plugin. The docs state the _simple_ alarms plugin should be used when `ALARM_TYPES` is not set though. Try setting `ALARM_TYPES=simple` explicitly, maybe that helps.
