### ISSUE TITLE
Calculation of warnClock missing conversion from minutes to timestamp

### ISSUE THREAD

**Issue by seh-len** [MilosKozak/AndroidAPS#1825]
Hi,

the calculation of warnClock to decide which color formatting is being used doesn't convert the minutes given in PUMP_WARN_CLOCK into timestamp format. So even a slight deviation in the pump clock causes the expression to be 'true' and the level switches to WARN.

[pumpclockfix.patch.txt](https://github.com/MilosKozak/AndroidAPS/files/3259024/pumpclockfix.patch.txt)

**Comment by MilosKozak** [comment]
create PR please

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/0d9578763d40e8f7705b16d1a97db5db45de7676
