### ISSUE TITLE
Battery drain due to constant Wakelock in NSClientService

### ISSUE THREAD

**Issue by rumil** [MilosKozak/AndroidAPS#1826]
As discussed on Gitter (see [this](https://gitter.im/MilosKozak/AndroidAPS?at=5cf55ef6bf4cbd167c250929) post and a few following it) AAPS seems to constantly hold `AndroidAPS:NSClientService` wakelock preventing device from going into deep sleep - see screenshots provided by @p5nbTgip0r ).
I've done a small experiment and "reverted" `ab89e16acd972d252c7ce596ff6810e48a295307` in `info.nightscout.androidaps.plugins.general.nsclient.services.NSClientService` (I don't mean `git revert` but rather manually moving acquiring and releasing wakelock from `onCreate` and `onDestroy` to `initialize()` ).
Have been running it for a few days now and haven't found any drawbacks. However the way I use Nightscout is "upload only".
Battery consumption wise this change allowed me to get a full day on a single charge on my Galaxy S10 where before I needed to plug it in around 16:00-18:00 depending on the day

**Comment by MilosKozak** [comment]
this was disscussed on gitter. closing for now
