### ISSUE TITLE
I switched to Token authentication and now get wrong api secret error

### ISSUE THREAD

**Issue by betrayer111** [MilosKozak/AndroidAPS#1827]
using NSClinet 2.3 build 420fe12ef-2019.04.25-09:23
I switched my authentication on on heroku to token from api secret. I've created a token for nightscout and put it in the api secret preference for NSCLient since I couldn't find a place for the token but I continue to get the error message that the API secret is wrong

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
tokens will be supported in some upcomming versions
