### ISSUE TITLE
AndroidAPS 2.3 full Absturz auf Galaxy S8 

### ISSUE THREAD

**Issue by KiaCeed** [MilosKozak/AndroidAPS#1835]
Reporting bugs
--------------
Galayx S8 + G6 + Xdrip + AAPS 2.3

Vielleicht hat jemand die selbe Hardware und könnte helfen woran der ständige absturz liegen kann? Am Bild 2 kann man ziemlich gut sehen das die App ständig abschmiert.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3305134/AndroidAPS.log)

![Sceen1 1](https://user-images.githubusercontent.com/43519231/59749814-0772a800-927e-11e9-8de8-aff11a5d9a85.jpg)
![Screen2 1](https://user-images.githubusercontent.com/43519231/59749840-0fcae300-927e-11e9-91df-279f0c07f6be.jpg)
![Screen3 1](https://user-images.githubusercontent.com/43519231/59749854-178a8780-927e-11e9-8fd7-b627d54725f6.jpg)
![Screen4 1](https://user-images.githubusercontent.com/43519231/59749881-2113ef80-927e-11e9-9475-1da355c690b4.jpg)

**Comment by MilosKozak** [comment]
no crash is visible in this log file. please reopen if you have more info
