### ISSUE TITLE
TBR with Insight

### ISSUE THREAD

**Issue by JimZam** [MilosKozak/AndroidAPS#1844]
Good evening. I have started using my pump just a weed ago. I'm in Objetive 3. Sometimes, when the app suggest a new TBR and I accept it, Androidaps tries to comunicate with my pump to set it but nothing happens, no error message nor new TBR set. A couple of minutes later it suggest a new TBR again and this time it works. I'm afraid ones the loop is closed it fails setting TBRs.
I have Androidaps version 2.3 and my pump is an Accu-Chek Insight.
Thank you so much for this app
Regards

**Comment by TebbeUbben** [comment]
This can happen in case it fails to communicate with the pump. The algorithm is designed not to cause any harm in such cases.

**Comment by JimZam** [comment]
Nothing to worry about then, thank you.
Regards
