### ISSUE TITLE
Local profile doesn't send timezone in Profile Switch events

### ISSUE THREAD

**Issue by viq** [MilosKozak/AndroidAPS#1845]
When working with @wootmasterslick on dumping history of profile switches to turn them into profiles for either tracking of changes or using for autotune, it turns out that AndroidAPS doesn't send timezone with Profile Switch events when using local profiles.

**Comment by viq** [comment]
Also not all entries had `timeAsSeconds` or `time` set.

**Comment by MilosKozak** [comment]
can you explain it more pls?

**Comment by viq** [comment]
Sorry, I missed the follow up question.

Apparently if you're using a local profile, and change something in it, it
will generate a Profile Switch event sent to nightscout. This can later be
used for example to get profile information to use in autotune.
Those profile switch events don't include time zone in the profile sent.

**Comment by st0ber** [comment]
I only had the Local profile, no Nightscout profile. On my Nightscout page, he also showed with the basal plugin that no timezone is set. After switching from the Local Profile to the Nightscout in AAPS, the basal plugin showed my chosen timezone.
[AndroidAPS._2019-08-07_00-00-00_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3478327/AndroidAPS._2019-08-07_00-00-00_.0.zip)
[AndroidAPS._2019-08-07_00-00-00_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3478328/AndroidAPS._2019-08-07_00-00-00_.1.zip)
[AndroidAPS._2019-08-07_00-00-00_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3478329/AndroidAPS._2019-08-07_00-00-00_.2.zip)

**Comment by MilosKozak** [comment]
i did some changes in 2.4 please restest.
