### ISSUE TITLE
Show insulin activity on BG graph

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#1851]
According to Dana M. Lewis the level of insulin activity is a significant predictor for post-meal BG rise, more so then starting BG level (pge 100 in her book).

If so displaying insulin activity in the main (BG) graph would be of great help in reducing post-meal spikes.

Note: i created such an option in my local version of APS (base V2.3), i've included a screenshot to illustrate the request. The white line is insulin activity, scale is fixed.

![Screenshot_20190629-160340](https://user-images.githubusercontent.com/2260419/60385255-9d30e300-9a87-11e9-89c1-c0f075a3f9d3.png)

**Comment by Paulusma** [comment]
PS: i'm aware of the 'eating soon' option, my request helps the user decide if the 'eating soon' target is needed or not (graph also predicts insulin activity).

**Comment by fra-orolo** [comment]
I would like this plot very much.
@Paulusma If you have it in your local version, could prepare a patch / pull request?

**Comment by Paulusma** [comment]
OK but it will take some time, i've never done that.

**Comment by Paulusma** [comment]
Patch wrt latest master included with 2 changes. Note: in this patch IA is not optional. 
[Display_insulin_activity_in_BG_graph_.zip](https://github.com/MilosKozak/AndroidAPS/files/3352038/Display_insulin_activity_in_BG_graph_.zip)

**Comment by MilosKozak** [comment]
create PR please

**Comment by fra-orolo** [comment]
Good stuff, seems to work well: I just added the menu entry for the new curve and made it switchable.
Need to think about the scaling a bit deeper, the magic 1 / 0.04 produced a too big graph for me.

**Comment by Paulusma** [comment]
Thx for the switch! 

I changed form mmol to mg/dl and noticed no difference. Off-scale can be fixed by making scale dependent on max activity that can safely be achieved, which i think can be caluclated form the max IOB and max bolus U preference settings. This could be the fixed upper limit, but i think a reduction to some %% of this value will be required because during normal operation you will probably be way off this max value. I'll look into that.

**Comment by Paulusma** [comment]
OK insulin activity is in U/min so independent of mg/dl vs mmol setting.
Also determining max activity that can be achieved depends on a lot of additional factors, at least also on type of user, and SMB vs AMA. I think to incorporate that makes the code to determine scale too complex/dependent on other algos. I think it's best to include a new preference setting for the scal of activity in BG graph with a sensible default.

**Comment by Paulusma** [comment]
Currently included in 2.4-dev branch
