### ISSUE TITLE
Activity linked to insulindelivery.

### ISSUE THREAD

**Issue by ellabellakaramella** [MilosKozak/AndroidAPS#1855]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by ellabellakaramella** [comment]
A major problem with a kid is different activity levels that make them go low. Has anyone tried to link activity or heart rate through mobile or watch to regulate insulin delivery? It would at least slow down the bg-fall and give you a little more time to react.

**Comment by MilosKozak** [comment]
refer to discussion on FB
