### ISSUE TITLE
Improve wording for MaxIOB

### ISSUE THREAD

**Issue by Vlin-der** [MilosKozak/AndroidAPS#1865]
I was wondering about the wordings for Max IOB in the app. Not sure whether the wordings are incorrect or if it is simply me who didn't fully understand.
 
In the Settings it says:
For MA / AMA:
_openapsma_maxiob_title_
Maximum basal IOB OpenAPS can deliver [U]
 
_openapsma_maxiob_summary_
This value is called Max IOB in OpenAPS context\nThis is maximal insulin in [U] APS can deliver at once.
 
 
For SMB:
_openapssmb_maxiob_title_
Maximum total IOB OpenAPS can't go over [U]
 
_openapssmb_maxiob_summary_
This value is called Max IOB in OpenAPS context\nOpenAPS will not add more insulin if current IOB is greater than this value
 
 
1) The openapsma_maxiob_summary ends with "can deliver at once". That one seems confusing to me, as this regards basal and ehm basal is delivered over a longer period. I would expect a phrase like "can deliver at once" to be used in a bolus context.
 
2) Wordings between MA/AMA vs SMB are inconsistent, I think it would be better to align them. My personal preference would be to go for the ".... can deliver" for _titles_ and the SMB version for the _summaries_ (use 'if current basal IOB' for MA/AMA).
 
 
This is just a proposal, suggestions are welcome. When I know what to change I can make the pull request myself (PR for the app as well as PR for wiki).

**Comment by MilosKozak** [comment]
please create a PR for comments
