### ISSUE TITLE
Version 2.3 new update procedure

### ISSUE THREAD

**Issue by JimZam** [MilosKozak/AndroidAPS#1866]
Good morning. Somehow I changed my phone date and Androidaps showed the following message:
"New version for at least 30 days available"
I have read the Release notes and the new procedure that fall back to LGS and then to Open Loop. Does that mean that in 60/90 days my Androidaps will stop working even if I have set the correct day in my phone? And why it says that there is a new version available if there isn't?
Thank you in advance
Regards

**Comment by MilosKozak** [comment]
this message was displayed by mistake. latest version is currently 2.3
