### ISSUE TITLE
[SUGGESTION] Warn on hitting hard limit?

### ISSUE THREAD

**Issue by exet0189** [MilosKozak/AndroidAPS#1877]
Just a tentative suggestion for your *wonderful* system.  I've just discovered that AAPS has been reducing down my large evening meal boluses to 17U, without me noticing. I now know I can get round that my changing to "insulin-resistant adult" and/or by issuing multiple boluses. But how about adding a line to the Calculator to point out when a bolus is being reduced because of a hard limit?  (Or indeed a user-set limit in Preferences.)  It was only by investigating the Logs, acting from a tip-off by Marcus, that I discovered what had been happening.  As I say, just a suggestion. I am bowled over by how great AAPS is, so thank you to all.

**Comment by jotomo** [comment]
There is a setting _max allowed bolus_ which the calculator applies and notifies about (popup at the bottom).
If the hard limit is exceeded, the confirmation dialog prints _Bolus constraint applied_ in red letters, together with the adjusted bolus.

_max allowed bolus_ set to 30U:

![Screenshot_1563383924](https://user-images.githubusercontent.com/1732305/61396325-c1822180-a8c7-11e9-9c60-1a452485d1f4.png)

Calculator applies that limit:

![Screenshot_1563383795](https://user-images.githubusercontent.com/1732305/61396222-8849b180-a8c7-11e9-8832-8a7a0b20a40d.png)

Confirmation dialog applies and notifies about hard limit:

![Screenshot_1563383779](https://user-images.githubusercontent.com/1732305/61396252-9b5c8180-a8c7-11e9-9bc5-26cae635fbd3.png)

Please check settings and verify.

**Comment by exet0189** [comment]
Interesting. Thank you. If I put in e.g. 250g, the confirmation dialog box shows Bolus: 17.0U as in your picture above, but there is no red "Bolus constraint applied" message. Current settings for testing purposes are Max allowed bolus 22 and Max allowed carbs 250. Happy to send screenshots if helpful. Just to reiterate, it's not a complaint! I am in awe of what you guys have achieved.

**Comment by jotomo** [comment]
Ah, I was checking with the in-development version, not the current version 2.3. 
The issue is present in 2.3 as you describe, but it's fixed in dev, so it will be correct in 2.4.

**Comment by exet0189** [comment]
Which just shows how far you guys are ahead of me! I really can't thank you all enough :-)
