### ISSUE TITLE
Wrong error message after pump clogging

### ISSUE THREAD

**Issue by heba29** [MilosKozak/AndroidAPS#1882]
If the pump is blocked when a bolus is delivered, the error message is faulty.

I have continued a blous about 7,7 IE. Then came the message about the pump clogging with the hint that 0.20 IE were delivered by the 7.7 IE. The log files of my DANA R pump however said that 7 IE were delivered. Have the missing IE in the Careportal added, so that APPS continues to calculate correctly.

AAPS said something like: "Attention constipation! There were 0.20 IU of it." Actually the 7 IU should have been given and the 7 IU that were given according to the pump should have been used for the calculation.

My System: AAPS 2,3, DANA R, DEXCOM G6

![0](https://user-images.githubusercontent.com/33902762/61608670-d823d200-ac53-11e9-8cf8-19e6ab294b57.jpg)

![1](https://user-images.githubusercontent.com/33902762/61608679-e114a380-ac53-11e9-993b-f163dc76b4b4.jpg)

**Comment by MilosKozak** [comment]
what do you mean by pump is blocked?

**Comment by heba29** [comment]
Hello Milos, i mean the pump can not deliver the insulin during the Bolus.

German: Verstopfung
English: clog or clogging of the catheter.

Grüße Herbert

Am 22.07.2019 um 11:41 schrieb Milos Kozak <notifications@github.com<mailto:notifications@github.com>>:


what do you mean by pump is blocked?

**Comment by MilosKozak** [comment]
R driver doesn't use history from pump. It means in case of broken comm, failed bolus etc the situation must be resolved manualy.
You may upgrade pump to Rv2. This driver reads history

**Comment by heba29** [comment]
Okay. Thank you. But I thought the error message itself was faulty. But if the hitory is not read this makes sense again.
