### ISSUE TITLE
No connection to Accu-Chek insight possible

### ISSUE THREAD

**Issue by michiundso** [MilosKozak/AndroidAPS#1890]
Hey! 
The app crashes after 2 or 3 Times trying to connect the insight pump and restarts.
The list of Bluetooth devices does not appear.
phone is Galaxy S10 
aps Version is pumpcontrol 2.3 
build 420fe12ef-2019.04.25-09:23

**Comment by MilosKozak** [comment]
there is a bug in insight pairing in 2.3 version. wait for next version if this don't work for you

**Comment by Philoul** [comment]
Hello, I'm a new user of AndroidAPS and my problem is quite similar:
When I try to pair my phone (Samsung Galaxy A3) with my Insight pump, Everything is ok until step 3 on the insight pump, I confirm on my phone that the codes on pump and on phone are identical, and after 1min45, an information that pairing has been refused on both pump and phone…
(AndroidAPS v2.3, Android 7.0...)
