### ISSUE TITLE
no connection to Dana RS possible

### ISSUE THREAD

**Issue by Jean73** [MilosKozak/AndroidAPS#1894]
Hello,

I have problems connecting the Dana RS with version 2.3. I tried it with a Unihertz Atom, Samsung S9 and Samsung A6. The same thing happens with all phones: The pump is suggested to me but does not react and does not offer any coupling.  With version 2.0 it works fine. 

Regards

Jean
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3438517/AndroidAPS.log)

**Comment by MilosKozak** [comment]
This is not related to AAPS. Android is not able connect to pump. If you tested so many phones it's time to contact dealer and ask for new pump
