### ISSUE TITLE
[2.4-alpha1] Insulin activity outside graph

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#1902]
The curve of the insulin activity exceeds the canvas of both graphs. Especially on the BG graph the scaling should be much lower to obtain a good overview. The dynamic scaling added from @fra-orolo #1851 might still include a bug.

![Screenshot_20190728-173455__01](https://user-images.githubusercontent.com/2745710/62009387-dd56b480-b15e-11e9-8be6-e164e8887eb6.jpg)

**Comment by quizzmaster** [comment]
I found the scaling factor in the settings, but it is used for both graphs. Shouldn't there be two independent settings to gain more flexibility? I also would prefer setting a maximum for the IA instead of a scaling, so that the IA curve will always stay below a given y-line

**Comment by MilosKozak** [comment]
will you create PR?

**Comment by Paulusma** [comment]
@quizzmaster Scale = 0.05 means that max y value in a graph corresponds to IA = 0.05. I think that is applicable to both graphs? Also clipping larger/negative values is automatic so is it required to limit IA to below given y-line?

**Comment by Paulusma** [comment]
> @quizzmaster Scale = 0.05 means that max y value in a graph corresponds to IA = 0.05. I think that is applicable to both graphs? Also clipping larger/negative values is automatic so is it required to limit IA to below given y-line?

OK i now understand what you mean with 'below given y-line': like eg basals. I would then prefer the y-scale to be a preference (% of max BG) since having both BG and IA on top of each other makes comparison easier.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/0bdaa1708295166a6c6a1b10b98299488d22241c
