### ISSUE TITLE
[2.4-alpha1] Wrong title during installation

### ISSUE THREAD

**Issue by tanja3981** [MilosKozak/AndroidAPS#1904]
During installation the screen displays the wrong application name: "WeekdaysSelector" instead of AndroidAPS
![Screenshot_20190728-185332](https://user-images.githubusercontent.com/7403966/62010325-bb166400-b169-11e9-86a5-048d58d1dbc0.png)

**Comment by jotomo** [comment]
The weekdays-selector lib has a sample app which is packaged in v.1.0.4  of the lib, which contains the same string resources (app_name) as AAPS, which gets overridden.
v.1.1.0. has removed that resource and shouldn't conflict.
