### ISSUE TITLE
[2.4-alpha1] No BGs received through ESel

### ISSUE THREAD

**Issue by tanja3981** [MilosKozak/AndroidAPS#1905]
Using ESel to receive BG values from Eversense sensor by selecting MM640G as CGM source in AAPS. Since installing the alpha version to BGs were received.
AAPS seems to not receive any BGs, not even on "Manual Sync" in ESel.
![Screenshot_20190728-190448](https://user-images.githubusercontent.com/7403966/62010434-fbc2ad00-b16a-11e9-8903-4228e6b3b2bd.png)
![Screenshot_20190728-190506](https://user-images.githubusercontent.com/7403966/62010435-fbc2ad00-b16a-11e9-9370-296a62aa4a9c.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3439394/AndroidAPS.log)

If there is any specific I switch on for logging or check, please let me know.

**Comment by MilosKozak** [comment]
@AdrianLxM must be Esel updated to support SDK28?

**Comment by AdrianLxM** [comment]
Could be that we have to add a package name. Will check the code.

**Comment by AdrianLxM** [comment]
@tanja3981, could you please test this PR?
https://github.com/BernhardRo/Esel/pull/3

**Comment by tanja3981** [comment]
@AdrianLxM Will do in the evening!

**Comment by tanja3981** [comment]
@AdrianLxM The PR solved it!
