### ISSUE TITLE
[2.4 alpha 1] Information "Programing pump for bolusing"

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#1909]
Version 2.4 alpha 1 and older.
When giving bolus and Information "Programing pump for bolusing" is shown if you rotate the screen goes back to "wait for pump...".

**Comment by MilosKozak** [comment]
@jotomo this seems to be combo

**Comment by parapenT1sta** [comment]
@MilosKozak Yes it is :)
