### ISSUE TITLE
Dev branch from 20190729 Automation: Programming temporary profile percentage for given period of time under given conditions is not temporary. Profile is not comming back to 100% after time duration.

### ISSUE THREAD

**Issue by kaniaka** [MilosKozak/AndroidAPS#1917]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by kaniaka** [comment]
![Screenshot_20190730-212321](https://user-images.githubusercontent.com/24974763/62159350-c7d5bc00-b311-11e9-8877-d53c0a03fd5e.jpg)

**Comment by MilosKozak** [comment]
ok, testing now ....

**Comment by MilosKozak** [comment]
test finished and profile returned to previous value. If you have more info put it here to comments

**Comment by MilosKozak** [comment]
@kaniaka reopen if you find more info on this issue
