### ISSUE TITLE
Completed Objectives Forgotten :(

### ISSUE THREAD

**Issue by stugeo1** [MilosKozak/AndroidAPS#1922]
I have been using aaps for months now, and for the last month in closed loop mode having just got an Insight pump and I love it!!

Had the Eversense CGM, sending via ESEL and Xdrip to AAPS and working fine.

Just changed to Dexcom G6 (which I've used before, but not in closed loop mode) and for some reason have lost the objectives I've previously completed, taking me back to Objective 2 and having to wait 7 days, then follow all other objectives again.

Is there any way I can get back to previous settings to show I've completed these.

I did export and then import settings but to no avail.

Hoping you can advise.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
you have to contact us with the poof you were already looping and send us exported settings. (as a personal message)

**Comment by stugeo1** [comment]
Great.
I did export settings previously but not clear where that goes. I wish I'd
emailed them to myself. Is there a way of finding what I'd exported?
Thanks
