### ISSUE TITLE
Problem with AAPS - NS profile invalid !!!

### ISSUE THREAD

**Issue by miz012-om** [MilosKozak/AndroidAPS#1930]
Hello,

I'd like to ask you for help. We plan to order DANA R pump and we wanted to try this APP.

Yesterday we made apk and installation based URL:

https://androidaps.readthedocs.io/en/latest/CROWDIN/cs/Installing-AndroidAPS/Building-APK.html

Everything was OK.

After starting the AAPS we have problem with NS profile. We have our NS created on ns.10be.de about half a year and everything works smoothly. Data are visible in xDrip+ and are shared to other devices without problem, also making reports through NS reporter works correctly.

Only AAPS doesn't accept our NS profile. Everytime there is written in NS Profile tab Profile invalid !!! and in overview tab NO PROFILE SET.

Connection to NS server works, cause XDRIP na NSCLIENT section I see activity...
Also when we update values in profile through ns.10be.de/profile these values /  changes are visible in NS PROFILE tab.

Can I ask you for help? What can be missing in profile? All values are set inside.

Thanks

Ondrej

**Comment by AdrianLxM** [comment]
If you could post a screenshot of your profile it might be easier to figure it out.

**Comment by miz012-om** [comment]
You mean screens from server setup? From ns.10be.de?

**Comment by swissalpine** [comment]
DIA must be set to at least 5 hours if you use Sensitivity Oref1.

**Comment by heba29** [comment]
I think I read that the basal rates have to be completely filled at your NS provider. So from 0:00 - 01:00, 02:00-03:00 and so on. I have the same provider. for me works fine.

**Comment by miz012-om** [comment]
heba29: I set it hour by hour with no effect. Could please send me your server setup?

**Comment by heba29** [comment]
> 
> 
> heba29: I set it hour by hour with no effect. Could please send me your server setup?

You don´t !
![grafik](https://user-images.githubusercontent.com/33902762/62363401-8dda0500-b51f-11e9-8b1f-37b8452d31c1.png)

This way:
![grafik](https://user-images.githubusercontent.com/33902762/62363533-db567200-b51f-11e9-93a5-5fbedb23c99d.png)

**Comment by miz012-om** [comment]
heba29: I set it up, only didn't upload new screen...

![Screenshot_20190802_120513_info nightscout androidaps](https://user-images.githubusercontent.com/51736099/62364850-e65ed180-b522-11e9-81e5-7da04c378b11.jpg)

**Comment by miz012-om** [comment]
In every case. Some connection is working, cause when I restart AAPS it gives me comment into xdrip that AAPS was restarted.

**Comment by zehnBE** [comment]
and IC 00:00 -> 0g
And after them, you need to make a profilswitch to the current profile again.

**Comment by MilosKozak** [comment]
IC zero is the problem and DIA >3
3 intervals are fine

**Comment by miz012-om** [comment]
Thx to all for help. When we put IC > 0g it started to work :)
