### ISSUE TITLE
[2.4 - alpha2] No request to disable battery optimisation

### ISSUE THREAD

**Issue by twain47** [MilosKozak/AndroidAPS#1931]
During the setup wizard no prompt is shown for disabling battery optimisation. Tested on Pixel 2 phone.

Adding REQUEST_IGNORE_BATTERY_OPTIMIZATIONS permission is not enough to trigger this by itself it is also required to test with:

```
powerManager.isIgnoringBatteryOptimizations(packageName)
```

And trigger the dialog with:

```
Intent i = new Intent();
i.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
i.setData(Uri.parse("package:" + packageName));
activity.startActivity(i);
```

**Comment by MilosKozak** [comment]
can you create PR?

**Comment by twain47** [comment]
Have done my best, see #1932 above.

I've done my best but I was unable to work out how to trigger a refresh of the wizard page so to work round that I've made the battery optimisation page optional but I still think it is an improvement.
