### ISSUE TITLE
Font color included in translations

### ISSUE THREAD

**Issue by Vlin-der** [MilosKozak/AndroidAPS#1935]
Should the "<font color= .... </font>" part be included in Crowdin translation strings? Doesn't seem right to me?

Examples:
COB insulin: <font color=\'%1$s\'>%2$.1fg %3$.2fU</font>
<font color=\'%1$s\'>Bolus constraint applied: %2$.2fU to %3$.2fU</font>
<font color=\'%1$s\'>!!!!! Slow carbs absorption detected: %2$d%% of time. Double check your calculation. COB can be really off !!!!!</font>

**Comment by MilosKozak** [comment]
there is no perfect solution for this. either i make really complicated in code or expose the whole string
