### ISSUE TITLE
[Medtronic] (UI): battery indicator shows negative % reading

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#1940]
AAPS 2.4 alpha2 (2019-08-02), when configured to display battery stats for Type: Alkaline (Extended view) displays -11% (1.17v) when the battery is nearing end of life. The pump (a Medtronic 722) shows 1 bar remaining.

**Comment by andyrozman** [comment]
Batteries are tricky like that... We currently have working definition for alkaline set from 1.20V to 1.47V. I could extend this to 1.17V, but then others might get wrong value (they could have 30% left and battery would be dead or something like that)... Or I can just display 0% for all values under 0...Similar as I do for highest value...

**Comment by andyrozman** [comment]
So I went with solution, if number is negative, I set it to 1%. I don't want to change definition of battery, because it might give false readings to other... Another possibility would be to add Custom Battery Type and user could configure it in configuration.

**Comment by andyrozman** [comment]
@rustymonkey Did you check this, is it working correctly now?

**Comment by MilosKozak** [comment]
it works @andyrozman

**Comment by rustymonkey** [comment]
I can confirm the fix as well. Here are the measurements I observed:
Friday afternoon: 100% (aaps) / 1.47v (aaps) / 4 bars (on pump)
Saturday night: 59% / 1.36v / 4 bars
Sunday afternoon: 51% / 1.34v / 3 bars
Tuesday morning: 29% / 1.28v / 2 bars
Tuesday night: 25% / 1.27v / 2 bars
Wed morning: 14% / 1.24 / 2 bars
Wed night: 7% / 1.22 / 1 bar 
Thurs morning: 1% / 1.18v / 1 bar
Thurs noon: 1% / 1.17v / 1 bar 

Interestingly, at this point, the connection to the pump still seems to be reliable. In contrast, with Loop, boluses fail occasionally at about 20% battery remaining (as measured by Loop).
