### ISSUE TITLE
[2.4-alpha3] AAPS crash by open the action tab

### ISSUE THREAD

**Issue by n3cro1** [MilosKozak/AndroidAPS#1948]
![Screenshot_20190808-205900](https://user-images.githubusercontent.com/38436498/62730482-51773f00-ba20-11e9-80e6-637a934c21ca.jpg)
![Screenshot_20190808-205935](https://user-images.githubusercontent.com/38436498/62730483-520fd580-ba20-11e9-801f-9c30a433f1a4.jpg)

**Comment by n3cro1** [comment]
Update: all tabs in "burger menu" crash after selection.

**Comment by MilosKozak** [comment]
updated alpha3
