### ISSUE TITLE
[2.4-Alpha3] Battery optimization prompt issues (crash & optimization)

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#1951]
In 2.4 Alpha 3 (build c8096b096-2019-08-10-21:47), running on an S5mini (Android 6) that had previously been running alpha2 successfully, a dialog (re. #1932) appears on startup indicating:
AndroidAPS needs battery optimization whitelisting for proper performance. 

There are a couple of issues:
1) Clicking 'Request' --> AAPS crashes
[AndroidAPS-crash-on-request-for-power-setting-change.zip](https://github.com/MilosKozak/AndroidAPS/files/3489482/AndroidAPS-crash-on-request-for-power-setting-change.zip)

2) The warning appears despite the fact that the S5 settings has 'App power saving' disabled for both AndroidAPS and xDrip+, and there's no way to remove it! 

Note that xDrip+ also generates a similar warning on this device (I'm guessing it's a Samsung Android6-specific issue), but works around the problem with a toggle setting:
Battery Optimization Prompt [x]
Don't keep asking about battery optimization. Not recommended.

An alternative (and probably better) approach for AAPS could be to only display the warning on startup and give the user a means of dismissing/disabling it. e.g.
'Battery optimization must be disabled for AndroidAPS [Request] [Don't show]'

3) The formatting of the warning is a bit off. a) time appears across 2 rows b) 'REQUEST' is truncated as 'REQU'
![Screenshot_2019-08-10-22-32-44](https://user-images.githubusercontent.com/34991028/62828949-87532980-bbc0-11e9-8721-546175dff7b6.png)

**Comment by rustymonkey** [comment]
4. The same issues affect the Wizard. i.e.
a. Requesting permissing --> crash
b. There's no way to skip this step of the wizard for users with devices that already have power optimization disabled for AAPS.

**Comment by MilosKozak** [comment]
so far this happened only on your phone. could you test the same config on another phone?

**Comment by rustymonkey** [comment]
The issue doesn't occur on the Nexus 5x when clicking the 'request' permission button (using preferences imported from my S5 mini). I suspect that it's device-specific because of the similarities in behavior with xdrip on that device (re. requests for power management permissions not working).

**Comment by rustymonkey** [comment]
Tested on 2.4 Alpha 5 and this issue seems to have been resolved: The warning appears an before, but now, upon clicking 'Request' --> Message appears indicating that this device doesn't appear to support battery optimization and that issues may consequently arise. And upon clicking 'OK' the warning no longer appears (presumably it appears only on startup).

So from my perspective, this issue can be closed, unless further changes are planned to the fix.
