### ISSUE TITLE
[Medtronic][2.4-Alpha3] "Pump Frequency unsupported"

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#1953]
OS dependig Error?
Tested with: 
- Galaxy S5 Android 6
- Galaxy S5 LineageOD 15.1 (Android 8,1)

Pumps tested: 
- 712 and 722 
-  both WW
- also tryed with US frequency

RileyLink 2.0

Medtronic Encoding:
- Software Encoding
- Hardware Encoding

LAST (known) running Verion without problems: 2.4-alpha1 Build a8dc5422d

Log from 2.4_Alpha2
https://gist.github.com/jroth-haj/2492d5a297a786c0a2d8225868e638c7

**Comment by andyrozman** [comment]
Please state exact steps to reproduce.

**Comment by jroth-haj** [comment]
> Please state exact steps to reproduce.

No special steps. I get this error always on 2 different phones. First non functional version is 2.4-Alpha2.
Last full functional version is a.4-Alpha 1 Build like described above.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/compare/2.4_alpha1...2.4_alpha2
no change in MedtronicPumpStatus.java

**Comment by MilosKozak** [comment]
but you are comparing translated strings @andyrozman . this should be changed to some fixed string or ID

**Comment by MilosKozak** [comment]
split `medtronicPumpFreqArray` to values and names and store and check for values. Now I see this must be done for more arrays

**Comment by jroth-haj** [comment]
Will I get a notification after merge to dev?

**Comment by MilosKozak** [comment]
fixed in aplha4
