### ISSUE TITLE
[Medtronic][2.4-Alphax] "Minimum bolus amount 0.1U"

### ISSUE THREAD

**Issue by pjdjesus** [MilosKozak/AndroidAPS#1954]
The minimum bolus delivery for Medtronic 754/554 is 0.1U. 
The pump supports 0.025U.

**Comment by ToreBj** [comment]
We have discussed before. Not completely true, it depends:

Bolus delivery
• Insulin delivered/stroke:
• 0.025 units for bolus amounts in the range of 0.025 to 0.975 units
• 0.05 units for bolus amounts larger than 0.975 units
• Fluid delivered/stroke: 0.25 μL (microliter) for 0.025 unit pump stroke; 0.5 μL for 0.05 unit pump stroke

**Comment by pjdjesus** [comment]
ToreBj I know that. However the 2.4-Alphax version only allow multiples of 0.1U even when you deliver a bolus less than 0.975.

**Comment by ToreBj** [comment]
Yes, and when you enter 0.025 via keyboard it is not recognized as valid input. Just trying to be explicit and complete about the requirement for implementation :)

**Comment by pjdjesus** [comment]
I got your comment. The same happens if one enter 0.05, not recognised as valid input.

**Comment by andyrozman** [comment]
Stop bickering about... If you have time can you please check if this fixes it? Its on my repository in branch: bug_1954_mdt_wrong_min_bolus_for_554. 
Someone notified my that it works wrongly for 522 and lower and I fixed it in configuration, but it seems that new configuration was no communicated back to aaps.
Please test this, so that we can merge it to dev...

**Comment by pjdjesus** [comment]
I've tested on a 754. I was able to deliver 0.05U, but not 0.025U (the bolus step on the pump is set to 0.025U). 
Using the minus/plus increments on the INSULIN button, it increments/decrements by 0.05U. 
I've wrote 0.025, but when I've clicked ok, the confirmation dialogue box had Bolus:0.05U.

**Comment by andyrozman** [comment]
Can you try again. I did another change, this should now cover this. @pjdjesus

**Comment by pjdjesus** [comment]
Hi, app tested. I could deliver 0.025U. However, the minimum step is 0.02U. When I press OK in the confirmation box shows Bolus: 0.03U. The pump delivers 0.025U.
To deliver 0.05U or fraction of 0.05U, you need to introduce x.x4U or x.x6U. The confirmation box shows x.x05U.

**Comment by andyrozman** [comment]
So we changed minimal bolus step for application.  0.025 is not supported by application (2 decimal places) and for bolus this is not required. I changed minimal step to 0.05 now.
