### ISSUE TITLE
Roche Accu-Chek Solo

### ISSUE THREAD

**Issue by jcpeiro** [MilosKozak/AndroidAPS#1958]
Dear Milos,

Would be possible to write down an interface for the new Accu-Chek Solo micro pump?

I am open to provide you all the information you might need on the pump and also willing to help you to contribute writting the new driver:

PUMP TYPE: Roche Accu-Chek Solo  
https://www.accu-chek.co.uk/press-and-media/solo-managed-access

Bolus step: 0.01
Extended bolus step: 0.01
Extended bolus duration step: 15mins
Extended bolus max duration: 24h

Temp basal style: (percent or absolute) percent
Temp basal step:  1%
Temp basal duration step:   1min
Temp basal max value:   Decrease 0-90%   Increase 110-250%
Temp basal max duration:  15min to 24h

Base basal min value: 0.00 
Base basal step: 0.01
Max 24 time blocks, each between 15min - 24h

Let me know pls in case you need any additional information on the pump.

Best regards

Joan Carles Peiro

**Comment by jcpeiro** [comment]
I can provide the control instructions for Solo if needed.  Just send me a table with the equivalent blurtooth connections instructions  and controls for the pump (TBR, Bolus,...) for Insight and I will get the corresponding for Solo.  Let me know pls how best to proceed

**Comment by sennierer** [comment]
Can you maybe give an estimation of how long it will take to include a driver for the solo? I am currently testing the system and will need to decide whether I want to keep using it or switch to another pump. I am currently using AndroidAPS for suggestions and definitely want to stick with it. Great piece of software! Thanks!

**Comment by jcpeiro** [comment]
To my knowledge.  Still will take some time. Mid end 2020.  Solo can not yet be controlled from android phone for BT limitations.  First , new Solo with BT 5.0 support has to be released before we can develop the interfacing. Combo Spirit with FIASP or Insight with ypsomed cartridges to fill FIASP would be the Roche available solutions today.  Solo in mid end 2020.  Also looking forward to test solo when interface is ready.

Enviat des del meu iPhone

El 3 nov 2019, a les 12:28, Matthias Schlögl <notifications@github.com> va escriure:

**Comment by davidwillems13** [comment]
Hey @jcpeiro would you mind elaborating regarding the Bluetooth limitations, doesn't the controller always communicate with the Solo pump via Bluetooth?
Is Bluetooth 5.0 required for the interfacing to be developed?

**Comment by davidwillems13** [comment]
@jcpeiro I'd love some clarification around the bluetooth limitations. I've received a Solo now (referred to as just Bluetooth Low Energy) in the manual. I assume that's most likely V4, but what's the limitation of using that with Android Phones?

**Comment by pbudzon** [comment]
Hi all. I'm interested in helping develop the driver for Solo. From what I can gather so far, I need to wait for my next base change so the sniffer can listen in on the pairing between the base and the pilot to get the code to decrypt later communication.

Has anyone done any work around this? Would be great to hear any thoughts or issues that were already identified.

**Comment by davidwillems13** [comment]
> Hi all. I'm interested in helping develop the driver for Solo. From what I can gather so far, I need to wait for my next base change so the sniffer can listen in on the pairing between the base and the pilot to get the code to decrypt later communication.
> 
> Has anyone done any work around this? Would be great to hear any thoughts or issues that were already identified.

Hey! Great to hear of someone interested in the Solo! I got some Bluetooth captures of a pump base change just the other day, there is also someone who's had success getting low level access to the software that runs on the diabetes manager  (controller), although we haven't been able to get in touch with him quite yet. There is a Discord chat been set up the other day for discussion around the Solo development, but still very early days yet!
Email me at davidwillems13@gmail.com and I'll send you the link to the Discord

**Comment by andyrozman** [comment]
Here is invite for discord group for solo-dev... https://discord.gg/twJ5vyj

**Comment by thiagomsoares** [comment]
any update about Roche Accu-Chek Solo?

**Comment by MilosKozak** [comment]
no progress as I know

**Comment by andyrozman** [comment]
Join the discord and you will be updated... There is #solo-dev  channel there and its still open to public...

**Comment by thomasbeNZ** [comment]
Hi I was unable to find the public solo-dev channel on discord could you please provide an invite as the previous link has expired.

Also keen to try and get pump running. Am doing a new pump base in a couple of days so can capture traffic if it will help.
