### ISSUE TITLE
[Medtronic_maybe][alpha2-4] Double Bolus Entries with eCarbs

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#1964]
Alpha3: 
Using it since launch. Second time that AAPS shows dobble entry. 
Give 5 units correction insulin at 19:43. After that I give eCarbs for 2h. With the first eCarb AAPS make another entry of 5 units insulin at 19:44. 

The second entry was shown in NS IOB, but not in NS graph. But the first icon for eCarbs was different. I delete the first entry of the 5 units. 
https://www.dropbox.com/s/oiq8twacbvcuo8b/Screenshot_20190814-204703_Opera.jpg?dl=0

That was happened only twice from release until now.

Sorry, logs sendet to Andy Rozman yesterday, don't have them anymore.

Now Alpha4 is installed, have an eye on it.

See you
Mario

**Comment by andyrozman** [comment]
This might be tied with Medtronic driver, but it might not.

**Comment by andyrozman** [comment]
[mh_double_bolus_AndroidAPS_LOG_1566064649366.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3512822/mh_double_bolus_AndroidAPS_LOG_1566064649366.log.zip)

![mh_double_bolus_Screenshot_20190817-195716_AndroidAPS](https://user-images.githubusercontent.com/5500133/63222045-ec4ae880-c199-11e9-983b-7a33e26588d2.jpg)

This are the logs and screenshot sent to me...

**Comment by Alamo04** [comment]
The last 0.4U double entry comes from canula change. Without carbs, or eCarbs.

**Comment by pjdjesus** [comment]
I've also got a double entry.
[AndroidAPS.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3512940/AndroidAPS.log.zip)

**Comment by Alamo04** [comment]
The double entrys happens really rarely. I see some with direct starting eCarbs, one with give the filling cannula entry, and one or two with giving correction only.

**Comment by lydiaengler** [comment]
Example of another double entry on Alpha3

Have attached logs and screenshot of Treatments tab.  5U at 21.21.  Then entered ecarbs of 30g over one hour at 21.33.  It has recorded a further 5U bolus with the first chunk of 8g at 21.33

(The invalid was because I tried to remove the one associated with the 8g ecarb)

![IMG_0305](https://user-images.githubusercontent.com/45319130/63229170-61540780-c206-11e9-9a0c-54dd7a38a02e.JPG)


[AndroidAPS_LOG_1566154292030.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3513454/AndroidAPS_LOG_1566154292030.log.zip)

**Comment by Alamo04** [comment]
2 site changes later, with filling over AAPS Alpha4, both with double entrys.
So I have the last 4 site changes double entrys.

**Comment by matti05** [comment]
![Screenshot_AndroidAPS_20190821-104912](https://user-images.githubusercontent.com/24293261/63418074-c3795c00-c402-11e9-955e-57c1cbbb77c7.png)
[AndroidAPS_LOG_1566377603104.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3524416/AndroidAPS_LOG_1566377603104.log.zip)

**Comment by andyrozman** [comment]
@Alamo04 I have checked in change for fill cannula (which is seperate bug as this one, which is for ecarbs). Can you please check if it works for next "Fill cannula"

**Comment by andyrozman** [comment]
@matti05 You actually got to get Triple instead of double... How did you manage that?

**Comment by lydiaengler** [comment]
Using 2.4Alpha4.  This error seems to still be present...

[AndroidAPS_LOG_1567364140888.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3563814/AndroidAPS_LOG_1567364140888.log.zip)
![Screenshot_20190901-195459](https://user-images.githubusercontent.com/45319130/64081091-34b6ea00-ccf4-11e9-85c0-de9a0d00413a.png)

**Comment by m4nnihuber** [comment]
Double entries came back with RC1.
I hava ectually no log file. will check if it comes again and send then log

**Comment by andyrozman** [comment]
When new RC comes out (RC2) please retest this. @m4nnihuber @lydiaengler
