### ISSUE TITLE
[Medtronic][2.4-alpha4] App crashes at startup

### ISSUE THREAD

**Issue by pjdjesus** [MilosKozak/AndroidAPS#1967]
The 2.4-alpha4 crashes continuously on a Samsung Galaxy A3, Oreo 8.0.0, when trying to connect to a worldwide Medtronic pump 754 through a RileyLink v2.2/v2.0.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3512867/AndroidAPS.log)

**Comment by MilosKozak** [comment]
no sign of crash in logs. please reopen if you have more info

**Comment by pjdjesus** [comment]
The is crashing when trying to connect to a MDT pump (phone Sony XZ1 compact, Pie 9.0)
[AndroidAPS.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3526724/AndroidAPS.log.zip)

**Comment by parapenT1sta** [comment]
@pjdjesus I had some crashes but now are being solved, take a look: https://github.com/MilosKozak/AndroidAPS/issues/1970
