### ISSUE TITLE
Units not possible to be changed

### ISSUE THREAD

**Issue by pocsag** [MilosKozak/AndroidAPS#1968]
I cannot change from mg/dL to mmol/L within AAPS. is this something i need to choose before compiling? within the app the choice can be made, but on the dashboard it does not result in a change.. only mg/dL seems possible. as i am used to mmol/L i would like to change this..
i tried to reboot the phone, no luck...

**Comment by jotomo** [comment]
Units can be set in profiles (Local Profile, Nightscout profile) and becomes active when you do a profile switch.
