### ISSUE TITLE
[Medtronic][2.4 Alpha 4] Error in decoding Pump basal profile

### ISSUE THREAD

**Issue by tim2000s** [MilosKozak/AndroidAPS#1969]
Each time AAPS pulls pump data, it reads everything okay, except the basal profile, which contains a decoding error, as below. 
```
11:17:44.697 [main] D/PUMPCOMM: [MedtronicCommunicationManager.checkIfWeHaveMoreData():792]: Length: 190
11:17:44.706 [main] D/PUMPCOMM: [MedtronicConverter.convertResponse():44]: Raw response before convert: 42 00 00 40 00 02 3A 00 04 3E 00 06 36 00 08 46 00 0A 4A 00 0C 4C 00 0E 4E 00 10 4C 00 12 4E 00 14 50 00 16 50 00 18 4E 00 1A 4A 00 1C 4A 00 1E 4A 00 20 4C 00 22 4A 00 24 4A 00 26 48 00 28 00 2A 4A 00 2C 4A 00 2E 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 83 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
11:17:44.709 [main] E/PUMPCOMM: [BasalProfileEntry.<init>():61]: Error creating BasalProfileEntry: startTimeInterval=74, startTime_raw=74, hours=37, rateStrokes=10752
11:17:44.713 [main] E/PUMPCOMM: [BasalProfile.getEntries():238]: Error decoding basal profile from bytes: 42 00 00 40 00 02 3A 00 04 3E 00 06 36 00 08 46 00 0A 4A 00 0C 4C 00 0E 4E 00 10 4C 00 12 4E 00 14 50 00 16 50 00 18 4E 00 1A 4A 00 1C 4A 00 1E 4A 00 20 4C 00 22 4A 00 24 4A 00 26 48 00 28 00 2A 4A 00 2C 4A 00 2E 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 83 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
11:17:44.714 [main] W/PUMPCOMM: [MedtronicCommunicationManager.getBasalProfile():773]: Error reading profile in max retries.
11:17:44.715 [main] W/PUMP: [MedtronicUIComm.executeCommand():71]: Reply not received for GetBasalProfileSTD
11:17:44.716 [main] D/PUMP: [MedtronicUITask.postProcess():188]: MedtronicUITask: @@@ In execute. GetBasalProfileSTD
11:17:44.717 [main] W/PUMP: [MedtronicUIComm.executeCommand():36]: Execute Command: GetBasalProfileSTD
11:17:44.718 [main] D/PUMP: [MedtronicUITask.execute():52]: MedtronicUITask: @@@ In execute. GetBasalProfileSTD
```
[0_AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3518921/0_AndroidAPS.log)

**Comment by andyrozman** [comment]
Can you write me down your full profile....
This is what I could decode, before it crashed... Is there any more or is 20:00 last entry?


DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=00:00, rate=1.6500000000000001]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=01:00, rate=1.6]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=02:00, rate=1.4500000000000002]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=03:00, rate=1.55]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=04:00, rate=1.35]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=05:00, rate=1.75]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=06:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=07:00, rate=1.9000000000000001]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=08:00, rate=1.9500000000000002]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=09:00, rate=1.9000000000000001]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=10:00, rate=1.9500000000000002]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=11:00, rate=2.0]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=12:00, rate=2.0]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=13:00, rate=1.9500000000000002]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=14:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=15:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=16:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=17:00, rate=1.9000000000000001]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=18:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=19:00, rate=1.85]
DEBUG: BasalProfile: Basal Entry: BasalProfileEntry [time=20:00, rate=1.8]

**Comment by andyrozman** [comment]
So after long analysis and help from Eric, I finally found where the problem is. I rewrote some of methods, so it should work correctly now... 

It can be tested in https://github.com/andyrozman/AndroidAPS/tree/bug_1969_error_decoding_basal_profile
