### ISSUE TITLE
[2.4 Alpha 3 and 4] Crashes at startup (Accu-Check Combo)

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#1970]
I own a Redmi 4X using LineageOS and since version 2.4 alpha 3 I simply can't use AAPS, I have been testing compiling it commit by commit and with these two commits the app doesn't start: 
https://github.com/MilosKozak/AndroidAPS/commit/246186f03f8460b1c58866d654d0dca35962c546
https://github.com/MilosKozak/AndroidAPS/commit/0c3d3f0dd87925bc1967551d05d33fb89e25dcbe

I would like to ask if some developer can create a branch with all the 2.4 alpha 4 commits except with these two, so I can test if it is the issue source. I tried to revert them but I get an error compiling the APK.

Thanks

![image](https://user-images.githubusercontent.com/608650/63333240-ff43f100-c330-11e9-9329-fba559663f5c.png)

**Comment by jotomo** [comment]
Thanks for narrowing it down two those commits, that is very helpful!
@MilosKozak seems another SDK check is needed; xDrip guards that check like so: https://github.com/jamorham/xDrip-plus/blob/master/app/src/main/java/com/eveningoutpost/dexdrip/Home.java#L576
LineageOS version should be 15.1 (only officially supported version), which is Oreo / 8.1.

**Comment by jotomo** [comment]
@parapenT1sta Are you on LOS 15.1? My test phone has that version, but I'm not seeing the issue there.

**Comment by parapenT1sta** [comment]
@jotomo Yes, I am. Are you using an Accu-Check Combo too?
I made a video that can show me where I install the version with the commits and what happens as soon I install the alpha 2.

https://drive.google.com/open?id=1-U9P3HzvrQF9-4tVROokWS4KAHeQrRgy

**Comment by jotomo** [comment]
Yes, I'm using a combo, but the issue is independent of the pump used.
I would have believed you without a video ;-) I'm trying to reproduce the crash, so that I can see if a fix solves the issue.

**Comment by parapenT1sta** [comment]
@jotomo Maybe it's just a coincidence but I notice that the app crashes and I have BT icon on the pump alwways on... for minutes, as soon I install Alpha 2 and run the app it goes away after few seconds.

**Comment by jotomo** [comment]
That's coincidental: during start a connection to the Combo is initiated, but since the app crashes the connection is never closed and stays open till Aplha 2 cleanly closes it again (technically: ruffy keeps the connection open until AAPS sends a command to close the connection).

**Comment by parapenT1sta** [comment]
But why only happens after I compile with those two commits?

**Comment by parapenT1sta** [comment]
Running good with no issues: https://github.com/parapenT1sta/AndroidAPS/commits/2.4_alpha_good

![Screenshot_20190820-122019_AndroidAPS](https://user-images.githubusercontent.com/608650/63343166-3d4b1000-c345-11e9-8350-d01902a86a8b.png)

**Comment by swissalpine** [comment]
Same here with actual dev branch.

**Comment by jotomo** [comment]
@swissalpine Could you run the app via Android Studio and copy the output from the run window? There should be a stacktrace where it reads FATAL EXCEPTION.

**Comment by swissalpine** [comment]
Yes. I've seen this in catalog. BUT after pulling the latest commits (dev) the problem seems solved, no restarts. Sorry for my alarm and perhaps a solution for alpha 4?

**Comment by MilosKozak** [comment]
@jotomo did you find a solution?

**Comment by jotomo** [comment]
@MilosKozak No, but it seems the newly added check should only run on devices running Oreo or higher?
@parapenT1sta Can you test with a version where you add this line 
```
Thread.setDefaultUncaughtExceptionHandler((thread, ex) -> log.error("Uncaught exception crashing app", ex));
```

to `app/src/main/java/info/nightscout/androidaps/MainApp.java` after line 141 (the one starting with _sDatabasehelper = .._):

After the app crashes, open the log file[1] and see if there's an entry _Uncaught exception crashing app_.

@twain47 This crash (and probably #1951) started occurring after your changes. Can you help out here?

[1] https://androidaps.readthedocs.io/en/latest/CROWDIN/ko/Usage/Accessing-logfiles.html?highlight=log

**Comment by twain47** [comment]
Doing a bit of research I see this may case a Fatal Exception (android.content.ActivityNotFoundException) on devices without this functionality. I'll see if I can add something to handle this possibility but I don't have any suitable devices to test with.

**Comment by parapenT1sta** [comment]
@jotomo Made an APK as you told: https://github.com/parapenT1sta/AndroidAPS/commits/2.4_alpha3_log

```
6:18:01.669 [main] E/CORE: [MainApp.lambda$onCreate$0():141]: Uncaught exception crashing app
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6494) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ~[na:0.0]
```
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3526044/AndroidAPS.log)

**Comment by jotomo** [comment]
@parapenT1sta Thanks!
If you're up for testing a fix, you can test PR #1975.
Either add my fork as a remote and checkout the branch, or, in Android Studio press Ctrl-Alt-A and enter _View pull requests_ and in the PR window, right click on the PR and select _Create new local branch_.

**Comment by parapenT1sta** [comment]
> @parapenT1sta Thanks!
> If you're up for testing a fix, you can test PR #1975.
> Either add my fork as a remote and checkout the branch, or, in Android Studio press Ctrl-Alt-A and enter _View pull requests_ and in the PR window, right click on the PR and select _Create new local branch_.

Thank you so much. Only in about two hours I can compile it. I promise to give you feedback as soon as I can.

**Comment by parapenT1sta** [comment]
> @parapenT1sta Thanks!
> If you're up for testing a fix, you can test PR #1975.
> Either add my fork as a remote and checkout the branch, or, in Android Studio press Ctrl-Alt-A and enter _View pull requests_ and in the PR window, right click on the PR and select _Create new local branch_.
@jotomo Didn't work :( Do you want me to add the line that you asked before and check for the log?

**Comment by twain47** [comment]
Have created #1976 to attempt to catch errors due to battery optimization.

This doesn't match your error message but based on the commits that caused the issue it may be worth a try.

**Comment by jotomo** [comment]
@parapenT1sta I've added that line to the PR, pull the changes and check if the same message is still locked (whenever you have the time).
@twain47 I think the issues with battery optimization on lower-SDKs and crashes due to foregrounding services seen here are two different issues.

**Comment by parapenT1sta** [comment]
@jotomo 
```
15:27:49.795 [Timer-0] E/CORE: [MainApp.lambda$onCreate$0():142]: Uncaught exception crashing app
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method) ~[na:0.0]
	at java.lang.Thread.start(Thread.java:733) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377) ~[na:0.0]
	at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:620) ~[na:0.0]
	at io.socket.thread.EventThread.nextTick(EventThread.java:76) ~[na:0.0]
	at io.socket.thread.EventThread.exec(EventThread.java:57) ~[na:0.0]
	at io.socket.client.Manager$1$4.run(Manager.java:326) ~[na:0.0]
	at java.util.TimerThread.mainLoop(Timer.java:555) ~[na:0.0]
	at java.util.TimerThread.run(Timer.java:505) ~[na:0.0]
15:27:49.904 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.02, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
15:27:50.375 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.026, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
15:27:50.889 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.024, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
15:27:51.394 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.025, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
15:27:51.919 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.025, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
15:27:52.414 [Binder:8199_3] D/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter$1.rtDisplayHandleMenu():103]: rtDisplayHandleMenu: Menu{type=MAIN_MENU, attributes={BATTERY_STATE=0, BASAL_SELECTED=1, RUNTIME=0:24, LOCK_STATE=0, INSULIN_STATE=0, DEBUG_TIMING=0.024, BASAL_RATE=4.608, TIME=15:27, TBR=480.0, WARANTY=true}}
```
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3530612/AndroidAPS.log)

**Comment by jotomo** [comment]
@parapenT1sta Thanks again. The shown error is a subsequent error, original cause (in the log) is still the original error.
I've pushed another commit with all my remaining ideas. If you're not yet tired of this please test ;-)

**Comment by parapenT1sta** [comment]
> @parapenT1sta Thanks again. The shown error is a subsequent error, original cause (in the log) is still the original error.
> I've pushed another commit with all my remaining ideas. If you're not yet tired of this please test ;-)

Do you think I am tired? I am with my heart full with all the effort you guys are making to get me back with AndroidAPS.

**Comment by parapenT1sta** [comment]
@jotomo 
**We are making PROGRESS!!! YES!!!** Now I can open AndroidAPS but I am getting issues regarding profile that I never got them before, at startup and while using AAPS.

![Screenshot_20190822-195303_AndroidAPS](https://user-images.githubusercontent.com/608650/63541993-2e1bbc00-c517-11e9-973f-4e5ea1d31a47.png)
![Screenshot_20190822-195150_AndroidAPS](https://user-images.githubusercontent.com/608650/63541994-2eb45280-c517-11e9-870c-2bbbd8ca115a.png)
![Screenshot_20190822-195251_AndroidAPS](https://user-images.githubusercontent.com/608650/63541995-2eb45280-c517-11e9-94b9-90aa524b1f2c.png)

**Comment by parapenT1sta** [comment]
@jotomo Just a quick update.
- The messages "value_current basal" only appeared on the first boot after the installation.
- "NO PROFILE SET" is always on at the notification bar, it doesn't go away even when I restart the phone.

**Comment by jotomo** [comment]
The message about `current_basal` being out of range is temporary: on start, the basal rates are read from the pump. If e.g. OpenAPS runs while they're still being read from the pump you get that message. So it's not pretty, but harmless.
About _NO PROFILE SET_. Seems the crashes messed up the active profile switch. After activating your current profile by doing a profile switch it should be fine again.

**Comment by parapenT1sta** [comment]
@jotomo Just did a Profile Switch and also Activated it at NSProfile but no luck, shows me "NO PROFILE SET" 40 min (the time passed from my last restart).

**Comment by parapenT1sta** [comment]
@jotomo Issues are back with 2.4 Alpha 5 :(

**Comment by jotomo** [comment]
@parapenT1sta Please give this PR a final test: https://github.com/MilosKozak/AndroidAPS/pull/1987

**Comment by parapenT1sta** [comment]
> @parapenT1sta Please give this PR a final test: #1987

No luck :( Is not possible to make the Notification messages and sound not work until the app is fully running? I think this is what is making the app crash. Before the crash I will see a popup message on the top screen with my Basal and other info and I hear a sound.

**Comment by jotomo** [comment]
I give up.

**Comment by parapenT1sta** [comment]
> I give up.

@jotomo I want to thank you all your efforts! I am really happy for everything you did to help me. I am the only complaining about this, so for sure the issue is on my side. I will keep using 2.4 alpha 2 until I am able to use it.

**Comment by parapenT1sta** [comment]
@jotomo @MilosKozak Problem solved with the latest DEV. :) THANK YOU.
