### ISSUE TITLE
[2.4 Alpha 4] Medtronic Using Wizard missing IOB 

### ISSUE THREAD

**Issue by MichaelS83** [MilosKozak/AndroidAPS#1971]
Hi,
sometimes when i use the Wizard i get the bolus from the pump but missing it in treatment and IOB but in xdrip and nightscout there is an entry

**Comment by andyrozman** [comment]
We don't read IOB from pump... When you do the bolus Wizard entry we just take CH from it, and discard everything else... IOB and all other entries are ignored.

This won't be changed.

**Comment by MichaelS83** [comment]
Maybe its a AAPS problem, i upload the log files later today and test 2.4 with the insight pump 🤔

**Comment by andyrozman** [comment]
We ignore all information from Bolus wizard except CH... IOB is calculated internally in AAPS, and pump doesn't have information that AAPS has.
