### ISSUE TITLE
Unable to build through Studio 3.5

### ISSUE THREAD

**Issue by KheldarUK** [MilosKozak/AndroidAPS#1981]
Clean machines (OSX and Win 10.)
Fresh downloads of Android Studio and source. Documentation followed verbatim where possible (I believe documentation written for older version of Studio, differences are found during process)

Problem 1. Studio does not give the error messages to install missing SDKs
Problem 2. Error displayed is agreements have not been signed.

Attempted solution. Install missing SDKs manually through Studio settings.

Problem 3. Build fails reporting unable to find com.google.android.wearable 2.0.1

No solution found yet - please advise what I’ve done wrong

**Comment by jotomo** [comment]
3. try this: in SDK manager, under _SDK tools -> Support Repository_, install _Google Repository_

**Comment by astair** [comment]
Dear Milos,
I might have the same issue. I tried to build on macOS Mojave 10.14.6 with a fresh installation of Android Studio 3.5. After the **above stated Problem 2 error**: '_Agreements have not been signed_', I installed Android SDK Platform 27 and Build-Tools 27. The build continued but later through the following error:
```Could not find com.google.android.wearable:wearable:2.0.1.
Searched in the following locations:
    file:/Users/Jonas/Library/Android/sdk/extras/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    file:/Users/Jonas/Library/Android/sdk/extras/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    file:/Users/Jonas/Library/Android/sdk/extras/google/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    file:/Users/Jonas/Library/Android/sdk/extras/google/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    file:/Users/Jonas/Library/Android/sdk/extras/android/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    file:/Users/Jonas/Library/Android/sdk/extras/android/m2repository/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    https://dl.google.com/dl/android/maven2/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    https://dl.google.com/dl/android/maven2/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    https://jcenter.bintray.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    https://jcenter.bintray.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    https://maven.google.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    https://maven.google.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    https://github.com/com.google.android.wearable/wearable/archive/2.0.1.xml
    https://github.com/com.google.android.wearable/wearable/archive/2.0.1.jar
    https://jcenter.bintray.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.pom
    https://jcenter.bintray.com/com/google/android/wearable/wearable/2.0.1/wearable-2.0.1.jar
    file:/Users/Jonas/StudioProjects/AndroidAPS/wear/libs/wearable-2.0.1.jar
    file:/Users/Jonas/StudioProjects/AndroidAPS/wear/libs/wearable.jar
Required by:
    project :wear
```

I tried to install _Google Repository_ as suggested
> 1. try this: in SDK manager, under _SDK tools -> Support Repository_, install _Google Repository_

but could not find the mentioned option:

![image](https://user-images.githubusercontent.com/25106724/63651441-16ca1200-c755-11e9-81c8-7c7a1c98af84.jpeg)

I'd be grateful for other suggestions to try out.

**Comment by MilosKozak** [comment]
2.3 version must be build in studio 3.4
