### ISSUE TITLE
Local Profile: unable to save modified profiles if the modification is deletion of an entry

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#1990]
Tested v2.4-alpha5 build dd7e6e657-2019.08.25-15:02

Replicable as follows:
1 Open Local Profile
2 Delete an IC/ISF/Basal entry in the profile by pressing 'x'
--> No 'Save' button appears to save the modified profile!! 
3 Add an entry to the Profile
--> 'Save' button appears as expected

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/3fed995d5159c9e8bb8d79a8353310beed25973a
thanks!
