### ISSUE TITLE
Local Profile: 'Reset' causes portions of the profile to appear in duplicate

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#1991]
Tested v2.4-alpha5 build dd7e6e657-2019.08.25-15:02

It's possible that I don't understand the intended functionality and that this isn't a bug, however, at the very least, the current behavior is confusing:

1 Open 'Local Profile'
2 Delete an entry 
--> 'Reset' button appears at the bottom
3 Press 'Reset'
--> Duplicate IC/ISF/Basal/Target settings appear! i.e.

DIA settings
...
IC settings
...
IC settings
...
ISF settings
...
ISF settings
...
Basal settings
...
Basal settings
...
Target settings
...
Target settings
...

4 Attempt to edit the settings
--> all kinds of bizarre behavior starts occurring in the dialog (add buttons not functioning as expected, settings not saved, etc.)

5 Switch to a different tab (away from 'Local Profile' and back to Local Profile
--> All the issues that appeared in steps 3 and 4 no longer appear (i.e. the configuration didn't actually get corrupted in steps 3 and 4--it was only a presentation problem)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/0866b480ac3565a22c5be019dccb42e77932ad47
