### ISSUE TITLE
Modifying an existing time in a NightScout profile doesn't update in AAPS

### ISSUE THREAD

**Issue by joshbohmer** [MilosKozak/AndroidAPS#1993]
When updating a time for an existing profile entry, AAPS doesn't update the time field

**e.g.**
```
08:00 - 0.5U
change to
09:00 - 0.6U
```
will update in AAPS/NSClient as
```
08:00 - 0.6U
```

where it should read
```
09:00 - 0.6U
```

**Temporary workaround** 
Delete the entire line and recreate it with the correct time value

**Potential Impact**
Users may intend to change their basal or sensitivities, but without realising they may set the loop running with unintended/incorrect parameters

**Comment by MilosKozak** [comment]
Confirmed.
It's a bug in NS. I'll create an issue there.

**Comment by MilosKozak** [comment]
https://github.com/nightscout/cgm-remote-monitor/issues/4929
