### ISSUE TITLE
Different bolus values using the watch bolus wizard and the wizard on AAPS main screen

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1994]
I'm using AAPS2.3 and use parallel a smartwatch (SWF50). If I use the bolus wizard on the smartwatch often the value is different from using the wizard directly in AAPS2.3 The wizard values on the smartwatch are often higher than the wizard values calculated in APPS wizard directly.

Please see the screenshots. (Made directly on same time)
![20190826_143500](https://user-images.githubusercontent.com/37514390/63691685-2b1f1500-c810-11e9-9f9e-13f05dc1ec6a.jpg)
![20190826_143529](https://user-images.githubusercontent.com/37514390/63691702-33775000-c810-11e9-8fe3-16cb1c4ab59d.jpg)

**Comment by MilosKozak** [comment]
did you doublecheck you do the same calculation? 
checkoxes in wizard vs setting for watch?

**Comment by thomasmenges** [comment]
You have no settings for the wizard for the watch. Only that it appears on the watch. 
So, normally the wizard of the watch should take the same default checkboxes as it is used in AAPS2.3.

These checkboxes are marked automatically as default in AAPS2.3: 
- BG
- BolusIOB and
- BasalIOB
It seems, that the watch wizard do not use these items and so the calculation is completely different.
![20190826_214624](https://user-images.githubusercontent.com/37514390/63718760-9d611b00-c84b-11e9-8f20-56beb3927fc0.jpg)
![20190826_214701](https://user-images.githubusercontent.com/37514390/63718765-a225cf00-c84b-11e9-9f2b-7da4d9f697fb.jpg)

**Comment by MilosKozak** [comment]
there is in preferences under watch

**Comment by thomasmenges** [comment]
You're right. I found the preferences for the watch in AAPS2.3.
My mistake was that I searched for the preferences in the settings on the watch and there you cannot define preferences.
So issue can be closed. Sorry for the circumstances.
