### ISSUE TITLE
[Dev 2.4, Build: cd550e4c0-2019.08.24-13:13] "Profile not set" problem

### ISSUE THREAD

**Issue by kaniaka** [MilosKozak/AndroidAPS#1995]
Hello

I have the problem described below. Additional logs has been also send on logs@androidaps. I am using dev version of aaps, this problem did also happened with Aaps 2.4 alpha 1 and 3:

I cant see the pattern (what is the reason), but from time to time I am losing my profile settings and local data from xdrip (screenshot of this situation is attached to the email). AAPS is stuck.

According to the attached screenshots, I've found this problem f.e. at 11.50 today. I've noticed "Profile not set" on the main screen of aaps. To get rid of this problem I have to "change the profile" in aaps. Afterwards, AAPS gave the information on the main screen that last bg measure was 71 mins ago. On xdrip tab it is showing that bg data has been received.  I've attached the log files in the attachment of this email.

Thank You in advance for help and back information with some advice if it is possible.

Yours Sincerely,
Tomasz Kania.

AndroidAPS 2.4-dev-b
Build: cd550e4c0-2019.08.24-13:13
Remote: https://github.com/MilosKozak/AndroidAPS.git
Flavor: fullrelease
Wersja Nightscout: 0.12.4-dev

Tryb Inżynierski włączony

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
try it without connection to NS

**Comment by parapenT1sta** [comment]
Did you try with latest Dev or Alpha6?

**Comment by kaniaka** [comment]
I did try with latest Dev and without connection to nightscout (with local profile) but it did not solve the problem. Yesterday I've installed RC1 with hope, but in the morning I've received "No profile set" again and two times AAps stucked with "application is not responding" command from android system. I am using Oneplus 6T phone with android pie and all actualizations if it matters.

**Comment by parapenT1sta** [comment]
For some moments I felt that you are facing the same issues I had before but were fixed with the latest alpha and dev versions: https://github.com/MilosKozak/AndroidAPS/issues/1970#issuecomment-524033517

**Comment by kaniaka** [comment]
I think my problems lies in automation plugin. I have several changes set: when bg is bigger than 90 and smaller than 96 and delta is equal or bigger than 1 then set profile 115, when bg is bigger than 96 and delta is bigger than 0 then set profile to 130 percent etc.
With RC1 application is crashing not only while trying to chamge the condition but also while trying to turn off automation plugin.

**Comment by MilosKozak** [comment]
I see Oneplus 6T as most crashing device at all.
I see you using unfinished code (merged AverageProfile which has still bugs) too.
So I'd recommend reset the phone to factory setting and test if clean RC1 with basic features is stable.
If yes then enable more features to determine problem
