### ISSUE TITLE
[2.4 Alpha 4] No warning when setting TT of 72 mmol

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#1997]
When creating a custom TT (either from the menu or through automation) i can set a TT of 72 mmol. There is no warning. This is especially dangerous when using automation as the TT can be set without the user being aware of this (eg on low BG trigger).
In previous versions there was at least a warning. For automation TT levels should be checked upfront. See below for screen of **previous** version.
![iss1996-2](https://user-images.githubusercontent.com/2260419/63783468-5deb0b00-c8ed-11e9-8a78-eeff8659bf21.png)

**Comment by Paulusma** [comment]
NOTE: this is spinoff of #1996. I have disabled the 'battery optimization' request (i use DuOS on SDK 22) but still no warning.

**Comment by Paulusma** [comment]
Investigated further: turns out there is a range check set (2-30) BUT not triggered when not using +/- buttons. Also the default value is not checked but this will be OK once #1996 is fixed.

**Comment by MilosKozak** [comment]
TT limit is now 72-180
https://github.com/MilosKozak/AndroidAPS/commit/66512dbe387bb802bae0a000894e0d3d413a3213
