### ISSUE TITLE
[2.4 Alpha4] Automation trigger range checks not quite right

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#1998]
Automation task, entering trigger for glucose. 

1) Repeatedly using + button eventually leads to range check: 'you reached allowed limit' at 540 mg/dl. But when pressing OK the value 270 is used instead.
2) Repeatedly using - button eventually leads to range check: 'you reached allowed limit' at 40 mg/dl. But when pressing OK the value 72 is used instead.

Trying to set values in the range 270-539 or 41-72 does not result in an error but values are always set to 270 and 72 respectively

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/e6ae4f03d569e19c7eaaf8f5e44892ae4555d605
