### ISSUE TITLE
AAPS2.3 Loop is deactivated but Loop  is creating temp targets

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#1999]
Today I'm checking my Basal values and so I have  loop deactivated.
The Pump delivers normal basal rates but I'm wonsering because AAPS2.3 creates temp targets which are not send to the pump but to NS. The calculation of iob is completely wrong.

By the way. I'm using a local profil
![20190827_212457](https://user-images.githubusercontent.com/37514390/63803918-45431b00-c916-11e9-8a72-313b871cc040.jpg)
![20190827_214925](https://user-images.githubusercontent.com/37514390/63803940-4ecc8300-c916-11e9-9098-a627fad8d5bc.jpg)

**Comment by MilosKozak** [comment]
provide logfile pls

**Comment by MilosKozak** [comment]
are you sure there is no other phone running AAPS connected to your NS?

**Comment by thomasmenges** [comment]
I'm using a second mobile phone but only in virtual pump mode and the upload to NS is complete deactivated.
To test if the phone makes problems I also shut tdown the phone but the issue still exists on the pump phone.

attached is the logfile
[AndroidAPS_LOG_1566941778607.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3548272/AndroidAPS_LOG_1566941778607.log.zip)

**Comment by MilosKozak** [comment]
these logs contains only 2 min: 23:35 - 23:36
no loop invocation during this time
only on cancel of TBR invocated probably manualy
turn off AUTOSENS logging which is producing huge amount of data

**Comment by thomasmenges** [comment]
@MilosKozak I checked again the usage of the second phone. And here was the problem:
* I'm using the second phone in virtual pump mode. On this phone there is also Xdrip as follower defined. 
Why I'm using a second phone ? Beacause my pump phone is an ATOM (very small --> perfect for me. But changing the local profile data a larger screen is necessary. So here the second phone is perfect and i transfer the changed preferences to the ATOM).

Now to the issue:
In the NS data of AAPS2.3 (second phone) there was my NS URL defined because I thought that in virtual pump mode no data will be sent to NS. It's a pitty that data are catched from NS (BG value etc.) but also updated in NS if you're using the virtual pump mode.

So I eliminated the NS URL and now the issue is solved.

But now I have the problem that in AAPS on the second phone no BG values are shown any more although BG source is XDRIP.

Do you have a solution for that or can I define that only NS data are catched in virtual pump mode instead of changing?

**Comment by MilosKozak** [comment]
let NSClient connected but disable data upload
but this will still transfer data  from first phone
if you want 2 independent setups sharing BG data you need 2 NS instances with the same bg collection but others different
