### ISSUE TITLE
Extended bolus

### ISSUE THREAD

**Issue by JimZam** [MilosKozak/AndroidAPS#2007]
Good evening. I use an Insight pump. I've read about ecarbs and the way they replace extended and multiwave boluses. The question is sometimes, in Treatments, I see Androidaps has used extended boluses. Why am I not allowed but the app can use it?
As always, thank you for your help and for this great application.
Regards

**Comment by MilosKozak** [comment]
In Insight driver Extended boluses are used for emulation higher temp basals (>250%) thus they are not available for common use
