### ISSUE TITLE
[2.4 RC1]Automation action Temp target value can be set and started outside safety limits without proper feedback to the user.

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#2014]
NOTE: should be easy fix as profile task 'Percent [%]' editbox already has the desired functionality!

Trying to set the target level using +/- results prevents going beyond the range [4,10] mmol but directly entering a value of eg 30 in the edit box is allowed without warning.

This is a general problem with input controls of that type but notmally, when manually starting a TT, this is no real issue as the user will at least get an error notification when the TT is started (though the TT will still be run at the value eg 30 mmol!).

When TT is activated by automation the same warning is given however the situation is a little bit different, eg the user might be asleep and not paying close attention to the fact that the error was only detected, not corrected.

Since the error message keeps popping up the user will eventually figure out what is wrong so this is perhaps not a bug but a 'feature'. *Although*... the warning sound is of the kind that might not awake one, and: is the sound always played, ie even when sound level set to zero or phone muted?

**Comment by Paulusma** [comment]
[AAPS 2014](https://user-images.githubusercontent.com/2260419/64207155-5652d580-ce9c-11e9-82f1-ebd83fb26a9f.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/c848095060ab66464de036708fcc866400b93840
