### ISSUE TITLE
[2.4 RC1] Automation range &default value for BGdifference when mmol seems wrong

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#2015]
If the range for 'BG difference' trigger is [-4,4] when using mg/dl then should the range for mmol not be [-4/18,4/18]?

**Comment by MilosKozak** [comment]
why? 4mmol = 72 mgdl

**Comment by Paulusma** [comment]
Woops didn't actually check for mg/dl, assumed it would be 4!
