### ISSUE TITLE
Data stops from xdrip to AAPS and settings removed

### ISSUE THREAD

**Issue by Ewan-O** [MilosKozak/AndroidAPS#2016]
Hello All, 

I have recently started (day 2) an open loop using DanaRS, AAPS, xdrip, Nightscout, miaomiao and libre. 

So far it has been running pretty smoothly and I am quite pleased :-)

But I have had the connection to xdrip drop out a couple of times over the course of the day today. The pump is still connected to AAPS and readings are continued in the xdrip app itself, but I am shown the attached screen.

![image-0-02-07-90e7bf64bb3319ad4392420dfe96063f54803e53b2f62c8316798009f72684a3-V](https://user-images.githubusercontent.com/35754106/64238171-033b5a00-cf52-11e9-9ed4-59437cd2e664.jpg)

There are also no settings shown in/the tabs:
- Loop information
- OpenAPS AMA

I have only managed to get the connection going again by re-running the setup wizard. 

I have just exported the settings under the maintenance menu, so hopefully I can import them back to fix this if it happens again.

![IMG_20190904_203113](https://user-images.githubusercontent.com/35754106/64238726-0f73e700-cf53-11e9-84ba-9a3d3665f353.jpg)

Has anyone else experienced this? Or offer me some advice?

**Comment by MilosKozak** [comment]
do you have bg source xDrip?
does it work if you turn wifi and network off?

**Comment by Ewan-O** [comment]
Thanks for the quick reply. :-)
Yes, I am using xdrip as the source of my bg.
With no WiFi or mobile data turned on, my readings in AAPS are not updating.
But xdrip is continuing to gather readings.

**Comment by MilosKozak** [comment]
you have wrong xdrip setting. check wiki
