### ISSUE TITLE
[2.4 RC1] automation 'BG difference' input control not working when profile units = 'mg/dl'

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#2018]
Set profile to mg/dl  and add an automation task with trigger 'BG difference':

1) i can enter a positive value like eg 72 but negative values aren't allowed
2) +/- buttons don't work

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/d452d21c93861b3f7c5b62eb11c1e036c9076fff
