### ISSUE TITLE
[2.4 RC1] Auomation COPY trigger does not work as expected

### ISSUE THREAD

**Issue by Paulusma** [MilosKozak/AndroidAPS#2019]
(Example below uses profile unit 'mg/dl' but error is the same for 'mmol') 
Create a trigger 'short avg delta is lesser than 50' and press COPY.
1) I expect to get an identical copy but instead get 'is equal to' in place of 'is lesser than'

Change the copy to 'Delta is lesser than 10' and pressOK

2) Screen now shows two IDENTICAl triggers 'Delta is lesser than 10' instead of 'Delta is lesser than 10' and 'short avg delta is lesser than 50'

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/139455747e1d78fd85845831411c41549903e450
and found more bugs like this

**Comment by MilosKozak** [comment]
thanks
