### ISSUE TITLE
[2.4-RC1] automation confition Recurring time does not trigger

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2030]
![Screenshot_20190906-003325](https://user-images.githubusercontent.com/28272471/64388168-9225a080-d03e-11e9-8f07-c99d91353520.jpg)
Recurring time as condition with temp target as setting does not set a temp target on that time.

**Comment by MilosKozak** [comment]
can you provide log from 04:01PM ?

**Comment by hartlijn** [comment]
[AndroidAPS._2019-09-14_00-00-05_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3613082/AndroidAPS._2019-09-14_00-00-05_.0.zip)

**Comment by MilosKozak** [comment]
condition "Time" AND "Different time" is never valid

**Comment by MilosKozak** [comment]
this is 4:01AM only
