### ISSUE TITLE
[Dev] wrong URL in objective 2

### ISSUE THREAD

**Issue by MarieT1D** [MilosKozak/AndroidAPS#2035]
Link wrong in:
- monitoring children (line 157)
- suspend loop (line 73)
- wrong carbs (line 141)
- food with protein and fat (better: https://androidaps.readthedocs.io/en/latest/EN/Usage/Extended-Carbs.html) (line  147)

Source:
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/constraints/objectives/objectives/Objective2.java 

URL doesn't fit perfect:
in line 82

**Comment by MilosKozak** [comment]
mostly copy paste erros, thanks, removed wrong ones
