### ISSUE TITLE
[Dev 2.4] Objectives: Profile Switch - 1 answer not clear enough

### ISSUE THREAD

**Issue by MarieT1D** [MilosKozak/AndroidAPS#2037]
"90 % Profil switch => You will get 10% less Insulin in total" is not 100%" correct. If you have your Loop enabled, then it might correct so that you are at 100% again. Or has corrected to 90% Insulin before.
Correct answer would be: 
"90 % Profil switch => You will get 10% less Insulin in total in case  closed loop is not correcting"

**Comment by MilosKozak** [comment]
even correction is affected by percentage. total efect will be close to 90%. 
what about: You will get around 10% less Insulin in total?

**Comment by MarieT1D** [comment]
Sounds better to me! Thanks :)
