### ISSUE TITLE
[Feature Request]: set Temp Target via SMS command

### ISSUE THREAD

**Issue by sw1976de** [MilosKozak/AndroidAPS#2038]
Hello,
would be great to be able to set a TempTarget via SMS Command.

excample
TT BG[value] duration[min]
TT 85 60min

Thanks for your wonderful work!

**Comment by timocm** [comment]
if following from NSclient on a following phone, the TT can be changed and then that is sent to nightscout and then to AAPS on the phone controlling the pump. So why the need for TT via SMS command?

**Comment by dhermanns** [comment]
Regarding the documentation, it should already be possible to set e.g. the Meal Temp Target:
https://androidaps.readthedocs.io/en/latest/EN/Children/SMS-Commands.html

It should be possible to send something like:
`TARGET MEAL`

using the SMS interface. The downside is, that it doesn't seem to work for me using Android APS 2.5.1. Is it a bug or do I miss something?

**Comment by dhermanns** [comment]
> if following from NSclient on a following phone, the TT can be changed and then that is sent to nightscout and then to AAPS on the phone controlling the pump. So why the need for TT via SMS command?

There is no NSClient-App for iOS Devices. So SMS is here right now the only way to do remote controlling...

**Comment by cascer1** [comment]
You can configure temporary targets from the nightscout interface which are then picked up by AAPS @dhermanns, so there is a way to set them remotely from iOS.

**Comment by dhermanns** [comment]
Good tip - missed that one but found it now. Thanks.

**Comment by MilosKozak** [comment]
in 2.6

**Comment by sw1976de** [comment]
Thanks a lot. Very appreciated.

Best regards,
Stefan
