### ISSUE TITLE
[Enhancement] Make Nightscout integration optional

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#2039]
Just noticed #1821 , and wanted to expand on the idea. It would be simpler if all configuration for AAPS is done within AAPS, and nightscout integration wasn't a requirement at all (e.g. in the Objectives). 

If the user wants the remote management, reporting functionality available via Nightscout, then the user can optionally enable it so that they can:
- view BG/AAPS history/profiles remotely
- switch existing profiles remotely (or better yet, switch % overrides)
- set temporary targets
- add carb entries remotely
- etc.

**Comment by MilosKozak** [comment]
NS is currently the only way of exporting looping data from AAPS. until this change we'll force setup of NS

**Comment by rustymonkey** [comment]
OK. Closing.

**Comment by rustymonkey** [comment]
Related to #2090
