### ISSUE TITLE
[Medtronic] Double entry after using wizard

### ISSUE THREAD

**Issue by m4nnihuber** [MilosKozak/AndroidAPS#2040]
Today 09:03 I did a correction with Bolus Wizard.
SMB was working a few moments ago.
SMB was 0.1 Units (Bolus from Pump on 09:03)
Correction was 1.4 Units (Bolus from Pump on 09:04)

i think IOB is calculated wrong becaus eof the missing 1.2 units in careportal
See Pictures and Logs attached

[AndroidAPS_LOG_1568099827656.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3594364/AndroidAPS_LOG_1568099827656.log.zip)
![Screenshot_2019-09-10-09-15-19-599_info nightscout androidaps](https://user-images.githubusercontent.com/48382169/64593618-a951ee80-d3ae-11e9-8234-6d7d95215828.png)
![Screenshot_2019-09-10-09-16-53-384_info nightscout androidaps](https://user-images.githubusercontent.com/48382169/64593619-a951ee80-d3ae-11e9-939c-6677621e942a.png)
![IMG_20190910_093534](https://user-images.githubusercontent.com/48382169/64593620-a951ee80-d3ae-11e9-9586-f548bab0c2c1.jpg)

**Comment by andyrozman** [comment]
For any actions done on Pump directly (you should avoid that), it takes up to 5 minutes to be visible in AAPS (we refresh History every 5 minutes).

**Comment by m4nnihuber** [comment]
@andyrozman 
New test on RC2

See Today on 18:58
Looks like the SMB which was given in the same minute is shown as the bolus.

Should be 9.55 units. Shown as 9.55 units.


![Screenshot_2019-09-29-20-54-41-302_info nightscout androidaps](https://user-images.githubusercontent.com/48382169/65837779-bc941200-e2fb-11e9-8ee1-6080a881433a.png)
![Screenshot_2019-09-29-20-58-48-377_info nightscout androidaps](https://user-images.githubusercontent.com/48382169/65837805-f6651880-e2fb-11e9-8878-82b76dd7b6d9.png)
