### ISSUE TITLE
AAPS 2.4 RC 1 : Insulin to fill the cannula (action menu Pre-fill/fill ) is mistakenly attributed as correction

### ISSUE THREAD

**Issue by peterleimbach** [MilosKozak/AndroidAPS#2043]
Insulin to fill the cannula (action menu Pre-fill/fill ) is mistakenly attributed as correction and therefore added to the IOB. In consequence IOB is higher then real IOB.
Here you see that 4 IE are added as correction to IOB.
![Screenshot_2019-09-10-20-56-14-570_info nightscout androidaps](https://user-images.githubusercontent.com/4148261/64643601-0088ab00-d411-11e9-8950-8adb08cce517.png)
Here you see that their is a "Pumpenkatheder-Wechsel) noted as requested by menu action pre-fill/fill.
![Screenshot_2019-09-10-21-03-47-898_info nightscout androidaps](https://user-images.githubusercontent.com/4148261/64643642-1a29f280-d411-11e9-889a-6d9281e42057.png)

**Comment by MilosKozak** [comment]
i need log files to determine what was wrong

**Comment by peterleimbach** [comment]
I have sent the log files to logs@andriodaps.org.

**Comment by andyrozman** [comment]
Which pump are you using?

**Comment by peterleimbach** [comment]
I use a Dana RS pump.

**Comment by peterleimbach** [comment]
Today I made a fill/prefill again and there was NO error. That means I can not reproduce it.

**Comment by MilosKozak** [comment]
all PUMP debugging was off. it's not possible to dermine what was wrong
