### ISSUE TITLE
Checkbox superbolus in calculator don't recalculate insulin dose

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#2049]
Version 2.4RC1

After check or uncheck check box superbolus, the dose of insulin does not recalculate.

If change ammount of carbs, is correct recalculated.

**Comment by MilosKozak** [comment]
fixxed by https://github.com/MilosKozak/AndroidAPS/commit/4d23fb1d6166a3c9317ec9c2fe808aeb556f58eb
thanks!
