### ISSUE TITLE
[2.4-RC1] Automation tab does not show the latest started tasks

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#2050]
I have defined two tasks „High Glucose TT“ and „Low Glucose TT“. Both are working very well. But at the first day I changed the condition and the action of the both tasks. At the bottom of the AUTOMATION tab, the startet tasks are logged for the first time. But the newest of them are not shown. There I have to go to the TREATMENTS tab and look for the „TempTarget“. And perhaps it would be fine, if the shown started tasks are listed with a date and timestamp and not only with a timestamp. So, it’s easier to find old entries in this list. Perhaps old entries could be cleared every 12 hours.

Kind regards,
Winfried

**Comment by winni67** [comment]
![2CA9677A-9AB7-452F-91A7-B5AEADF3CFD9](https://user-images.githubusercontent.com/6819067/65354879-ef9a1f80-dbf0-11e9-89ed-607687a105f0.png)
![566E4EA3-1164-4E0E-A674-28E42E11D5C1](https://user-images.githubusercontent.com/6819067/65354880-ef9a1f80-dbf0-11e9-9386-a9371742984d.png)
![5E7445AB-EA06-417C-9FBA-CF2BC0798CCA](https://user-images.githubusercontent.com/6819067/65354883-ef9a1f80-dbf0-11e9-8848-5bd7431a4d99.png)

**Comment by MilosKozak** [comment]
scroll problem?

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/3ecee094437358ef6f2bc84912b29c1247e654bc
