### ISSUE TITLE
2.4 RC1 percentage shown incorrectly

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2053]
When using the "Deliver this part of bolus wizard result [%]" I have tried using 25%, 50% and 75%. Each time the bolus given was correct, but the calculation screen always shows [50%] next to the calculated bolus, rather than the actual percentage used.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/bb41ee76d3eda7dcadb8def175b884fb9dfbf890
good catch thanks!
