### ISSUE TITLE
[2.4 RC1] unstoppable notifications

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2057]
so far I've had 3 alarms occurring with 2 problems.  The first is that I don't seem to be able to cancel the alarms/warnings about cannula and insulin age - I change my cannula first thing in the morning, and have the warning, which used to only turn the notification red or yellow on the home screen but now give an alarm as well.  This would be fine if the urgent alarms didn't happen an hour before I get out of bed!  I like the yellow/red notification on the main screen, but would like to be able to get rid of the notification sound.

I have also had a notification warning of future low BG come up, which is useful, but if I dismiss it then it returns before another BG reading has been taken, I've had the notification-dismiss-notification cycle repeated four times for the same BG reading.  I don't have the exact phrasing of the notification at the moment, but will fill it in next time it happens.

**Comment by ShaggydogUK** [comment]
Just come up "Warning. Check BG predicted"Came up at 17.01, Dismissing the message from within AAPS doesn't clear it from the icon, clearing it from the icon doesn't clear it from within the app, so if I just clear the notification from the icon it repeats the alarm from withing the app, and resets the notification it seems.  This may just be and Android quirk, I don't know.

**Comment by ShaggydogUK** [comment]
Check predicted BG alert this morning. I don't want this alert but can't seem to turn it off.  After I cancelled the notification it came back (3 times) until I dismissed it from within the app and then cleared the notification.
,

**Comment by MilosKozak** [comment]
these alarms are comming from NS. setup in NS what you want or let AAPS ignore them
