### ISSUE TITLE
2.4 RC1 eng lost connection with patched Dexcom G6 app

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2059]
AAPS has been working with patched Dexcom G6 until 03.25 this morning (263 minutes ago) when it got it's last reading, nothing passed across since.  The Patched Dexcom app is still getting readings, but nothing coming to AAPS.  I've rebooted phone, restarted bluetooth.  Last 3 logs 
[AndroidAPS._2019-09-18_06-56-16_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3624863/AndroidAPS._2019-09-18_06-56-16_.0.zip)
[Uploading AndroidAPS.log…]()
[Uploading AndroidAPS._2019-09-18_06-15-55_.0.zip…]()

attached.

**Comment by ShaggydogUK** [comment]
Reinstalled Dexcom APP and all is working again.  I had tried reinstalling AAPS and that had no effect.

**Comment by ShaggydogUK** [comment]
It appears that this is a Bluetooth problem with my phone, not AAPS, I've since had my pump and my watch lose connection for a few hours each, while other things stay connected.  I'll shut this down.

**Comment by typ1-brods** [comment]
How can it be a BT issue, when you get further readings in patched app? I have had the same issue with 2.4 patched app, but not with 2.3 patched app 2018

**Comment by twain47** [comment]
This is probably linked to https://github.com/dexcomapp/dexcomapp/issues/19

**Comment by ShaggydogUK** [comment]
@typ1-brods the patched app was losing connecting for a few hours, then reconnecting and backfilling data.  A turn off and turn on of the phone sorted it (not a restart though).
