### ISSUE TITLE
[2.4-RC1] Wrong notification popping up after every profile change

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2062]
Problem: 
Every time I do a profile switch the following message pops up on the home screen: "Basal value replaced by minimal supported value". --> see picture (20.09.2019, 08:12)

Build version: d4f393775-2019.09.01-15:46 full release 

Logs:
[AndroidAPS._2019-09-20_00-01-09_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3634473/AndroidAPS._2019-09-20_00-01-09_.0.zip)
[AndroidAPS._2019-09-20_00-01-09_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3634474/AndroidAPS._2019-09-20_00-01-09_.1.zip)

Screenshot:
![Screenshot_20190920-081256_AndroidAPS](https://user-images.githubusercontent.com/50026512/65304297-8e3a6800-db80-11e9-9a88-0dddb3668366.jpg)

**Comment by MilosKozak** [comment]
You have to remove this wrong PS from treatments tab
