### ISSUE TITLE
Display issues in Config builder

### ISSUE THREAD

**Issue by PedanticAvenger** [MilosKozak/AndroidAPS#2064]
--------------
-able to reproduce at will in my build of 2.4_RC1 fullrelease (d4f393775-2019.09.05-10:51)
  - entering config builder at top level, then entering properties for a list item, then coming back results in display of duplicate option blocks. 

Will add link to screen recording example if it won't directly attach.

https://drive.google.com/file/d/16wWLTB7VCfVQwvtqndwHPRmg9omixuzW/view?usp=drivesdk

**Comment by chriddetyp1** [comment]
Hi! 

I can confirm this behaviour on build d4f393775-2019.09.22-18:23.

BR

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/79c0ca4ca009f8eac8f53eb673140c98edde3327
thanks!
