### ISSUE TITLE
French string problems

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2065]
Hello,

Some little problem or error found in french translation : 

`<string name="careportal_newnstreatment_carbtime_label">Durée glucides</string>`

Durée means Duration, in calulator it's not Duration but an offset time...

I propose :
`<string name="careportal_newnstreatment_carbtime_label">Heure glucides</string>`

The other issue is not a translation problem but a too long string in automation:
`<string name="careportal_temporarytarget">Cible temporaie</string>`

The same String is used several times (Care Portal, automation...)

In automation, when you edit a temp target, "Cible temporaire [mg/dl]" is too long and the "+" button disappears on the right of the popup

I propose :
`<string name="careportal_temporarytarget">Cible temp.</string>`

(or maybe you can use different string name of careportal for automation...)

**Comment by gregorybel** [comment]
are you sure "carb time" is an offset?

**Comment by Philoul** [comment]
when I use it in calculator, it's a time offset for carbs.
if I use calculator at 8:00 and I fill -30 min, carb is 30 min earlier (for example if I was low and started my breakfast at 7:30 half an hour before my bolus).
If I fill +30 min, it indicate that my breakfast will begin 30min later (at 8:30).

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/EN/translations.html
feel free to join translations team and fix it
