### ISSUE TITLE
[2.3] Closed Loop ignores MaxIOB and gives more insulin than allowed

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2067]
I just started closing the loop today and set MaxIOB to 0 as recommend. Still the closed loop reacted to a rising BG:

![image](https://user-images.githubusercontent.com/5219415/65392379-9bb84380-dd74-11e9-8eb6-fdb2d7810b37.png)

![image](https://user-images.githubusercontent.com/5219415/65392382-a07cf780-dd74-11e9-9d1b-c12ad5e225eb.png)

This is a dangerous behaviour in my opinion! I thought it would only suspend on lows in this configuration.

I used the 2.4-RC1 in open loop before and switched to 2.3 to use the closed loop, maybe this triggered the bug?!

**Comment by nshtg** [comment]
Continues to do so:

![image](https://user-images.githubusercontent.com/5219415/65392564-893f0980-dd76-11e9-90cb-5cc0500819c7.png)

**Comment by goomStar** [comment]
This is expected (but maybe not overly mentioned) behavior and will ONLY happen at this point, when your basals have been reduced before and you cummulated "negative IOB". Then and ONLY then AAPS will raise the TBR above 100% and fill the missing IOB IF conditions require.

**Comment by nshtg** [comment]
That's a great feature, thank you!
