### ISSUE TITLE
[2.4 RC 1]

### ISSUE THREAD

**Issue by TEbinger** [MilosKozak/AndroidAPS#2071]
Had a loud and annoying "pump not reachable" alarm with sound, although in Settings, local alarms, Alarm, when pump not reachable" is turned off. 
Never heared this happening on 2.3.
Samsung Galaxy S8, Android 9 Kernel-Version 4.4.111-16626851

excerpt of log file, when this occurred:
17:36:25.722 [main] D/NOTIFICATION: [NotificationStore.add():58]: Notification received: Zeitüberschreitung der Verbindung
17:36:25.729 [EventThread] D/NSCLIENT: [NSClientService$4.call():402]: {"level":0,"title":"Announcement","message":"Zeitüberschreitung der Verbindung","plugin":{"name":$
17:36:26.857 [main] D/info.nightscout.androidaps.plugins.general.overview.dialogs.ErrorDialog: [ErrorDialog$onViewCreated$2.onClick():46]: Error dialog mute button pres$
17:36:26.918 [main] D/CORE: [AlarmSoundService.onDestroy():83]: onDestroy
17:36:28.590 [main] D/info.nightscout.androidaps.plugins.general.overview.dialogs.ErrorDialog: [ErrorDialog$onViewCreated$1.onClick():42]: Error dialog ok button pressed
17:36:28.737 [main] D/CORE: [MainActivity.onResume():147]: onResume
17:36:28.742 [main] D/OVERVIEW: [OverviewFragment.updateGUI():1002]: updateGUI entered from: onResume
17:36:28.745 [main] D/CONSTRAINTS: [StorageConstraintPlugin.isClosedLoopAllowed():55]: Internal storage free (Mb):28199
17:36:28.755 [main] D/OVERVIEW: [Profiler.log():14]: >>> onResume <<< executed in 12 miliseconds
17:36:28.756 [Thread-20740] D/OVERVIEW: [Profiler.log():14]: >>> onResume - 1st graph - START <<< executed in 13 miliseconds
17:36:28.760 [Thread-20740] D/OVERVIEW: [Profiler.log():14]: >>> onResume - 2nd graph - START <<< executed in 17 miliseconds
17:36:28.833 [main] D/OVERVIEW: [Profiler.log():14]: >>> onResume - onDataChanged <<< executed in 90 miliseconds
17:36:30.761 [main] D/NOTIFICATION: [NotificationRecyclerViewAdapter$NotificationsViewHolder.onClick():99]: Notification text is: Zeitüberschreitung der Verbindung
17:36:30.767 [main] D/NSCLIENT: [NSClientPlugin.onStatusEvent():164]: ALARMACK  0 Announcement 3600000
17:36:30.856 [EventThread] D/NSCLIENT: [NSClientPlugin.onStatusEvent():164]: CLEARALARM received
17:36:30.859 [EventThread] D/NSCLIENT: [NSClientService$7.call():490]: {"clear":true,"title":"All Clear","message":"Announcement - Info was ack'd","group":"Announcement$
17:36:31.262 [main] D/OVERVIEW: [OverviewFragment.updateGUI():1002]: updateGUI entered from: EventDismissNotification
17:36:31.271 [main] D/CONSTRAINTS: [StorageConstraintPlugin.isClosedLoopAllowed():55]: Internal storage free (Mb):28199
17:36:31.306 [main] D/OVERVIEW: [Profiler.log():14]: >>> EventDismissNotification <<< executed in 42 miliseconds
17:36:31.307 [Thread-20743] D/OVERVIEW: [Profiler.log():14]: >>> EventDismissNotification - 1st graph - START <<< executed in 43 miliseconds
17:36:31.314 [Thread-20743] D/OVERVIEW: [Profiler.log():14]: >>> EventDismissNotification - 2nd graph - START <<< executed in 50 miliseconds
17:36:31.346 [main] D/OVERVIEW: [Profiler.log():14]: >>> EventDismissNotification - onDataChanged <<< executed in 82 miliseconds
17:36:40.063 [main] D/CONSTRAINTS: [Constraint.setIfSmaller():68]: Setting because of smaller value 1111111 -> 160 (Begrenze Kohlenhydrate auf 160 g wegen Max. Wert in $
17:36:40.064 [main] D/CONSTRAINTS: [Constraint.setIfSmaller():68]: Setting because of smaller value 1111111.0 -> 40.0 (Begrenze Bolusmenge auf 40,0 IE wegen Limit der P$
17:36:40.065 [main] D/CONSTRAINTS: [Constraint.setIfSmaller():68]: Setting because of smaller value 40.0 -> 14.0 (Begrenze Bolusmenge auf 14,0 IE wegen Max. Wert in den$
17:36:40.075 [main] D/CORE: [BolusWizard.doCalc():197]: info.nightscout.androidaps.utils.BolusWizard@27249eb
17:36:40.242 [main] D/CORE: [BolusWizard.doCalc():197]: info.nightscout.androidaps.utils.BolusWizard@39df04a
17:36:41.320 [main] D/AUTOMATION: [AutomationPlugin.processActions():165]: processActions
17:36:42.914 [main] D/info.nightscout.androidaps.utils.SingleClickButton: [SingleClickButton$1$1.run():59]: Button enabled
17:36:48.066 [EventThread] D/NSCLIENT: [NSClientPlugin.onStatusEvent():164]: PING received
17:37:00.346 [main] D/CORE: [MainActivity.onResume():147]: onResume
17:37:00.348 [main] D/OVERVIEW: [OverviewFragment.updateGUI():1002]: updateGUI entered from: onResume
17:37:00.349 [main] D/CONSTRAINTS: [StorageConstraintPl

**Comment by MilosKozak** [comment]
this is comming from NS. you have to disable NS alarms too

**Comment by TEbinger** [comment]
All alarms are turned off in aaps settings ... 
![Screenshot_20190923-210319_AndroidAPS](https://user-images.githubusercontent.com/23135590/65456138-fd49e200-de48-11e9-9fe2-c16762ec81ed.jpg)
