### ISSUE TITLE
[2.4-RC2] Automation with two conditions does not work

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2077]
Automation with two conditions does not work (see enclosed picture). Of course, both conditions were met. Automation was created about 5 minutes before the screenshot.
Build: e05443d02-2019.09.24-15:59
![Automation](https://user-images.githubusercontent.com/13958493/65538265-43657b00-df07-11e9-9b8b-cc11abb5afe9.jpg)

**Comment by MilosKozak** [comment]
it may seem it doesn't work but it's because 5 min limit between executions

**Comment by xJoe** [comment]
Was not aware of that and obviously not patient. I will add this information to wiki.
