### ISSUE TITLE
[2.4-RC2] Extended status lights too wide

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2078]
Extended status lights do not fit screen width [Galaxy A3 (2017)] and are presented in three rows instead of one. Therefore graph heigth is reduced and this makes graph less readable.
Build: e05443d02-2019.09.24-15:59
![ExtendedStatusLights](https://user-images.githubusercontent.com/13958493/65538535-cc7cb200-df07-11e9-881c-e6c2f3699644.jpg)

**Comment by MilosKozak** [comment]
improved by https://github.com/MilosKozak/AndroidAPS/commit/300eecf27d329a31548b5da7119cddedd0a36d38
