### ISSUE TITLE
[2.4-RC2] App crashes in Config Builder

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2079]
Can someone please confirm this? I get the same error in Full and in NSClient builds. Tried on 2 different Samsung phones.

Config Builder > General > Overview > Gear icon. App freezes completely. Screen goes black and the user can't do anything. Not even press O (home), as the controls are gone. I locked the screen, unlocked (to get the Android controls visible) and killed the app. Same error regardless of times tested. Other Config Builder menu options work.

**Comment by MilosKozak** [comment]
no crash here

**Comment by xJoe** [comment]
Works fine on Samsung Galaxy A3 (2017)

**Comment by Mackwe** [comment]
I tried it on an A3 (2017) and an S9. Both failed. Will try a rebuild then.

Den ons 25 sep. 2019 12:05xJoe <notifications@github.com> skrev:

**Comment by Philoul** [comment]
Works fine on Samsung Galaxy A3 2016

**Comment by adrianagomezdiaz** [comment]
My nsclient and too nsclient2 is in off when click in prefer.

**Comment by MilosKozak** [comment]
try if it's related to specific preferences i.e. if it works with clean install

**Comment by winni67** [comment]
Works on a motorola one.

**Comment by mjroodt** [comment]
I can confirm my nsclient crashes on samsung s10 in same scenario as post.

**Comment by MilosKozak** [comment]
resolved by https://github.com/MilosKozak/AndroidAPS/pull/2084
