### ISSUE TITLE
ver 2.4 RC2 problem with questions in objectives

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2081]
Living the questions under the objectives, but a roblem with one of them. For question about The IC Value you refer to "bread units" - I've never come across these, so those questions are meaningless to me.  I work in carbs only.

**Comment by MilosKozak** [comment]
easy to google it. most of T1D are still using BU for calculations. the question is objectives should teach everyone to use [g]
