### ISSUE TITLE
Enhancement: Omnipod support

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#2082]
Hello,

what‘s about the integration of the Omnipod pump? There is a lot of work done with the OmniCore project
https://github.com/winemug/OmniCore
and the customized version of AndroidAPS
https://github.com/winemug/AndroidAPS
Is there a timeline for the Omnipod integration?
Thanks in advance.

**Comment by MilosKozak** [comment]
there is no ETA yet
