### ISSUE TITLE
[2.4-RC2] Profile switch duration max. 24h

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2083]
PS duration is limited to 24 h (1.440 min.) I think it was not limited in 2.3.
Usecase: Depending of way of transport to the office (bike or car) I have a different profile. Depending on weather forecast [only sunshine cycler ;-)] I change profile and would like to do that also for several days.
Build: e05443d-2019.09.24-15:59

**Comment by MilosKozak** [comment]
7 days
https://github.com/MilosKozak/AndroidAPS/commit/c6f2eaecdc4cb16c67fbf230ef4abc3f8ed22623
