### ISSUE TITLE
[Feature Request] make NsClient websocket optional

### ISSUE THREAD

**Issue by cascer1** [MilosKozak/AndroidAPS#2090]
Currently, AndroidAPS uses a persistent websocket connection to Nightscout to upload and download treatments. While I think it's very cool to have all changes show up instantly, I think that being able to use my phone for an entire day without having to charge it is more valuable.

Instead of using a persistent websocket connection, I would like to have the option to upload/download treatments similarly to how OpenAPS does it (i.e: once every five minutes) I believe this would improve battery life of my phone without greatly impacting AndroidAPS functionality.

**Comment by MilosKozak** [comment]
this will come with NS api v3
