### ISSUE TITLE
 2.4 RC2 issue with objectives 3. The IC Value:  IC vs. CR

### ISSUE THREAD

**Issue by libxmike** [MilosKozak/AndroidAPS#2096]
Objective 3. The IC Value: is asking what IC is but the docks (link in objectives) describes CR, could be confusing for newcomers

**Comment by tim2000s** [comment]
Please feel free to CR an edit to the docs in for the wiki.

**Comment by libxmike** [comment]
> Please feel free to CR an edit to the docs in for the wiki.

I'm just not sure where is the mistake, AAPS objectives or the docs as CR is different from I:C, looks like the docs description is describing CR but objectives says IC

**Comment by xJoe** [comment]
Thanks for your hint. Changed wiki: https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/FAQ.html#insulin-to-carb-ratio-ic-g-u
Can you please close this PR @libxmike? Tx.
