### ISSUE TITLE
Issue "Bolus Constraint applied" in Calculator for Corr between 0.02 and 0.04

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2098]
Hello

I have compiled last dev branch yesterday and the problem still exist... (re-open the problem) 
I have "Bolus constraint applied" message for each "Corr" between 0.02 and 0.04 in calculator...

_Originally posted by @Philoul in https://github.com/MilosKozak/AndroidAPS/issues/2066#issuecomment-539189570_

**Comment by MilosKozak** [comment]
what pump do you use?

**Comment by Philoul** [comment]
Accu chek Insight

**Comment by MilosKozak** [comment]
version of AAPS?

**Comment by Philoul** [comment]
problem view on 2.3, 2.4 RC2, 2.4 RC3

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/14dd29befd79aeaca88196d9534c708ccf6583db
