### ISSUE TITLE
RC3 gets no data from Dexcom 2.4 region3 app from Oct08

### ISSUE THREAD

**Issue by dalilith** [MilosKozak/AndroidAPS#2103]
Aaps gets no data from the last com.dexcom.g6.region3.mgdl-patched.apk app. I'm using G6 with 8G transmitter, former versions of the 2.4 app crashed. The new app works fine but i still got no data in aaps.

#
[AndroidAPS_LOG_1570617517449.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3706899/AndroidAPS_LOG_1570617517449.log.zip)
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
Update G6 app
