### ISSUE TITLE
[2.4RC3]SMB Autosens Pb with data

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2104]
I have a problem with autosens data as you can see in screenshot below...

Each hour is indicated twice:
--(7)[70g]x(7)[70g]xxxx
xx(8)(PROFILESWITCH)x(8)(PROFILESWITCH)xxxxx
--(23)=(23)=++

![AAPS2 4RC3BugDonnéesAutosens](https://user-images.githubusercontent.com/52934600/66477832-55175880-ea99-11e9-853d-e4db69593b40.png)

**Comment by Philoul** [comment]
This morning everything is ok... The only thing I done is a Site Change.

**Comment by MilosKozak** [comment]
i'm unable to locate this issue. i'm waiting until this happen to any dev or a user who allows me connect to his computer with connected phone

**Comment by Philoul** [comment]
I am completely new to android developments, but I have already developed small applications on other systems (Javascript, C ++, VBA, ...)
I'm going to try to build skills to help ...
For the current issue, maybe we can close it. It appeared once after the installation of RC3 and since the next day, everything is Ok...
