### ISSUE TITLE
[All version] Calculation screen : No Strings to translate "ISF" and "IC"

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2105]
There is no "String" to translate ISF and IC in caculation screen...

In french we have other acronyms... (SI for ISF and G/I for IC)...

![Calculation](https://user-images.githubusercontent.com/52934600/66479605-2ac79a00-ea9d-11e9-9e92-7baf9383b9cc.png)

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/1340f60b5a2e02784a07dd3d4682892c4ba5af0b
