### ISSUE TITLE
[2.4RC3] Automation trigger still active with deactivated Loop

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2108]
I deactivated closed loop yesterday for todays tests (BR and other factors). After my midday meal I had some BG rise which caused my automation trigger to fire and made a profile switch. Is this behaviour wanted? 
I was under the impression that disabling loop will also deactivate any automation. A TT wouldn't be a problem as loop is disabled but nevertheless why is it still active?

![Screenshot_2019-10-09-19-03-47-818_info nightscout androidaps](https://user-images.githubusercontent.com/38214111/66508391-4ba9e280-ead1-11e9-95fb-b18681bd5d5f.png)
![Screenshot_2019-10-09-16-32-04-599_info nightscout androidaps](https://user-images.githubusercontent.com/38214111/66508392-4ba9e280-ead1-11e9-9330-a6eb31b9266c.png)

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/63aaa3883437f3a32cf22e27672a8d9017e3179b
