### ISSUE TITLE
[2.4RC3] Primed insulin shows up as negative IOB while disabled loop

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2109]
I primed for new pump site today 17:20 and the primed insulin showed up as negative IOB although loop was disabled. 
Why would any primed insulin show up in IOB? Shouldn't it be ignored in any case?

![Screenshot_2019-10-09-18-01-10-546_info nightscout androidaps](https://user-images.githubusercontent.com/38214111/66511248-e1943c00-ead6-11e9-90db-58ac1b0505d2.png)

**Comment by MilosKozak** [comment]
it is not the priming bolus but stopped basal before
