### ISSUE TITLE
Objective questions: Hypo Temp-Target 

### ISSUE THREAD

**Issue by timocm** [MilosKozak/AndroidAPS#2110]
Objective questions: Hypo Temp-Target 
Why is it useful to set a hypo TT? (check all correct answers) 

remarks: 
if all correct answers are to be checked then all three options should be checked.

https://androidaps.readthedocs.io/en/latest/EN/Usage/temptarget.html:

"Realizing you will go low: Usually, the Loop should handle it, but sometimes you can see better in advance than the loop, so the loop can react faster when it targets a higher blood glucose value"

This means that hypo TT can be set to prevent BG from going low and to help recovering from a low BG and to prevent SMB enactment.

If the idea was to bring attention that a hypo TT would prevent the enactment of SMB , would it not be more appropriate to phrase the question and the instruction as: 

" Why is it useful to set a hypo TT? ( check the most appropriate answer) 
Prevent BG from going low 
To help recovering from a low BG 
to reduce the SMB enactment"

making the third answer shorter will not draw more attention to it and help people to think about the scenario.

**Comment by MilosKozak** [comment]
answers changed
