### ISSUE TITLE
[Medtronic] pump paused after pump low battery alarm

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#2111]
**pump paused after pump low battery alarm**
- Updated to RC3.
- AAPS was running normally.
- Got a pump battery low alarm.
- Changed pump battery.
- AAPS was running normally.
- Some time later the pump was paused in AAPS while the pump itself was running normally.

Possibly the battery low alarm was wrongly interpreted when reading the history.

**Comment by andyrozman** [comment]
Fixed: in branch https://github.com/andyrozman/AndroidAPS/tree/bug_2111_pump_stopped_when_not

**Comment by jroth-haj** [comment]
Todays Pump battery change without issue. :-)
