### ISSUE TITLE
Mmol representation in aaps not showing with simple profile without guide

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2112]
When xdrip with mmol units set is setup in aaps as gly data source (any profile type), the data are represented by default as Mg/dl. 
Only the guided setup allows to change this.
Maybe point for enhancement to read units type set in xdrip source.

Tested on v2.3 -fullrelease

**Comment by MilosKozak** [comment]
can you provide some screenshots what you did?

**Comment by pmisun** [comment]
V2.3

- used somehow setup without wizard.

Dne so 12. 10. 2019 21:18 uživatel Milos Kozak <notifications@github.com>
napsal:

**Comment by MilosKozak** [comment]
hmmm. that's not enough. i can test it if you'd able to provide steps to replicate this issue.
Open another issue if you find it out
