### ISSUE TITLE
[2.4 RC3] Extended bolus invisible for NS Clients

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2113]
Just tested the Extended bolus feature in Actions menu. It seems to work, but ut is only visible for the AAPS user. No info is sent to either Nightscout or NSClient. I believe this must be fixed before release.

Thank you!

**Comment by MilosKozak** [comment]
it works for me. and extended bolus will be removed anyway

**Comment by Mackwe** [comment]
![IMG-20191013-WA0000](https://user-images.githubusercontent.com/6748615/66712893-f1947000-eda3-11e9-989e-2ad3f8b8f964.jpg)
![Screenshot_20191013-010159_NSClient](https://user-images.githubusercontent.com/6748615/66712895-f8bb7e00-eda3-11e9-9514-b8473027200b.jpg)

**Comment by MilosKozak** [comment]
what pump driver?

**Comment by Mackwe** [comment]
Dana R v2. NS site is 0.12.3.

**Comment by nshtg** [comment]
> it works for me. and extended bolus will be removed anyway

May I ask why? I really like the feature and use it quite often for e.g. pizza.

**Comment by Mackwe** [comment]
This issue is absolete/superceeded by other solution. Closing.
