### ISSUE TITLE
[2.4 RC3] Enhancement: Duration for Change profile to

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2114]
Would be great if a duration could be definied for "change profile to" like for "profile percentage".

Use case:
For me (and others as I read) Fiasp has a significantly weaker effect with higher BG (> 180 / 200 mg/dl). So far I do a temporary profile switch to adapt the ISF to it - rest of profile stays the same, therefore no percentage switch but other profile.
With duration also for "change profile to" this would be easier to solve via automation - and would have no influence on autosense.
Thanks for considering.

**Comment by Philoul** [comment]
I think it's the same request than mine https://github.com/MilosKozak/AndroidAPS/issues/2068

The first step is already included in RC3 (thank's Milos, it's very useful ...), and I suggested to Milos to add all the "Change of profile" parameters (at least percentage and duration, I'm not sure for time-shift option but why not) in the same automation action...

**Comment by xJoe** [comment]
@Philoul you are right. Haven't seen that. I agree with you and therefore close this issue. Let's hope the devs will find time to include the additional parameters.
