### ISSUE TITLE
[2.4 RC3] Bug with Automation Rule checkbox

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2120]
I have a bug with automation rule checkbox

If I have up to 5 automation rules, I can enable or disable each rule with the little checkbox on the upper left side of each rule.

When I create a 6th rule, these checkbox doesn't work. Only the checkbox of the upper rule works but it enable or disable all my 6 automation rules together!

Now when I have 6 rules, If I delete one rule, it works again with the 5 remaining rules...

**Comment by Philoul** [comment]
![5RulesOK](https://user-images.githubusercontent.com/52934600/66916372-5b6a7f00-f01b-11e9-90b7-719e9f7255f2.png)
![6RulesKO](https://user-images.githubusercontent.com/52934600/66916373-5b6a7f00-f01b-11e9-90b5-f6e08201f5ac.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/6a7cb2ac7ba2a92d7a59b2474ec98d22d191fa3e
thanks!
