### ISSUE TITLE
[2.4 RC3] Automation UI overlap

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2126]
Hello,

A little picture is beter than a long message : 

![Automation UI suggestion](https://user-images.githubusercontent.com/52934600/67140409-6f4ff400-f25a-11e9-83a6-4fb40027b53f.jpg)

I suggest to split Automation screen in 2 different zones to avoid ovelap...
(with of course the + button to add new rules at the bottom of Rules zone)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/7cd66a6a43f39acf7af473f4e6048c3cfb7160dd
