### ISSUE TITLE
[All version] No strings for extendedStatuslight duration Units (d & h)

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2127]
Hello,

I can't find strings to translate the status light duration units (d and h are for english, we have other letters espacially for "day" in french...)

![extendedStatuslightUnits](https://user-images.githubusercontent.com/52934600/67141209-87774180-f261-11e9-8549-ff3e6dd2d66b.png)

**Comment by gregorybel** [comment]
hard coded:

https://github.com/MilosKozak/AndroidAPS/blob/cc298f81b80d37f4f81d79f5592fc808a3bb6857/app/src/main/java/info/nightscout/androidaps/db/CareportalEvent.java#L103

if you can do some coding, that's not so complicated, you need to create a string key in strings.xml, for example:

https://github.com/MilosKozak/AndroidAPS/blob/f4842b656a50fecf9168887eaa58ad031efd8ed3/app/src/main/res/values/strings.xml#L158

**Comment by Philoul** [comment]
Thank's,
Good exercise for me ...

**Comment by Philoul** [comment]
I tried to make my first Pull Request for this modification...
https://github.com/MilosKozak/AndroidAPS/pull/2179

Hope everything is ok... (It works on my build...)

**Comment by Philoul** [comment]
My second PR is merged : https://github.com/MilosKozak/AndroidAPS/pull/2185
I close this Issue...
Thank's
