### ISSUE TITLE
[2.4 RC4] Calculation elements hidden

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2131]
I don't like the fact that the elements that are the base for bolus calculation (BG, 15 min trend, COB, IOB) are hidden as of RC4. Looks like this is due to the calculator icon.
If it is not possible to bring back the old view I'd like to suggest that the setting of the "eye box" is saved so that I do not have to tick this box every time I use bolus calculator in order to see the calculation elements.
Thanks for considering my suggestion.

**Comment by jroth-haj** [comment]
I also prefer saving the last status of the "eye box"!

**Comment by 2flea** [comment]
+1

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/414695c5e3e8d94b30f180f6d8c9254610fdb077
