### ISSUE TITLE
AAPS 2.4 - RC3 crash after enabling short module names in UI

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2144]
Uncaught exception crashing app after enabling short module names. Reproduced twice.

V: 2.4 RC3
Phone: Samsung XCover 4s
Android version: 9 /OneUI: 1.1
ASKS v.2.1.0 r 190226
ADP v2.0 r 180525
SMR Oct-2019 R1
Sec Android: 1.10.2019

[Uncaught exception crashing app.txt](https://github.com/MilosKozak/AndroidAPS/files/3775335/Uncaught.exception.crashing.app.txt)

**Comment by MilosKozak** [comment]
does this appear in 2.5.x?
