### ISSUE TITLE
[2.5.0] Extended Bolus missing after update

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2147]
After updating to 2.5.0 I can no longer find "Extended Bolus" unter the action menu.
I used this option to account for pizza etc and eCarbs never worked for me as an alternative.

How do I get the option back? One option would be to use the insulin pump itself to add the extended bolus but then AndroidAPS won't know about it, right?

I'm using a DanaRS as pump.

**Comment by nshtg** [comment]
8d5fbeb66d3fdb3a02b4ad0c5a6e904acc1448de

is the commit in question that removed it

**Comment by triplem** [comment]
This option should not be used in a loop. Question is still what happens if you are not using Loop.

**Comment by nshtg** [comment]
@triplem Why shouldn't it? I mainly use the loop to prevent night time lows and to correct mild highs. When I eat pizza and bolus correctly without the extended bolus I will go high 6-7 hours after eating and it will stay like that for 6+ hours. When I use extended bolus I can counter that. If I wait till the high starts the loop won't be able to correct it. I understand why you shouldn't use it primarly but it should be an option if someone wants to use it. Like make an option to show or not.

**Comment by diascout** [comment]
I am missing it, too. It should be at least available for the DANA RS when the Loop is deactivated. However, in combination with AMA, I never had an issue. E-Carbs are only working well with SMB.

**Comment by nshtg** [comment]
If anyone want's the feature back:

https://github.com/nshtg/AndroidAPS

I reverted the commit in my master branch.

**Comment by fra-orolo** [comment]
+1 for fixing this, It should be possible to apply this from AAPS and it should be read correctly from pump history.
Our loop is still "Hybrid closed loop", If the user applies a bolus (in 1 minute or in 60mins) it must be seen as a given external disturbance. The algorithm could give hints (as for carb corrections) if the result seems to go out of range.
