### ISSUE TITLE
Warning Time 24h before Timechange is bad

### ISSUE THREAD

**Issue by SandraK82** [MilosKozak/AndroidAPS#2148]
Got woken up in the middle of the night, a day before the Timechange occured.
Something between 12 and 18 hours would be better I think.

https://github.com/MilosKozak/AndroidAPS/blob/1ab004a39ec26eab2ef55ec31039a46037a51894/app/src/main/java/info/nightscout/androidaps/plugins/constraints/dstHelper/DstHelperPlugin.java#L25

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/b2079aa31606b4bbb718bd2df45fb531bfadd5a7
