### ISSUE TITLE
Use as pump remote without CGM? 

### ISSUE THREAD

**Issue by kabachello** [MilosKozak/AndroidAPS#2150]
Is there a way to use this beautiful software as a remote control for the pump without xDrip or another CGM? I know, there is a special type of build for pump remote, but in my case it does not display anything (no basal rate, not IOB chart if I don't configure a BG-source. IMHO it would be really cool to just enter the Bg-value from the meter an still keep track of basal rates and IOB. The Calculator also still works - it's just the missing charts.

**Comment by MilosKozak** [comment]
it would mean to much changes in the code because too many functionalities rely on CGM
