### ISSUE TITLE
[2.5] Language switch not possible

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2152]
AAPS 2.5.0 - build: 1ab004a39-2019.10.27-07:45
Galaxy A3 (2017) with Android 8.0.0

Language switch in Preferences does not lead to effective language change.  Some strings are translated others not. See attached screenshot - hamburger menu English, 3-dots-menu German (language setting English).  Different Elements of the hamburger menu in English lead to German submenus.

Others also report similar problem:
https://www.facebook.com/groups/loopedDE/permalink/946647202379769/?comment_id=946861545691668&reply_comment_id=947190182325471
![Screenshot_20191028-183416_AndroidAPS](https://user-images.githubusercontent.com/13958493/67702665-6ece0080-f9b2-11e9-8648-d51058080add.jpg)

https://www.facebook.com/groups/loopedDE/permalink/946647202379769/?comment_id=946861545691668&reply_comment_id=947623042282185

**Comment by Philoul** [comment]
Same problem for me
I have to switch languages in both AAPS and in Smartphone Settings, and then I'll get full english in AAPS...
Only one switch is not enough...

**Comment by Snowli17** [comment]
Wenn es ne Lösung dafür gibt, hätte ich großes Interesse. Habe das gleiche Problem mit dem deutsch/Englisch.

**Comment by xJoe** [comment]
As Philoul said switching language in AAPS + Android settings workd also on my Galaxy A3 (2017) with Android 8.0.0.

**Comment by Philoul** [comment]
The workaround I propose is :
1) Switch smartphone language to English : 
SETTINGS / General management / Language and input / Language
=> I add a second language in my phone (Français (France) and English (United States)
Long press on one language to shift order (set English to the 1st place)

2) Change language in AAPS in Preferences

To go back to your language, Switch it in AAPS, and in phone settings shift your language to the first place

**Comment by quizzmaster** [comment]
It's still the same as it was in 2.0, see #1060.

**Comment by xJoe** [comment]
@quizzmaster Thanks. Never had it in previous versions and I do a lot of language switches for wiki screenshots. Will use workaround.

**Comment by winni67** [comment]
Same to me, Android 9.0 and Android 7.x, AAPS 2.5.1. Never had this problem in the past. I used the english language as default AAPS language. But perhaps I switched to the german language due to this bug since AAPS 2.0. Please switch back to the old behavior, because it was helpful for me as a supporter of AAPS. Thanks in advance and kind regards.

**Comment by andyrozman** [comment]
Same for me... I know it was fixed in some dialogs, but some string still look for System Lang setting instead of AAPS Lang setting (as they should)
