### ISSUE TITLE
Android APS crashing every 5 min loop

### ISSUE THREAD

**Issue by mjroodt** [MilosKozak/AndroidAPS#2154]
I believe the app is crashing very loop. Has only happended since upgrading 2.5. Have had no issues on previous devices . My setup is the following:

Phone : Unihertz Atom , Android 9 ( Battery saving settings have been disabled)
Build: 1ab004a39-2019.1   (2.5.0 ) fulldebug  NS version 0.12.4
Pump : Accu-Chek Insight 
CGM: Patched G6 2.4  Region 3 mmol

Last crash at 20:05

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3785596/AndroidAPS.log)

**Comment by AdrianLxM** [comment]
@mjroodt could you please build branch `adrian/NCRworkaround` and see if this solves your issue?

**Comment by mjroodt** [comment]
Thanks! this resolves the issue.

**Comment by Philoul** [comment]
This morning i had the same issue...
Yesterday, AAPS would restart about once an hour, but this morning it was every 2 to 3 minutes...

![Screenshot_20191031-121533](https://user-images.githubusercontent.com/52934600/67944153-1aa66480-fbdc-11e9-88b2-63a733d8268f.png)


My config is a little bit different:
Smartphone : Samsung Galaxy A3 2016
AAPS : 2.5.0 fullRelease
Pump : Accu-Chek Insight
CGM : FSL + Miaomiao 2 (from xDrip+)

I'll try the build branch adrian/NCRworkaround to see if it also solves my problem...

**Comment by ShaggydogUK** [comment]
I had this issue and resolved it be doing a clean install after a full un-install.

**Comment by Philoul** [comment]
I have built branch adrian/NCRworkaround and it solves my issue... No restart in past 10 hours.

**Comment by MilosKozak** [comment]
resolved in 2.5.1
