### ISSUE TITLE
[Medtronic] AAPS delivered the same bolus twice without me authorizing it. 

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2157]
Build version: 1ab004a39-2019.10.27-16:11

I entered an amount of 30g of carbs in the bolus calculator and authorized the bolus of 3.2 U. (17:47) 
approx. half an hour later i looked at the treatments screen and saw that AAPS delivered the same bolus right after the first one as a correction bolus without me interfering. I could prevent a hypo but bg was already dropping fastly :-/ 

![Screenshot_20191030-182252_AndroidAPS](https://user-images.githubusercontent.com/50026512/67882934-6e18a400-fb43-11e9-8cf1-a0967571b624.jpg)

Logs of this day: 
[AndroidAPS._2019-10-30_00-00-19_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3790377/AndroidAPS._2019-10-30_00-00-19_.0.zip)
[AndroidAPS._2019-10-30_00-00-19_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3790378/AndroidAPS._2019-10-30_00-00-19_.1.zip)
[AndroidAPS._2019-10-30_12-07-46_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3790379/AndroidAPS._2019-10-30_12-07-46_.0.zip)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by jotomo** [comment]
@RobHoff Provided logs only run till 16:00

**Comment by jotomo** [comment]
@RobHoff Can you provide logs covering the relevant time? Also, can you double check the boluses on the pump?

**Comment by RobHoff** [comment]
Sorry, can't provide the logs :-( . I unfortunately deleted them -.- 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 31.10.19, 21:17, Johannes Mockenhaupt <notifications@github.com> schrieb:
@RobHoff Can you provide logs covering the relevant time? Also, can you double check the boluses on the pump?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MilosKozak/AndroidAPS/issues/2157?email_source=notifications\u0026email_token=AL5VQEF5EIGSZH4WNUFYNPTQRM4PFA5CNFSM4JG5WKN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZDTGI#issuecomment-548551065",
"url": "https://github.com/MilosKozak/AndroidAPS/issues/2157?email_source=notifications\u0026email_token=AL5VQEF5EIGSZH4WNUFYNPTQRM4PFA5CNFSM4JG5WKN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECZDTGI#issuecomment-548551065",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JoernL** [comment]
What does your pump says about bolus information on 30.10. at 17:28? Does it really delivered it twice?

**Comment by andyrozman** [comment]
@RobHoff  Which Pump are you using?

**Comment by RobHoff** [comment]
Medtronic Paradigm 744
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 01.11.19, 11:59, Andy Rozman <notifications@github.com> schrieb:
@RobHoff  Which Pump are you using?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MilosKozak/AndroidAPS/issues/2157?email_source=notifications\u0026email_token=AL5VQECLI3RCOVH4HX7XCELQRQDYDA5CNFSM4JG5WKN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC2T5SI#issuecomment-548749001",
"url": "https://github.com/MilosKozak/AndroidAPS/issues/2157?email_source=notifications\u0026email_token=AL5VQECLI3RCOVH4HX7XCELQRQDYDA5CNFSM4JG5WKN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEC2T5SI#issuecomment-548749001",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MilosKozak** [comment]
did you check pump history?

**Comment by MilosKozak** [comment]
what pump?

**Comment by RobHoff** [comment]
I use the Minimed Paradigm 722 (not 744, sorry for the mistake)
Regarding the pump history: I checked it too late and the values of that day were already overwritten since the pump can only save 20 bolus-values :-/

**Comment by RobHoff** [comment]
@andyrozman I turned the feature on and will provide new logs as soon as I encounter the problem again. 
I don't think the bolus was just showed as treatment but not injected by the pump. I think it was delivered, because as soon as I realized it and saw my bg dropping slowly I corrected with the appropriate amount of carbs and my bg went about on a more or less normal course, not significantly dropping any further...

**Comment by andyrozman** [comment]
@RobHoff This problem was fixed, and will probably be released soon. If you want you can test it on my branch (double_bolus_debug_master) or on dev.
