### ISSUE TITLE
[dev-branch] [2.5] Version 2.5 app doesn't start anymore

### ISSUE THREAD

**Issue by CaptainBalou** [MilosKozak/AndroidAPS#2158]
Phone: Samsung S7 (SM-G930F)
Android: 8.0.0

I just built the current dev branch (dev from 30.10.2019) into a signed apk and updated my 2.4-dev-i (build: dd00230e6) with it.
The upgrade was working fine as usual. But after that the app does not start anymore. I just see the AndroidAPS logo.
To be able to loop again I installed version 2.4 again without deinstalling 2.5. Version 2.4 started again. But e.g. the bolus calculator looks different then before.

![Screenshot_20191031-003708_AndroidAPS](https://user-images.githubusercontent.com/17015872/67907021-c87f2800-fb76-11e9-8df7-fc79515380af.jpg)

I attached the log I had after the downgrade.

[AndroidAPS_LOG_1572476304153.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3791481/AndroidAPS_LOG_1572476304153.log.zip)

Can someone see in the log what's the issue was with 2.5? The other question would be what to do to get a clean 2.4 back to work. Delete the app, reinstall 2.4 and import the settings again?

**Comment by gregorybel** [comment]
I had same problem and after installing 2.5, I rebooted my phone then aaps started.

**Comment by CaptainBalou** [comment]
I tried that as well but without success.

**Comment by MilosKozak** [comment]
there is something wrong in compiled APK. start compiling from scratch

**Comment by gregorybel** [comment]
I don't think so....

**Comment by CaptainBalou** [comment]
I tried to pull all changes since I built it last time again yesterday. No changes. I re-built the apk but again no luck after installation @MilosKozak . 

Today I saw you devs put version 2.5.1 in place. I also saw changes in dev branch. So I pulled them, built the new apk and tried to install it as an update over my current running 2.4-dev-i. Again I had no luck.

Because I am bulding the apk the same way each time since years I don't think I am doing a mature fault here. But I am willing to learn if so. :-)

![Screenshot_20191102-001856_AndroidAPS](https://user-images.githubusercontent.com/17015872/68061760-bd5b0200-fd06-11e9-9e7e-0ee13e94a44c.jpg)

**Comment by CaptainBalou** [comment]
Again a comment to help someone who is reading this issue report some day.

@MilosKozak was right. It was concerning a problem during building the app. I assume I updated gradle some day or so. I erased the project in Android Studio and created it new. Then refused to update gradle in this project. I then built the app again and everything is fine.
