### ISSUE TITLE
SMS Bolus confirmation bug

### ISSUE THREAD

**Issue by maba76** [MilosKozak/AndroidAPS#2159]
Hi,
I am using version 2.5 and noticed a bug in the SMS confirmation. After sending an SMS to bolus 2.8u I received a confirmation message "Bolus failed". However, the "LastBolus" line confirmed that the 2.8u were actually delivered and the 2.8u also appeared in nightscout?! 

The issue does not occur every time I bolus SMS. Most of the time the SMS confirmation is correct. I do not know what triggers the wrong message?!

**Comment by MilosKozak** [comment]
you have to provide log files when this issue reappear

**Comment by MilosKozak** [comment]
what pump?

**Comment by maba76** [comment]
We use a Dana RS.  In any case,  the last bolus statement lines has the info of the current bolus,  not the previous one
![IMG_20191102_085634](https://user-images.githubusercontent.com/30212759/68060059-c079e080-fd4e-11e9-8f5a-86b032472a99.jpg)

**Comment by MilosKozak** [comment]
is the bug on the last screenshot?

**Comment by maba76** [comment]
There are two separate issues.
1) If you follow the SMS thread, you can see that the entry for 'LastBolus' is actually the current bolus.
2) The first message states 'Bolus failed' although the bolus was delivered as you can infer from the 'LastBolus' bug.

Issue 2 has occurred only once, I think after upgrading to APPS 2.5.1. Maybe it is directly linked to issue 1? 

Thanks for looking into this!

**Comment by MilosKozak** [comment]
did this appear more that once?
actualy this can happen when connection is interrupted during bolus

**Comment by maba76** [comment]
It only happened once with AAPS 2.5.1 but occurred several times with version 2.4.  It is possible that the connection got lost for whatever reason. Phone and pump are usually in close proximity. Nightscout displays the correct bolus information. In the past, I checked nightscout whenever I got the bolus failed SMS reply to confirm whether it was actually delivered.
