### ISSUE TITLE
Notes entered in bolus wizard not contained in JSON object

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#2164]
Notes entered inside the Bolus Wizard are not contained in the resulting JSON object which gets send to Nightscout. The `notes` field always is empty.

Notes entered within the Careportal or eCarbs are handled correctly.

Tested with v2.5 master.

**Comment by robinsondan87** [comment]
I have also noticed this too, same happens for Insulin, Carbs and Calculator.
