### ISSUE TITLE
How does Version-Checker work (I have to use a different phone)?

### ISSUE THREAD

**Issue by Adelaide72** [MilosKozak/AndroidAPS#2165]
Hi guys, 

sorry if that's the wrong place to ask for, but I'll try it anyways. ;)

Currently I'm using a business smartphone with AAPS on it. Because of security reasons my employer decided it's not allowed to use external apps anymore. But it is still allowed to use private numbers and receive calls from family members though.

I want to use my business phone for receiving calls and stuff and another phone for my loop. But I just want to use this phone for only looping, not for receiving calls or anything like that and because of financal issius I don't want to have another cell phone contract.

**My question is**: If the phone is offline all the time do I still get notifications when a new version is available and how many days are left for using the current version?

So does the Version-Checker has to have connection to the internet for recognizing that or is the version-checker static with that, that after a 60-90 days the loop backdrops to just LGS-mode or dies the checker check for new version and then stars counting the days that are left?

Thank you very much in advance.

Regards
Marc

**Comment by MilosKozak** [comment]
without connectivity there will be no warning. i'd recommend setup home wifi for example to receive notification and upload data to NS
