### ISSUE TITLE
Short pump disconnection cancel longer temp-zero running

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2166]
If I have a "long" temp-zero running (60, 90 or 120 min for exemple) and I disconnect my pump for a short time (15min for a shower)
=> If I set "Disconnect pump for 15 min", then my long temp-zero is replaced by a shorter one
When I reconnect my pump, AAPS set my current basal profile instead of previous temp-zero remaining time...

Not a big issue because after the next calculation a new temp-zero is set again if required

=> I suggest to not set a temp-zero when I disconnect pump if I allready have a temp-zero running with longer remaining time than pump disconnection time...

**Comment by MilosKozak** [comment]
this is how TBR works in pump. 
User action should always have higher priority than automated action so setting 15 TBR is correct

**Comment by Philoul** [comment]
I understand (and I'm agree) with that rule. but my action was not to set a 15min TBR. It was just to inform AAPS of 15min pump disconnection... (to avoid smb during that time for ex.).
