### ISSUE TITLE
Disabling NSClient stops network change updates for other plugins

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#2167]
Automation, Tidepool and NSClient plugins are interested in _EventNetworkChange_ events.
_NetworkChangeReceiver_ is registered in the manifest and broadcasts the event when called by the system. NSClient additionally registers the receiver on start and unregisters[1] it on plugin stop. Hence disabling NSClient causes the app to not receive any further network change events, breaking Tidepool and Automation functionality.
If Tidepool plugin starts using charging state changes to determine time to upload, the same will apply to _ChargingStateReceiver_.

[1] https://github.com/MilosKozak/AndroidAPS/blob/2a7a004afda174267f828350aa88839a5b8f2c56/app/src/main/java/info/nightscout/androidaps/plugins/general/nsclient/NsClientReceiverDelegate.java#L57

**Comment by MilosKozak** [comment]
Do you have an idea why it's there?

**Comment by MilosKozak** [comment]
resolved by https://github.com/MilosKozak/AndroidAPS/commit/9aa77122ba76ece6d27bf2634203194ed4b5e194
