### ISSUE TITLE
[2.5.0] AAPS alarm could not be acknowledged after xDrip alarm

### ISSUE THREAD

**Issue by fezulin** [MilosKozak/AndroidAPS#2168]
AndroidAPS 2.5.0
It happened just once, and the conditions will certainly not happen often: 
1.	I manually entered bolus in AAPS.
2.	Shortly after entering this, xDrip announced an alarm because of high values. Nearly at the same time, AAPS announced an alarm because pump (combo) could not be reached, and so the bolus could not been given. So two different alarm sound were played at the same time.
3.	I acknowledged the high-value alarm from xDrip.
4.	After I did this, the alarm sound form AAPS was still ringing, but the message informing me about the error wasn't displayed anymore. So I could not acknowledge the AAPS alarm. 
5.	Finally I had to reboot the mobile, to stop the alarm sound.
Remark: I am not absolutely sure, but I guess I changed from portrait format to landscape format and back again while this process.

**Comment by MilosKozak** [comment]
to be able resolve this i need step by step action to reproduce this isseu

**Comment by fezulin** [comment]
I can reproduce the part of having two alarm sounds at the same time. But regarding the conditions, this is correct and the expected behavior. But (now) I can acknowledge both alarms. 
So I can't reproduce the behavior I observed and described above.
Unless others are having the problem, I suggest this issue should be closed.
