### ISSUE TITLE
One entry with Carb button, 2 in Treatments, over insulin delivery...

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2171]
Yesterday at 20:54 I entered 20g Carb correction with Carb button, 

At 23:48, surprised to get down and all SMB given between 21:00 and 22:00, I checked treatment and I saw that I had 2 entries of 20g Carbs for the same hour (20:54). I first thought I made a mistake so I just delete the double entry in traitment.

While I was still low at 1:10, I entered 20g carb, and then a second 10g carb at 1:11 and I check traitments...

When I saw that once again I had a double entry in treatments (see below), I took a screenshot and I immediatly delete the second entry...

![Carb double entry_20191101-011139](https://user-images.githubusercontent.com/52934600/68013765-0e7adf80-fc8e-11e9-8367-1127f3f7b30c.png)

Then I wake up deep Low (and a little in panic) at about 05:00... I suspend the loop, take "unannouced" carb, take a screenshot of all the "halloween" night...

![Carbx2curve_20191101-050634](https://user-images.githubusercontent.com/52934600/68013755-091d9500-fc8e-11e9-898a-59b682c94b32.png)

It's the first time I have such a bad night... I'll send you all log by mail...

I do not know if it's the same issue as https://github.com/MilosKozak/AndroidAPS/issues/2157 but the result is similar (double entry in treatment and over insulin delivery...

**Comment by Alamo04** [comment]
Medtronic 754, RL 2.0, Samsung S7
Don't have that Bug in all the last Medtronic versions, but with Master 2.5.1 I have it.

Bug Confirmed. and back to 2.5.0
https://www.dropbox.com/s/iv1lfcivykvjbs5/Screenshot_20191102-105819_AndroidAPS.jpg?dl=0

Logs sended to Andy

**Comment by dlvoy** [comment]
Not sure if it is the same here, but i found similar issue with xDrip+ also syncing to Nightscout. When AAPS was configured to broadcast locally (NSClient -> Advanced ->Local broadcast ON) entries were duplicated in NS because both AAPS and xDrip+ submited same data at the same time. Comment says to not turn it on if you have another instance of AAPS or NSClient, but not mention xDrip+ :) After turning it off, items were no longer doubled at entry.

**Comment by Alamo04** [comment]
@dlvoy 
Thats not the same and not a program failure. This is a user failure.

It is normal, that both (XDrip and AAPS) sends the data to NS.
That's why you must deactivate that option in XDrip, if you are using AAPS.

**Comment by dlvoy** [comment]
> It is normal, that both (XDrip and AAPS) sends the data to NS.
> That's why you must deactivate that option in XDrip, if you are using AAPS.
Agreed! And it seems obvious when you think about how it works and connect the dots. But somehow it took me to Robo3T/MongoDB debugging of jsons to find out reason of duplicated entries :/ Maybe we can add that into manual, because it is not mentioned directly there.

**Comment by Philoul** [comment]
Although this should be better described in the documentation (I will try to suggest something in wiki), I think this should be solved in the code because an overdose of insulin affects security:
All actions have a timestamp, so 2 identical actions must have at least a few seconds gap in their timestamp to be taken into account. Which means that it should be easy, if the duplicate comes from a double upload to NS of a single action (from AAPS and from xdrip), to check if it's duplicate entry or not...

**Comment by Alamo04** [comment]
Fixed this failure with a fresh , clean installation of 2.5.1.
If I update my 2.5.0 to 2.5.1 without clean installation, the double entry error comes up.
