### ISSUE TITLE
Invalid  date, when  used automatic mark of sensor warm up from Dexcom 2.4 app

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#2176]
Invalid  date, when  used automatic mark of sensor warm up from Dexcom 2.4 app

AAPS 2.51 , Android 9 (Samsung A70)
replicated in other cases too.

![74914171_482960072562471_5266065504774127616_n](https://user-images.githubusercontent.com/16052233/68086816-e5a24800-fe4f-11e9-82ae-5699a58c137b.jpg)
![75233547_675539526308983_8193403222455484416_n](https://user-images.githubusercontent.com/16052233/68086817-e5a24800-fe4f-11e9-8b2f-2ac81d0dc17f.jpg)

**Comment by ShaggydogUK** [comment]
Same as issue #2140

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/2fe276d1013c795dcf50b4cd58d77f0871cd5229
