### ISSUE TITLE
[2.4 - 2.5.1] building not possible in 32 bit environment

### ISSUE THREAD

**Issue by chaosbiber** [MilosKozak/AndroidAPS#2177]
Since May 2019 there has been a change to gradle.properties setting
`org.gradle.jvmargs=-Xmx2g`
(shortly after 2.3 release)

resulting in the following error in a 32 bit environment:
```
ERROR: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/5.4.1/userguide/gradle_daemon.html
Process command line: C:\android-studio\jre\bin\java.exe -Xmx2g -Dfile.encoding=windows-1252 -Duser.country=DE -Duser.language=de -Duser.variant -cp C:\Users\xyz\.gradle\wrapper\dists\gradle-5.4.1-all\3221gyojl5jsh0helicew7rwx\gradle-5.4.1\lib\gradle-launcher-5.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 5.4.1
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 2097152KB object heap
```

There are obviously only few 32bit systems left but on facebook there are currently at least two people trying to upgrade to 2.5(.1) getting this error. I could recreate the error on a 32 bit Win 10 VM. With only 2GB RAM allocated all values above 1g (1536m, 1200m, 1100m) were too much, `-Xmx1g` **did** work. 

If there is no specific reason why 2gb was set I'd recommend setting it back to 1 for future updates.

**Comment by MilosKozak** [comment]
I don't remember the reason, but something made me to do it
32bit W10 is rare ..... i think we can delare it's not supported
I'll ask wiki team to mention it in troubleshooting

**Comment by xJoe** [comment]
@MilosKozak We had that issue again (see https://www.facebook.com/groups/AndroidAPSUsers/permalink/2579894375565297/). I do not know how much work it would be to change RAM demand but I hope it is little effort and might help some users with older machines who cannot afford to just buy a new one.
Thanks for reconsidering.
