### ISSUE TITLE
Feature Request: force restart app 

### ISSUE THREAD

**Issue by tepidjuice** [MilosKozak/AndroidAPS#2183]
When using a MDT pump if there is a bluetooth connection issue with the RL or a persistent pump connection issue then hard code an app restart. As exiting the app and restarting it seems to fix flaky BT connection issues I have.

**Comment by MilosKozak** [comment]
exit is in upper right menu

**Comment by tepidjuice** [comment]
It would be good to have this automated as errors can happen while I'm
asleep or otherwise not able to manually restart.

**Comment by m4nnihuber** [comment]
Would be really good Feature to restart App automatically when Connection Error occours
