### ISSUE TITLE
Incorrect basal rate on App compared to pump. Intermittent fault.

### ISSUE THREAD

**Issue by DrVoles** [MilosKozak/AndroidAPS#2188]
On 28th October 2019 at 16.12 GMT.
AndroidAPS 2.5
Accu chek insight pump.
Dexcom patched app 2.4 region 1 mmol/l
Pixel 3XL Android 10.

Was noted that glucose was dropping. APS advised 0% basal rate, which was shown on the pump as having been enacted - but on APSaon screen - was not showing correct basal. Could this be leading to inaccurate calculations?
Following discussions on Facebook - was advised to change setting: Always use basal absolute values, from on to off.
This appears to have rectified the issue - but means information from autotune is not valid.
Please see attached photos and log.
![IMG_20191028_161210](https://user-images.githubusercontent.com/42710627/68386894-ff47d600-0154-11ea-9b7c-b0398fdd2748.jpg)
![Screenshot_20191028-162211](https://user-images.githubusercontent.com/42710627/68387026-403fea80-0155-11ea-9dc5-6256546ebaae.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3819438/AndroidAPS.log)

Many thanks for your continued hard work!! X
Mark

**Comment by MilosKozak** [comment]
disable uploading as absolute value in NSClient

**Comment by DrVoles** [comment]
As I've said - I've already done this - but this means information from Autotune is not valid. Thus - the issue is not fixed..
