### ISSUE TITLE
2.5.1 No Connection to Nightscout

### ISSUE THREAD

**Issue by wastlkl** [MilosKozak/AndroidAPS#2191]
Build: eb98ca765-2019.11.05-2020:19, nsclientrelease 
In Night-scout-Client there ever is the comment:  NSCLIENT do connect
When i use the 2.3 Version with the same parameters, everything is fine, the connection is functioning.
I use our own Nightscout-Server (version 0.11.0-dev-20181116) on a Raspberry. Of course the server has no HTTPS, is this a problem? 
My son with the compilered full-release of 2.5/2.5.1 has the same connection problem, but i think we have a basic error.
The handys are the same, Samsung S8 with Android 9.
Many thanks for your support!

**Comment by akofort** [comment]
I've the same problem on my Xiaomi Mi 9 (Android 10). Version 2.3 works, 2.5 and 2.5.1 don't work.
Status (for ever): 'NSCLIENT do connect' (after restart: 'Connection destroy' and 'NSCLIENT do connect'...) 
I took network traces on the phone and on the nighscout server. I can't see any connection attempt.

**Comment by MilosKozak** [comment]
do you use https ?

**Comment by akofort** [comment]
Hi Milos,




I have 2 instances of NS running, one is plain http, the other is https. I was not able to use any of those.


If needed, I can try it again send you logs from both attemps ?




Many thanks for your work.




Cheers


Andreas




Holen Sie sich Outlook für Android







On Fri, Nov 15, 2019 at 11:20 AM +0100, "Milos Kozak" <notifications@github.com> wrote:












do you use https ?



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.






do you use https ?

**Comment by fra-orolo** [comment]
Would be great to see actual errors from the underlying io.socket library in the log. 
Currently this is lost (callbacks for errors are not registered?). 
I am facing problems with a new phone and operating-system, this is not related to 2.5 -- it does not work with https. But 3 other systems and the web browsers on the new phone can work nicely with my Nightscout.

**Comment by harrylah** [comment]
Please help. I have mongodb and nightscout running in docker containers on my Synology NAS. I have tested with docker images providing Nightscout versions 0.11.1 and 13.0.1 with no difference. I face the following situation:
- AAPS-2.3: The NS client connects via http, everything works fine.
- AAPS-2.3: Securing that with a self signed certificate and addressing it via a reverse proxy providing https, the connection fails. However, if I press the URL in the Nightscout Client tab, I will see my Nightscout up and running via https in a browser window.
- AAPS-2.5.1: NS Client does not connect via http
- AAPS-2.5.1 NS Client does not connect via https

> Would be great to see actual errors from the underlying io.socket library in the log.
Is there anything I can do to provide something?

**Comment by akofort** [comment]
Did anyone with this problem manage to get NSClient working with 2.5.1 and https ? I'm still having this problem and it's really annoying.
My setup (docker container on qnap)/problem  is similar to harrylah's. 
Today I tried with a new NS instance (ver 13.0.1) on 10be.de, this also didn't help. So I expect no problem with my QNAP+Docker setup (self-signed certificate).
Milos, is it possible to make http (optional, maybe with a big warning). I'm only syncing when I'm at home, so there's need for https in my case. Sounds that harrylah is doing the same...
Thanks.

**Comment by harrylah** [comment]
Right, that's exactly what I do. When I'm out, I tunnel in via VPN so I also do not need https.
I managed to connect to Nightscout via https with 2.5.1, but only to my Heroku site. No luck on my Synology NAS.

**Comment by MilosKozak** [comment]
sorry we cannot help with custom configurations
https is forced by OkHttp library and we don't plan to change it
