### ISSUE TITLE
AAPS crashing every loop

### ISSUE THREAD

**Issue by lydiaengler** [MilosKozak/AndroidAPS#2196]
This seems to be the same as #2154 

The issue started at 2 AM in the middle of the night, with no changes to anything done (we were asleep!).  Was running 2.5.0 on a Xiaomi Redmi Go at the time, but this morning have upgraded to 2.5.1.  that didn't help

Have tried uninstalling and reinstalling AAPS, as well as clearing the AAPS cache.

I note in the comments to #2154 there was a suggestion to try another branch, but I thought that fix was in 2.5.1

[AndroidAPS_LOG_1573556102284.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3835886/AndroidAPS_LOG_1573556102284.log.zip)

**Comment by lydiaengler** [comment]
BTW I am not sure this is actually every loop  seems morre frequent.

**Comment by jotomo** [comment]
#2154 is a different issue.
Like Milos said, the problem is an invalid Temp Target received from NS
(created around _Nov 11 16:05:16 CET_). However that is NOT crashing the app.
The logs provided only begin at 10:44 and don't go till the night. Please provide the log files showing the night (each log line starts with the time of the day).

**Comment by lydiaengler** [comment]
Thanks - not sure how I find more log files - the zip above is what I got when I go into maintenance, send logs by email, then I export them to my cloud drive.  Where would I find more logs?

**Comment by jotomo** [comment]
See https://androidaps.readthedocs.io/en/latest/EN/Usage/Accessing-logfiles.html

**Comment by lydiaengler** [comment]
Thank you. I have put all available logs into: https://1drv.ms/u/s!AlNSgvv2w8Q7hscTLFIXeSobJgnvVw?e=maB8rb

Unfortunately I have to go out now (to a funeral) so will have to resume investigations later.

If this turned out to be something to do with fauly NS data, can you advise how to reset that? (Preferably without losing all the data!)  Thanks

**Comment by jotomo** [comment]
> If this turned out to be something to do with fauly NS data, can you advise how to reset that? (Preferably without losing all the data!) Thanks

In NS, under treatments find the temp basal with the mentioned timestamp and remove it.

Hm, logs still don't show the relevant time. Try starting the app again and let it crash again, then copy _AndroidAPS.log_ over (which contains the most recent entries) and attach here.

**Comment by lydiaengler** [comment]
Thanks very much for trying to help on this.

In the end I set up a brand new NS site, and pointed AAPS at that.  It was still crashing so that really eliminated NS, so I just set everything up on another (more powerful) phone - Xiaomi Mi A2 lite - and all is working nicely.  Have no idea why the previous phone just stopped working at a specific time when it had been OK before.  Wasn't storage as was only using 53%.  Maybe something RAM related.  Don't know and I don't think it's profitable to delve further unless the developers feel otherwise.

**Comment by lydiaengler** [comment]
Re-opening this as it's just recurred.  This time, however, someone has solved it for me on FB: I cleared data cache for Dexcom patched app and re-paired it to the transmitter, the old session was picked up after about 5 mins and now AAPS running fine without restarts.  The restarts were occuring whenever Dexcom app sent sent to AAPS.  Although fixed for me, this seems to be an outstanding bug. It's obviously little known given nobody pointed it out before when it first happened for me when I posted above and onto FB (and the reinstallation onto a new phone fixed it because obviously it started with a clean Dexcom data cache).

Using AAPS 2.5.1 and Dexcom patched app 2.4 for region 1

**Comment by lydiaengler** [comment]
I am not sure why this has been closed as the issue doesn't seem to have been fixed - it happened to us again last night.  Using AAPS 2.5.1 and patched Dexcom app 2.4 region 1.

AAPS just started crashing every loop.  Reinstalling patched Dexcom app solves the issue (for several weeks apparently, then it recurs).

**Comment by lydiaengler** [comment]
Just to say that this issue is still happening on 2.6.  Everthing runs fine for, say 2-3 weeks, then AAPS crashes and restarts whenever a BG comes in.

Uninstalling the Dexcop app 2.4 region 1 and reinstalling it solves the issue - for a fewe weeks, after which it comes back.
