### ISSUE TITLE
automation enable/disable - feature request

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2200]
It would be nice, if it was possible to enable/disable automation settings. At the moment you have to delete the setting, if you don´t want it do act for a certain time.

**Comment by MilosKozak** [comment]
there is a checkbox for enabling/disabling rule

**Comment by CaroGo** [comment]
Could you please give me a hint where to find it? I just see a bin to delete...?!

**Comment by CaroGo** [comment]
Sorry 🙉 got it! Sorry, sorry, sorry! Shame on me!
