### ISSUE TITLE
Glimp listed as not supported in 2.5.x

### ISSUE THREAD

**Issue by rob-andy** [MilosKozak/AndroidAPS#2205]
Is there a reason why glimp is listed as not supported in 2.5.x?  Was a decision made to drop support? or what needs to be done to allow it to work with the new 2.5 series

**Comment by MilosKozak** [comment]
All apps have to be updated to support SDK28 broadcasts. We don't have confirmation from Glimp it's done

**Comment by MilosKozak** [comment]
Glimp 4.15.57 and newer is supported
