### ISSUE TITLE
[2.6-dev] Battery drainage after midnight

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2207]
I monitored my phone battery last two nights - both times in flight mode all night. 

First night it was fully charged. Battery loss over 11h was 15% battery. This is fine. 

Last night though battery was drained from 45% to 0% this morning, phone was dead. 
I started at 2200 and till 0000 battery drain was 3% in 2h. After midnight I got 12/13% by 2h. This morning at 0720 it was dead. 

Please find log files attached. 

**What happens at midnight that could cause such behaviour?** 
I am using Pocophone F1 in flight mode with enabled BT overnight.

16.11.2019 / 17.11.2019
2145 100% - 09:00 85%

17.11.2019 / 18.11.2019
2200 45% - 0720 0% dead

Details of 2nd night:
2200 45% --> 0000 42% -- looks ok
0000 42% --> 0200 30% -- massive battery use
0200 30% --> 0400 17% -- massive battery use
0400 17% --> 0600 3% -- massive battery use
0600 3% --> 0720 0% - dead phone -- massive battery use

![image](https://user-images.githubusercontent.com/38214111/69052682-eb7b5a00-0a07-11ea-800f-19c0df4a7474.png)

[2nd_night_AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3858588/2nd_night_AndroidAPS.log)
[2nd_night_AndroidAPS._2019-11-17_14-51-31_.log](https://github.com/MilosKozak/AndroidAPS/files/3858589/2nd_night_AndroidAPS._2019-11-17_14-51-31_.log)
[1st_night_AndroidAPS._2019-11-17_00-00-27_.log](https://github.com/MilosKozak/AndroidAPS/files/3858590/1st_night_AndroidAPS._2019-11-17_00-00-27_.log)
[1st_night_AndroidAPS._2019-11-16_15-38-15_.log](https://github.com/MilosKozak/AndroidAPS/files/3858592/1st_night_AndroidAPS._2019-11-16_15-38-15_.log)

Following logs were enabled:
![image](https://user-images.githubusercontent.com/38214111/69052654-d9012080-0a07-11ea-8fa0-59dee555376f.png)

**Comment by MasterPlexus** [comment]
Please take care, that not WhatsApp causes the issue. There was issues announced that WhatsApp drains massively due to several updates (also if it is not on the top of drain apps list). Could be that this will be better the next days with next updates...

**Comment by 2flea** [comment]
@MasterPlexus you are right. I saw the info about WhatsApp as well. It might be the combination of WhatsApp and passive GPS in AAPS in flight mode. I didn't activate flight mode last two nights and consumption was ok. I will further monitor this.
