### ISSUE TITLE
[2.5.1] Nightscout log traffic strongly increased

### ISSUE THREAD

**Issue by opal06** [MilosKozak/AndroidAPS#2208]
Hello,
after installing v2.5.1, I noticed heavily increased traffic on my Nightscout server, more precisely of the Papertrail logs. Previously to the update, average daily traffic was between 2.5 and 3 MB, which is totally fine. After installing the update, traffic hit more than 10 MB in two days in a row (see screenshot below). That is the free traffic limit for Papertrail logs on heroku, logging stops thereafter until the next day. My projected traffic according to Papertrail would be arund 80 MB a day. As a result, BG is logged, but no carbs, treatment  or basal insulin information are saved and displayed in the reports on Nightscout. This could be very problematic, as it reduces accountability of the system and the possibility to evaluate both the medical treatment as well as the functioning of the system. There is also an inherent risk of data loss if people are not aware that their logging data is capped and do not save their data elsewhere.

![Bildschirmfoto vom 2019-11-19 10-16-42](https://user-images.githubusercontent.com/41026414/69133796-c2fe6900-0ab6-11ea-91e2-38f1816926aa.png)

**Comment by dansuk** [comment]
I have the same issue here. I noticed that my autotune results were completely erratic and I just checked my nightscout site and confirmed that only BG is being logged, no carbs/treatments etc. I had received emails regarding Papertrail log limit being exceeded and therefore logging had been stopped. I had not realised this was the cause of the autotune recomendations being completely wrong but now know why.

**Comment by dansuk** [comment]
The email I received today:

"Your Papertrail service for "" has reached its log data transfer limit of 10 MB for today.
Based on recent volume, your projected total daily log data transfer is 107 MB."

**Comment by dansuk** [comment]
I'm also noting in my PaperTrail logs entries which seem to be historic being recorded at a much later time:
![image](https://user-images.githubusercontent.com/33720345/69144164-981a1200-0ac2-11ea-996e-0f3fd1c482cc.png)

**Comment by MilosKozak** [comment]
1) remove papertrail. it's not needed
2) select logging level in maintenance

**Comment by dansuk** [comment]
Thanks @MilosKozak, going to adjust the logging level that's very helpful.

I am not sure why treatments are not going to Nightscout though if Papertrail is not needed. I had some SMBs logged yesterday in Nightscout but when I enter carbs and insulin using the treatment button or calculator, they do not appear in Nightscout.

**Comment by dansuk** [comment]
Perhaps it's nightscout related

**Comment by dansuk** [comment]
Ok for me I seem to have solved the issue.

@opal06 can you confirm if you have a queue of items in the NSCLIENT tab of AAPS? For me I had an ever growing queue of DBADD devicestatus requests. I deleted the devicestatus collection from my MongoDB in Heroku and my issue with treatments not showing in Nightscout was solved.

**Comment by opal06** [comment]
Yes, there is a long list of DBADD elements. I deleted device status from MongoDB too, updated Nightscout and deleted papertrail. Hopefully, functionallity will be restored.
Will report.
