### ISSUE TITLE
Dexcom G6 sensor replacement logged twice in CP

### ISSUE THREAD

**Issue by sailor-911** [MilosKozak/AndroidAPS#2209]
[AndroidAPS._2019-11-13_00-00-00_.14.zip](https://github.com/MilosKozak/AndroidAPS/files/3863182/AndroidAPS._2019-11-13_00-00-00_.14.zip)
**Description:** G6 sensor replacement (triggered by modified Dexcom G6 app) is displayed twice in AAPSs care portal (CP)  (see screenshot attached): Lower item is correct, most upper item is wrong and should not be logged / created / displayed.

**Affected AAPS-version:** 2.4, 2.5.x (latest)
**Linked data source:** modified Dexcom app, Ver. 1.5.1.5, Software-ID SW11587
**Mob-OS:** Android 9
Log-file attached.

![Screenshot_20191113-091627](https://user-images.githubusercontent.com/55198446/69135973-538a7880-0aba-11ea-8010-ba117112063a.png)

**Comment by ShaggydogUK** [comment]
Isn't this the same as #2140 and #2176?

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/2fe276d1013c795dcf50b4cd58d77f0871cd5229
