### ISSUE TITLE
Feature request: Possibility to sort automated tasks

### ISSUE THREAD

**Issue by sailor-911** [MilosKozak/AndroidAPS#2211]
First: Automated task tool is a great feature introduced with 2.5. 

I would suggest following to simplify usage:
A kind of sort functionality that allows i. e. to bring more “important” tasks more to the top (or tasks that need better higher visibility) that a user doesn’t need to scroll all the time. Currently all tasks are in the list as they are created: oldest on the top, latest on the bottom. This may confuse - in my special situation a have a lot of different tasks that I have enabled all over whole day.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/a66b3f70903392512c6ab96bef06d1e6a8c22c98
