### ISSUE TITLE
Feature Request: Allow change of IC during bolus calculation

### ISSUE THREAD

**Issue by Cagier** [MilosKozak/AndroidAPS#2223]
A feature that we really miss from our last pump is the ability to change the Insulin-to-Carb ration "on the fly" so if you want to increase or decrease it during a carb bolus then you can use an alternative rate without permanently changing the profile.  For example, there may some foods, activities or other situations where you want to reduce or increase the carb ratio.  I know you can make a separate correction to the total bolus but this would be more accurate and the details would also be recorded in the history (and possibly used in subsequent IOB calculations).

The number is already on the screen so if you could do something like a long press on the IC when on the calculator screen then that would be pretty cool.

A similar option for the ISF on that screen might also be handy for doing corrections based on the same logic.

**Comment by MilosKozak** [comment]
Sorry but this would make wizard too complicated. If you don't want use corrections you can prepare more profiles and then just use it in calculation

**Comment by Cagier** [comment]
I understand why you closed this but the value by which we may change the IC may vary on the food, activity, weekday/weekend and will not be a fixed amount that can be entered in another profile.  This was a feature in the EZCARB option on the Vibe which we really miss.  I am trying to move my wife from another App to AndroidAPS and this is a bit of a deal breaker so just wanted to plead my case!

I think this could be a very subtle change on the Bolus Wizard which would not affect it visually.  So I am not suggesting an extra NumberPicker or anything that would complicate the screen appearance.  However, by changing the "treatments_wizard_cob" TextView to a Button, it could keep the same appearance but a long press would pop up a simple dialog box for the new IC value.  I'm not even sure if it needs to be changed to a button in order to allow some sort of onClick event.  Anyway, this would give us a lot more flexibility and we could also use this as an Open Loop calculator with the Ypsopump during the daytime if we wanted.

I've been playing in Android Studio but I'm not proficient enough in java to make this change myself yet.  If you don't want this as an optional facility for everyone, maybe someone could even just point me in the right direction on how to change the IC value for my own customised version?

I can see that BolusWizard.kt uses profile.ic to get the ic used for calculating insulinFromCarbs.  I think I would need to include something in boluscalcJSON in order to pick up the modified value.  Apologies, I know this isn't StackOverflow!  Thanks for any assistance as this will probably take me weeks to do by myself.
