### ISSUE TITLE
Xdrip not showing AAPS data

### ISSUE THREAD

**Issue by cramis1** [MilosKozak/AndroidAPS#2224]
I cant seem to get any of the AndroidAPS data to show up in Xdrip+. Such as showing treatments, insulin-on-board, and carbs-on-board. I have enabled local broadcast on AAPS and on Xdrip I have selected Accept Treatments. As I would also like the "aaps" object to appear in the local xDrip web request.

**Comment by MilosKozak** [comment]
ask on FB page. Providing screenshots with settings will help
