### ISSUE TITLE
Nightscout "Temporary Target Cancel" treatment is ignored

### ISSUE THREAD

**Issue by tynbendad** [MilosKozak/AndroidAPS#2229]
Repro:
Add a Nightscout treatment of Event Type temporary target (e.g., eating soon 80/80 @60m)
See it shows up in AAPS overview target box
Add a Nightscout treatment of Event Type=temporary target cancel
See it does not show up in AAPS overview target box
(Optional: delete the temporary target treatment in Nightscout report, you'll see AAPS remove the target).

AAPS version 2.5.1

**Comment by tynbendad** [comment]
it looks like it could be that aaps doesn't like that the "temporary target cancel" treatment is just a blank temporary target treatment?

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/517b9a9fa7a64e0f2270271ff2e41860d678a392
