### ISSUE TITLE
Enhancement : Add Strings for Watch translation (settings and units of watchfaces)

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2233]
If it's possible it would be nice to also translate wear watch (mainly settings and dialogs)
=> I can help with Strings creation and code or UI modification but I need help for the beginning...
=> Setting mechanism in code to allow "translations" in wear watch development (+ CROWDIN interface) and one string as example to start working...

**Comment by MilosKozak** [comment]
yeah, if you extract all strings to resources, I can configure crowdin for translations

**Comment by dlvoy** [comment]
In recent dev there is helper method for translations:  `aaps.gs(R.strings.key)` - and second for parametrized strings

**Comment by Philoul** [comment]
I propose to close this Issue (even if we can find some improvement in translations now it works...)
