### ISSUE TITLE
[2.6 dev] Setup Wizard runs repeatedly on launch

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#2236]
I updated from 2.51 Release to 2.6 Dev 2019.12.02-10:11 and each time AAPS launches, the Setup Wizard runs (despite the existence of settings):

1 Launch AAPS --> Setup Wizard appears (despite existing settings)!
2 From within the setup wizard, 'import settings' --> AAPS closes to apply the settings and reruns, but the Setup Wizard appears again! 
3 Press the 'Exit' button in the Setup Wizard --> most times it fails to respond (I don't think it's a performance problem since the 'Next'/'Previous' buttons do respond consistently)!
On occasions where it does respond, --> AAPS overview screen appears with some warnings (e.g. Max Basal incorrect).
4 Click 'OK" on the warning --> Setup wizard relaunches a second time!
5 Exit the wizard --> This time it doesn't relaunch
6 Close AAPS and restart it --> the problem reccurs!

[AndroidAPS_LOG_1575305170792.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3912269/AndroidAPS_LOG_1575305170792.log.zip)

**Comment by MilosKozak** [comment]
the wizard stop appering once you finish it to the end
if you import settings you probably imported situation where wizard was not finished to the end or there is new setting thus wizards was started again.
Resolution finish wizard and export settings for next time

**Comment by rustymonkey** [comment]
Completing the wizard solved the problem, but this was a setup that had been working previously prior to the upgrade to the latest dev version (i.e. the Wizard had previously been completed and I didn't notice any newly introduced items to complete in the wizard).

 @2flea mentioned at https://gitter.im/MilosKozak/AndroidAPS?at=5de80c6646397c721c885136 that it may be due to a 'unit' change ?

**Comment by 2flea** [comment]
I did not finish the wizard, I exited it and
switched once from mg/dl to mmol and back. Wizard did not appear since.

**Comment by MilosKozak** [comment]
yeah if you didn't specify units wizard appears (because it's part of wizard now)
