### ISSUE TITLE
Feature request: new setting to disable/enable automatic date/time trimming on pump

### ISSUE THREAD

**Issue by sailor-911** [MilosKozak/AndroidAPS#2245]
Within the pump preferences a new feature could be implemented to enable / disable the automatic date / time update from AAPS towards the pumps date / time settings. 
If you are on one location / time zone it’s a very welcome feature to have all the time an accurate time value inside the pump. But if you travel across time zones it could be helpful to disconnect for a certain time the automatic time update feature to give your body the chance to accommodate in the new time zone. It could be implemented ie. in first step with a switch (on/off) in the according pump settings dialog of AAPS. Insight pumps do have a time update feature, for Dana pumps I don’t know yet. Must be checked for each supported pump type in AAPS.

**Comment by MilosKozak** [comment]
time synchronization is necessary for reading history. if you want to fake it, do it on phone side
