### ISSUE TITLE
Wrong Bolus calculation in QuickWizard

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#2254]
Hello,

I have set „Deliver this part of bolus wizard result [%]“ to 80% of the calculated value. This value of 80% isn‘t considered by the QuickWizard. The QuickWizard uses 100% of the calculated bolus value.

![C4F63AC8-4D45-4367-9D8B-D8DB868337BA](https://user-images.githubusercontent.com/6819067/70389350-aae77e80-19be-11ea-9bf6-4ec2248e9e10.png)
![EA224698-6F29-4647-BEF8-3FC90E6C3AC2](https://user-images.githubusercontent.com/6819067/70389351-ab801500-19be-11ea-8343-5e72899f80f0.png)

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/b69af9579109c01a9291b0783e7c060d2a3e42e0
