### ISSUE TITLE
[2.6 RC1] Note in bolus wizzard not logged

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2255]
As in 2.5.1 notes entered in bolus wizzard are not logged  and therefore not visible in Treatments / Careportal.
Workaround to go to Careportal and enter note separately works but is inconvenient.
Thanks for bringing the pre-2.5 behaviour back.

**Comment by MilosKozak** [comment]
note is visible in wizardr record

**Comment by xJoe** [comment]
https://en.wiktionary.org/wiki/PEBCAK :-(
