### ISSUE TITLE
[2.6 RC1] Automation profile switch problems

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2260]
Profile switch through Automation does not work when NS profile is used. Same rule works fine with local profile.

**Comment by PoweRGbg** [comment]
Give an example of profile names or provide logs please. For me it works.

**Comment by xJoe** [comment]
Name of running profile: Aktuell
Name of profile to switch to: Aggressive
![ProfileSwitchViaAutomationNotWorking](https://user-images.githubusercontent.com/13958493/70791770-04252880-1d98-11ea-90bb-5d19444d6137.jpg)

**Comment by PoweRGbg** [comment]
Right now I'm dealing with a problem closer to this and it is down to the profile name itself.  Try deleting the action and adding it again when you have NSProfile enabled. Select the Aggresive profile after that.

**Comment by MilosKozak** [comment]
it works for me .... your NS profiles have to be messed up if i see your other issues

**Comment by MilosKozak** [comment]
should be fixed in dev
