### ISSUE TITLE
[2.5.1] MDT pump permanently suspended due to bad history reading

### ISSUE THREAD

**Issue by skuzzer** [MilosKozak/AndroidAPS#2264]
Overview screen shows "pump suspended" and there is no way to unsuspend the pump. Pump history shows the most recent entry as being a suspend event from 29/00/2030.
Pump model is 712.

AndroidAPS.log shows these entries
```
21:53:48.081 [Thread-21] E/PUMPCOMM: [DateTimeUtil.toLocalDateTime():52]: Error creating LocalDateTime from values [atechDateTime=28, year=2030, month=0, day=29, hour=30, minute=24, second=28]. Exception: Value 30 for hourOfDay must be in the range [0,23]
21:53:48.082 [Thread-21] E/PUMP: [MedtronicHistoryData.finalizeNewHistoryRecords():260]: Problem decoding date from last record: {}PumpHistoryEntry [type=Suspend              [30 , 0x1E], DT: 29.00.2030 30:24:28, length=2,5,0(7), data=No data]
21:53:48.082 [Thread-21] E/PUMP: [MedtronicHistoryData.finalizeNewHistoryRecords():286]: Since we couldn't determine date, we don't clean full history. This is just workaround.
```

I've attached this log and the log zip.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3945659/AndroidAPS.log)
[AndroidAPS._2019-12-01_21-51-38_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3945660/AndroidAPS._2019-12-01_21-51-38_.0.zip)

**Comment by andyrozman** [comment]
This entry is not a problem. Problem is that your last history entry is PumpSuspend, 21 years in the future... 

But looking at your history there is a lot of items that can't be decoded, which produced this error... I have to take closer look at decoding of your history... 

Are you using CGMS at same time as Pump on same device?

**Comment by andyrozman** [comment]
Ok. So far I think there is one history item I can't decode, which broke reading of history... I am looking into fixing this...

**Comment by skuzzer** [comment]
CGM being used is dexcom g5, using patched app.

If the entry was that far in the future I'd understand it, but the month `00` threw me, I was thinking perhaps if a date couldn't be created from the entry the entry should be scrapped rather than kept with best effort values

**Comment by andyrozman** [comment]
So I did a fix of this, you can test it out... If we are fast enough with this, it might be added to next release... SO here it is: https://github.com/andyrozman/AndroidAPS/tree/bug_2264_historyproblem_512_2e

**Comment by skuzzer** [comment]
I'm not see a pump suspended event in month 0 year 2030 anymore so this is looking good 👍

**Comment by andyrozman** [comment]
PR was done and its part of dev now. And it will be part of 2.6.0 release
