### ISSUE TITLE
[2.6 RC1] Settings mmol isn't transferred

### ISSUE THREAD

**Issue by lutzlukesch** [MilosKozak/AndroidAPS#2265]
If the App is set in mmol with Master2.51, AAPS changes after update to mmg/dl. The setting mmol has to be reentered.
Could also just be a update info for the users with  mmol, that the setting has to be reentered.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/5b345c5ce355f43112cbb058436a777b4fa95293
