### ISSUE TITLE
[2.6 RC1] App crashes after update when importing profile settings

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2276]
Yesterday (12.12.19) at about 6 p.m. I updated from 2.5.1 to Version 2.6 RC1. The app started with the configuration manager and when I tried to import my local profile settings (which I exported beforehand), the app crashed. This happened multiple times, so I had to downgrade it to work properly again. 

Logs were sent via Email.

**Comment by MilosKozak** [comment]
can you provide step by step what you did if you can reproduce this issue

**Comment by RobHoff** [comment]
I think it's working now. Apparently the issue was with android studio showing 5 errors while building the app.
