### ISSUE TITLE
AAPS loosing CP entries

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2277]
I see AAPS "loosing" CP entries for reservoir & canula change. Maybe also others but those are easy to identify by wrong status lights. Can be reloaded from NS but I am surprised as I entered those through CP tab in AAPS. Happend in the past (i.e. 2.5.1) as well as with 2.6.0 RC1.

Screenshot left side is before update from NS.

![CPlostData](https://user-images.githubusercontent.com/13958493/70791908-60884800-1d98-11ea-816e-37304be9a9b5.png)

**Comment by MilosKozak** [comment]
provide log files if this happen
i didn't meet this issue
