### ISSUE TITLE
Medtronic 722 double bolus recorded but not delivered

### ISSUE THREAD

**Issue by JustinSouthcombe** [MilosKozak/AndroidAPS#2280]
Double bolus today.
Doesn't exist in pump so only a bug in aaps.
Double bolus was not delivered.

Log file, version and screen shot of double bolus in treatment page are below....

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3963800/AndroidAPS.log)
![Screenshot_20191214-114135](https://user-images.githubusercontent.com/56894482/70848395-b9bfac80-1e68-11ea-8849-81965ca30da8.png)
![Screenshot_20191214-094330](https://user-images.githubusercontent.com/56894482/70848402-c6440500-1e68-11ea-948d-cb33dac94ad4.png)

**Comment by JustinSouthcombe** [comment]
The Medtronic double bolus debug mode was activated at the time.

**Comment by RobHoff** [comment]
Same issue for me with same pump and same build version yesterday at around 11:18 a.m.. Unfortunately don't have a screenshot.

Logs for the day: 
[AndroidAPS._2019-12-14_00-00-26_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3964663/AndroidAPS._2019-12-14_00-00-26_.0.zip)
[AndroidAPS._2019-12-14_00-00-26_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3964664/AndroidAPS._2019-12-14_00-00-26_.1.zip)
[AndroidAPS._2019-12-14_00-00-26_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3964665/AndroidAPS._2019-12-14_00-00-26_.2.zip)
[AndroidAPS._2019-12-14_00-00-26_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/3964666/AndroidAPS._2019-12-14_00-00-26_.3.zip)
[AndroidAPS._2019-12-14_00-00-26_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/3964667/AndroidAPS._2019-12-14_00-00-26_.4.zip)
[AndroidAPS._2019-12-14_00-00-26_.5.zip](https://github.com/MilosKozak/AndroidAPS/files/3964668/AndroidAPS._2019-12-14_00-00-26_.5.zip)

**Comment by andyrozman** [comment]
Double bolus problem was fixed, and will be released soon. (see 2.6.0 RC1). After that please retest this, but it should be fixed.

**Comment by JustinSouthcombe** [comment]
Not really sure what I should do now. Is there a fix I need to add or just wait until 2.6.0 is ready? You might need to explain step by step. Sorry.

**Comment by MilosKozak** [comment]
if you are not experienced user just wait for new release
