### ISSUE TITLE
Stop bolus button in bolus progress dialog freezes UI

### ISSUE THREAD

**Issue by bartsopers** [MilosKozak/AndroidAPS#2283]
During testing, I noticed that in the BolusProgressDialog.onClick(View view) method, after setting the Stop bolus button to invisible, we call
`ConfigBuilderPlugin.getPlugin().getCommandQueue().cancelAllBoluses();`
In that method, we then directly call the PumpInterface.stopBolusDelivering() method (this is where it bypasses the queue). This causes the thread to block until the stopBolusDeliveringMethod() returns. So the onClick returns after the command is finished, which causes the UI not to update until then, so the Stop Bolus button does not disappear and it feels like the app freezes. For Omnipod this can take 2-3 seconds so it's not really user friendly and sometimes also causes Android to show a warning that the app is not responding.

**Comment by MilosKozak** [comment]
yes, `stopBolusDelivering` should not definitely run in UI thread
changed in https://github.com/MilosKozak/AndroidAPS/commit/77904cd1fdab557c303cb9c71eee6041c39a8943

**Comment by bartsopers** [comment]
Great, thanks!
