### ISSUE TITLE
[2.6.0 RC01] Message : New version for at least 1 days available! Fallback to LGS...

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2287]
I changed my phone on friday evening, and install AAPS latest version on it (2.6-RC01)
After import my preferences, I first receive a message "Loop disable" because Engineering mode was not active (normaly not necessary on a released version...) 
Now each days I have a message "New version for at least 1 days available..." (it's allways 1 day...)
I don't understand why it ask me to update every days ?

![Screenshot_20191216-210714_AndroidAPS](https://user-images.githubusercontent.com/52934600/70940410-89376880-204a-11ea-870d-315c34d92294.jpg)

**Comment by jotomo** [comment]
Likely a duplicate of https://github.com/MilosKozak/AndroidAPS/issues/2266 - resolved in dev.

**Comment by Philoul** [comment]
ok, I close it...
thank's
