### ISSUE TITLE
DIA @ OpenAPS-AMA doesn't match DIA @ local profile 

### ISSUE THREAD

**Issue by vmichalec** [MilosKozak/AndroidAPS#2288]
There is a difference between DIA set in the local profile and the value shown in OpenAPS-AMA (AndroidAPS 2.5.1)

Maybe it is DetermineBasalAdapterAMAJS.java, maybe shoud be max() instead of min()? See last picture.

![Screenshot_20191217-173047_AndroidAPS](https://user-images.githubusercontent.com/24793786/71015863-9446d300-20f4-11ea-9051-d6b8f2e66885.jpg)

![Screenshot_20191217-173147_AndroidAPS](https://user-images.githubusercontent.com/24793786/71015864-9446d300-20f4-11ea-828d-6627149cff61.jpg)

![math_min](https://user-images.githubusercontent.com/24793786/71017122-6bbfd880-20f6-11ea-9cf9-c52e4043a06c.png)

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/FAQ.html#aps-algorithm
