### ISSUE TITLE
[2.6 RC01] Double bolus still an issue

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2292]
I still experience the "double bolus problem" where a bolus is logged twice in AAPS but not in the pump. (This time 17.12.2019, 16:40 --> see screenshot)

![Screenshot_20191217-164555_AndroidAPS](https://user-images.githubusercontent.com/50026512/71084184-040c9a80-2195-11ea-976c-948df33484ed.jpg)
![Screenshot_20191217-164603_AndroidAPS](https://user-images.githubusercontent.com/50026512/71084193-07078b00-2195-11ea-8d3f-25c569ee03e7.jpg)

[AndroidAPS._2019-12-17_00-01-02_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3978248/AndroidAPS._2019-12-17_00-01-02_.0.zip)
[AndroidAPS._2019-12-17_00-01-02_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3978249/AndroidAPS._2019-12-17_00-01-02_.1.zip)
[AndroidAPS._2019-12-17_00-01-02_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/3978250/AndroidAPS._2019-12-17_00-01-02_.2.zip)
[AndroidAPS._2019-12-17_21-01-11_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/3978251/AndroidAPS._2019-12-17_21-01-11_.0.zip)
[AndroidAPS._2019-12-17_21-01-11_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/3978252/AndroidAPS._2019-12-17_21-01-11_.1.zip)

**Comment by andyrozman** [comment]
I see where the problem is... When pump history was resolved it tried to map history entry, to currrent Treatments and instead of finding one, it found 2... Carbohydrate entry and insulin entry. Since it found 2, it reported error and added additional entry.
I will extend filtering to exclude non insulin entries... I will try to add this before 2.6 release is made.

**Comment by andyrozman** [comment]
One question... To your treatment picture... Why do you have separate entry for Bolus and for CH? Did you do half of entry on pump (bolus) and half on aaps (CH)?

**Comment by RobHoff** [comment]
No, everything was done in AAPS. The CH where ecarbs I think.

**Comment by pjdjesus** [comment]
Another example of a double-entry:
[AndroidAPS.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4019969/AndroidAPS.log.zip)
![Screenshot_20191225-145214_NSClient](https://user-images.githubusercontent.com/36236092/71736271-f02d8d80-2e50-11ea-977e-1f9922766361.jpg)

**Comment by andyrozman** [comment]
Is this still an issue? @RobHoff

**Comment by RobHoff** [comment]
It didn't happen with 2.6, yet :-)
 

Gesendet: Donnerstag, 26. März 2020 um 21:17 Uhr
Von: "Andy Rozman" <notifications@github.com>
An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com>
Cc: RobHoff <ro91@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [MilosKozak/AndroidAPS] [2.6 RC01] Double bolus still an issue (#2292)


 

Is this still an issue? @RobHoff

**Comment by pjdjesus** [comment]
I'm just running v2.6.1 for 2 days. So far so good.
