### ISSUE TITLE
[2.6-dev (18.12.2019)]  App crash - no profile set

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2294]
### Background info:
This happened twice to me already, last time last night starting 1:38AM. 
(I am not sure how this can be reproduced currently - I have now set a new automation trigger to fire for BG below 300 to set a temp PS of 99% for 2min in order to reproduce. I now enabled Automation, Core, NSClient, Profile and Pumpqueue log setting. Issue did not re-occur so far)

### ISSUE:
Phone was in flight mode so NS client was writing to queue only. 
I use Automation for rising BG > 140 to set temporary PS of 115% for 10min of my local profile. 
First BG >140 occured at 1:38AM at which time the errors start in the logs. Errors indicate that no profile can be found:
_01:38:28.087 [RxCachedThreadScheduler-35] E/PROFILE: [ProfileFunctions.getProfile():155]: getProfile at the end: returning null_

Phone woke me up with an alarm "NO PROFILE SET" at 05:25AM. From the logs I see that the app has crashed and restarted at that point in time. 

### LOGS:
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3982345/AndroidAPS.log)

![2019-12-19_08-54-04](https://user-images.githubusercontent.com/38214111/71155712-9e74e880-223e-11ea-92b1-facee7c06035.jpg)

**Comment by PoweRGbg** [comment]
I have a similar problem with NSprofile and full connectivity

**Comment by 2flea** [comment]
Happened today again - I saw it at 11:08AM. Phone was online in Wifi and all the time next to me and pump.
No automation triggered at that time. 

If you have any idea what to have a special look at and what might cause this let me know.

### LOGS:
[AndroidAPS_20191220.log](https://github.com/MilosKozak/AndroidAPS/files/3987823/AndroidAPS_20191220.log)

**Comment by 2flea** [comment]
Both times I see following peace of logs around the time the issue occured:

05:24:54.018 [main] D/CORE: [MainApp.onCreate():130]: onCreate
05:24:54.094 [main] I/CORE: [MainApp.onCreate():161]: Version: 2.6-dev
05:24:54.094 [main] I/CORE: [MainApp.onCreate():162]: BuildVersion: 101b294ad-2019.12.16-10:58
05:24:54.095 [main] I/CORE: [MainApp.onCreate():163]: Remote: https://github.com/MilosKozak/AndroidAPS.git
05:24:54.112 [main] E/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter.<init>():162]: No connection to ruffy. Pump control unavailable.
05:24:54.122 [main] D/PROFILE: [NSProfilePlugin.loadNSProfile():96]: Loading stored profile


11:03:04.841 [main] D/CORE: [MainApp.onCreate():130]: onCreate
11:03:05.082 [main] I/CORE: [MainApp.onCreate():161]: Version: 2.6-dev
11:03:05.086 [main] I/CORE: [MainApp.onCreate():162]: BuildVersion: 72a7f78b9-2019.12.19-16:09
11:03:05.087 [main] I/CORE: [MainApp.onCreate():163]: Remote: https://github.com/MilosKozak/AndroidAPS.git
11:03:05.152 [main] E/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter.<init>():162]: No connection to ruffy. Pump control unavailable.
11:03:05.170 [main] D/PROFILE: [NSProfilePlugin.loadNSProfile():96]: Loading stored profile

**Comment by 2flea** [comment]
Another time "no profile set" today at 20:35. 

[AndroidAPS_20191221.log](https://github.com/MilosKozak/AndroidAPS/files/3991812/AndroidAPS_20191221.log)

**Comment by MilosKozak** [comment]
should be fixed in dev now
