### ISSUE TITLE
Request to add log browsing function

### ISSUE THREAD

**Issue by wootmasterslick** [MilosKozak/AndroidAPS#2295]
I have been receiving a number of messages from AAPS of which I was unable to read the full message in the notification screen. Then when opening AAPS the message had already disappeared from the main screen. My wish is to be able to review these messages in AAPS. 
I know they are being tracked in the log file but in order to view this I need to browse a very long text file/ export it to pc etc.
My idea was to add a section that allows you to browse the log file, or at least the last 24hours.

**Comment by MilosKozak** [comment]
it was already there but it was really hard to read it on phone thus it has been removed.
