### ISSUE TITLE
[DEV 19.12.2019] No "unreachable pump" message?

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2296]
![1b49ab55-4f40-4d0c-a352-6835ff23a4ac](https://user-images.githubusercontent.com/608650/71242925-f7a84f00-2306-11ea-8418-7c75f1cd6777.jpg)

![a8f223be-4e6a-43d6-9332-222aa31826de](https://user-images.githubusercontent.com/608650/71243337-0e9b7100-2308-11ea-92c1-1880d122e5ab.jpg)

Logs: 
[AndroidAPS_LOG_1576825858219.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3987508/AndroidAPS_LOG_1576825858219.log.zip)

**Comment by jotomo** [comment]
The "pump unreachable" alert is suppressed while the pump is disconnected.
From a quick look at the logs, the message appears to be an announcement that was received from Nightscout...

**Comment by parapenT1sta** [comment]
@jotomo The thing is, I don't have a clue about what can be...

**Comment by MilosKozak** [comment]
there is not enough info in log file.
closing
