### ISSUE TITLE
Dana Pump (R) not able to disconnect for 15/30  min 

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2301]
I am not able to disconnect my Dana R pump for 15 or 30 min. I only see the option 1h and longer. I can delete the line "if (pumpDescription.tempDurationStep15mAllowed)" in overwiew fragment to enable the feature. It seems to be an issue just for Dana R pump only ...or is there any reason for this limitation?

**Comment by AdrianLxM** [comment]
Does your pump have the capability to do a zero-temp shorter than 60 minutes?

**Comment by MilosKozak** [comment]
you need to upgrade pump to v2 to have such feature

**Comment by CaroGo** [comment]
Oh, OK. Is it possible to find that information somewhere.. And possible explanation?
