### ISSUE TITLE
Feature request - SMBs suitable for low basal rates using  temp basals as fine adjustments

### ISSUE THREAD

**Issue by evalisapphire** [MilosKozak/AndroidAPS#2304]
Hi Milos,

We love AAPS, we’d like to avoid having to dilute insulin to use SMBs though. Could you please consider a revised SMB algorithm suitable for low basal rates so that bolus increments below 0.1 are delivered via temp basals. Thanks so much 🙏

**Comment by MilosKozak** [comment]
openaps 0.7 will support this
