### ISSUE TITLE
[enhancement] Automation action - cancel negative IOB

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#2306]
[enhancement] - Add to the list of possible actions under the Automation plugin the ability to cancel negative IOB and therefore to set IOB == 0

Reasoning: Imagine the following: you have a busy day when you are more active than usual, you spend time working in the garden and fetching and carrying. Maybe you have set a higher TT, but AAPS correctly withholds insulin and keeps your BG to an acceptable level. However, over a number of hours IOB has gone negative due to the delivered insulin being less than normal basal. The algorithm is therefore (incorrectly) predicting a rise.

You then stop working and take a rest. BG starts to rise naturally due to the reduced level of activity, but the rise triggers the loop into action. It now delivers insulin based on the (incorrect) forecast which has been calculated using the negative IOB figure and would likely be too high. Therefore too much insulin is delivered at a time when insulin sensitivity is likely temporarily greater than usual.

As a manual intervention the user can deliver a "fake" bolus ("Do not bolus. record only") to cancel the negative IOB but ideally there would be a way to automate this. Using the Automation plugin a user could set conditions (e.g. BG < x .AND. IOB < 0) which would trigger an action which sets negative IOB back to zero.

**Comment by nicoleloop** [comment]
Yes! That's the exact problem I've been running into lately. I wasn't sure what they changed in the programming, but it scares me when I've been active for a few hours and then see that my blood sugar is in the low 60's...yet AAPS is running a 90% temp basal! Out of curiosity I sat and watched it continue to fall to 48 that day before I intervened and simply disconnected my pump for 35 minutes. Even using a hypo TT AAPS was still interspersing the expected 0% temp basals with 90%... And my BG levels were plummeting. My question about the dangers posed by that programming behavior were brushed off; at best. I've not felt safe using the AndroidAPS during any sustained activity for about a month now. 😉

**Comment by GrapesAfonsoGithub** [comment]
I do this manual IOB intervention (through fake bolus) especially at night. It would be a very welcome feature.

**Comment by MilosKozak** [comment]
sorry there will never be an action affecting the algorithm. Just because it would be dangerous in wrong hands or if you do only stupid mistake.
Paste a screenshot with APS result where you think result should be different and we can work on improving this
