### ISSUE TITLE
[2.5.1] Boluses from Insight pump have wrong date

### ISSUE THREAD

**Issue by stefankarner** [MilosKozak/AndroidAPS#2307]
I am using AAPS 2.5.1 with Accu-Chek Insight and a local profile. Whenever I issue a bolus between 00:00 and 00:59 the record is saved with the date of the day before. E.g. if I bolus at Dec 24, 00:28 the bolus history in AAPS shows Dec 23, 00:28 instead. 

Accordingly, the IOB calculations are wrong if there were any boluses issued between 00:00 and 00:59. This is potentially dangerous as the loop might think that there is less IOB than there actually is. 

My phone is set to Central European Time (UTC+1), so I suppose this might be some sort of timezone issue.

Please see the attached logs for further details:
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3996717/AndroidAPS.log)

**Comment by wootmasterslick** [comment]
How could this happen? It used to work fine in last version. We use autotune regularly so that is impacted, this could explain the highs we experience during nights.  Perhaps we need more bug screening before a next release since we are now forced to use this version.

**Comment by TebbeUbben** [comment]
Could you provide more information about your pump's firmware and manufacturing date, please? Does it behave diffently when changing the time zone of your phone?
