### ISSUE TITLE
ziparchive: unable to open ... base.apk No such file or directory

### ISSUE THREAD

**Issue by PolynomialDivision** [MilosKozak/AndroidAPS#2308]
I can not install the apk. I tried `fullDebug` and `fullRelease`. I can not even retrieve the logs...

Infos:

- Android Studio 3.5.3
- Phone: Hauawei P20 Lite
- Android 9

Here is the error obtained from `logcat`:

    W ziparchive: Unable to open '/data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk': No such file or directory
    E ndroid.launche: Failed to open APK '/data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk' I/O error
    E ResourcesManager: failed to add asset path /data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk
    W PackageManager: Failure retrieving resources for info.nightscout.androidaps
    I RecentsTaskLoadPlan: to show tasks size is 3
    W ziparchive: Unable to open '/data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk': No such file or directory
    E ndroid.launche: Failed to open APK '/data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk' I/O error
    E ResourcesManager: failed to add asset path /data/app/info.nightscout.androidaps-TemlX2EejchMI2W5wyrSlQ==/base.apk
    W PackageManager: Failure retrieving resources for info.nightscout.androidaps
    
More:

    D NetworkSecurityConfig: No Network Security Config specified, using platform default
    I PreDnsController: canPreDnsQuery,persist.sys.predns is false!
    W System.err: java.lang.IllegalArgumentException: Unknown package: null
    W System.err: 	at com.android.server.pm.Settings.getInstallerPackageNameLPr(Settings.java:4618)
    W System.err: 	at com.android.server.pm.PackageManagerService.getInstallerPackageName(PackageManagerService.java:23458)
    W System.err: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1136)
    W System.err: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:4466)
    W System.err: 	at com.android.server.pm.HwPackageManagerService.onTransact(HwPackageManagerService.java:432)
    W System.err: 	at android.os.Binder.execTransact(Binder.java:739)
    E         : [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
    
More:

    I HwApsImpl: APS: new HwApsImpl created
    W ziparchive: Unable to open '/data/app/info.nightscout.androidaps-qIAZKS_VFPObH6uh5WiczA==/base.apk': No such file or directory
    E ndroid.launche: Failed to open APK '/data/app/info.nightscout.androidaps-qIAZKS_VFPObH6uh5WiczA==/base.apk' I/O error
    E ResourcesManager: failed to add asset path /data/app/info.nightscout.androidaps-qIAZKS_VFPObH6uh5WiczA==/base.apk
    W PackageManager: Failure retrieving resources for info.nightscout.androidaps

**Comment by MilosKozak** [comment]
it's your phone problem .... try troubleshooting steps in wiki
