### ISSUE TITLE
[2.6 RC2] Missing view/button refresh when cancelling temp basal

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2310]
The "Cancel nnn%"-button for cancelling a temp basal rate (action tab) doesn't load the correct BR-state after cancelling. When pressing the button, the font greys out during processing the routine and shows the same BR as before.
This is just a visual issue, as the instructions are delivered, pump and home-screen show running on correct base profile afterwards. Also the action-tab will show its correct status, but only after reloading the app entirely.

Haven't noticed this behavior on official master.

Using AndroidAPS 2.6-rc2
Build fce61afa8-2019.12.20-02:31
Pump DanaRS

Can provide logs tomorrow if needed

**Comment by MilosKozak** [comment]
this will be redesigned in RC3 ..... wait and report again if needed
