### ISSUE TITLE
After update to DEV 2.6 from 23.12.19: No Bolus entry in NS, after refresh NS entrys Bolus is deleted in AAPS

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2311]
DEV 2.6 Build: 677f1e4c8-2019.12.23-20:40

After update to this version:

After using calculator and giving 4 I/E for 40g carbs (15 minutes later).
Direct after that, the entrys are shown in AAPS.
But in NS I saw only the carbs and after refresh from NS, the 4 I/E are also gone in AAPS.

Because the "careportal" is gone in this version and there is no option in "actions" tab, I can correct this only over NS.

Sending logs to Andy.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by Alamo04** [comment]
Same with DEV 2.6 967777f0f-2019.12.25-12:33

IOB was shown correct,  but no entry for insulin in NS. 
If I'm not refresh NS entrys, it will stay in AAPS. 

If NS entrys will be refreshed, the entry will also be deleted in AAPS and IOB will decrease at this deleted value.

**Comment by andyrozman** [comment]
Please enable double bolus debugging and I need pictures of Treatments... And time when problem AND what problem happened.

**Comment by Alamo04** [comment]
Test again, just now and same result.
Deleted the Logs just before the test and send them again to your mail.
![Screenshot_20191225-160721_AndroidAPS](https://user-images.githubusercontent.com/36486505/71447634-1f494e00-2731-11ea-915c-a21c54a1cc0a.jpg)
![Screenshot_20191225-160707_Chrome](https://user-images.githubusercontent.com/36486505/71447637-26705c00-2731-11ea-9830-ab5ff1a5722b.jpg)

**Comment by Alamo04** [comment]
In the last mail to you I hyve given the time etc.
Now I deleted the Logs and did a new test, with a fresch log. Will send it also to your mail.
![Screenshot_20191225-160721_AndroidAPS](https://user-images.githubusercontent.com/36486505/71447684-dcd44100-2731-11ea-99d1-0dd9ec721c49.jpg)

**Comment by Alamo04** [comment]
![Screenshot_20191225-161331_Opera](https://user-images.githubusercontent.com/36486505/71447694-f5dcf200-2731-11ea-8207-06e03c2ebaf4.jpg)

**Comment by andyrozman** [comment]
[AndroidAPS_LOG_1577287288909.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4006981/AndroidAPS_LOG_1577287288909.log.zip)

**Comment by Alamo04** [comment]
Still happens with latest dev.

Also confirm https://github.com/MilosKozak/AndroidAPS/issues/2329

**Comment by Alamo04** [comment]
Fixed for my system with latest Dev from 09.01.2020

**Comment by Alamo04** [comment]
Sorry, it comes back with bigger bolus over calculator. Still not fixed.

For smaller bolus/carbs it works in my first tests.

This problem comes with the new UI.

**Comment by MilosKozak** [comment]
logs?

**Comment by Alamo04** [comment]
@MilosKozak 

Andy has posted them above.
https://github.com/MilosKozak/AndroidAPS/files/4006981/AndroidAPS_LOG_1577287288909.log.zip

New from today calculator was used to give insulin at 17:09 and carbs at 17:24.
Carbs will stay in reports and graph, insulin was deleted again.
Used and tested with the latest dev from yesterday evening.

You can find the new log, from today, here:
https://www.dropbox.com/s/km4azl1x49bt46l/AndroidAPS_LOG_1579128169347.log.zip?dl=0

**Comment by Alamo04** [comment]
It was still the same, IOB was shown correct and was not deleted.
Also the carbs will not be deleted.
Only the insulin units are deleted in graph and report.

This will only happens if calculator was used.

![Screenshot_20200115-235141_Opera](https://user-images.githubusercontent.com/36486505/72478503-73a49280-37f2-11ea-99a8-2226e7e4e8af.jpg)

**Comment by MilosKozak** [comment]
nsclient logging is not enabled , so i cannot confirm if it's the same bug. but i'd expect it's fixed in dev now.
create new issue if this appear in RC6
