### ISSUE TITLE
[2.6-dev] Refactor header area destroys layout on Atom

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#2318]
![image](https://user-images.githubusercontent.com/12517693/71562614-e8ea3680-2a82-11ea-83db-9da61332ede1.png)

**Comment by swissalpine** [comment]
@osodebailar

**Comment by osodebailar** [comment]
I will check the problem on my atom and fix it

**Comment by swissalpine** [comment]
Thank you. And can you change the color of the in range bg back to green. It is nice if we have the same color as Nightscout. In my opinion the choose of colors has to be consequent and should follow a concept ...
If you like you can use this xml as a working layout for small devices. I'm not convinced that the new header area has any benefit for those.
![image](https://user-images.githubusercontent.com/12517693/71577415-52565d80-2af4-11ea-904a-470b94b70ca6.png)

[overview_fragment_smallheight.zip]

**Comment by swissalpine** [comment]
[overview_fragment_smallheight.zip](https://github.com/MilosKozak/AndroidAPS/files/4009490/overview_fragment_smallheight.zip)

**Comment by swissalpine** [comment]
Oh. Sorry. I didn't see that you have fixed it allready.
