### ISSUE TITLE
Cancel button in bolus progress dialog can not be re-enabled

### ISSUE THREAD

**Issue by bartsopers** [MilosKozak/AndroidAPS#2322]
Once the Stop button in the bolus progress dialog is pressed, it is removed from the dialog (or disabled, I don't remember). However, when cancelling the bolus fails, there is no way to re-enable the button from code. I feel this ability should be added in order for users to be able to retry bolus cancellation.

**Comment by MilosKozak** [comment]
all drivers are trying to stop bolus again if stop fail
pm me if you need help

**Comment by bartsopers** [comment]
Alright thanks. I implemented that in the Omnipod driver too now.
