### ISSUE TITLE
2.6rc2 Crash 

### ISSUE THREAD

**Issue by JelmerFokkema** [MilosKozak/AndroidAPS#2324]
Aaps 2.6rc2 crashes when opening pump profile from the Dana Tab all other buttons in the Dana tab function properly. 
![Screenshot_20191230-125802__01](https://user-images.githubusercontent.com/51903932/71596868-50ff5200-2b41-11ea-8972-3bb55b4e70d3.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4010763/AndroidAPS.log

**Comment by MilosKozak** [comment]
it's already resolved in dev
