### ISSUE TITLE
Refactored headers cause TBR not to be fully visible

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2329]
I reported this on gitter but didn't see a response so just in case it's slipped through the cracks, here goes....

I'm running the very latest dev build 1b4d06101-2020.01.02-18:44 full release with Nightscout 13.0.1 on a Moto G7 Power running Android 9 (fully updated).

The newly refactored headers cause the TBR to be presented always as "BAS: 0% (min/30) orig BR".  The actual TBR % is cut off as 0% by the start of the line/"BAS: ".

I've attached a screenshot showing the issue.  You can see that the TBR is 0.25 U/h (500%) of the original Basal of 0.05 U/h.

![Screenshot_20191229-164045](https://user-images.githubusercontent.com/2486510/71683573-3b816680-2d93-11ea-9267-a731145ef357.png)

**Comment by guydavies** [comment]
Note, this was taken with an older version but it still seems to be the case.  Right now, my TBR *is* 0% so that doesn't really show the issue well, so I used an older screenshot.

**Comment by MilosKozak** [comment]
what pump?

**Comment by guydavies** [comment]
Virtual pump (Medtronic 640G) for now

**Comment by Alamo04** [comment]
Confimed with Medtronic 754

**Comment by MilosKozak** [comment]
fixed in dev branch
