### ISSUE TITLE
Slow rendering of Overview screen

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#2330]
Ver 2.5.1 the overview screen renders very slowly. It seems that having the IOB graph and to a lesser extent the Activity graph turned on creates the problem. It was not a problem in earlier versions.

**Comment by wootmasterslick** [comment]
Same here, much slower than version before

**Comment by MilosKozak** [comment]
can you explain what graph configuration is slow?

**Comment by roppenheimer** [comment]
When the IOB and also the Activity graphs are selected in the Overview screen there is a delay before the graphs refresh. This shows up when the orientation of the phone is changed or when changing the timescale for the display.

**Comment by MilosKozak** [comment]
closing as there i don't see more info how to dela with this
