### ISSUE TITLE
[2.6 RC2] discrepancy between graph background and pump/loop state

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2335]
Observing following behavior:

User: Suspend Loop for X hour
--> AAPS: suspends Loop; graph background greys out for X hours into future (expected)
User: Disconnect pump for 15min
--> AAPS: sets BR to 0%, graph background double greys out (expected)
User: waits 15min
--> AAPS: sets **Loop fully active**; **background** still **greyed out** (at least one of these effects needs improvement)

From my expectation, after completing the 15min timer AAPS should return to its previous state (Loop suspended).
If switching back to fully operational Loop-state is intentional (no matter which previous state was selected), I highly recommend to have the graphs background behave in the same manner.

I haven't tested this for the actual master (2.5.1) - maybe someone can check that too.

![Screenshot_AndroidAPS_20200103-095234](https://user-images.githubusercontent.com/38337079/71759180-7249a080-2ea9-11ea-9043-4ba95f858d0e.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/b1a376e68a10737953daf2882e152e9a204fdf40
