### ISSUE TITLE
COB in open loop temp basal reason should be 0Decimal

### ISSUE THREAD

**Issue by danielhers** [MilosKozak/AndroidAPS#2337]
In version 2.5.0, open loop with OpenAPS AMA shows a really long "reason" string for cancelling a temp basal. The COB is shown with full precision but it should just be rounded to the nearest integer.

I tried to find where in the code the COB string is calculated for showing in the reason but failed...

**Comment by MilosKozak** [comment]
this is output of algorithm and it's hard to change
