### ISSUE TITLE
Statistika

### ISSUE THREAD

**Issue by Korostensky** [MilosKozak/AndroidAPS#2345]
Reporting bugs
--------------
Při spuštění statistika aplikace zamrzne.
![Screenshot_20200109-214240_AndroidAPS](https://user-images.githubusercontent.com/54218454/72103433-80744280-3329-11ea-9014-34990f1ee9d1.jpg)

- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner). 2.6 rc3
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/ae87a6ae0cda0557bf9e57209eb46efc8f897375
