### ISSUE TITLE
[2.6-dev] Overview graphs no longer displayed due to NPE in DatabaseHelper.java

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2346]
@MilosKozak any idea where my graphs are gone? It worked fine till 1h ago. I disconnected pump for shower and afterwards my graphs looked like this. I tried to install apps again. Stopped and deleted cache. No help. Any clue where to look?
Killed all and restarted phone also.

![image](https://user-images.githubusercontent.com/38214111/72104455-c3cfb080-332b-11ea-96de-2a9f5120eb44.png)

21:53:47.066 [main] D/CORE: [MainApp.onCreate():125]: onCreate
21:53:47.161 [main] I/CORE: [MainApp.onCreate():156]: Version: 2.6-dev
21:53:47.162 [main] I/CORE: [MainApp.onCreate():157]: BuildVersion: 61411e6bd-2019.12.26-18:44
21:53:47.163 [main] I/CORE: [MainApp.onCreate():158]: Remote: https://github.com/MilosKozak/AndroidAPS.git
21:53:47.183 [main] E/info.nightscout.androidaps.plugins.pump.combo.ruffyscripter.RuffyScripter: [RuffyScripter.<init>():162]: No connection to ruffy. Pump control unavailable.
21:53:47.208 [main] D/SMS: [SmsCommunicatorPlugin.processSettings():146]: Found allowed number:
21:53:47.224 [main] E/PROFILE: [ProfileFunctions.getProfile():155]: getProfile at the end: returning null
21:53:47.798 [main] D/CORE: [ActivityMonitor.onActivityResumed():32]: onActivityResumed: MainActivity
21:53:47.888 [main] D/OVERVIEW: [OverviewFragment.updateGUI():996]: updateGUI entered from: onResume
21:53:49.668 [Thread-15] D/AUTOSENS: [Profiler.log():14]: >>> IobCobOref1Thread <<< executed in 1977 miliseconds
21:53:49.682 [main] D/OVERVIEW: [Profiler.log():14]: >>> onResume <<< executed in 1790 miliseconds
21:53:49.682 [Thread-30] D/OVERVIEW: [Profiler.log():14]: >>> onResume - 1st graph - START <<< executed in 1791 miliseconds
21:53:49.749 [Thread-30] E/CORE: [MainApp.lambda$onCreate$0():138]: Uncaught exception crashing app
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at info.nightscout.androidaps.db.DatabaseHelper.preprocessOpenAPSOfflineEvents(DatabaseHelper.java:1472) ~[na:0.0]
at info.nightscout.androidaps.db.DatabaseHelper.getCareportalEventsFromTime(DatabaseHelper.java:1443) ~[na:0.0]
at info.nightscout.androidaps.plugins.general.overview.graphData.GraphData.addTreatments(GraphData.java:326) ~[na:0.0]
at info.nightscout.androidaps.plugins.general.overview.OverviewFragment.lambda$updateGUI$26$OverviewFragment(OverviewFragment.java:1431) ~[na:0.0]
at info.nightscout.androidaps.plugins.general.overview.-$$Lambda$OverviewFragment$8-sFoErja5VhA_rdqskznJjKpoA.run(Unknown Source:18) ~[na:0.0]
at java.lang.Thread.run(Thread.java:764) ~[na:0.0]

**Comment by 2flea** [comment]
I did a reset of DB in AAPS and restarted my phone afterwards. I got back graphs again. Not sure what the root cause was here. I did multiple disconnects this afternoon/evening, automation did temporary PS which overlapped with disconnects. I will have a look if this happens again...

Nevertheless it might be a good idea not to raise NPE and crash at that step.

**Comment by rustymonkey** [comment]
fyi, I'm seeing a variant of this: the top graph is showing, but the bottom graph is empty.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/67b3b2613d92acc9b8e3ae6a66fb4259949d8f93
