### ISSUE TITLE
[2.6 RC3] Care portal disabled

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2347]
CP cannot be enabled in config builder. If I check the box on the left it is checked and in the same second automatically unchecked again.

build: fe4a6fc62-2020.01.10-06:21
Samsung Galaxy A3 (2017), Android 8.0.0, Samsung Experience 9.0

**Comment by PoweRGbg** [comment]
Try from the Actions tab  :)

**Comment by xJoe** [comment]
There are only some of the functions available in actions tab. I am missing
- Excercise
- Carb correction (i.e. if you forgot to bolus and want to enter carbs eaten more than 60 min ago)
- Correction bolus
- Note
- Pump site change
- Insulin cartridge change
- Pump battery change

**Comment by guydavies** [comment]
pump site change in actions contains the insulin reservoir change and catheter change as check boxes. I agree that the others are missing. however, I think @MilosKozak has already pointed out why the changes were made.

**Comment by xJoe** [comment]
@guydavies thanks for the hint. It is a problem with the translation to German therefore I did not espect it to be there. Nevertheless I am not happy with this pump site change solution.
Which statement of Milos do you mean?

**Comment by guydavies** [comment]
there was an earlier issue raised in which I discussed the same issues. I don't have the number to hand but it was recent (an issue on the dev branch). 

I initially didn't like the pump site change but it's more an issue of what you're used to. I've been using it since Christmas and I'm now used to the new workflow.

The pump battery change also appears in actions so that's not an issue.

**Comment by xJoe** [comment]
> there was an earlier issue raised in which I discussed the same issues. I don't have the number to hand but it was recent (an issue on the dev branch).

I guess you mean this one: https://github.com/MilosKozak/AndroidAPS/issues/2320#issuecomment-570093416

**Comment by guydavies** [comment]
that's the one.

**Comment by xJoe** [comment]
After going into details the only one really missing is the note. Notes can be made when performing an action (i.e. bolus...) but sometimes it is helpful to make a note without action just for later reference.
As notes are possible with actions, is there a possibility to get the note without action button back @MilosKozak? Would be great!
I am thinking of preparing a page in docs about how to act with v2.6 if you have been using CP before.

**Comment by MilosKozak** [comment]
so note and excercise is missing?

**Comment by guydavies** [comment]
I ended up using Automate to make direct REST POST messages to NS for
exercise. Since my exercise falls into two fairly specific classes (mostly)
it was easy to setup a couple of flows to identify a walk of >10 minutes or
a visit to my gym 🙂. Other than that I'll have to work something else out
maybe using IFTTT to create a specific exercise icon on my home screen.

**Comment by xJoe** [comment]
> 
> 
> so note and excercise is missing?

Yes. Thanks.
Would be very happy if you can integrate it. Heard from several persons in my AAPS bubble that they would also miss note and excercise.

**Comment by TEbinger** [comment]
Another thing is missing imho: You can't tell AAPS that You have a new reservoir. So insulin age is getting older and older. This button should be implemented. Then in configuration You still have the entry "Carportal", but You can't activate it. This is confusing and should not be shown at all if there is no careportal tab anymore.

**Comment by RobHoff** [comment]
Same for me...reservoir age button is missing and additionally, "Careportal" can't be activated.

**Comment by xJoe** [comment]
@TEbinger & @RobHoff 
Option is available after clicking button prime/fill. 
Maybe pump site change would be a better text on the button.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/23de3b0a3bc43d66c7325feed7f13b1b10d9648b
