### ISSUE TITLE
[2.6 RC3] New design start page

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2348]
Not really an issue, just my opinion:
- BG number might be a bit bigger (not as big as it was)
- Font size IOB/COB/BAS/AS would look better if same size as for BG delta etc. would be used (the text below BG number)

**Comment by Philoul** [comment]
I made 2 screenshots on my dev phone : I'm agree with you
=> As you can see in low res phone text is to big (2 lines for basal and delta...) => Graph size is then reduced.

I think it is necessary to add parameters for the text information on the graph (too much unreadable text on the graph) ... (eCarbs values, temp basal value, CP notifications, invalid value, missing value...)

![Screenshot_20200111-082539](https://user-images.githubusercontent.com/52934600/72208623-4039cf00-34a5-11ea-9497-f674b46f81f4.png)
![Screenshot_20200111-082705](https://user-images.githubusercontent.com/52934600/72208713-6b70ee00-34a6-11ea-9239-94c9785890e1.png)

**Comment by zjedr** [comment]
And the delta line should wrap between the 15 & 40 delta rather than the 40 delta label and value

**Comment by MilosKozak** [comment]
delta has been splitted to 2 lines
