### ISSUE TITLE
Připojení k pumpě DanaR

### ISSUE THREAD

**Issue by Korostensky** [MilosKozak/AndroidAPS#2350]
9.1. od 23:12 se nedařilo připojit k pumpě. Ve 3:26 jsem řešil po notifikaci z XDripu. Od té doby běží ok. Myslím, že hlídač BT byl zapnutý. Spouštěčem problému bylo “odpojení pumpy na hodinu“. 
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
[AndroidAPS_LOG_1578602223544.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4045754/AndroidAPS_LOG_1578602223544.log.zip)
[AndroidAPS_LOG_1578623198172.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4045757/AndroidAPS_LOG_1578623198172.log.zip)

**Comment by MilosKozak** [comment]
Phone was not able connect to pump. Usualy android issue
If you have this issue regulary turn on PUMPBTCOMM logging and report again when this happen
