### ISSUE TITLE
[2.6 RC3] ACT: Button "Cancel TBR" with automatic TBR

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2352]
TBR button on ACT tab changes to cancel when AAPS reduces TBR automatically to keep BR in range.
Would have expected that to happen only with TBR activated manually by user.

build: fe4a6fc-2020.01.10-06:21
Samsung Galaxy A3 (2017), Android 8.0.0, Samsung Experience 9.0

![ACT_TBR](https://user-images.githubusercontent.com/13958493/72177044-2a160b00-33e0-11ea-83e3-85827ae76fe9.jpg)

**Comment by MilosKozak** [comment]
we don't distinquish who issued TBR
have possibity to cancel TBR is good when loop did something wrong
