### ISSUE TITLE
Reactivate delayed bolus in open loop

### ISSUE THREAD

**Issue by mikatajo** [MilosKozak/AndroidAPS#2353]
Unfortunately, in the current master version 2.5.1 you can no longer use a delayed bolus in the "open loop". Please enable the possibility to deliver a delayed bolus in the open loop again.
Why: 
The delayed bolus in the open loop has helped us to get less fluctuations in blood glucose. At the moment we can use this is only with Dana RS pump. It is really inconvenient and complicated to operate a delayed bolus directly from the pump. He doesn’t like to wait till we select this via Dana RS. For us this is just stress at the moment.

We need more time and experience before we switch to the close loop. In open loop delayed bolus help us very much.

**Comment by MilosKozak** [comment]
Allowed
https://github.com/MilosKozak/AndroidAPS/commit/94dd843825c9b30c5d6ac73f399f4761a2526a3f
