### ISSUE TITLE
[2.6 RC3] NSClient: option for local profile

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2356]
1. Treatment tab>profile switch: has clone option to create local profile
2. Quick wizzard dont allow selecting local profile
3. Upload local profile changes to ns on/off option appears in Preferences

As im not sure if the local profile option was previously in nsclient (as neverused it), cant say what is wrong,you understand for sure :)

However in such case that local profile wasnt available for nsclient, it could be good enhancement for future development. Can image scenarios when I would like to update profile locally even via ns client and use upload to ns.

**Comment by MilosKozak** [comment]
i'm not sure i understand you
you can use local profile and let it upload to ns

**Comment by pmisun** [comment]
There is no possibility in UI  to create local profile in nsclient (not fullrelease) generated from 2.6 rc3 branch.

**Comment by pmisun** [comment]
![20200112_010913](https://user-images.githubusercontent.com/12038874/72212230-78a6d080-34d8-11ea-82de-61e26a8eb1ab.jpg)
![20200112_010852](https://user-images.githubusercontent.com/12038874/72212236-878d8300-34d8-11ea-9f61-cad0e3b3fe6a.jpg)
![20200112_010935](https://user-images.githubusercontent.com/12038874/72212238-95430880-34d8-11ea-8d38-453ec4606144.jpg)

**Comment by MilosKozak** [comment]
this is not planned to be available
from AAPS point of view, NSProfile is read only
you can clone profiles directly NS

**Comment by pmisun** [comment]
..so as mentioned, capabilities shown in case 1. and 3. in UI of NSclient shall be not visible and hidden in UI then. Nmind.
