### ISSUE TITLE
[2.6 RC3] Critical: Bolus/Carbs sometimes do not get logged

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2358]
I have a treatment (20g/2u). Insulin was delivered, only carbs were logged. 
Thought I forgot to give the insulin, double dosed. 

After installing 2.5.1 again it synced and showed all insulin doses correctly.

**Comment by MilosKozak** [comment]
pump? logfiles?
otherwise this report is useless

**Comment by nshtg** [comment]
My pump is a DanaRS.
Seems like my pump was dying (it did some hours later). 
Still I was suprised AndroidAPS did not throw a warning when insulin was applied and not recorded (since the pump responded nonsense probably).
Another error that occured that AAPS set temp basal rates were (displayed correctly on the pump) but not recognized by AndroidAPS.

Logfiles: is there a way I can privatly send them to you?

**Comment by MilosKozak** [comment]
put it here ...... time around the issue is enough

**Comment by nshtg** [comment]
https://gist.github.com/nshtg/ef43872cbb790be61fc0c88a232a9930#file-aaps_20200112-log-L547

6.0 were delivered but not saved to xDrip or to AAPS.
Time on the pump was wrong (gave 6.0 about an hour ago too and both appeared on this time):

![out](https://user-images.githubusercontent.com/5219415/72298032-7d48c180-365d-11ea-9c36-8c5e1ce90d64.jpg)

2-3hrs later the pump started to suddenly reboot every 30s-10min,

**Comment by MilosKozak** [comment]
hmm this looks like messed up db inside pump leading to clash in AAPS.
it's not anythig we can solve in AAPS
