### ISSUE TITLE
[2.6 RC3/4/5] No visual Graph-Feedback on disabled/suspended Loop status

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2360]
Switching into suspended or disabled Loop mode takes functional effect but doesn't result in graying out the graph as user feedback.

Bug or feature? At least it's a change from the expected behavior in earlier versions, but on the other hand it improves readability when using non-loop therapy, so may also be intended - just needs to be clear ;)

//edit: Same behavior in RC4
//edit: Same behavior in RC5. - If no one else can either reproduce or confirm this issue, I consider a flaw on my side (although I have no clue why that would be). For me personally it's a feature, as it eases readability for me and I know where to look for correct Loop/Pump-status.

**Comment by MilosKozak** [comment]
i'm unable to reproduce this issue. provide logfiles if you are able to repeat it

**Comment by goomStar** [comment]
Compiled a clean RC to eliminate errors on my end. Started AAPS, let it fetch up the data, collect a fresh BG value to confirm a running loop.
Then disconnected pump- reconnected pump, suspended loop - resumed loop, disabled loob - enabled loop.
[AndroidAPS_LOG_1578965189901.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4056862/AndroidAPS_LOG_1578965189901.log.zip)

DanaRS, Oneplus One on Android 8.1
Could reproduce the visual behavior. 
![Screenshot_AndroidAPS_20200114-022533](https://user-images.githubusercontent.com/38337079/72306172-93af4700-3676-11ea-921d-fc11c6afc19e.png)
![Screenshot_AndroidAPS_20200114-022445](https://user-images.githubusercontent.com/38337079/72306173-93af4700-3676-11ea-987d-aff07be9d5ac.png)
![Screenshot_AndroidAPS_20200114-022606](https://user-images.githubusercontent.com/38337079/72306174-93af4700-3676-11ea-8d4f-f8dc917d71bf.png)

**Comment by goomStar** [comment]
No change in RC5 for me.
RC2 works and shows expected graying out behavior (well - with issue #2335), RC3+ are leaving the graph clear for me.

Not an issue for me personally as I like the enhanced readability it comes with, and if no one else can reproduce this I'd consider it a flaw on my side (although I don't have a clue why).

**Comment by MilosKozak** [comment]
i see some unspecific crash from "One"
as you are the only one i'd say it's your phone issue. you can try:
reset db in AAPS
clear db in NS
reset phone to factory setting
