### ISSUE TITLE
[2.6-rc3] App crashes on opening statistics 

### ISSUE THREAD

**Issue by tanja3981** [MilosKozak/AndroidAPS#2362]
Pump: Dana RS, although statistics might include combo pump data
BG Source: xDrip 

After clicking Statistics the app hangs and is reported as crashed by android shortly after. Restart is necessary. 

Let me know if you need more information. 
[AndroidAPS (1).log](https://github.com/MilosKozak/AndroidAPS/files/4057838/AndroidAPS.1.log)

**Comment by MilosKozak** [comment]
this is alredy resolved in dev
