### ISSUE TITLE
[2.6 RC3] App frequently loses connection to pump (Minimed Paradigm 522) 

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2363]
I encounter frequent connection losses with the pump. They usually persist for about 30 to 60 minutes. Only after multiple restarts of phone and riley-link connection could be re-established. 

Last time it happened on 13.01.2020 at about 3:30 p.m. 

I didn't realize what I did that caused the connection loss though :-/ 
[AndroidAPS._2020-01-13_00-00-30_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4057931/AndroidAPS._2020-01-13_00-00-30_.0.zip)
[AndroidAPS._2020-01-13_00-00-30_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4057932/AndroidAPS._2020-01-13_00-00-30_.1.zip)
[AndroidAPS._2020-01-13_00-00-30_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4057933/AndroidAPS._2020-01-13_00-00-30_.2.zip)
[AndroidAPS._2020-01-13_00-00-30_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/4057934/AndroidAPS._2020-01-13_00-00-30_.3.zip)
[AndroidAPS._2020-01-13_00-00-30_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/4057935/AndroidAPS._2020-01-13_00-00-30_.4.zip)
[AndroidAPS._2020-01-13_00-00-30_.5.zip](https://github.com/MilosKozak/AndroidAPS/files/4057937/AndroidAPS._2020-01-13_00-00-30_.5.zip)
[AndroidAPS._2020-01-13_00-00-30_.6.zip](https://github.com/MilosKozak/AndroidAPS/files/4057938/AndroidAPS._2020-01-13_00-00-30_.6.zip)
[AndroidAPS._2020-01-13_15-56-26_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4057939/AndroidAPS._2020-01-13_15-56-26_.0.zip)
[AndroidAPS._2020-01-13_15-56-26_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4057940/AndroidAPS._2020-01-13_15-56-26_.1.zip)
[AndroidAPS._2020-01-13_15-56-26_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4057941/AndroidAPS._2020-01-13_15-56-26_.2.zip)
[AndroidAPS._2020-01-13_15-56-26_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/4057942/AndroidAPS._2020-01-13_15-56-26_.3.zip)
[AndroidAPS._2020-01-13_15-56-26_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/4057943/AndroidAPS._2020-01-13_15-56-26_.4.zip)
[AndroidAPS._2020-01-13_15-56-26_.5.zip](https://github.com/MilosKozak/AndroidAPS/files/4057944/AndroidAPS._2020-01-13_15-56-26_.5.zip)

![Screenshot_20200114-084321_AndroidAPS](https://user-images.githubusercontent.com/50026512/72324321-ec98d280-36aa-11ea-979c-9b22235b22e8.jpg)

**Comment by MilosKozak** [comment]
based on logs it seems tobe  RL problem connecting to pump
