### ISSUE TITLE
[2.6 RC3] Graph disappeared suddenly and didn't reappear even after phone restart

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2364]
Happened suddenly after AAPS froze for 5 seconds, at 14.01.2020 around 6:30 a.m.

![Screenshot_20200114-084321_AndroidAPS](https://user-images.githubusercontent.com/50026512/72324662-bf005900-36ab-11ea-8940-999dbcc29b31.jpg)
![Screenshot_20200114-063412_AndroidAPS](https://user-images.githubusercontent.com/50026512/72324668-c0ca1c80-36ab-11ea-85ec-35fbb6acfa56.jpg)
[AndroidAPS._2020-01-14_00-00-07_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4057957/AndroidAPS._2020-01-14_00-00-07_.0.zip)
[AndroidAPS._2020-01-14_00-00-07_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4057958/AndroidAPS._2020-01-14_00-00-07_.1.zip)
[AndroidAPS._2020-01-14_00-00-07_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4057959/AndroidAPS._2020-01-14_00-00-07_.2.zip)
[AndroidAPS._2020-01-14_06-34-20_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4057960/AndroidAPS._2020-01-14_06-34-20_.0.zip)
[AndroidAPS._2020-01-14_06-43-52_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4057961/AndroidAPS._2020-01-14_06-43-52_.0.zip)

**Comment by MilosKozak** [comment]
fixed in dev
