### ISSUE TITLE
[2.6 RC4] App freezes/doesn't respond on loading 'Treatments --> Careportal'

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2365]
Trying to load the careportal tab in treatments causes my app to freeze / getting unresponsable.
[AndroidAPS_LOG_1579019567020.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4060287/AndroidAPS_LOG_1579019567020.log.zip)

**Comment by MilosKozak** [comment]
resolved in dev
