### ISSUE TITLE
[2.6 RC5] Bg in vertical graph shown wrong values

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2367]
![Screenshot_20200115-232127](https://user-images.githubusercontent.com/12038874/72476818-684f6800-37ee-11ea-9877-c10995a32735.png)

Its nsclient, appears randomly aftee time cadence switch. Dismissing after next 5min bg reading

**Comment by pmisun** [comment]
+  cas "před 1"..nevim zda se "min"  odebralo nebo to takhle ma byt.

**Comment by MilosKozak** [comment]
will be resolved in RC6
