### ISSUE TITLE
[2.6 RC5] Top of screen stretched beyond screen

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2368]
![Screenshot_20200115-233612_AndroidAPS](https://user-images.githubusercontent.com/12038874/72477611-2f17f780-37f0-11ea-8710-590d49969b10.jpg)

720 x 1280 px / 294 ppi

**Comment by pmisun** [comment]
+ 

![Screenshot_20200116-114754_AndroidAPS](https://user-images.githubusercontent.com/12038874/72518754-4093ea80-3856-11ea-9391-20bf0182d729.jpg)

**Comment by MilosKozak** [comment]
will be resolved in RC6
