### ISSUE TITLE
[2.6 RC5] ActionsTab, fill_dialog 

### ISSUE THREAD

**Issue by lutzlukesch** [MilosKozak/AndroidAPS#2369]
If you check both items: siteChange and insulinChange only insulin change is recorded. 

Dialog shows both but registered is only the insulinChange.

If only one item  is checked siteChange xor insulinChange it works.

![IMG_0843](https://user-images.githubusercontent.com/15966098/72510218-518a2f00-3849-11ea-8977-fce4904ffeab.jpeg)
![IMG_0845](https://user-images.githubusercontent.com/15966098/72510328-89917200-3849-11ea-8269-8c7e1f91a352.jpeg)
![IMG_0846](https://user-images.githubusercontent.com/15966098/72510397-a7f76d80-3849-11ea-88ad-a69c84b229a8.jpeg)

**Comment by guydavies** [comment]
For me, it always takes a few seconds longer for the Katheteralter (Site Change in the English language file) to update but it does change.  I went back and re-entered the Site Change initially but it's not required (for me).  I noticed this with earlier 2.6_RCn releases.

**Comment by Alamo04** [comment]
Confirmed, 
but in my system only Site Change was updated, Insulinage was not.
