### ISSUE TITLE
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION

### ISSUE THREAD

**Issue by kskandispersonal** [MilosKozak/AndroidAPS#237]
I get this when trying to install the fullNowearDebug build via AS.  I also have xDrip+ and HAPP installed.

adb -s 49cdc2d1 install -r app/build/outputs/apk/app-full-nowear-debug.apk
app/build/outputs/apk/app-full-nowear-debug.apk: 1 file pushed. 3.1 MB/s (10395689 bytes in 3.148s)
        pkg: /data/local/tmp/app-full-nowear-debug.apk
Failure [INSTALL_FAILED_DUPLICATE_PERMISSION perm=com.eveningoutpost.dexdrip.permissions.RECEIVE_EXTERNAL_
STATUSLINE pkg=com.hypodiabetic.happ]

**Comment by AdrianLxM** [comment]
Ah, I know where this is coming from. Thanks @kskandispersonal for reporting this

Both AndroidAPS and HAPP export the same permission to send statuslines.
In order for it to work, all 3 apps (aaps, happ, xdrip) must be built/signed by the same person. As NSClient is a restricted AndroidAPS and comes prebuilt with a different key than xDrip or HAPP this is not good.

xDrip should receive any broadcast of statuslines anyways - no matter if it was sent with permission or not. I think we can lose the permission: as far as I understand it, it only means, 

Here is a PR that removes the permission form AndroidAPS: https://github.com/MilosKozak/AndroidAPS/pull/238

Thanks, cheers, Adrian

**Comment by kskandispersonal** [comment]
This worked for me, too.  Thanks!
