### ISSUE TITLE
[2.6 RC5] [2.6.0] Bolus not considered in IOB (wizzard with future carbs)

### ISSUE THREAD

**Issue by tKostka** [MilosKozak/AndroidAPS#2379]
AAPS forgets (or did not notice) the Insulin given with wizzard. This happend the second time.

17.01. 21:02 - Used wizzard for a 70g meal, calculated bolus was given by pump, also progress bar in AAPS shows giving the bolus.
17.01. 21:35 - I've noticed several SMBs given and therefore took a look at AAPS to see the reason for that. IOB was too smal, the bolus from 21:02 was not considerd in IOB, graph or treatments tab.
After forced close (via Android Settings) and restart of AAPS, IOB was correct.

The screenshots where made before and after AAPS restart and show different IOBs and difference in treatment tab.

Setup:
AAPS 2.6 RC5
OnePlus 7T / Android 10
Accu-Chek Combo
xDrip+ / Dexcom G5 non-native
NS client in AAPS is set to upload only

[AndroidAPS_LOG_1579293508632.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4080682/AndroidAPS_LOG_1579293508632.log.zip)
![Screenshot_20200117-213552](https://user-images.githubusercontent.com/11375777/72663918-1a0db500-39f8-11ea-8692-9fd98c541459.jpg)
![Screenshot_20200117-213559](https://user-images.githubusercontent.com/11375777/72663919-1a0db500-39f8-11ea-8d01-fbefa2eedac4.jpg)
![Screenshot_20200117-213705](https://user-images.githubusercontent.com/11375777/72663920-1a0db500-39f8-11ea-8b79-23f22326bc46.jpg)
![Screenshot_20200117-213714](https://user-images.githubusercontent.com/11375777/72663922-1aa64b80-39f8-11ea-9d55-41918b6ba0d4.jpg)
![Screenshot_20200117-213722](https://user-images.githubusercontent.com/11375777/72663923-1b3ee200-39f8-11ea-9201-4d9708f579ae.jpg)

**Comment by tKostka** [comment]
Happened again, the last bolus (1.9 - 17:51) not in  treatments. After restart ok again.

![Screenshot_20200118-180858](https://user-images.githubusercontent.com/11375777/72667644-60760a80-3a1e-11ea-9645-193acd74ea34.jpg)
![Screenshot_20200118-180848](https://user-images.githubusercontent.com/11375777/72667645-60760a80-3a1e-11ea-9d20-ce08e4e68b37.jpg)

**Comment by tKostka** [comment]
Happens 1-2 times per day. Not sure, but maybe it only happens with time offset in wizzard (using wizzard for a meal in past or future). Am i really the only one with this problem? I'm back at 2.5.1 for the moment.

**Comment by tKostka** [comment]
Seems to be a duplicate to #2311 
Sorry, have not seen it before.

**Comment by MilosKozak** [comment]
i'm unable to reproduce this bug even with combo
I added at least an ugly patch to eliminate IOB impact
https://github.com/MilosKozak/AndroidAPS/commit/6c23cb1d2933ccb3935e27b414dd9e5d79ec4d1b

**Comment by tKostka** [comment]
Problem still exists with 2.6 RC7. 
Wizzard used at 14:17 for 60g carbs (set 10 minutes in future), 6.4 IE Bolus given.
AAPS forgets the 6.4 IE and therefore gives too much Insulin via SMB. After restart AAPS reads Combo history and Bolus is correct again. Last screenshot was made after downgrade to 2.5.1. 

How can i help to reproduce or provide more data? I can't use the 2.6 Versions, 2.5.1 is working perfect.

[AndroidAPS._2020-02-08_15-02-54_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4208579/AndroidAPS._2020-02-08_15-02-54_.0.zip)

![Screenshot_20200208-145756](https://user-images.githubusercontent.com/11375777/74589675-87b4fd00-5007-11ea-983f-0cdac85ecf96.jpg)
![Screenshot_20200208-145813](https://user-images.githubusercontent.com/11375777/74589678-8be11a80-5007-11ea-81e1-2c7195c52fe8.jpg)
![Screenshot_20200208-145904](https://user-images.githubusercontent.com/11375777/74589680-90a5ce80-5007-11ea-81b5-5b37f056468d.jpg)
![Screenshot_20200208-145910](https://user-images.githubusercontent.com/11375777/74589681-926f9200-5007-11ea-9535-37a7078cdcef.jpg)
![Screenshot_20200208-145937](https://user-images.githubusercontent.com/11375777/74589682-97344600-5007-11ea-9781-b8ea1f14fc09.jpg)
![Screenshot_20200208-150127](https://user-images.githubusercontent.com/11375777/74589685-9c919080-5007-11ea-988c-0cc729c3c4f0.jpg)
![Screenshot_20200208-151650](https://user-images.githubusercontent.com/11375777/74589690-a0251780-5007-11ea-83f0-63cc8a943f69.jpg)

**Comment by tKostka** [comment]
Retested with latest dev compiled today. Error still there. It seems to happen everytime i use wizzard with carbs in future, then only carbs are saved in AAPS but not the bolus (but still shown in Combo tab).

**Comment by tKostka** [comment]
Still the same with 2.6.0. Easy to reproduce, happens every time when using future carbs in wizzard.

**Comment by tKostka** [comment]
Closed as duplicate, to be tracked in the more public discussed issue #2469
