### ISSUE TITLE
[2.6-dev] Setting Automation Time Range to 00:00 changes the value to 18:00

### ISSUE THREAD

**Issue by stevebell117** [MilosKozak/AndroidAPS#2381]
As the title says, when setting up a new Automation condition, if `Time Range` is set to 00:00 to XX:YY, when the condition is finalized the `Time Range` is _actually_ set to 18:00 to XX:YY. Setting the `Time Range` to 00:01 avoids this behavior.

**Comment by PoweRGbg** [comment]
Which Timezone is your phone in ?

**Comment by stevebell117** [comment]
@PoweRGbg CST

**Comment by stevebell117** [comment]
This was resolved by PR#2384
