### ISSUE TITLE
[2.6 RC5] version update message even though engineering mode

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#2382]
I'm testing 2.6 RC5 in engineering mode and every day the error message "new version..." is shown although there is no new version available.
![20200118_114716](https://user-images.githubusercontent.com/37514390/72719107-7ea34e00-3b77-11ea-9bb7-3aaec6fb9c5c.jpg)

**Comment by MilosKozak** [comment]
did this happen again with RC6?

**Comment by thomasmenges** [comment]
Problem seems to be solved in RC6
