### ISSUE TITLE
[2.6RC5] Wrong record in Treatment Tab (Meals entered from Calculator are recorded as SMB)

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2383]
Previsouly all Carbs entered for meal was shown in graph with a big green point...

Now I haven't Carb since I upgrade AAPS in 2.6RC5 and bolus point is not at the right place in graph...
I took my meal at 21:10
The 2 small blue points in watchface are ok (SMB)
but big point for Bolus is too late in graph and carb point is missing

![screen 28](https://user-images.githubusercontent.com/52934600/72760229-5f88d880-3bd8-11ea-9164-559043bc7655.png)
![screen 29](https://user-images.githubusercontent.com/52934600/72760467-213fe900-3bd9-11ea-9ae1-05090ea21e77.png)

![Screenshot_20200120-230202_AndroidAPS](https://user-images.githubusercontent.com/52934600/72760499-3f0d4e00-3bd9-11ea-9349-eb3ad14bbea2.jpg)

With improved AAPSv2 interface it's the same (Carbs are in orange colors)
![screen 30](https://user-images.githubusercontent.com/52934600/72760877-7defd380-3bda-11ea-83ff-4ac316b61862.png)

And in a previous screenshot I had :
![screen 24](https://user-images.githubusercontent.com/52934600/72760903-8cd68600-3bda-11ea-8415-42ad419976dd.png)

**Comment by Philoul** [comment]
In Treatment tab I think informations are not correctly recorded:

Meal entered from watch are recorded as SMB (12:30 and 21:10) and one SMB is recorded as Corr (22:30)

![Screenshot_20200120-233837_AndroidAPS](https://user-images.githubusercontent.com/52934600/72762074-906c0c00-3bde-11ea-886e-cac7c26431ba.jpg)

**Comment by Philoul** [comment]
The problem comes from wrong entry in Treatment tab:
This morning I use calculator in AAPS (2.6-RC5) to enter my breakfast at 07:12
=> Recorded as SMB in Treatment Tab (and no "Calc" link to see detailled calculation)

I made a downgrade of AAPS to 2.6-RC2 at 11:20 and I entered 5g of Carbs from calculator at 11:24
Recorded as "Meal" with "Calc" Link

Then I entered my lunch from watch (wizard) at 12:30 and it's also Ok (Meal with Calc link) with ...

![Screenshot_20200121-211112_AndroidAPS](https://user-images.githubusercontent.com/52934600/72840002-a5ef3d80-3c93-11ea-99da-f6500f9a2902.jpg)

**Comment by MilosKozak** [comment]
provide logs when this happen

**Comment by Philoul** [comment]
Excuse me for forgetting...

With 2.6RC5, 2 meals entered from watch and recorded as SMB in Treatment Tab:
[AndroidAPS._2020-01-20_00-00-00_.8 - 12h30 meal from watch as SMB.zip](https://github.com/MilosKozak/AndroidAPS/files/4105106/AndroidAPS._2020-01-20_00-00-00_.8.-.12h30.meal.from.watch.as.SMB.zip)
[AndroidAPS._2020-01-20_00-00-00_.11 - 21h10 meal from watch as SMB.zip](https://github.com/MilosKozak/AndroidAPS/files/4105108/AndroidAPS._2020-01-20_00-00-00_.11.-.21h10.meal.from.watch.as.SMB.zip)
For SMB recorded as "Corr" at 22h30, I do not know if it is in Log above or below
[AndroidAPS._2020-01-20_22-38-30_.0 - 22h30.zip](https://github.com/MilosKozak/AndroidAPS/files/4105112/AndroidAPS._2020-01-20_22-38-30_.0.-.22h30.zip)

Breakfast from calculator recorded as SMB in Treatment Tab (2.6RC5)
[AndroidAPS._2020-01-21_00-00-00_.1 7h12 breakfast from calculator as SMB.zip](https://github.com/MilosKozak/AndroidAPS/files/4105121/AndroidAPS._2020-01-21_00-00-00_.1.7h12.breakfast.from.calculator.as.SMB.zip)

I made Downgrade from 2.6RC5 to 2.6RC2 at 11h20 and then entered from calculator 5g Carbs at 11h24
[AndroidAPS._2020-01-21_11-19-42_.0 11h24 Meal after downgrade 2.6RC2 done at 11h20.zip](https://github.com/MilosKozak/AndroidAPS/files/4105144/AndroidAPS._2020-01-21_11-19-42_.0.11h24.Meal.after.downgrade.2.6RC2.done.at.11h20.zip)

**Comment by MilosKozak** [comment]
[AndroidAPS._2020-01-20_00-00-00_.txt](https://github.com/MilosKozak/AndroidAPS/files/4111791/AndroidAPS._2020-01-20_00-00-00_.txt)

@TebbeUbben do you have explanation for this?
time: 21:10:18.621

**Comment by Philoul** [comment]
Is this issue still being analysed?
on my side, I got it once when I installed the RC5 fron the RC2. 
Since then, I have made several version switches (RC2-RC6-RC2-RC7-RC5-Dev-RC2) and I have not reproduced it (currently the reference version that I use the most to make the functional comparisons is RC2).
Maybe we can close this issue...
