### ISSUE TITLE
[2.5.1] eating bolus not only shows twice, but also delivers twice

### ISSUE THREAD

**Issue by DiaWreckingball** [MilosKozak/AndroidAPS#2385]
Reporting bugs
--------------
- **23.01.2020 at 18:38 and 18:50** 
Using the calculator and clicking "ok" and the it shows it was waiting for the pump for about 1-1.5 minutes then started the bolus. It showed that it delivered twice. 
I knew about the bug, which showed it delivers twice but in reality doesn't. 
After some time I fell into severe hypoglycemia, even after eating ~100 - 120g carbohydrates.

- Build: eb98ca765-2019.12.03-20:17

- 

> 
[AndroidAPS_LOG_1579812686196.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4105650/AndroidAPS_LOG_1579812686196.log.zip)

**Comment by DiaWreckingball** [comment]
@MilosKozak as you asked in Facebook.
Thank you :-)

**Comment by andyrozman** [comment]
There is nothing in the logs, and you forgot to add snapshots of Treatments tabs... I need to see the logs to determine what was happening...

There is no code, that would actually start bolus twice... Are you sure you didn't dose yourself twice by mistake?
