### ISSUE TITLE
[2.6] Carb entries disappear in some cases

### ISSUE THREAD

**Issue by rustymonkey** [MilosKozak/AndroidAPS#2386]
Noticed a situation with 2.6 RC6 (Samsung S7/Android 8.0/Medtronic 554) in which a carb entry was made, insulin given, but AAPS failed to log the carb entries. Steps:
1 Make ecarb entry (duration 1hr)
2 Use the calculator to give a partial upfront bolus (based on the above entry)
--> 1.7U of insulin is dosed
--> treatment/eCarbs appear in nightscout
--> treatment appears in AAPS but Carbs don't (in COB, in the graph or in Treatments)!

Note: the boluses were logged accurately--here's the bolus history hand-copied from the pump:
6:37 .1
6:53 .1
6:59 .1
7:02 .1
7:17 .1
7:22 .1
7:27 .1
7:53 .1
7:53 1.7
8:33 .1
8:37 .3
8:53 .5

![Screenshot_AndroidAPS_home](https://user-images.githubusercontent.com/34991028/73042925-0ff11980-3e31-11ea-9e58-a740816e3652.jpg)
![Screenshot_AndroidAPS_treatments](https://user-images.githubusercontent.com/34991028/73042932-1384a080-3e31-11ea-99c9-f02fa259c7a8.jpg)
![Screenshot_xDrip+](https://user-images.githubusercontent.com/34991028/73042938-18e1eb00-3e31-11ea-8575-2785df695b4d.jpg)
![Screenshot_Nightscout](https://user-images.githubusercontent.com/34991028/73042964-3747e680-3e31-11ea-9f8d-cd76a335fe0f.jpg)
[AndroidAPS_LOG_1579831121849.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4106730/AndroidAPS_LOG_1579831121849.log.zip)

**Comment by MilosKozak** [comment]
your NS is malfuctioning.
clear database and maybe remove treatment collection

**Comment by rustymonkey** [comment]
I'm using a local profile and SMS Communicator is disabled. So even if NS is completely non-functional and/or has incorrect entries, why should that have any impact on the local database and cause AAPS to lose carb entries / not treat the carb entry?

**Comment by rustymonkey** [comment]
In case anyone else experiences this issue, Milos clarified that I had two-way synchronization enabled for nightscout, so any errors in nightscout propagated back to AAPS. The solution is to disable two-way sync in NS Client config > advanced settings.
