### ISSUE TITLE
[2.6RC5] Cannula change in new actions tab will only log reservoir or cannula change although both a selected.

### ISSUE THREAD

**Issue by tanja3981** [MilosKozak/AndroidAPS#2387]
On entering a cannula change in the actions tab, I tick "cannula change" and "reservoir change" and press OK.
Only the first selected item will be logged in careportal and only the time for the corresponding age is updated in the actions tab,

![image](https://user-images.githubusercontent.com/7403966/73068661-0c4ea880-3eac-11ea-88c0-4548b4cca21e.png)

![Screenshot_20200124-131407](https://user-images.githubusercontent.com/7403966/73068518-ba0d8780-3eab-11ea-8b6c-d466b10db7e4.png)

![Screenshot_20200124-131420](https://user-images.githubusercontent.com/7403966/73068530-bf6ad200-3eab-11ea-9cd4-d49cb1bf4a97.png)

**Comment by jotomo** [comment]
Duplicate of #2369, #2374
Will be fixed via #2373 - tests from others confirming the PR works are welcome.

**Comment by tanja3981** [comment]
@jotomo Tested PR #2373 and it's fixed, thank you!
