### ISSUE TITLE
[2.6 latest Dev (25.01.2020) and also RC4, RC5] Calculator was still broken

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2388]
Still using 2.6 RC2 because all versions with new layout have broken the calculator.

Did test every new version, with hope that it is fixed, last was from today 25.01.2020 03:15AM because it should be fixed in that. It's not.

Still the same issue:
Give over calculator 7,6U Bolus and enter 80g carbs with a 20 minutes delay.
Everything works fine in AAPS, but in NightScout only the carbs and IOB are changed. 
No entry for the Bolus.

If AAPS now update the entrys from NS, the Bolus was also deleted in AAPS. 
After that also IOB was wrong and without that bolus.

Attaced:
3 Scrennshots from AAPS and NightScout
1 Log file (with default Log Settings)

**Comment by Alamo04** [comment]
Uploads:
![Screenshot_20200125-130515_AndroidAPS](https://user-images.githubusercontent.com/36486505/73121951-1097c600-3f7f-11ea-91c7-578c6bfd3b25.jpg)
![Screenshot_20200125-124927_AndroidAPS](https://user-images.githubusercontent.com/36486505/73121953-14c3e380-3f7f-11ea-87f0-b18d3196eb15.jpg)
![Screenshot_20200125-124916_Opera](https://user-images.githubusercontent.com/36486505/73121954-17263d80-3f7f-11ea-99e2-531d9d1f3d6b.jpg)
[AndroidAPS_LOG_1579953104428.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4112060/AndroidAPS_LOG_1579953104428.log.zip)

**Comment by Alamo04** [comment]
[AndroidAPS_LOG_1579953104428.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4112061/AndroidAPS_LOG_1579953104428.log.zip)

**Comment by MilosKozak** [comment]
reset your database and try again

**Comment by MilosKozak** [comment]
another fix pushed to dev

**Comment by Alamo04** [comment]
First test with small values 2,1 I/E and 12g carbs 15 minutes later works correct. 
Test with normal meal bolus followed tomorrow. 
Will report then.

Thanks for your work Milos.

**Comment by Alamo04** [comment]
@MilosKozak 
Test with normal meal works also correct now, but I have a new bug.
Low/High Alarm is not cancelable, must shutdown phone to get it silence. 
Then I have to wait until my numbers are in "No Alarm" Range, before restart the phone and AAPS.

Only the Sound comes up, no messages or buttons.

Will create a new Bug report for it, so you can close this issue after reading.
