### ISSUE TITLE
Some state exists where TT (particularly hypo) is deleted ~30sec after setting in RC5 

### ISSUE THREAD

**Issue by PedanticAvenger** [MilosKozak/AndroidAPS#2389]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
Multiple times during night (Jan 25), was low, took carb dose and set hypo TT. Shortly later reawoken with another low due to smb dosing during rise previously. Redosed carbs, set another hypo TT and this time noticed it just vanished a moment later. Tried setting multiple times to no effect. Finally went to treatments, refreshed from NS (which removed a lot of canceled from list and replaced with list of actions I had actually set) whereupon the TT was restored as desired then operated as expected. 
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner)
C03f874bd-2020. 01.23-10:07 (rc5) 
- Obtain the app's log files, which can be found on the phone in
  Will be attached along with screencaps.

**Comment by PedanticAvenger** [comment]
![Screenshot_20200125-061102](https://user-images.githubusercontent.com/15637097/73122952-a31c7300-3f47-11ea-910c-4afc42c67949.jpg)
Set hypo
![Screenshot_20200125-061130](https://user-images.githubusercontent.com/15637097/73122957-a9aaea80-3f47-11ea-8f54-519aab0e2445.jpg)
30 sec later
![Screenshot_20200125-061230](https://user-images.githubusercontent.com/15637097/73122959-b0396200-3f47-11ea-8726-aaa22883f463.jpg)
After sync w/ NS in treatments.

**Comment by PedanticAvenger** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4112139/AndroidAPS.log)

**Comment by MilosKozak** [comment]
yes cancel is comming from NS after you create TT

**Comment by PedanticAvenger** [comment]
Did it again, screenshots of treatments.
![Screenshot_20200125-140512](https://user-images.githubusercontent.com/15637097/73127804-5eaec880-3f83-11ea-8da4-ff78d5de67d1.jpg)

![Screenshot_20200125-140553](https://user-images.githubusercontent.com/15637097/73127809-68383080-3f83-11ea-8693-2989a16da77a.jpg)

**Comment by PedanticAvenger** [comment]
Is it coming from NS or is nsclient doing something screwy? Given the cancel disappears upon refreshing from NS.

**Comment by MilosKozak** [comment]
it's not visible from logs.

**Comment by PedanticAvenger** [comment]
Would a higher level of debug somewhere help? Seems i can still reproduce.

**Comment by MilosKozak** [comment]
disconnect from NS

**Comment by PedanticAvenger** [comment]
Issue disappeared with RC6
