### ISSUE TITLE
2.6 RC6 UI layout problem

### ISSUE THREAD

**Issue by libxmike** [MilosKozak/AndroidAPS#2393]
almost half of the display gray, see screenshot
OP6, Android 10
![Screen Shot 2020-01-26 at 11 40 15 AM](https://user-images.githubusercontent.com/16604543/73133991-16e67a80-4031-11ea-8adf-c8c69489960e.png)

**Comment by MilosKozak** [comment]
it's by design now

**Comment by libxmike** [comment]
> it's by design now

by design? what design?
