### ISSUE TITLE
2.6 RC6 bolus delivery background not visible anymore (is not translucent)

### ISSUE THREAD

**Issue by libxmike** [MilosKozak/AndroidAPS#2394]
in RC6 and previous release the background goes black while delivering bolus which distract the view of current IOB/COB which maybe crucial info if one wants to make sure did not make mistake and overestimated the bolus, should be changed to transfused (no 100% but maybe 80% as previous like in RC2?) 

![Screen Shot 2020-01-26 at 11 47 23 AM](https://user-images.githubusercontent.com/16604543/73134027-ab50dd00-4031-11ea-8265-1019c60a47af.png)

this is 2.5/2.6 RC2
![Screen Shot 2020-01-26 at 11 48 11 AM](https://user-images.githubusercontent.com/16604543/73134038-ce7b8c80-4031-11ea-99d6-bf8a6a09affe.png)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/dad36ed6a0fe4a56a692a424528718a1e3bfc8c6
