### ISSUE TITLE
[2.6 RC6] Graph doesn't get auto-scaled vertically

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2395]
Seen on different users/devices, same in landscape.

![Screenshot_AndroidAPS_20200126-095709](https://user-images.githubusercontent.com/38337079/73134289-25cf2c00-4035-11ea-8bf3-8694af5cbf87.png)

**Comment by MilosKozak** [comment]
it's by design

**Comment by goomStar** [comment]
Just to be sure... the difference in readability between those two is intentional?

![Screenshot_AndroidAPS_20200126-000917](https://user-images.githubusercontent.com/38337079/73138658-a4dc5880-4065-11ea-87c5-eead124904eb.png)
![Screenshot_AndroidAPS_20200122-014924](https://user-images.githubusercontent.com/38337079/73138659-a4dc5880-4065-11ea-92af-a1790b652932.png)
