### ISSUE TITLE
[2.6 RC6 and actual dev] Low/High Alarm gives only Sound, no messages, or buttons to cancel the alarm

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2396]
Low/High Alarm is not cancelable, must shutdown phone to get it silence. 
Then I have to wait until my numbers are in "No Alarm" Range, before restart the phone and AAPS.

Only the Sound comes up, no messages or buttons.

**Comment by Alamo04** [comment]
[AndroidAPS_LOG_1580055095610.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4113682/AndroidAPS_LOG_1580055095610.log.zip)

**Comment by MilosKozak** [comment]
what low/high alarm?

**Comment by MilosKozak** [comment]
no sign of crash in logs

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/404bf7e633fd7ab94cffe6a56a7314511246939c

**Comment by Alamo04** [comment]
Works thanks.

**Comment by jamespaulley** [comment]
I get a similar thing with connection to Dana pump interrupted alarms. Sometimes if connection gets interrupted during a bolus a horrible urgent ala sounds and there is no way to silence it apart from force stopping aaps. Sometimes there is a dialogue to me the alarm, but not always
