### ISSUE TITLE
[Feature request] Export to

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2398]
What
- add new option of preferences export - export to

Why 
- simplify the persistance / backup / import of settings 
- actual export forces casual users to install unnecessary app accessing root folder

**Comment by MilosKozak** [comment]
so i don't understand why you need to install any app

**Comment by pmisun** [comment]
@MilosKozak - not all default phone file exploders are capable to access default export location, you need ess file exploder or similar to be able access it...

**Comment by MilosKozak** [comment]
it's available even via browsing from PC.
I think it's not necessary to change it.
closing this issue
