### ISSUE TITLE
[2.6 RC6] Bug (minor)- allowance to set sms bolus delay below 15

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2399]
Once user adds 2nd number to SMS commands, is allowed to change limit between 2 boluses delay. 

Problem is, that user can set this value below 15, but actally its hard-limited to minimum of 15mins (tested with 10 minutes defined)

Nice to have: enable delay redefinition even for 1 number entered.

**Comment by MilosKozak** [comment]
if you set 2 numbers it's possible to lower the value to 3 min.
 otherwise 15 min is low limit

**Comment by pmisun** [comment]
@MilosKozak so itsnot working, having printscreens only from commands and setup, will ulload

**Comment by pmisun** [comment]
Ok, so this was not working then. Ive set the limit to 10 minutes delay, and it was allowed after 15 - see times at psc 
![Screenshot_20200127-093321_Messages](https://user-images.githubusercontent.com/12038874/73160039-41473f00-40e8-11ea-9535-945c5ae79637.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/128547d1a5d7a9736fcc0dbc197b010c9d45fce3
thanks
