### ISSUE TITLE
2.6 RC6 temporary basal rate not shown

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2400]
Insight pump, temp basal rate not shown on main screen.  Always use absolute basal values is NOT turned on.  Now it's changed to an 80% tbr it is showing, but when 0 % it wasn't.

![Screenshot_20200127-112735](https://user-images.githubusercontent.com/30231246/73172161-4b723900-40fa-11ea-89e9-07a9f151e341.png)
![Screenshot_20200127-112748](https://user-images.githubusercontent.com/30231246/73172162-4b723900-40fa-11ea-9e54-eee60c9415f2.png)

**Comment by MilosKozak** [comment]
pump?
screenshot of TBR in treatments?

**Comment by ShaggydogUK** [comment]
Sorry, missed tbr in treatments, I'll get it if it happens again.  Pump is Insight.  Images now correct!

**Comment by ShaggydogUK** [comment]
Treatmens

![Screenshot_20200127-114840](https://user-images.githubusercontent.com/30231246/73172518-1c0ffc00-40fb-11ea-9b3b-5e83f98f4780.png)

**Comment by ShaggydogUK** [comment]
![Screenshot_20200127-115206](https://user-images.githubusercontent.com/30231246/73172710-8aed5500-40fb-11ea-84ee-45b83b8fa0c9.png)

**Comment by MilosKozak** [comment]
next time make a picture of the pump as well

**Comment by ShaggydogUK** [comment]
Ok, sorry.   It showed a temp basal of 0% but I don't remember the time shown.
