### ISSUE TITLE
[feature request] Missing default setting for profile switch 

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2401]
As a safety feature I would like to have a default setting for the duration of a profile switch (like 1min or 30 min). 
Reason : if you forget to enter the duration for your profile switch it will stay active for undetermined hours... This could lead to a hypo in case of putting the profile above 100%. If you control your BG from the watch you won't see the active profile properly and maybe won't notice it... If you had to change the duration manually you would probably be more conscious about it. 
AAPS 2.5. 1

**Comment by MilosKozak** [comment]
What I have learned is you cannot protect people against themself.
And in this case if you don't watch, both is dangerous

**Comment by CaroGo** [comment]
You are absolutely right.... But I think it would be easy to change this... And if I can easily prevent people from making mistakes, I think we should do it!

**Comment by EknalpTiel** [comment]
@MilosKozak please reopen!
This ist a real safety relazed setting!

I prefer a explizit warning.

If the phone will be lost in the time a percentual profile switch ist active, He hast to reprogramm the Profile manually at the pump.

And if the user forget to set a time, this profile will also run over night.

I also recommend to add this in the objective questions.

**Comment by typ1-brods** [comment]
To prevent from a profile switch that is accidentally permanent, I would say a short hint would be helpful in this case (but not in case of a temp limited profile switch).

**Comment by AdrianLxM** [comment]
While I also don't think that setting a time as default would be the right thing, we should still read this as "there's a possibility for UX improvement when doing profile switches" for when we do a UI/UX sprint.

**Comment by CaroGo** [comment]
Another possible solution would be a quick pop up asking "do you really want to change your profile without determing duration?"  But I think, this would mean more code changing than just setting a default time... I would prefer the pop up solution though.

**Comment by twain47** [comment]
@CaroGo For hormone or illness related issues we regularly set a temp without a duration because we want it to run until we change it. We rarely set a temp with a duration because a high target is usually enough.

Given our usage I could just as easily suggest a popup for accidentally entering a duration :)

**Comment by AdrianLxM** [comment]
As de default case should always be without duration (it's a permanent profile), the non-default case with a duration should be the one highlighted, imho.
I then wonder if entering a time in not enough of a conscious action that we really need a warning like "Do you really want to change your profile only for a short period of time?"?

**Comment by twain47** [comment]
Sorry, to be clear I was playing devils advocate and illustrating a different usage of the system to show why the originally suggested change might cause problems, not advocating for an additional popup.

I entirely agree that entering a duration is unlikely to be done by accident.
