### ISSUE TITLE
[2.6 latest Dev (27.01.2020) and also RC4, RC5, RC6] Calculator was broken again after it was fixed in previous Dev version

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2403]
Same bug as before you fixed that in Dev from Jan 25, 2020 .
https://github.com/MilosKozak/AndroidAPS/issues/2388

After you fixed the Alarm Notification Bug, this calculator bug comes back. 

[AndroidAPS_LOG_1580128194901.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4118591/AndroidAPS_LOG_1580128194901.log.zip)

**Comment by MilosKozak** [comment]
time?

**Comment by Alamo04** [comment]
12:52 for Insulin13:07 for carbsCarbs are entered in NS, Insulin not.In AAPS everything looks good, if you do not update the NS treatments. In NS is only IOB correct shown, no treatment for insulin in graph and report.Am 27.01.2020 19:12 schrieb Milos Kozak <notifications@github.com>:time?

**Comment by MilosKozak** [comment]
Sorry i don't see how is it possible and i'm not able to replicate this bug
i created new branch with more logging. 
it will fail again but hopeffuly it will provide more info
https://github.com/MilosKozak/AndroidAPS/tree/nsuploadtest

provide logs when this happen again

**Comment by MilosKozak** [comment]
@Alamo04

**Comment by Alamo04** [comment]
Ok, will test it tomorrow evening, after work and will delete the Logfile before testing.
Give respond after that.

**Comment by Alamo04** [comment]
Here is the last clean log
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4121215/AndroidAPS.log)

**Comment by Alamo04** [comment]
unfortunately nsuploadtest doesn't fail. :(

**Comment by Alamo04** [comment]
Bug is fixed in installed Dev version from 02.02.2020 1:47 AM.
One test with big meal bolus works correct.

Will wait with closing this bug, because he is coming back with the next Dev version, as in the past.

**Comment by Alamo04** [comment]
RC7 is also ok, so I can close this issue.
