### ISSUE TITLE
[2.6 Rc4/5/6] Alarms not firing for Pump unreachable when timer expires.

### ISSUE THREAD

**Issue by PedanticAvenger** [MilosKozak/AndroidAPS#2407]
Build: 69c2532d4-2020.01.27-09:25
Phone: Oneplus 6 (Android 10)
Pump: Medtronic 722

Description:  On current and two previous rc builds, the alarm for pump unreachable never fires.  Verifying in the android notification settings no notification was ever sent.  Particularly problematic when pump goes fail safe in the middle of the night after a set of SMBs and a low occurs due to basal being re-established. My timer is currently set for 30 minutes.

Will re-create the issue again and upload logs.

**Comment by PedanticAvenger** [comment]
Ok, RL turned off at 9:15am (Mountain time), and no alarms anywhere right up until 10:15 when I turned it back on.

Log attached.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4129439/AndroidAPS.log)

**Comment by zehnBE** [comment]
i had the same, last connection 106 minutes ago, but no alert (dana r, android10, aaps dev).
The connection building "picture" shows trying since 71 seconds, so i think this brokes the trigger of alarm, that the connection counter was resettet.
I had not enough time to debug and look into the logs.

**Comment by PedanticAvenger** [comment]
Related: Alarms for failed bolus don't fire unless the app is active in foreground and screen on.

**Comment by MilosKozak** [comment]
it's new Android 10 feature.
I added fix to dev . At least phone starts ringing
