### ISSUE TITLE
[2.6 RC6] ui/minor "Closed loop" cz translation tab doublesized due break text

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2408]
![20200128_201927](https://user-images.githubusercontent.com/12038874/73297364-c4ad8100-420b-11ea-8ec4-235caf9cf4bf.jpg)

**Comment by MilosKozak** [comment]
???

**Comment by pmisun** [comment]
![20200128_223150](https://user-images.githubusercontent.com/12038874/73307265-27a81380-421e-11ea-9323-6abeb44515cd.jpg)


![20200128_223449](https://user-images.githubusercontent.com/12038874/73307425-79509e00-421e-11ea-88c7-7dfebd18b668.jpg)



It causes that the screen is moving with fingertouch up and down like scrollbar a little bit...

**Comment by pmisun** [comment]
@MilosKozak i would suggest to consider rather than make it again smaller to somehow educate users with this minimum screens dpi to set font smaller in phone settings. I just figured it out now its possible and its working, i understand this is time consuming, and, looking at 4 other bigger parental phones, the effect of scaling at this larger phones is creating too much of unused space by design. Soz itdidnt crossed my mind to rescale letters in phone settings earlier :(

**Comment by pmisun** [comment]
#2410 comment of mine applicable here too

**Comment by MilosKozak** [comment]
on smaller displays there will be break
