### ISSUE TITLE
[2.6 RC6] Prime/Fill action only seems to apply one of two checkbox actions.

### ISSUE THREAD

**Issue by PedanticAvenger** [MilosKozak/AndroidAPS#2409]
Build: 69c2532d4-2020.01.27-09:25
Phone: Oneplus 6 (Android 10)
Pump: Medtronic 722

Description:  When changing reservoir and infusion set, selecting both "Pump Site Change" and "Insulin Cartridge Change" does not reliably reset both Insulin and Canula Age in the Actions window.  Generally Canula age gets reset but I need to use the Prime/Fill action again to reset Insulin age.  Suspected NS sync timing issue but even when disabled this happens.

**Comment by MilosKozak** [comment]
provide logs with time of occurence

**Comment by PedanticAvenger** [comment]
Will recreate.  Last time was Sunday night and I only now got to logging it.

**Comment by PedanticAvenger** [comment]
Argh, put this on hold, recreating it last night (after it mis-behaved for at least the 3 previous resevoir/site changes) behaved correctly.  On further consideration I believe this is related to nightscout client possibly overwriting while this activity is happening.  I really don't want to turn off NS sync as I have a lot of shortcut buttons for different food and activity entries on my phone screen that are really useful that push directly to NS.

**Comment by PedanticAvenger** [comment]
Will re-open when/if recreate happens appropriately.
