### ISSUE TITLE
[2.6 RC6] UI minor : some text still over screen

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2410]
![20200128_224646](https://user-images.githubusercontent.com/12038874/73308535-c46bb080-4220-11ea-9f21-d27c48c4a7f4.jpg)

Soz having no better pic

**Comment by pmisun** [comment]
@MilosKozak i would suggest to consider rather than make it again smaller to somehow educate users with this minimum screens dpi to set font smaller in phone settings. I just figured it out now its possible and its working, i understand this is time consuming, and, looking at 4 other bigger parental phones, the effect of scaling at this larger phones is creating too much of unused space by design. Soz it didnt crossed my mind to rescale letters in small phone with android settings earlier :(

**Comment by pmisun** [comment]
Needed to adjust just 2 points down to result expected screen size


![20200128_230557](https://user-images.githubusercontent.com/12038874/73309597-d8b0ad00-4222-11ea-8b7a-e94f12561399.jpg)
![20200128_230613](https://user-images.githubusercontent.com/12038874/73309627-dd756100-4222-11ea-87e0-16298c515189.jpg)

**Comment by MilosKozak** [comment]
layout is now ConstraintLayout. it means i tell to Android what i need to have displayed and where (i.e. right of , under etc.). The rest is done by Android. This has an advantage of having it working all screen sizes but must not be perfect in some edge cases. For me better than different layout for every screen size

**Comment by guydavies** [comment]
hi @MilosKozak. I think the "corner cases" are more than than the "normal case". I have a large and a small phone and both are really unsatisfactory compared to pre-RC6 behaviour.
