### ISSUE TITLE
2.6 RC6 Wrong SMB administration

### ISSUE THREAD

**Issue by universe27** [MilosKozak/AndroidAPS#2412]
A SMB has been administered and should not. It doesn´t appear in the algorithm calculations (minGuardBG 34 <110)
Attached are the logs before and after the error (and photos)
[AndroidAPS._2020-01-28_20-26-29_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/4125548/AndroidAPS._2020-01-28_20-26-29_.4.zip)
[AndroidAPS._2020-01-28_20-26-29_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/4125549/AndroidAPS._2020-01-28_20-26-29_.3.zip)

![Screenshot_2020-01-28-22-02-07-467_info nightscout androidaps](https://user-images.githubusercontent.com/35197414/73317130-51206980-4235-11ea-8938-888c04968f3c.jpg)
![Screenshot_2020-01-28-22-01-27-362_info nightscout androidaps](https://user-images.githubusercontent.com/35197414/73317131-51b90000-4235-11ea-9149-bf7e2adec196.jpg)
![Screenshot_2020-01-28-22-01-12-703_info nightscout androidaps](https://user-images.githubusercontent.com/35197414/73317132-51b90000-4235-11ea-80cc-a4da4727c42f.jpg)

125541/AndroidAPS._2020-01-28_20-26-29_.3.zip)

**Comment by MilosKozak** [comment]
there were 2 runs of loop:
21:59:45 resulting in smb 0.1
and
21:59:46 with result displayed because of previous smb
so no bug, just page was not updated yet

**Comment by MilosKozak** [comment]
21:59:45.557 [RxCachedThreadScheduler-8] D/APS: [DetermineBasalAdapterSMBJS.invoke():145]: Result: {"temp":"absolute","bg":72,"tick":"+2","eventualBG":173,"insulinReq":0.21,"deliverAt":"2020-01-28T20:59:45.537Z","sensitivityRatio":1.04,"predBGs":{"IOB":[72,71,69,66,61,54,47,39,39,39,39,39,39],"ZT":[72,47,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[72,73,74,75,77,78,80,83,85,88,91,95,98,102,106,111,115,120,124,129,133,138,142,147,151,155,159,163,166,170,173,176,178,180,182,183,184,184,185,184,183,182,180,179,177,176,174,173],"UAM":[72,73,73,74,75,76,77,78,80,81,83,85,87,89,90,92,94,96,98,100,101,103,104,105,105,106,106,105,105,104,102,100,98,95,91,88,85,82,80,78,76,74,72,70,69,67,66,65]},"COB":36.58642857142856,"IOB":3.871,"reason":"COB: 36.58642857142856, Dev: 161, BGI: -25, ISF: 115, CR: 7.5, Target: 95, minPredBG 119, minGuardBG 69, IOBpredBG 39, COBpredBG 173, UAMpredBG 65;  insulinReq 0.21; setting 120m low temp of 0U/h. Microbolusing 0.1U. ","units":0.1,"rate":0,"duration":120}

**Comment by MilosKozak** [comment]
21:59:46.749 [RxCachedThreadScheduler-6] D/APS: [DetermineBasalAdapterSMBJS.invoke():145]: Result: {"temp":"absolute","bg":72,"tick":"+2","eventualBG":196,"insulinReq":0,"deliverAt":"2020-01-28T20:59:46.720Z","sensitivityRatio":1.04,"predBGs":{"IOB":[72,71,69,66,61,54,47,39,39,39,39,39,39],"ZT":[72,47,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[72,73,74,75,77,79,81,83,86,89,93,96,100,105,109,114,118,123,128,133,138,143,149,153,158,163,168,172,176,180,184,188,191,194,196,198,200,202,203,203,203,203,202,201,200,198,197,196],"UAM":[72,73,73,74,75,76,77,78,80,81,83,85,87,89,91,92,94,96,98,100,101,103,104,105,105,106,106,105,105,104,102,100,98,95,91,88,85,83,80,78,76,74,72,70,69,67,66,65]},"COB":36.58642857142856,"IOB":3.87,"reason":"COB: 36.58642857142856, Dev: 161, BGI: -25, ISF: 115, CR: 7.5, Target: 180, minPredBG 128, minGuardBG 69, IOBpredBG 39, COBpredBG 196, UAMpredBG 65; 12 add'l carbs req w/in 0m; minGuardBG 69<110","carbsReq":12,"duration":120,"rate":0}

**Comment by MilosKozak** [comment]
21:59:52.463 [RxCachedThreadScheduler-6] D/APS: [DetermineBasalAdapterSMBJS.invoke():145]: Result: {"temp":"absolute","bg":72,"tick":"+2","eventualBG":89,"insulinReq":0,"deliverAt":"2020-01-28T20:59:52.437Z","sensitivityRatio":1.04,"predBGs":{"IOB":[72,70,67,61,53,44,39,39,39,39,39,39,39],"ZT":[72,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[72,72,72,72,73,73,73,74,74,75,76,77,78,79,80,81,82,83,83,84,84,83,82,81,80,78,75,72,68,64,58,52,47,42,39],"UAM":[72,72,73,73,74,75,77,78,80,82,85,88,91,94,97,100,104,107,111,114,117,120,123,125,128,130,131,132,133,133,133,132,130,128,125,122,118,114,110,107,104,101,99,96,94,92,90,89]},"COB":36.58642857142856,"IOB":3.866,"reason":"COB: 36.58642857142856, Dev: 225, BGI: -36, ISF: 165, CR: 10.71, Target: 180, minPredBG 39, minGuardBG 34, IOBpredBG 39, COBpredBG 39, UAMpredBG 89; 24 add'l carbs req w/in 0m; minGuardBG 34<110","carbsReq":24,"duration":120,"rate":0}

**Comment by universe27** [comment]
Thanks a lot Milos!!!
