### ISSUE TITLE
[Dev 29.01.2020] Refresh Treat. from NS deletes everything from Graph

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2413]
Using latest DEV 3713f772d with xDrip 2020.01.26 I am facing some issues.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4127612/AndroidAPS.log)

**1 -** AAPS stop sending bolus/carbs info to xDrip my graph is clean and I didn't change nothing recently.

![Screenshot_20200129-104833_xDrip+](https://user-images.githubusercontent.com/608650/73351624-51e1eb80-4287-11ea-839b-067e1d6d6c9b.png)

**2 -** When I press Refresh Treatments from NS, it clears the List and the graph lose every info. I only can get it back after restart the phone. I also lose the info of active carbs.

After I press Refresh Treat.

![Screenshot_20200129-104655_AndroidAPS](https://user-images.githubusercontent.com/608650/73351781-a9805700-4287-11ea-9e6b-40fc9ea4dd31.png)

![Screenshot_20200129-104715_AndroidAPS](https://user-images.githubusercontent.com/608650/73351798-b2712880-4287-11ea-9702-508080cfb9a0.png)

After I restart the phone (compare the time between the screenshots)

![Screenshot_20200129-105407_AndroidAPS](https://user-images.githubusercontent.com/608650/73351860-cf0d6080-4287-11ea-8a6c-f490cf275aa0.png)

![Screenshot_20200129-105415_AndroidAPS](https://user-images.githubusercontent.com/608650/73351870-d46aab00-4287-11ea-9ec1-12445c5d8d81.png)

**Comment by parapenT1sta** [comment]
Start working after cleared NS Queue

**Comment by parapenT1sta** [comment]
But I am getting more itens on the queue
![Screenshot_20200129-120513_AndroidAPS](https://user-images.githubusercontent.com/608650/73355376-ef411d80-428f-11ea-8af9-51740102c491.png)

**Comment by MilosKozak** [comment]
refresh treatments deletes internal database and wait for data from NS. so i'd say it's expected behavior. data is back when you make NS working

**Comment by parapenT1sta** [comment]
> refresh treatments deletes internal database and waits for data from NS. so i'd say it's expected behavior. data is back when you make NS working

Thanks! My concern is about the COB go to 0 when I really have COB.
