### ISSUE TITLE
AAPS 2.6 RC6 - AndroidAPS Homescreen - time window is not grayed out when pump is disconnected

### ISSUE THREAD

**Issue by missmarple11** [MilosKozak/AndroidAPS#2418]
AAPS 2.6 - RC6 - Samsung A3 2017 
In all previous versions up to AAPS 2.5.1, the time window on the AAPS home screen was grayed out during the time the pump was disconnected from me.
So it was possible to see at first sight if the pump is disconnected or if it was because the blood sugar had changed abnormally.
It would be very helpful to see this further.

**Comment by goomStar** [comment]
Confirming this. Same behavior for me as in #2360.
No Graph entries for disconnecting, suspending,..

**Comment by MilosKozak** [comment]
provide steps you did , screenshots and logs

**Comment by missmarple11** [comment]
![Screenshot_20200131-145105_AndroidAPS](https://user-images.githubusercontent.com/39493767/73547086-906dd680-443e-11ea-919c-ad0b49223bdc.jpg)
![Screenshot_20200131-152154_AndroidAPS](https://user-images.githubusercontent.com/39493767/73547087-906dd680-443e-11ea-996a-801ed106e356.jpg)
Screenhots with Master 2.5.1
What I have done:
long touch on "Closed Loop" - disconnect pump selected for 30 minutes
Description:
While the pump is disconnected, a grey bar appears in the graph.
When the pump is reconnected, the grey bar remains visible for the time the pump was disconnected.

**With AAPS 2.6 RC6 the grey bar does not appear.**

**Comment by DM-LTR** [comment]
Same behaviour here with 2.6 rc5 and 2.6 rc6... Main graph remains without any change when pump is disconnected or loop is suspended... No grayed out sections appear (Galaxy S8 w Oreo)

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/73611603-bda7b980-45e3-11ea-8f72-a29ac4e01c39.png)
RC6
provide logs if you have troubles

**Comment by DM-LTR** [comment]
![Screenshot_20200202-183507_AndroidAPS](https://user-images.githubusercontent.com/43177472/73612317-0020c480-45eb-11ea-9706-87ab6d7957d1.jpg)
![Screenshot_20200202-183530_AndroidAPS](https://user-images.githubusercontent.com/43177472/73612320-06af3c00-45eb-11ea-8f9e-3b78c59eed03.jpg)
[AndroidAPS._2020-02-02_00-00-00_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4144804/AndroidAPS._2020-02-02_00-00-00_.2.zip)

**Comment by swissalpine** [comment]
Same here, latest dev.

**Comment by missmarple11** [comment]
![Screenshot_20200203-090943_AndroidAPS](https://user-images.githubusercontent.com/39493767/73671717-cbc10d00-46ab-11ea-91fe-b543f85e47fc.jpg)

**AAPS 2.6 RC6 - Samsung A3 2017 - Pump disconnected - no grey bar in the graphic**

**Comment by MilosKozak** [comment]
this is related to malfunctioning nsclient
NSClient is unable to upload data

**Comment by swissalpine** [comment]
No, not here. I have no problems with my NSClient, all treatments appears immediatly. But I see no gray if I suspend loop or disconnect pump.

**Comment by MilosKozak** [comment]
@swissalpine log?

**Comment by swissalpine** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4150139/AndroidAPS.log)
I choose disconnect 4-5 minutes ago, I see treatments in nightscout:
![image](https://user-images.githubusercontent.com/12517693/73689245-1a7f9e80-46ce-11ea-91fd-7394117aeb30.png)
![Screenshot_20200203-214302](https://user-images.githubusercontent.com/12517693/73689293-36834000-46ce-11ea-806e-0cc79ae07bdb.png)

**Comment by MilosKozak** [comment]
@swissalpine i don't see anything wrong in your log
anyway records were not written directly to DB which is fixed in dev now

**Comment by swissalpine** [comment]
Thank you!!!

**Comment by goomStar** [comment]
Seemes fixed for me in RC7 too, good job

**Comment by DM-LTR** [comment]
Confirmed. Fixed in RC7. Thank you devs!
