### ISSUE TITLE
[dev] Overview (Home) page is sized incorrectly on Pixel 3

### ISSUE THREAD

**Issue by stevebell117** [MilosKozak/AndroidAPS#2419]
Just installed the latest Dev and this is the overview tab, on my Pixel 3:

![Screenshot_20200130-190632](https://user-images.githubusercontent.com/8714307/73504090-d6219500-4393-11ea-81c1-784722dbb3b1.png)

I'll be reverting for the time being.

**Comment by guydavies** [comment]
if you're. complaining about the gap at the bottom, Milos has done that on purpose. the scaling has been turned off so the size of the graphs is fixed, which isn't great for the larger or smaller phones available today. there don't seem to be lots of medium sized phones on which this looks great.
