### ISSUE TITLE
[2.6 Rc6 / 2.5.1] Bug: Bolus restriction of teen profile persistance from child profile

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2420]
Tried with 2.5.1 and also 2.6 RC6.

After remission ended need of insulin raised rapidly, however the calculator is persisting the 2U limit after changing the profile from kid to teen.
The limit is set to 3U in preferences..

![Screenshot_20200131-063928_AndroidAPS](https://user-images.githubusercontent.com/12038874/73515278-0c433100-43f5-11ea-9231-ea234324e9c0.jpg)
![Screenshot_20200131-063900_AndroidAPS](https://user-images.githubusercontent.com/12038874/73515285-1107e500-43f5-11ea-9e6e-87c0faba69cd.jpg)
![Screenshot_20200131-063948_AndroidAPS](https://user-images.githubusercontent.com/12038874/73515289-15340280-43f5-11ea-950e-c3eed58e077c.jpg)

**Comment by MilosKozak** [comment]
this is correct. so you have limit in pump

**Comment by pmisun** [comment]
:dancing_men: solved, thanks!!!
