### ISSUE TITLE
NSClient performs its own IOB/COB calculations instead of mirroring already calculated data uploaded to NS.

### ISSUE THREAD

**Issue by musicman0329** [MilosKozak/AndroidAPS#2425]
- Problem is ongoing, but screenshots are specifically from 11:36am on 2/2/2020, and 12:35pm on 2/3/2020. The issue is an IOB/COB mismatch between Nightscout and the NSClient app.

- Build version: c7e1338d6-2020.01.25-14:37
- Flavor: nsclient2release
- Nighscout version: 13.0

Since they are desired, I've attached the log files from my NSClient app that encompass the time frames shown by the screenshot below, however the issue seems to be related to the design of the NSClient app rather than a device issue.

Relevant log files from 2/2/2020 (saved as a txt file to upload here, original file extension = ".1")
[AndroidAPS._2020-02-02_00-00-00_.txt](https://github.com/MilosKozak/AndroidAPS/files/4150074/AndroidAPS._2020-02-02_00-00-00_.txt)

Relevant log files from 2/3/2020 (saved as a txt file to upload here, original file extension = ".1")
[AndroidAPS._2020-02-03_00-00-00_.txt](https://github.com/MilosKozak/AndroidAPS/files/4150082/AndroidAPS._2020-02-03_00-00-00_.txt)

------------
Issue references this thread in the AndroidAPS FB group...
https://www.facebook.com/groups/AndroidAPSUsers/permalink/2616961101858624/

To summarize, the AAPS documentation (right now) indicates that NSClient is intended to be used for remote monitoring and downloads all data (IOB/COB included) that is uploaded to NS by the master phone.

Relevant documentation link:
https://androidaps.readthedocs.io/en/latest/EN/Children/Children.html

It appears that this is not actually the current behavior of the NSClient app, which performs its own IOB/COB calculations based on the settings configured in each individual app instance. If these settings differ from the master phone (or OpenAPS rig, in my case) in any way, then the results of the calculations performed by the NSClient app will produce different results from the master phone, potentially leading to a life threatening situation if a remote caregiver treats based on the data displayed in the NSClient app. If NSClient isn't designed to echo the data that a "master" phone/device (AAPS, OAPS, etc)...but instead performs its own calculations (using potentially different settings than the "master" device) on the same set of data, then the possibilities of receiving incorrect information on the "follower" device running NSclient seem to be endless. 

Although the NSClient app cannot be used for remote bolusing, and bolusing should occur from the master phone (if using AAPS) or the pump (if using OAPS), it is still possible (for caregivers using NSClient to follow a master AAPS phone) to remotely bolus using SMS commands, change targets, and make other treatment decisions. The same applies to OpenAPS users, sans the SMS remote bolusing. Furthermore, the NSClient app can also function as an alternate interface for Nightscout's Careportal. If treatment decisions are being made based off of potentially inaccurate data, then that is very concerning.

These two screenshots show the mismatch in IOB.
![Screenshot_20200202-113622](https://user-images.githubusercontent.com/15910886/73687273-a62a0880-4697-11ea-920c-a9ce2054c575.png)
![Screenshot_20200202-113612](https://user-images.githubusercontent.com/15910886/73687274-a62a0880-4697-11ea-8927-641e70a1c289.png)

These two screenshots show the mismatch in COB  (as reported by the OpenAPS rig) and the COB reported by NSClient. They also illustrate the IOB issue as well. 
![Screenshot_20200203-123504](https://user-images.githubusercontent.com/15910886/73687336-c659c780-4697-11ea-8cdb-b9fadc7b4768.png)
![redacted NS site](https://user-images.githubusercontent.com/15910886/73687337-c659c780-4697-11ea-8ce1-72739838eb88.jpg)

It was mentioned in the FB thread that having NSClient perform calculations is beneficial for non-loopers. While this is true, I submit that the NSClient app should reflect (either by default or even as its sole purpose) the data uploaded to Nightscout by a looping system such as an AAPS master phone or an OAPS rig. This will eliminate confusion and help avoid potentially life threating situations if treatments are made based on the data displayed by the NSClient app acting as a follower (which could potentially differ greatly from the data uploaded to NS by the master device if the NSClient app settings are not identical to the "master" system in every way). 

I also opened a related issue in the AndroidAPS docs repo since the documentation for NSClient does not reflect its actual behavior, but will remove if desired to consolidate issue tracking.
https://github.com/openaps/AndroidAPSdocs/issues/739

**Comment by MilosKozak** [comment]
like you said NSClient perform own calculations to be able display graphs like you see in AAPS
it will never match master with different settings or different loop system (at least because of rouding)
but it display data from loop run the same way like NS
cob data may be late in NS by a few min because data is uploaded after loop run only

**Comment by musicman0329** [comment]
Right, if the settings are different between the master device and follower then then the calculated data will not match. The issue that I am bringing up is not that NSClient is having difficulties uploading/receiving IOB/COB to or from Nightscout, it is that the result of NSClient's IOB and COB calculations does not match what Nighscout shows from the uploader system if master/follower configurations do not match. And that could potentially be dangerous if the master/follower settings are not identical. Wouldn't it be safer to let the master perform the calculations, and have NSClient function as a follower by simply displaying the data as reported to NS by the master? The graphs and predictions, as best as I can tell, remain identical between NSClient and Nightscout. It is just the IOB and COB that differ.

**Comment by MilosKozak** [comment]
nsclient is still only different build of AAPS
what are you asking is different product.
maybe someone else will do it, but it's not possible with the code we have

**Comment by musicman0329** [comment]
I see...understood. In that case, the docs page for NSClient should probably be updated to reflect that IOB/COB displayed is not simply downloaded and shown "as-is" from NS?

**Comment by MilosKozak** [comment]
it's not possible. there is a huge difference between OAPS and AAPS.
OAPS calculates always data to "now" only and upload it to NS
AAPS calculates the same for 24 h history and display it in graphs. it's not possible to grab it from NS as it's not there
