### ISSUE TITLE
Add ability to upload to Tidepool

### ISSUE THREAD

**Issue by cascer1** [MilosKozak/AndroidAPS#2428]
I think it would be useful for AAPS to be able to upload data to Tidepool.

In my case I'm using the patched dexcom app, so my flow to upload to Tidepool is dexcom -> aaps -> xdrip -> tidepool. Unfortunately, this flow loses treatment information so Tidepool ends up only having BG data in it.

**Comment by MilosKozak** [comment]
the code is written, now we need Tidepool cooperation to finish it. Ask on their support

**Comment by cascer1** [comment]
Anything specific we should ask for?
