### ISSUE TITLE
[2.6 RC6] [BUG]  generating a temporary basal rate even though the loop is disabled

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#2430]
I want to make a new basal rate test. For this I disable loop.
The problem is that AAPS calculates temp basal rates which are shown in the overview and are although uploaded to NS.  (In the screenshot 0% temp basal is shown, a day before for example 200% are calculatet.
It is a good thing that these temp basal rates are not forced to the dana pump.

By the way --> automation is switched off !!!

For me it is a clear bug that temp basal rates are calculated during the time of switched off loop.
Also the calculation of IOB is wrong because the pump does not receive the temp rates but AAPS calculates with these values.

How can Loop completely switched off without working on in AAPS ???

![Inked20200204_231049_LI](https://user-images.githubusercontent.com/37514390/73828380-6da63e00-4801-11ea-9165-42280b69605e.jpg)

**Comment by thomasmenges** [comment]
In Nightscout you can see that the temp basal is uploaded and in the treatments the infos are shown

![Screenshot_20200205-103121_AndroidAPS](https://user-images.githubusercontent.com/37514390/73829500-5b2d0400-4803-11ea-9cd9-b7ae88495c2f.jpg)
![2020-02-05 10_27_30-Pdf](https://user-images.githubusercontent.com/37514390/73829517-608a4e80-4803-11ea-9307-2554b37119a7.png)

**Comment by MilosKozak** [comment]
you have to provide logfiles

**Comment by thomasmenges** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4164483/AndroidAPS.log)

**Comment by MilosKozak** [comment]
this is new log. i need the part with timeframe you're reporting bugs

**Comment by thomasmenges** [comment]
Sorry, was my mistake. Here is hopefully the correct logfile

[AndroidAPS._2020-02-05_00-00-00_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4166496/AndroidAPS._2020-02-05_00-00-00_.0.zip)

**Comment by MilosKozak** [comment]
this file is not caontaing ttime range we need
try to simulate this problem again then upload latest logs

**Comment by thomasmenges** [comment]
Error isn't be visible since 2.6.0 master and before RC7
