### ISSUE TITLE
[2.6 RC7] system window permission error always shown

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#2431]
After closing and starting AAPS 2.6 RC7 the error --> system window permission is shown. You can request the permission but the error occurs again after closing and opening the app AAPS RC7

![20200205_121915](https://user-images.githubusercontent.com/37514390/73837813-8bc86a00-4812-11ea-9c18-2be7a29ac9c6.jpg)

**Comment by Alamo04** [comment]
Confirmed

Had the same issue.
After asking for request, it comes back with every new start.

My Fix:
- I disable all app permissions and set them new.
- After restart AAPS the error comes up again, but after klicking on request, the error was gone.

**Comment by thomasmenges** [comment]
Did the same but on my phone (ATOM) the problem still occurs. Switching back to RC6 the problem is solved

**Comment by Philoul** [comment]
Same issue on my phone (Samsung A40)
And I don't know if it's linked but I also have layout problem on the bottom of main screen with a black unused area...

![Screenshot_20200205-201648_AndroidAPS](https://user-images.githubusercontent.com/52934600/73874864-8d1a8680-4854-11ea-9730-0b0e5920ed28.jpg)

**Comment by Alamo04** [comment]
Ok, the error comes back after 20 hours.
After click  on REQUEST it is gone again, think he comes back tomorrow.

**Comment by MilosKozak** [comment]
what android versions are you using?

**Comment by Philoul** [comment]
My android version is 9

**Comment by goomStar** [comment]
same for 8.1 RC7

**Comment by Alamo04** [comment]
My Android version is 8.0

**Comment by guydavies** [comment]
I get the same on Android 9 on a moto G7 power and on RR7.0.2 (AOSP9 based) on an old Moto G3 LTE

**Comment by thomasmenges** [comment]
My Android version is 8.1.0 on an Atom

**Comment by typ1-brods** [comment]
Samsung Galaxy S7 with Android 8.0.0, same issue. All permissions are given

**Comment by sailor-911** [comment]
Same issue on phone “Motorola one” with android 9: recurring demand for “request for system permit on app messaging”. 
All permissions are set. The message is also triggered immediately when I simply turn the phone into landscape mode. Comes always back.

**Comment by MilosKozak** [comment]
that's the bug. this is necessary only for android 10.
anyone tested android 10?

**Comment by MilosKozak** [comment]
resolved by https://github.com/MilosKozak/AndroidAPS/commit/42c2d89f987c8819c369940fad89d15568ade9db
