### ISSUE TITLE
[Dev] Medtronic pumps will NAK basals that are ok in the oAPS algorithm, but not the pump itself

### ISSUE THREAD

**Issue by stevebell117** [MilosKozak/AndroidAPS#2433]
This issue was found as a part of testing PR https://github.com/MilosKozak/AndroidAPS/pull/2228. There are currently two sections to set a "Max Basal Rate" in the Settings. One is used by the Medtronic Pump section, and the other is used by the oAPS algorithm section. If the oAPS algorithm has a higher "max basal allowed" than the Medtronic, it can try to send a basal that is higher than the pump allows. When this occurs, the pump sends a NAK which invalidates the basal, and the SMB afterwards, ignoring them. This can cause huge issues for rapid increasing deltas, as it essentially disables the loop.

The two sections that can be conflicted, but there doesn't seem to be a validation:
`OpenAPS SMB` -> `Max U/hr a Temp Basal can be set to` 
`Medtronic` -> `Max Basal on Pump (U/h)`

There are logs in the mentioned PR, and let me know if screenshots of the two settings are needed.

**Comment by andyrozman** [comment]
I don't see an issue here... 

There are two settings, so both settings need to be set. 

What do you expect the outcome of this ticket to be? 

Set both settings to same value and problem is solved. One settings is for algorithm and the other is for pump.

**Comment by stevebell117** [comment]
@andyrozman What's the point of having the setting in two places, if they're required to be the same value? As of now, if they're mismatched the loop breaks and insulin is cut off (until the temp basal runs out on it's own, then it remains at the programmed level). This is dangerous, as rising blood sugars aren't curtailed due to the loop breaking. 

There's no documentation (that I'm aware of) that these two need to be the same value, even if it seems like common sense to those extremely familiar with the system.

The desired outcome of this ticket would be to prevent this mismatch occurring in the first place, This could be done by a validation or removing the Medtronic setting and inheriting it from the algorithm.

**Comment by Tornado-Tim** [comment]
@stevebell117, there is a max allowed basal on every single pump supported.
Its not just applicable to MMT Pumps.

The max pump setting will simply constrain the amount the algorithm will recommend.
These values shouldn't need to be the same, can you explain in detail (with screenshots) of where the loop is breaking because of the two values being mismatched.

**Comment by stevebell117** [comment]
@Tornado-Tim Unfortunately I'm no longer looping with AAPS so I can't get you the info you require. The issue is that the algorithm suggests a value higher than the pump allows, so it throws an error and breaks the loop. The only info that's available is that which I posted in the original PR, which contains the log info showing the failures, etc.
