### ISSUE TITLE
[2.6 RC7] permanently basal profil upload information 

### ISSUE THREAD

**Issue by thomasmenges** [MilosKozak/AndroidAPS#2436]
Since using RC7 I get permanently the message that the basal profil has uploaded to the pump.

No profil switches are done but the message appears always on.

Attached is a screenshot of the message and the actual logfile 

![Inked20200206_183927_LI](https://user-images.githubusercontent.com/37514390/73966205-dc74bb80-4915-11ea-936d-4b2e651f1e9f.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4167055/AndroidAPS.log)

**Comment by MilosKozak** [comment]
turn off autosens logging if you don't needed
provide log from time range when the problem happens

**Comment by thomasmenges** [comment]
The last message was sent on 09:12pm 
The logfile is created on 09:13pm without autosense logging.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4167541/AndroidAPS.log)

**Comment by MilosKozak** [comment]
your NS is malfunctioning. read wiki pls
