### ISSUE TITLE
[2.6 RC7] Notification system window permission 

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2437]
"Application needs system window permission for notifications" is shown once a day or when switching language setting in AAPS even though all rights are permitted.
Click on "request" button does not start any action.

2.6 RC7 is shown as AndroidAPS 2.6-dev-a / build 7b984550e-2020.02.05-20:41
Phone: Samsung Galaxy A3 (2017) - Android 8.0.0 / Samsung Experience 9.0

**Comment by MilosKozak** [comment]
already resolved in dev
it should be asked only on adnroid 10
