### ISSUE TITLE
[2.6 RCx] Bug: Dexcom G6 sensor change not logged in AAPS coming from patched Dexcom app

### ISSUE THREAD

**Issue by sailor-911** [MilosKozak/AndroidAPS#2438]
Pump used: Roche insight
AAPS versions affected: since 2.6 RC4 until latest version RC7, probably all 2.6RCx
Event types not recorded: sensor change 
Dexcom app V: 1.5.1.5 - SW11587

Remark: in last master 2.5.1 it works like a charm - with identical dexcom app

Workaround: re-install of 2.5.1 - waiting 5 minutes for next transmitted BG value. Sensor change date arrives then. 

Sensor change time: 07:46
Waiting time: 2h
App 2.5.1 reinstall between 10:30 and 10:45
Sensor date received: shortly 5 minutes after aaps re install V2.5.1

logs selection attached:

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4174028/AndroidAPS.log)
[AndroidAPS._2020-02-08_00-00-00_.17.zip](https://github.com/MilosKozak/AndroidAPS/files/4174032/AndroidAPS._2020-02-08_00-00-00_.17.zip)
[AndroidAPS._2020-02-08_10-21-04_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4174034/AndroidAPS._2020-02-08_10-21-04_.1.zip)
[AndroidAPS._2020-02-08_10-21-04_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4174036/AndroidAPS._2020-02-08_10-21-04_.2.zip)
[AndroidAPS._2020-02-08_10-21-04_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4174037/AndroidAPS._2020-02-08_10-21-04_.0.zip)
[AndroidAPS._2020-02-08_00-00-00_.15.zip](https://github.com/MilosKozak/AndroidAPS/files/4174038/AndroidAPS._2020-02-08_00-00-00_.15.zip)

**Comment by MilosKozak** [comment]
it's caused by mulfctioning NSClient. check your queue

**Comment by sailor-911** [comment]
so why does it work with 2.5.1 ?? 
there‘s NO change within the configuration between rc7 and 2.5.1. it’s the same mobile and the same config. its worth to do a deeper analysis on Def side

**Comment by sailor-911** [comment]
Hello Milos,
pls reopen this inc. again. it’s a bit more complicated than your expectation:

a) AAPSs nightscout client has a problem when switching OFF the option “extended settings > use absolute instead percentage values” 
—> if this is set, a portion of dead events always remains within the nightscout queue and are not removed. 
but OFF is the recommended option when using INSIGHT pumps

b) if set the previous option back to ON ALL pending values from the NS Q are taken and the Q is cleared. 

c) doing this I changed the battery on the insight pump. 
—> nothing was recorded in AAPS 2.6RCxx, here RC7, but to 99% all previous versions have the identical problem. 

d) Next attempt: shutting down AAPS RC7, clearing apps cache in android. restarting RC7, then doing canula refill on pump: 
—> nothing recorded in RC7

d) switching back to AAPS 2.5.1 all is ok and data is taken from the insight pump. 

—> pls put these issue(s) back into state OPEN.  

Regards

Holger

**Comment by sailor-911** [comment]
Hello,

want to confirm, that a special combination of settings in NS  Client if AAPS was found, so that data from insight pump gets transferred to NS. 
Hence this no update is required and the closed issue can remain closed. 

Thanks @ regards ! 


Anfang der weitergeleiteten Nachricht:
