### ISSUE TITLE
[2.6 RC7] Bug: When confirming TT, wrong unit is used

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2448]
Main screen -> Long press TT > Custom TT> Change something > press OK

The confirmation dialog now states the given minutes (i.e. 4 min) as 4 hours.. When pressing OK it still saves the original 4 minutes.

I think I have found the code line to be changed, but uncertain what the original author wanted. Minutes or hours? See TempTargetDialog.kt line 121.

![2020-02-17 09 35 42](https://user-images.githubusercontent.com/6748615/74639030-5fdfa980-516d-11ea-96e5-0a267067820f.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/3b9ea53cc4f0f65eec3c698afe3e8a3e6f075432
thanks for reporting

**Comment by peterleimbach** [comment]
Somehow the fix in the master version is not working. But it is only the confirmation message which is wrong. The execution is a requested.
![Screenshot_2020-03-03-13-33-15-565_info nightscout androidaps](https://user-images.githubusercontent.com/4148261/75776345-1f2e8580-5d54-11ea-9bd2-107cea4b91d8.jpg)
![Screenshot_2020-03-03-13-33-21-278_info nightscout androidaps](https://user-images.githubusercontent.com/4148261/75776350-2190df80-5d54-11ea-8afd-d213df177fde.jpg)

**Comment by AdrianLxM** [comment]
Reopening. Apparently only fixed for one dialogue and not the other.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/4cca305e1bb9d7cba6f4672ca6e1756e8db5e1ac
