### ISSUE TITLE
[Enhancement][Security][Documentation] Encourage users to choose local setup

### ISSUE THREAD

**Issue by asquelt** [MilosKozak/AndroidAPS#2450]
deleted, disregard. I don't intend to participate in this project.

**Comment by AdrianLxM** [comment]
In the upcoming version the LocalProfile will become much more feature rich and has the potential to replace the Nightscout profile in functionality.

If you would like to contribute to the wiki, please get in contact with our supporters!

Thanks for you input!

**Comment by asquelt** [comment]
i was trying to bring it up on facebook group, but i have some trouble with communicating there (there's serious bullying running over there).

i was asked by Dominik to raise this separately, what i understand it has a RFC status a should be a subject to discuss (with whom? can they see this ticket?)

**Comment by AdrianLxM** [comment]
I'm travelling this and next week.
Please drop me a message on adrian@androidaps.org and ignore Facebook for technical discussions ;)
If you like we can Skype in about two weeks when I have more time?

(RC as release candidate, not RFC. But still good to explore safety and security options for upcoming releases!)

**Comment by AdrianLxM** [comment]
closing as author deleted the text
