### ISSUE TITLE
Proposing: During EB disable Loop completely

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2457]
Right now (2.6 RC7) when using Extended Bolus the Closed Loop will be disabled and Open Loop will be used. I think most people used to the Closed Loop feel the questions of the Open Loop are a real nuisance. Maybe it would be preferable to disable Loop completely during the EB duration?

**Comment by MilosKozak** [comment]
you can disable loop at all if you don't want suggestions
