### ISSUE TITLE
2.6.0 Design changes optimization

### ISSUE THREAD

**Issue by Pamalosebi** [MilosKozak/AndroidAPS#2466]
Hey,
First, thanks a lot for your great work! :)

But I wanted to report a small issue since the Update to v2.6.0.
I have a very huge plain spot underneath my Overview Tab.
See related pictures:

![APS1_bearb](https://user-images.githubusercontent.com/49550055/75625398-e3fa4e00-5bbd-11ea-9f4a-ef6ffa62dc8c.jpg)

![APS2](https://user-images.githubusercontent.com/49550055/75625399-e8266b80-5bbd-11ea-800b-fcc165cf2b1f.jpg)

I use a Huawei Mate 20 Pro. Could you please have a look into that and make the size of the Graphs dynamical again?

**Comment by marc-gaub** [comment]
Also thanks for your great job.
Same problem on Note10+
![Screenshot_20200301-132132_AndroidAPS](https://user-images.githubusercontent.com/46347773/75625590-dfcf3000-5bbf-11ea-80b0-e908ff7a6284.jpg)

**Comment by cascer1** [comment]
I'm noticing the same thing on OnePlus 7 Pro running Android 9.

**Comment by guydavies** [comment]
It's intentional. The autoscaling caused significant difficulties for
various features so Milos disabled it.

**Comment by winni67** [comment]
Which features are affected and why can‘t we enable/disable this via the configuration?

**Comment by Pamalosebi** [comment]
>It's intentional. The autoscaling caused significant difficulties for
>various features so Milos disabled it.

So, is this considered as "broken" right now, or will it stay this way?
In other words... will it be fixed in the next Version?

**Comment by asquelt** [comment]
+1 for making it configurable. i guess majority of us find current behaviour annoying.

**Comment by MilosKozak** [comment]
design changes will continue on 2.7

**Comment by asquelt** [comment]
until 2.7 is out, if someone with Java coding skills could make a fork with old scaling code reverted, i think many ppl would be glad. it's a single unwanted change that is being reported since release.

**Comment by guydavies** [comment]
It's the way it will be from this version going forward. It is not
considered a bug as the numerous closed issues will attest.

**Comment by pmisun** [comment]
Transpose X,Y :)

**Comment by NanniniM** [comment]
Hi all,

I'v got the same problem with oneplus 6 phone and Android 10. It would be perfect to go back to the previous layout ( ie 2.5).

Thanks for all job done !!

**Comment by Air69** [comment]
![IMG_20200303_084047](https://user-images.githubusercontent.com/54677671/75755813-560f9600-5d6a-11ea-8919-67823ac7719e.jpg)
First of all, thanks to the developers of this project. It changed my life!  I `m from China.  However,loopholes appear in the use. I suggest removing the Chinese translation of IOB, COB and BAS, for most people understand what it means.

**Comment by MarieT1D** [comment]
I got similar problems, but the other way round with my tiny phone which will make me need to downgrade to use it in exams. 

- portrait: graph time scale and bg number are not fully shown 
Before Update:
![Screenshot_20200304-172001](https://user-images.githubusercontent.com/37214302/75901896-82e1ad00-5e3f-11ea-8cf1-94c00106826c.png)
After:
![Screenshot_20200304-173416](https://user-images.githubusercontent.com/37214302/75902494-5e3a0500-5e40-11ea-934a-74a205b3a706.png)


- landscape: even with this enhancement: https://github.com/MilosKozak/AndroidAPS/issues/2475, bg number and graph would be too far apart, what makes this design more difficult to read without touching the phone i.e. in exams :/
Before update: 
![Screenshot_20200304-174502](https://user-images.githubusercontent.com/37214302/75901899-8412da00-5e3f-11ea-8686-dc6a04a5291b.png)
After:
![Screenshot_20200304-173913](https://user-images.githubusercontent.com/37214302/75901898-837a4380-5e3f-11ea-914d-d4aaf4b5a786.png)
![Screenshot_20200304-173909](https://user-images.githubusercontent.com/37214302/75901897-837a4380-5e3f-11ea-82df-4e022a5e3203.png)

Thanks for all your work!

**Comment by shipleyr** [comment]
I have the same thing on oneplus 5t. The screen size just has loads of empty space in it and the graph is all crammed at the top of the screen. Personally for me the size of the graph makes it unusable.

**Comment by MilosKozak** [comment]
having buttons scrollable on small phones and in landscape mode is reasonable change
https://github.com/MilosKozak/AndroidAPS/commit/2467c0bba7b624b91fd8210fe41f53839d6a54d2
