### ISSUE TITLE
[2.6] no insulin in AAPS with future carbs

### ISSUE THREAD

**Issue by n3cro1** [MilosKozak/AndroidAPS#2469]
Logs send by mail!

![Screenshot_20200301-190144](https://user-images.githubusercontent.com/38436498/75631059-0c02a500-5bf0-11ea-8648-0ba0b79f0387.jpg)
![Screenshot_20200301-190136](https://user-images.githubusercontent.com/38436498/75631061-0dcc6880-5bf0-11ea-81f7-589b8faff7cb.jpg)
![Screenshot_20200301-190127](https://user-images.githubusercontent.com/38436498/75631062-0dcc6880-5bf0-11ea-98f1-70db386ef942.jpg)
![Screenshot_20200301-190120](https://user-images.githubusercontent.com/38436498/75631064-0efd9580-5bf0-11ea-9236-28f1b37d882e.jpg)

**Comment by glaskopf** [comment]
Observed comparable behaviour this morning:

**Basic:**
After upgrading to 2.6 I activated local profils and changed NS to "Upload only"

**Situation:**
Using Bolus calculator with timeshift between insulin and carbs

**Problem:**
Smartphone / AndroidAPS shows only the insulin but not the latter carbs (careportal)
NS shows both values correctly 

**What I have done?**
Restartet my smartphone
AndroidAPS shows now both values (insulin, carbs) but only as a single entry in careportal / digaram with the insulintime. The time shift for carbs was not considered

**Comment by reijoahola-nightscout** [comment]
I  noticed the same problem but I think that at firts it showed only carbs but not insulin so IOB was wrong. When I testarted the phone it corrected the insulin but still with the same timestamp as carbs.

**Comment by reijoahola-nightscout** [comment]
Samsung Galaxy S9 with Android 10
AAPS updated into 2.6.0 yesterday
With AAPS 2.5.1 I did not notice the same problem.

**Comment by reijoahola-nightscout** [comment]
This looks like the same as earlier issue #2424 for 2.6 RC6 but it is in closed state.

**Comment by SabineDo** [comment]
I have the same problem:
I entered bolus and carbs with future carbs 10+ and it was not calculated in IOB, only the carbs. 
The Bolus was shown in the combo history, but not in AAPS.
[AndroidAPS_LOG_1583142248226.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4274767/AndroidAPS_LOG_1583142248226.log.zip)

**Comment by 2flea** [comment]
I heard of a similar case this morning by Sabine who is also using Combo and is also (as above) offline. 
![image](https://user-images.githubusercontent.com/38214111/75667895-b6260f80-5c78-11ea-9b80-57ebeebf6389.png)

@MilosKozak for you info, I tried today with my setup (DanaRS, 2.6-dev of 01.03.2020) and I cannot reproduce this error. I tried two boluses with future carbs (+10min), one online and one offline, both worked fine. I assume this is only Combo related?!
![image](https://user-images.githubusercontent.com/38214111/75667849-9b539b00-5c78-11ea-8791-979be13d6bba.png)

**Comment by tKostka** [comment]
Looks like the same issue as #2379

**Comment by fezulin** [comment]
I took some screenshots of this behaviour. 
AAPS: 2.6
Pump: Combo

Be aware: At first the bolus is not displaed.
But some minutes late, the bolus is displayed.
![Screenshot_1](https://user-images.githubusercontent.com/16593716/75680280-8c2d1700-5c91-11ea-965f-3aebe886c6f2.png)
![Screenshot_2](https://user-images.githubusercontent.com/16593716/75680285-9222f800-5c91-11ea-9674-1ba4fce4a595.png)
![Screenshot_3](https://user-images.githubusercontent.com/16593716/75680293-94855200-5c91-11ea-8e98-199e8e737e68.png)
![Screenshot_4](https://user-images.githubusercontent.com/16593716/75680297-9818d900-5c91-11ea-934a-4a44dcc9def4.png)
![Screenshot_5](https://user-images.githubusercontent.com/16593716/75680305-9a7b3300-5c91-11ea-8ce3-6a32c30f6df5.png)

**Comment by reijoahola-nightscout** [comment]
I waited about half an hour but it did not correct the problem.
I think that these are common for the reported problem systems
- Wizard used with carbs delayed
- Combo pump
- Android 10
- NS upload only (disabled sync)

**Comment by glaskopf** [comment]
I do not think it depends on the android version. I'm running Android 9 and have the same issue.

**Comment by reijoahola-nightscout** [comment]
> I do not think it depends on the android version. I'm running >Android 9 and have the same issue.
Ok, let's drop Android 10 from the list.
Can we drop something else ?

**Comment by reijoahola-nightscout** [comment]
In my system, when the problem is corrected by resetting the phone or restarting AAPS with exit command,
Treatments page list still have only one entry (both bolus and carbs). Timestamp is the bolus time. Also what is not correct that IOB and COB curves start from the the same time.

**Comment by SabineDo** [comment]
I'm also on Android 9.
After restarting the phone ( Xiaomi pocophone f1) there is now the following entry:
![IMG-20200302-WA0015](https://user-images.githubusercontent.com/45911340/75688418-c00f3900-5c9f-11ea-885a-1b86ea6f5596.jpeg)

Before the restart, the Bolus at 7.34 was not there
![20200302_091404](https://user-images.githubusercontent.com/45911340/75688497-e3d27f00-5c9f-11ea-859d-5358e4b2d629.jpg)

**Comment by wkuebel** [comment]
I had this issue this morning with Dana RS also and realized it while analyzing my NS Reports because the Insulin Value seems not to be correct. I corrected it manually in Nichtscout and later i read about the issue in the looper Community. 
![Screenshot_20200302-224014_AndroidAPS](https://user-images.githubusercontent.com/39454071/75721129-18fac380-5cd8-11ea-89f1-67e545d5cc16.jpg)

**Comment by mtothearkus** [comment]
I was able to reproduce the error as well. Can provide screenshots in the evening. After restart iob was recognized correctly.

**Comment by reijoahola-nightscout** [comment]
I made a new test when the setting
NS upload only (disabled sync) was OFF.
Now the problem did not exist or the system corrected it by syncing from NS. May be it corrected it so fast (within minute) that I had not time to check Treatments page.

**Comment by 2flea** [comment]
In Sabine's logs there is following records - it seems the sync of DB records for carbs and insulin of Combo is not working, dates are different?! Before (for Combo) there was only one record entry with both insulin AND carbs inside, seems the sync does not work correctly here. (NB, for RS there are always two records in DB, one for insulin and one for carbs, even for the same meal bolus.) 

07:35:14.288 [Thread-27130] D/DATATREATMENTS: [TreatmentService.createOrUpdate():326]: New record from: PUMP Treatment{date= 1583130869000, date= 02.03.2020 07:34:29, isValid= true, isSMB= false, _id= null, pumpId= 1583130869000, insulin= 3.0, carbs= 0.0, mealBolus= false, source= 1}

07:35:14.290 [Thread-27130] D/DATATREATMENTS: [TreatmentService.createOrUpdate():284]: Pump record already found in database: Treatment{date= 1583130869000, date= 02.03.2020 07:34:29, isValid= true, isSMB= false, _id= null, pumpId= 1583130869000, insulin= 3.0, carbs= 0.0, mealBolus= false, source= 1} wanting to add Treatment{date= 1583131470000, date= 02.03.2020 07:44:30, isValid= true, isSMB= false, _id= null, pumpId= 1583130869000, insulin= 0.0, carbs= 29.0, mealBolus= true, source= 1}

**Comment by reijoahola-nightscout** [comment]
This can be dangerous if the bolus was big and the user does not notice that bolus was not included in IOB. Should there be a warning about possible problem in AAPS Fb group.

**Comment by mtothearkus** [comment]
Here are the screenshots. The issue is definitely reproduceable. 

It seems that after restart after reading treatments from combo the iob is correctly showed. 

![Screenshot_20200303-083549](https://user-images.githubusercontent.com/52837251/75771888-24d39d80-5d4b-11ea-812d-1f816135e70e.png)
![Screenshot_20200303-083601](https://user-images.githubusercontent.com/52837251/75771890-269d6100-5d4b-11ea-9e54-30baab51f6b2.png)
![Screenshot_20200303-084245](https://user-images.githubusercontent.com/52837251/75771893-27ce8e00-5d4b-11ea-8ca1-38d9cdf65e35.png)
![Screenshot_20200303-083537](https://user-images.githubusercontent.com/52837251/75771895-29985180-5d4b-11ea-8bc0-448b2935f44c.png)

**Comment by MilosKozak** [comment]
My tests on RS are also negative

**Comment by swissalpine** [comment]
I know many people using combos can confirm the issue, me too.
@MilosKozak

**Comment by MilosKozak** [comment]
@swissalpine can you test this? https://github.com/MilosKozak/AndroidAPS/pull/2483

**Comment by swissalpine** [comment]
@MilosKozak https://github.com/MilosKozak/AndroidAPS/pull/2483 fixes the issue for me.
Thanks to @jotomo

**Comment by n3cro1** [comment]
@MilosKozak 
It works for me too!
Very nice @jotomo !
![Screenshot_20200306-213315](https://user-images.githubusercontent.com/38436498/76120769-7cdffd80-5ff2-11ea-8149-5a6153c36a63.jpg)
