### ISSUE TITLE
Basal differs from AAPS display and NS/NS client display - 2.5.1 and 2.6.0

### ISSUE THREAD

**Issue by jeanyvesrenard** [MilosKozak/AndroidAPS#2470]
last build version 2.6.0 : c3dbd1ec2-2020.03.01-16:26

Hello. I post this issue 15 days ago on FB, but I had no solutions.
On 2.5.1 
 Here is my question = I have differences on the graph of the basal showed between aaps full release, nsclient release and NS site. Ns site and nsclient are showing the same basal. The pump is sending the basal showned on NS. The IA on aaps and on NS is not the same either. So, will the calculations and the decisions taken by aaps be right ? For exemple (on the photo on FB on this link), you can see differences below between 17h and 18h. There are also differences on GA and IOB showed. Why this can happen? How can I solve those differences ? Many thanks for your help. JYR Father of Noemie (did, 6 years old). https://www.facebook.com/groups/AndroidAPSUsers/permalink/2627109694177098/

It's continuing on 2.6.0  
As Milos asked on wiki, I've installed the 2.6.0 version to see if the problem persist.  Unfortunately, the problem still remains. You can see on the new pictures attached : differences on 17:58 : basale rate on aaps display = 0.28, on AC-I display : 0% an on NS : 0.  There are also differences around 
15:30.  Many thanks for your help :o)

[AndroidAPS._2020-03-01_11-30-18_.1.log](https://github.com/MilosKozak/AndroidAPS/files/4272286/AndroidAPS._2020-03-01_11-30-18_.1.log)
[AndroidAPS._2020-03-01_11-30-18_.0.log](https://github.com/MilosKozak/AndroidAPS/files/4272287/AndroidAPS._2020-03-01_11-30-18_.0.log)

![Picture 1](https://user-images.githubusercontent.com/55049287/75632662-9b16b980-5bfe-11ea-9ef1-1c73b0a5de69.jpg)
![Picture 2](https://user-images.githubusercontent.com/55049287/75632663-9c47e680-5bfe-11ea-9b5a-fce35274a219.jpg)

**Comment by MilosKozak** [comment]
do you have upload as absolute values off?

**Comment by MilosKozak** [comment]
https://androidaps.readthedocs.io/en/latest/EN/Configuration/Accu-Chek-Insight-Pump.html#settings-in-aaps

**Comment by jeanyvesrenard** [comment]
Hello Milos.  Thank you very much.  I'm feeling so stupid.  Unfortunately, it was not put on off.  I'm sure I put it on off when I've builded and configured the application.  In the meantime I had to make a handling error...  Sorry to take your precious time for this issue.  It's working normaly now :o)  Thanks for your help! We can count on you, it's so precious !   Jean-Yves Renard
