### ISSUE TITLE
SMS carbs functionality not working

### ISSUE THREAD

**Issue by glaskopf** [MilosKozak/AndroidAPS#2472]
**I have  a problem with the new command "carbs"** 

- All other SMScommands are working for me. 
- The problem is reproduceable for me

**Description**

- Sending SMS:"_carbs 6_". 
- Receiving SMS: "_Um 6g Kohlenhydrate einzugeben, antworte mit dem Code Esa_"
- Sending SMS:"_Esa_"
- REceiving SMS: "_6g Kohlenhydrate erfolgreich erfasst_"

So far, so bad because AndroidAPS on the smartphone shows in parallel  an alarm and the message on smartphone:

"_Der Eintrag (Insulin 0,00, Kohlenhydrate:6 ) konnte nicht als Behandlung gespeichert werden. Bitte überprüfe die aktuelle Liste und füge, falls notwendig, den Datensatz manuell hinzu_"

And the error message is correct, because the carbs entry was not considered /saved.

---
AndroidAPS 2.6.0

**Comment by AdrianLxM** [comment]
Could you please provide log files?

**Comment by glaskopf** [comment]
Yesm I sent it via eMail. Please ignore the first email, because the problem was not in file.
In the newer logfile you can find the problem at ca. 09:57:25.464

**Comment by MilosKozak** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4289927/AndroidAPS.log)
09:57:25.465

@jotomo || @AdrianLxM 
can you test it on combo? It works with Dana

**Comment by glaskopf** [comment]
I have still the (exactly) same problem also with 2.6.1

**Comment by MilosKozak** [comment]
can you test https://github.com/MilosKozak/AndroidAPS/pull/2528 ?

**Comment by MilosKozak** [comment]
@glaskopf

**Comment by glaskopf** [comment]
@MilosKozak 
What is the best way to test it? 
I can Build a new app release via AS -> but I'm not sure which branch I should use?
Or is there a more elegant way to build a new release only with the four changed files?

**Comment by jotomo** [comment]
@glaskopf IMO the simplest way is to follow the steps in the first part of this blog post: https://blog.jetbrains.com/idea/2018/10/intellij-idea-2018-3-eap-github-pull-requests-and-more/ (Android Studio is based on IntelliJ, so the blog post also applies to Android Studio)
Then you have a local copy of the branch the PR uses, which you can then build and install as you usually do.

**Comment by MilosKozak** [comment]
@glaskopf did you test?

**Comment by glaskopf** [comment]
@MilosKozak Not yet, I have still problems with GIt just to build the right copy. Any hint which available build should be better suitable?

**Comment by MilosKozak** [comment]
fixed in dev

**Comment by glaskopf** [comment]
Sorry for my delayed test, I'm not so fit with AS. However, I make a re-test today with the actual master branch (2.6.1.1) and everything works as expepected. Thx a lot!
