### ISSUE TITLE
[2.6-dev 01.03.2020] Minor - Turning phone to landscape while bolusing indicates a total of 0.0U

### ISSUE THREAD

**Issue by 2flea** [MilosKozak/AndroidAPS#2473]
When I give a bolus of 6.0U with the wizard and turn my phone to landscape while the progress bar is shown the total bolus in landscape is shown as 0.0U. 

![image](https://user-images.githubusercontent.com/38214111/75665985-524e1780-5c75-11ea-998d-7151637667f0.png)

![image](https://user-images.githubusercontent.com/38214111/75666038-6a259b80-5c75-11ea-8fb9-3e1ce4591994.png)

![image](https://user-images.githubusercontent.com/38214111/75666145-9e00c100-5c75-11ea-9268-817572580cbe.png)

**Comment by wkuebel** [comment]
so does mine... I`am not sure i turned to landscape before, but may be...
![Screenshot_20200303-064431_AndroidAPS](https://user-images.githubusercontent.com/39454071/75749488-381e4300-5d22-11ea-92e2-d1d4c1552273.jpg)

**Comment by MilosKozak** [comment]
thanks
fixed by https://github.com/MilosKozak/AndroidAPS/commit/90a9b09395214cfdaebe49e8b6eb815862285801
