### ISSUE TITLE
[Enhancement] Option to hide overview screen buttons in landscape mode

### ISSUE THREAD

**Issue by roppenheimer** [MilosKozak/AndroidAPS#2475]
![IMG_2236](https://user-images.githubusercontent.com/179086/75701899-78db7500-5cac-11ea-89d9-80f7234d7f7c.JPG)

When in landscape mode in ver 2.6 the buttons at the bottom of the overview screen remain floating at the bottom of the overview screen partially obscuring the graphs. Currently it is not possible to arrange the phone in landscape so as to be able to see both the headline BG figure and the BG graph, which is the most common view to want. 

This request is to include the option to hide the buttons in landscape mode or to have the option to down-swipe them to remove them from the screen.

**Comment by guydavies** [comment]
I like the idea of an automatically hiding dock of action buttons. It seems like a sensible approach given the new fixed scaling.
