### ISSUE TITLE
[2.6.0] Careportal: activity / landscape / bg

### ISSUE THREAD

**Issue by mtothearkus** [MilosKozak/AndroidAPS#2477]
Hi,

setup:
Sony XZ2 compact
Android 9
Accu Chek Combo
AAPS 2.6.0

I recently wanted to fill in my activity through AKT tab. When I put in activity and put phone in landscape and put it back in normal mode, than the formula changed to BG-Entry.
Will also be saved as BG-Entry in Careportal.

**Comment by MilosKozak** [comment]
good catch, thanks
fixed by https://github.com/MilosKozak/AndroidAPS/commit/a8e8659e18cb01f1b79321ac9cd4a91f9db72a9f
