### ISSUE TITLE
Bolus not recorded

### ISSUE THREAD

**Issue by ShaunTheRam** [MilosKozak/AndroidAPS#2478]
At 8:05am I used the calculator to bolus, used the superbolus, and delivered 6.3 units with carbs to be eaten 10 minutes later. Whilst the bolus delivered, AAPS stated “delivering 0.0 units”. Insulin was delivered, and Combo screen stated last bolus 6.3 units. However, overview screen showed no IOB and the calculator showed no IOB, suggesting I have a large amount of insulin to correct. Pump shows insulin was delivered. Have had to manually enter insulin to avoid any potentially dangerous boluses. I’m using AAPS 2.6.0, build c3dbd1ec2-2020.03.01-23:21, full release.

**Comment by 2flea** [comment]
Probably the same than #2469
