### ISSUE TITLE
PumpControl 2.6.0 - Dana R not connect regularly

### ISSUE THREAD

**Issue by streethawk22** [MilosKozak/AndroidAPS#2479]
@Reporting bugs
--------------
On the Pumpcontrol version of AAPS 2.6.0, the pump will not connect regularly (one time in 30-60mins), but boluses goes without Problems and also the basal changes and all others Actions...When the Pump too long not connect, it come a Alarm...i have the Pumpcontrol downloaded from Github...It was for another Peoples, not for me...THX...Peter from Slovakia.
The last BOLUS was on 4.3.2020 on 20:13.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4289623/AndroidAPS.log)

**Comment by MilosKozak** [comment]
i double checked PumpControl + DanaR. AAPS reconnects every 30 min
maybe Android is putting app to sleep?
