### ISSUE TITLE
cancel tempbasal before suspend

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#248]

**Comment by AdrianLxM** [comment]
I've got something like this already in my experimental branch.
Please wait before implementing - I can do a suggestion-PR tonight.

**Comment by MilosKozak** [comment]
ok, i'm setting zero temp but it fails if another temp is running

**Comment by AdrianLxM** [comment]
zero-temps are only for "disconnects", not for  "suspends"?

**Comment by AdrianLxM** [comment]
Disconnects from the GUI set a Zero-Temp and this cancels out the current temp or extended bolus. This works fine for me.
