### ISSUE TITLE
[2.6.0] TBR canceling seems to crash AC Insight pump

### ISSUE THREAD

**Issue by Snackya** [MilosKozak/AndroidAPS#2480]
After updating to the 2.6.0 release today from 2.6RC7, my Accu Check Insight pump has crashed twice. The pump's screen goes black for a minute, then shows an E7 electronics error and alerts you to call the hotline. The pump continues to function properly after removing and re-inserting the battery. (The battery was the cause for the first case according to the hotline, so i changed it after that.)

First crash happened at 09:42 and second one just now at 16:05 according to pump alert logs. TBR cancelations are logged at 09:40 and 16:04 respectively.
Since both crashes happened around the time of the closed loop canceling a 0% TBR, this seems to be the prime suspect for main cause of the crash. I'm currently on Ojective 6, so the closed loop is only using Low Glucose Suspend at the moment.
Prior crashes on 2.6RC7 with Open Loop did not occur. The switch to 2.6.0 and Closed Loop happened simultaneously.

AC Insight is on FW V3.00.17, phone is a Google Pixel 3a on the latest Android 10 update. AAPS build is c3dbd1e.
Here are the log extracts from around the time both crashes occured.
[TBR_cancel_insight_crash_first.log](https://github.com/MilosKozak/AndroidAPS/files/4288213/TBR_cancel_insight_crash_first.log)
[TBR_cancel_insight_crash_second.log](https://github.com/MilosKozak/AndroidAPS/files/4288214/TBR_cancel_insight_crash_second.log)

**Comment by Philoul** [comment]
No crash with my Insight...
My firmware is the same (v3.00.17) and running with 2.6.0 since release (sunday).
My phone is a samsung A40 (android 9)...

**Comment by Chris99621** [comment]
Maybe i can help. I got that Problem in 2.5.1 too but only when i press a button on the pump at the same moment aaps connects to the pump. Then it goes to a black screen and dont react anymore only ar reboot (battery out) helps. Running now 2.6 on Galaxy s10+ with insight. Since i know that i dont press a butten when aaps connects :)

**Comment by overfrenk** [comment]
@Chris99621 yes! Same me... Your solution is the same that I use!

**Comment by TebbeUbben** [comment]
I don't think I can do much about this issue, but since it works again after re-inserting the battery, I doesn't seem to be too bad. There are probably just some weird things going on in the pump in that pump moment rightfully causing the electronic error - just be a bit more gentle to your pump.
