### ISSUE TITLE
Local profile not send to nightscout correctly, AAPS 2.6 

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2486]
I can't get the local profile uploaded to nightscout..the settings for upload are set correctly. There is created a new database but with empty profile and no date and time set. Couldn't get any hints by the community so far. Using AAPS 2.6, Dana R, Nightscout 13.01.,latest xdrip nightly.

**Comment by xJoe** [comment]
Same for me. Profile is uploaded as invalid. Using Dana RS and NS master 13.0.1 via 10be.de.

**Comment by xJoe** [comment]
![grafik](https://user-images.githubusercontent.com/13958493/76146178-f9291e00-6090-11ea-8f16-9b25add8db01.png)

**Comment by zehnBE** [comment]
on the server overview, you can download the "server.log", there you can see, what aaps sends.

**Comment by xJoe** [comment]
@MilosKozak I will sent you server.log as proposed by @zehnBE by mail.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/07aa6f20394d1f8493b7f75020c6b22fc7ed2165

**Comment by CaroGo** [comment]
I am on 12.6.1 build bbe2fd506-2020-03-09-14:34
I don't get any profile uploaded now...?!
