### ISSUE TITLE
LocalProfile page dosen't display  AVTIBATE PROFILE button in kospet hope smartwatch

### ISSUE THREAD

**Issue by hnsding** [MilosKozak/AndroidAPS#2487]
Reporting bugs
In my kospet hope smartwatch (fullandroid smartwatch with android 7.1.1), AndroidAPS2.6-dev (build mdt_00.11-835-g99e31cad9) worked fine, but I updated to AndroidAPS2.6.0(build:c3dbd1ec2) and it did not dispaly ACTIVATE PROFILE button, the background turns red. So I cannot  activate the LocalProfile. 
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
sorry, we don't support watch. it's not in our time possibilities to test on every piece of HW.
I keep this issue open for some time if you find enyone to help

**Comment by hnsding** [comment]
Thank you very much!
I uninstall and reinstall AndroidAPS2.6.0 in my kospet hope smartwatch today,  everything goes right!
