### ISSUE TITLE
Small screen 

### ISSUE THREAD

**Issue by Korostensky** [MilosKozak/AndroidAPS#2492]
Reporting bugs
--------------
- **everytime** on very small screen I don't see bolus treatment. Another treatments are ok. See attached files

![20200309_204305](https://user-images.githubusercontent.com/54218454/76251808-fae91200-6247-11ea-99e4-902f61bd53d3.jpg) 

![20200309_204314](https://user-images.githubusercontent.com/54218454/76251766-e9a00580-6247-11ea-9a66-fac504d09a21.jpg)

![20200309_204323](https://user-images.githubusercontent.com/54218454/76251735-d42adb80-6247-11ea-8fdd-5db1055c808b.jpg)

- 2.6.0

**Comment by MilosKozak** [comment]
sorry watches are not supported
https://github.com/MilosKozak/AndroidAPS/issues/2487

**Comment by Korostensky** [comment]
Ok, no problem. I can work without it and deleted wrong COB with NS Client on my phone. Thank you for your time. Have a nice day.
