### ISSUE TITLE
Android APS 2.6 SMB Problem

### ISSUE THREAD

**Issue by nahumgold** [MilosKozak/AndroidAPS#2494]
Hello
I use Dexcom G6 Sensor, Omnipod Pump and xdrip. 
After upgrading to 2.6 version, i have issue with SMB always and after carbs. 
In the openaps smb tab i see that the BG source doesn't support advanced filtering. 
But at my opinion G6 support it by the default. G6 native mode is marked in Xdrip. 
No problem with the previous 2.5.1 AAPS version. 
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
provide log files

**Comment by nahumgold** [comment]
Attached
Thank you!

вт, 10 мар. 2020 г., 21:44 Milos Kozak <notifications@github.com>:

**Comment by nahumgold** [comment]
https://drive.google.com/a/cng.co.il/file/d/1s-QhzflIE9Yeu2ykRsqV1-FeaNFBGq8Q/view?usp=drivesdk
 8:13 Nahum Golodets <nahum@cng.co.il>:

**Comment by MilosKozak** [comment]
not available for download

**Comment by MilosKozak** [comment]
closed by inactivity
