### ISSUE TITLE
Smb are doubled, AAPS 2.6.

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2495]
I report this for a colleague : My Setup:
SMB are delivered twice. See attached logs:
https://drive.google.com/file/d/10OLzgzUQYD7Qx1bem5MxqBJM6U-vqxKI/view?usp=drivesdk

Sony Xperia XZ1
Dana RS
Dexcom G6 with xdrip+
Local Broadcast and upload to NS
[Logs](https://drive.google.com/file/d/10OLzgzUQYD7Qx1bem5MxqBJM6U-vqxKI/view?usp=drivesdk) [](https://drive.google.com/file/d/10OLzgzUQYD7Qx1bem5MxqBJM6U-vqxKI/view?usp=drivesdk) 
ADD TIME OF EVENT HERE: 10th March 2020 8:45
ADD ISSUE DESCRIPTION OR GITHUB ISSUE REFERENCE NUMBER: double SMB
AndroidAPS 2.6.0
Build: c3dbd1ec2-2020.03.06-23:00
Remote: https://github.com/MilosKozak/AndroidAPS
Flavor: fulldebug
Nightscout version: 0.12.3

**Comment by MilosKozak** [comment]
there is already fix in dev https://github.com/MilosKozak/AndroidAPS/commit/1e02773b71d0180bf30b6185c40b718ea268200f

**Comment by MilosKozak** [comment]
log ends 8:40

**Comment by CaroGo** [comment]
OK.. So do you need more information or is it already fixed?

**Comment by AdrianLxM** [comment]
If they are delivered twice: More info needed!
If they appear to be delivered twice: Should be fixed.

**Comment by MilosKozak** [comment]
Closed by inactivity

**Comment by CaroGo** [comment]
Yes, sorry for that... Told the Person to provide more information .. But she did not.. 😕
