### ISSUE TITLE
Automation triggers even if not in SSID

### ISSUE THREAD

**Issue by BastianBickelhaupt** [MilosKozak/AndroidAPS#2496]
As i mentioned here: https://www.facebook.com/groups/AndroidAPSUsers/?post_id=2641537899400944

With latest AAPS version the automation rules are fired even if the selected SSID is not active.
I have 2 automation rules ... both requires a SSID from my office.

Before Upgrading to 2.5.0 it was working perfectly. After the update the rules are fired every time, even when i am not in the office.

**Comment by zehnBE** [comment]
I think, it comes from this changes:
https://github.com/MilosKozak/AndroidAPS/commit/9aa77122ba76ece6d27bf2634203194ed4b5e194#comments

**Comment by MilosKozak** [comment]
good catch, thanks.
fixed by https://github.com/MilosKozak/AndroidAPS/commit/bec6d9903699e638673a868a77e0b9e19de53969
