### ISSUE TITLE
Dagger3 crash after wear plugin launch

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2497]
After launch I can see a few second home screen, then app closes and I have a message asking me if I want to restart... 

log on dev phone (low cost phone, Hola Android 8.1)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4315059/AndroidAPS.log)

log on loop phone (Samsung A40 Android 9)
[Dagger3 A40.log](https://github.com/MilosKozak/AndroidAPS/files/4315080/Dagger3.A40.log)

**Comment by MilosKozak** [comment]
nothing visible in logs.
and turn off autosens logging unless you really need it

**Comment by Philoul** [comment]
I may have a clue regarding the problem: I noticed yesterday on my loop phone that one of my automation rules started at midnight instead of 17:30...
I checked on my dev phone, and the crash changes the time trigger of my rules:

Screenshot before dagger install with Time trigger ok (17h30)
![TimeTriggerAutomationRule](https://user-images.githubusercontent.com/52934600/76394477-e1de7f00-6375-11ea-8170-8bb8dd2bf550.png)

Then installation and run of Dagger3:
![Dagger3Crash1](https://user-images.githubusercontent.com/52934600/76394545-f4f14f00-6375-11ea-957b-fb3a6de1ca83.png)
![Dagger3Crash2](https://user-images.githubusercontent.com/52934600/76394557-f9b60300-6375-11ea-8e5e-3ac49933f2ae.png)

And just after that check of the automation rule reset to 00:00:
![TimeTriggerAutomationRuleKO](https://user-images.githubusercontent.com/52934600/76394580-09354c00-6376-11ea-99e1-f4ceebf1617c.png)

I then reload my preferences and made the same test with automation plugin disable
=> Same result... (crash with dagger 3 and time trigger in automation rules also reset even if plugin was disabled during dagger crash...)

**Comment by Philoul** [comment]
The problem comes from Wear plugin
With all plugins disable I can launch Dagger3
With all other plugins activated it seems to work... (those that I use: Loop, Actions, NSclient, Automation)
when I enable wear plugin Dagger3 crash...

**Comment by MilosKozak** [comment]
hopefully fixed

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/927e690f7f576772dd4fa10d77eec28b46731718

**Comment by Philoul** [comment]
Unfortunatly not...

It's just a litle bit better : I can now launch AAPS, enable Wear plugin, but whatever I do related to this Wear plugin (open the wear parameters, open the wear tab, open the preferences of the application that contains Wear category ...) AAPS crash immediatly!

(sorry for autosens log, i have disabled it but probably enabled again after a import settings...)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4330055/AndroidAPS.log)

You can directly go at the end of log after 15:27 (crash at 15h28)

**Comment by MilosKozak** [comment]
fixed
