### ISSUE TITLE
[2.6] "basal value set to lowest possible" keeps popping up falsely

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2498]
I have to set my profile to 30-40% when i work out. 
Whenever I do that, a warning pops up that (more or less) says "basal value set to lowest possible value". So far so good.
From then on, this warning pops up with every profile change I do (90%, 70%, etc.) until I delete the low profile switches (30%,40% where the message popped up in the first place) from the treatment history. 

This is really annoying and I suggest that it should be enough to see this message one time.

**Comment by MilosKozak** [comment]
this is by design and will not be changed. during calculations AAPS load and uses older data thus this message reappears

**Comment by RobHoff** [comment]
But this is obviously wrong! When I change my profile to 90% the basal value is obviously not set to the lowest possible value. Nevertheless the message pops up in red and is confusing and annoyingly red and distracting at the top of the screen.

**Comment by guydavies** [comment]
Not necessarily.  If the minimum value of the basal is 0.1u/h (as an example) and your basal is set to 0.1u/h, it doesn’t matter if you set it to 10% or 90% of that value, you’re already at the minimum value of the basal.  Some pumps have a minimum basal that is  not zero.

Rgds,

Guy

**Comment by RobHoff** [comment]
Fair, but that can be easily falsified. The message pops up even when my basal rate is 0.9 and I set the profile to 90%. And the pump can deliver basal rates lower than 0.8, so this can't be the minimum value.

**Comment by guydavies** [comment]
Fair enough but your assertion that it *must* be broken for that reason was
not true. Your extra info suggests it is wrong so hopefully someone can
help.
