### ISSUE TITLE
Big time difference between AndroidAPS and Dana RS

### ISSUE THREAD

**Issue by sfriedriszik** [MilosKozak/AndroidAPS#2499]
I get an error message in AndroidAPS that the time difference between the pump and AndroidAPS should be too large. In fact, the deviation is 1 minute.
AndroidAPS 2.6.0

![WhatsApp Image 2020-03-11 at 12 24 39](https://user-images.githubusercontent.com/43376497/76413154-35ac9080-6395-11ea-8e53-f74321d8a13e.jpeg)
![WhatsApp Image 2020-03-11 at 12 24 26](https://user-images.githubusercontent.com/43376497/76413161-39d8ae00-6395-11ea-877a-e862922e7d28.jpeg)

[AndroidAPS_LOG_1583926117669.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4317982/AndroidAPS_LOG_1583926117669.log.zip)
t: 12:23

**Comment by guydavies** [comment]
could it be related to the date format? your phone is in German so will have the date in format DD/mm/yyyy but your pump appears to have the date as mm/DD/yyyy. that would create a variation of several months.

**Comment by sfriedriszik** [comment]
> could it be related to the date format? your phone is in German so will have the date in format DD/mm/yyyy but your pump appears to have the date as mm/DD/yyyy. that would create a variation of several months.

it has been running for 14 months with the same settings

**Comment by guydavies** [comment]
hmm. weird.

**Comment by AdrianLxM** [comment]
I cannot find it in the logs.
Did it happen once or does it happen regularly?

If it happens regularly, please upload logs of a period where it happens.
Thank you!

**Comment by CaroGo** [comment]
@AdrianLxm logs are underneath the second foto! 😉

**Comment by MilosKozak** [comment]
you have pump logging disabled. so in this particular case i cannot help.
if this is for the first time i'd just ignore it.
if this is repeating issue, turn on PUMP and PUMPCOMM logging and open new issue when the problem appear again

**Comment by AdrianLxM** [comment]
Reopening and will label it with "more info" needed. :)

**Comment by sfriedriszik** [comment]
thank you for taking up the topic again.I can't say much more about the problem at the time. the only thing I can do is turn on the log for pump communication and wait for the as symptom to appear again. this error was unique.

**Comment by AdrianLxM** [comment]
@sfriedriszik, then, if you don't mind, I will really close this. Please re-open or open a new ticket if it happens again.
