### ISSUE TITLE
"Ignore battery optimization?" keep showing repeatedly.

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2500]
On a Realme X2 PRO with Android 9, this message is keep showing even when I select "Allow". Sometimes twice a day or more. 

![Screenshot_2020-03-12-02-32-29-15](https://user-images.githubusercontent.com/608650/76495383-a94eac00-642e-11ea-82c4-9a473e67c41b.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4322701/AndroidAPS.log)

**Comment by twain47** [comment]
Is this a new install / new phone or an upgrade (and if so from what version)?

Was this working previously on this phone and something has changed, or is this the first time running AAPS on this phone?

Are you seeing any notification in AAPS, or just this system popup?

**Comment by parapenT1sta** [comment]
It's a brand new phone, before I had a Redmi 4X with LineageOS 16 with no issues. With this phone since day 1 is like this.

Just know I got the message to accept it again. 

![Screenshot_2020-03-12-10-01-29-00_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/76510903-42d78700-644a-11ea-94fb-afd4efa9a88d.jpg)

**Comment by twain47** [comment]
I'd suggest going into settings and see if you can manually disable battery optimisation for AAPS.  You might have to hunt around for what the option is called on this phone.

From what I can see Realme devices possibly use their own variant of Android (ColorOS) - it is possible they have disabled this option in some way. Without battery optimisation disabled AAPS isn't hugely safe - it can be shut down by Android at night when it isn't being used which means loop is disabled without warning.

**Comment by parapenT1sta** [comment]
I did that since day one. On Ruffy, Dexcom App, xDrip and AndroidAPS. Only on xDrip and AndroidAPS I get this warning. The fact is that the app never stopped working. It's just annoying keep asking the samething over and over.

![Screenshot_2020-03-12-10-55-09-79](https://user-images.githubusercontent.com/608650/76514600-0d359c80-6450-11ea-9d5a-03c08a440090.jpg)

**Comment by MilosKozak** [comment]
it's phone specific issue. we cannot help sorry . ask on fb if anyone is using the same phone
