### ISSUE TITLE
Calibration is not transfered from AAPS 2.6.0 to xDrip

### ISSUE THREAD

**Issue by FlyRad** [MilosKozak/AndroidAPS#2504]
Reporting bugs
--------------
Since update to 2.6.0: when you put in new calibration value in AAPS 2.6.0 the value is not transfered anymore to xDrip. Therefore calibration is not executed. (using Dexcom G6).
Info: in xDrip Inter-App settings, "accept calibrations from other aps" is switched on, like always.

**Comment by adrian-hidothealth** [comment]
Hi Thomas,

could you please try this a couple of times and then grab the logs and attach them?
Ideally note the time when you did that. Makes it easier so search in the logs :) 

thanks,
Adrian

**Comment by AdrianLxM** [comment]
Hi Thomas,

could you please try this a couple of times and then grab the logs and attach them?
Ideally note the time when you did that. Makes it easier so search in the logs :)

thanks,
Adrian

**Comment by cepo** [comment]
Hello. I have the same problem but for me even the carbs/boluses are not sent to xDrip in 2.6.0. The "calibration not sent" issue started few weeks before updating to 2.6.0 I am using Xiaomi phone with Android 7 and MIUI 11.0.2.0 if it can help in searching for the bug. Dexcom G5, tried with older and also new beta version of xDrip.

**Comment by AdrianLxM** [comment]
@cepo like I wrote Thomas, could you please attach some logs.
It would also be nice to write what you see step by step in AndroidAPS (First it asks to confirm, then it shows a toast notification that, ...)

**Comment by FlyRad** [comment]
When calibration is done with AAPS 2.6.0, calibration it is not transfered to xDrip.
How do I calibrate:
1. In AAPS I press button with small blood drops
2. put in number from finger prick and press o.k.
3. after that window pops up "calibration"
4. again press o.k.
---> calibration is not transfered and in xDrip logs there is also no information .

see attatched files!

Regards, thank you Thomas


-- 
Thomas Rank

 
 

Gesendet: Dienstag, 17. März 2020 um 18:59 Uhr
Von: "AdrianLxM" <notifications@github.com>
An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com>
Cc: FlyRad <Th.Rank@web.de>, Author <author@noreply.github.com>
Betreff: Re: [MilosKozak/AndroidAPS] Calibration is not transfered from AAPS 2.6.0 to xDrip (#2504)


 

@cepo like I wrote Thomas, could you please attach some logs.
It would also be nice to write what you see step by step in AndroidAPS (First it asks to confirm, then it shows a toast notification that, ...)

**Comment by cepo** [comment]
Logs attached.

I hit calibration button on the home screen -> enter the number -> hit OK -> it shows me the number I entered -> hit OK again -> it jumps back to home screen. No warning, error or xDrip opening ... Tried between 19:11 and 19:13, 4 times.

Insulin/carbs entries can be found between 16:32 and 17:00 for example.

I have also problems with NSclient upload but another issue #2511 was opened for that by different user.

Thanks.

[AndroidAPS_17032020.zip](https://github.com/MilosKozak/AndroidAPS/files/4345172/AndroidAPS_17032020.zip)

**Comment by AdrianLxM** [comment]
I've just seen that there are two confirmation dialogues chained.
I will come back to you if I have something to test.

Thank you guys!

**Comment by AdrianLxM** [comment]
@FlyRad , @cepo , if you know how to build dev branches, could you please test this one: https://github.com/MilosKozak/AndroidAPS/pull/2522

(branch: fix/issue2504)

**Comment by AdrianLxM** [comment]
Fixed in dev.
