### ISSUE TITLE
Bolus delivery failed (Combo)

### ISSUE THREAD

**Issue by enzogachineiro** [MilosKozak/AndroidAPS#2509]
Reporting bugs
--------------
I am using closed loop, connection between pump and mobile worked fine, but all tries of bolus delivery were unsuccessfully. I tried through calculator, treatment and insulin buttons.
After confirmation, I received the "Waiting for pump" and then the "Bolus delivery failed" message.

My installation is new, just migrated from Medtronic 640 to Combo yesterday. I tried to start with 2.6 but it didn't worked (also loop offline was not working). So I uninstalled and installed the version 2.5.1 (current one). The loop offline resolved, but the issue with bolus delivered not.

I am using Xaiomi Mi A2 (Android 9), Dexcom G6, xDrip+, Ruffy, AndroidAPS 2.5.1.

[AndroidAPS._2020-03-15_00-32-51_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/4335923/AndroidAPS._2020-03-15_00-32-51_.4.zip)
[AndroidAPS._2020-03-15_00-32-51_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4335924/AndroidAPS._2020-03-15_00-32-51_.0.zip)
[AndroidAPS._2020-03-15_00-32-51_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4335925/AndroidAPS._2020-03-15_00-32-51_.1.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4335926/AndroidAPS.log)
[AndroidAPS._2020-03-15_00-32-51_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4335927/AndroidAPS._2020-03-15_00-32-51_.2.zip)
[AndroidAPS._2020-03-15_00-32-51_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/4335928/AndroidAPS._2020-03-15_00-32-51_.3.zip)
![image01](https://user-images.githubusercontent.com/31545350/76721469-f4aed600-671e-11ea-83d7-2efd46e9478e.jpg)
![image05](https://user-images.githubusercontent.com/31545350/76721473-f7a9c680-671e-11ea-8585-2355753a9f31.jpg)
![image04](https://user-images.githubusercontent.com/31545350/76721474-f8daf380-671e-11ea-8aa3-b061ebfc71ad.jpg)
![image03](https://user-images.githubusercontent.com/31545350/76721477-f8daf380-671e-11ea-8994-9290138d683d.jpg)
![image02](https://user-images.githubusercontent.com/31545350/76721478-f9738a00-671e-11ea-87dd-00df78a93396.jpg)

**Comment by MilosKozak** [comment]
did you do at least on bolus on pump?

**Comment by jotomo** [comment]
@MilosKozak RuffyScripter can handle a new pump with an empty history for a while now :-)
@enzogachineiro When entering the bolus menu to input the bolus amount, AAPS fails to detect it's on the bolus input screen (the one where you use up/down to set the desired bolus amount).
What language have you set on the pump?

**Comment by enzogachineiro** [comment]
> did you do at least on bolus on pump?

Yes, he is wearing the new pump (we didn’t go back to Medtronic). We are doing bolus directly in the pump (and then informing carbs in APPS). After doing a bolus we resync with pump so APPS gets the IOB from pump.

I believe it would be very important to include in the objectives doing a bolus.

**Comment by enzogachineiro** [comment]
> @MilosKozak Ruffy can handle a new pump with an empty history for a while now :-)
> @enzogachineiro When entering the bolus menu to input the bolus amount, AAPS fails to detect it's on the bolus input screen (the one where you use up/down to set the desired bolus amount).
> What language have you set on the pump?

Portuguese, and APPS in English. Is this an issue?

**Comment by jotomo** [comment]
> [Combo] Portuguese, and APPS in English. Is this an issue?

Ruffy needs the texts on each given screen to determine which screen is currently displayed. So if a translation is wrong, ruffy will not be able to. 
The screen mentioned above should have the text "VOLUME DO BOLUS". Can you check on the pump that it says that?

**Comment by enzogachineiro** [comment]
> > [Combo] Portuguese, and APPS in English. Is this an issue?
> 
> Ruffy needs the texts on each given screen to determine which screen is currently displayed. So if a translation is wrong, ruffy will not be able to.
> The screen mentioned above should have the text "VOLUME DO BOLUS". Can you check on the pump that it says that?

“DOSE DO BOLUS” ... should I change the language to English?

**Comment by jotomo** [comment]
That's a quick solution if the patient is comfortable with it.
Apparently you're using a different (perhaps newer) pump model with different translations than the ones on my pump. If you like you can collect the screen names from your pump and I can add them to ruffy, so that ruffy will support that pump in Portuguese as well. The current translations (which would then be extended to include those on your pump) are here: https://github.com/MilosKozak/ruffy/blob/a65693c5f3b20a6d1b5ca63e4ab8435d8c2142bf/app/src/main/java/org/monkey/d/ruffy/ruffy/driver/display/menu/TitleResolver.java#L366
Those names or shown when accessing the quick info menu (pressing the check button in the root menu), regular bolus, extended and multiwave bolus (not supported with AAPS, so checking those isn't absolutely essential), temporary basal, "my data" (history). For the last two, navigate through all entries with the menu key, so that for temporary basal both percentage and duration is displayed and for the history, boluses, temporary basals, errors and TDD titles.

**Comment by enzogachineiro** [comment]
> That's a quick solution if the patient is comfortable with it.
> Apparently you're using a different (perhaps newer) pump model with different translations than the ones on my pump. If you like you can collect the screen names from your pump and I can add them to ruffy, so that ruffy will support that pump in Portuguese as well. The current translations (which would then be extended to include those on your pump) are here: https://github.com/MilosKozak/ruffy/blob/a65693c5f3b20a6d1b5ca63e4ab8435d8c2142bf/app/src/main/java/org/monkey/d/ruffy/ruffy/driver/display/menu/TitleResolver.java#L366
> Those names or shown when accessing the quick info menu (pressing the check button in the root menu), regular bolus, extended and multiwave bolus (not supported with AAPS, so checking those isn't absolutely essential), temporary basal, "my data" (history). For the last two, navigate through all entries with the menu key, so that for temporary basal both percentage and duration is displayed and for the history, boluses, temporary basals, errors and TDD titles.

Changing language to English worked fine... thanks Guys, you are awesome!!!

I reviewed all the items, and all are correct, except 2. Bellow the correct translation:

if(title.equalsIgnoreCase("dose do bolus")) //multiwave 1
            return Title.BOLUS_AMOUNT;

if(title.equalsIgnoreCase("dados de alarmes")) //mydata 2
            return Title.ERROR_DATA;
      
Thanks!

**Comment by jotomo** [comment]
Thanks! I've added the translations and updated the _combo_ branch. Could you please update (Ctrl-T in Android Studio, just like with AAPS) and install the updated ruffy version (just install, don't uninstall ruffy).
Bolusing should then also work when you set the pump language to Portugese again.

**Comment by enzogachineiro** [comment]
> Thanks! I've added the translations and updated the _combo_ branch. Could you please update (Ctrl-T in Android Studio, just like with AAPS) and install the updated ruffy version (just install, don't uninstall ruffy).
> Bolusing should then also work when you set the pump language to Portugese again.

Yessssss!!!!! It is now working in Portuguese! Thank you so much!
