### ISSUE TITLE
2.6 Automation to set temp target

### ISSUE THREAD

**Issue by JeanNo2a** [MilosKozak/AndroidAPS#2510]
I got an issue with temp target set with automation
My rule is : if glucose is > 110, then set temp target =90 ; 45 min
I got the smile in the automation log, but the temp target is not set.
If I reboot aaps, the target is set 1 time then auto canceled in the 5 minutes

**Comment by MilosKozak** [comment]
the you have another rule which turn it off

**Comment by JeanNo2a** [comment]
It does the same
temp target auto set
then few seconds after switched off
![image](https://user-images.githubusercontent.com/34631572/76893277-5d679100-688c-11ea-836d-43998d4f0f07.png)
![Screenshot_20200317-201358_AndroidAPS](https://user-images.githubusercontent.com/34631572/76893342-7d975000-688c-11ea-96e9-56c675864b85.jpg)

**Comment by JeanNo2a** [comment]
![tempFileForShare_20200317-202008](https://user-images.githubusercontent.com/34631572/76893518-c6e79f80-688c-11ea-9307-02cc49478df1.jpg)

**Comment by JeanNo2a** [comment]
Now it's working... 

![IMG-20200317-WA0015](https://user-images.githubusercontent.com/34631572/76897149-7cb5ec80-6893-11ea-8121-f63cbed57bb8.jpg)

**Comment by JeanNo2a** [comment]
And again it doesn't work anymore
![Screenshot_20200317-234835_AndroidAPS](https://user-images.githubusercontent.com/34631572/76908902-24d6b000-68aa-11ea-8378-d5598cda1971.jpg)
![Screenshot_20200317-234844_AndroidAPS](https://user-images.githubusercontent.com/34631572/76908917-2ef8ae80-68aa-11ea-85cb-c626fbf6f189.jpg)

**Comment by MilosKozak** [comment]
ok, povide log files when this happen again

**Comment by JeanNo2a** [comment]
[AndroidAPS_LOG_1584512389582.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4347320/AndroidAPS_LOG_1584512389582.log.zip)

**Comment by JeanNo2a** [comment]
It does the same with another automation rule
If hour = 5 to 8 then target =80 time 45 min

**Comment by JeanNo2a** [comment]
And now it works again

[AndroidAPS_LOG_1584517020868.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4347604/AndroidAPS_LOG_1584517020868.log.zip)

**Comment by JeanNo2a** [comment]
A 24h log
[AndroidAPS_LOG_1584600084089.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4353007/AndroidAPS_LOG_1584600084089.log.zip)

**Comment by MilosKozak** [comment]
i'm a bit confused. if you provide log, please specify time of occurence

**Comment by JeanNo2a** [comment]
Sorry
In this log, I manually set a temp target at 15:49
It was auto cancelled at 15:50
[AndroidAPS_LOG_1584715822430.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4360210/AndroidAPS_LOG_1584715822430.log.zip)

**Comment by MilosKozak** [comment]
log ends 15:50:22
provide more
here is no cancel

**Comment by JeanNo2a** [comment]
I don't know... 
May it's a display bug
It's true I have some SMB. As I am with FsL I doesn't have normally with no temp target 
[AndroidAPS_LOG_1584727822801.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4361233/AndroidAPS_LOG_1584727822801.log.zip)

**Comment by MilosKozak** [comment]
same reason as https://github.com/MilosKozak/AndroidAPS/issues/2515
