### ISSUE TITLE
[2.6.0] NS client/Connection settings do not work

### ISSUE THREAD

**Issue by selli2931** [MilosKozak/AndroidAPS#2511]
The button "Only use WiFi connection" or "Only during charging" do not trigger an upload stop, although the conditions are not given, instead the treatments are permanently uploaded to NS.

I use Medtronic Pump, Libre sensor and xdrip

**Comment by Chris99621** [comment]
same for me. I [mentiond](https://github.com/MilosKozak/AndroidAPS/issues/2484#issuecomment-595966801) it here too. I use a Insight with Libre 2 on Android 10 (March 2020) Galaxy s10+. I also tried to reinstallt AAPS but there was no change. If i change the setting for charging while the phone is not charging, NS is not allowed but if i charge NS stays in not allowed like it is frozen.

**Comment by MilosKozak** [comment]
Fixed bug in charging detection https://github.com/MilosKozak/AndroidAPS/commit/82ffe0f9ac503dece7045e4304e29dc84e4d3a27
Wifi detection works like expected in upcomming 2.6.1
