### ISSUE TITLE
AAPS 2.6 Profileswitch not synchronized from home screen to profile tab

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2513]
AAPS 2.6
Using local profiles: If I do a profile switch on homescreen, the shown profile in the profile tab is not changed..this can be confusing.

![1584469628495](https://user-images.githubusercontent.com/22258719/76889139-5c7f3100-6885-11ea-8c84-3840690a5baf.jpg)

I can provide log files if needed.

**Comment by MilosKozak** [comment]
these are 2 different things. profile tab shows a list of available profiles
on overview you can pick one and make it active. active profile is then displayed

but profile tab has no relation to active profile running and displayed on overview. theoreticaly you can do profile switch from NS and then active profile will not be even listed on profile tab

**Comment by CaroGo** [comment]
Yes, I thought it would be like that... As people are now using local profiles more often, I still think this could be a bit confusing. Maybe we should comment this in wiki?

**Comment by MilosKozak** [comment]
it's already well described at profile switches chapter. but you can PR improvement
