### ISSUE TITLE
AAPS 2.6 still restarting every loop

### ISSUE THREAD

**Issue by lydiaengler** [MilosKozak/AndroidAPS#2518]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by lydiaengler** [comment]
Just to say that this issue reported in #2196 is still happening on 2.6. Everthing runs fine for, say 2-3 weeks, then AAPS crashes and restarts whenever a BG comes in.

Uninstalling the Dexcop app 2.4 region 1 and reinstalling it solves the issue - for a few weeks, after which it comes back.

I think you said you hoped this would be fixed in 2.6 but it doesn't look like it has been.

**Comment by MilosKozak** [comment]
provide logs pls when the crash happen

**Comment by lydiaengler** [comment]
Apologies for not providing this earlier Milos.

Anyway, this is still happening.  It works without the issue for about 3 weeks, then the restarying every loop starts up, you just have to delete then reinstall the patched Dexcom app, and it goes away for another 3 weeks or so.

Interestingly, when it happened today, there happened to be no data coming from the sensor (as I was in the bath tub!) but AAPS was still restarting every 5 minutes just after every no signal alert notification from the patched Dexcom app.  So it's related to the patched dexcom app just talking to AAPS, not the BG data specifically being sent.

Anyway, here's the log...I have replaced the NS URL with xxxxxx's for security reasons.
[AndroidAPS crashlog 11 Apr 2020.txt](https://github.com/MilosKozak/AndroidAPS/files/4464386/AndroidAPS.crashlog.11.Apr.2020.txt)

**Comment by lydiaengler** [comment]
@MilosKozak have you had any opportunity to look at the logs?

**Comment by MilosKozak** [comment]
no sign of crash in log. open new issue with new logs if this happen again
