### ISSUE TITLE
[2.6.0] NS client does not connect when wifi is turned on and option "Only use WiFi connection" enabled

### ISSUE THREAD

**Issue by cepo** [MilosKozak/AndroidAPS#2526]
Hello.

I have the "Only use WiFi connection" enabled and WIFI on phone turned on, NS client is unable to connect. Still showing "Status: Not allowed". Even when I press Restart few times, situation is still the same. 
After I disable and enable again the "Only use WiFi connection" it goes through: "Connecting ...", "Athenticated (RWT)" and actually connects.
When I turn WIFI off/on it stops working again and queue is growing.

No issue with previous AAPS versions.
Thanks.

**Comment by MilosKozak** [comment]
duplicate to https://github.com/MilosKozak/AndroidAPS/issues/2511
