### ISSUE TITLE
UI 2.6.x: Top chart no longer grows to fill height

### ISSUE THREAD

**Issue by nielsmaerten** [MilosKozak/AndroidAPS#2531]
Starting with v2.6.0, the top chart no longer grows to occupy the available height of the display.

Device: OnePlus 3 running Android 9
Display: 5.5 in;1920 x 1080; 401ppi ([source](https://en.wikipedia.org/wiki/OnePlus_3))

Screenshot of portrait mode in v2.6.1:
![Screenshot_20200323-224052](https://user-images.githubusercontent.com/4604406/77366528-7f638680-6d58-11ea-859f-967fd11454bd.jpg)

v2.6.1, with the bottom chart disabled:
![Screenshot_20200323-224104](https://user-images.githubusercontent.com/4604406/77366567-8db1a280-6d58-11ea-9dbf-54e4fabdf0fe.jpg)

v2.6.1, landscape mode (this looks fine)
![Screenshot_20200323-224109](https://user-images.githubusercontent.com/4604406/77366596-9d30eb80-6d58-11ea-8aeb-bca05eb5731c.jpg)

For comparison: the portrait screen in v2.5.x (the 'expected' layout)
![Screenshot_20200105-080319](https://user-images.githubusercontent.com/4604406/77366633-b0dc5200-6d58-11ea-8be2-07aa573b45d1.jpg)

**Comment by MilosKozak** [comment]
it's by design ... discussed in other issues. search for it
