### ISSUE TITLE
[2.6.1] No upload of local profile to NS

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2537]
Build 9a26f7b2f-2020.03.21-18:07
LP not uploaded to NS (heroku) from my Pixel 2 with Android 10

What I tried so far:
- Created new profile in NS
- LP tab in AAPS, select profile and press button 'activate profile'
- Wait some time and check that NSClient queue is 0

Can provide logs by mail if neccessary. Thanks.

**Comment by MilosKozak** [comment]
tested now and working
profile definition is sent to NS once you SAVE
profile switch once you ACTIVATE
provide logs if you can replicate

**Comment by xJoe** [comment]
Sorry, I do not understand completely. How to save LP? In LP Tab there is only button activate profile. Tx.

**Comment by xJoe** [comment]
Am I right that only profiles created after switching on "upload local profile changes to NS" are uploaded? Will try to proof this with a copy of my existing profile.

**Comment by MilosKozak** [comment]
upload profile must be on
then everytime you press save
