### ISSUE TITLE
Project Research 

### ISSUE THREAD

**Issue by gabriellm1** [MilosKozak/AndroidAPS#2538]
Hey guys, my name is Gabriel and I'm a computer engineering student in Brazil. I'm developing a real human glucose simulator for my technological research which would help open-source artificial pancreas to be tested. Do you guys have any test mode for AndroidAPS? I know OpenAPS is working on a simulator but I couldn't discover how to use.

Thanks in advance.

**Comment by MilosKozak** [comment]
it's possible with insilico branch

**Comment by gabriellm1** [comment]
I there any guide on how to use it?

**Comment by MilosKozak** [comment]
there is a subdir in root directory with sample batch files
