### ISSUE TITLE
High power consumption

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#254]
I use AAPS 1.3rc2 on a honor 8 with andoird 6 and aaps uses lot of power.
Virtual Pump.
Intern NS Client.

What is strange is loop is disabled so I wonder why aaps is using so much power.

See sreenshot:
![2017-05-20 12 43 00](https://cloud.githubusercontent.com/assets/24234385/26553785/7055094e-448d-11e7-9df9-59f1921729bf.png)

Let me know which other information you need to better understand issue.

Thanks.

**Comment by MilosKozak** [comment]
update to latest version. there is lot of optimalisations since 1.3

**Comment by diabetesdt1** [comment]
I use the dev-branche. 
In the 1.5, there is used really a lot more Energy. Version 1.46 works good, the 1.5x used really more. I switched back to 1.46 :-( comes it from the new execute-service? Do you need the Logs or how can i report the needed Data/Logs?

**Comment by MilosKozak** [comment]
it has been fixed yesteday.

**Comment by diabetesdt1** [comment]
ah ok. Thx Milos, today i have not download the latest changes. i will try it. thx

**Comment by gregorybel** [comment]
Hi Milos 

I use 1.46 since 1 week and I forgot to write results but I don't see any differences. 

What I really wonder is that I don't loop, so is doing the app when not looping? Why so much power consumption?
