### ISSUE TITLE
Integrate AndroidAPS with Google Assistant

### ISSUE THREAD

**Issue by Ljuslykta** [MilosKozak/AndroidAPS#2544]
I was thinking about this feature. To activate Google Assistant and issue for example "Use calculator with 25 grams of carbs", "Give 2 units of insulin" or "Add 30 grams of carbs over 2 hours". I think this feature would increase the ese of use in that AndroidAPS would not need to be opened.

**Comment by PoweRGbg** [comment]
I was considering something like this a year ago, but came to the conclusion that It's not safe enough. Of course you could add a confirmation about the bolus, but still sounds pretty risky doing a bolus through a third party app.

**Comment by guydavies** [comment]
Wow. I agree. Imagine a conversation where you tell your partner "I decided
to give two units of insulin" and Google hears that and gives another two
units of insulin. No! That's crazy dangerous. How would it know that it was
me and not some random person? And if there needs to be a confirmation on
the phone, the extra convenience is lost.

**Comment by MilosKozak** [comment]
I agree with comments.
