### ISSUE TITLE
Bolus calculator does not account for negative carb time in bolus calculation

### ISSUE THREAD

**Issue by Suchiman** [MilosKozak/AndroidAPS#2549]
For example, when you're predicting a hypo and you eat something big (~70g carbs) and 45 minutes later you remember that you didn't bolus for it so you go into AAPS, open bolus calculator, enter 70g carbs with -45 minutes offset with a current glucose of 110mg/dl (rising) and it calculates the bolus as if you were eating now. If you instead go and first enter the carbs via the carbs button 45 minutes in the past, then the overview will show that it already has absorbed 20g carbs and the bolus calculator will suggest much fewer insulin.

**Comment by MilosKozak** [comment]
yes. this cannot be changed. at the time of wizard calculation there is no carbs record in history thus cob calculation is not possible
