### ISSUE TITLE
[SMS Communicator] Security: There is no OTP request for some LOOP commands

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2554]
LOOP DISABLE/STOP, ENABLE/START, STATUS and RESUME are **not** verified with OTP, while 

LOOP SUSPEND **is** verified. So I can stop and start the Loop without verification, but I can't suspend it..? Is this behaviour a bug or by design?

If you feel this should be changed, feel free to assign to me and I will look at it.

![2020-04-05 23 06 08](https://user-images.githubusercontent.com/6748615/78547730-d90b8c80-77ff-11ea-9704-63eb6a802fa8.jpg)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/8a731a9187982dab3dd26fa5718e8b427f436af1
