### ISSUE TITLE
[SMS Communicator] UX: Allow localized characters in SMS texts

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2557]
At present, all diacritical marks are removed before sending replies. I don't know the background or reason for this. Would be nice if it can be fixed.

Solution: Remove SmsCommunicatorPlugin-kt , line 903:

[  s = s.replace("[\\p{InCombiningDiacriticalMarks}]".toRegex(), "")  ]

**Comment by MilosKozak** [comment]
by removing it SMS is sent with 7bit encoding and can be longer

**Comment by Mackwe** [comment]
Fair point. But does AAPS ever send 160+ characters in a text message? Or can we make sure it never does?

**Comment by MilosKozak** [comment]
depends on pump status
