### ISSUE TITLE
2.6.1 Medtronic pump permanently suspended

### ISSUE THREAD

**Issue by Zaker120** [MilosKozak/AndroidAPS#2560]
Overview screen show pump suspended,pump history shows suspend event from 30.00.2060

AndroidAPS.log shows these entries

> 14:09:59.103 [Thread-91] D/PUMP: [MedtronicHistoryData.processNewHistoryData():481]: ProcessHistoryData: 'Delivery Suspend' Processed [count=0, items=[]]
14:09:59.104 [Thread-91] E/PUMPCOMM: [DateTimeUtil.toLocalDateTime():52]: Error creating LocalDateTime from values [atechDateTime=60, year=2060, month=0, day=30, hour=0, minute=20, second=60]. Exception: Value 60 for secondOfMinute must be in the range [0,59]
14:09:59.104 [Thread-91] E/PUMP: [MedtronicHistoryData.finalizeNewHistoryRecords():267]: Problem decoding date from last record: {}PumpHistoryEntry [type=Suspend              [30 , 0x1E], DT: 30.00.2060 00:20:60, length=2,5,0(7), data=No data]

[AndroidAPS_LOG_1586344220787.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4481692/AndroidAPS_LOG_1586344220787.log.zip)

**Comment by andyrozman** [comment]
Can you try reseting the pump in clearing its memory? That would be the easiest way to get this solved...

**Comment by Zaker120** [comment]
Thanks,its worked
