### ISSUE TITLE
NSClient uploads battery charge level of follower phone to Nightscout

### ISSUE THREAD

**Issue by PetraBangtsson** [MilosKozak/AndroidAPS#2562]
NSClient uploads battery charge level to Nightscout. This feature is not possible to switch off. This is a problem since it makes it hard to distinguish the important battery level - that is the one of the phone with AndroidAPS. Nightscout displays in its pill the lowest battery level of the ones uploaded. As a follower I cannot easly see if it is the AndroidAPS-phone or some of the other followers phones.

I would say that the most common case is that all followers are only interested in the AndroidAPS-phones battery level. But there has been some interest in keeping this feature with multiple upload, so to make it an option would be the best solution.

NSClient version 2.6.1.

**Comment by listerthrawn** [comment]
Confirm in 2.7 also

**Comment by MilosKozak** [comment]
reseolved in dev
