### ISSUE TITLE
wrong basal

### ISSUE THREAD

**Issue by JimZam** [MilosKozak/AndroidAPS#2566]

**Comment by JimZam** [comment]
Good morning. Sometimes Androidaps shows a BAS in the main screen different from Loop calculations. My basal at 12:00 is 0,6U/h and Openaps calculates it should be 90% for 30 minutes. The pump shows this but Androidaps main screen shows the full basal rate. See the attached images.
Thank you in advance
Kind regards

![1](https://user-images.githubusercontent.com/23319786/79067479-ddccb680-7cbf-11ea-8e0e-2e12062b98cb.jpg)
![2](https://user-images.githubusercontent.com/23319786/79067482-de654d00-7cbf-11ea-96dd-f09f239f14fc.jpg)
![3](https://user-images.githubusercontent.com/23319786/79067483-de654d00-7cbf-11ea-9496-a06077e7d4e0.jpg)
![4](https://user-images.githubusercontent.com/23319786/79067484-defde380-7cbf-11ea-8d36-a46553b383e6.jpg)
![5](https://user-images.githubusercontent.com/23319786/79067485-defde380-7cbf-11ea-9ba5-f3f7f38ca3c2.jpg)

**Comment by reijoahola-nightscout** [comment]
Is it the same as this issue ?https://github.com/MilosKozak/AndroidAPS/issues/2484

**Comment by JimZam** [comment]
Good evening. Yes, it's the same problem. I thought I had taken a photo of the main screen but I didn't so the difference couldn't be seen.
Thank you for your help.
Regards

**Comment by MilosKozak** [comment]
duplicated
