### ISSUE TITLE
AAPS stopped responding/running

### ISSUE THREAD

**Issue by kamilfb** [MilosKozak/AndroidAPS#2569]
Version 2.6.1
Build cffe1b439-2020.04-.01-08:50
Flavour: fullrelease

Noticed at 05:51 on 12 Apr 2020
When noticed, the app was unresponsive and became apparent it stopped working some time after midnight of that day.

Upon inspection of the log files, there seem to be a lot of exceptions:
 "Uncaught exception crashing app"
[AndroidAPS_LOG_1586667049024.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4473713/AndroidAPS_LOG_1586667049024.log.zip)

I had to restart the phone to recover as closing the app didn't seem to make any difference.

If I can be of any more help please do let me know.

**Comment by jotomo** [comment]
@kamilfb A fix for this has been released to the `master` branch as version 2.6.1.2.

**Comment by kamilfb** [comment]
Thank you @jotomo & @MilosKozak. Built and installed 2.6.1.2 - so far looking good. Many thanks
