### ISSUE TITLE
AAPS stop working (may be when cartridge change) - insight pump

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#2571]
AAPS stop working (only logo AAPS is appered), after restart running ok.
Reported by two users.
may be when cartridge change
log from one user included (errror is at the end, log downloaded when AAPS stop working)
AAPS  2.6.1
Insight pump
640G BG source (from ESEL)
[AndroidAPS (1).log](https://github.com/MilosKozak/AndroidAPS/files/4477484/AndroidAPS.1.log)

**Comment by jotomo** [comment]
@maskac  A fix for this has been released to the `master` branch as version 2.6.1.2.
