### ISSUE TITLE
Suspended Loop while using Extended Bolus

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2573]
When using Extended Bolus the (temporary!) loop suspension is ignored and it will always work as "Open Loop".

When the loop is fully disabled no suggestions are made.

Screenshot:
![Screenshot_20200416-162553](https://user-images.githubusercontent.com/5219415/79468484-43da7600-7fff-11ea-8e60-2b7982afbfb9.jpg)

Shouldnt the suspension take precedence over the ExtendedBolus=>OpenLoop force?

(Version: 2.6.1, Dana RS pump)

**Comment by MilosKozak** [comment]
sorry this is not possible to implement with current code at the moment
