### ISSUE TITLE
Cancel tt with automation

### ISSUE THREAD

**Issue by RainerTischnet** [MilosKozak/AndroidAPS#2575]
no bug
 i would like an improvement in the automation, cancel tt by selecting the name of tt. that would be a sensible improvement.thank

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by PoweRGbg** [comment]
Why do you need to cancel a specific TT when there can be only one set? If there is a specific condition not to set this TT maybe you can include it in the recipe which is setting. 
For example I have a recipe which sets Hypo TT when BG is below 4.5 mmol and COB is less than 15g ( so that meals are excluded from this recipe.

**Comment by RainerTischnet** [comment]
I have various tasks for automated tasks. for example high or low. cancel at 95 or rise and fall slide. unfortunately, cancel the meal  tt.

**Comment by PoweRGbg** [comment]
I think I gave you the solution in my previous answer. If you don't want to cancel your meal tt - add a check for COB or "Boulus ago" in the recipe that cancels the meal TT. If this is not enough - please be more specific and include screenshots of what exactly you are doing.

**Comment by MilosKozak** [comment]
closed by inactivity
