### ISSUE TITLE
2.6.1 minor SMS from 2nd number set receiving result twice

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2576]
![IMG_20200417_225914](https://user-images.githubusercontent.com/12038874/79613683-46bc9000-80ff-11ea-8e30-9b60f2a9dd52.jpg)
![IMG_20200417_230014](https://user-images.githubusercontent.com/12038874/79613684-47552680-80ff-11ea-98bb-b36ba9c62066.jpg)

2nd number set (white bg) - when sending sms command, the "applied" message is  send twice to second number in setting.

It works fine when 1st number in aaps sms settings is sending commands.

**Comment by MilosKozak** [comment]
i saw this issue on some phones when android sends SMS twice
... assuming you have the number in preferences only once.
There is nothing more  I can do with this
