### ISSUE TITLE
Audible alarm in open loop to notify changes?

### ISSUE THREAD

**Issue by qwerty1203** [MilosKozak/AndroidAPS#2580]
My phone only vibrates to tell me of a suggested change in open loop mode? Is there anything in preferences so AndroidAPS can send an audible notification instead of vibrating? I cant find anything.
Thanks!

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
if you turn on notifications as android notifications you can define it in android
