### ISSUE TITLE
Overview "Show Extended Status lights..."

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2585]
Dev: 2.6.5

On my Realme X2 PRO the reservoir info is not shown on portait mode, I think would be better change "Days" and "Hours" to "D" and "H" to be able to get more info on screen.

![Screenshot_2020-04-20-11-13-57-70_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79741659-89e25300-82f9-11ea-8f7b-46caf4cb3c6b.jpg)
![Screenshot_2020-04-20-11-14-03-57_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79741662-8b138000-82f9-11ea-8b52-ebad66acb2a3.jpg)

**Comment by MilosKozak** [comment]
resolved by https://github.com/MilosKozak/AndroidAPS/commit/9d83ff0cc358a21dca117e93cc9dbe1e310746d8
