### ISSUE TITLE
2.6.5_dev freezes on RUN NOW in OAPS or LOOP tabs

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2590]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

- Problem occurred at 15:03 CEST 25/04/2020
- Build 8f8fe39bf-2020.04.24-16:44
- Logs attached
- When testing the above image on a MotoG5S, the application freezes when the RUN NOW button is pushed in either LOOP or OAPS tabs.  I've also seen this on a MotoG7 Power.  The application takes long enough that a warning is raised to "close the app" or "wait".  I have factory reset the MotoG5S prior to testing so it has nothing else running on it except for Google's/Moto's default apps.  It's running Android 8.1 (stock Motorola OS).

[AndroidAPS._2020-04-24_21-50-37_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4533003/AndroidAPS._2020-04-24_21-50-37_.0.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4533004/AndroidAPS.log)

**Comment by guydavies** [comment]
It appears that more importantly, LOOP/OAPS don't actually work in open loop at all on my MotoG5S.  I've been running for some time now with the 2.6.5_dev as the receiver and it's not proposing any TBR despite my falling to 94mg/dl and a downward trajectory. Typically, this would trigger a zero TBR at least for a short while to fix that downward trajectory and get back towards my target of 110.

**Comment by MilosKozak** [comment]
resolved

**Comment by guydavies** [comment]
Confirmed.  I'm now testing the 2.6.5_dev image more seriously on a MotoG5S.
