### ISSUE TITLE
2.6.5_dev update from 2.6.1_release switches SVG source from Xdrip+ to Dexcom (Patched)

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2592]
- The issue happened yesterday when I first upgraded from 2.6.1 release to 2.6.5 on my main phone (a MotoG7 Power).  I'm afraid I don't have an exact time for the initial installation.
- The Build is 8f8fe39bf-2020.04.24-16:44
- The logs are attached
- When upgrading from 2.6.1 release to 2.6.5 dev, I eventually noticed that my setting of Xdrip+ as the source of SVG data had automatically switched to Dexcom (Patched).  This appears to be the default because that was also chosen when I installed fresh to the MotoG5S I'm currently using as a tester (having switched back to 2.6.1 on my main phone).  This doesn't seem to be a nice behaviour on upgrade.  Having got everything setup on my MotoG5S, it seems like Xdrip+ (plus 600SeriesAndroidUploader for my Medtronic 640G + Enlite) is working nicely (except for the issue reported earlier with LOOP/OAPS not running - a fairly major issue).

[AndroidAPS._2020-04-24_18-35-47_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4533043/AndroidAPS._2020-04-24_18-35-47_.0.zip)
[AndroidAPS._2020-04-24_18-36-56_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4533045/AndroidAPS._2020-04-24_18-36-56_.0.zip)
[AndroidAPS._2020-04-24_18-36-56_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4533046/AndroidAPS._2020-04-24_18-36-56_.1.zip)

**Comment by CaroGo** [comment]
Had the same on poco f1... Switched to patched dex app as source...

**Comment by Alamo04** [comment]
Confirmed

**Comment by jroth-haj** [comment]
confirmed on S5 with Lineage 16

**Comment by MilosKozak** [comment]
this is really huge update
![image](https://user-images.githubusercontent.com/11146458/80466271-993a4f80-893c-11ea-8d8f-aa1c5a76ab06.png)
lot of things changed internaly. it's a new app inside
settings must be reviewed after update

**Comment by guydavies** [comment]
I accept that.  But if certain settings are *known* to be reset to a particular value, it's probably worth release noting it.
