### ISSUE TITLE
2.6.5_dev completely unusable on MotoG3

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2593]
I tried using my overnight phone (my son's old MotoG3 running RR7.0.2 [Android 9]) to test the 2.6.5_dev test image and it wouldn't successfully start to the point of even displaying the main overview screen.  This was an upgrade from 2.6.1 release (since reverted) with Xdrip+ and 600SeriesAndroidUploader with my Medtronic 640G/Enlite, which works fine, if a little sluggishly.  The phone runs no other apps (not even the majority of the GApps - I installed a minimal set to ensure that the phone was as lightweight as possible).  The app just sat until it raised the warning that AAPS wasn't responding, "Close App" or "Wait".  Waiting just waited until the next warning.

I can add logs later if you wish but hopefully the logs from my other two phones, which I've uploaded on three recent cases should give hints as to what's happening.

**Comment by MilosKozak** [comment]
this is not much helpfull. provide logs or close the issue

**Comment by MilosKozak** [comment]
resolved in dev
