### ISSUE TITLE
2.6.5_dev NS profile change results in double entry in treatmens

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#2595]
**Issue**
Changing the NS profile results in double entry in the tab treatment/profile switch.

**Enviroment**
- AAPS 2.6.5_dev
- NS 13.0.1
- Phone LineageOS 16 (Android 9)
- Pump MDT 722, RL 2.0

**Comment by MilosKozak** [comment]
cannot reproduce. 
test with disabled NSClient

**Comment by MilosKozak** [comment]
closed by inactivity

**Comment by jroth-haj** [comment]
![image](https://user-images.githubusercontent.com/1705174/81380082-86790500-910a-11ea-986d-a5873418cbba.png)

same after pausing nsclient
![image](https://user-images.githubusercontent.com/1705174/81380350-0dc67880-910b-11ea-8f07-d8effd4af94b.png)

**Comment by jroth-haj** [comment]
Only the last profile change has a double Entry in the list.profile change.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/3d1b5003953ba1b1e93f2d151056bc590316fbee
