### ISSUE TITLE
2.6.5_dev no open Loop

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#2597]
**Issue**
Changing from closed Loop to Open Loop in Config Builder the Loop status stays in Closed Loop.
Checking Config Builder again there is still open Loop selected.
MDT Driver isn't able to connect to the pump.
In closed Loop it's able to connect.

**Enviroment**
- AAPS 2.6.5_dev
- NS 13.0.1
- Phone LineageOS 16 (Android 9)
- Pump MDT 722, RL 2.0

**Comment by MilosKozak** [comment]
tested now with MDT driver, open/closed loop . all fine.
Provide screenshots/logs

**Comment by MilosKozak** [comment]
closed by inactivity

**Comment by PoweRGbg** [comment]
OK

**Comment by jroth-haj** [comment]
This bug only appeared in the special dev-build version and no longer occurs.
