### ISSUE TITLE
2.6.5_dev MDT Pump Driver wasn't read completely (only history), so loop doesn't start. 

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2599]
Want to test today's new dev 2.6.5 but:

Closed Loop is not working on my system with Medtronic 754, Samsung S7, RL v2.0,  G6,  because MDT driver didn't read all pump settings at first connection.
Only history was read, then the driver freezes before reading status batterie-, basal....
So loop didn't start and I had to go back to Master 2.6.1.2.

Sorry, no logs available.

**Comment by MilosKozak** [comment]
MDT driver is updated now. I tested as working.
Open new issues with logs if the problem persists
