### ISSUE TITLE
[2.6.1] Deleted treatments are not deleted on NS

### ISSUE THREAD

**Issue by sennierer** [MilosKozak/AndroidAPS#2603]
NS: 13.0.1
AAPS: 2.6.1

I am using AAPS in open-loop mode with the insight flavoured virtual pump.
When deleting e.g. a carb intake treatment it is deleted in AAPS, but not in NS.

This is not a direct problem for AAPS, but e.g. if you use OpenAPS Autotune or create reports via NS.

**Comment by MilosKozak** [comment]
this is common feature witch should work .... if you are able to reproduce you can check what's sent to NS onm NSClient tab

**Comment by sennierer** [comment]
Just tried to reproduce it and it worked fine. Found out yesterday that I had Xdrip+ not configured correctly and it double uploaded everything to NS. When I deleted something via AAPS only one of the two entries was deleted obviously. So deleting entries in AAPS is working as intended.
Sorry for that.
