### ISSUE TITLE
Time not displayed correctly in automation screen

### ISSUE THREAD

**Issue by EasyKey5** [MilosKozak/AndroidAPS#2606]
![APS-Issue-Time](https://user-images.githubusercontent.com/58390605/80534082-95d3b200-8996-11ea-9ba6-98792ca12852.png)

I made an automation to lower the profile if I'm below 8.0 mmol and the time is between 10:00 pm and 11:00 pm but as you can see, the time is 9:17 and it has just activated. This could possibly be something to do with time zones? I'm not really sure but it needs to be fixed because it could be dangerous for people who use a lot of automations which activate at the wrong time.
I'm using a Pixel 2 with APS version 2.6.1

**Comment by MilosKozak** [comment]
i cannot replicate the problem

**Comment by MilosKozak** [comment]
can you do more test and provide more info?

**Comment by MilosKozak** [comment]
can you test it in current dev branch?

**Comment by EasyKey5** [comment]
# Dev Branch

The same thing happened in the dev branch: 

![Incorrect Time](https://user-images.githubusercontent.com/58390605/82740346-e47b2e80-9d3f-11ea-9a69-d386f77106a7.png)

---

After doing this, the app crashed and now I just get this screen so that's all the testing I could do unfortunately

![AAPS Crashed](https://user-images.githubusercontent.com/58390605/82740376-23a97f80-9d40-11ea-8e2a-d69ad3bb1179.png)


Maybe this could be an issue with my specific settings, which carried over after switching to the dev branch, or possibly just my phone?

**Comment by MilosKozak** [comment]
send me logs with the crash

**Comment by EasyKey5** [comment]
# Logs

[Here are my log files](https://github.com/MilosKozak/AndroidAPS/files/4672532/AndroidAPS_LOG_1590268599399.log.zip)

**Comment by MilosKozak** [comment]
current dev is 2.6.6

**Comment by EasyKey5** [comment]
# Dev 2.6.6

I ran that version on a Pixel 3a emulator to see if was to do with my phone, but the same isse occured:

![AAPS-Emulator](https://user-images.githubusercontent.com/58390605/82752072-85ef9800-9db3-11ea-9f83-bbdad6f487ae.png)


![AAPS-Emualator-About](https://user-images.githubusercontent.com/58390605/82752074-8851f200-9db3-11ea-8943-277d64da7013.png)

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/82761320-0d5ffa00-9dfa-11ea-981f-62673d42306f.png)
![image](https://user-images.githubusercontent.com/11146458/82761329-1781f880-9dfa-11ea-9ac5-01c8bc86442a.png)
I still cannot replicate the issue even on new Pixel3a EMU with Android 10

**Comment by CaroGo** [comment]
Works for me too (poco f1, Dana R,) no issues in time settings..

**Comment by MilosKozak** [comment]
what's your timezone?

**Comment by EasyKey5** [comment]
I'm in GMT + 1:00 (British Summer Time)

**Comment by EasyKey5** [comment]
# 1 o'clock

Ok this is weird - when I set the start or end time to 1am (but not pm), it shows the correct time.
Not sure what's going on there

**Comment by EasyKey5** [comment]
In the current dev version (2.6.7-beta1) this issue is fixed
