### ISSUE TITLE
2.6.5_dev Empty graphs

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2609]
2.6.5_dev  is unusable on my loop phone (Samsung A40 Android 10 with pump Insight and xDrip)

Nothing is shown on graphs, and application seems to use 4000% of processor capacity...

After each action (ex click on hamburger menu), I have to wait about 15s or 20 s before seeing a beginning of something... (even if I try to switch to a recent other application, it takes a very long time before action)

![2 6 5 dev](https://user-images.githubusercontent.com/52934600/80762866-a6725c80-8b3d-11ea-94f2-7b760e787363.jpg)

I don't have this problem with latest version of Dagger3 branch...

And on my dev phone (low cost "Logicom le Hola" Android 8.1, virtual pump and BG Source NSClient) 2.6.5_dev works...

=> If you want some logs I'll send them tomorow

**Comment by Philoul** [comment]
Good news, this morning, with the latest commits, AAPS is running like a rabbit!
But I still have empty graphs...

![Screenshot_20200501-100407_AndroidAPS](https://user-images.githubusercontent.com/52934600/80792062-ccc2e700-8b93-11ea-9bd5-1ef3bff15f28.jpg)


[AndroidAPS_LOG_1588319536302.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4562972/AndroidAPS_LOG_1588319536302.log.zip)

**Comment by MilosKozak** [comment]
i believe you fixed it already

**Comment by Philoul** [comment]
On the lastest versions, it worked (I regularly refresh my Autotune branch on which I work with the dev branch).
