### ISSUE TITLE
2_6_5_Dev Lower units on the Y axis are truncated on secondary charts (minor)

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2618]
My phone is a Samsung A40

I have the default font and default font size, 
=> I have to set my phone to the minimum size if I want to see the whole charaters (but it's very small to read it...)

![Y_unit_truncated](https://user-images.githubusercontent.com/52934600/80973001-183cf580-8e1f-11ea-882f-add6025ca190.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/2d3f1323dd6f4f62060e1d3ec2cc6b98de661844

**Comment by MilosKozak** [comment]
it's a bug in library.
i don't know how to fix it .... but you may play with if you wish
