### ISSUE TITLE
[Insight] delayed bolus is recorded as normal bolus

### ISSUE THREAD

**Issue by Suchiman** [MilosKozak/AndroidAPS#2622]
The insight pump supports a delayed bolus where you can set to give e.g. 2U of insulin IN 15 minutes (not over 15 minutes).
If you do that, AAPS will record the 2U as if they were given at the time of entering.

```
04:22:30.756 [Thread-114853] D/DATATREATMENTS: [TreatmentService.createOrUpdate():338]: New record from: PUMP Treatment{date= 1588645293000, date= 05.05.2020 04:21:33, isValid= true, isSMB= false, _id= null, pumpId= 1577118925188, insulin= 2.0, carbs= 0.0, mealBolus= false, source= 1}
```
[aaps.log](https://github.com/MilosKozak/AndroidAPS/files/4578889/aaps.log)

**Comment by MilosKozak** [comment]
rule #1 do not touch pump and do thing sonly supported by apps

**Comment by TebbeUbben** [comment]
This feature is called "lag time". The new version of the Insight driver I'm working on will support this.
