### ISSUE TITLE
2.6.5_dev profile button in Actions appears briefly then disappears

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2625]
when I scroll to the Actions tab, initially the profile switch button is there but it immediately disappears. see the linked video. 

https://photos.app.goo.gl/NcMUcYMKAV4ntEcv9

this isn't critical since I can switch profiles from the main screen but it's a visual irritant. 

this has been in all the Dev builds I've used so far.

**Comment by Philoul** [comment]
I have quite the same problem but for me it's not the Switch Profile button, it's the Extended Bolus button...

I see it in flash and it disappears immediatly.

It's not really a problem for me because I never use it, but I don't find other way to send an extended bolus without that button...

**Comment by MilosKozak** [comment]
i fixed this behavior in dev hopefully, retest please

**Comment by guydavies** [comment]
I tried this in 2.6.6_dev 9c472e4e0 from around lunchtime yesterday CET. It
still wasn't working then. I'll try updating again to the latest version
this morning.

**Comment by guydavies** [comment]
I just updated my MotoG7 power to 2.6.6_dev c03a89db1 and it still exhibits the problem with the Profiles button in the Actions tab, as does the MotoG LTE I use as my regular backup phone.

**Comment by MilosKozak** [comment]
i cannot reproduce it.... 
test fresh config pls

**Comment by guydavies** [comment]
Hi Milos

I tried to save my config and uninstall then reinstall after a reboot but
it still picks up the old config. How can I completely clean the config and
start again?

Rgds

Giy

**Comment by MilosKozak** [comment]
in android settings - apps - AndroidAPS - clean data

**Comment by guydavies** [comment]
Hi Milos,

This completely drops me back to the start of the objectives.  I was at objective 6.  I don’t want to jump right to the end of the objectives, that doesn’t make sense, but I also don’t consider going back to the start a reasonable cost of fixing a broken UI element.

Rgds,

Guy

**Comment by MilosKozak** [comment]
send me your config

**Comment by guydavies** [comment]
Thanks. Which email can I use to send you the file and the encryption code?

Rgds

Guy

**Comment by MilosKozak** [comment]
milos@androidaps.org

**Comment by CaroGo** [comment]
Another display issue....I check local profile to be displayed in tabs, but it does not appear and I. settings it unchecks itself... Should I open a new issue for this?

**Comment by guydavies** [comment]
There's already an open issue for that. I don't have the number but I
opened it shortly after 2.6.5_dev was released.

**Comment by EknalpTiel** [comment]
> Another display issue....I check local profile to be displayed in tabs, but it does not appear and I. settings it unchecks itself... Should I open a new issue for this?

This is a known bug:
#2591

**Comment by MilosKozak** [comment]
i believe it was caused by not enabled engineering mode
I removed this restriction anyway

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/b2b1485c273e6edd4152a0543701cc4329d25137

**Comment by guydavies** [comment]
Confirmed.  Works exactly as expected.

Rgds,

Guy
