### ISSUE TITLE
2.6.5_dev Changing Range for Visualization results in ANR and crash

### ISSUE THREAD

**Issue by dlvoy** [MilosKozak/AndroidAPS#2629]
Tested on 2.6.5 branch: dev [cf291b3]

When changing LOW mark or HIGH mark in preferences: (Preferences->Overview -> Range for Visualization) just after updating preference field app hangs and Android ANR dialog is shown (AndroidAPS isn't responding) which results in crash.

`
2020-05-08 08:14:07.203 21404-21425/? E/ActivityManager: ANR in info.nightscout.androidaps (info.nightscout.androidaps/.activities.PreferencesActivity)
    PID: 28259
    Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 1.)
    Load: 3.95 / 4.88 / 3.17
`

Reproduced both on simulator and device (Samsung Galaxy S8 SM-G950F). On device after ANR app was hanging afterwards on each reopening, but was successfully started after device restart.

**Comment by pjdjesus** [comment]
I got similar behaviour. When I've tried to change the LOW mark, the value was not set and the app has frozen. I had to kill the app a restart it.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/a241a23c99883826316ff66fb403fffb4533bfe7
