### ISSUE TITLE
Adjust OAPS outputs to small screens

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#263]
@MilosKozak is it ok if I switch back to the "old" layout file as fallback in case the screen is very small?
I believe the code to fill the layout has not changed.

**Comment by MilosKozak** [comment]
i already added checking for null for some elements like here
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/Overview/OverviewFragment.java#L1190
so all elements must not be on all layouts.
maybe you can go this way too and create another layout for extra small phones with only minimal elements needed

**Comment by yolk** [comment]
@AdrianLxM What device/display dimensions are your trying to optimize for?

**Comment by AdrianLxM** [comment]
@yolk I have been successfully using current "master" and previous versions on 2.4 inch phones. I will test "dev" on the same.

**Comment by AdrianLxM** [comment]
Works on a Jelly Pro.
