### ISSUE TITLE
2.6.5_dev MDT Alarm "Failed to update basal profile"

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#2630]
Failed to update basal profile
Basal profiles could not be set.

Logs sent by email.
![Screenshot_20200507-125317](https://user-images.githubusercontent.com/1705174/81379433-685ed500-9109-11ea-9983-7646f2278189.png)

**Comment by Alamo04** [comment]
Had this error in past versions too, but it happens only if pump was busy.
Perhaps a bolus was delivered in that time ?

**Comment by MilosKozak** [comment]
probably random error as i cannot reproduce
