### ISSUE TITLE
2.6.5_dev Desire to improve adjustments of preferences

### ISSUE THREAD

**Issue by jroth-haj** [MilosKozak/AndroidAPS#2631]
It is a very good improvement of the user experience to show the preferences in a fold-out manner.
Please add the collapse again.

![image](https://user-images.githubusercontent.com/1705174/81395346-c00a3a00-9123-11ea-9f77-5575c9df76b1.png)

**Comment by MilosKozak** [comment]
it's an android feature.  i don't know how to do this
