### ISSUE TITLE
Sync sportapp activities into AndroidAPS

### ISSUE THREAD

**Issue by wouterlemcke** [MilosKozak/AndroidAPS#2633]
AAPS offers the possibility to register an exercise from the careportal. I wonder whether it would be possible to sync/auto import exercises from a sportingapp.

E.g. I already register all my activities on Strava and Strava has the option to fire a webhook when an activity is uploaded. It would be awesome if the exercise is then automatically added to AndroidAps (and Nightscout)

**Comment by guydavies** [comment]
It's already possible to create a REST call to Nightscout to upload the
data. I do this using Automate on my phone to upload autodetected walks and
gym sessions. I don't think that there's a REST API into AAPS.  There is
the possibility to listen to broadcast data which may be an option.

**Comment by MilosKozak** [comment]
you can do it through NS
