### ISSUE TITLE
strange profile switch to "unknown" profile

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2640]
Using AAPS 12.6.1.2 ; Nightscout 13.0.1 
I noticed a profile switch I can not remember having issued. On monday 10.5.20 at 22.40 h (a time I would rarely do any profile switches and indeed I am pretty sure not having done this) the profile changed to a profile named "primero". This profile isn´t available in local profile tab or in nightscout profiles. I changed profiles a few times 4 h before this happend... but that should not be a explanation for this one....as I don´t know, where this profile and it settings come from...haven´t used a profile with that name in a very long time...actually I don´t even remember having used it at all...log files attached below! If this is no issue, please, please provide some hint to get an explanation of what went wrong! Just to understand!
[AndroidAPS._2020-05-10_15-15-35_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4614670/AndroidAPS._2020-05-10_15-15-35_.2.zip)

**Comment by MilosKozak** [comment]
12.6.1.2 is not supported version

**Comment by CaroGo** [comment]
OK, but you know that this version has no changes that affect the behaviour of the App itself...I hope this will not occur again.

**Comment by osodebailar** [comment]
As far as I am concerned I never do or did any changes to the algorithm in AAPS. 
I only work on a better usability and data presentation.

**Comment by MilosKozak** [comment]
the problem with supporting other versions is just time
it's even hard to support one exact build when you are doing it in free time
