### ISSUE TITLE
Latest DEV 2.6.6 (6h ago) - Not reading Medtronic pump

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2641]
Have only the Log.

With latest DEV the Medtronic pump 754 is not reading.
AAPS connects to RL and Pump, the first reading was "Get pump time" and there the reading stops.

##############################
at info.nightscout.androidaps.plugins.pump.medtronic.comm.MedtronicCommunicationManager.sendAndListen(MedtronicCommunicationManager.java:555) ~[na:0.0]
	at 
##############################

Sorry that I can`t give more information.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4618035/AndroidAPS.log)

System:
Samsung S7
Medtronic 754
RL 2.0

**Comment by Alamo04** [comment]
Bug still exists with latest "History Browser Fix".

**Comment by MilosKozak** [comment]
fixed in dev now
