### ISSUE TITLE
2.6.5_Dev GraphData lost in main screen after changing day in history browser

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2642]
As you can see in screenshots below, there is only one minute between these 2 screenshots ...
I can reproduce this issue easily from the image on the left:
1) Select History Browser
2) Change the day (I selected yesterday)
3) Return to the main screen => you lost all your graph data and you get an alert Missing BG readings
note: if you remain too long time in the History Browser with not today selected, you also get the alert
![GraphDataKoAfterHistory](https://user-images.githubusercontent.com/52934600/81737196-04853500-9498-11ea-8602-c44b02c14e0a.jpg)

To recover your graphs, just select again History Browser (by default today is selected), then go back to main screen and everything is Ok again...

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/c03a89db16988384c60b9e316d0d5610f8387480
thanks
