### ISSUE TITLE
2.6.6-Dev: Language bug Portuguese pt_PT vs. Portuguese, Brasilian pt_BR

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2646]
I selected Portuguese (from Portugal) and some itens are shown as Portuguese, Brazilian.

On this screen, "Carbs" button in Portuguese is Hidratos, and it's showing Carbos from Portuguese, Brazilian.

![Screenshot_2020-05-14-14-56-58-73_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/81943675-96558500-95f3-11ea-91aa-12e1fe8bcd75.jpg)

**Comment by MilosKozak** [comment]
sorry i don't know difference between this languages. Is it a global problem in app or this single button?

**Comment by parapenT1sta** [comment]
There are some expressions that are different. For example, inside of Actions tab.
Acções in Portugue - Portugal
Ações in Brazil.
but it's shown as Ações when I Select Portuguese and I translated as Acções.

**Comment by MilosKozak** [comment]
I added option to use language from android settings. Translations are changing when switching between pt and pt_BR.
I cannot do more

**Comment by parapenT1sta** [comment]
> I added option to use language from android settings. Translations are changing when switching between pt and pt_BR.
> I cannot do more

Thank you so much for your effort. Going to test it

**Comment by guydavies** [comment]
I also tested and it seems to work fine and also helps with the selection
of 24 hour time Vs 12 hour time. I had to switch the system to fixed 24
hour rather than taking the system default.

Rgds

Guy

**Comment by parapenT1sta** [comment]
I tested and now it's working if I select System Default! :) If I select Portuguese it mix Portuguese - Portugal with Portuguese - Brasil! 
Thank you so much!
