### ISSUE TITLE
[2.6.6_dev] Recent changes to graph1 lose data at the top (was an issue with numbers at the bottom)

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2648]
Since update 2d3f1323d, it appears that the second graph on the main screen (graph1) appears to now be shifted too high, so the top of the graph is lost because there's no scaling.  I'm running the latest 2.6.6_dev build 51ab43416.

The problem is always present.  Any graph that extends above around +5 on the lower graph is clipped.

![Screenshot_20200515-165147](https://user-images.githubusercontent.com/2486510/82065208-1b14d180-96ce-11ea-842b-0b402ba1850c.png)

**Comment by MilosKozak** [comment]
improved

**Comment by guydavies** [comment]
confirmed that this is much better. Thanks Milos for the awesome work.
