### ISSUE TITLE
2.6.6-dev: DanaRS history / TDD incorrect

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2650]
ADD TIME OF EVENT HERE: Right before dumping the log

AndroidAPS 2.6.6-dev
Build: 51ab43416-2020.05.15-18:24
Remote: https://github.com/MilosKozak/AndroidAPS
Flavor: fullrelease
Nightscout version: 13.0.1
Engineering mode enabled

Reading the TDD and/or insulin history leads to incorrect and incomplete results (see screenshots attached).

I'm mailing you the log right after opening this issue.
//EDIT: Log file sent to milos@androidaps.org

![Screenshot_20200515-211847](https://user-images.githubusercontent.com/5219415/82088598-5c1edd00-96f2-11ea-8783-aafbf3f6bebc.jpg)
![Screenshot_20200515-211838](https://user-images.githubusercontent.com/5219415/82088594-5b864680-96f2-11ea-9c1e-ed96c2eb7d7a.jpg)

![IMG_20200515_211656](https://user-images.githubusercontent.com/5219415/82088589-5923ec80-96f2-11ea-8e55-53f8f3f8d5d6.jpg)
![IMG_20200515_211704](https://user-images.githubusercontent.com/5219415/82088591-5a551980-96f2-11ea-9102-943b81cd31ab.jpg)
![IMG_20200515_211708](https://user-images.githubusercontent.com/5219415/82088592-5aedb000-96f2-11ea-9b97-dbfdbcac5fe4.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/e98e5ec9def030bcc5ce6969c5a36be4b006afab thanks!

**Comment by nshtg** [comment]
Can confirm the issues are fixed, thanks for fast response!
