### ISSUE TITLE
Dev 2.6.6 15.05.2020 21:00 - Phone size can't be set to 5.0", looks like 6"

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2653]
Last Build: 713f57343

I have choose the 5.0" Pixel phone for building, that was a good choise in the past for Samsung S7.

In this version now the Ui seems to be fixed fo 6.0" devices, because I can scroll the screen a lot. Normaly I can't scroll the display because it was optimised for 5.0".

That's not a big problem, only a optical thing. I can scroll back to see and reached what I need.

Using:
Samsung S7
Medtronic 754
RL 2.2

**Comment by MilosKozak** [comment]
UI will never be perfect for all sizes
