### ISSUE TITLE
2.6.6_dev crash and hang on communication with medtronic pump

### ISSUE THREAD

**Issue by ToreBj** [MilosKozak/AndroidAPS#2654]
Starts and establishes communication with Medtronic pump 554 W. After a little while the pump  communication hangs and looping is prevented. 
Reinstalling 2.6.1 without restarting RL the looping is stable
![AAPS266dev](https://user-images.githubusercontent.com/23278852/82130393-44ffee00-97cb-11ea-89a0-835ff0cfe7e5.jpg)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4639400/AndroidAPS.log)

**Comment by ToreBj** [comment]
I have switched to my 515 pump and it is completely stable. I'm using the same RL. ??

**Comment by MilosKozak** [comment]
i don't see any issues on my 522 pump too

**Comment by ToreBj** [comment]
After some research I have found that my 554 pump works fine after removing "other devices" in "connect devices" under "utilities". This has to do with the "Mysentry option" which I used when testing the Loop app on Iphone. This is(Mysentry) not supported for the Medtronic implementation in AAPS, and seems to disturb the communication somehow.
