### ISSUE TITLE
Hallo Milos, Die Automatisierung hat einen einprogrammierten Profilwechsel auf 130% ausgeführt, da der Blutzucker entsprechend gestiegen war. Die Basalrate wurde auf 430% gesetzt, obwohl  der Sicherheitsmultiplikator  der aktuellen Basalrate auf Faktor4, wie empfohlen,  begrenzt war AAPS 2.6.1 Könnte das ein bug sein?

### ISSUE THREAD

**Issue by emwz** [MilosKozak/AndroidAPS#2656]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by emwz** [comment]
respective issue 2656

![Screenshot_20200518-185742_Photos 1](https://user-images.githubusercontent.com/65556266/82240297-79de8300-993a-11ea-8b89-44c74333614d.jpg)

![Screenshot_20200518-185751_Photos 1](https://user-images.githubusercontent.com/65556266/82240414-ae523f00-993a-11ea-9c8d-5e3393adb482.jpg)

[AndroidAPS._2020-05-17_08-59-11_.0[1].zip](https://github.com/MilosKozak/AndroidAPS/files/4645464/AndroidAPS._2020-05-17_08-59-11_.0.1.zip)

**Comment by dlvoy** [comment]
@emwz please / bitte:
- Englisch verwenden, nicht jede ist Deutschsprachige
- make title simple sentence, and not problem description - for that use Issue body

**Comment by emwz** [comment]
Oh, of course. I didn't realize there was anything wrong with that.

 

Von: Dominik Dzienia [mailto:notifications@github.com] 
Gesendet: Dienstag, 19. Mai 2020 20:07
An: MilosKozak/AndroidAPS
Cc: emwz; Mention
Betreff: Re: [MilosKozak/AndroidAPS] Hallo Milos, Die Automatisierung hat einen einprogrammierten Profilwechsel auf 130% ausgeführt, da der Blutzucker entsprechend gestiegen war. Die Basalrate wurde auf 430% gesetzt, obwohl der Sicherheitsmultiplikator der aktue

 

@emwz <https://github.com/emwz>  please / bitte:

*	Englisch verwenden, nicht jede ist Deutschsprachige
*	make title simple sentence, and not problem description - for that use Issue body

**Comment by emwz** [comment]
please delete this issue and take a look at the new one #2662
