### ISSUE TITLE
heroku deployment

### ISSUE THREAD

**Issue by alexfos** [MilosKozak/AndroidAPS#266]
Hello guys, i am trying to set up a Heroku deployment and i am getting an error after setting the command

On a Windows machine, either set it in the System Properties/Environment Variables, or do it from the terminal:
> set HTTP_PROXY=http://proxy.server.com:portnumber
or
> set HTTPS_PROXY=https://proxy.server.com:portnumber
> heroku login

Then i am trying to log in HEROLU
and i get this message: 

ECONNRESET: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.server.com proxy.server.com:0

Do you know how i should proceed?

**Comment by PoweRGbg** [comment]
Do you use a proxy server ( do you need one ) ? If not then I think it's not needed to set it in the enviroment of your windows machine.
