### ISSUE TITLE
safeta multiplier 4x current

### ISSUE THREAD

**Issue by emwz** [MilosKozak/AndroidAPS#2661]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
????

**Comment by emwz** [comment]
The  basal ratio was set on 430%,
even though the safety multiplier of the current basal ratio was limited on 4x.

![Screenshot_20200517-094713_AndroidAPS 1](https://user-images.githubusercontent.com/65556266/82420224-bec00200-9a7f-11ea-9584-c318d755b911.jpg)

![Screenshot_20200517-094927_AndroidAPS 1](https://user-images.githubusercontent.com/65556266/82420272-cda6b480-9a7f-11ea-86f7-9d3f211b712f.jpg)
