### ISSUE TITLE
Safety multitplier of current basal

### ISSUE THREAD

**Issue by emwz** [MilosKozak/AndroidAPS#2662]
Profileswich 130%  per automation,, safety multiplier of current basal is 4 as recommended, nevertheless AAPS has increased basal to 430%, not only 400% as anticipated! 

[AndroidAPS._2020-05-17_08-59-11_.0[1].zip](https://github.com/MilosKozak/AndroidAPS/files/4656094/AndroidAPS._2020-05-17_08-59-11_.0.1.zip)

![Screenshot_20200517-094713_AndroidAPS 1](https://user-images.githubusercontent.com/65556266/82434180-ca68f400-9a92-11ea-9f8e-1cdd2dec5c36.jpg)

![Screenshot_20200517-094927_AndroidAPS 1](https://user-images.githubusercontent.com/65556266/82434241-dc4a9700-9a92-11ea-983c-57f9c60fb2f7.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by emwz** [comment]
AAPS 2.6.1

**Comment by EknalpTiel** [comment]
Was war hier die Ursache?
Tritt dieser Fehler in der aktuellen Dev auch auf?

**Comment by emwz** [comment]
Ich nutze die  Version  master 2.6.1 

Safety multiplier war auf 4 eingestellt.

Basal wurde mit 430% gepumpt.

Liegt das am Profilswitch auf 130% (Automatisierung)?

 

 

Von: EknalpTiel [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Mai 2020 19:05
An: MilosKozak/AndroidAPS
Cc: emwz; State change
Betreff: Re: [MilosKozak/AndroidAPS] Safety multitplier of current basal (#2662)

 

Was war hier die Ursache?
Tritt dieser Fehler in der aktuellen Dev auch auf?

**Comment by Alamo04** [comment]
@emwz 
Hmmm...
Wenn ich das richtig sehe sind 4fach = 400%, diese beziehen sich auf die laufende Basalrate.
Weiterhin hast du die Basalrate ja auf 130% gestellt, hiernach richtet sich dann die restlichen Sicherheitseinstellungen.

Gehe ich jetzt mal von 1 I/E normale Basalrate aus, welche du auf 130% erhöht hättest, so wären 5.2 I/E möglich. Formel: 1x 1,3 x4 = max. 5.2 I/E

Kann mich aber auch irren.

Da ansonsten noch keiner diesen Fehler gemeldet hat, solltest du nochmal prüfen, ob es sich hier wirklich um einen Fehler von AAPS gehandelt hat.

**Comment by emwz** [comment]
Ich sehe das so:

Die Basalrate war auf 130% erhöht, konkret: von 0,25 auf 0,33. Diese 0.33 sind dann die aktuelle Basalrate und diese darf bis zum 4-fachen hochgesetzt werden. Da steht aber, dass sie auf 430% gesetzt wurde und genau das habe ich bisher nie beobachtet.

Hatte versuchsweise das Ganze nochmal händisch nachgegestellt, indem ich das Profil auf 200% hochsetzte und den Faktor auf 2 herunter gesetzt habe und da wurde, wie erwartet , diese quasi verdoppelte Basalrate nur aucf exact 200% erhöht.

Deshalb glaube ich, dass das ein bug war

 

Von: Mario [mailto:notifications@github.com] 
Gesendet: Mittwoch, 20. Mai 2020 22:22
An: MilosKozak/AndroidAPS
Cc: emwz; Mention
Betreff: Re: [MilosKozak/AndroidAPS] Safety multitplier of current basal (#2662)

 

@emwz <https://github.com/emwz> 
Hmmm...
Wenn ich das richtig sehe sind 4fach = 400%, diese beziehen sich auf die laufende Basalrate.
Weiterhin hast du die Basalrate ja auf 130% gestellt, hiernach richtet sich dann die restlichen Sicherheitseinstellungen.

Gehe ich jetzt mal von 1 I/E normale Basalrate aus, welche du auf 130% erhöht hättest, so wären 5.2 I/E möglich. Formel: 1x 1,3 x4 = max. 5.2 I/E

Kann mich aber auch irren.

Da ansonsten noch keiner diesen Fehler gemeldet hat, solltest du nochmal prüfen, ob es sich hier wirklich um einen Fehler von AAPS gehandelt hat.
