### ISSUE TITLE
2.6.6-dev History Browser several issues (very slow, portrait/landscape mode reset selected day)

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2667]
If we select a day in the history browser, it is very very long to obtain results (about 1min30s and once I timed more than 5 min ...)... too long to navigate

When we select and dedicated day and change phone orientation from landscape to portrait or from portrait to lanscape, History Browser don't keep all graph calculation and reset data to current day (so #2min to calculate again current day and #2min to reselect previous day and get results...).

In landscape mode main graph is unreadable on a phone see screenshot below

![Screenshot_20200521-223012_AndroidAPS](https://user-images.githubusercontent.com/52934600/82646011-1b542600-9c14-11ea-9aed-e4e9b30459f4.jpg)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/ec3ebd17dbdc17ba436e2dd7925e63224d933375
this is probably max we can do with current AAPS
