### ISSUE TITLE
pump-activity shown makes shortcut-buttons unavailable

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2668]
Since I switched pumps (from Combo to Dana) I noticed that the activity on the pump is shown on the homescreen on top of the (by me) most used buttons Swtich Profile and set Temp Target.
Unfortunately this is not a matter of a few seconds I can't use the buttons but it can take up to 30 seceonds waiting time.
**Request**: Prevent hiding the SwitchProfile/TT buttons and do show the pump-activity line _above_ the buttons, _instead of_ hiding them.

Screen 1: with the issue. during pump activity (the line with 'Wachten voor tijdsynchronisatie (31 sec)'--> Buttons are not available
![InkedScreenshot_2_LI](https://user-images.githubusercontent.com/28272471/82660276-5d886200-9c2a-11ea-88d1-75ad1d250459.jpg)

Screen 2: normal with the pump-activity text line (most of the time; when no communication task is running with pump --> Buttons are available.
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/28272471/82660257-55302700-9c2a-11ea-8b00-296161fca4dd.jpg)

AndroidAPS v 2.6.1

**Comment by MilosKozak** [comment]
this is by design. better that wasting of space just for pump comm line.
you can access these features from actions tab anytime
