### ISSUE TITLE
COB bug

### ISSUE THREAD

**Issue by modroocka** [MilosKozak/AndroidAPS#2673]
Hi there, we have realized of 10g and 20g carbs entered by AAPS itself. To this two times 0.1 SMB was recorded (before 7 a.m. On the screenshot). Later on, we sent meal bolus to 25g carbs. It is not readable in NS. Moreover, this is written as SMB and not as a bolus in treatment folder... Before 9 a.m. I sent a bolus via sms, and it is not visible in NS either. But IOB is correct. Any idea what is happening please? 
We did not make any update, neither the aaps nor the phone. We have set the aaps settings according to the wiki two months ago and we haven’t realized any of this since today. Pump is accucheck insight. 
![5B4D3D8B-0976-4F6A-B7DC-FABE26D2A448](https://user-images.githubusercontent.com/26759528/82787696-44202980-9e67-11ea-9dad-3674eeeaaa17.jpeg)
![44B30507-E953-4225-9D6D-FEB60B47BD98](https://user-images.githubusercontent.com/26759528/82787699-471b1a00-9e67-11ea-8523-ac0a1973bab5.jpeg)
![F2B9ED71-02BC-467A-9D74-50EA093D5BCB](https://user-images.githubusercontent.com/26759528/82787704-497d7400-9e67-11ea-9599-2b02f2f9e7f0.jpeg)
![DA22C891-3328-4328-8539-6DE5B9E4468D](https://user-images.githubusercontent.com/26759528/82787709-4b473780-9e67-11ea-97a1-674976d744f0.jpeg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4675874/AndroidAPS.log)

[AndroidAPS._2020-05-25_07-18-23_.0.log](https://github.com/MilosKozak/AndroidAPS/files/4675881/AndroidAPS._2020-05-25_07-18-23_.0.log)

**Comment by MilosKozak** [comment]
database is damaged, please reinstall AAPS
