### ISSUE TITLE
2.6.1. DanaRS wrong reservoir fill after change of low reservoir alarm

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2674]
AAPS 2.6.1 - build 9a26f7b2f-2020.03.21-18:07

Had to change reservoir around 1:00 tonight as I received an occlusion alarm at reservoir volume 14 units:
1. Prime & tube filling on pump (not AAPS)
2. Recorded reservoir change in action tab
3. Updated reservoir filling by pressing BT icon in Dana tab -> **274 units were shwon correctly**

A few minutes later I changed low reservoir alarm in Dana pump settings from 10 to 20 units and clicked Save options to pump. Right after that reservoir volume was **changed to 14 units** and alarm low reseroivr started. Had to fill tubing again to get correct reservoir volume.

Will send logfile to @MilosKozak . Here are some lines that might explain the problem:

00:57:13.379 [Thread-255487] D/PUMPCOMM: [DanaRS_Packet_General_Initial_Screen_Information.handleMessage():78]: Reservoir remaining units: 14.8

00:57:15.829 [Thread-255536] D/PUMPCOMM: [DanaRS_Packet_Option_Get_User_Option.handleMessage():103]: refillAmount: 14

01:13:48.691 [Thread-256284] D/PUMPCOMM: [DanaRS_Packet_APS_History_Events.handleMessage():188]: EVENT REFILL (11) 25.05.20 01:09:46 Mitteleuropäische Sommerzeit (1590361786000) Amount: 290.0U

01:16:16.770 [IntentService[DataService]] D/DATASERVICE: [DataService.onHandleIntent():54]: onHandleIntent Bundle{ delta => true; devicestatuses => [...]"reservoir":274,"clock":"2020-05-24T23:16:11Z"},...

01:20:06.520 [Thread-256490] D/PUMPCOMM: [DanaRS_Packet_Option_Get_User_Option.handleMessage():102]: lowReservoirRate: 20
01:20:06.520 [Thread-256490] D/PUMPCOMM: [DanaRS_Packet_Option_Get_User_Option.handleMessage():103]: refillAmount: 14

**Comment by MilosKozak** [comment]
i can confirm. it looks like it's a bug in RS firmware.
I tested RSv3 is not affected anymore => i'll report it but we can probably ignore it for now
