### ISSUE TITLE
[Feature Request] Import blood-glucose-value from Contour Next One by bluetooth

### ISSUE THREAD

**Issue by lolo49lala** [MilosKozak/AndroidAPS#2677]
Hi folk,

in advance, i will give my thanks for excellent job!

Is it possible to create a function to import bg values from blood glucose meter "Contour Next One" by using Bluetooth-connection?

And no, I dont use xdrip+ because I need sensor values in clarity, use a bolus-calculator in aaps and don't like to use a third app on my mobil.

**Comment by andyrozman** [comment]
I don't think that it is that easy... Protocol for Next is pretty complicated, and having Meter import in "Loop" software (AAPS in this case) is pretty useless. If you ant to import calibration you would have to use Xdrip for that... It has support for Next One (I use it myself)...

**Comment by MilosKozak** [comment]
I agree. this is a task for a CGM app
