### ISSUE TITLE
accu check pump

### ISSUE THREAD

**Issue by cduarte** [MilosKozak/AndroidAPS#268]
Hi

Any news abou work with accu check pump?

Thank

**Comment by MilosKozak** [comment]
sandra is working on it

**Comment by cduarte** [comment]
Good :) 

and to use accu check pump need a RileyLink or xDrip ?

Thanks a lot for the project!! Very good :)

**Comment by AdrianLxM** [comment]
More info can be found here: https://github.com/monkey-r/ruffy
