### ISSUE TITLE
Triple entry of carbs

### ISSUE THREAD

**Issue by lydiaengler** [MilosKozak/AndroidAPS#2683]
As reported on Facebook at 21.40 UK time 26 May 2020

Running 2.6.1.2 with Dana RS.

We have just now experienced a very worrying incident.

My wife was a little low, so when we had dinner we just put 20g of carbs in, no insulin, intending to rely on SMBs as her BG rose.

You can see the 20g on NS, but unfortunately the 20g seems to have been duplicated not once, but twice, so AAPS gave SMBs as if she had 60g carbs on board, resultng in a massive hypo (from which she is now recovering).

Any thoughts as to the issue?

![20200526_202655179_iOS](https://user-images.githubusercontent.com/45319130/82949237-2522b400-9f9b-11ea-8226-fdbebc7afaba.jpg)
![20200526_202612000_iOS](https://user-images.githubusercontent.com/45319130/82949241-2653e100-9f9b-11ea-8279-2dc67e96a689.png)

Logs at https://1drv.ms/u/s!AlNSgvv2w8Q7h65fz8QAsZdNO8oN-A?e=8G0una  This is password protected. Milos, have sent password via FB messenger.

**Comment by MilosKozak** [comment]
```
20:03:11.924 [main] D/info.nightscout.androidaps.dialogs.DialogFragmentWithDate: [CarbsDialog$submit$$inlined$let$lambda$1.run():212]: USER ENTRY: CARBS 20 time: 1590519779600
20:03:11.928 [main] D/PUMPQUEUE: [CommandQueue.add():133]: Adding: CommandBolus - CARBS 20g
20:03:11.929 [main] D/PUMPQUEUE: [CommandQueue.notifyAboutNewCommand():182]: Thread is already running
20:03:12.030 [main] D/info.nightscout.androidaps.dialogs.DialogFragmentWithDate: [CarbsDialog$submit$$inlined$let$lambda$1.run():212]: USER ENTRY: CARBS 20 time: 1590519779600
20:03:12.032 [main] D/PUMPQUEUE: [CommandQueue.add():133]: Adding: CommandBolus - CARBS 20g
20:03:12.033 [main] D/PUMPQUEUE: [CommandQueue.notifyAboutNewCommand():182]: Thread is already running
20:03:12.134 [main] D/info.nightscout.androidaps.dialogs.DialogFragmentWithDate: [CarbsDialog$submit$$inlined$let$lambda$1.run():212]: USER ENTRY: CARBS 20 time: 1590519779600
20:03:12.135 [main] D/PUMPQUEUE: [CommandQueue.add():133]: Adding: CommandBolus - CARBS 20g
```
OK button was clicked 3 times
Hard to say if it's android or user error

**Comment by lydiaengler** [comment]
OK thanks, in that case I think it was Android.  Occasionally, screen seems unresponsive when tapping on AAPS - as if it has frozen.  You have to click on another app, then back to AAPS for it to register.  So we probably tapped a few times without realising they'd all be actioned.

BUT:

(1) this wasn't a case of tapping on  20g three times so it totals 60g.  This was pressing the OK button 3 times.  Should that in any case create 3 separate entries?  One press of OK should clear that screen so if all 3 presses of OK button are processed when the screen is unfrozen, surely only the first would invoke the requested action.

(2) isn't it concerning that only one 20g entry sent to NS?

**Comment by MilosKozak** [comment]
1) this can happen when android is busy. you may click more times before AAPS code is called and dialog closed
2) records were identical thus NS merged them into one
