### ISSUE TITLE
Enhancement: Creating new local profile based on a percentage of another local profile

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2686]
Would it be possible to include a function to be able to not only copy a local profile, but copy it with a "permanent profile-switch", so to speak? So for example, I would like to create a new local profile, which is the same as the old profile with a 85%-profile switch (so changes in basal, IC and ISF).

**Comment by MilosKozak** [comment]
you can create profile switch with % and then convert it to new profile
