### ISSUE TITLE
[2.6.6_dev] numeric scale on second graph doesn't update when graph is scaled due to change of timeslot in view

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2690]
when I change the timeslot of my overview, I get the second graph changing its scaling to show greater separation of lines (which is fine) but the numeric scale at the left of the graph remains unchanged. This could lead to confusion when looking at the Autosense values being provided. I've got some screenshots to add but the git client on the phone doesn't provide a mechanism to add them. I'll go across to the laptop when possible to add them. 

I'm running the latest build of dev 49274ac0e
it is repeatable. just have significantly different AS in different periods (e.g high for 24h to 12h ago then down to zero due to profile change then tiny rise in the last hour)

**Comment by guydavies** [comment]
actually, it appears that the numeric scale is consistent but the AS line actually varies in scale dramatically.

**Comment by guydavies** [comment]
Here are two screenshots taken one straight after the other with different timeslots.  You can see that the AS in the broader timeslot shows the current AS as almost zero, while when the narrower timeslot is shown, it jumps to almost 6, which is the scale that was set in the broader timeslot.
![Screenshot_20200530-135628](https://user-images.githubusercontent.com/2486510/83328033-95be1f00-a280-11ea-9c7c-95c6f236f28b.png)
![Screenshot_20200530-135701](https://user-images.githubusercontent.com/2486510/83328042-a2db0e00-a280-11ea-929f-23e670ef708c.png)

**Comment by Philoul** [comment]
Scale of each curve is adjusted according to maximum value, that explains the results...
In first screenshot earlier (between 4AM and 8AM) sensitivity was higher (probably about 115% or 120%...)
Numerical value on the left is for the higher selected curve in menu (Insulin scale in your graph...)

**Comment by Philoul** [comment]
I understand it could confusing with several curves on the same graph (because scale on the left correspond to the upper selected curve on the graph... and in your both graph the highest IOB value is close to 6 UI, that's why it doesn't change).
if you put your sensitive curve alone in another secondary graph, you'll have scale on the left and curve consistent and they will both change according to timeslot

**Comment by guydavies** [comment]
@philoul. ah yes. that probably needs stating explicitly somewhere. if it is, then apologies. I will try with the sensitivity separated into graph2. it looks better. 

one suggestion would be to colourise the units the same as the thing they're the units of. that would help at least show what they refer to.
