### ISSUE TITLE
2.6.6-dev First secondary graph truncate in low res phone

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2692]
And titles of secondary graphs are not above graph as in my loop phone but behind curves.

But I don't know how to fix it...

See screenshot of my dev phone...

![Screenshot_20200531-002055](https://user-images.githubusercontent.com/52934600/83340535-b23a7580-a2d9-11ea-83e7-9f29a9a2dc7a.png)

**Comment by MilosKozak** [comment]
i was playing with this and didn't found general solutiuon as well
