### ISSUE TITLE
2.6.6-Dev Icons on overview_ststuslights_layout.xml

### ISSUE THREAD

**Issue by libxmike** [MilosKozak/AndroidAPS#2698]
The icons on overview_ststuslights_layout.xml are too small and not to recognize, changing the scale to 2.5 will solve this, see pics.  

![Screen Shot 2020-06-02 at 12 26 30 PM](https://user-images.githubusercontent.com/16604543/83510067-ae227980-a4cc-11ea-92a9-9d8c8609c23e.png)

<img width="1150" alt="Untitled" src="https://user-images.githubusercontent.com/16604543/83510049-a5ca3e80-a4cc-11ea-9e16-29dcc487fa1d.png">

**Comment by MilosKozak** [comment]
this don't work on small displays

**Comment by Philoul** [comment]
As you can see I have more informations in my statuslights, not sure it's ok with your proposed scale of 2.5... (It also should work with low res phone)

But I agree that they are too small... (may be it could be increased a little bit)

![StatusLight](https://user-images.githubusercontent.com/52934600/83514345-c2b64000-a4d3-11ea-9757-88a69524dd5d.jpg)

**Comment by libxmike** [comment]
> this don't work on small displays

The majority uses large displays (around 6 inch) and even on a small display like Jelly or ATOM you won't see the icons, only if you turn the phone horizontal.

I can do the change for myself but the majority won't see the icons.

For 2.5" displays the only solution is to use two rows, one for icons. 2nd for text
Screenshots below with scaleX/Y 2.5 on a ATOM

![Screenshot_20200602-181622](https://user-images.githubusercontent.com/16604543/83543889-649e5280-a4fd-11ea-8587-ce62f44d571d.png)
![Screenshot_20200602-180142](https://user-images.githubusercontent.com/16604543/83543913-6c5df700-a4fd-11ea-8d6a-9a4360cd9b79.png)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/5432fce13d27aa650466436a170060311e4322c6
