### ISSUE TITLE
2.6.6-dev History time axis hrs

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2699]
2.6.6-dev 31/05/2020 History time axis error after 16:00hrs goes 19 then 23 for previous days, current day is OK with 20 etc.
![Screenshot_20200602-193852_AndroidAPS](https://user-images.githubusercontent.com/43484095/83557772-1cd1f800-a50a-11ea-8e0f-5b84c5b39d82.jpg)
![Screenshot_20200602-193929_AndroidAPS](https://user-images.githubusercontent.com/43484095/83557804-307d5e80-a50a-11ea-901a-e441f2133070.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/8d2139fb59ee2babfeac958a107e8884f8fe7eb6
