### ISSUE TITLE
2.6.6-dev minor Lang not updated

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2703]
Build 5395ca4e7-2020.06.04-19:16

When changed lang to eng from czech, the header of modal remains in czech, see psc. 

![20200604_191731](https://user-images.githubusercontent.com/12038874/83790859-1de55f80-a699-11ea-81db-24e88fd29310.jpg)

**Comment by MilosKozak** [comment]
it's android issue. we cannot do more. You may try new "Default language" option in dev
