### ISSUE TITLE
2.6.6-dev The nsclient aaps icon of pump\loop not showing as-is state

### ISSUE THREAD

**Issue by pmisun** [MilosKozak/AndroidAPS#2704]
Build 5395ca4e7-2020.06.04-19:16
Actual fullrelease state:
![20200604_193151](https://user-images.githubusercontent.com/12038874/83791557-399d3580-a69a-11ea-88be-5f4c85cd6e65.jpg)
Actual nsclient release state (manual sync with ns tried):
![Screenshot_20200604-193121_NSClient](https://user-images.githubusercontent.com/12038874/83791676-56d20400-a69a-11ea-8d91-ea3f89ae8ad1.jpg)

Logs from nsclient release:

[AndroidAPS_LOG_1591292049309.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4731774/AndroidAPS_LOG_1591292049309.log.zip)

**Comment by MilosKozak** [comment]
what action led to pump stopped message?

**Comment by MilosKozak** [comment]
ahhh undestand .. it's nsclient only .....
pump disconnected is internal AAPS status only. it's not transfered to NS thus not displayed in nsclient
(NS doesn't support this state)
