### ISSUE TITLE
2.6.6-dev DIA on OAPS tab=3 LocalP=7

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2705]
2.6.6-dev DIA on OAPS tab=3 LocalProfile=7. Running AMA. Screenshots attached. 
![Screenshot_20200605-074734_AndroidAPS](https://user-images.githubusercontent.com/43484095/83846236-363d9480-a702-11ea-8df9-aca896da7a80.jpg)
![Screenshot_20200605-074824_AndroidAPS](https://user-images.githubusercontent.com/43484095/83846279-448bb080-a702-11ea-983c-bead386c4617.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by chrisbev** [comment]
Updated from 2.6.1.2PR2529 and have profile switched before noticing difference.

**Comment by st0ber** [comment]
Read this -> https://androidaps.readthedocs.io/en/latest/EN/Getting-Started/FAQ.html?highlight=Dia#why-does-it-show-dia-3-in-the-openaps-ama-tab-even-though-i-have-a-different-dia-in-my-profile

**Comment by chrisbev** [comment]
Different DIA for AMA.

**Comment by chrisbev** [comment]
Different DIA for AMA.
