### ISSUE TITLE
2.6.6-dev History Browser can't get treatment data before specific day

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2708]
This is a strange issue (I don't know if it's a bug or if there is a safety mechanism...)
Until this morning I could see in the history browser all the Treatments data (Carbs, Bolus and SMB) until May 27 (but not before)
=> I thought there was a problem in my NS data but I can't find any problem...

And since this afternoon, I can no longer see the Treatments data before June 5.
![Screenshot_20200607-194711_AndroidAPS](https://user-images.githubusercontent.com/52934600/83978445-cdc00480-a907-11ea-96cd-82a200f90052.jpg)

The problem comes from the 2 functions below (TreatmentService.java) which return a null Array when there is the problem...
```
    public List<Treatment> getTreatmentDataFromTime(long mills, boolean ascending) {
        try {
            Dao<Treatment, Long> daoTreatments = getDao();
            List<Treatment> treatments;
            QueryBuilder<Treatment, Long> queryBuilder = daoTreatments.queryBuilder();
            queryBuilder.orderBy("date", ascending);
            Where where = queryBuilder.where();
            where.ge("date", mills);
            PreparedQuery<Treatment> preparedQuery = queryBuilder.prepare();
            treatments = daoTreatments.query(preparedQuery);
            return treatments;
        } catch (SQLException e) {
            aapsLogger.error("Unhandled exception", e);
        }
        return new ArrayList<>();
    }

    public List<Treatment> getTreatmentDataFromTime(long from, long to, boolean ascending) {
        try {
            Dao<Treatment, Long> daoTreatments = getDao();
            List<Treatment> treatments;
            QueryBuilder<Treatment, Long> queryBuilder = daoTreatments.queryBuilder();
            queryBuilder.orderBy("date", ascending);
            Where where = queryBuilder.where();
            where.between("date", from, to);
            PreparedQuery<Treatment> preparedQuery = queryBuilder.prepare();
            treatments = daoTreatments.query(preparedQuery);
            return treatments;
        } catch (SQLException e) {
            aapsLogger.error("Unhandled exception", e);
        }
        return new ArrayList<>();
    }
```

Data exists in NS, are correct (it works this morning...)

=> I don't have "Unhandled exception" in log...

[AndroidAPS._2020-06-07_19-55-05_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4742803/AndroidAPS._2020-06-07_19-55-05_.0.zip)

**Comment by MilosKozak** [comment]
there is not enough info in logs. you have to debug it if the problem still appears

**Comment by Philoul** [comment]
I'm not surprised, I didn't see anything in log too...
Any advice to debug this kind of issue? 
- Today I only use log for debugging, but here I am directly in dao library, 
- I try to avoid breakpoint and step by step that is very slow and doesn't work on all situation (but maybe no other choice...)

(I can reproduce this issue easily, I use this function in autotune plugin, I just have to select enough days...)

**Comment by MilosKozak** [comment]
are you able to reproduce it?

**Comment by Philoul** [comment]
Yes but only on my loop phone.
I tried on my dev phone and I can't reproduce issue on it (synchronized with same NS web site, it works...).
