### ISSUE TITLE
Since [AAPS 2.6.6-dev] Build: 5a35d0639-2020.06.11-16:05 - RileyLink did not connect with starting AAPS.

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2715]
2.6.6 Dev from 11.06.2020 4:00pm.

Riley Link only connect with phone after calling Medtronic Tab. 
If you only starts AAPS and you are not going to Medtronic Tab, RL will not connect with phone.
After switching to Medtronic Tab, RL connects in seconds.

[AndroidAPS_LOG_1591906536737.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4771846/AndroidAPS_LOG_1591906536737.log.zip)

It was the same in the last Dev's since 25.05.2020

System:
- Samsung S7, Android 8
- RileyLink v2
- Medtronic 754
- Dexcom G6 / XDrip
- AAPS 2.6.6-dev Build: 5a35d0639-2020.06.11-16:05

**Comment by MilosKozak** [comment]
can you specify time when it didn't connect and when it started working?

**Comment by Alamo04** [comment]
Allways with first start AAPS, after reboot phone or AAPS.

If I start AAPS and stay on the main screen, RileyLink didn't connect.

After going to medtronic tab, RL connects in seconds.
Then everything works fine. 

You have just not forget to go to medtronic tab after starting AAPS, or RL will never connect.

**Comment by ToreBj** [comment]
+1

**Comment by Alamo04** [comment]
Still the same issue in actual dev 2.6.7.

**Comment by Alamo04** [comment]
Still the same issue in 2.7 Beta

**Comment by jroth-haj** [comment]
@MilosKozak, @andyrozman any news on this issue?
Do you need more logs?
How can we support you?

**Comment by MilosKozak** [comment]
resolved in dev
