### ISSUE TITLE
2.6.6-dev predicted lines change order

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2717]
Predicted lines dark blue and light blue change order, sometimes light above dark sometimes reverse. I understand from docs dark is IOB and light zero temp so light has less insulin so I think should always be above dark on BG graph (both assume no carbs?). The order changing may only be a simple graph error/bug but may impact AAPS loop algorithm? I seem to remember this on previous versions?
![Screenshot_20200613-140133_AndroidAPS](https://user-images.githubusercontent.com/43484095/84579731-589d7500-adc8-11ea-813d-70f2f345e726.jpg)
![Screenshot_20200613-180906_AndroidAPS](https://user-images.githubusercontent.com/43484095/84579736-605d1980-adc8-11ea-9fcd-a26e364c2e80.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by Philoul** [comment]
It's not new... (it was the same in 2.4, 2.5 and 2.6 released versions).
I didn't deep dive in prediction lines calculation, but one explain could be start slope of prediction lines... For light blue curve it is not tangent to the BG curve (I suppose 5min delta or avg delta is not taken into account for this prediction curve).

**Comment by chrisbev** [comment]
Thanks for looking at this, yes I have noticed it previously and has to me seemed strange and a bit confusing using the colours. For manual intervention and deciding the need to 0% or 100% it is obvious using intuition but not the colours. Just a minor (?) to me but does anyone go to 100% (from the colours) when needing to bring BG up when the 0% is the one to use? Maybe a note in the docs as to me reading the colours are 0% and 100%. Maybe me reading too much in to it?

**Comment by chrisbev** [comment]
It looks like you are right about not being tangent and this seems to be where the light blue line goes astray, Probably BG (with zero added insulin) couldn't change direction that quick (quicker than 100%)?
