### ISSUE TITLE
2.6.7-dev,When using mmol/L units, the visual range displayed on the watch is problematic

### ISSUE THREAD

**Issue by DriverTicks** [MilosKozak/AndroidAPS#2718]
When using mmol/L units, the visual range displayed on the watch is problematic.
It looks like the target range on the watch is 1/18 of the original range
As you can see in the figure below, the lower limit of red is so close to the upper limit of yellow.
![image](https://user-images.githubusercontent.com/30198264/84589888-82a47500-ae64-11ea-81ab-ec278060c3e9.png)

![image](https://user-images.githubusercontent.com/30198264/84589895-8afcb000-ae64-11ea-9ef8-6514e6409a58.png)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
@AdrianLxM can you check where it is?

**Comment by dlvoy** [comment]
Bug confirmed, 
it seems it is old bug - wear app has this display quirk on 2.5.x too

**Comment by DriverTicks** [comment]
@dlvoy Sorry, there is still a problem.
When I just installed the new program, the blood sugar curve on the watch became normal, but the color of the blood sugar value is yellow and not normal white. After five minutes, the blood sugar curve also became abnormal, and there was a problem with the blood sugar range, but you can see that the curve is still white.
![image](https://user-images.githubusercontent.com/30198264/84925805-109a8d00-b0fd-11ea-9174-d8668edb6f80.png)
![image](https://user-images.githubusercontent.com/30198264/84925821-142e1400-b0fd-11ea-8bc2-adf31ba3c2d7.png)
![image](https://user-images.githubusercontent.com/30198264/84925927-39228700-b0fd-11ea-83ac-2abef9cb980e.png)

**Comment by dlvoy** [comment]
@DriverTicks I've noticed that just afterwards :D It is caused by same issue but for predictions,
fix is already in PR: https://github.com/MilosKozak/AndroidAPS/pull/2729

**Comment by DriverTicks** [comment]
@dlvoy Thank you.

**Comment by DriverTicks** [comment]
@dlvoy I updated to the latest development version, and the blood glucose display range on the watch returned to normal. The forecast curve is also normal. However, even if my blood sugar is within the target range, the blood sugar level and the trend arrow are always yellow instead of the normal white.Thanks.
