### ISSUE TITLE
2.6.7-dev Install Preferences ignored

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2720]
Situation: Export preferences from 2.6.6-dev. Install 2.6.7-dev 1st graph changed to have Activity showing which was not previously selected. Graph 1 gained Absolute Insulin showing as this is new (I think) may be intentional? graph 2 not used. I don't know if such trivial feedback is useful but raised in case. 
Samsung A320.
![Screenshot_20200616-142020_AndroidAPS](https://user-images.githubusercontent.com/43484095/84781355-a55a9900-afde-11ea-936d-8b4802a9293a.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by Philoul** [comment]
Not a bug, Absolute curve has been moved on the top of the list to be in background.
When Absolute was the last curve of the list, it also was in front of all other curves.
The side effect of this change is the necessity of select again curves of each secondary graphs but is mainly limited to tester of dev version I think.

**Comment by chrisbev** [comment]
Close
