### ISSUE TITLE
2.6.7-dev BG deltas consistency

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2721]
Top right BG deltas, for me the delta includes '+' sign for positive numbers, the 15m and 40m deltas do not. 15m and 40m include a ':' after but the delta does not. 
Samsung A320.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by chrisbev** [comment]
Just as another silly thought if say the time prefixed the delta triangles then the triangles could be in a verticle line?
         A: +0.2
15m A: +0.3
40m A: +0.4
Need fixed spacing?
Or 05m: +0.2?

**Comment by MilosKozak** [comment]
screenshot?

**Comment by chrisbev** [comment]
![Screenshot_20200617-122342_AndroidAPS](https://user-images.githubusercontent.com/43484095/84893482-37be7380-b097-11ea-951b-dcdc91ba215d.jpg)
![Screenshot_20200617-130231_AndroidAPS](https://user-images.githubusercontent.com/43484095/84895924-fd56d580-b09a-11ea-9a3c-fc56892bd725.jpg)

**Comment by Philoul** [comment]
See proposed PR and result
![BGDeltasEnhancement](https://user-images.githubusercontent.com/52934600/85759828-8f9d5000-b711-11ea-8a59-70edc3d3694b.jpg)

**Comment by chrisbev** [comment]
Looks excellent cheers...

**Comment by Philoul** [comment]
PR updated to align values to the right too...
See last screenshot here: https://github.com/MilosKozak/AndroidAPS/pull/2775

**Comment by chrisbev** [comment]
Looks good thanks, Samsung A3 2017 A320 Android 8.0 portrait/landscape. Samsung GT-i8190 A7.1.2. 799d4205d Not sure if relevant or something else, see screenshots A3 is loop phone and GT-i8190 is using NS as BG source, see 40m on GT it is zero with no sign but A3 has +0.2. 
![Screenshot_20200628-213045_AndroidAPS](https://user-images.githubusercontent.com/43484095/85957781-31c66d80-b988-11ea-8ce3-6087f89dbf26.jpg)
![20200628_212940](https://user-images.githubusercontent.com/43484095/85957798-5884a400-b988-11ea-9631-7ead95a11ec1.jpg)

**Comment by Philoul** [comment]
If delta is really 0, it is displayed unsigned.
if you see a signed 0 (+0.0 or -0.0), it's a positive or negative delta rounded to 0.
Concerning the gap for 40m delta between your loop phone and your GT-i8190, for me it's not linked to this modification but maybe NS sync issue... (I only modified layout and text formatting)
