### ISSUE TITLE
2.6.7-dev History countdown long time 95s

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2722]
For me the History page takes a long time to count down (onResume) for 95seconds but top graph appears in about 10s. Previous pages appear the same (onClickLeft). 
Samsung A320

![Screenshot_20200616-142020_AndroidAPS](https://user-images.githubusercontent.com/43484095/84787942-77795280-afe6-11ea-957f-929cec7ccc1a.jpg)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by Philoul** [comment]
Same than https://github.com/MilosKozak/AndroidAPS/issues/2667

**Comment by MilosKozak** [comment]
it depends only on speed on your phone. data must be calculated first

**Comment by chrisbev** [comment]
This is strange as 2.6.6-dev for me was OK except #2699 but same phone and 2.6.7-dev was not. Will try beta1 when I can build it. Samsung A320.
