### ISSUE TITLE
UTC time sync

### ISSUE THREAD

**Issue by JustinWalkerMDPL** [MilosKozak/AndroidAPS#2731]
Hey Milos, I tested the UTC time sync and this works excellent.  Much easier than previous needing to delete history within Engineering Mode.  However when I moved backwards more than 60minutes AAPS alerts to advise that time difference is too big - adjust time on the pump!  Is it possible to open this limitation and allow UTC time sync unrestricted?

**Comment by MilosKozak** [comment]
step to reproduce is only change android timezone for more than 2h?

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/40c9907515671601e67f093d0186a3e9832bbe62
