### ISSUE TITLE
2.6.7 beta 1 issue importing bg source settings after first installation.

### ISSUE THREAD

**Issue by RalfCGM** [MilosKozak/AndroidAPS#2733]
After first installation bg source switched from xdrip to dexcom patched.

**Comment by PoweRGbg** [comment]
Same with me.

**Comment by guydavies** [comment]
This was reported at least twice in the Dev branch. I think the explanation
was that there were major changes in code that triggered this. It might be
specifically from Xdrip+ to Dexcom patched. Not sure. I don't think it'll
be fixed but I do think it should be clearly release noted. Being "in the
closed issues" isn't sufficient for this unless you want lots more futile
issues and worried users on FB.

**Comment by xJoe** [comment]
Also happened to me. Will add a list of things to check in docs.

**Comment by MilosKozak** [comment]
> Also happened to me. Will add a list of things to check in docs.

thanks
