### ISSUE TITLE
2.6.7 beta 1 - history browser really slow

### ISSUE THREAD

**Issue by RalfCGM** [MilosKozak/AndroidAPS#2734]
It takes minutes to load history browser.

If I can provide more info please met know. I don't know about the possible reasons for it to be so slow.

**Comment by MilosKozak** [comment]
i don't have this issue. i need more info

**Comment by RalfCGM** [comment]
It displays bg values graph really quickly, but it starts a countdown after displaying the bg graph with "xxx (on resume)" in grey text, counting down the xxx from about 300. This literally takes minutes to complete.

**Comment by goomStar** [comment]
![Screenshot_AndroidAPS_20200620-012844](https://user-images.githubusercontent.com/38337079/85185744-9ea97b80-b295-11ea-896c-53922e001ba8.png)

Ticks down ~2 numbers per second.
Android 8.1, phone maybe a bit weak xD

**Comment by chrisbev** [comment]
I had same/similar problem going from 2.6.6-dev for me was OK except #2699 but same phone and 2.6.7-dev was not. Samsung A320 Android 8.0.0. #2722

**Comment by xJoe** [comment]
Counting down reasonable on Pixel 2.
My problem is that CGM curve + all activated graphs are shown on one page - no scroll down. The more of the additional graphs are activated, the smaller the CGM curve.
Looks like deativating graph in history browser also deactivates this on main screen.

**Comment by RalfCGM** [comment]
I experience exactly what @goomStar experiences,on Nokia 6.1 with android 10.

**Comment by DM-LTR** [comment]
Same here (Galaxy S8, Oreo 8.1), sometimes History browser does nothing & app freezes (Img 1)
Coundown takes about 40 sec, but TBR graph appears after another 2-3 minutes, not scrollable (Img 2)
In landscape mode - History does not work (Img 3)
![Img 1](https://user-images.githubusercontent.com/43177472/85398005-d4c85300-b554-11ea-9953-2091e3a52ca0.jpg)
![Img 2](https://user-images.githubusercontent.com/43177472/85398009-d5f98000-b554-11ea-9793-1d55729ca817.jpg)
![Img 3](https://user-images.githubusercontent.com/43177472/85398010-d5f98000-b554-11ea-948f-7c6380c7f8d8.jpg)

**Comment by RalfCGM** [comment]
I've resetted the database from the maintenance menu. Now it looks much quicker. Page loads in about 5 seconds.

**Comment by reijoahola-nightscout** [comment]
I have now this same problem (History browser really slow) when using 2.7.0-rc2. I am not sure is this related to the new realease because I did not use the history browser earlier. What happens if I reset Database from Maintenance menu ? Does it mean that I lose only CGM and Treatments data from local history ? Should I reset when IOB and COB have gone to 0 ?

**Comment by reijoahola-nightscout** [comment]
Now the local database is reseted and the history browser problem disappeared. I could restore treatments etc. from NS database and everything went smoothly. No need to wait IOB and COB zero.
