### ISSUE TITLE
2.6.7 beta 1 - sensitivity change with high / low tt is (still) greyed out

### ISSUE THREAD

**Issue by RalfCGM** [MilosKozak/AndroidAPS#2735]
We know it was disabled because of safety issues. A lot of people would love this feature back. Can we somehow help testing, or think with you about solutions?

**Comment by MilosKozak** [comment]
yes, using it can be dangerous. it doesn't work with profile switches

**Comment by RalfCGM** [comment]
We would love having it back. It's a bless with sports and hypos... Is somebody already working on it? Can we assist on it?  Or can we somehow initiate the investigation on what's exactly going wrong and provide solutions for it?
