### ISSUE TITLE
2.6.7 beta 1 app stopped after importing prefs

### ISSUE THREAD

**Issue by RalfCGM** [MilosKozak/AndroidAPS#2737]
See subj. Logs sent by mail.
After second restart the app worked.

**Comment by MilosKozak** [comment]
import from maintenance or startup wizard?

**Comment by RalfCGM** [comment]
From maintenance. App stopped completely. Just a simple restart helped out, but it was unexpected behavior.

**Comment by MilosKozak** [comment]
[AndroidAPS._2020-06-19_01-42-50_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/4805726/AndroidAPS._2020-06-19_01-42-50_.0.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4805727/AndroidAPS.log)

**Comment by MilosKozak** [comment]
and time of occurence?

**Comment by RalfCGM** [comment]
Sorry, don't know anymore. Must have been around the time of first installation of this version.
