### ISSUE TITLE
2.6.7_dev CoB not shown in graphs while CGM in startup. 

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2738]
When I start a new sensor in my CGM, the CoB from a meal isn't shown until the BG readings begin. I did a sensor switch this morning at breakfast time and entered carbs and insulin but only the IoB shows in the graph. 

I'm still using a virtual pump (640G) with data coming via Xdrip+ from Enlite sensors. 

I have cae6abfbb build of Dev branch (hadn't updated yet to b1). I'll add a screenshot to the issue in a minute.

**Comment by guydavies** [comment]
![Screenshot_20200619-090756](https://user-images.githubusercontent.com/2486510/85107180-d2d95980-b20d-11ea-92fa-1cd5d4ee213b.png)
![Screenshot_20200619-091437](https://user-images.githubusercontent.com/2486510/85107243-f00e2800-b20d-11ea-8538-8f5f91783d13.png)

**Comment by PoweRGbg** [comment]
Actually there are no BG values, so AAPS can't calculate how many of the carbs are absorbed. So cannot show anything.
