### ISSUE TITLE
2.6.7 beta 1 - DanaRS Pump Password Lost during Upgrade

### ISSUE THREAD

**Issue by AndyS117** [MilosKozak/AndroidAPS#2742]
In Place upgrade from v2.6.1 to 2.6.7-beta 1.

App attempts to reconnect to pump, requiring confirmation on pump, but then reports incorrect password.

Re-Entering and restarting app continues ok so more an annoyance / something for users to be aware of.

Password on pump is NOT default.

Pump details:
Firmware BPN-1.0
Model: 05
Protocol: 01
Code: 02

Checking logs password was correct though reported wrong until re-entered.

Log while failing:
15:46:13.558 [Binder:24770_D] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():537]: <<<<< ENCRYPTION__TIME_INFORMATION 02 01 14 06  13 0F 2E 10  F6 1C 
15:46:13.562 [Binder:24770_D] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():562]: Pump user password: **REMOVED**
15:46:13.563 [Binder:24770_D] E/PUMPBTCOMM: [BLEComm.processEncryptionResponse():564]: Wrong pump password

Logs currently while working:
16:20:41.390 [Binder:31081_8] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():537]: <<<<< ENCRYPTION__TIME_INFORMATION 02 01 14 06  13 10 14 2C  F6 1C 
16:20:41.392 [Binder:31081_8] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():562]: Pump user password: **REMOVED**
16:20:41.393 [Binder:31081_8] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():573]: RS connected and status read

**Comment by MilosKozak** [comment]
RS Pump password was not checked in previous versions. Now it is and you must enter it correctly
