### ISSUE TITLE
2.6.7 Beta1 Treatment/ProfileSwitch profileviewer always show current profile

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2743]
When I click on a previous profile in profileswitch tab of Treatment, I see in profileviewer current profile and not selected profile

It's not a recent issue (exist also in previous dev versions), I tried to fix it but I couldn't :-(

**Comment by CaroGo** [comment]
it seems, it just shows current _or the one before_... older profiles are not shown...

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/3305a5979ddf7678a6d1f82f53f5a75b88c08725
