### ISSUE TITLE
Enhancement: add informations in careportal zone of action tab

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2744]
We have more available space in this zone (xxx age) and less informations than in status light...
I propose to add pump battery level (%) reservoir level (U), and an important and missing information (I think): sensor battery level (when available).
I saw that xdrip gives this information but it is not managed today by AAPS...

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/85234096-544a0b00-b40b-11ea-814d-a42db7dae555.png)
I have it there. What do you mean?

**Comment by Philoul** [comment]
You have sensor age information, but not sensor battery level
I use a miaomiao2 transmitter, and I sometimes forget to check the battery level in xDrip, the autonomy is not exactly 14 days as advertised)... (it happened to me to break down at the start of the night)
(see my photoshop draft)

![proposal](https://user-images.githubusercontent.com/52934600/85260012-48416600-b46a-11ea-8759-eee64c9d54bb.jpg)

**Comment by Philoul** [comment]
I think I can get this information from xdrip with unused key below (services/Intents)
```String EXTRA_SENSOR_BATTERY = "com.eveningoutpost.dexdrip.Extras.SensorBattery";```

EversensePlugin seams to manage this information too (I saw a ```"batteryLevel"``` key in plugin)

But I didn't see anything in the other BG plugins

**Comment by Philoul** [comment]
I propose to close this issue (I'll remove the patch included in merged PR to not display the sensor battery level when the fix proposed in xdrip will be merged ...)
