### ISSUE TITLE
2.6.7-beta1 status line for CAN, INS, SENS and BAT - Text over the symbols

### ISSUE THREAD

**Issue by Chris99621** [MilosKozak/AndroidAPS#2745]
Hi im Testing the 2.6.7-beta1 as you can see in the screenshot the text and the symbols in the status line are overlapping. Mayber the symbols have to be smaller. Im using a galaxy s10+ with a 6,4 Zoll display. 
![Screenshot_20200620-123643_AndroidAPS 1](https://user-images.githubusercontent.com/61082188/85200127-0a6f0100-b2f5-11ea-8698-2b5fcad43ee5.png)

**Comment by guydavies** [comment]
I think it's the extra length of "Std" Vs "h" that does that. In English
and French, there's no overlap. I don't know what the abbreviation for hour
is in other languages so can't say whether it impacts any languages other
than German.

**Comment by xJoe** [comment]
Translation will be changed to h instead of Std.

**Comment by Chris99621** [comment]
Maybe you are right. In 2.5.1 it was h instead of Std. If it will be changed back it could fit

**Comment by guydavies** [comment]
What about trying "St"?  That might leave sufficient space while
representing Stunden better than "h".

**Comment by guydavies** [comment]
Ha!  I just noticed that it's got "d" as the abbreviation for day/Tag. So
maybe reverting to "h" is easier.

**Comment by Chris99621** [comment]
that is true and "h" is not confusing in German
can somebody tell me where i can change the translation i could not find the line in the stings.xml?

**Comment by xJoe** [comment]
@Chris99621 Already done yesterday.
Translation is sometimes difficult if you do not know where words will be used and how much room there is.

**Comment by Chris99621** [comment]
@xjoe ok thx is that in the dev channel or in the beta1 channel so can can Pull and rebuild again?

**Comment by guydavies** [comment]
It's probably still in the I10conv_dev branch until Milos merges that back
into Dev/2.6.7-beta1

**Comment by xJoe** [comment]
@Chris99621 Sorry, I am not into coding details. Made changes in Crowdin (https://crowdin.com/translate/androidaps/7/en-de).

**Comment by Chris99621** [comment]
ok thanks, in the l10_dev i dont find anything about the translation, therefore i have to wait. But good to know that the fix is on the way

**Comment by xJoe** [comment]
Just to let you know: req is "Anfrage" at present and takes up too much space in the COB section. Changed that to "angefr."
Details will be explained in docs as I could not think of any self-explaining abreviation. But also the English original "req" is not 100% self-explaining.

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/85234141-a559ff00-b40b-11ea-906f-8f05292d1477.png)
It depends on the phone resolution, font size, translations etc.
not possible to have it perfect for everyone
