### ISSUE TITLE
2.6.7 beta1: Language mix if language change only in AAPS

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2746]
If there is a difference between the language set in AAPS and phone settings language mix occurs.

AAPS: English
Phone: German

English (just examples): pump connection (green bar below tabs), COB req carbs, h in canula time etc.
German: buttons (insulin, carbs, calculator...)

Changing language also in phone settings to English solves the problem.

2.6.7-beta1 - build: 75bf23c66-2020.06.19-22:04

**Comment by guydavies** [comment]
There's a new language option in AAPS to use default phone settings which
seems to be more consistent.

**Comment by xJoe** [comment]
Thanks @guydavies. Read that in release notes but did not check yet.
So for most users system settings would be the choice. But those who want have different languages in AAPS and phone (for what ever reason) will face difficulties.

**Comment by guydavies** [comment]
Well. There do seem to be some places where inconsistencies arise for some reason. I've seen a few folks say that certain pages appear partially translated. I sometimes switch AAPS to French for my health care professionals to see while I keep my phone in English which is more comfortable for me.

**Comment by xJoe** [comment]
Yes, I guess there are reasons why people have different language settings. But if AAPS offers this option than it should be consistent if possible.
I remember we had the language mix problem in previous versions and it was fixed than. As I am not a dev I do not know how much work it would be to get that streight. Just wanted to report the problem. @MilosKozak as developer of this new feature (according to release notes) must decide what to do.

**Comment by MilosKozak** [comment]
it's an android issue that overriding default andorid language sometime don't work. i cannot do more
