### ISSUE TITLE
2.6.7 beta1 - Preferences & plugin preferences

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2748]
Items in plugin preferences are the same as in preferences > overview

1. Why two items in three-dot-menu?
2. Why different names for the same? Once called Overview and once plugin preferences.

**Comment by MilosKozak** [comment]
Plugin preferences shows preferences only for currently selected plugin. doesn't it work for you?

**Comment by xJoe** [comment]
Maybe I do not really understand how you define plugin. For me both ways show the same:
![pref](https://user-images.githubusercontent.com/13958493/85259583-97d36200-b469-11ea-83ad-3538c722dc77.png)

**Comment by MilosKozak** [comment]
scroll to pump page and select plugin preferences

**Comment by xJoe** [comment]
Thanks. Took some time to understand. Now I can explain in docs.
