### ISSUE TITLE
2.6.7 Local Profile wrong profile selected on Activate profile button

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2754]
On Local Profile, when you click on "Activate profile" button, selected profile in Profile Switch dialog is not edited profile but another (default profile?)
So if you don't change selected profile in Profile Switch dialog you activate wrong profile...

**Comment by Philoul** [comment]
Ok, it's not a bug, it's just a remaining "todo" in  ```LocalProfileFragment```
```
        localprofile_profileswitch.setOnClickListener {
            // TODO: select in dialog localProfilePlugin.currentProfileIndex
            ProfileSwitchDialog().show(childFragmentManager, "NewNSTreatmentDialog")
        }
```
Good exercise, I will try to do something ...

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/6a1394b7b9e37daa00fa8ad68615c72b9521f88c
