### ISSUE TITLE
2.6.7 beta1: min_5m_carbimpact shown twice

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2755]
If AMA is selected in config builder,  min_5m_carbimpact is shown twice
- OpenAPS AMA section
- Absorption settings section

If SMB is selected, min_5m_carbimpact is only shown in absorption settings.

![min_5m_carbimpact_TWICE](https://user-images.githubusercontent.com/13958493/85226751-775bc700-b3d9-11ea-88f6-5c9e06a18f47.png)

**Comment by MilosKozak** [comment]
it must be in both because it's possible combination where this option would be not available
