### ISSUE TITLE
2.6.7 beta1: Status lights settings lost

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2756]
Preset figures are decimal (i.e. 46.0). If I try to enter decimal figure message "only numeric digits..." appears. (Don't know if this is relevant for my problem.)

I can set my private figures in preferences and as soon as I close preferences they are activated, status lights are shown correctly.  If I return to status lights settings right away figures are still correct.

But after some time they return to default values without myself touching status lights preferences again.

2.6.7-beta1 - build: 75bf23c-2020.06.19-22:04

**Comment by MilosKozak** [comment]
can you provide screenshots?

**Comment by xJoe** [comment]
After 45-50 min. values return to default.
Will send you a screenshots per mail.

**Comment by ToreBj** [comment]
Same here 2.6.7 dev
![Screenshot_20200622-130853](https://user-images.githubusercontent.com/23278852/85281055-a5004900-b489-11ea-9be1-0f5175cc2b09.jpg)

**Comment by ToreBj** [comment]
![Screenshot_20200622-131310](https://user-images.githubusercontent.com/23278852/85281389-32dc3400-b48a-11ea-8e10-67a780746d31.jpg)
Sensor warning was set to 9 days(216h) for dexcom G6 and 228 for critical. Is reset after some time.

**Comment by MilosKozak** [comment]
[StatusLights.pdf](https://github.com/MilosKozak/AndroidAPS/files/4814643/StatusLights.pdf)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/500de5fa2deba4ad48a74bd6f579ebb431f5209e
