### ISSUE TITLE
2.6.7-beta1: no external status in xDrip+ from AndroidAPS

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#2757]
In past, xDrip+ has been receiving the 'external status' from AAPS locally, so that it was shown in 'Extra Status Line'. Since using 2.6.7-beta1, xDrip+ does not receive the status (IOB/COB/TBR) anymore.

Maybe it's xDrip+ problem?

![20200621_212431](https://user-images.githubusercontent.com/32912987/85233426-4940ac00-b406-11ea-8577-48d2965c440a.jpg)

![20200621_212452](https://user-images.githubusercontent.com/32912987/85233427-4d6cc980-b406-11ea-98e1-f855524c2426.jpg)

**Comment by MilosKozak** [comment]
do you have status plugin enabled?

**Comment by typ1-brods** [comment]
in xDrip+: yes

**Comment by typ1-brods** [comment]
Okay, for some reson in AAPS config builder it was unchecked :-/ Sorry. Closed
