### ISSUE TITLE
Not defect as displayed are relative, not absolute:Incorrect TBR calculation leading to wrong IOB and up/down TBR

### ISSUE THREAD

**Issue by muthijammy** [MilosKozak/AndroidAPS#2758]
On objective#6 to 7, currently with g5/xdrip plus/combo/s9+ with one ui2.0/android10. Aaps version is 2.6.1.4. I had been using virtual pump till objective#4 last day with perfect suggestions for temp basal as got combo pump consumables only that day. Came to objective#6 immediately as i had accepted temp basal suggestions in #4 itself satisfying #5. Didnt edit max iob to zero but i see it is used in openaps calculations.

Calculation from % increase or decrease to TBR U/hr is too less. Though temp basal ratio calculated incorrect but correct insulin delivered by pump as it takes only % . This leads to wrong IOB calculations in AAPS and cascades to less than expected bg, making 0% TBR. Finally, once bg becomes high, same cycle continues. Initially, i was working around by bolus and open loop but leave it this way now a days. 300 TBR in 1 week+ on pump. 

For ex, 22 june early morning, when local profile basal is 0.68 u/hr, 110% calculated as 0.07 u/hr instead of 0.7 u/hr and aaps thinks 0.02 u only  delivered in 10 min but pump had delivered lot more. Same with less than 100% temp basals. Whenever it becomes 0%, it is calculated correctly. Snapshots show up down and incorrect TBR U/hr, insulin and Iob calculation
[AndroidAPS._2020-06-21_15-23-44_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/4810394/AndroidAPS._2020-06-21_15-23-44_.1.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4810395/AndroidAPS.log)

![Screenshot_20200622-084032_AndroidAPS](https://user-images.githubusercontent.com/37772619/85236800-6b691700-b464-11ea-9e10-2bed6b45f93d.jpg)
![Screenshot_20200622-083953_AndroidAPS](https://user-images.githubusercontent.com/37772619/85236801-6d32da80-b464-11ea-9f83-f4b6df35ebb3.jpg)
![Screenshot_20200622-084111_AndroidAPS](https://user-images.githubusercontent.com/37772619/85236802-6dcb7100-b464-11ea-8e50-8e0ce35d497a.jpg)
![Screenshot_20200622-084118_AndroidAPS](https://user-images.githubusercontent.com/37772619/85236804-6e640780-b464-11ea-897e-85dcd8edfee3.jpg)
![Screenshot_20200622-084300_AndroidAPS](https://user-images.githubusercontent.com/37772619/85236806-6efc9e00-b464-11ea-90cc-4f8c2ebbd4ee.jpg)

**Comment by MilosKozak** [comment]
ratio you see on tratment tab is relative ie 110% add 0.07 U/h

**Comment by muthijammy** [comment]
Combined with on/off TBR and assuming it is absolute, i thought it is bug. I agree I totally forgot IOB concept. Closing
