### ISSUE TITLE
2.6.7b1 language switch not working

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2759]
setting the language settings to (for example) English, most of the application is not in the selected langauge but in the android system langauge.
My epectation would be that settings this switch will switch the full langauge of the application to the selected language.

**Comment by xJoe** [comment]
Android issue - see https://github.com/MilosKozak/AndroidAPS/issues/2746#issuecomment-647173145

**Comment by hartlijn** [comment]
hm I see. a pitty
