### ISSUE TITLE
2.6.7b1 Alert if carbs are required sends two notifications (on watch only)

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2761]
the notification to take carbs; on watch two notifications are sent:
1. the simplified notification to take x carbs (same message you receive on phone)
2. an detailed notification  with 'new suggestion' - with lots of details. I am used to receive these notifications when I was in Open Loop (I am in closed loop now).

My expectation is that notification #2 is not sent.

**Comment by Tornado-Tim** [comment]
Can be closed now @MilosKozak
