### ISSUE TITLE
2.6.7.-beta1 and beta2: New automation BT trigger does not stop TT when disconnecting device

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#2762]
I've got the following two rules in automation tab: 

1. if connecting to car audio BT device, set TT125 and send a message 'TT set to 125'
2. if disconnecting from car audio BT device, stop active TT and send a message 'TT stopped'

Rule 1 is working properly.
Rule 2 does only show up the message, but doesn't stop the TT.

Logs sent via email

![Screenshot_20200623-084951_AndroidAPS](https://user-images.githubusercontent.com/32912987/85370845-a8e6a680-b52f-11ea-9eb0-dcc2e64102f5.jpg)

**Comment by MilosKozak** [comment]
i need log

**Comment by typ1-brods** [comment]
got it?

**Comment by MilosKozak** [comment]
time of occurence?

**Comment by typ1-brods** [comment]
I'm not sure, because the timestamp of the trigger message is showing 01:00. Must be 6/23 between 7 and 8 am

**Comment by MilosKozak** [comment]
please replicate it again and provide more exact info with logs

**Comment by typ1-brods** [comment]
it seems that the problem only exists when BT connection is lost / out of range. in this case the "when disconnecting" trigger fails. maybe a ConnectionStatusChanged event or an additional trigger like "if actually connected to" would solve?

will send logs tomorrow

**Comment by typ1-brods** [comment]
Sent logs again with exact time if occurrence. Now TT is starting and stopping at the same time. BT device was running and connected

**Comment by MilosKozak** [comment]
![Screenshot_20200623-084951_AndroidAPS](https://user-images.githubusercontent.com/11146458/86412513-7c652400-bcbf-11ea-968a-c7cc0bba54db.jpg)

**Comment by typ1-brods** [comment]
?

**Comment by MilosKozak** [comment]
you have so many rules in place. it's hard to find something. could you enable only failing rule and retest?

**Comment by MilosKozak** [comment]
and verify you have at least automation, nsclient and treatments logging enabled

**Comment by typ1-brods** [comment]
So replicated again.

When 'BT connecting' rule active and 'BT disconnecting' disabled: Trigger is working

When 'BT disconnecting' rule active and 'BT connecting' disabled: Trigger is working

When both are active, both triggers are firing the same time when connecting to BT device, notifications are 'connected' and 'stopped' at the same time. But TT is not stopped

Logs sent via mail

![Screenshot_20200705-213246_AndroidAPS](https://user-images.githubusercontent.com/32912987/86540624-21257280-bf07-11ea-9709-cbe08bd9dfdb.jpg)
![Screenshot_20200705-213251_AndroidAPS](https://user-images.githubusercontent.com/32912987/86540625-22ef3600-bf07-11ea-81a6-cbed9a79e662.jpg)
![Screenshot_20200705-212345_AndroidAPS](https://user-images.githubusercontent.com/32912987/86540626-24206300-bf07-11ea-8eca-e5aa9a3ffa1b.jpg)
![Screenshot_20200705-213237_AndroidAPS](https://user-images.githubusercontent.com/32912987/86540628-25519000-bf07-11ea-96f1-488a82069d02.jpg)

**Comment by MilosKozak** [comment]
your problem is that both stop and start is executed at the same time

**Comment by typ1-brods** [comment]
one trigger should fire when connecting, the other when disconnecting. i don't understand why both fire at the same time. but maybe problem of my BT device
