### ISSUE TITLE
2.6.1 and 2.6.7-beta1 diabox app, xdrip and aaps

### ISSUE THREAD

**Issue by RainerTischnet** [MilosKozak/AndroidAPS#2764]
If I choose xdrip as the data source, can AAPS only accept values ​​from xdrip? I installed the DiaBox app for a bubble transmitter. values ​​are found and calibrated by xdrip. Unfortunately, AAPS also receives the values, which are unfortunately far too low. Now wrong value and then the xdrip value follows the Xdrip value and the loop goes crazy.
2.6.1 and 2.6.7-beta1

log 2.6.7-beta1
[AndroidAPS.zip](https://github.com/MilosKozak/AndroidAPS/files/4818948/AndroidAPS.zip)

**Comment by MilosKozak** [comment]
it's not AAPS problem. problem is that both uses the same protocol. that has to be changed. or DiaBox has to address xDrip explicitly
