### ISSUE TITLE
enhancement: improve human readibility in SMB info

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2769]
to help people give insight and overview on the information in the SMB (or AMA?) tabs I suggest several improvements. Numbers below are mentioned on attached screenshot as well.

1. mention the BG values in out_units. for me as user working with mmol/l the values in mg/dl do not make much sense. It helps me if I can see the mmol/l values. For me personal the mg/dl values can be skipped in info, but maybe a better solution would be to show the mmol/l (calculated) values between brackets after the original mg/dl value. Same goes for ISF.
2. convert unix timestamps to 'normal' time. 
3. round values that have more than 3 digits after decimal separator.

![image](https://user-images.githubusercontent.com/28272471/85523042-c0dd2980-b606-11ea-809b-03478b7a53f4.png)
![image](https://user-images.githubusercontent.com/28272471/85523081-cd618200-b606-11ea-83be-66d2e2a0c9bb.png)
![image](https://user-images.githubusercontent.com/28272471/85523117-d94d4400-b606-11ea-88f2-5b8c28bc381b.png)
![image](https://user-images.githubusercontent.com/28272471/85523189-eff39b00-b606-11ea-96e8-3b2a9225cf51.png)

**Comment by chrisbev** [comment]
That would be so nice... but would my mental health suffer not having to divide by 18 all the time?

**Comment by MilosKozak** [comment]
this is not easy possible. Displayed params are raw values passed to the algorithm which works in mgdl.
change would mean huge amount of work which is not a worth in this case i think
