### ISSUE TITLE
2.6.7 beta 1: Problem with alerts NS Client

### ISSUE THREAD

**Issue by Korostensky** [MilosKozak/AndroidAPS#2770]
# Reporting bugs
---
- **NS Client** 
- 2.6.7 beta 1
---
#  `Settings:`
![image](https://user-images.githubusercontent.com/54218454/85539976-baef4480-b616-11ea-9dd8-7c3461ac9738.png)
![image](https://user-images.githubusercontent.com/54218454/85540011-c478ac80-b616-11ea-8d7d-9bc6d749df4c.png)
#  `Result:`
![image](https://user-images.githubusercontent.com/54218454/85539822-8f6c5a00-b616-11ea-88a3-89226c1faba1.png)

**Comment by MilosKozak** [comment]
i teseted it and found a bug for announcements. But on your screenshot is common alert.
I cannot replicate this issue. 
Is it NSclient or AAPS? Handling is a bit different

**Comment by Korostensky** [comment]
Sorry, screenshots with settings and Alerts are in NSClient.
________________________________

**Comment by Pallesauka** [comment]
I also disabled all alarms in NSClient but are still getting low, high and predicted low alarms for some reason. I'm on 2.6.6 dev (8b45464f3 2020-06-09) but it might be the same issue.

**Comment by MilosKozak** [comment]
turning value on - off resolves this issue
but fixed in https://github.com/MilosKozak/AndroidAPS/commit/b13c39ebc5963299bfd60df8e38dff27779b6cc5
