### ISSUE TITLE
2.6.7-beta1: NSClient and Pumpcontrol applications have COB always n/a (value under graphical COB symbol)

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2772]
NSClient 2.6.7-beta1, Build ee16edcc72-2020.06.22, nsclientrelease, Nightscout version 13.0.1, Engineering mode enabled.

Question about NSClient and Pumpcontrol applications. The graphical symbol shows always n/a. COB line in Graph clearly has some value. Treatments list seems to have correct Carb entries. CGM values are ok and no missing values so it cannot be the reason for this. BTW this problem does not exist with AAPS application.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/e9670dd20ab5e821bd8ba7b941ce895d044f58bb

**Comment by reijoahola-nightscout** [comment]
Tested with beta2 version. Now it worked :)
