### ISSUE TITLE
2.6.7 - Beta 1: Temp Target via Automation routine has wrong units

### ISSUE THREAD

**Issue by DM-LTR** [MilosKozak/AndroidAPS#2773]
When setting Temp Target via Automation routine, TT units does not reflect general app setting for units (mmol/l or mg/dl). Even though you have mmol/l selected, TT in Automation has to be set in mg/dl.

How to reproduce (when using mmol/l):

1) Go to Automation tab in AAPS.
2) Create new automation and select Action: Start Temp Target.
3) Check if TT is in mg/dl (and should be in mmol/l).
![SmartSelect_20200625-002140_AndroidAPS](https://user-images.githubusercontent.com/43177472/85734840-9d48da80-b6fd-11ea-92db-d2657d43952c.jpg)

Using: Samsung Galaxy S8, Android Oreo 8.1

**Comment by reijoahola-nightscout** [comment]
Same problem in my installation.
