### ISSUE TITLE
AAPS 2.6.7-beta1: OpenAPS SMB settings max_iob cannot be changed

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2777]
AndroidAPS 2.6.7-beta1, Build: e16edcc72-2020.06.19-16:23,
Flavour: fullrelease
Nightscout version 13.0.1
Engineering mode enabled
Virtual pump
Local profile
Closed loop

When editing OpenAPS SMB settings in Config Builder the setting name is "Maximun basal IOB ...." and not "Maximun total IOB ..." and when checking max_iob value from OPENAPS SMB status page, the value does not change. In earlier release the name of the setting was according to AMA/SMB selection, now the same text is for both.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/bbfbdb18d5580d3a128580320fb9ce59e168c571
good catch. thanks!

**Comment by reijoahola-nightscout** [comment]
Tested with beta2 version. Now it worked :)
