### ISSUE TITLE
2.6.7 beta1: DanaRv2 history does not show up TDD

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#2779]
in dana tab > history, the TDD data does not load. 

(DanaRv2)

logs via mail (27/6/2020,06:20)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/8cf2d3aeb162e14a6eeb43354545b68e40ca58d6
thanks!
