### ISSUE TITLE
2.6.7 beta1: Profile Switch with duration - Banner does not revert to normal after duration

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#2780]
I set a profile switch of 85% for 4 hours, more than 24 hours later and the GUI is still indicating that the profile switch is active.

![image](https://user-images.githubusercontent.com/33720345/85917463-1eb18180-b852-11ea-9619-3f3ef2ac901b.png)

**Comment by AdrianLxM** [comment]
This looks like a PS without duration but 4h timeshift. Could you please verify that?

**Comment by dansuk** [comment]
Ah, perhaps I entered the duration in the wrong part, how do I verify?

I clicked on Profile Switch again and this shows:
![image](https://user-images.githubusercontent.com/33720345/85925304-6acee700-b88f-11ea-901f-4edf0f5fad63.png)
Is that consistent with a 4 hour time shift?

My profile is still showing an 85% profile switch.

Would it make sense to separate the feature and make Time Shift a third option in the Profile menu (View profile, Profile switch and Time Shift)? Seems like potential for error if can issue a % profile switch and time shift at same time?

**Comment by dansuk** [comment]
Just looking at my basals and you're spot on Adrian, looks like everything has shifted by 4 hours. Not what I originally intended but my mistake!

**Comment by dansuk** [comment]
I just tested another profile switch and noticed when doing a duration it has brackets after the first set of brackets which decrease with time. Perhaps the interface could just be updated to indicate time shift with the letters TS in that yellow profile switch banner. Would have been more obvious to me that I'd set it incorrectly had I seen that.

**Comment by DM-LTR** [comment]
Similar issue here. When target BG is adjusted via autosense, light green button on top does not revert to its normal grey shade.
![Screenshot_20200701-091857_AndroidAPS](https://user-images.githubusercontent.com/43177472/86217104-4751b800-bb7f-11ea-8546-4d17ed7601eb.jpg)
