### ISSUE TITLE
AdrianLxM I need help please

### ISSUE THREAD

**Issue by zainebukra** [MilosKozak/AndroidAPS#2781]
I live in NZ and am trying to get nightwatch to work with my dexcom g6 so i can use it on my samsung watch. Someone said you had a non-US link to download so the dexcom share will work?

_Originally posted by @AdrianLxM in https://github.com/MilosKozak/AndroidAPS/pull/2694#issuecomment-637773462_

**Comment by lolo49lala** [comment]
Read here,  pls
https://androidaps.readthedocs.io/en/latest/EN/Hardware/DexcomG6.html

**Comment by zainebukra** [comment]
I thought I might not need to get xdrip and do all of that as I watched this video (https://www.youtube.com/watch?v=Uha-QFFgrU4).

I have been having trouble trying to get xdrip to work on my phone

"his app allow dexcom share and dexcom clarity upload and send data to xdrip+ or aaps" - which app are you talking about?

Im sorry im not very tech savvy

**Comment by zainebukra** [comment]
I am not on a loop system either...

**Comment by FreDiabetics** [comment]
@zainebukra check my WIKI for xDrip Watchfaces https://github.com/FreDiabetics/xDrip--Tasker-Tizen-Watchface-Integration/wiki
