### ISSUE TITLE
 2.6.7-beta1 Kospet Prime 4g Operations out of range 

### ISSUE THREAD

**Issue by RainerTischnet** [MilosKozak/AndroidAPS#2782]
Hello, I'm using a Kospet Prime 4g. in advance oopLibre, xdrip and aaps 2.6.7-beta1 with virtual pump work so far. Where openloop now runs with suggestions for TBR. There inputs that the OK is out of range.

**Comment by RainerTischnet** [comment]
![IMG_3534](https://user-images.githubusercontent.com/49461374/85930556-af717700-b8bd-11ea-8cdd-0c464bf23c39.jpg)

**Comment by MilosKozak** [comment]
sorry but watches are not supported for running AAPS

**Comment by RainerTischnet** [comment]
![0E51DE3B-1CE4-4190-8DFA-676FF114BF1F](https://user-images.githubusercontent.com/49461374/86169651-40dd2500-bb1a-11ea-9883-9d72ff0ff6e6.jpeg)
![6951627D-4395-444B-8B6E-BBA7D14D4789](https://user-images.githubusercontent.com/49461374/86169655-433f7f00-bb1a-11ea-9a11-c84d3f412816.jpeg)

**Comment by RainerTischnet** [comment]
![6AD8E5EB-DF33-48A8-91F3-A75428440D49](https://user-images.githubusercontent.com/49461374/86169840-8994de00-bb1a-11ea-80b5-47ab08289796.jpeg)

**Comment by MilosKozak** [comment]
i know. Reason is very simple. Nobody has time test it on all possible devices. If it works for you, great. If not, you have to deal with it or avoid it.
We test AAPS on common phones only
