### ISSUE TITLE
2.6.1 Potenitally adverse event: lost bolus

### ISSUE THREAD

**Issue by YPOC** [MilosKozak/AndroidAPS#2783]
This morning I've encountered a potentially very dangerous situation of over-bolusing by AAPS.

At around 11:17 I've used the bolus calculator to give a bolus of 10 U for 72 g carbs with a delay of 10 minutes. The bolus started delivery, I didn't bother to check for completeness, but there weren't any signs of something unusual. While eating my meal I noticed AAPS delivering SMBs exceptionally early, so when checking the app I noticed it showed far too little IOB and bolus calc recommenend a bolus of about 6.4 U. **The earlier bolus of 10 U did not show up.** *See images 1 & 2.*

Even after tapping the bluetooth-icon to sync with the pump the bolus still didn't show. Checking my pump's history it clearly showed a 10 U bolus at 11:27 (I think this shows the end, which checks with my delivery speed). *See images 3, 4 & 5.*

Previous actions: At 11:15 I gave a little bolus of 0.8 units. When noticing the problem I disabled loop to stop SMBs.
Following actions: I manually entered a bolus of 10 U without delivery to continue looping.

See attached logs: [AndroidAPS.zip](https://github.com/MilosKozak/AndroidAPS/files/4842169/AndroidAPS.zip)

![Screenshot_2020-06-28-12-07-03](https://user-images.githubusercontent.com/24976043/85946487-fce4f700-b944-11ea-8d6e-c2a54a00e8b4.jpg)
![Screenshot_2020-06-28-12-07-22](https://user-images.githubusercontent.com/24976043/85946485-fc4c6080-b944-11ea-947f-6ed950de9a12.jpg)

![Screenshot_2020-06-28-12-07-44](https://user-images.githubusercontent.com/24976043/85946484-fbb3ca00-b944-11ea-9635-96f36b3b3747.jpg)
![Screenshot_2020-06-28-12-08-27](https://user-images.githubusercontent.com/24976043/85946482-fb1b3380-b944-11ea-8056-85c141b194ad.jpg)
![IMG_20200628_120933](https://user-images.githubusercontent.com/24976043/85946481-f6567f80-b944-11ea-9d81-47f116c21c37.jpg)

**Comment by MilosKozak** [comment]
thanks for catching this. It's really rare. bolus ended exactly 10 min after start what interferred with 10 min carbs delay
fixed by https://github.com/MilosKozak/AndroidAPS/commit/a08c1d5269bc9dd7da04b93530764490cf517a51
