### ISSUE TITLE
2.6.7-beta1: Loop calculation stopped working

### ISSUE THREAD

**Issue by the-swish** [MilosKozak/AndroidAPS#2786]
At 17:26 I saw the last loop run was done at 16:51.
After pressing "Run now" in the Loop tab I got "APS: NO APS SELECTED!".
Pressing "Run now" in the SMB tab showed a empty results field.
After that, it started working again.
Logfiles for this timeframe are attached. 
[Log.zip](https://github.com/MilosKozak/AndroidAPS/files/4853310/Log.zip)
![Screenshot_20200630-172637_AndroidAPS](https://user-images.githubusercontent.com/64657078/86153760-68c08e80-bb02-11ea-91cd-51914b8a279e.jpg)
![Screenshot_20200630-172643_AndroidAPS](https://user-images.githubusercontent.com/64657078/86153784-72e28d00-bb02-11ea-8935-742f66e7fdae.jpg)

**Comment by MilosKozak** [comment]
hmmm i see there was no APS execution but from logs is not visible what happened. 
closing for now. create new issue or reopen if you find more info

**Comment by MilosKozak** [comment]
thanks for reporting
