### ISSUE TITLE
2.6.7 beta1: Button color does not revert when target is adjusted via autosense

### ISSUE THREAD

**Issue by DM-LTR** [MilosKozak/AndroidAPS#2788]
[AndroidAPS.zip](https://github.com/MilosKozak/AndroidAPS/files/4856829/AndroidAPS.zip)
When target BG is adjusted via autosense, light green button on top does not revert to its normal grey shade when AS is back to 100%. Showing this green button for 3 days in a row with AS on 100%. Sensitivity in SMB tab showing as "normal". Worked fine before.
![Screenshot_20200701-091857_AndroidAPS](https://user-images.githubusercontent.com/43177472/86217104-4751b800-bb7f-11ea-8546-4d17ed7601eb.jpg)

_Originally posted by @DM-LTR in https://github.com/MilosKozak/AndroidAPS/issues/2780#issuecomment-652251491_

**Comment by MilosKozak** [comment]
i don't see the bug. I added more logging to dev branch

**Comment by chrisbev** [comment]
My button also returns to green, Cancel also returns to green. @DM-LTR did you find a way to get back to grey? 2.6.7-beta1 dfaf3f86f

**Comment by chrisbev** [comment]
I'm not using autosense to switch TT but I do switch on high/low BG.

**Comment by DM-LTR** [comment]
Yes, I am able to revert it back to grey ONLY IF target BG in NS profile is set as a range of values, not single value...

![Screenshot_20200703-131258_AndroidAPS](https://user-images.githubusercontent.com/43177472/86464057-ff719300-bd2e-11ea-9afe-35f17df2b11b.jpg)

**Comment by chrisbev** [comment]
Ah, if I set Local target to a range then I also get grey, if that helps? Will leave it as a range and see if automation cancels to grey or green.

**Comment by chrisbev** [comment]
Automation high/low TT also clears to grey if local target range used.

**Comment by DM-LTR** [comment]
Works properly in beta 2

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/pull/2804
