### ISSUE TITLE
2.6.7 beta1 objective 2 was closed, now open

### ISSUE THREAD

**Issue by RainerTischnet** [MilosKozak/AndroidAPS#2789]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
screenshots?

**Comment by RainerTischnet** [comment]
[
![IMG_3539](https://user-images.githubusercontent.com/49461374/86290320-96363680-bbed-11ea-95ea-6df75330b9c1.jpg)
![IMG_3540](https://user-images.githubusercontent.com/49461374/86290326-97676380-bbed-11ea-9ac7-704328bcc7ee.jpg)
![IMG_3542](https://user-images.githubusercontent.com/49461374/86290329-99312700-bbed-11ea-8a02-b08e420631de.jpg)
![IMG_3543](https://user-images.githubusercontent.com/49461374/86290331-9a625400-bbed-11ea-94bf-a3dd5f69fb73.jpg)
![IMG_3544](https://user-images.githubusercontent.com/49461374/86290335-9c2c1780-bbed-11ea-91c2-6d024a4c958e.jpg)
![IMG_3545](https://user-images.githubusercontent.com/49461374/86290341-9fbf9e80-bbed-11ea-9f1b-43d0ba434d04.jpg)
![IMG_3547]
![IMG_3549](https://user-images.githubusercontent.com/49461374/86290354-a4845280-bbed-11ea-9f27-8fb1c6de6271.jpg)
![IMG_3550](https://user-images.githubusercontent.com/49461374/86290356-a5b57f80-bbed-11ea-8082-ee6df10a825c.jpg)
![IMG_3551](https://user-images.githubusercontent.com/49461374/86290360-a6e6ac80-bbed-11ea-8913-8d350ff0b129.jpg)
![IMG_3551](https://user-images.githubusercontent.com/49461374/86290365-a817d980-bbed-11ea-8b55-fcd6942c0ddf.jpg)
![IMG_3552](https://user-images.githubusercontent.com/49461374/86290368-a9490680-bbed-11ea-856a-cc377d18707c.jpg)
![IMG_3553](https://user-images.githubusercontent.com/49461374/86290372-aa7a3380-bbed-11ea-9125-4f958bf9c344.jpg)
![IMG_3554](https://user-images.githubusercontent.com/49461374/86290375-acdc8d80-bbed-11ea-968b-a3b9bd4dce15.jpg)
![IMG_3555](https://user-images.githubusercontent.com/49461374/86290379-aea65100-bbed-11ea-9f69-fcbbf0cec016.jpg)
![IMG_3556](https://user-images.githubusercontent.com/49461374/86290388-afd77e00-bbed-11ea-9c89-f6420f39a8ba.jpg)
![IMG_3557](https://user-images.githubusercontent.com/49461374/86290392-b1a14180-bbed-11ea-8f13-699dcb2d4f47.jpg)
![IMG_3558](https://user-images.githubusercontent.com/49461374/86290393-b2d26e80-bbed-11ea-8f0f-30005d115cac.jpg)
![IMG_3559](https://user-images.githubusercontent.com/49461374/86290395-b4039b80-bbed-11ea-9166-9fe130c75b31.jpg)
![IMG_3560](https://user-images.githubusercontent.com/49461374/86290408-b960e600-bbed-11ea-9011-0f101e304894.jpg)












(https://user-images.githubusercontent.com/49461374/86290350-a1896200-bbed-11ea-99c4-e568915ce7b2.jpg)
![IMG_3548](https://user-images.githubusercontent.com/49461374/86290353-a3532580-bbed-11ea-9c00-f93a6df8b568.jpg)







](url)

**Comment by RainerTischnet** [comment]
I checked again on smartphone where the beta is installed. Everything is fine there. I think it happens because I switched between 2.6.1 and 2.6.7-beta1 on the clock without restoring the backup.
