### ISSUE TITLE
2.6.7 beta1: Carb req right after entry through calculator

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2790]
Right after entering 65g carbs through calculator a request for 60g carbs is shown. Is this expected behaviour?

Treatments:
07:00 65g carbs / 7,3 U
06:38 2 U pre-bolus

2.6.7-beta1 - build: 75bf23c-2020.06.19-22:04
![CarbReq](https://user-images.githubusercontent.com/13958493/86322027-76792f80-bc3a-11ea-918b-52f68d936b5c.png)

**Comment by MilosKozak** [comment]
does it correct itself?

**Comment by xJoe** [comment]
Yes. Just irritating at the beginning.

**Comment by MilosKozak** [comment]
this is impossible to resolve because it depends on COB calculation which is done after next BG value
