### ISSUE TITLE
2.6.1 Max daily safety multiplier dialog text misleading (german translation)

### ISSUE THREAD

**Issue by Rhabarbara745** [MilosKozak/AndroidAPS#2791]
I'm not sure if this is only a thing of the german translation but

the german translations of `Max daily safety multiplier` dialog means it limits **Basal-IOB** to 3 * the amount of the biggest basalrate programmed in the pump.

**According to the docs this safety multiplier defines the highest setable basalrate by AAPS**

[https://androidaps.readthedocs.io/en/latest/EN/Usage/Open-APS-features.html](url)
> Max daily safety multiplier This is an important safety limit. The default setting (which is unlikely to need adjusting) is 3. This means that AndroidAPS will never be allowed to set a temporary basal rate that is more than 3x the highest hourly basal rate programmed in a user’s pump. Example: if your highest basal rate is 1.0 U/h and max daily safety multiplier is 3, then AndroidAPS can set a maximum temporary basal rate of 3.0 U/h (= 3 x 1.0 U/h).

Same for the `Current Basal safety multiplier` dialog.

![Screenshot_20200702-152344](https://user-images.githubusercontent.com/57756367/86364254-3769cf00-bc78-11ea-929e-50d593ebd868.png)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/pull/2765/commits/16b549c6fdf5caf12e773e51232662b4cfd24d34
