### ISSUE TITLE
2.6.7-beta2 SMB Tab column alignment

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2795]
Not sure if this is intended or important but for me the SMB Tab alignment appears to be a bit astray between Script debug : and Result :, see screenshot. (as -beta 1). Samsung A3 A320 Android 8.0.0. 2.6.7-beta 2 157d8f7f5
![Screenshot_20200704-153616_AndroidAPS](https://user-images.githubusercontent.com/43484095/86515306-d4ab3b80-be0f-11ea-86a9-acecf57b535c.jpg)
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
i don't have this issue... is it pemanent?

**Comment by chrisbev** [comment]
Yes permanent also on Samsung S3 mini GT-I8190N. Also portrait and landscape. See attached I also have 'IOB data :' on the right further up. If only me will try Eng mode off and I recall it in Beta1 but can't remember if 2.6.6 or 2.6.7. Will try prevoius apks to see when started. Could it be my building with Android Studio (just updated to 4), seems unlikely but if only me on 2 different phones?
![Screenshot_20200708-072647_AndroidAPS](https://user-images.githubusercontent.com/43484095/86894479-07e51780-c0fb-11ea-8cd4-67a4a7f2f184.jpg)

**Comment by chrisbev** [comment]
On Gt-I8190 Linage OS 14.1:-
2.6.1 cffe1b439 does not have the problem the data is by IOB data : not way down. 2.6.7-B2 157d8f7f5 and 2.6.7-dev 799d4305d do have.
NB When it starts the girst time and before the column is populated with data the left column headings are on the left except 'IOB data :' which is right justified! Screenshot with an invalid BG source.
![Screenshot_20200708-193812_AndroidAPS](https://user-images.githubusercontent.com/43484095/86957594-dbf58080-c152-11ea-9edc-d2880d6dc1f9.jpg)

**Comment by chrisbev** [comment]
Both phones OK with 2_6_7-dev 1d8120d05 (20200709)

**Comment by chrisbev** [comment]
-dev OK
