### ISSUE TITLE
[question] 2.6.7-beta2:   Missing forecast in diagram (no pump,  ICT mode)

### ISSUE THREAD

**Issue by lolo49lala** [MilosKozak/AndroidAPS#2797]
Hi community,

can anyone help, why AAPS doesn't make forecast in diagram?
![Screenshot_20200704-192112_AndroidAPS](https://user-images.githubusercontent.com/8592414/86517796-f1ee0300-be2b-11ea-8d6e-f2d41334747f.jpg)

I don't have a pump configured, because ICT ist selected. My bg source is dexcom G6 patched app and I upload my data to nightscout.

What should be doing to enable forecast?

Best regards

**Comment by MilosKozak** [comment]
on ICT options are limited (because of no basal rate)

**Comment by lolo49lala** [comment]
I understand that the therapy with CSII has a lot of more options as ICT. But because it is not possible to make a forecast for ICT? All values of insulin profil, insulin amount and carbs are stored in application. Can nobody enable the line for forecast?
