### ISSUE TITLE
APSResult.changeRequested not updated 

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#280]
Variable is self-assigned in both instances, should be assigned _true_ I think:

https://github.com/MilosKozak/AndroidAPS/blob/0e6a93df90ac71a3cdf4bb9b07610cb354a4cb71/app/src/main/java/info/nightscout/androidaps/plugins/OpenAPSMA/DetermineBasalResultMA.java#L44

https://github.com/MilosKozak/AndroidAPS/blob/0e6a93df90ac71a3cdf4bb9b07610cb354a4cb71/app/src/main/java/info/nightscout/androidaps/plugins/OpenAPSAMA/DetermineBasalResultAMA.java#L46

**Comment by AdrianLxM** [comment]
I think the logic is valid as is. If there is a `duration`, it should request the change depending on what was determined from the `rate` field.

instead of self assignment a short comment might do.

**Comment by jotomo** [comment]
@AdrianLxM Thanks for checking the logic, I gotta admit I didn't do that, I was only skimming the code working on something else :-)

**Comment by AdrianLxM** [comment]
In the PR cleanups i've changed that: https://github.com/MilosKozak/AndroidAPS/pull/302
