### ISSUE TITLE
[2.6.7 beta2] Boluse delivered but finished with error: "Asked: 7.2 Delivered: 0.0"

### ISSUE THREAD

**Issue by ledrexter** [MilosKozak/AndroidAPS#2801]
Hi Guys,

I'm with Dana Rv2 and aaps 2.6.7 beta2.
Last night my blouse for dinner was calculated 70 grams corresponds to 7.2 units.
I was distracted so i didn't' notice if the pump responded for corrector number of units by sound but at certain point I heard aaps alarm:  "7/6/20 21:50 Asked 7.20U Delivered: 0.00U Error code:2"
Although the error IOB and COB were reflecting the bolus and the meal. 
I checked the log file in the pump and it showed that 7.20 bolus was applied.
This means the error is a fake error

I'm attaching the log file. You can find the messages of the delivered insulin and at the end the following error:
21:50:33.156 [Thread-10590] D/PUMPQUEUE: [CommandQueue.add():164]: Adding: CommandLoadEvents - LOAD EVENTS
21:50:33.156 [Thread-10590] D/PUMPQUEUE: [CommandQueue.notifyAboutNewCommand():205]: Thread is already running
**21:50:33.158 [Thread-10590] D/PUMP: [DanaRv2Plugin.deliverTreatment():197]: deliverTreatment: OK. Asked: 7.2 Delivered: 0.0**

[AndroidAPS_LOG_1594061542579.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4885508/AndroidAPS_LOG_1594061542579.log.zip)
![Screenshot_20200707_002019](https://user-images.githubusercontent.com/51510015/86800537-cbbea200-c07b-11ea-8db9-8596dbd6e657.jpg)

Please let me know if the log and the snapshot are sufficient to reveal the issue.

Kind regards,
Petar Harizanov

**Comment by MilosKozak** [comment]
This error is what pump reported at the end of bolus command. But AAPS uses data from pump history to check delivered insulin. 
So, the behavior is as designed. After any error you have to check pump to see if correct data is loaded
