### ISSUE TITLE
2.6.7-beta2 NSClient shows loop status symbol

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2803]
NSClient 2.6.7-beta2
Flavour: nsclientrelease
Engineering mode enabled

In earlier versions (2.6.1.2) NSClient did not try to show Loop status and did not show a menu for Loop disable etc. Now the new 2.6.7 beta versions show Loop symbol but it does not follow the loop status of the master (AAPS). Is Loop status in NSClient an inteded feature and how it should work ?

 Note: In my test system the master AAPS is still the earlier version 2.6.1.4 if it somehow has some effect.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/45f168d427083a07f5871dd0d3a3bbadfc6f6fd4
thanks!
