### ISSUE TITLE
min_5m_carbimpact remains in mg/dl / 5 min even when mmol/l units is selected

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2805]
I don't know if this is a missing conversion or if it's voluntary (to be perfectly consistent, when we select mmol/l units, it should be converted to mmol/l / 5min)
It may be better to leave it as it is, because the default values ​​(3 mg/dl / 5min or 8 mg/dl / 5min) are easier to remember than converted values in mmol and there are probably very few people who know how the calculation is done to convert this setting to a minimum decrease of COB...

**Comment by MilosKozak** [comment]
converting value passed directly to the alg may be confusing. i'd keep it as it is
