### ISSUE TITLE
2.6.7-beta2 Pumpcontrol application shows loop status symbol

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2806]
Pumpcontrol 2.6.7-beta2
Flavour: pumpcontrolrelease
Engineering mode enabled

Pumpcontrol application shows the new Loop status symbol and status is always enabled.
Probably this application should not show Loop status.
I did not check how it was in earlier releases.

**Comment by MilosKozak** [comment]
already fixed in dev along with nsclient
