### ISSUE TITLE
TT cancel/end doesn't return to grey

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#2808]
2.6.7-beta2 and 2.6.7-dev 1d8120d05 (20200709) if a TT is set the bar/button changes colour but when cancelled/ended for me returned to green if a single target value is used, does return to grey with a target range. Similar to #2788 problem. Samsung A3 and GT-I8190.

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by artirgeci** [comment]
I've just observed a similar situation with "Eating Soon" TT. After the 30min period when TT ends, the bar/button turns green and continues with a target at 4.0 (Eating Soon target value).

Time when I enabled manually the "Eating Soon" mode (18:46:48.638)
Time when it continued at 4.0 target with green button, after the "Eating Soon" timer ended (19:17:48.633)
Build: e44080802-2020.07.03-22:23 (2.6.7-beta2)
[AndroidAPS._2020-07-16_00-00-03_.8.zip](https://github.com/MilosKozak/AndroidAPS/files/4933910/AndroidAPS._2020-07-16_00-00-03_.8.zip)
[AndroidAPS._2020-07-16_00-00-03_.9.zip](https://github.com/MilosKozak/AndroidAPS/files/4933911/AndroidAPS._2020-07-16_00-00-03_.9.zip)

![image](https://user-images.githubusercontent.com/23337996/87716869-c108b900-c7af-11ea-9cc7-5813f66360d9.png)

**Comment by MilosKozak** [comment]
green indicates target has been adjusted by algorihtm

**Comment by artirgeci** [comment]
It does not look normal behavior to me, did test it yesterday, and it happend again after the 30min of "Eating Soon" mode, instead of returning to my normal target it continues at 4.0, unless i restart the app.
