### ISSUE TITLE
[Enhancement|Bug][2.6.1.2]  - Alarm when pump is 0 units of insulin and set basal to 0

### ISSUE THREAD

**Issue by radu-neacsu** [MilosKozak/AndroidAPS#2809]
Issue
I forgot to change the insulin cartridge and the AAPS was unaware that we weren't doing any basal rate.  So after changing the cartridge I ended up high glucose because the algorithm was counting an amount of insulin that was never delivered.

**Comment by MilosKozak** [comment]
this is very pump specific and cannot be done generaly in AAPS
You can put missing insulin via refill fuction

**Comment by radu-neacsu** [comment]
Yes, thats what i did. But if a temp basal rate  is set 0 when pump
reservoir is equal to 0, this is a app decision. This way when you refill
the reservoir will make the need it amount.
Like i said it's a improvement.
