### ISSUE TITLE
ConfigBuilder.ConfigBuilderPlugin#applyAPSRequest doesn't honor pump capabilities

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#281]
While the javadoc states the method uses an absolute TBR or a percentage TBR based on the pump capabilities, it always tries to set an absolute TBR.

I'll eventually fix this with a PR.

**Comment by AdrianLxM** [comment]
If it uses real temp-basals or emulates them by extended boluses depends on what you specified in the settings.
When this setting is activated, all extended boluses are treated as temp basals. (For IOB, vizualization, ...)

The possible increase in case of a real temp-basal (percentage) should depend on the pump capabilites. This is 200% for the DanaR; not sure if this is questioned explicitly or "known" by the programme. The Combo that can have different maximums might need adjustment?

**Comment by jotomo** [comment]
My grief is about the _setTempBasalAbsolute_ call at the end of the method: the Combo only does percentage TBRs, it's unable to set a certain rate. That is defined in the _PumpDescription.tempBasalStyle_ - that settings needs to considered to make the Combo work.

**Comment by AdrianLxM** [comment]
"absolute" rates are set on the DanaR by emulating them with extended boluses. The same could be done by the Combo pump.

**Comment by AdrianLxM** [comment]
Just for clarification: the Dana-R-Pump has no "absolute rate" nor does it see one. Setting a percentage or an extended bolus is done within AndroidAPS.
So without having checked the code (I can do this later): in practice it works.

Only the emulated pump does allow real "absolute rates".

**Comment by jotomo** [comment]
The ComboPlugin now does the conversion from absolute rate to percent, thus closing.
