### ISSUE TITLE
2.6.7-beta2 bug with requested carbs

### ISSUE THREAD

**Issue by Chris99621** [MilosKozak/AndroidAPS#2810]
In the alarm AAPS requested 30 carbs, but in the carb section there are 3 carbs requested. 3 carbs make more sense than 30 carbs, so i think there is a bug in the notification (maybe there is a zero too much). I send the logs by email.

![Screenshot_20200710-105218_AndroidAPS](https://user-images.githubusercontent.com/61082188/87137334-03586480-c29d-11ea-9086-58dd9fb22e96.jpg)

**Comment by MilosKozak** [comment]
do you have logs from that time?

**Comment by Chris99621** [comment]
should this be here. But i send it also as mail with a refference to this issue
[AndroidAPS._2020-07-10_00-00-03_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/4926903/AndroidAPS._2020-07-10_00-00-03_.2.zip)

**Comment by MilosKozak** [comment]
this is a message from some time ago. i need more if the message is changing as carbsReq is changing

**Comment by Chris99621** [comment]
i will test it with the RC1 and will provide a screenshot and logs. Do you need more?

**Comment by the-swish** [comment]
Looks like the same issue as #2827
German translation swapped carbs and minutes.
