### ISSUE TITLE
Glitch in direction of TBR "deviation icon" 

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2815]
Hi

I am using the latest 2.6.7_dev (1d8120d05) and have noticed for some time a minor glitch when AAPS changes from on TBR to a different one. For example, if my programmed basal is 0.1 and a TBR of 0.3 is set, I correctly see an icon showing s higher TBR. But if the TBR then drops from 0.3 to 0.2, the icon shows a downward deviation even though it is still higher than my programmed BR. I think the icon is being set by comparing with current basal (the active TBR) rather than the current programmed BR. 

I guess you could argue this point either way but I consider it slightly confusing. I would prefer the icon to show the deviation relative to programmed because I may not have seen the previous TBR. As I say, could be argued either way.

**Comment by swissalpine** [comment]
You misunderstood the concept: Deviations are blood glucose deviations, not tbr deviations.

**Comment by guydavies** [comment]
You misunderstood my issue ;)

In the main screen, there's an icon that shows your current basal rate in
purple. If it's your normal basal rate, it's flat. If it's higher, I'd
expect it to show an up deviation. If it's lower I'd expect a downward
deviation. The higher/lower is currently compared to the current TBR, not
the programmed BR, which I think is not the original intent.

**Comment by swissalpine** [comment]
Sorry. Deviation leads me in the false direction.

**Comment by Philoul** [comment]
@guydavies is this issue new (in beta version) or did you see it when I made my PR with these icons (dev branch) ?
And which branch did you build (dev, 2.6.7-beta1 or 2.6.7-beta2) ?
With my config, when TBR is running, I always see a percentage below icon (and icon is consistent with this percentage, below 100% or above 100%). I see basal rate only if no TBR is running (flat icon) or if fake extended (high TBR icon)... (my config is from dev branch)

**Comment by guydavies** [comment]
Hi Philloul

I noticed it a little bit ago but I couldn't be 100% sure exactly when. It
was certainly something I noticed but wasn't sure a week or so ago.

**Comment by Philoul** [comment]
Hi Davis,

Here is the code extracted from overview fragment (dev branch), it seems to be good for me so I can't explain your issue: (compare is not done with previous TBR value but with current default basal rate, TBR over or below 100%...)

```
if (activeTemp != null)
    overview_basebasal_icon?.setImageResource(if (activeTemp.tempBasalConvertedToPercent(System.currentTimeMillis(), profile) > 100) R.drawable.ic_cp_basal_tbr_high else R.drawable.ic_cp_basal_tbr_low)
else
    overview_basebasal_icon?.setImageResource(R.drawable.ic_cp_basal_no_tbr)
```
(and in Beta1 and Beta2 versions the only difference is the "?" removal)
I'm sorry I can't solve the issue (maybe a more competent developer and a log analysis could help ...)

**Comment by guydavies** [comment]
Hi @Philoul, I am a very poor programmer but I would have considered that your code looks like it does the right thing.

In pseudo code, I read it as something like

If I'm running a TBR
  If my TBR as a percentage of my current profile Basal is > 100, show an up icon
  else (my TBR as a percentage of my current profile basal is < 100) show a down icon
else show flat

The only question is whether the "profile" is pulling the correct value against which to compare, I guess.

Is there a specific reason why you need to first convert the TBR to a percentage of the current profile?  Wouldn't it be simpler to just do a comparison of the absolute values?

If I'm running TBR
  If TBR > current profile Basal show up icon
  Else show down icon
Else show flat

**Comment by Philoul** [comment]
It's because in activeTemp (it's a ```TemporaryBasal``` object), according to selected pump and type of TBR, sometimes you only have ```percentRate``` (```absoluteRate``` is not available or requires an specific convertion of this object to absolute), sometimes you only have an ```absoluteRate``` and sometimes (if TBR emulation is activated and it's a "Fake TBR") you only have ```netExtendedRate``` (it's an additionnal basal rate value done with a "Square bolus"...)
```tempBasalConvertedToPercent``` is a standard method of ```TemporaryBasal``` object that deals with all these situations and always return the correct percentage...
```
public int tempBasalConvertedToPercent(long time, Profile profile) {
    if (isFakeExtended) {
        return (int) ((profile.getBasal(time) + netExtendedRate) / profile.getBasal(time)) * 100;
    } else if (isAbsolute) {
        return (int) (absoluteRate / profile.getBasal(time)) * 100;
    } else {
        return percentRate;
    }
}
```
(```profile``` is initialized in the beginning of this module with "current active profile")

**Comment by guydavies** [comment]
thanks. that makes sense. you've got to go one way or another :).

**Comment by Philoul** [comment]
Do you use profileswitches with percentage ?

**Comment by guydavies** [comment]
No. I have two independent profiles that I switch (weekdays/weekends) but I
only use absolute TBR and switch from one profile to the other.

**Comment by Philoul** [comment]
No other idea sorry... 

Maybe Milos could analyse this issue if you send him log and screenshot...

**Comment by guydavies** [comment]
I'll try to reproduce and get the screenshots and logs.

**Comment by guydavies** [comment]
Finally, the problem has recurred.  If you see the icon shows down, but the value is 0.35 and you can see in the popup that my base is 0.2, so it should be up.  As I say, it's a glitch, not a catastrophe.  I'll send logs too.  The time of the event is as shown in the screenshot.

![Screenshot_20200715-111029](https://user-images.githubusercontent.com/2486510/87527232-1c418b00-c68c-11ea-8aaa-d8f2c2d00eea.png)

**Comment by MilosKozak** [comment]
hopefully fixed by https://github.com/MilosKozak/AndroidAPS/commit/ee3f63c327bea7d544c9c7a1766810c063bb8778

**Comment by guydavies** [comment]
Thanks Milos,

Just building now.  It will be difficult to confirm definitively that it *is* fixed but I’ll let you know if it isn’t :)

Rgds,

Guy

**Comment by Philoul** [comment]
Good catch Milos, I'm convinced you fixed it.
With previous code only TBR with percent above (or equal) 200% had correct high TBR icon (below 200% it was always a low tbr icon)...
Here 0.35/0.2 = 1.75 converted to int = 1 so previous result was 100, => low tbr icon
with commit new result 175 => high tbr icon

But may be it remains one issue... Don't we have in a specific pump (medtronic?) a non standard "neutral tbr" (a tbr running with percent of 100%), if we can have this situation, with my code we will never have flat icon (always replaced by a low tbr icon)...

**Comment by guydavies** [comment]
Hi Philoul,

I have seen the request for a TBR pointing at exactly my current programmed basal for my MDT640G as a virtual pump.  I’ll be switching to DanaRS v3 soon so probably won’t see it again.

Rgds,

Guy
