### ISSUE TITLE
[Enhancement] Upload AAPS Data to two different NightScout sites.

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2816]
Is it possible to include the option to upload AAPS data to two different NightScout sites, as it is in XDrip+ (site1;site2) ?

If I can upload the data to 10be and to Heroku, I always have a 1:1 backup and if something goes wrong with one of them, I can change to the other one.

If it is to mutch work, or not possible, please close this issue.

**Comment by ToreBj** [comment]
+1

**Comment by MilosKozak** [comment]
not possible with current nsclient and not planned in the future
