### ISSUE TITLE
2.6.7 beta2: current location not available when adding new automation rule

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#2818]
When adding a new location trigger in automation module, the current location is not available when pushing on 'current location'. It doesn't matter what location service is used. Tested on Samsung Galaxy S7 and Google Pixel 2.

![Screenshot_20200713-082400_AndroidAPS](https://user-images.githubusercontent.com/32912987/87277805-5b80a800-c4e3-11ea-80d5-d5023f74ab15.jpg)

**Comment by xJoe** [comment]
Can confirm problem on Pixel 2.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/9ff3011514552c946b442f7adf32ec13172d03ff
