### ISSUE TITLE
Bolus wizard suggests bolus unsupported by pump

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#282]
e.g. 0.45 U when the pump only supports 0.1 U increments, thus either 0.4 U or 0.5 U.
Should the wizard honour the pumps capabilities or should this be rounded by the pump code?

**Comment by AdrianLxM** [comment]
I'd prefer having the feedback in the GUI. The pump-plugin does report the "Bolus Step".

**Comment by AdrianLxM** [comment]
fixed in #285. Thanks @jotomo
