### ISSUE TITLE
maxSMBBasalMinutes not working as expected

### ISSUE THREAD

**Issue by Rhabarbara745** [MilosKozak/AndroidAPS#2820]
https://github.com/openaps/AndroidAPSdocs/issues/876
can someone with deeper understanding of the oref algorithm confirm this?

The reason I am asking, yesterday I had a hypo and took therefore fast carbs (without entering them in AAPS).
According to my code insights of [determine-basal.js](https://github.com/MilosKozak/AndroidAPS/blob/master/app/src/main/assets/OpenAPSSMB/determine-basal.js) I expected `maxSMBBasalMinutes` would be 30 because COB was 0.
**Instead a single SMB with 120 Minutes of Basal got administered.**  

How is this possible? Please correct me if I’m looking at the wrong code parts.

**Comment by Rhabarbara745** [comment]
Strangely enough also the openaps log of that SMB looked different than usually

![output](https://user-images.githubusercontent.com/57756367/87664811-2b950700-c766-11ea-99fd-5913c896dc3c.jpg)

![Screenshot_20200716-124655](https://user-images.githubusercontent.com/57756367/87664822-318ae800-c766-11ea-9e00-dc3f35459859.png)

**Comment by MilosKozak** [comment]
what is wrong in AAPS?

**Comment by Rhabarbara745** [comment]
The version of the oref0 algorithm in AAPS 2.6.1 delivered 120 Minutes (current setting in preferences) of Basal although there were no COB.

According to the docs SMBs with size of `maxSMBBasalMinutes` are only allowed if there are COB which are not yet covered by Insulin.
