### ISSUE TITLE
Bluetooth issue with the DANARS AAPS 2.6.7 Beta2 Firmware V1 

### ISSUE THREAD

**Issue by MTR93600** [MilosKozak/AndroidAPS#2824]
In this version, i can't connect the pump if my password start by 0. In the log only the last 3 numbers sent to the pump, the first one, 0, is missing. I change the password in the pump, starting by 2 and it works very well. 

10:56:07.149 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.processConnectResponse():437]: <<<<< ENCRYPTION__PUMP_CHECK (OK) 02 00 4F 4B  
10:56:07.150 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.processConnectResponse():442]: Using stored pairing key: 571C
10:56:07.152 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.sendPasskeyCheck():509]: >>>>> ENCRYPTION__CHECK_PASSKEY A5 A5 04 DF  22 87 9A 9F  C4 5A 5A 
10:56:07.295 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.processPasskeyCheck():515]: <<<<< ENCRYPTION__CHECK_PASSKEY 02 D0 00 
10:56:07.297 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.sendTimeInfo():577]: >>>>> ENCRYPTION__TIME_INFORMATION A5 A5 02 DF  F3 81 4E 5A  5A 
10:56:07.443 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():533]: <<<<< ENCRYPTION__TIME_INFORMATION 02 01 14 07  11 0A 38 09  86 04 
**10:56:07.444 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.processEncryptionResponse():558]: Pump user password: 871**
10:56:07.445 [Binder:22505_1] E/PUMPBTCOMM: [BLEComm.processEncryptionResponse():560]: Wrong pump password
10:56:07.446 [Binder:22505_1] D/PUMPBTCOMM: [BLEComm.disconnect():129]: disconnect from: WrongPassword

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/38e2ae90d8e10ed62f599a79ce01fab439cf3224
Thanks!
