### ISSUE TITLE
SMB with temporary target

### ISSUE THREAD

**Issue by Korostensky** [MilosKozak/AndroidAPS#2825]
2.6.7 beta 2
--------------
**SMB with temporary target**
- settings
![20200715_211048](https://user-images.githubusercontent.com/54218454/87804531-4b0a5d80-c854-11ea-8196-a0116dec1ee7.jpg)
- **SMB** was still applied
![Screenshot_20200715-233708_NSClient](https://user-images.githubusercontent.com/54218454/87805006-f74c4400-c854-11ea-800c-4fd7d9a9b08e.jpg)
- Profile target
![20200715_204446](https://user-images.githubusercontent.com/54218454/87805335-6de94180-c855-11ea-9a54-ade9f4317f64.jpg)

**Comment by MilosKozak** [comment]
i need to see if TT was set on AAPS. not nsclient

**Comment by Korostensky** [comment]
IT was set on AAPS with automation.

https://www.facebook.com/groups/AndroidAPSCZ/permalink/1161863887514858/

![20200715_204433](https://user-images.githubusercontent.com/54218454/87941964-35877480-ca9c-11ea-9abc-a445f0f4cc08.jpg)

**Comment by MilosKozak** [comment]
provide logs from AAPS pls

**Comment by Korostensky** [comment]
https://drive.google.com/file/d/1ueSK8iJfjsYR6OqM0a9VGznBc_SmUQ5P/view?usp=drivesdk

**Comment by MilosKozak** [comment]
and time of occurence within this log?

**Comment by Korostensky** [comment]
![20200720_162855](https://user-images.githubusercontent.com/54218454/88394738-397b0580-cdc0-11ea-9a82-5f3699f09a09.jpg)
![20200720_162819](https://user-images.githubusercontent.com/54218454/88394750-3c75f600-cdc0-11ea-8647-5874c03fb4c3.jpg)
![20200720_162811](https://user-images.githubusercontent.com/54218454/88394756-3ed85000-cdc0-11ea-83dd-27fff4faae73.jpg)
20.7. 16:27?

**Comment by MilosKozak** [comment]
this date is not in logs

**Comment by Korostensky** [comment]
https://drive.google.com/folderview?id=1u_BY8PQy6Msj9QCoVyFcHudYFAhDiI7A

Second try see attachment.
What's the time sequence in the exported log?

**Comment by MilosKozak** [comment]
smb enable always has higher priority in this case.
i updated preferences a bit to make it more clear 
https://github.com/MilosKozak/AndroidAPS/commit/007df3aab33c6b6b70bcd2a3e0df810c786101a1
