### ISSUE TITLE
2.6.7Beta2: Error at Bolus delivery / Bolus succesfull delivered

### ISSUE THREAD

**Issue by EknalpTiel** [MilosKozak/AndroidAPS#2826]
Got Message: Error at Bolus delivery.
The pump was delivering the Bolus.
Later AAPS gilt this Information by reading pump history.

This error normaly lets the User deliver the bolus again. This is dangerous!

Logs dent by Email containing Bug id.

AAPS 2.6.7 Beta2
MDT 722
Software encoding

**Comment by Alamo04** [comment]
Confirmed. 
But this is an old issue and happened extreme rarely, it was also reported in Facebook from time to time.

A new user, or a user who only check AAPS, should give a second bolus, without checking the pump history. This was also reported in Facebook.

**Comment by EknalpTiel** [comment]
I think it's Importamt to find the error.
How big and red must the letters of the warning message be? Not every user is checking the pump in this situation even if trusted it before?

**Comment by MilosKozak** [comment]
this can happen anytime. Starting bolus and then broken communication.
Everyone MUST check pump on these errors. Repeating bolus without check is a way to hell
