### ISSUE TITLE
Beta2: Notification requesting 0g carbs 

### ISSUE THREAD

**Issue by an-di-looper** [MilosKozak/AndroidAPS#2827]
AAPS has requested 0g carbs several times. Maybe this is a bug? 

![Screenshot_20200718-111302_Samsung Experience Home](https://user-images.githubusercontent.com/68446861/87849313-dda80c80-c8e7-11ea-84c9-57bc3d742280.jpg)

**Comment by the-swish** [comment]
Still present in 2.7.0-rc1.
Carbs and time are in the wrong order in the German string for carbsreq.
For this example, it should be 5 g in the next 0 minutes.

**Comment by an-di-looper** [comment]
Ah, you mean it's a translation problem? Wrong string in German?

**Comment by an-di-looper** [comment]
I checked. Translation is: 'Innerhalb der nächsten %d Minuten werden %dg zusätzliche Kohlenhydrate benötigt', that should be OK. 

'Minimum Carbs Required For Suggestion' setting is 1.

**Comment by the-swish** [comment]
The first %d is always replaced by carbs and the second %d with minutes.

`return String.format(resourceHelper.gs(R.string.carbsreq), carbsReq, carbsReqWithin);`

The German text must be changed to something like `%dg zusätzliche Kohlenhydrate werden innerhalb der nächsten %d Minuten benötigt`

**Comment by an-di-looper** [comment]
Fixed in German translation
