### ISSUE TITLE
2.6.7 Beta 2 [BUG] Automation Notification Timestamp

### ISSUE THREAD

**Issue by m4nnihuber** [MilosKozak/AndroidAPS#2829]
Timestamp for Notification created with Automation Rule ie always 01:00 

Tried to create a Notification when BG rises over 180.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/05eee2ebb9cdb423b8a4b1868e0cdc6dff70a0ee
Thanks!
