### ISSUE TITLE
Hardcoded "New temp actions"

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#283]
info/nightscout/androidaps/plugins/Actions/ActionsFragment.java:215, onClick handler: uses _DanaRv2Plugin_ instead of active pump. I don't see anything pump-specific about high/low temps actions, hence it would be nice to generalize this to work for all pumps.

**Comment by MilosKozak** [comment]
it's test code added during refactoring. allign you code with current dev, it's already removed

**Comment by jotomo** [comment]
Whops, sorry, will update :-)
