### ISSUE TITLE
Automatic Carb entries without any manual action in AAPS

### ISSUE THREAD

**Issue by HeidiBoermans** [MilosKozak/AndroidAPS#2831]
Yesterday and today I had an issue that AAPS registered carbs without an entry from my part. Today the app did this four times, this morning, at lunch, at dinnertime and later this evening. The last time was 21h22 and the system registered 20gr carbs without any action from me. It appeared on COB just after AAPS made a connection with my AC Insight pump. Here are some print screens from AAPS, Nightscout and log files. AAPS Version 2.6.1 I've never had this before since I started looping more than one year ago. Look at the following rules in the log file; 8432 and 8440. 

Thanks in advance for looking at this issue!

![Printscreen 1](https://user-images.githubusercontent.com/50968714/87884311-1e01aa80-ca0e-11ea-8884-99be001b9217.jpg)
![Printscreen 2](https://user-images.githubusercontent.com/50968714/87884313-20fc9b00-ca0e-11ea-9a32-cacb5b63ea3a.jpg)
![Nightscout](https://user-images.githubusercontent.com/50968714/87884319-26f27c00-ca0e-11ea-9990-d707c281a695.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/4944564/AndroidAPS.log)

**Comment by Suchiman** [comment]
Looks like AAPS is getting a treatment from the pump with `pumpId= 1572625449052` that matches a treatment in the database that is a few months old already and overwrites that one (except for the carbs which then become "now" again).

**Comment by MilosKozak** [comment]
it looks like corrupted database.
clear NS data, then clear AAPS data
