### ISSUE TITLE
2.6.7RC1: Profile helper - Target line feed

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2833]
Compared targets would be easier to read if there was a line feed after each new time slot:

00:00 100,0 - 100,0 mg/dl
06:00 110,0 - 110,0 mg/dl
...

instead of 

00:00 100,0 - 100,0 mg/dl 06:00 110,0 - 110,0 mg/dl...

**Comment by MilosKozak** [comment]
screenshot?

**Comment by xJoe** [comment]
![target](https://user-images.githubusercontent.com/13958493/88166302-588a6380-cc17-11ea-836f-183185dbb1f7.png)

**Comment by Philoul** [comment]
PR made to add new line (see screenshot with modification)
![Screenshot_20200724-011441_AndroidAPS](https://user-images.githubusercontent.com/52934600/88347590-56292600-cd4b-11ea-9af3-338e856dd985.jpg)

**Comment by xJoe** [comment]
Great! Thanks!
