### ISSUE TITLE
"Eating Soon" TT continues at 4.0 Target after timer expires

### ISSUE THREAD

**Issue by artirgeci** [MilosKozak/AndroidAPS#2834]
Is anyone else observing a similar issue? Just tried in 2.7.0-rc1, same behavior. It doesn’t look normal to me, or am I'm missing something?

After the 30min period when TT ends, the bar/button turns green and continues with a target at 4.0 (Eating Soon target value).

I need to restart the app, for my target to return to normal.

Time when I enabled manually the "Eating Soon" mode (18:46:48.638)
Time when it continued at 4.0 target with green button, after the "Eating Soon" timer ended (19:17:48.633)
Build: e44080802-2020.07.03-22:23 (2.6.7-beta2)
[AndroidAPS._2020-07-16_00-00-03_.8.zip](https://github.com/MilosKozak/AndroidAPS/files/4933910/AndroidAPS._2020-07-16_00-00-03_.8.zip)
[AndroidAPS._2020-07-16_00-00-03_.9.zip](https://github.com/MilosKozak/AndroidAPS/files/4933911/AndroidAPS._2020-07-16_00-00-03_.9.zip)

![image](https://user-images.githubusercontent.com/23337996/87716869-c108b900-c7af-11ea-9cc7-5813f66360d9.png)

_Originally posted by @artirgeci in https://github.com/MilosKozak/AndroidAPS/issues/2808#issuecomment-659639979_

**Comment by hartlijn** [comment]
Had the same.

**Comment by MilosKozak** [comment]
there is lot of changes in RC1. i need logs from this version

**Comment by artirgeci** [comment]
Sure, I will upload the logs later Today. One thing I noticed is when my BG source is from NSClient, this does not happen. With xDrip as a source,  I was able to enact every time I try.

**Comment by artirgeci** [comment]
It seems that even that the target "stays" at 4.0, it's not affecting the functionality, also i notice the graph target line turns to normal after timer expires. Could this be only graphical issue? 

I will try to test it more in the coming days.

**Comment by MilosKozak** [comment]
yellow means active TT
green means ajusted by smb alg (or used different value than current settings in last run)

**Comment by artirgeci** [comment]
Milos, I understand what they mean. Not sure why you think I don't understand the basics of how aaps works? It is very dangerous if it keeps the lower target at 4.0 after timer expires! 

Other users are reporting something similar, why close it?

**Comment by MilosKozak** [comment]
can you provide example with logs on RC1 or latest dev?

**Comment by artirgeci** [comment]
Thanks for reopening! I'm still unsure of the trigger, because it's not happening all the time with RC1

If I can't enact it until tomorrow, I will close it by tomorrow. 

Thanks

**Comment by hartlijn** [comment]
Logs send by mail.
It seems a UI thing. I set a temp target of 8. After the period the TT renaims green, but the SMB resultlog shows my original target. See screens.
![Screenshot_20200724-180538](https://user-images.githubusercontent.com/28272471/88411889-02651e00-cdd9-11ea-8607-2d6d0c9bc20e.jpg)
![Screenshot_20200724-180525](https://user-images.githubusercontent.com/28272471/88411909-0b55ef80-cdd9-11ea-849a-85980df9824c.jpg)
![Screenshot_20200724-180513](https://user-images.githubusercontent.com/28272471/88411920-10b33a00-cdd9-11ea-8629-29f07c2b4436.jpg)

**Comment by artirgeci** [comment]
I was unable to trigger it with "Eating Soon" mode on RC1. Let me know if I should close this?
