### ISSUE TITLE
2.7.0-rc1: NSClient and Pumpcontrol Automation operations

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2835]
NSClient 2.7.0-rc1

I am not sure if NSClient and Pumpcontrol applications should have Automation operations but such can be created but it is not causing any operations or notifications. One clue is that in the Automation window there are "Loop is disabled" texts at the bottom of the window.

However, Automation is working as expected in AAPS application (2.7.0-rc1).

**Comment by MilosKozak** [comment]
TODO: disable automation for nsclient

**Comment by reijoahola-nightscout** [comment]
What about Pumpcontrol application ? Should Automation be disabled ?

**Comment by MilosKozak** [comment]
resolved in dev
