### ISSUE TITLE
[2.7.0-RC1] Biometric challenge when changing settings

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#2836]
I tried to change the language and was prompted with the biometric challenge and the master password dialog simultaneously. Is this intended?

I use the biometric challenge for securing the app itself and the settings.

**Comment by MilosKozak** [comment]
is it replicable?

**Comment by quizzmaster** [comment]
yes, it is

**Comment by MilosKozak** [comment]
for me it works well. send screenshot of your settings and steps to reproduce
