### ISSUE TITLE
[2.7.0-RC1] Profile helper: Questions and Bugs

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#2837]
Questions:
- Where does the Standard-Profile come from (it looks rather odd to me)?
- What does DPV stand for?
- Why does the DPV profile not print out any IC/ISF?
- Is the input of weight **or** TDD intended?

Bugs:
- If you input an age >18 you get an error, which doesn't really help, if one doesn't know that the form of the basal profile doesn't change if over 18.
- You can input a weight for the DPV profile, but it does only work with the TDD right now

Improvement:
- Shouldn't there be a field for shifting the whole profile according to when you normally get up?

**Comment by MilosKozak** [comment]
will be explained in docs
i don't have data for 18+

**Comment by CaroGo** [comment]
Sorry for asking again...
but those who are going to write the docs need to test and understand it... Is there any way to get more information about how the profile helper is expected to work?
