### ISSUE TITLE
[2.7.0-RC1] Biometric lock don't work propperly

### ISSUE THREAD

**Issue by quizzmaster** [MilosKozak/AndroidAPS#2841]
I suppose the biometric lock for the whole app should really lock the app.
Although the fingerprint sensor gets activated, the app isn't locked at all. I still was able to use the bolus wizard and other functions.

**Comment by ArthurusDent** [comment]
@quizzmaster How exactly did you circumvent it? Have a look at this issue: #2796

Did you set a master password?

You still can circumvent the biometric lock if you disregard the alert about setting a master password.

**Comment by MilosKozak** [comment]
do you have  master pass set?

**Comment by quizzmaster** [comment]
Yes, thats what I did before activating the biometric lock

**Comment by MilosKozak** [comment]
for me it works well. send screenshot of your settings and steps to reproduce

**Comment by quizzmaster** [comment]
Steps to reproduce:

1. Set Master-Password
2. Set app protection to biometric
3. Close App and reopen:  
   My in-screen fingerprint reader gets activated, but I can control every part of the app and even bolus

Settings:
![photo_2020-07-31_00-24-13](https://user-images.githubusercontent.com/2745710/88980562-4453ff80-d2c4-11ea-8640-100864309f1b.jpg)

**Comment by MilosKozak** [comment]
i ended up in this state and i cannot skip it
![image](https://user-images.githubusercontent.com/11146458/89006790-c3b6f280-d307-11ea-9f60-1521d2661138.png)

**Comment by quizzmaster** [comment]
That's what I get with the app being fully responsive while the Icon for the fingerprint reader is being displayed.

![image](https://user-images.githubusercontent.com/2745710/89012980-5e68fe80-d313-11ea-99c9-37f485a84f81.png)

**Comment by MilosKozak** [comment]
what phone is it?

**Comment by quizzmaster** [comment]
It's a OnePlus 6T. Other Apps with biometric protection work fine, maybe there is something odd going wrong

**Comment by MilosKozak** [comment]
ok, it's know issue of OnePlus
https://forums.oneplus.com/threads/problems-about-oneplus-6t-fingerprint-api.944959/

**Comment by Stealthwick** [comment]
![Screenshot_20200731-204101](https://user-images.githubusercontent.com/40660629/89027660-3955a980-d36e-11ea-9ae0-0796990fc849.jpg)

All working correctly on OnePlus 5T - Oxygen OS 9.0.11

**Comment by ArthurusDent** [comment]
The Oneplus 5T has a normal fingerprint scanner on its back.

I have a Oneplus 3T and it works for me, too.

**Comment by larsvandoremalen** [comment]
I cannot reproduce on xiaomi note 10 lite with on-screen fingerprint reader. When I cancel the reading, it jumps to master password when I cancel that AAPS closes after a message authorization failed.
