### ISSUE TITLE
[2.7.0-rc1] Reporting incorrectly new version?

### ISSUE THREAD

**Issue by AndyS117** [MilosKozak/AndroidAPS#2842]
Occured 15:31 UTC, alert / pop-up stating "New version for at least 1 days available!" Fall-back to LGS after 7 days, loop will be disabled after 14"

Build: b5957db98-2020.07.20-16:32

Log section:
16:31:12.885 [RxCachedThreadScheduler-5] D/APS: [Profiler.log():13]: >>> calculateIobArrayInDia() <<< executed in 255 miliseconds
16:31:12.893 [RxCachedThreadScheduler-2] D/NOTIFICATION: [NotificationStore.add():60]: Notification received: New version for at least 1 days available! Fallback to LGS after 7 days, loop will be disabled after 14 days
16:31:12.898 [RxCachedThreadScheduler-5] D/CONSTRAINTS: [StorageConstraintPlugin.isClosedLoopAllowed():40]: Internal storage free (Mb):90838
16:31:12.899 [RxCachedThreadScheduler-5] D/APS: [Profiler.log():13]: >>> detectSensitivityandCarbAbsorption() <<< executed in 13 miliseconds

**Comment by artirgeci** [comment]
I just had the same msg.

**Comment by overfrenk** [comment]
Same msg for me.Only 1 notification!

**Comment by AdrianLxM** [comment]
My guess is that it is a timing issue that only appears on release candidates.
There the warn-level is one day - and the check is done at most once a day.

If you are online and it doesn't say 2 days tomorrow, it is only a warning that happens on RCs.
Could you please report back.

**Comment by AndyS117** [comment]
@AdrianLxM Okay looks like a RC warning. Still says New Version for at least 1 day.

Can I assume then that as long as it remains as 1 day in that warning it can be ignored and can just be treated as nuisance warning?
If that is the case I close the issue.

**Comment by Alamo04** [comment]
Message Confirmed
