### ISSUE TITLE
NSClient Authentification not possible via WiFi

### ISSUE THREAD

**Issue by Volberger** [MilosKozak/AndroidAPS#2843]
Tried version 2.7 RC1 today.  I use medtronic 712 with RileyLink and a motorola mobile G5plus. NSClient shows status "not allowed" when wifi is used. Queue fills up gradually and is not emptied.  If wifi is switched off and mobile network activated, the authentification works, status "autheticated (RWT)" and the queue is transmitted immediately.

**Comment by MilosKozak** [comment]
paste screenshot of nsclient connection settings

**Comment by Volberger** [comment]
Here are the wanted ScreenShots:
Not allowed when WIFI is switched ON
https://drive.google.com/file/d/1vz11PgUmKlGb2oBa0jsMj2RFbJPJTgZ7/view?usp=sharing

Authenticated when WIFI is switched OFF
https://drive.google.com/file/d/1w1zP94Oojcpcgd_ayfvp1R0GKmMHr3cs/view?usp=sharing

**Comment by MilosKozak** [comment]
i need your settings

**Comment by Volberger** [comment]
![Screenshot_20200728-081607](https://user-images.githubusercontent.com/48906527/88626992-e51ba280-d0ab-11ea-976b-70598f31b0d9.png)
![Screenshot_20200728-081550](https://user-images.githubusercontent.com/48906527/88626995-e64ccf80-d0ab-11ea-90db-8ca7f60fbdd4.png)
![Screenshot_20200728-081814](https://user-images.githubusercontent.com/48906527/88626997-e64ccf80-d0ab-11ea-8005-66544d1fb912.png)
![Screenshot_20200728-081514~2](https://user-images.githubusercontent.com/48906527/88626998-e6e56600-d0ab-11ea-9cad-4bf100d2394a.png)

**Comment by MilosKozak** [comment]
remove doublequotes from SSID

**Comment by MilosKozak** [comment]
closed by inactivity
