### ISSUE TITLE
NS Client 2.7.0-rc1  no CGM Button

### ISSUE THREAD

**Issue by HenryNightt** [MilosKozak/AndroidAPS#2844]
No CGM button and calibration, although activated.
Pump catheter and insulin reservoir button are unfortunately missing.

**Comment by guydavies** [comment]
Pump catheter and reservoir buttons appear in the Actions tab now.  Careportal was removed.  There’s a single button that has two checkboxes when you select it, one each for swap catheter and fill reservoir so you have the flexibility to do them together in a single action or separately if you need.

I don’t know if that’s any different in the NS Client, I’m using the full release.

**Comment by HenryNightt** [comment]
Then probably only in the full version.
Unfortunately we cannot use this (Omnipod).
In the NSClient version there is no insulin / pump change under Action.

**Comment by guydavies** [comment]
There’s no reason why you cannot use the full version with Omnipod as a virtual pump.  I’m using it right now with the Medtronic 640G in exactly that mode.  Sure, using the precompiled versions is more convenient, but you are limited in the ways you describe, it would seem.

**Comment by HenryNightt** [comment]
I didn't think of it. Very good idea! THX.

**Comment by MilosKozak** [comment]
removed from nsclient
