### ISSUE TITLE
[2.7.0-rc1] Manually setting temporary basal no longer possible? 

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2846]
It seems like it is no longer possible to manually set a temporary basal while loop is deactivated. Is this the case or did I just not see it? 
It is really important for me to have this feature in order to set temporary basals manually (i.e. for physical activity) and not only rely on temporary targets.

**Comment by swissalpine** [comment]
This is still possible in the Action tab after selecting "Suspend Loop" by long clicking on the Loop icon (then in the Action tab: Cancel TBR -> Set TBR).

**Comment by RobHoff** [comment]
> 
> 
> This is still possible in the Action tab after selecting "Suspend Loop" by long clicking on the Loop icon (then in the Action tab: Cancel TBR -> Set TBR).

Unfortunately, the cancel TBR/Set TBR button is missing. Not only while the loop is inactive, but all the time

![Screenshot_20200723-090056_AndroidAPS 1](https://user-images.githubusercontent.com/50026512/88259861-7ca37e80-ccc3-11ea-9586-530277a0612b.jpg)
![Screenshot_20200723-090102_AndroidAPS 1](https://user-images.githubusercontent.com/50026512/88259872-85945000-ccc3-11ea-9e83-e54803946f7a.jpg)
![Screenshot_20200723-090233_AndroidAPS 1](https://user-images.githubusercontent.com/50026512/88259884-8c22c780-ccc3-11ea-9e10-ae6ab05a7c32.jpg)

**Comment by reijoahola-nightscout** [comment]
This problem does not exist in my rc1 installation.

**Comment by reijoahola-nightscout** [comment]
It looks like PROFILE SWITCH button is also missing from your Actions-page picture.

**Comment by swissalpine** [comment]
Thanks for the screenshots: You haven't activate your pump but MDT (= ICT), a modus without pump. Activate your pump in config builder and you will see the buttons.

**Comment by RobHoff** [comment]
> Thanks for the screenshots: You haven't activate your pump but MDT (= ICT), a modus without pump. Activate your pump in config builder and you will see the buttons.

That's actually incorrect. I use an older medtronic pump and the loop is working fine. However, the buttons are missing.

**Comment by reijoahola-nightscout** [comment]
I do not have Medronic pump but when I select in my test system MDT (no real comnection into the pump) those buttons are missing. Are you sure that your Riley link and the pump connection is working ?

**Comment by MilosKozak** [comment]
this is situatiaon when pump is not initiliazed yet. once connected properly buttons appear
