### ISSUE TITLE
[2.7.0-rc1] Carbohydrate graph doesn't fit on the screen

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2848]
It seems like an additional graph beneath the usual BG/Basal graphs is too big to be shown on the screen without having to scroll. This was not the case in 2.6.4. Would it be possible to adjust it, so that at least one graph can be shown on the screen beneath without scrolling?
![Screenshot_20200723-090056_AndroidAPS 1](https://user-images.githubusercontent.com/50026512/88260283-5df1b780-ccc4-11ea-9773-fe0764498f50.jpg)

**Comment by swissalpine** [comment]
Can't you scroll a little bit up?

**Comment by MilosKozak** [comment]
it's not possible. the UI logic changed from 2.6
