### ISSUE TITLE
Security backup of all settings and progresses

### ISSUE THREAD

**Issue by Mog1970** [MilosKozak/AndroidAPS#2851]
Is there a possibility to backup all settings and progresses in order to install the full app including all appdata on another phone without the need to go through the full set up process in case the first phone gets lost, damaged, etc.?

**Comment by ArthurusDent** [comment]
This is not the right place to ask for help. This is for bugtracking.

Please find help in those places: https://androidaps.readthedocs.io/en/latest/EN/index.html#where-to-go-for-help

To answer your question, you can export your settings including the progress of objectives: https://androidaps.readthedocs.io/en/latest/EN/Usage/ExportImportSettings.html
You might be able to export the on-device database but I don't know how. 

Please close this issue.
