### ISSUE TITLE
[2.7.0-RC1] Multiple graphs

### ISSUE THREAD

**Issue by JohnKitching** [MilosKozak/AndroidAPS#2853]
New to testing, hope I'm not stuffing this up too badly!
I think this is an enhancement but I'm not sure how to flag it as such. I've checked for similar issues but can't find one. 

A few points on the multiple graphs (which are already a brilliant addition):

- Multiple scales if more than one variable on a graph. 

- Sensitivity shown as a percentage same as the main display

- When modifying graphs keep the settings onscreen until clicking off them, making a lot of changes takes a while as the settings disappear each time (I'm assuming it's not me and can only see to change them from the dropdown)

**Comment by MilosKozak** [comment]
all this is limitted by used graph and android libraries. not possible
