### ISSUE TITLE
[2.7.0-RC1] Nightscout pump info pill not populated

### ISSUE THREAD

**Issue by JohnKitching** [MilosKozak/AndroidAPS#2854]
![image](https://user-images.githubusercontent.com/48366213/88466325-0c634b80-cec3-11ea-9ee7-ce1d809548a8.jpeg)

**Comment by JohnKitching** [comment]
Sorry. Literally a couple of minutes later it updated but I've been running 2.7 for hours. Will post again if it does it again. ![image](https://user-images.githubusercontent.com/48366213/88466408-e12d2c00-cec3-11ea-8215-58c41348ab81.jpeg)

**Comment by JohnKitching** [comment]
Gone again so it looks like it is an issue.

**Comment by Alamo04** [comment]
Have that sometimes with RC1, but also with the earlier and actual Dev's.
But the pump pill comes back with the next reading, so I didn't report tthat.
Not realy important for me.

**Comment by JohnKitching** [comment]
I’ve not noticed it with earlier versions. 
I’m not saying it’s important, just thought whoever wrote that bit might want to know.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/b7221aa2861ed70281155ca71d76add899e436f3
