### ISSUE TITLE
[Enhancement]  All Versions - Please change the background color to dark black.

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2855]
I hate this gray background in AAPS, why is not a real black one used in AAPS as it is in XDrip ? This should also save batterie a little bit. 

Can we change that, or bring in an option for it in Android Studio ?

Please close, if it is not possible, or not wanted.

**Comment by ArthurusDent** [comment]
I'm actually quite happy with the dark grey. The Twitter app gives you the option to get pure black or dark grey as a background and I do find the pure black a bit too harsh. Dark grey is easier for my eyes. Also, xDrip+ doesn't use pure black. On its homescreen it uses an even darker grey than AndroidAPS. The menus use a colour gradient with pure black at the top. I would guess that you already do get a good amount of battery saving on AMOLEDs this way.

**Comment by Suchiman** [comment]
I find the infinite contrast of AMOLED Black very pleasing
![image](https://user-images.githubusercontent.com/7110884/88480274-58f76700-cf55-11ea-9189-d92202a2f43f.png)

**Comment by MilosKozak** [comment]
design changes are tricky . you always find people who like it and who not
