### ISSUE TITLE
[2.7 - RC1] Phone restart caused AAPS to “lose” pump

### ISSUE THREAD

**Issue by JohnKitching** [MilosKozak/AndroidAPS#2856]
Dana RS (2.x firmware). I restarted phone and on opening AAPS pump wasn't connected. 
Screenshots attached and I'll email logs. 

Had to re-pair pump.

 ![image](https://user-images.githubusercontent.com/48366213/88559285-8bbc6080-d024-11ea-9f04-d6836ab51635.png)

![image](https://user-images.githubusercontent.com/48366213/88559365-a2fb4e00-d024-11ea-9f8c-75031467951b.png)

**Comment by JohnKitching** [comment]
I restarted phone again to check and AAPS had lost connection to pump again. 
Happy to do any testing I can to help.

**Comment by guydavies** [comment]
Hi John, I think you may need to re-enter your pump password/passcode because it was ignored prior to 2.6.  Now it is strictly checked, so I think it has to be re-entered.

**Comment by JohnKitching** [comment]
Thanks Guy,
That was definitely an issue when I first installed 2.7 but I don't think it is now. 
I've checked and the password is in AAPS and is correct. 
When I restart the phone the pump isn't connected but if I go to the config builder, Dana RS, selected pump it re-pairs without an issue.

**Comment by MilosKozak** [comment]
this is BT issue of your phone
AAPS just tell android "connect"

**Comment by JohnKitching** [comment]
When I first installed 2.7 I had connection problems due to pump password. When I was trying to solve it I removed the pump from Bluetooth devices on the phone. 
Could that be the problem?
I've tried re-adding it through Bluetooth settings but it's not adding. 
Or should AAPS be adding it if it's not there?
Is it possible that because AAPS knew it was once there it's not trying to add it?

**Comment by guydavies** [comment]
I seem to remember there being a procedure that's similar for when you move
to a new phone and use your backup data. AAPS "knows" about the device
because it's in your backup but the phone doesn't. Sorry,  I'm not at an
interface that would make it easy to search but there was definitely
something relatively recent on one of the lists (FB, GitHub or Discord)
IIRC.

**Comment by JohnKitching** [comment]
I'm not certain but I may have fixed it by clearing the Bluetooth cache. 
Sorry.
