### ISSUE TITLE
Units to fill/prime are added to IOB after Pump failure.

### ISSUE THREAD

**Issue by sve-bra** [MilosKozak/AndroidAPS#2858]
Hello,
my setup is: AAPS 2.6.1.2, Android 10, Dana RS (V1.0)
On Sunday I filled the pipe via the action tab in AAPS as I always do, but I forgot to type in the new reservoir level (my mistake) and the pump stopped when 0 U were left in the tank (in truth there where almoste 300 U in there, but pump couldn't know it). I git an Alarm from the pump but sadly the alarm didn't end as usual (it's not important) so I removed the battery. When the pump reconnected to AAPS the IOB was wrong, cause the priming units were added.
My log file is on its way.

This seems a similar problem to the issue #2489 
For me the IOB was obviously wrong, so I deleted this entry and was good to go. I will try to reproduce it. with the next tubing.

I wanna say a huge thank you to all developers of AndroidAPS! You guys are awesome! THX

**Comment by MilosKozak** [comment]
this can simply happen if comm is broken, app restarted etc. and it has to be manualy resolved.
there is no flag in pump "this was priming"
