### ISSUE TITLE
[2.7 - RC1] closing or crashing overnight

### ISSUE THREAD

**Issue by JohnKitching** [MilosKozak/AndroidAPS#2859]
Two nights running AAPS hasn't been running in the morning. I've only been running 2.7 for two days. 
No alarms for missing data
Battery optimisation for app is off 
I will email current logs.

**Comment by MilosKozak** [comment]
thre is no crash visible in log and no crashreport uploaded for Pixel 3 XL
i cannot help

**Comment by JohnKitching** [comment]
It's done it again. 
I'm fairly convinced it's a 2.7 problem but there's nothing else I can do. Going back to release version. Sorry I couldn't be more help.

**Comment by JohnKitching** [comment]
Fixed with a full reset of phone. 
At least it went one night without exiting.
