### ISSUE TITLE
AAPS 2.6.1.4: Statistics/TDD does not include Extended boluses

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2861]
Android APS 2.6.1.4
Fullrelease
Insight pump

Home page top right menu / Statistics analysis for TDD does not contain extended boluses, not in Bolus count and not in basal count.
Extended bolus is shown in main display and Treatments page / Extended bolus page has it normally.

Tested also with 2.7.0-rc1 pumpcontrol application (virtual pump) and the same problem also there.

Is this a known issue ?

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/ba4f599242d7bcb145ba9f01bb4ecf8ec7c2d5d0
thanks!
