### ISSUE TITLE
Aaps freezes, and wont connect to Rileylink

### ISSUE THREAD

**Issue by Dani501i** [MilosKozak/AndroidAPS#2864]
Hi. My phone (Oneplus 8) wont connect to my rileylink. When trying to connect, it freezes the app, and then fails to connect to Rileylink. Video to show: https://www.youtube.com/watch?v=YMNYiZHB5c4

AAPS Log file
https://we.tl/t-GK2qo8jxT6

AAPS about window
Build: EROS_0.3-2020.07.30-14:00
Flavor: fulldebug
Nightscout version: 13.0.1
Engineering mode enabled

**Comment by MilosKozak** [comment]
sorry omnipod is not supported yet. contact devs on discord
