### ISSUE TITLE
[2.6.1.4 - 2.7-rc1] Setup Wizard: selecting mg/dL results in a profile with mmol/L

### ISSUE THREAD

**Issue by ArthurusDent** [MilosKozak/AndroidAPS#2865]
The problem occurs when setting up a fresh installation of AndroidAPS 2.6.1.4 - 2.7-rc1. Selecting mg/dL in the Setup Wizard leads to later being presented with a profile set to mmol/L. Going back to the choice between mg/dL and mmol/L doesnt change anything because mg/dL is still selected. Deleting the profile presents the user with a new profile with mg/dL. 
Expected behaviour: Selecting mg/dL should result in a profile with mg/dL.

![Screenshot_20200721-160011](https://user-images.githubusercontent.com/6848629/88982088-b0843280-d2c7-11ea-8901-411000332ed7.jpg)

![Screenshot_20200721-160657](https://user-images.githubusercontent.com/6848629/88982096-b548e680-d2c7-11ea-84b0-c1c58d1965e0.jpg)

![Screenshot_20200721-160759](https://user-images.githubusercontent.com/6848629/88982106-b9750400-d2c7-11ea-9575-3425879ed7e7.jpg)

Tested with:
Oneplus 3T (Android 9)
Dexcom G6
Medtronic 554
AAPS: 2.7-rc1 b5957db98
xDrip+: 2020.07.13
[AndroidAPS._2020-07-24_02-45-27_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5004185/AndroidAPS._2020-07-24_02-45-27_.0.zip)

Samsung S10+
FreeStyle Libre 2
MDI
AAPS: 2.6.1.4
xDrip+: 2020.07.13

Samsung Galaxy Note 8 - Android 9
Freestyle Libre 2
MDI
AAPS 2.6.1.4
xDrip+: Version 18b040a - 2020.04.18.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/4bacfad0db1d574dc8bbdaed662daaf19419443b
