### ISSUE TITLE
[2.xx] Insight pump, no zero temp during a reservoir change

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2875]
As you can see in image below, my pump stopped at 17:42 and started again at 17:46, during that time I change my reservoir, so to have correct IOB calculation I should have a zero temp TBR during that time...
As you can see on th right I had a TBR running between 17:19 and 17:49 (20%).
=> here gap is very little, but sometimes my reservoir change duration can be longer ...

![Insight_zerotemp_missing](https://user-images.githubusercontent.com/52934600/89128078-4d76e380-d4f3-11ea-83fe-72b02a9ef7e7.jpg)

[AndroidAPS._2020-08-02_18-33-53_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5012505/AndroidAPS._2020-08-02_18-33-53_.0.zip)

**Comment by TebbeUbben** [comment]
It only adds a TBR to the database if the pump has been stopped, not paused. The reason for this is that insulin that has not been delivered during the pause will be once the pump is started again. (The pump can only be in pause mode for up to 15 minutes, afterwards it automatically switches to stop mode.)

**Comment by Philoul** [comment]
Ok, thank's for the answer Tebbe.
If I understand zero temp is only added when the duration of my change is over 15 min, and then the zero temp duration is the total pause duration + stop duration ?
