### ISSUE TITLE
Bolus of 136,05 IE documented in AAPS-App that has not been entered or delivered

### ISSUE THREAD

**Issue by sannescgm** [MilosKozak/AndroidAPS#2876]
Hi everybody! 
Last night I noticed an IOB of >100 IU on my AAPS Home-Tab (my daily insulin dose is only around 50 IU). 
![Screenshot_20200802-213338_AndroidAPS](https://user-images.githubusercontent.com/41548035/89160573-92415f80-d571-11ea-8cb4-e22855711ed6.jpg)

Checking my traeatments ("Behandlungen") I found a bolus of 136,05 IU supposedly delivered at 21:13 (02.08.2020), which I never entered and which (considering my blood sugar and the filling state of my reservoir) never has been delivered.
After I pushed "Löschen" (delete) the entry stayed in the treatment list but with the addition "ungültig" (invalid). This invalid-addition was not there before I pushed delete, but unfortunately I only took a screen shot after pushing delete... The IOB went back to normal after pushing delete in the treatment list (see lower screenshot with AAPS-home tab).
![Screenshot_20200802-213911_AndroidAPS](https://user-images.githubusercontent.com/41548035/89160648-ad13d400-d571-11ea-9c9f-a3274c30ea1b.jpg)
![Screenshot_20200802-213833_AndroidAPS](https://user-images.githubusercontent.com/41548035/89160752-daf91880-d571-11ea-930b-f68e8a3939fd.jpg)

The bolus is not in the bolus-history of the pump. There is no bolus at all at 21:13 (last bolus was 2 IU at 18:24, next bolus was .1 IU at 21:41).
![20200803_095850](https://user-images.githubusercontent.com/41548035/89160770-e3515380-d571-11ea-9bf6-e9632bfec6cd.jpg)

136,05 can neither have been the filling of the reservoir at 21:13 (it should have been lower)...

PUMP: Medtronic Minimed 754 2.6A WW
RILEYLINK: firmware BLE113: ble_rfspy 2.0 ; CC110: subq rfspy 2.2
PHONE: Samsung S7, Android 8.0.0
AAPS: 2.6.1.4 ; build: 08730dfc9-2020.06.28-16:40
![Screenshot_20200803-073438_AndroidAPS](https://user-images.githubusercontent.com/41548035/89160792-ee0be880-d571-11ea-9f7f-5448357ab9e3.jpg)

Log that should contain the relevant timeperiod (event occurred at 02.08.2020, 21:13):
[AndroidAPS._2020-08-02_11-16-31_.4.zip](https://github.com/MilosKozak/AndroidAPS/files/5014678/AndroidAPS._2020-08-02_11-16-31_.4.zip)

Hope this will help explain and solve the issue :-)

**Comment by andyrozman** [comment]
Was bolus delivered, can you check on pump?

**Comment by sannescgm** [comment]
As I wrote in the post on github, the bolus is not in the bolus-history 
of the pump. There is no bolus at all in the bolus-history of the pump 
at 21:13 (last bolus was 2 IU at 18:24, next bolus was .1 IU at 21:41). 
There is also a photo of my pump displaying the bolus-history 
("Bolus-Speicher") of the corresponding time range in the github post.
As the bolus did not appear in the pump, my blood sugar did not react as 
if I had just gotten the 3-fold amount of my daily insulin and I did not 
notice the reservoir drop by a huge amount, I cannot imagine, that the 
bolus was actually given. It seems more like a "virtual fatamorgana" 
that none the less did affect the IOB-calculation...

Am 03.08.2020 13:58 schrieb Andy Rozman:

**Comment by andyrozman** [comment]
Problem found and solved. Should be in /dev soon. It was problem in history parsing.

**Comment by sannescgm** [comment]
I'm impressed, that was fast!Thank you for all your work!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Andy Rozman <notifications@github.com> Datum: 03.08.20  18:58  (GMT+01:00) An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com> Cc: sannescgm <Roeckl.S@posteo.de>, Mention <mention@noreply.github.com> Betreff: Re: [MilosKozak/AndroidAPS] Bolus of 136,05 IE documented in AAPS-App that has not been entered or delivered (#2876) 
Problem found and solved. Should be in /dev soon. It was problem in history parsing.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/2877
