### ISSUE TITLE
2.7.0 - rc2 -> DanaRS V3 connection error

### ISSUE THREAD

**Issue by veterlch** [MilosKozak/AndroidAPS#2880]
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5038497/AndroidAPS.log)
[AndroidAPS._2020-08-07_04-53-26_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5038498/AndroidAPS._2020-08-07_04-53-26_.0.zip)
[AndroidAPS._2020-08-06_23-59-38_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5038499/AndroidAPS._2020-08-06_23-59-38_.0.zip)

I have a problem with Dana-RS V3.

1. At first, the connection between the pump and AAPS is good, but after that, the pairing key of the pump keeps changing and the connection is difficult.
(This problem does not occur when using AnyDANA application.)

2. After rebooting my phone, AAPS apps keeps shutting down. (I cannot open my AAPS.)

**Comment by MilosKozak** [comment]
try clear pairing by long press on BT icon on Dana page

**Comment by veterlch** [comment]
After changing my BG source from Xdrip to patched dexcom app, the problem of being terminated of the application has disappeared. There might be errors in X-drip+ when  AAPS 

However, whenever I do my objectives(change basal profile, temporary basa) or bolus injection, I have to clear pairing and reconnect the pump with changed pairing key. 

[AndroidAPS[1].log](https://github.com/MilosKozak/AndroidAPS/files/5050955/AndroidAPS.1.log)
This log file is 2.7.0 - rc1 because I'm now trying AAPS with rc1 and rc2.

**Comment by veterlch** [comment]
The problem of being termination of the application appeared again after quit AAPS.
BT connection failure might be the reason, I think.

**Comment by MilosKozak** [comment]
the reason of crash is not visible from provided log
But I improved correct pairing detection of RSv3 anyway (in dev now)
