### ISSUE TITLE
2.7.0-rc2: Please help fine-tune UI typographic aspect

### ISSUE THREAD

**Issue by DM-LTR** [MilosKozak/AndroidAPS#2882]
I tried to find selected strings in crowdin, but struggle to find apropriate variables. Could you please help to find the right ones or confirm this has to be fixed in code itself?

After doing its math, bolus calc pop-up says: 
**Bolus: 1,9U (90%)
Sacharidy: 15g ( + 15 minut )**

Correct version for Czech language:
**Bolus: 1,9 U (90 %)
Sacharidy: 15 g (+15 minut)**

(note inconsistent spacing around parentheses in app and subtle differences in spacing in fixed version)

![Poznámka 2020-08-08 122718](https://user-images.githubusercontent.com/43177472/89707854-89d29580-d972-11ea-867b-6fe21aa467c0.png)

**Comment by Philoul** [comment]
I have quite the same spacing in french language, I'll take a look in code to answer you...

**Comment by MilosKozak** [comment]
fixed
