### ISSUE TITLE
2.7.0-rc2: NSClient - UX issues (Wear loop status, location perm, local BG broadcast from xDrip)

### ISSUE THREAD

**Issue by old-square-eyes** [MilosKozak/AndroidAPS#2886]
Couple of questions about NSClient rc 2, 2.7.0

- xDrip Status (watch). For OpenAPS users - The data is all useful (thanks!), except a big ugly "S:Loop Disabled" right at the front of the status line on Wear and xDrip - where real estate is at a premium. What's the best way for me to request something meaningful here? Not too sure what it shows for AAPS users but I guess OpenAPS last loop time per the Nightscout pill would be most useful, perhaps thresholds for missed loops.
- App is pestering me for location perms... not needed for NSClient users (BT scan etc)
- I have lost the ability to select xDrip local broadcast as BG source. Or it's moved and I can't find it.

![117314828_1330788280598324_5830777520283737652_n](https://user-images.githubusercontent.com/25760491/90063263-34fd9900-dd3d-11ea-8c2d-454c4eafd1fd.jpg)

**Comment by old-square-eyes** [comment]
Any thought on this? Would love to get "S:Loop Disabled" removed from view.

**Comment by old-square-eyes** [comment]
@MilosKozak any chance of looking at this for 3.0?

**Comment by MilosKozak** [comment]
NSClient was never intended to be OpenAPS client but AAPS client
i fixed the permission, that's all I can do
you can try build pumpcontrol, which is more configurable than nsclient mode
