### ISSUE TITLE
2.6.1.4 Unable to set a temp target

### ISSUE THREAD

**Issue by JimZam** [MilosKozak/AndroidAPS#2889]
Good evening. I don't know why everytime I set a temp target it stays just for a few seconds. I can see the temp target in yellow but in a few seconds AAPS overwrites it and applies calculated loop results. It happens even with custom temp target.
I'm not sure how long this has been happening because in the past it worked. I have changed default temp target in settings (all of them were set to 0 by default...) but it makes no difference.
Thank you so much for your help

Edit: It has to do with NS Settings. If I enable "NS only update" I can set temp targets, I had it disabled to avoid the main screen not showing correct BAS as reported in issue 2484.
https://github.com/MilosKozak/AndroidAPS/issues/2484

**Comment by MilosKozak** [comment]
set NS upload only
