### ISSUE TITLE
function LGS (Low Glucose Suspend) does not match general expected meaning

### ISSUE THREAD

**Issue by hartlijn** [MilosKozak/AndroidAPS#2890]
my expectation and I think it's the general interpreation of LGS (Low Glucose Suspend) is that it disables insuline dosing on (expected) low bloodsugars.

The AAPS LGS function however increases basal and gives SMB like in closed loop with the restriction that IOB has to be < 0.
Suggestion to not use LGS but rename it to 'Limited Closed Loop' or 'Closed Loop when IOB<0' or anything else that covers the functionality of the current LGS function.

**Comment by reijoahola-nightscout** [comment]
BTW, when using LGS with SMB, is it Basal IOB or total IOB wjat is limited to < 0 ?

**Comment by reijoahola-nightscout** [comment]
What about the name "IOB limited CL" ?

**Comment by MilosKozak** [comment]
the behavior is so close to LGS that choosing another name would make it even less cleaner.

**Comment by hartlijn** [comment]
I disagree from a safety point of view @MilosKozak . It put me in hypo, while i was testing with LGS my basal for which i suspected to be too strong. LGS really means something else then closed loop with iob < 0.

**Comment by MilosKozak** [comment]
ok, you can describe it by longer sentence but on many places you very short name (shortcut) to fit the screen. and create new shortcut would make it non-undestandable.
how AAPS LGS works is described in wiki
