### ISSUE TITLE
2.7.0 rc2 bolus error given when adding carbs

### ISSUE THREAD

**Issue by ShaggydogUK** [MilosKozak/AndroidAPS#2892]
2.7 RC2 engineering mode
Dana RS v3.0

Low BG at lunch, therefore entered carbs through the carbs button.  Realised I'd given the wrong amount (35g), pressed remove under treatments.  Then tried on several times to add correct number of carbs (30g) through the carbs button, not the calculator, and each time get a bolus delivery error "asked 0.00U Delivered 0.00U Error code 0.  Happens no matter what amount is entered.  Pictures of treatment tab showing deleted treatment and attempt to add carbs (cannot get picture of message the arrives a few seconds after OK is pressed).  Also logs.

![Screenshot_20200816-124353](https://user-images.githubusercontent.com/30231246/90333782-73ef5100-dfc0-11ea-9f40-70008ce0239c.png)
![Screenshot_20200816-125610](https://user-images.githubusercontent.com/30231246/90333787-7b165f00-dfc0-11ea-958f-ba74d0e9592b.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5080604/AndroidAPS.log)
[AndroidAPS._2020-08-16_00-00-03_.13.zip](https://github.com/MilosKozak/AndroidAPS/files/5080605/AndroidAPS._2020-08-16_00-00-03_.13.zip)

**Comment by ShaggydogUK** [comment]
After half an hour I rebooted the phone and tried again, everything worked fine.

**Comment by ShaggydogUK** [comment]
I have not been able to replicate on RC3 yet, but I'll keep trying!

**Comment by MilosKozak** [comment]
next time i need exact time of the error
