### ISSUE TITLE
[2.7.0 rc3/rc5] [bug] wrong information about new version is available

### ISSUE THREAD

**Issue by rICTx-T1D** [MilosKozak/AndroidAPS#2894]
Hi folks, 
today I installed the new version tagged as 2.7.0 RC3 to my Android 10.

Approximately 2-3h later, I get a message banner, that new version is available and some functions will be disabled soon.

A newer version is not available at this moment. 

![Screenshot_20200816-184032_AndroidAPS](https://user-images.githubusercontent.com/8592414/90339368-9731f480-dff0-11ea-94f7-7f0e1516928b.jpg)

**Comment by Philoul** [comment]
I think it's because 2.7.0 rc3 is not a released version.
It is only for testers or developers

**Comment by veterlch** [comment]
I have same bug.
In the previous 2.7.0 rc2 or rc1 didn't have the problem.

**Comment by guydavies** [comment]
Yes, RC1 *did* have the problem.  I reported it at the time :)

**Comment by rICTx-T1D** [comment]
In version 2.7.0 RC2, I doesn't have this message and RC1 I dont have installed.

**Comment by Burgi007** [comment]
In Version 2.7.0 RC2, I have the same Problem.

**Comment by MilosKozak** [comment]
send me log when this happen

**Comment by streethawk22** [comment]
I have the same experience in 2.7 RC3, it was on Yesterday evening. I see today when it happen again.

**Comment by rICTx-T1D** [comment]
Is this Bug in rc5 present too? Can anyone check it, please?

**Comment by ArthurusDent** [comment]
It's in 2.7-RC5.

**Comment by streethawk22** [comment]
> Is this Bug in rc5 present too? Can anyone check it, please?
Yes, It's happens on 2.7 RC5 too.

**Comment by veterlch** [comment]
I also saw the message that new version is available in rc5.
I attach my log file.
The message appeared 07:09PM(the time I changed AAPS version yesterday)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5175953/AndroidAPS.log)
[AndroidAPS._2020-09-04_13-36-38_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/5175954/AndroidAPS._2020-09-04_13-36-38_.2.zip)

**Comment by EvaEssIg** [comment]
hello everyone I am using version AAPS 7.0 rc7 and especially at night around midnight I also get the message that a newer version is available.
As already described by my predecessors ...
I try to add the log file.
Thank you for the great work!
Eva
[Log Export.txt](https://github.com/MilosKozak/AndroidAPS/files/5251592/Log.Export.txt)

**Comment by rICTx-T1D** [comment]
Because a new stable version is published, I'll close this issue. In stable version, i don't get this message at the moment.
