### ISSUE TITLE
DNS can't find "translations.androidaps.org"

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2896]
Link to translations website isn't working anymore:

translations.androidaps.org

It used to be a redirect to the Crowdin project, but isn't anymore.

**Comment by Philoul** [comment]
For app translation, this link works...
https://translations.androidaps.org/project/androidaps

where did you find a wrong link?

**Comment by Mackwe** [comment]
That link doesn't work for me either..?



Den mån 17 aug. 2020 22:50Philoul <notifications@github.com> skrev:

**Comment by Mackwe** [comment]
When something needs to be translated, I get an e-mail with a link to the project (https://crowdin.com/project/androidaps) and the string to translate (https://crowdin.com/translate/androidaps/all/en-sv). They both work. But if I want to use the androidaps.org redirects, it won't redirect me.. 

I just looked a bit further; My DNS can't find translations.androidaps.org at all. 
```
> translations.androidaps.org
Server:  dns.google
Address:  8.8.8.8

*** dns.google can't find translations.androidaps.org: Server failed
```

**Comment by Philoul** [comment]
Hum, after verification you're right, on my phone redirection works, but not on my computer (windows 10)
(tested with Edge and Chrome)...

**Comment by MilosKozak** [comment]
fixed
