### ISSUE TITLE
(2.7.0-rc3) -> Korean DanaRS pairing key keeps changing.

### ISSUE THREAD

**Issue by veterlch** [MilosKozak/AndroidAPS#2898]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

AndroidAPS 2.7.0-rc3
Build: a4b2ce32a-2020.08.17-13:06
Remote: https://github.com/MilosKozak/AndroidAPS.git
Flavor: fullrelease
Nightscout version: 0.10.2-release-20171201

[AndroidAPS_LOG_1597673602758.log.zip](https://github.com/MilosKozak/AndroidAPS/files/5084782/AndroidAPS_LOG_1597673602758.log.zip)

Time the problem occured(8/17 14:18)

I opened same issue with DanaRS V3 before.
My DanaRS V3 has connection problem with AAPS.(2.7.0-rc1,2,3, all of them)
The first connection is successful, but if I do an additional command, the pairing keys changes and the pump doesn't connect automatically.

I created video related with above problem. (https://youtu.be/CRxzoYUFCwU)

**Comment by Mackwe** [comment]
Looking at the video it is hard to tell, but does the RS display time out and go blank? If so, that is probably the issue. Make sure (by clicking the (-) button on the pump every few seconds) that is stays on and keeps showing the keys until you have entered them into AAPS and pressed OK. Alternatively you can sett the screen timeout at a higher value of course.

Please report back if this solved your issue.

**Comment by veterlch** [comment]
Thanks for reply.

In my video, screen looked turned off, but the screen was on until my pump was connected.
Actual problem is that even if the connection is successful at first, the pairing key value changes when I do additional action.

**Comment by Mackwe** [comment]
Very strange. I have tested this with a v3 and it worked really well... Then I am afraid I can't help much more. I don't have very good insights in the v3 drivers.

**Comment by veterlch** [comment]
I bought this pump 3 wks ago in Korea.
Maybe... V3(upgraded from V2) and brand new danaRS V3 are different software?

I don't know. but I hope AAPS will work with my pump someday..

**Comment by MilosKozak** [comment]
i see the pump is detected as DanaRS Korean.
I never had this pump in my hands and probably there is  something different
contact sooil for international version

**Comment by Mackwe** [comment]
The firmware should be no different between upgraded or new, but as Milos suggests, since it is a Korean pump there may be some other differences. For Dana R I know there is. Maybe that goes for RS as well..

**Comment by veterlch** [comment]
Let me share you today's communication with sooil.

- There is no way to obtain international version in Korea. (Because pump is invasive medical device, Korean should use korean device)
- It is impossible to change version.(Korea version -> International version)
- Korea version and International version are same except time table(?) and language. (I don't know what is time table)
- It seems that there is conflict with Korean alphabet and AAPS.   (or something)

**Comment by MilosKozak** [comment]
@veterlch you may try current dev. there is an update for RS

**Comment by veterlch** [comment]
@MilosKozak  Really appreciate your effort. Pairing key changing problem still presents.
However connection between pump and AAPS becomes better. In the previous version, I have to clear pairing by long press on BT icon on Dana page whenever I want to reconnect. In recent dev version , I don't have to clear pairing when I reconnect the pump. although pairing key keeps changing.

**Comment by MilosKozak** [comment]
try it again and provide new log files.

**Comment by veterlch** [comment]
AndroidAPS 2.6.7-dev
Build: 35ca0d22b-2020.08.28-01:23
Remote: https://github.com/veterlch/AndroidAPS
Flavor: fullrelease
Nightscout 버전: 0.10.2-release-20171201
[AndroidAPS_LOG_1598606932872.log.zip](https://github.com/MilosKozak/AndroidAPS/files/5141293/AndroidAPS_LOG_1598606932872.log.zip)

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5141291/AndroidAPS.log)


18:24 pairing success
18:25 try temp basal -> reconnect the pump message appeared(AAPS)
18:26 try temp basal -> reconnect the pump message appeared(AAPS) -> I pushed ok button in pump -> wrong password message appeared(AAPS)

thanks

**Comment by veterlch** [comment]
I'll try build again and recomment later. thanks.

**Comment by veterlch** [comment]
@MilosKozak It works well. Thank you so much 👍 There was a mistake in building recent dev apk. It works very well in my dana rs korean pump.
