### ISSUE TITLE
Not connecting to DanaRS v3

### ISSUE THREAD

**Issue by beesonelastic** [MilosKozak/AndroidAPS#2899]
- Issue occurred with my new pump today. Tried to pair with the app (2.7.0 rc3) and despite connecting via BT the app couldn't connect with the pump to move onto the next section of the wizard. Any help would be appreciated!

**Comment by Mackwe** [comment]
Could this be the issue? https://github.com/MilosKozak/AndroidAPS/issues/2898

**Comment by MilosKozak** [comment]
provide more detailed info, screenshots etc

**Comment by beesonelastic** [comment]
Have now resolved by using above workaround. Thank you!
