### ISSUE TITLE
Cap value of bg in bolus wizard independent of units

### ISSUE THREAD

**Issue by jumalakarhu** [MilosKozak/AndroidAPS#2900]
Max manually entered blood glucose in bolus wizard is capped at 500 mg/dl or 500 mmol/L. A better value would be 500 mg/dl or 30 mmol/L. 
My daughter entered 88 mmol/L instead of 8.8 mmol/L. Luckily only bolus for 13g carbs was sent to pump.

Using APS-eros 0.3, but I do not think this is omnipod driver issue.

**Comment by MilosKozak** [comment]
improved , thanks
https://github.com/MilosKozak/AndroidAPS/commit/9ca20f425fc4d938e104520c0b84bf43b8dd890e
