### ISSUE TITLE
Optionally disable number entry in bolus wizard

### ISSUE THREAD

**Issue by jumalakarhu** [MilosKozak/AndroidAPS#2901]
Feature request.

For safety of kids and parents well-being it would be nice the have the option to disable number entry in bolus wizard and force use of -/+ to decrease or increase carbs, manual bg etc. There is a big difference between bg 3.9 mmol/L and 39 mmol/L or carbs entered in bg field.

**Comment by MilosKozak** [comment]
this is too specific wish

**Comment by jumalakarhu** [comment]
Forcing -/+ would mimic the original use of most pumps which (all?) do not have a number pad/dial. I guess it is implemented as a security measure and not only to save space.
I hope you can keep this idea floating.
