### ISSUE TITLE
[2.7-RC3] Performance degradation (lag) and crash?

### ISSUE THREAD

**Issue by ArthurusDent** [MilosKozak/AndroidAPS#2906]
I'm not even sure whether this is a bug or normal behaviour because AndroidAPS compresses its logs in the background. Just to be sure I'm posting this issue.

Starting with RC3 (a4b2ce32a) I have enabled engineering mode.

The first time I noticed performance degradation was probably with 2.7-RC2, although I'm not sure. I just restarted my phone and it was gone. 

But what I have now witnessed is that the app sometimes gets laggy and shortly after restarts. I noticed the lag when I was using the buttons on the main screen. I don't think I have ever seen arbitrary restarts by AndroidAPS before. That's why I thought this might be a crash after all.

I did a grep over all my existing log files and searched for what I think are restarts:
[grep.log](https://github.com/MilosKozak/AndroidAPS/files/5103314/grep.log)

What's immediately obvious is that the restarts are only in log files that end on *.0.zip.

I do not restart my phone this often. I have installed RC3 on 16.08.20 at 16:45:37 but my phone has an uptime of seven days by now (today is the 20.08.20).

Those are the corresponding log files for RC3 only:
[AndroidAPS._2020-08-16_16-45-14_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5103336/AndroidAPS._2020-08-16_16-45-14_.0.zip) (installation)
[AndroidAPS._2020-08-17_15-00-37_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5103345/AndroidAPS._2020-08-17_15-00-37_.0.zip) (15:00:37)
[AndroidAPS._2020-08-19_03-29-54_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5103423/AndroidAPS._2020-08-19_03-29-54_.0.zip) (03:31:43)
[AndroidAPS._2020-08-19_15-29-48_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5103439/AndroidAPS._2020-08-19_15-29-48_.0.zip) (15:29:49)
[AndroidAPS._2020-08-20_06-11-42_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5103453/AndroidAPS._2020-08-20_06-11-42_.0.zip) (06:11:59)

**Comment by reijoahola-nightscout** [comment]
After the installation of RC3 I had two AAPS restarts within 3 .. 4 hours. Then I restarted the whole phone and no AAPS restarts after that.

**Comment by MilosKozak** [comment]
i see app restart in logs but the reason is not there
