### ISSUE TITLE
2.7.0-rc1/2/3 Basal Statistics in Insight and AAPS (SMB mode)

### ISSUE THREAD

**Issue by reijoahola-nightscout** [MilosKozak/AndroidAPS#2907]
Just a question is it a known feature that the Statistics for total Basal in AAPS (Top Right menu/Statistics) and in Insighjt pump (TDD button)  do not have exactly the same value for daily basal ? When using 2.7.0-rc3 I can see a difference (Insight - AAPS) between 0,1 ... 0,3 U.

I just thought that can TBR bug fix (#2484) for Insight cause this small difference or has this existed even before 2.7.0-rc1.

**Comment by MilosKozak** [comment]
one value is from pump second calculated by apps. small difference is possible
