### ISSUE TITLE
AndroidAPS RC 4 stops to geht CGMS Data from patched Dexcom App in the mornings 

### ISSUE THREAD

**Issue by peterleimbach** [MilosKozak/AndroidAPS#2911]
AndroidAPS 2.7.0 RC 4 with patched Dexcom App SW11587; 1.5.1.5)

Today with RC 4 and yesterday with RC 3 CGMS Data arrival in AndroidAPS from patched Dexcom App stoppen but Dexcom App got data! Therefore AndroidAPS falls back to default profile.

When restarting AndroidAPS the CGMS data arrived again.

**Comment by MilosKozak** [comment]
> [Log Export #2911.txt](https://github.com/MilosKozak/AndroidAPS/files/5111957/Log.Export.2911.txt)

```
04:11:02.031 [AutomationPluginHandler] D/CONSTRAINTS: [Constraint.getMostLimitedReasons():118]: Limiting original value: true to false. Reason: Objectives: Objective 11 nicht begonnen
06:32:15.426 [main] D/CORE: [MainApp.onCreate():68]: onCreate
```
from 4:11 to 6:32 app was not running without any sighg of crash. i'd say killed by android

**Comment by MilosKozak** [comment]
btw why did you turn off "Log App start". it's there for this kind of issues

**Comment by peterleimbach** [comment]
I turned „Log App start“ of in my early days of looping when the start messages cluttered the diagram. No special reason for this in this context.
I turned it on after the error occurs because I thought ist would be helpful Information. And indeed I can see after the fallback to standard profile happened tonight AndroidAPS logged a restart message around two hours later at 7:31.
For the next night I will double check that AndroidAPS and Dexcom apps are runing and send you the log files again if the error happens.

**Comment by peterleimbach** [comment]
![A2612D2A-04FD-42AC-834D-1F8D7B1827A9](https://user-images.githubusercontent.com/4148261/91129256-fb684e80-e6a9-11ea-9a6c-3416915668db.png)

**Comment by peterleimbach** [comment]
I double checked the energy saving options. No restrictions for AndroidAPS and Dexcom as it should be and worked in the past on this phone very stable.

**Comment by peterleimbach** [comment]
Tonight the same problem as before. I double checked that AndroidAPS and Dexcom have been running before going to sleep. In the night the CGMS data stopped arriving in AndroidAPS but the AndroidAPS App has been active! AndroidAPS falls back into default basal profile. After restarting AndroidAPS data arrived again and works as normal.
What should I do to get out of this situation?

**Comment by peterleimbach** [comment]
[Log Export 27. August.zip](https://github.com/MilosKozak/AndroidAPS/files/5134330/Log.Export.27.August.zip)

**Comment by MilosKozak** [comment]
app stopped at the same time like in log before (4:14)
something in your phone must trigger it

**Comment by peterleimbach** [comment]
I don't understand why it is solved now but yesterday it happened that there was no data from patched Dexcom was delivered to AndroidAPS even after phone restart. I then checked again all possible security restrictions for AndroidAPS which have all been enabled. In the end I disabled the special setting "access Dexcom app" and enabled it again and after that it worked again and it did work last night without interruption.

**Comment by peterleimbach** [comment]
![Screenshot_2020-08-30-11-34-00-096_com google android packageinstaller](https://user-images.githubusercontent.com/4148261/91655935-dc582b00-eab4-11ea-996f-b7b9011630ab.jpg)

**Comment by peterleimbach** [comment]
Next night where system was working as expected. => I suggest to close this issue.

**Comment by rICTx-T1D** [comment]
@peterleimbach: Please click on close issue button at end of this page. Only issue reporter and admins can close this issue.

**Comment by peterleimbach** [comment]
issue stops occuring. I close the issue.
