### ISSUE TITLE
[AndroidAPS_RC4] Bug #2715 is back with RC4

### ISSUE THREAD

**Issue by Alamo04** [MilosKozak/AndroidAPS#2915]
. #2715

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by andyrozman** [comment]
Code looks good to me... The change I did for this problem is still there... The guys did do some refactoring on rileylink code though. And some testers from gitter/RileyLinkAAPS (and me) have run the build so it should work. But fix I did is definetly there so it should work.

**Comment by bartsopers** [comment]
@Alamo04 @rICTx-T1D van you please provide logs? Make sure that you have PUMP, PUMPCOMM and PUMPBTCOMM logs enabled. You can find these settings by clicking the menu bar in the left top of the app, then click on Maintenance and then click on Log Settings

**Comment by MilosKozak** [comment]
i tested both rc4 and latest dev and the bug is not there. it must be your phone.

**Comment by Alamo04** [comment]
@bartsopers 
Used RC4 and with first start RL didn't connect until I go tonMDT Tab, after 48 minutes. 
Tested with new start of Phone and/or closing AAPS and this Bug didn't comes up again
So perhaps it was a fault from my new phone.

Now I'm using latest dev, with a new Android 10 phone and have a lot Bluetooth problems. 
Xdrip lost connection to G6 Transmitter and didn't reconnect, many pump connection lost and AAPS automatically restarts 3-5 times a day. :(
But also, this issue didn't come up here.

@andyrozman 
So I have no logs for you Andy, but I think it was my mistake, or from this $%&# new phone.

Closing this Issue.

**Comment by larsvandoremalen** [comment]
tested today using a 554 europe Medtronic, Moto G4 smartphone (android 7) and a Rileylink (433 mhz version so connection to pump can be choppy). Could not reproduce a delay in connection to RL on AAPS startup on either RC4 or Omnipod_Dev branch. Did not switch tabs at all and visually confirmed green light on RL before switching to check.
