### ISSUE TITLE
[2.7.0-rc4] DanaRS Pump Settings

### ISSUE THREAD

**Issue by NickSills1** [MilosKozak/AndroidAPS#2920]
DanaRS fw3

Pump settings not loaded correctly and not saved.

DANARS > USER OPTIONS

These settings are not the same as in the pump:

![Screenshot_20200822-193408_AndroidAPS](https://user-images.githubusercontent.com/15063589/90963402-381c2600-e4af-11ea-9b86-573a00070f75.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/7e2e5be6bbba712488908b417c2bbaa9fb696788
thanks!
