### ISSUE TITLE
[2.7.0-rc4] LOOP > OpenAPS AMA 'After  processed constraints' inconsistency

### ISSUE THREAD

**Issue by NickSills1** [MilosKozak/AndroidAPS#2921]
2020-08-23  - 15:10:17

I've seen this on multiple occasions. The 'After processed constraints' Rate is limited to 200.00% (1.50 U/h) but this does not affect the TBR.  I'm not sure how the 200% constraint is derived and do not believe it to be correct or relevant.

[AndroidAPS._2020-08-23_00-00-19_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/5114799/AndroidAPS._2020-08-23_00-00-19_.3.zip)

![Screenshot_20200823-151504_AndroidAPS](https://user-images.githubusercontent.com/15063589/90987144-9e24ae00-e580-11ea-8f0e-fded44a0a48d.jpg)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/d7817792cab8a86bf12bceef8561a7bf5cce67ea
