### ISSUE TITLE
[2.7.0-rc4] Bugs in new UI

### ISSUE THREAD

**Issue by muschelman** [MilosKozak/AndroidAPS#2923]
![grafik](https://user-images.githubusercontent.com/47613434/91049810-0bd2e780-e61e-11ea-81d1-23407c04ee44.png)
1) If the CGM does not provide any BG values (in my case an Eversense in the charging cradle), the information text is so wide that the loop symbol is no longer completely displayed. I think that an abbreviation as shown here for the carbs ("N / A") would be better.

2) Due to an allergy, I can wear the catheter for a maximum of 2 days. To make this visible in AAPS, I have set the variable "CAGE_WARN" to 36 and "CAGE_URGENT" to 40 in my Nightscout instance. Thus in version 2.6 the age information for the catheter was displayed in yellow after 36 hours and in red after 40 hours. In the 2.7 RC4 the variables from Nightscout no longer seem to have an effect.

**Comment by muschelman** [comment]
Here is a Screenshot of a catheter age longer than 36h with my Settings:
![grafik](https://user-images.githubusercontent.com/47613434/91051159-01b1e880-e620-11ea-8bba-3d809deb6fc2.png)
Under "Actions" its the same.

**Comment by reijoahola-nightscout** [comment]
I remember that Canula warning and critical levels comes now from Config Builder (Overview / Status lights).

**Comment by MilosKozak** [comment]
1) i reported "night verfuegbar" as too long translation
2) the settings is now in preferences. but you can overtake value from NS on the same place
