### ISSUE TITLE
[2.7..0-RC4] Problem reservoir change 

### ISSUE THREAD

**Issue by RainerTischnet** [MilosKozak/AndroidAPS#2927]
I changed the reservoir. have to enter it in rc4. and only reservoir selected. now the catheter has also been set to zero.
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
depending on the pump it can be loaded from history too

**Comment by RainerTischnet** [comment]
it is an old dana rs firmware, the data have also been changed on the pump. when I switch to the stable version the catheter date is also reset. i find out through that it is an isuse. If only reservoir change is selected, the catheter must not also be reset. this behavior was not observed with the stable version.

**Comment by RainerTischnet** [comment]
unusual effect aaps often calls the history pump in the rc4. now I briefly saw the correct catheter age, was overwritten shortly afterwards
