### ISSUE TITLE
[2.7.0-RC4] Objective 4 manual adjustments are not counted so you can't finish objective 4 or further

### ISSUE THREAD

**Issue by Bertrick** [MilosKozak/AndroidAPS#2928]
When reaching Objective 4 in Open Loop mode you need to run Open Loop for 7 days and do 20 manual adjustments just like AndroidAPS suggested. 

When doing a manual adjustment the counter doesn't add up.

It stays on 0/20.

This way you can't finish Objective 4 or any further.

**Comment by MilosKozak** [comment]
did you press the button with recommendation?

**Comment by Bertrick** [comment]
Ah I thought you had to manually do the suggestion in your actions menu.
Which would have preferred by me. Other wise how do people know how to manualy set temps?

But I saw it as a status box with a message. But you can click on everything. 

Thanks for pointing out and I will close the issue.
