### ISSUE TITLE
[2.7.0-RC4] String for "missing_carbs" seem to be missing in many translations.xml

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2930]
If I go to WizardDialog.kt, there is a string called "missing_carbs" to tell the user if carbs are missing. This string is only present in 8 language files, where Swedish isn't one of them, so I cannot translate it.

Please verify that all language files include "missing_carbs":

`<string name="missing_carbs">Missing %1$d g</string>`

**Comment by MilosKozak** [comment]
i see it translated. the rest is processed in crowdin

**Comment by Mackwe** [comment]
Well, it still isn't available in most languages. \values-sv-rSE for one.

I can however find it in Crowdin, but still not in the xml strings files in
the git repo.

**Comment by MilosKozak** [comment]
it appears in xml once is translated in crowdin

**Comment by Mackwe** [comment]
It is translated in Crowdin. And has been for about 2 years, I believe.

Den tors 27 aug. 2020 11:07Milos Kozak <notifications@github.com> skrev:

**Comment by MilosKozak** [comment]
i see it in dev branch for SE language

**Comment by Mackwe** [comment]
Can't say what happened, but it wasn't there in the RC4 source. It's back in RC5..
