### ISSUE TITLE
[Feature request] COB gets updated without sensor data when manual BG is input.

### ISSUE THREAD

**Issue by scarral** [MilosKozak/AndroidAPS#2935]
While sensor warm up or when sensor data is not available, it would be useful to have COB information so that the bolus calculator can calculate the correct dose. We  measure often when for whatever reason sensor information is not availabe. Would it not be possible to update COB information with manually entered BG values?

Thanks! 

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
COB is calculated from CGM data, single (or more) BG value is not enough for calculation
