### ISSUE TITLE
Use target range from profiles instead of preference settings

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#294]
- [ ] Remove target, min, max from settings
- [ ] Use active profiles instead
- [ ] Migration path for existing users: we don't have release notes as such and many users(?) run from the dev branch. So how to inform them, with a popup if the prefs exist and then removing them?

WIP: https://github.com/jotomo/AndroidAPS/commits/move-to-range-in-profile

**Comment by AdrianLxM** [comment]
A Popup that checks for the settings when the main activity is started sounds good for migration purposes.

**Comment by MilosKozak** [comment]
Popup sounds good

**Comment by jotomo** [comment]
Since AAPS doesn't have a changelog yet, it might be an idea to integrate that into the application and show it on application startup, e.g. if the version differs from the we saved in the DB. A general way to inform the user about changes ...

**Comment by MilosKozak** [comment]
i think we can check for existing SharedPrefences key and remove it after user confirm dialog

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/340/files
