### ISSUE TITLE
2.7 RC5: Button scroll causes system error in DanaRv2

### ISSUE THREAD

**Issue by an-di-looper** [MilosKozak/AndroidAPS#2946]
Under user options in Dana Tab, you can select Button scrool even when using a DanaR. This causes the pump to an urgent system error warning. I had to remove battery to go on. This is because DanaR does not support button scrolling.

Pump hardware: DanaRv2, Model 03, Protocol 02, Code B1

![Screenshot_20200902-113054_AndroidAPS](https://user-images.githubusercontent.com/68446861/91965295-93041780-ed10-11ea-9bac-375e0d23aca1.jpg)

**Comment by MilosKozak** [comment]
i cannot replicate this issue on pump
Model 03
Protocol 02
Code B1

**Comment by an-di-looper** [comment]
Hm. Button scroll was off, activated, save options to pump, then there was an ongoing beep in pump and a rectangular with "System error!". I'm afraid of trying this again 🙈
