### ISSUE TITLE
(2.7.0-rc5) -> Korean DanaRS pairing key changes sometimes.

### ISSUE THREAD

**Issue by veterlch** [MilosKozak/AndroidAPS#2949]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

AndroidAPS 2.7.0-rc5
Build: 984134ce5-2020.09.03-19:30
Remote: https://github.com/MilosKozak/AndroidAPS.git
Flavor: fullrelease
Nightscout ver.: 0.10.2-release-20171201
[AndroidAPS_LOG_1599232918791.log.zip](https://github.com/MilosKozak/AndroidAPS/files/5175932/AndroidAPS_LOG_1599232918791.log.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5175934/AndroidAPS.log)

In dev version. It works very well with my dana rs korean pump.
I changed version from dev to rc5 yesterday evening.
Pairing key have changed 3 times today.( about 8 am, 9 am, 11:30 pm)

**Comment by steven850** [comment]
I have been having the same issue on RC3 and RC5 with a german danaRS V3. Key changes at random times. sometimes it lasts 1hr sometimes 30hrs. But constantly need to enter new key.

**Comment by veterlch** [comment]
No more change in rc6
