### ISSUE TITLE
2.7.0-rc-1-5  DanaRS randomly loses connection

### ISSUE THREAD

**Issue by JelmerFokkema** [MilosKozak/AndroidAPS#2951]
Been monitoring this problem throughout the RC,s. My RV2 DanaRS randomly loses connection. And I will notice this because basal is not adjusted alltough SMB tab says it should. In the pump tab it will say connection is gone period x. The DanaRS is off course renowned for it's rock solid connection and on earlier releases the problem doesn't occur. 

Did a quick search couldn't find anything similar, In case this has been reported my sincere apologies. 

![Screenshot_20200905-071217__01](https://user-images.githubusercontent.com/51903932/92299012-0d21df80-ef4f-11ea-80b8-d7dddf5fd32a.jpg)

[AndroidAPS._2020-09-04_00-00-00_.5.zip](https://github.com/MilosKozak/AndroidAPS/files/5177615/AndroidAPS._2020-09-04_00-00-00_.5.zip)
[AndroidAPS._2020-09-05_00-00-00_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5177616/AndroidAPS._2020-09-05_00-00-00_.0.zip)
[AndroidAPS._2020-09-05_00-00-00_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/5177617/AndroidAPS._2020-09-05_00-00-00_.1.zip)

**Comment by JelmerFokkema** [comment]
Well de/re installing Aaps does make a difference. Last night no connections lost/halted.

**Comment by xJoe** [comment]
Stable connection with Pixel 2 and v2 RS on my side with all RC.

**Comment by JelmerFokkema** [comment]
Here the second stable 24h after complete reinstall so consider it closed and phone related.
