### ISSUE TITLE
[2.7.0-rc5] Automations don't work anymore after update

### ISSUE THREAD

**Issue by RobHoff** [MilosKozak/AndroidAPS#2958]
I updated from 2.6.1.4 and suddenly my automations don't work anymore. It seems that there's now an objective for automation, which I can't complete, because I haven't completed on of the objectives which has been added a few versions ago. Because I have completed the later objectives a long time ago I thought I didn't have to do these ones. 
One of them says I should separate the pump for 1 hour to simulate showering. I find this objective to be highly careless and dangerous, so I won't complete it. I try to shower in under 15 minutes to PREVENT big BG-fluctuations! So is there any way for me to make my automations work again? Also, please call people's attention to the possibly not-working automation when updating!

**Comment by MilosKozak** [comment]
you should disconnect pump and in next step reconnect. i don't think it's dangerous
