### ISSUE TITLE
2.7.0 RC6 Tag error

### ISSUE THREAD

**Issue by veterlch** [MilosKozak/AndroidAPS#2964]
![2 7 rc6 tag2](https://user-images.githubusercontent.com/69113205/92995020-85356a00-f53a-11ea-965c-abd40fe92d01.PNG)
![2 7 rc6 tag](https://user-images.githubusercontent.com/69113205/92995021-86669700-f53a-11ea-99b0-f96b5ac0efd1.PNG)

Wrong version was made when building rc6 apk

**Comment by MilosKozak** [comment]
there was no release record created for rc6. simply use rc6 branch
