### ISSUE TITLE
Confusing graph for fast acting insulin prolonged  

### ISSUE THREAD

**Issue by Heiner1** [MilosKozak/AndroidAPS#297]
I think there must be something wrong if DIA is set below 6 hours. Change it and you see the effect at the graphical display of insulin activity. 
![error-prolonged-insulin-graph-01](https://user-images.githubusercontent.com/20724321/28371983-cce3c388-6c9e-11e7-8d38-71e67188d51d.png)
![error-prolonged-insulin-graph-02](https://user-images.githubusercontent.com/20724321/28371984-cd02d462-6c9e-11e7-813f-09eecf7ff0bd.png)

**Comment by AdrianLxM** [comment]
I can't see anything wrong when I see it on the large picture:
* The pink curve (IOB) decreases from 1 to 0 in 300 or 360 minutes accordingly
* The peak of the blue line (Insulin-Activity, translates to BGI) is at slightly below 0.01 for a 5-hour-DIA and at slightly above 0.008 for a 6-hour-DIA. It seems plausible to me that the peak is slightly lower when the insulin action is spread over one more hour.

**Comment by Heiner1** [comment]
You are right, but why is the left y-axis scale max. doubled? For me it makes no sense.

**Comment by AdrianLxM** [comment]
From the gitter chat it seemed that it was more the scale and which is which that was confusing.
I have added colours to the labels to relate them to the corresponding line more easily:

![screenshot_20170719-233539](https://user-images.githubusercontent.com/9692866/28390831-f0be1c1c-6cdb-11e7-9ca3-f0c79d221001.png)

**Comment by AdrianLxM** [comment]
PR: https://github.com/MilosKozak/AndroidAPS/pull/301
