### ISSUE TITLE
RC 2.7.0 rc7 manual bolus(s) given from medtronic 722 did not update on AAPS graph or treatment tab.

### ISSUE THREAD

**Issue by ezondii** [MilosKozak/AndroidAPS#2970]
Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
I very rarely bolus directly on the medtronic pump buttons, but any time i have int he past the boluses given manually have always updated to AAPS. In 2.7.0 rc7 it did not. 
I manually bolused 0.6 units due to persistant high on the pump interface. This was not uploaded to AAPS graph or treatment tab. 40 minutes later I checked the AAPS screen noticed that there was no record of the manual 0.6 units being given so i gave a further 0.6 manually on the pump button interface and watched for it to be given by pump (it was) and watched for the bolus to be updated on RC 2.7.0 rc7(it was not). 

I was not home so i unistalled RC 2.7.0 rc7 (therefore i have no logs to share) and reinstalled RC 2.7.0 rc6 which updated from the pump and recognized to two seperate 0.6 unit boluses on the graph and treatment tabs as expected.

- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner). RC 2.7.0 rc7

- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
Sorry logs overwritten by install of RC 2.7.0-rc6 so unsure if the boluses were ever taken into account for IOB on 2.7.0 rc7 but they definately did not show on the main graph or treatments tab. the two boluses were at least 30 mintues apart and i watied another 10 before unintalling 2.7.0 rc7 in case it was just slow to update for some reason. 
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
without logfiles it's useless
what is not clear on this https://androidaps.readthedocs.io/en/latest/EN/Configuration/MedtronicPump.html#manual-use-of-pump ?

**Comment by ezondii** [comment]
Tried to replicate the issue by reinstalling 2.7.0 RC 7. Manual boluses issued directly on the medtronic pump all were reocorded on AAPS. 
Issue was unrepeatable. 
Any point in upploading log files? Should i close this issue?
