### ISSUE TITLE
[2.7.0-rc7] DanaRS v3 disconnections overnight

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2971]
Running the last two nights with 2.7.0-rc5 (14 to 15/09/2020) then 2.7.0-rc7 (15 to 16/09/2020), which no longer crashes, I have found in the morning that the pump is struggling to reconnect when I woke up around 6:45am.  This would suggest that no actions to reduce my basal would have been activated had they been required (I'm still on Objective 6, so no extra basal while IOB>0).

Taking them in turn, looking through the logs as best I can, in the logs from 15/09/2020, at 04:16:24, I see the last "successful" communication with the pump.  I then see nothing with "D/PUMP" until 04:36 when I start seeing lots of "Connection needed" and ultimately "no connection possible".  It doesn't recover until I reboot the phone (not found exactly in this log).

In the logs from 16/09/2020 you see similar failures starting at 04:02:27, when I see the first "no connection possible" then up to 07:01 at which time I restart the phone and the logs start up again at 07:04 and the data connection to the Dana RS reestablishes.

The logs are attached.

[AndroidAPS._2020-09-16_07-01-46_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/5231869/AndroidAPS._2020-09-16_07-01-46_.0.zip)
[AndroidAPS._2020-09-16_00-00-01_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/5231870/AndroidAPS._2020-09-16_00-00-01_.1.zip)
[AndroidAPS._2020-09-15_00-00-04_.3.zip](https://github.com/MilosKozak/AndroidAPS/files/5231877/AndroidAPS._2020-09-15_00-00-04_.3.zip)

**Comment by guydavies** [comment]
Could you please explain what you saw that enabled you to come to that conclusion?  I’m not saying you’re wrong.  How could I?  But having gone through similar issues with Xdrip+, which were solved completely when I switched to the patched Dexcom app, I would like to understand rather than just getting the case closed with an answer that tells me nothing to work with.

**Comment by MilosKozak** [comment]
it seems to be BT issue

**Comment by MilosKozak** [comment]
aaps ask android to connect to BT device .... if android fail to connect there is nothing we can do

**Comment by guydavies** [comment]
Thanks Milos,

So, arguably, it’s either a problem with the phone/Android *or* the pump ;-) since it’s a two sided communication process.  I’ll see if there’s any further information I can extract regarding the BT and see what happens.  As I say, having had issues with Dexcom G5 and Xdrip, which were not dissimilar to these issues and which have completely disappeared when switching to Dexcom patched app, it’s not always as simple as “it must be the phone”, which was what I was also being told wrt Xdrip ;-)

Thanks for all the efforts, I’m delighted with the behaviour other than this disconnect overnight.  If I can just pin it down, I’ll be ecstatic.

Rgds,

Guy

**Comment by guydavies** [comment]
Hi Milos, I know you closed this as "the phone's problem".  I changed my logging overnight and restarted a couple of times early evening and the phone worked right through.  It stopped around 08:45 this morning and I noticed about 50 minutes later as I was going low and the pump wasn't being stopped by AAPS.  I only had to click on the BT symbol to kick it back into sync (at around 09:35).  I minimised the logs to show only Pump and Core events.  Given that a simple tap of the BT symbol restarted the process, do you consider that a sufficiently significant change to review.  I've attached the logs from overnight.  The last successful connection is at 08:45.  I restarted by just tapping the BT symbol in the DanaRS tab at 09:35.
[AndroidAPS_LOG_1600328414712.log.zip](https://github.com/MilosKozak/AndroidAPS/files/5237209/AndroidAPS_LOG_1600328414712.log.zip)

**Comment by guydavies** [comment]
I should say that I've also (just) added the BT watchdog and an alarm on my phone to try to recover from the BT failure to the pump.  Let's see if that helps any.

**Comment by Tornado-Tim** [comment]
Hey @guydavies, yea looks like a issue with the BT stack on your phone.
Often the BT watchdog can recover these faults by turning the BT off and on again.

But as far as AAPS talking with a BT device, everything depends on a solid BT stack and unfortunately not all phones are the same and they have quirks in each implementation.

Sticking to phones that have a close to stock if not stock Android implementation will often help avoid issues like the above.

Hope this helps :)

**Comment by guydavies** [comment]
Thanks Tim, I really appreciate the extra detail in the explanation.

I have now set the watchdog and also the alarm if the pump loses connection (after 30 minutes) but that alarm seems to be on a hair trigger because it’s triggered at least twice today and when I check, it’s connected within the last minute.  I may switch off the alarm because it doesn’t seem useful.

When I come to buying a new phone, I’ll definitely go for as close to stock as I can.  The Pixel 4a looks interesting (not a stupid price and a reasonable spec).

Rgds,

Guy
