### ISSUE TITLE
[2.7-RC7] [graphical/UI] Scaling of additional graph may need improvement

### ISSUE THREAD

**Issue by goomStar** [MilosKozak/AndroidAPS#2980]
The scaling of fresh additional graphs seem to depend on the first data source selected. For full graph functionality a pre-check before drawing would be required, to find the optimal scaling.

Example/Reproduction:
Create an empty graph and use COB and DEV as data. As COB is the first source, the graph will use a fixed scaling with positive numbers only, even though DEV would need negative values.
It also affects the deviation-slope in negative area. They always work stand-alone, but in combination with COB as first source, the graph is not optimized.
When no COBs are found to be displayed for the chosen timeframe, the graph stays blank completely (like in the picture).
![Screenshot_20200918-093107_AndroidAPS](https://user-images.githubusercontent.com/38337079/94168853-5c906700-fe8e-11ea-8ba4-a95893c1fbca.png)

**Comment by MilosKozak** [comment]
ability of graph library we use is very limited for multiple axis support. i did max possible
we have now multiple graphs support so use it
