### ISSUE TITLE
2-7 Engeneering mode activated/diplayed

### ISSUE THREAD

**Issue by CaroGo** [MilosKozak/AndroidAPS#2983]
It seems to be, that engeneering mode is automatically displayed /activated? without activating it manually when installing new version. 
I have no logs but observed this during the Looper meet up (users did not update from rc, and did not activate it)

**Comment by goomStar** [comment]
Confirmed and hopefully addressed soon here: https://github.com/nightscout/AndroidAPS/issues/6

**Comment by dlvoy** [comment]
Fix merged to dev on main repo - please check there and close issues if confirmed ;)
