### ISSUE TITLE
NS Client loosing connection

### ISSUE THREAD

**Issue by Duester64** [MilosKozak/AndroidAPS#2984]
NS Client saying destroy and afterwards not allowed until the App is stopped and restart. It happens every few minutes. Updated to 2.7 shortly. With 2.614 no issues. Checked already the server, seems its normal. Tested on 13, 1405 and 1406, all the same. Got some socket errors before. Any idea ?

**Comment by MilosKozak** [comment]
check connectivity settings of nsclient. behavior has changed in 2.7
