### ISSUE TITLE
[2.7] Dana v3 unpairs itself

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#2987]
Setup: 
- Samsung S7 (Android 8.0)
- Dexcom G6
- Dexcom patched
- AAPS 2.7
- xDrip 

Have paired an RS v3 pump with AAPS 2.7. It has worked fine for some time. Then after about a week, it asked me to input the pairing keys again. So I did. And it worked fine. For a week..  Same issue this morning. Deleted it from the BT devices list, got into AAPS and re-paired. Worked fine again. 

I have now enabled some logging on that phone to hopefully see what is going on. 

Just wanted to add an issue in case there are others with the same symptoms .If I don't get the same problem in a week or two, I will close this issue.

**Comment by guydavies** [comment]
Hi Marcus,

Yes, there are lots of people with similar experiences with the DanaRSv3.  I am one of them.  Others, myself included are also having issues with AAPS losing connection to the pump overnight but simply not reconnecting nor (in many cases) asking to repair.

Milos put a poll up on FB on 3/10 I think to try to get some data to pin down the issues.  

Rgds,

Guy

**Comment by Mackwe** [comment]
Thanks for input. WIll have a close eye on that too, then.

**Comment by Mackwe** [comment]
Issue reoccured just now. App says "Please pair with pump" at the top of Overview screen.

- Restarted app
- Restarted phone
- Tab DanaRS > Bluetooth icon, trying to connect
- Put pump in flight mode and back 

I didn't get it up and running until I went to Config Builder > Dana RS > Gear icon > Choose pump > Chose my pump's serial number. This time I didn't have to re-enter the pairing keys at least.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5356300/AndroidAPS.log)

**Comment by MilosKozak** [comment]
v3 uses following way to detect valid encryption:
send initial packect and initiate encryption
send a test packet and wait for response
if no response is received encryption setting in aaps is marked as invalid and removed. next time new pairing should be initiated

there is no other way to test if encryption keys are valid
there is one possible issue if connection is broken during testing encryption status. it may be erroneously marked as invalid

i also found a state where initial handshake always fail but i was unable to reproduce and fix

**Comment by Mackwe** [comment]
Hi Milos,

Could you please look at the logs I provided? I don't know the protocol or background processes, but to me it looks odd.

* At the top (App start), it generally talks about a Dana v2 connection, then a Dana R reset. Sometimes getting RS data.
* [Thread-8] Seems to connect at first and while waiting for disconnect, [main] is still communicating with it.

And this:
18:09:31.688 [main] D/PUMP: [DanaRSPlugin$mConnection$1.onServiceConnected():123]: Service is connected
18:09:32.502 [Thread-8] D/PUMPQUEUE: [QueueThread.run():119]: connect
18:09:32.503 [Thread-8] D/PUMP: [DanaRSPlugin.connect():137]: RS connect from: Connection needed
18:09:32.503 [Thread-8] D/PUMPBTCOMM: [BLEComm.connect():88]: Initializing BLEComm.
18:09:32.509 [Thread-8] D/PUMPBTCOMM: [BLEComm.connect():117]: Trying to create a new connection from: Connection needed

So [main] has the pump connected, but [Thread-8] is re-initializing BLEComm to create a new connection anyway..?

You don't have to explain if you don't want to. I just thought it looked strange.

Does it look correct to you?

**Comment by guydavies** [comment]
Hi Marcus,

I am also seeing my new Pixel4a unpairing from the DanaRSv3.  I’ve had the phone about 24 hours now and it has already done it twice.  Fortunately, not in the middle of the night, so I actually got my first night with the phone and pump and CGM all attached all night.  But I am fairly sure that was just luck.  I suspect it’ll fail during the night at some point.

I have attached a log file that shows the “Request pairing keys !!” At 13:45:52.006.  This was the latest time that the issue seems to have occurred (the previous one being before the start of this log file).

Maybe that can provide some more information for Milos.

Rgds,

Guy

**Comment by tomloopgit1974** [comment]
I have the same, 2 times now. Onelus7T, DexpatchedG6.
In logs i found: Clearing pairing key!! ?!?

**Comment by MilosKozak** [comment]
i added to dev following change:
AAPS clears pairing keys if it's not possible to establish encrypted connection for more than 5 min
test pls

**Comment by guydavies** [comment]
Will do

**Comment by guydavies** [comment]
@MilosKozak, does this mean that the pump/mobile will be even more “needy” ;-). If I happen to step away from my phone for >5 minutes, it will require a repairing?  That could easily happen going to the toilet overnight while my phone remains on my bedside table.

Rgds,

Guy

**Comment by guydavies** [comment]
@MilosKozak , I've tested and not seen any resets of the pairing key or of the pairing itself for about 24 hours.  This could be the good build.  So far, it's been very stable.

**Comment by Edgar2014-pompe** [comment]
Hello there,
can you explain me how can I test the changes youd add @MilosKozak I have the same issue with the jelly atom of my son.
@guydavies Maybe you can help me too ?
Is i still stable with the last changes ?

**Comment by guydavies** [comment]
Yes. It is stable with the latest changes. I've also worked out that the
provided leather pouch with the magnetic clasp tends to interfere with
connectivity from the pump to the phone. Looking into alternative pouches.

**Comment by Edgar2014-pompe** [comment]
@guydavies Thanks for your answer. But How can I found the last changes ? On Android Studio ?

**Comment by guydavies** [comment]
The latest Dev build can be selected in the bottom right corner of Android
Studio. You need to use VCS > git > fetch; then VCS > git > pull to ensure
you pull the latest Dev down.

Be careful though. The Dev build contains comparatively untested features
so is not for the novice. You also need to set the engineering mode to be
able to enable closed loop with the Dev build otherwise you'll only have
access to open loop.

**Comment by Mackwe** [comment]
@MilosKozak I have now cherry picked these changes into my branch and it seems stable now. I will close this and re-open should the problem re-occur. Thank you!
