### ISSUE TITLE
AAPS with VEO and Enlite for CGM?

### ISSUE THREAD

**Issue by Typ1er** [MilosKozak/AndroidAPS#2989]
I use the VEO and the Enlite Sensor.

Is AAPS still adjusted to receive CGM values via the RileyLink?

**Comment by ArthurusDent** [comment]
1. This is mainly a bugtracker and not a forum where questions like this can be addressed. Try Gitter, Discord or Facebook.

2. I'm pretty sure this has never been possible.

3. Please close this issue.

**Comment by MilosKozak** [comment]
it's not planned
