### ISSUE TITLE
What is the canonical repo for this project now?

### ISSUE THREAD

**Issue by StephenBrown2** [MilosKozak/AndroidAPS#2992]
Since about a month ago, there has been a new project at https://github.com/nightscout/AndroidAPS, where it seems that code is being worked on and merged, while this repo remains active as well.

My thought is that it will only cause confusion and extra work for @MilosKozak , having to maintain two different copies and sources for issues.

Why was this repo not migrated to the nightscout org, thus allowing for redirects, preserving the issues/PRs and keeping a single source of truth?

**Comment by MilosKozak** [comment]
to keep 2.6.X running

**Comment by StephenBrown2** [comment]
Cool. I suppose that makes sense. Will it be archived when the 2.6 branch gets EOLed (i.e. when 2.8 is a thing?) Not sure how long your support cycle is for different releases.

**Comment by MilosKozak** [comment]
2.6 will be discontinued after some time too
