### ISSUE TITLE
Add manual option to remove basal from IOB when pump disconnected

### ISSUE THREAD

**Issue by muthijammy** [MilosKozak/AndroidAPS#2994]
Add manual option to remove basal from IOB when pump disconnected

When pump is disconnected, AAPS assumes basal has been delivered as per active profile. When disconnected, pump may not delivered as disconnected from body accidentally. While it autocorrects bolus delivered via pump history once connected, same not happening via basal. Similar thing happens for site failure, etc. Can there be negate basal insulin option? I think if we enter from and to time, all basal insulin delivered as marked as 0% percentile and confirmation displays how much IOB is removed and timing entered. Currently, only option is giving correction manually so it matches what AAPS had used in calculations and then marking that bolus as invalid treatment

**Comment by MilosKozak** [comment]
this is not so simple like it may sounds. Allign IOB by using prefill feature is the best way
