### ISSUE TITLE
[2.7 omnipod 0.4] Wrong values for 15m and 40M delta glucose calculations

### ISSUE THREAD

**Issue by dududu13** [MilosKozak/AndroidAPS#2995]
Setup:
AAPS 2.7 omnipod 0.4  Buid version NoGitSystemAvalaible-202 0.11.19-22:23
Flavor : fulldebug
Version Nightscout 14.0.6
Xiaomi N10 lite
Xdrip+ / Freestylelibre
Omnipod open
Time : today everytime

I am french, sorry for my poor english
I am a new user, and I am on open loop since a good week
I noticed that the correction in basal was not very good, then I wanted to understand what was wrong
Then I saw that the 15m and 40m delta glucose values were wrong 
Xdrip values are OK
See the screen copy attached
![Screenshot_2020-11-24-18-21-56-084_info nightscout androidaps](https://user-images.githubusercontent.com/24843286/100131589-89f49380-2e84-11eb-964b-af33d6aa8d13.jpg)

**Comment by dududu13** [comment]
The immédiate delta and the 15m seem to be OK
I have try to stop Xdrip local broadcast, but I had to restart it because AAPS was not updated
Perhaps I have to wait 40m now to see

**Comment by MilosKozak** [comment]
why do thing it's wrong?

**Comment by dududu13** [comment]
Well I think that my parameters are still no correct , only this, that's why I wanted to understand
But my values for short_avgdelta and long_avgdelta (15 minutes and 40 minutes) are still wrong
Here this morning 
Delta15m= -14  and with Xdrip values 93-139=-46
Delta40m= -9 and with Xdrip values 93-153=-60
Perhaps I don't understand ? Or the unit are in mmol/l ?
![Screenshot_2020-11-25-10-28-49-288_info nightscout androidaps](https://user-images.githubusercontent.com/24843286/100210327-2a8d9680-2f0b-11eb-9d6d-95b7e20f58e7.jpg)

**Comment by jotomo** [comment]
The 15m and 40m deltas are _averages per 5m minutes_, not the delta between the current reading and the reading 15m or 40m ago. So, for the 15m delta calculation, the deltas between the readings are like this:
139 -> 124 = -15
124 -> 111 = -13
111 -> 93 = -18
Hence, the average delta of those is 15 (due to rounding values may differ slightly).

**Comment by dududu13** [comment]
OK, I understand now, thanks a lot, I am confused
