### ISSUE TITLE
Profile helper text button text dark on dark theme

### ISSUE THREAD

**Issue by guydavies** [MilosKozak/AndroidAPS#2997]
When using the profile helper in the current Dev build and every time I've previously tested, the button at the top of the screen shows black text on a dark background so it's barely visible. 

I suspect this is just not adjusting at all to dark mode. 

https://photos.app.goo.gl/eNxD8nNpie5RxY1e9

**Comment by andyrozman** [comment]
This repository is no longer active. If you have problem, test it with new dev version, and open Issue on nightscout/AndroidAPS repository.

**Comment by guydavies** [comment]
Yes. I must have put the issue on the old.repo. I was always using an up to
date version dev build. It is still present in the latest build from the
Nightscout repo.

**Comment by andyrozman** [comment]
Please close this issue here and reopen on other repository.
