### ISSUE TITLE
Safety first? Default Temp Target value is very low - 4.0 mmol/L (72mg/dl)

### ISSUE THREAD

**Issue by haspden** [MilosKozak/AndroidAPS#3001]
I feel the ethos and methodology of "Safety first" is missed with the default manual temp target being set at 4.0 (72). 

With just 2 button presses I can initiate a temp target possibly accidentally at my "floor" so to speak. My low value. I feel the default temp target should be set at your profile defined target. In my case 5.8 so that it required more user inputs to deviate away from this default target range in the event of a child / accidental but dial situation.

In my eyes this could also be definded in the settings page under the "Defaultn Temp-Targets" section. Tickbox to use profile target range as default target, followed by if uncheck the option to set a manual entry for this value.

![image](https://user-images.githubusercontent.com/4039041/104907881-a4775480-597d-11eb-83ca-745cf1ad3e83.png)
_p.s. Please ignore the high bloods in the background - forgot to bolus for my 100g+ carby breakfast.__

**Comment by MilosKozak** [comment]
agree. changed by https://github.com/nightscout/AndroidAPS/commit/6239f8e289832265a98988ea89142e9302b1827b

**Comment by haspden** [comment]
@MilosKozak  thanks, the move to 8.0 (144) is good (and safe) but I feel at some point using the profile defined target may be better. Coming back to safety I doubt many have their target > 8.0 (144) unless their new to looping with AAPS, however for those minority TT of 8.0 could still be lower than the profile defined.

Ideally in my head it should be the highest value of their target range as default.

Thanks for changing to 8.0 for now tho. Appreciate this isn't a big issue / priority and there are more pressing code changes to make. Would have changed it myself & merged but couldn't see where it was defined.

**Comment by chrisbev** [comment]
I like the 4.0 but get the pont how about the 'current' target as default. I use the pre-programmed buttons but also the default custom at 4.0 as the loop is so safe and quite often need to pull it down do 4.0 for say 20 mins does wonders.  To scroll down from normal to the bottom endstop would not be as bad as going down from 8? Normal aim target must be 'safer' than 4 or 8?
