### ISSUE TITLE
[2.8.1.1] CANCEL/OK buttons seem dim on some forms

### ISSUE THREAD

**Issue by chrisbev** [MilosKozak/AndroidAPS#3004]
2.8.1.1 For me the Insulin/Carbs/Calculator buttons on the main Tab lead to forms that have dim CANCEL/OK buttons but for comparison the Cancel Temp Target form has brightness that seems OK. Samsung A41.
Wish I could copy/paste the build info on the About form but expect not needed?

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
https://github.com/nightscout/AndroidAPS/commit/30547af0b411760fa44eb9f4e84956947f257698
