### ISSUE TITLE
Treatments received from xDrip/NS not working in 2.8.1 and 2.8.1.1

### ISSUE THREAD

**Issue by classchneider** [MilosKozak/AndroidAPS#3006]
Treatments downloaded from NS fail to show up on AndroidAPS app versions 2.8.1. and 2.8.1.1 (2.7.0 works fine)

Only BG data is updated correctly in AndroidAPS 2.8.1 versions when using the app for overwatch only. I had to revert to the 2.7.0 version (the last I had installed) to have the update working.

Build 10bd1d2df-2021.01.21-21:27, but the error was also on 2.8.1

I searched in the suggested path for my log file, but the newest files found were changed 13.01.2021 (today is 21.01.2021), so did not attach the log.

It should be fairly easy to reproduce the error as NO treatments are shown.

The below screen shots show that treatmenst were received at 22:05:31, but they cannot be found in the Treatments tab

--------------
![Screenshot_20210121-220557](https://user-images.githubusercontent.com/31922961/105415294-d9fb9680-5c38-11eb-8091-f0fe834c57ff.png)
![Screenshot_20210121-220620](https://user-images.githubusercontent.com/31922961/105414038-3e1d5b00-5c37-11eb-8d9b-4ba26585532c.png)
![Screenshot_20210121-220615](https://user-images.githubusercontent.com/31922961/105415557-2fd03e80-5c39-11eb-979e-d3274cb34ec8.png)

**Comment by MilosKozak** [comment]
did you read release notes?

**Comment by classchneider** [comment]
Please link me to release notes, they are well hidden ... they may be right in front of me, though I am not a novice I am fairly new to AndroidAPS. A hint to solving the problem if it is at my side would also be nice.

On the page https://github.com/MilosKozak/AndroidAPS there are 58 releases, the last 2.6.1.4 from may 2020 (no links to release notes on them ...). So for me it seems that there is only the master version which turns out after installation to be 2.8.1 or 2.8.1.1.

My old 2.7.0 keeps telling me that there is a new version 2.8.1.1 (could it please stop spamming me with that) - it would be nice if it was possible to turn that message off, moreover so as 2.8.1.1 seems not to be a release.

**Comment by classchneider** [comment]
I found the release notes.

**Comment by classchneider** [comment]
I guess these are the lines from release notes I should focus on:
> Option NS_UPLOAD_ONLY has been forced ON for all 2.8.1 users
> NS_UPLOAD_ONLY can only be turned off if engineering mode is enabled.

This means that all parents wanting to use AndroidAPS over overwatch their child, needs to run the app in engineering mode? This means that probably more than half of the installations will be engineering mode? How can this be a good idea?

I thought I *was* using engineering mode, but it seems engineering mode setting has changed (not found in the release notes). Not sure when this changed - it should probably have been mentioned in the corresponding release notes.

**Comment by classchneider** [comment]
The problem persists, engineering_mode *is* enabled, but the treatments are still not added to treatments in the AndroidAPS app.

On another device I have 2.7.0 running, which shows that an SMB was received from NS at 14:15.

![Screenshot_20210123-142827](https://user-images.githubusercontent.com/31922961/105579639-f22dfb80-5d87-11eb-9f23-8d4ce30f634c.png)
![Screenshot_20210123-142529](https://user-images.githubusercontent.com/31922961/105579641-f528ec00-5d87-11eb-8fb6-5363e11907ba.png)
![Screenshot_20210123-141914](https://user-images.githubusercontent.com/31922961/105579643-f78b4600-5d87-11eb-8d5d-d07f47c008e4.png)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/5860263/AndroidAPS.log)

**Comment by classchneider** [comment]
I realized that 2.8.1 did not just override my setting, it also *changed* my setting switching on the upload-only setting. Switching back off the setting made the app work again in overwatch mode (download NS data only). My mistake.

This means that this issue can be closed, allthough I think AndroidAPS need an option saying "Overwatch mode" for parents so that engineering__mode is necessary - this mode could be enabled when using a virtual pump.
