### ISSUE TITLE
Optional Two-factor authentication

### ISSUE THREAD

**Issue by AlmazKo** [MilosKozak/AndroidAPS#3009]
New approach of SMS protection which appeared in 2.7(https://androidaps.readthedocs.io/en/latest/Children/SMS-Commands.html) is overcomplicated (of cause it's more safer, but it's really difficult to use hourly)

Please add some checkbox for returning the old logic where 3-symbols codes are generated

PS: I've already seen custom builds where it exists

**Comment by MilosKozak** [comment]
this is not planned. but maybe will be possible use nsclient for that in the future
