### ISSUE TITLE
Temporary Targets set in NS do not appear in AAPS

### ISSUE THREAD

**Issue by dhermanns** [MilosKozak/AndroidAPS#3011]
Hi!

I already saw this:
#2515

But not sure if that’s related. I updated to Aaps 2.8.2 and it looks like it doesn‘t activate entered Temp Targets from Nightscout anymore. NSClient prints the entered treatment out, but they are not displayed in Aaps Care Portal.

When having a look at the json treatments, it turns out that the Aaps native temp targets have a NS_CLIENT_ID. Is there a new security feature or the like?

**Comment by flashfabrixx** [comment]
Had the same problem and found the answer in https://github.com/MilosKozak/AndroidAPS/issues/3006. 

In the [release notes](https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Releasenotes.html#version-2-8-1-1) of version 2.8.1.1, you will find the following information:
> **Important hints**
> - Option NS_UPLOAD_ONLY has been forced ON for all 2.8.1 users.
> - If you use NSClient to enter TT, carbs or profile switches you must turn it off in AAPS but only in case your synchronization is working well (ie. you don’t see unwanted data changes like self modification of TT, TBR etc).
> - ATTENTION: DO NOT do this if you have any other app handle treatments ( like xDrip broadcast/upload/sync...).
> - NS_UPLOAD_ONLY can only be turned off if engineering mode is enabled.

As our configuration and setup is working fine, I've the [enable engineering mode](https://androidaps.readthedocs.io/en/latest/Installing-AndroidAPS/Dev_branch.html) today and re-installed the app, to make the required settings visible and enable it again. 

<img width="372" alt="settings" src="https://user-images.githubusercontent.com/579869/132007174-8f394e58-6851-46cc-97d7-52cd4e4ddc30.png">

**Comment by dhermanns** [comment]
Thanks - good to know that. But disappointing that you have to enable the Dev-Mode for it. This makes the feature practical unusable for normal users. How is it intended to e.g. add some carbs now?

**Comment by flashfabrixx** [comment]
Yes, normally we entered carbs and TTs using your fantastic Nightguard iOS app - but with the latest update, this functionally was broken and we now finally found a workaround. 

Especially hard for parents to get this up and running now, even when I can fully understand the reasoning behind it.
