### ISSUE TITLE
Cannot "Profile Switch" 

### ISSUE THREAD

**Issue by christinadamianou** [MilosKozak/AndroidAPS#3017]
build e39014962-2021.12.19-13:34 - AndroidAPS 3.0-beta11
Using Pump Omnipod DASH. BG Source Glunovo
Go to Actions > Profile Switch
Press the button.
Button turns to disabled for some seconds and turns back to normal without opening the window to let me change my profile.

[AndroidAPS._2022-01-06_17-06-36_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/7829277/AndroidAPS._2022-01-06_17-06-36_.0.zip)

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
this repo is not used anymore. go to https://github.com/nightscout/AndroidAPS/issues
