### ISSUE TITLE
Strange Omnipod DASH error code

### ISSUE THREAD

**Issue by christinadamianou** [MilosKozak/AndroidAPS#3018]
While injecting a bolus with Omnipod DASH, I received a POD Fault: 49.
Officiali Insulet error codes do not include 049. What does it stands for?
POD was beeping until deactivated.

AndroidAPS 3.0-beta11
build: e39014962-2021.12.19-13:34
Reporting bugs
--------------
[Screenshot_20220105-131835_AndroidAPS](https://user-images.githubusercontent.com/38248445/148556822-4d8743cf-5de7-4a24-961d-73adac0cd10e.jpg)
[AndroidAPS._2022-01-05_13-15-23_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/7829293/AndroidAPS._2022-01-05_13-15-23_.0.zip)
[AndroidAPS._2022-01-05_13-15-23_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/7829294/AndroidAPS._2022-01-05_13-15-23_.1.zip)

**Comment by MilosKozak** [comment]
this repo is not used anymore. go to https://github.com/nightscout/AndroidAPS/issues
