### ISSUE TITLE
Add Prime to Database

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#317]
Idea:
 * Add "Prime" boluses to database by adding an extra boolean flag to the DB.
 * Exclude those Treatments from IOB calculation here: https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/Treatments/TreatmentsPlugin.java#L182

Advantages:
 * Can be seen in the Treatment tab (different colour e.g.), Overview and later watchface
 * Combo pump will be able to add treatments directy entered from the Pump and not confuse the logic

@MilosKozak Your opinion about that?

**Comment by MilosKozak** [comment]
I was already thinking about it and all records contains 'isValid' for cases like this and for 'delete' button in treatments. But it's not implemented yet

**Comment by MilosKozak** [comment]
In v2 driver it will be necessary
