### ISSUE TITLE
No profile switch button in Profile Pluginw with pumps that don't allow to write basal rate

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#321]
Applies to SimpleProfile and CPP, probably local profile as well

The button is needed with new ProfileSwitch logic.

Possible solution:
If `!isSetBasalProfileCapable` and setting to use the profile directly is not set: Show the button but don't name it "SEND TO PUMP" but "ACTIVATE PROFILE".

**Comment by MilosKozak** [comment]
agree. you?

**Comment by AdrianLxM** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/366
