### ISSUE TITLE
Only cancel rates that are real cancel events

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#326]
I would like to delete the `|| Math.abs(request.rate - getBaseBasalRate()) < 0.05` in the following: https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/ConfigBuilder/ConfigBuilderPlugin.java#L558

Reason: 
 *  for small basal rates like 0.3 Units things like 110% will now become possible
 * Cancelling with the Combo pump is cumbersome. An Alarm will rise that needs to be caught and the pump will vibrate. Keeping the rate running or changing is no problem.

I couldn't find disadvantages:
 * If it is close to the base basal rate and get rounded to the base basal rate, the dana pumps will cancel it anyway.
 *  Sending a cancel-event or setting something like 110% both need pump communication so we don't lose anything there (on average)

**Comment by MilosKozak** [comment]
👍
