### ISSUE TITLE
Button in Actions-Plugin does not cancel RealTempBasals

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#333]
... the registered listener has no case for that, just for extended boluses.

**Comment by AdrianLxM** [comment]
Fixed in pull request: https://github.com/MilosKozak/AndroidAPS/pull/334

**Comment by MilosKozak** [comment]
i forgot it in overview. remove it pls

**Comment by AdrianLxM** [comment]
> @MilosKozak 
> i forgot it in overview. remove it pls

Did remove the handling and removed the button in the other Overview layouts (smallscreen and NSClient) as well. PR updated.

**Comment by MilosKozak** [comment]
thanks !! i didn't notice it
