### ISSUE TITLE
Stale data alert

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#336]

**Comment by PoweRGbg** [comment]
https://github.com/PoweRGbg/AndroidAPS/blob/stale-alarm/app/src/main/java/info/nightscout/androidaps/plugins/Overview/Notification.java

**Comment by AdrianLxM** [comment]
@PoweRGbg this has all the SMB things in the history. Two workarounds:
1) checkout a clean branch of `dev` and cherry-pick your changes (`git cherry-pick #commithash)
2) generate a clean copy of `dev` in your repo and do a PR via github and then don't choose `merge` but ` Squash and merge`

**Comment by MilosKozak** [comment]
i don't see it

**Comment by RoumenGeorgiev** [comment]
Opened #337

**Comment by MilosKozak** [comment]
Things to be tested:
- [ ] Settings is retrieved from NS or from preferences (offline users)
- [ ] Alarms can be disabled in preferences
- [ ] Alarm is generated when nsclient is connected
- [ ] Alarm is generated when nsclient is not connected
- [ ] Snoozing alarm in AAPS snoozes alarm in other NSs and AAPSs (over NS, if connected)
- [ ] Alarm reappear after snooze time expire
- [ ] There are 2 separate stale data alarms for BG and OpenAPS

**Comment by RoumenGeorgiev** [comment]
1- tested OK
2 - tested OK
3 - not tested
4 - tested OK
5 - not tested
6 - tested OK
7 - not tested

**Comment by MilosKozak** [comment]
👍 let' go on

**Comment by stavlor** [comment]
All appears to be working ok in 39d41e8e need to update my build at some
point this weekend

**Comment by stavlor** [comment]
Note that if something is acknowledged via pushover it does get properly
dismissed in AAPS

**Comment by RoumenGeorgiev** [comment]
1- tested OK
2 - tested OK
3 - Tested - alarms for low apeared in AAPS also
4 - tested OK
5 - tested - dismissing an alarm in AAPS doesn't send ACK to NS
6 - tested OK
7 - Tested OK
