### ISSUE TITLE
Superbolus suspends pump even if bolus failed

### ISSUE THREAD

**Issue by savek-cc** [MilosKozak/AndroidAPS#341]
When issuing a superbolus (including basal for the next 2h) via the calculator, the pump is suspended even if the bolus delivery failed (e.g. pump comms error). No basal entry is recorded though.
See logic at https://github.com/MilosKozak/AndroidAPS/blob/32084094fd39c30434d422613f86cda5b20468a2/app/src/main/java/info/nightscout/androidaps/plugins/Overview/Dialogs/WizardDialog.java#L313

**Comment by MilosKozak** [comment]
all 3 actions (setting temp, bolus and superBolusTo) must be executed. there is no good solution when any action fails. it must be resolved manually

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/issues/508 duplicate
