### ISSUE TITLE
Autosense adjusted basal rate is not changed

### ISSUE THREAD

**Issue by Heiner1** [MilosKozak/AndroidAPS#343]
I had switched off autosense overnight, after switching it on, the BR is calculated, but not changed
![screenshot_2017-08-07-08-00-10](https://user-images.githubusercontent.com/20724321/29014007-0eb5500e-7b47-11e7-9f66-4f45582f4e0a.png)
![screenshot_2017-08-07-07-59-59](https://user-images.githubusercontent.com/20724321/29014008-0eb6761e-7b47-11e7-95a4-3b73e462f5d5.png)

**Comment by AdrianLxM** [comment]
@Heiner1 Autosens does not write the BR to the pump. It will give the overall result as temp basal. Without the reason field it is hard to tell, why it didn't set a new temp (or did it?). It might be still very close (rounded) e.g. when all the other calculations apply.

**Comment by Heiner1** [comment]
@AdrianLxM  THX, I thought I'd seen autosense changed basal rates; that's confusing me; next time I won't forget the reason field
