### ISSUE TITLE
Notification if Loop hits some preference boarders 

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#347]
During looping, sometimes the Loop is hitting some security boarders (preferences like max_basal, max_iob, max_daily_safety_multiplier, current_basal_safety_multiplier) and does not give the right amount of insulin for corrections. I think it would be helpful, if I can see a notification, when this happens and which parameter is limiting the Loop. Thanks in advance.

**Comment by savek-cc** [comment]
+1

**Comment by gempickfordwaugh** [comment]
+1 😊 and raised in openAPS too https://github.com/openaps/oref0/issues/623

**Comment by scottleibrand** [comment]
Has anyone thought through the best ways to capture this data in the json?

**Comment by winni67** [comment]
In the Loop tab form AAPS, there is the „After processed constraints“ field. Sometimes there are comments indicating such an event.

**Comment by MilosKozak** [comment]
resolved in dev
