### ISSUE TITLE
Correct index in DetailedBolusInfoStore?

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#350]
https://github.com/MilosKozak/AndroidAPS/commit/57f5e5a92d0301c03647de16e7985ae2294df1da#diff-499d43df4b401c6892dc4c9dfcfd383fR31

Should this be `long infoTime = store.get(0).date;` or `long infoTime = store.get(i).date;` ?
"get **i**th element" instead of "get first element"?

**Comment by MilosKozak** [comment]
THANKS !!!!!!
https://github.com/MilosKozak/AndroidAPS/commit/7884c98f2f33eb5daf9807a2d2d08864e7cad29b
