### ISSUE TITLE
Stale data alerts

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#356]
* Settings are not visible when NSClient is not activated.

* It is unclear what setting stops the "online" notifications to appear on the phone and what setting is to activate the local stale data alerts.

* If NSClient is disabled -> no need to check for any online notifications.

Thanks @PoweRGbg for taking care of this.

**Comment by RoumenGeorgiev** [comment]
Signing here to get notifications and remember me to do it :)

**Comment by AdrianLxM** [comment]
Stale data alerts are no longer part of the NSClient but are separate now.
