### ISSUE TITLE
1.5g/Local Profile/Target time can't be set properly

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#359]
When trying to set Target into Local Profile, it is impossible to set 'pm' time, only 'am' is possible.
For example, select 10pm, then 10am is selected.

**Comment by jotomo** [comment]
@gregorybel As a workaround, configure time to be displayed as 24 hours in Android preferences.

**Comment by gregorybel** [comment]
@jotomo Android is already configured like this 🙁

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/29373875-e10e20c0-82af-11e7-987e-7fcee51a031f.png)
what doesn't work?

**Comment by gregorybel** [comment]
Set first time 00:00 am
Then second time try to set 10pm, then 10am will be selected.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/b93a153b2397bb676d54fc19e9883e951a38d56b

**Comment by gregorybel** [comment]
Thanks a lot @MilosKozak
