### ISSUE TITLE
Actions from wear not done 

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#390]
Hi 

I have a huawei smartwatch version 1 with wear 2.0, when I try inputting bolus or using wizard, nothing happens! 

Do I have do something wrong or is there an issue? 

Please see this log or let me know what you need to better understand. Thank you:
08-23 08:48:26.525 27088 17337 D NSClientInternalPlugin: [EventThread] DEBUG [NSClientInternalPlugin.java:153]: PING received
08-23 08:48:34.981 27088 27099 D CircadianPercentageProfilePlugin: [Binder:27088_1] DEBUG [WatchUpdaterService.java:179]: Wear: bolus 0.1 1
08-23 08:48:35.000 27088 27088 D CircadianPercentageProfilePlugin: [main] DEBUG [WatchUpdaterService.java:507]: Requesting confirmation from wear: bolus 0.1 1
08-23 08:48:41.240 27088 27128 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-23 08:48:41.338 27088 27088 D TreatmentsPlugin: [main] DEBUG [TreatmentsPlugin.java:277]: activeTempbasal: TemporaryBasal{date=1503470725000, date=23/08/2017 08:45, isValid=true, pumpId=0, _id=599d24868bad51104cc1cd45, percentRate=80, absoluteRate=0.0, durationInMinutes=30, isAbsolute=false, isFakeExtended=false, netExtendedRate=0.0, minutesRemaining=27, secondsRemaining=1603}
08-23 08:48:41.341 27088 27088 D OverviewFragment: [main] DEBUG [OverviewFragment.java:880]: updateGUI entered from: onResume
08-23 08:48:41.344 27088 27088 D Notification: [main] DEBUG [Notification.java:170]: bgReadingAgoMin value is:3
08-23 08:48:41.344 27088 27088 D Notification: [main] DEBUG [Notification.java:173]: OpenAPS Alerts enabled: false
08-23 08:48:41.401 27088 27088 D OverviewFragment: [main] DEBUG [Profiler.java:16]: >>> onResume <<< executed in 60 miliseconds
08-23 08:48:41.611 27088 27088 D ActivityThread: Remove activity client record, r= ActivityRecord{df744d3 token=android.os.BinderProxy@de23bf1 {info.nightscout.androidaps/info.nightscout.androidaps.plugins.Overview.Dialogs.BolusProgressHelperActivity}} token= android.os.BinderProxy@de23bf1
08-23 08:48:51.631 27088 17393 D NSClientInternalPlugin: [EventThread] DEBUG [NSClientInternalPlugin.java:153]: PING received
08-23 08:49:00.007 27088 28767 D TreatmentsPlugin: [Binder:27088_4] DEBUG [TreatmentsPlugin.java:277]: activeTempbasal: TemporaryBasal{date=1503470725000, date=23/08/2017 08:45, isValid=true, pumpId=0, _id=599d24868bad51104cc1cd45, percentRate=80, absoluteRate=0.0, durationInMinutes=30, isAbsolute=false, isFakeExtended=false, netExtendedRate=0.0, minutesRemaining=26, secondsRemaining=1584}
08-23 08:49:00.032 27088 17528 D SendDataThread: DataMap: {sgvString=149, sgvLevel=0, avgDelta=+3,6, low=80.0, slopeArrow=→, entries=[{sgvString=204, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451197E12, sgvDouble=204.06708188632138, delta=+4,9, battery=85}, {sgvString=203, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451497E12, sgvDouble=202.89539182173394, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451797E12, sgvDouble=205.53169446705567, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452097E12, sgvDouble=207.87507459623055, delta=+4,9, battery=85}, {sgvString=202, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452397E12, sgvDouble=202.40718762815587, delta=+4,9, battery=85}, {sgvString=188, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452697E12, sgvDouble=187.66342098209736, delta=+4,9, battery=85}, {sgvString=199, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452999E12, sgvDouble=198.69683575696232, delta=+4,9, battery=85}, {sgvString=205, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453298E12, sgvDouble=204.7505677573307, delta=+4,9, battery=85}, {sgvString=202, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453597E12, sgvDouble=202.40718762815587, delta=+4,9, battery=85}, {sgvString=197, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453897E12, sgvDouble=196.93930066008116, delta=+4,9, battery=85}, {sgvString=207, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454197E12, sgvDouble=206.60574369292746, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454497E12, sgvDouble=207.97271543494617, delta=+4,9, battery=85}, {sgvString=210, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454797E12, sgvDouble=209.53496885439606, delta=+4,9, battery=85}, {sgvString=207, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455097E12, sgvDouble=207.48451124136804, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455397E12, sgvDouble=206.215180338065, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455697E12, sgvDouble=206.1175394993494, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455997E12, sgvDouble=208.16799711237738, delta=+4,9, battery=85}, {sgvString=211, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456297E12, sgvDouble=210.60901808026787, delta=+4,9, battery=85}, {sgvString=216, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456597E12, sgvDouble=215.58870085476445, delta=+4,9, battery=85}, {sgvString=218, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456897E12, sgvDouble=218.32264433880178, delta=+4,9, battery=85}, {sgvString=223, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503457197E12, sgvDouble=223.30232711329833, delta=+4,9, battery=85}, {sgvString=217, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503457497E12, sgvDouble=217.0533134354987, delta=+4,9, battery=85}, {sgvString=217, sgvLevel=1, avgDelta=+3,6, low=80.0, 
08-23 08:49:00.049 27088 17528 D SendDataThread: DataMap: {sgvString=149, sgvLevel=0, avgDelta=+3,6, low=80.0, slopeArrow=→, entries=[{sgvString=204, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451197E12, sgvDouble=204.06708188632138, delta=+4,9, battery=85}, {sgvString=203, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451497E12, sgvDouble=202.89539182173394, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503451797E12, sgvDouble=205.53169446705567, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452097E12, sgvDouble=207.87507459623055, delta=+4,9, battery=85}, {sgvString=202, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452397E12, sgvDouble=202.40718762815587, delta=+4,9, battery=85}, {sgvString=188, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452697E12, sgvDouble=187.66342098209736, delta=+4,9, battery=85}, {sgvString=199, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503452999E12, sgvDouble=198.69683575696232, delta=+4,9, battery=85}, {sgvString=205, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453298E12, sgvDouble=204.7505677573307, delta=+4,9, battery=85}, {sgvString=202, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453597E12, sgvDouble=202.40718762815587, delta=+4,9, battery=85}, {sgvString=197, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503453897E12, sgvDouble=196.93930066008116, delta=+4,9, battery=85}, {sgvString=207, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454197E12, sgvDouble=206.60574369292746, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454497E12, sgvDouble=207.97271543494617, delta=+4,9, battery=85}, {sgvString=210, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503454797E12, sgvDouble=209.53496885439606, delta=+4,9, battery=85}, {sgvString=207, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455097E12, sgvDouble=207.48451124136804, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455397E12, sgvDouble=206.215180338065, delta=+4,9, battery=85}, {sgvString=206, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455697E12, sgvDouble=206.1175394993494, delta=+4,9, battery=85}, {sgvString=208, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503455997E12, sgvDouble=208.16799711237738, delta=+4,9, battery=85}, {sgvString=211, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456297E12, sgvDouble=210.60901808026787, delta=+4,9, battery=85}, {sgvString=216, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456597E12, sgvDouble=215.58870085476445, delta=+4,9, battery=85}, {sgvString=218, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503456897E12, sgvDouble=218.32264433880178, delta=+4,9, battery=85}, {sgvString=223, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503457197E12, sgvDouble=223.30232711329833, delta=+4,9, battery=85}, {sgvString=217, sgvLevel=1, avgDelta=+3,6, low=80.0, slopeArrow=→, high=160.0, batteryLevel=1, timestamp=1.503457497E12, sgvDouble=217.0533134354987, delta=+4,9, battery=85}, {sgvString=217, sgvLevel=1, avgDelta=+3,6, low=80.0, 
08-23 08:49:00.061 27088 17529 D SendDataThread: DataMap: {temps=[{amount=0.0, endbasal=0.4, startBasal=0.4, starttime=1503468840001, endtime=1503470640001}, {amount=0.32, endbasal=0.32, startBasal=0.4, starttime=1503470880001, endtime=1503471240001}], basals=[{amount=0.5, endtime=1503453840001, starttime=1503451140001}, {amount=0.55, endtime=1503457440001, starttime=1503453840001}, {amount=0.7, endtime=1503461040001, starttime=1503457440001}, {amount=0.85, endtime=1503464640001, starttime=1503461040001}, {amount=0.7, endtime=1503468240001, starttime=1503464640001}, {amount=0.4, endtime=1503470940001, starttime=1503468240001}]} sent to: HUAWEI WATCH 1424
08-23 08:49:00.067 27088 17529 D SendDataThread: DataMap: {temps=[{amount=0.0, endbasal=0.4, startBasal=0.4, starttime=1503468840001, endtime=1503470640001}, {amount=0.32, endbasal=0.32, startBasal=0.4, starttime=1503470880001, endtime=1503471240001}], basals=[{amount=0.5, endtime=1503453840001, starttime=1503451140001}, {amount=0.55, endtime=1503457440001, starttime=1503453840001}, {amount=0.7, endtime=1503461040001, starttime=1503457440001}, {amount=0.85, endtime=1503464640001, starttime=1503461040001}, {amount=0.7, endtime=1503468240001, starttime=1503464640001}, {amount=0.4, endtime=1503470940001, starttime=1503468240001}]} sent to: SmartWatch 3 7B19
08-23 08:49:05.683 27088 27099 D CircadianPercentageProfilePlugin: [Binder:27088_1] DEBUG [WatchUpdaterService.java:179]: Wear: bolus 0.1 1
08-23 08:49:05.689 27088 27088 D CircadianPercentageProfilePlugin: [main] DEBUG [WatchUpdaterService.java:507]: Requesting confirmation from wear: bolus 0.1 1
08-23 08:49:16.772 27088 17548 D NSClientInternalPlugin: [EventThread] DEBUG [NSClientInternalPlugin.java:153]: PING received
08-23 08:49:18.882 27088 27164 D CircadianPercentageProfilePlugin: [Binder:27088_3] DEBUG [WatchUpdaterService.java:179]: Wear: temptarget  true 15 100.0 100.0
08-23 08:49:18.895 27088 27088 D CircadianPercentageProfilePlugin: [main] DEBUG [WatchUpdaterService.java:507]: Requesting confirmation from wear: temptarget  true 15 100.0 100.0
08-23 08:49:25.403 27088 27088 V AudioManager: playSoundEffect   effectType: 0
08-23 08:49:25.403 27088 27088 V AudioManager: querySoundEffectsEnabled...
08-23 08:49:25.476 27088 27088 I HwPointEventFilter: do not support AFT because of no config
08-23 08:49:25.524 27088 27128 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-23 08:49:26.972 27088 27088 V AudioManager: playSoundEffect   effectType: 0
08-23 08:49:26.972 27088 27088 V AudioManager: querySoundEffectsEnabled...
08-23 08:49:27.010 27088 27088 D HwCust  : Create obj success use class android.app.HwCustActivityImpl
08-23 08:49:27.012 27088 27088 D HwCust  : Create obj success use class android.app.HwCustHwWallpaperManagerImpl
08-23 08:49:27.013 27088 27088 V ActivityThread: ActivityThread,callActivityOnCreate
08-23 08:49:27.027 27088 27088 D HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0b003a, context : info.nightscout.androidaps.PreferencesActivity@2c9ddce, Nhwext : 0, get Blur : disable with , null
08-23 08:49:27.031 27088 27088 D HwRTBlurUtils: check blur style for HwPhoneWindow-, themeResId : 0x7f0b003a, context : info.nightscout.androidaps.PreferencesActivity@2c9ddce, Nhwext : 0, get Blur : disable with , null
08-23 08:49:27.072 27088 27088 D ActivityThread: add activity client record, r= ActivityRecord{728cd7c token=android.os.BinderProxy@4266d35 {info.nightscout.androidaps/info.nightscout.androidaps.PreferencesActivity}} token= android.os.BinderProxy@4266d35
08-23 08:49:27.074 27088 27088 I HwPointEventFilter: do not support AFT because of no config
08-23 08:49:27.100 27088 27128 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-23 08:49:27.167 27088 27128 D OpenGLRenderer: endAllActiveAnimators on 0xc529f200 (ListPopupWindow$DropDownListView) with handle 0xc9c28d40
08-23 08:49:28.360 27088 27088 D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
08-23 08:49:28.361 27088 27088 D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
08-23 08:49:28.361 27088 27088 D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
08-23 08:49:28.361 27088 27088 D CubicBezierInterpolator: CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
08-23 08:49:42.910 27088 17587 D NSClientInternalPlugin: [EventThread] DEBUG [NSClientInternalPlugin.java:153]: PING received
08-23 08:49:52.350 27088 27088 D KeyEvent: obtain, mHwFlags=120
08-23 08:49:52.415 27088 27088 D KeyEvent: obtain, mHwFlags=120
08-23 08:49:52.444 27088 27088 D TreatmentsPlugin: [main] DEBUG [TreatmentsPlugin.java:277]: activeTempbasal: TemporaryBasal{date=1503470725000, date=23/08/2017 08:45, isValid=true, pumpId=0, _id=599d24868bad51104cc1cd45, percentRate=80, absoluteRate=0.0, durationInMinutes=30, isAbsolute=false, isFakeExtended=false, netExtendedRate=0.0, minutesRemaining=26, secondsRemaining=1532}
08-23 08:49:52.445 27088 27088 D OverviewFragment: [main] DEBUG [OverviewFragment.java:880]: updateGUI entered from: onResume
08-23 08:49:52.457 27088 27088 D OverviewFragment: [main] DEBUG [Profiler.java:16]: >>> onResume <<< executed in 11 miliseconds
08-23 08:49:52.464 27088 27128 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-23 08:49:52.782 27088 27088 D ActivityThread: Remove activity client record, r= ActivityRecord{728cd7c token=android.os.BinderProxy@4266d35 {info.nightscout.androidaps/info.nightscout.androidaps.PreferencesActivity}} token= android.os.BinderProxy@4266d35
08-23 08:49:54.182 27088 27088 V AudioManager: playSoundEffect   effectType: 0
08-23 08:49:54.182 27088 27088 V AudioManager: querySoundEffectsEnabled...
08-23 08:49:54.202 27088 27088 I HwPointEventFilter: do not support AFT because of no config
08-23 08:49:54.260 27088 27128 D mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000
08-23 08:49:56.537 27088 27088 V AudioManager: playSoundEffect   effectType: 0
08-23 08:49:56.537 27088 27088 V AudioManager: querySoundEffectsEnabled...
08-23 08:49:56.547 27088 27088 I System.out: [logcat, -d, AndroidAPS:D]
08-23 08:49:56.547 27088 27088 I System.out: null
08-23 08:49:56.547 27088 27088 I System.out: null
08-23 08:49:56.550 27088 27088 I System.out: Calling by::className:info.nightscout.utils.LogDialog  MethodName:showLogcat

**Comment by gregorybel** [comment]
Version 1.5g combo

**Comment by AdrianLxM** [comment]
In Android-Wear 2.0 the notification to confirm the calculation does not pop up automatically like on AW 1.0 and 1.5.
Did you pull the notification up and confirm it?

**Comment by AdrianLxM** [comment]
Solution was: need to make the Notifications pop up
closeing

**Comment by gregorybel** [comment]
Thank you for your help!
