### ISSUE TITLE
Wrong IAGE SAGE

### ISSUE THREAD

**Issue by Heiner1** [MilosKozak/AndroidAPS#392]
If IAGE is set on AAPS it's first correct, then, when SAGE is set, IAGE is changed (17 Days) SAGE (only 46 hours) - vice versa; logfile line 5280; 
IAGE and SAGE is displayed correct in Nightscout "0.10.0-dev-20170423","head":"c7b1520"
I can't put the logfile in there - shall I mail you?

**Comment by MilosKozak** [comment]
send me some more detailed info as i'm not able to reproduce this bug

**Comment by MilosKozak** [comment]
@Heiner1 do you still have this issue?

**Comment by Heiner1** [comment]
Sorry Milos, forgot to look for it. I didn't see it the last months, might be another reason what caused that.
