### ISSUE TITLE
Restrict temp targets

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#401]
... in the GUI to the range we later accept in the OAPS plugins without alarm.

**Comment by AdrianLxM** [comment]
... and while doing this, refactor the limit constants to the constants class.

**Comment by wootmasterslick** [comment]
Please also indicate the limits in the selection screen when selecting the tgt. For example when trying to set a target above 10mmol/l do not allow the couter to go further up, or make it so the color turns read. The errors that ovcur when setting up a to high tgt are difficult to interpret for novice users.
