### ISSUE TITLE
Not install on android 5.0 / 6.0

### ISSUE THREAD

**Issue by cr4sh0v3r** [MilosKozak/AndroidAPS#405]
Building the 1.55 version, tested on : 
galaxy s4 with android 5.0, i receive a can't install app.
zenfone2 android 6.0 same issue 
zenfone 2 android 5.0 same issue
huawei p9 plus with android 7 and it works. 

Any idea ? Min sdk 21, target 23

**Comment by MilosKozak** [comment]
do not change anything. it's working on 5+

**Comment by cr4sh0v3r** [comment]
Just tried, it starts on virtual device, but it doesn't start on the tested phones, any idea ?!? Older version works normally

**Comment by MilosKozak** [comment]
probably something wrong with studio.
update it to latest version and download AAPS sources again

**Comment by cr4sh0v3r** [comment]
I'll try as soon as you can, however I'm using your software for my uncle, he thanks you for your job, he is living fine, hope God bless you. Thanks for all

**Comment by savek-cc** [comment]
First uninstall all old/existing versions on the phone and then try to install/start again; Maybe there is an old version with a different signature (built on a different PC) already installed?

**Comment by cr4sh0v3r** [comment]
Done all the updates for android studio, downloaded new version of winrar ( just to be sure ) and nothing to do. Starts installing and then it fails. Tried with different devices, also from friends, android 5 / 6 / 6.01 not installing, my p9 plus 7.0 works fine.

**Comment by cr4sh0v3r** [comment]
Executing tasks: [:app:assembleFullWearRelease]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\Samsung\AppData\Local\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to C:\Users\Samsung\AppData\Local\Android\Sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preFullWearReleaseBuild UP-TO-DATE
:app:checkFullWearReleaseManifest
:app:preFullNowearDebugBuild UP-TO-DATE
:app:preFullNowearReleaseBuild UP-TO-DATE
:app:preFullWearDebugBuild UP-TO-DATE
:app:preFullWearcontrolDebugBuild UP-TO-DATE
:app:preFullWearcontrolReleaseBuild UP-TO-DATE
:app:preNsclientNowearDebugBuild UP-TO-DATE
:app:preNsclientNowearReleaseBuild UP-TO-DATE
:app:preNsclientWearDebugBuild UP-TO-DATE
:app:preNsclientWearReleaseBuild UP-TO-DATE
:app:preNsclientWearcontrolDebugBuild UP-TO-DATE
:app:preNsclientWearcontrolReleaseBuild UP-TO-DATE
:app:preOpenloopNowearDebugBuild UP-TO-DATE
:app:preOpenloopNowearReleaseBuild UP-TO-DATE
:app:preOpenloopWearDebugBuild UP-TO-DATE
:app:preOpenloopWearReleaseBuild UP-TO-DATE
:app:preOpenloopWearcontrolDebugBuild UP-TO-DATE
:app:preOpenloopWearcontrolReleaseBuild UP-TO-DATE
:app:prePumpcontrolNowearDebugBuild UP-TO-DATE
:app:prePumpcontrolNowearReleaseBuild UP-TO-DATE
:app:prePumpcontrolWearDebugBuild UP-TO-DATE
:app:prePumpcontrolWearReleaseBuild UP-TO-DATE
:app:prePumpcontrolWearcontrolDebugBuild UP-TO-DATE
:app:prePumpcontrolWearcontrolReleaseBuild UP-TO-DATE
:app:prepareAndroidEdittextValidatorV134ModLibrary
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:app:prepareComAndroidSupportAppcompatV72340Library
:app:prepareComAndroidSupportCardviewV72340Library
:app:prepareComAndroidSupportDesign2340Library
:app:prepareComAndroidSupportGridlayoutV72340Library
:app:prepareComAndroidSupportPercent2340Library
:app:prepareComAndroidSupportRecyclerviewV72340Library
:app:prepareComAndroidSupportSupportV42340Library
:app:prepareComAndroidSupportSupportVectorDrawable2340Library
:app:prepareComCrashlyticsSdkAndroidAnswers1312Library
:app:prepareComCrashlyticsSdkAndroidBeta124Library
:app:prepareComCrashlyticsSdkAndroidCrashlytics267Library
:app:prepareComCrashlyticsSdkAndroidCrashlyticsCore2316Library
:app:prepareComEclipsesourceJ2v8J2v8316Library
:app:prepareComGoogleAndroidFlexbox030Library
:app:prepareComGoogleAndroidGmsPlayServicesBase750Library
:app:prepareComGoogleAndroidGmsPlayServicesWearable750Library
:app:prepareComJjoe64Graphview401Library
:app:prepareComJoanzapataIconifyAndroidIconify211Library
:app:prepareComJoanzapataIconifyAndroidIconifyFontawesome211Library
:app:prepareComWdullaerMaterialdatetimepicker230Library
:app:prepareIoFabricSdkAndroidFabric1316Library
:app:prepareFullWearReleaseDependencies
:app:compileFullWearReleaseAidl UP-TO-DATE
:app:compileFullWearReleaseRenderscript UP-TO-DATE
:app:generateFullWearReleaseBuildConfig UP-TO-DATE
:app:mergeFullWearReleaseShaders UP-TO-DATE
:app:compileFullWearReleaseShaders UP-TO-DATE
:app:generateFullWearReleaseAssets UP-TO-DATE
:app:mergeFullWearReleaseAssets UP-TO-DATE
:wear:preBuild UP-TO-DATE
:wear:preRestrictedReleaseBuild UP-TO-DATE
:wear:checkRestrictedReleaseManifest
:wear:preFullDebugBuild UP-TO-DATE
:wear:preFullReleaseBuild UP-TO-DATE
:wear:preRestrictedDebugBuild UP-TO-DATE
:wear:prepareComAndroidSupportRecyclerviewV72301Library
:wear:prepareComAndroidSupportSupportV42301Library
:wear:prepareComGoogleAndroidGmsPlayServicesBase730Library
:wear:prepareComGoogleAndroidGmsPlayServicesWearable730Library
:wear:prepareComGoogleAndroidSupportWearable140Library
:wear:prepareMeDenleyWearpreferenceactivityWearpreferenceactivity050Library
:wear:prepareUstwoClockwiseDebugLibrary
:wear:prepareRestrictedReleaseDependencies
:wear:compileRestrictedReleaseAidl UP-TO-DATE
:wear:compileRestrictedReleaseRenderscript UP-TO-DATE
:wear:generateRestrictedReleaseBuildConfig UP-TO-DATE
:wear:generateRestrictedReleaseResValues UP-TO-DATE
:wear:generateRestrictedReleaseResources UP-TO-DATE
:wear:mergeRestrictedReleaseResources UP-TO-DATE
:wear:processRestrictedReleaseManifest UP-TO-DATE
:wear:processRestrictedReleaseResources UP-TO-DATE
:wear:generateRestrictedReleaseSources UP-TO-DATE
:wear:incrementalRestrictedReleaseJavaCompilationSafeguard UP-TO-DATE
:wear:javaPreCompileRestrictedRelease
:wear:compileRestrictedReleaseJavaWithJavac UP-TO-DATE
:wear:mergeRestrictedReleaseShaders UP-TO-DATE
:wear:compileRestrictedReleaseShaders UP-TO-DATE
:wear:generateRestrictedReleaseAssets UP-TO-DATE
:wear:mergeRestrictedReleaseAssets UP-TO-DATE
:wear:transformClassesWithDexForRestrictedRelease UP-TO-DATE
:wear:compileRestrictedReleaseNdk UP-TO-DATE
:wear:mergeRestrictedReleaseJniLibFolders UP-TO-DATE
:wear:transformNativeLibsWithMergeJniLibsForRestrictedRelease UP-TO-DATE
:wear:processRestrictedReleaseJavaRes UP-TO-DATE
:wear:transformResourcesWithMergeJavaResForRestrictedRelease UP-TO-DATE
:wear:validateSigningRestrictedRelease
:wear:packageRestrictedRelease UP-TO-DATE
:app:handleFullWearReleaseMicroApk UP-TO-DATE
:app:processFullWearReleaseManifest UP-TO-DATE
:app:fabricGenerateResourcesFullWearRelease
:app:generateFullWearReleaseResValues UP-TO-DATE
:app:generateFullWearReleaseResources
:app:mergeFullWearReleaseResources
:app:processFullWearReleaseResources
warning: string 'app_name' has no default translation.


:app:generateFullWearReleaseSources
:app:incrementalFullWearReleaseJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileFullWearRelease
:app:compileFullWearReleaseJavaWithJavac UP-TO-DATE
:app:compileFullWearReleaseNdk UP-TO-DATE
:app:compileFullWearReleaseSources UP-TO-DATE
:app:lintVitalFullWearRelease
:app:transformClassesWithDexForFullWearRelease UP-TO-DATE
:app:mergeFullWearReleaseJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForFullWearRelease UP-TO-DATE
:app:processFullWearReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForFullWearRelease UP-TO-DATE
:app:validateSigningFullWearRelease
:app:packageFullWearRelease
:app:assembleFullWearRelease

BUILD SUCCESSFUL

Total time: 16.517 secs

**Comment by cr4sh0v3r** [comment]
i'm downloading ndk, only warning i've at the moment

**Comment by AdrianLxM** [comment]
Can you also please check that in your path to the SDK there are no whitespaces.

**Comment by cr4sh0v3r** [comment]
no spaces, seems all ok but doesn't start, on android 7 is working fine like previous try.

Executing tasks: [:app:assembleFullNowearRelease]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preFullNowearReleaseBuild UP-TO-DATE
:app:checkFullNowearReleaseManifest
:app:preFullNowearDebugBuild UP-TO-DATE
:app:preFullWearDebugBuild UP-TO-DATE
:app:preFullWearReleaseBuild UP-TO-DATE
:app:preFullWearcontrolDebugBuild UP-TO-DATE
:app:preFullWearcontrolReleaseBuild UP-TO-DATE
:app:preNsclientNowearDebugBuild UP-TO-DATE
:app:preNsclientNowearReleaseBuild UP-TO-DATE
:app:preNsclientWearDebugBuild UP-TO-DATE
:app:preNsclientWearReleaseBuild UP-TO-DATE
:app:preNsclientWearcontrolDebugBuild UP-TO-DATE
:app:preNsclientWearcontrolReleaseBuild UP-TO-DATE
:app:preOpenloopNowearDebugBuild UP-TO-DATE
:app:preOpenloopNowearReleaseBuild UP-TO-DATE
:app:preOpenloopWearDebugBuild UP-TO-DATE
:app:preOpenloopWearReleaseBuild UP-TO-DATE
:app:preOpenloopWearcontrolDebugBuild UP-TO-DATE
:app:preOpenloopWearcontrolReleaseBuild UP-TO-DATE
:app:prePumpcontrolNowearDebugBuild UP-TO-DATE
:app:prePumpcontrolNowearReleaseBuild UP-TO-DATE
:app:prePumpcontrolWearDebugBuild UP-TO-DATE
:app:prePumpcontrolWearReleaseBuild UP-TO-DATE
:app:prePumpcontrolWearcontrolDebugBuild UP-TO-DATE
:app:prePumpcontrolWearcontrolReleaseBuild UP-TO-DATE
:app:prepareAndroidEdittextValidatorV134ModLibrary
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:app:prepareComAndroidSupportAppcompatV72340Library
:app:prepareComAndroidSupportCardviewV72340Library
:app:prepareComAndroidSupportDesign2340Library
:app:prepareComAndroidSupportGridlayoutV72340Library
:app:prepareComAndroidSupportPercent2340Library
:app:prepareComAndroidSupportRecyclerviewV72340Library
:app:prepareComAndroidSupportSupportV42340Library
:app:prepareComAndroidSupportSupportVectorDrawable2340Library
:app:prepareComCrashlyticsSdkAndroidAnswers1312Library
:app:prepareComCrashlyticsSdkAndroidBeta124Library
:app:prepareComCrashlyticsSdkAndroidCrashlytics267Library
:app:prepareComCrashlyticsSdkAndroidCrashlyticsCore2316Library
:app:prepareComEclipsesourceJ2v8J2v8316Library
:app:prepareComGoogleAndroidFlexbox030Library
:app:prepareComGoogleAndroidGmsPlayServicesBase750Library
:app:prepareComGoogleAndroidGmsPlayServicesWearable750Library
:app:prepareComJjoe64Graphview401Library
:app:prepareComJoanzapataIconifyAndroidIconify211Library
:app:prepareComJoanzapataIconifyAndroidIconifyFontawesome211Library
:app:prepareComWdullaerMaterialdatetimepicker230Library
:app:prepareIoFabricSdkAndroidFabric1316Library
:app:prepareFullNowearReleaseDependencies
:app:compileFullNowearReleaseAidl UP-TO-DATE
:app:compileFullNowearReleaseRenderscript UP-TO-DATE
:app:generateFullNowearReleaseBuildConfig UP-TO-DATE
:app:mergeFullNowearReleaseShaders UP-TO-DATE
:app:compileFullNowearReleaseShaders UP-TO-DATE
:app:generateFullNowearReleaseAssets UP-TO-DATE
:app:mergeFullNowearReleaseAssets UP-TO-DATE
:app:processFullNowearReleaseManifest UP-TO-DATE
:app:fabricGenerateResourcesFullNowearRelease
:app:generateFullNowearReleaseResValues UP-TO-DATE
:app:generateFullNowearReleaseResources
:app:mergeFullNowearReleaseResources
:app:processFullNowearReleaseResources
warning: string 'app_name' has no default translation.


:app:generateFullNowearReleaseSources
:app:incrementalFullNowearReleaseJavaCompilationSafeguard UP-TO-DATE
:app:javaPreCompileFullNowearRelease
:app:compileFullNowearReleaseJavaWithJavac UP-TO-DATE
:app:compileFullNowearReleaseNdk UP-TO-DATE
:app:compileFullNowearReleaseSources UP-TO-DATE
:app:lintVitalFullNowearRelease
:app:transformClassesWithDexForFullNowearRelease UP-TO-DATE
:app:mergeFullNowearReleaseJniLibFolders UP-TO-DATE
:app:transformNativeLibsWithMergeJniLibsForFullNowearRelease UP-TO-DATE
:app:transformNativeLibsWithStripDebugSymbolForFullNowearRelease UP-TO-DATE
:app:processFullNowearReleaseJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForFullNowearRelease UP-TO-DATE
:app:validateSigningFullNowearRelease
:app:packageFullNowearRelease
:app:assembleFullNowearRelease

BUILD SUCCESSFUL

Total time: 17.643 secs

**Comment by cr4sh0v3r** [comment]
if somebody can send a compiled apk i can try installation on my devices

**Comment by MilosKozak** [comment]
Try pumpcontrol app from releases

**Comment by cr4sh0v3r** [comment]
Not working, but i've seen this : 
:app:compilePumpcontrolNowearReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by cr4sh0v3r** [comment]
If i use android studio connected with my device, and i build with the adb device attached, it builds and works. If i generate the apk and then try to install on the device, it fails installing

**Comment by cr4sh0v3r** [comment]
android monitor log errors : 

08-30 20:10:02.248 27932-27932/info.nightscout.androidaps E/WindowManager: android.view.WindowLeaked: Activity info.nightscout.androidaps.MainActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{9b9ed48 V.E...... R.....I. 0,0-0,0} that was originally added here
                                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:610)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
                                                                               at android.app.Dialog.show(Dialog.java:505)
                                                                               at info.nightscout.utils.OKDialog.show(OKDialog.java:40)
                                                                               at info.nightscout.androidaps.MainActivity.askForBatteryOptimizationPermission(MainActivity.java:221)
                                                                               at info.nightscout.androidaps.MainActivity.onCreate(MainActivity.java:82)
                                                                               at android.app.Activity.performCreate(Activity.java:6904)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                               at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7331)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by cr4sh0v3r** [comment]
just installed used build, now i've a full-nowear-DEBUG, and it works.
If i use the signed version it doesn't start
