### ISSUE TITLE
Improvement: remove non-functioning time-dependency code in DanaR extended bolus plugins

### ISSUE THREAD

**Issue by wouterla** [MilosKozak/AndroidAPS#420]
In the ```setExtendedBolus``` methods in all the DanaR plugins, there is code that seems to change the rounding step for the amount of insulin:
```
insulin = Round.roundTo(insulin, getPumpDescription().extendedBolusStep * (1 + durationInHalfHours % 1));
```
The ```* (1 + durationInHalfHours % 1)``` doesn't do anything, as ```durationInHalfHours``` is an int, so the remainder there will always be `0`.

There also doesn't seem to be a reason there to change the rounding step, so the behaviour seems as intended, so this code should probably be removed for clarity.

**Comment by MilosKozak** [comment]
`durationInHalfHours` ... `(1 + durationInHalfHours % 1)`
1 ... 2
2 ... 1
3 ... 2
4 ... 1
5 ... 2
6 ... 1

**Comment by MilosKozak** [comment]
am i right?

**Comment by MilosKozak** [comment]
hmmm right.
first idea was  % 2, but looks like 2 bugs lead to working code too :( it works more than 1 year well so we can remove it.
thanks. 
send PR please, it will be in all Dana plugins probably ...

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/e063f3a2cb553d479411495b04325876575277af
thanks @wouterla
