### ISSUE TITLE
NS-client: Enter a reduced BR

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#431]
In NS-client if I want to notice a reduced BR I couldn't enter a negative value (f. e. -10%) as the amount of reduction, error message: "You reached allowed limit".
But if I enter a BR of 10% the NS-client stores a BR of 110%.
Workaround is to enter the absolute amount of insulin per hour.
Thanks for your great work and for fixing this small issue.

![screenshot_20170926-100338](https://user-images.githubusercontent.com/12517693/30849528-ea963d72-a2a2-11e7-8d7d-4c76cfbb7b27.png)
![screenshot_20170926-100400](https://user-images.githubusercontent.com/12517693/30849529-ea997e06-a2a2-11e7-8890-93878a0db451.png)

**Comment by stavlor** [comment]
Hmm interesting this likely is due to the fact that NSClient is based off AndroidAPS which rarely uses % basal values but will check into it.

**Comment by MilosKozak** [comment]
that's correct because AAPS uses Dana notation (0 ... 200%) and NS uses Animas/MM notation (-100 ... +100%). and careportal is a NS feature.
But all values should be translated to correct notation

**Comment by swissalpine** [comment]
Thank you.
And you're right, I found another example that could be investigated, the
combo bolus. Xdrip and Nightscout are getting false values.

Am 04.10.2017 12:02 vorm. schrieb "Milos Kozak" <notifications@github.com>:
