### ISSUE TITLE
NS client app

### ISSUE THREAD

**Issue by ellabellakaramella** [MilosKozak/AndroidAPS#440]
I think it is really nice but wonder if maybe I can suggest a couple of improvements. Instead of Pbat age I think p.bat % is more rewarding to know. Target bg range would be great to see. 

![screenshot_20171001-113120 1](https://user-images.githubusercontent.com/16548944/31189569-e53d5666-a938-11e7-9fc7-a99207fd6557.png)

**Comment by MilosKozak** [comment]
do you use dana pump?

**Comment by MilosKozak** [comment]
pump battery status is visible under Pump (if enabled in NS)
