### ISSUE TITLE
New to GitHub, but wanted to ask about possible way to access minimed pumps via AndroidAPS and Moto mods

### ISSUE THREAD

**Issue by Jieseldeep** [MilosKozak/AndroidAPS#443]
Motorola's Moto Z line of phones uses Moto mods to attach hardware to their z and z2 phones. They have available a developers mod that is essentially a breadboard to create your own hardware to clip on the back of their phones. 

One of the developer mods is apparently designed to interface with Hat form factor, which is apparently something the old raspberry pi OpenAPS used. Is there anyone out there who would be willing to work on such an idea? I could probably provide the phone and maybe the developer mod kit if someone was willing to try to make it work...

**Comment by Jieseldeep** [comment]
https://www.element14.com/community/groups/moto-mods

In case anyone is interested in checking it out further. They have a Pi Hat mod available but I don't know how to get from the old raspberry pi software utilized in the beginnings of OpenAPS to where the phone will communicate directly with the Hat without needing a Pi in between. Eventually I'll persevere or catch someone's interest with this one!

**Comment by MilosKozak** [comment]
nobody is working on it
