### ISSUE TITLE
Failed bolus error

### ISSUE THREAD

**Issue by gempickfordwaugh** [MilosKozak/AndroidAPS#449]
Failed bolus gives an error on the phone app screen, but can this be sent to the watch so it's not easily missed? (Took me 2 hrs to notice today) Also IOB thinks it has the insulin from the missed bolus so won't allow accurate corrections, so a failed bolus should delete the insulin treatment entry too?

**Comment by jotomo** [comment]
Was it a dialog/popup or a red notification header on the overview screen? If the latter, you can enable the _Overview notification_ under the wear section to display those messages as watch notifications.

> Also IOB thinks it has the insulin from the missed bolus

Can you check both treatments (in NS) and the pump history? The treatment record (which is then used in IOB calcs) should only be written _after_ a successful bolus of course.

**Comment by gempickfordwaugh** [comment]
Sorry, I thought I had that _Overview Notification_ enabled but it turns out I didn't (I knew something like that would already be covered!).  Am now getting all the red/amber/green notification headers on the watch, thank you :-)

I'm confident from my blood scores that the bolus definitely wasn't delivered but no proof from the pump as too long ago.  If it happens again (I sometimes walk away from my phone before the bolus has happened due to slow connection so probably won't take long to recreate!!) I'll compare pump history and NS.  It happened a day later and the unsuccessful bolus didn't show up in NS so I wonder whether it doesn't write it when red notification dismissed immediately, but the first time as I didn't dismiss the notification until 2 hours later it was too outdated to affect the treatment upload?  Speculation of course.  I'll see if I can recreate it!
