### ISSUE TITLE
DIA issue?

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#481]
Hi

I wonder why when I set a DIA of 5, loop still use a DIA of 3, see screenshots:

DIA is 5:

![2017-10-07 11 02 41](https://user-images.githubusercontent.com/24234385/31910600-50288342-b83e-11e7-905e-386ecbab53c1.png)

DIA is also 5:

![2017-10-07 11 03 09](https://user-images.githubusercontent.com/24234385/31910610-58a9550a-b83e-11e7-88b5-4b75d9107ee7.png)

But Loop uses a DIA of 3:

![2017-10-07 11 03 01](https://user-images.githubusercontent.com/24234385/31910622-632352b0-b83e-11e7-83e9-4377c89c3f27.png)

is it an issue or did I do something wrong?

I use version 1.5h

Thanks

**Comment by savek-cc** [comment]
same here with 1.54 dev

**Comment by gregorybel** [comment]
@savek-cc thanks checking on newer version, I still did not feel comfortable updating!

**Comment by AdrianLxM** [comment]
Yes, that's how it is inteded to be.

DIA should only be used for IOB calculations, not as a parameter for  expected delta as it was done by mistake in detemine basal. Hence the cap.

**Comment by gregorybel** [comment]
OK thanks for explanation. So we should simply keep a dia of 3 for determine basal? And we should not touch this parameter?
