### ISSUE TITLE
Default min_5min_carbimpact

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#482]
I wonder why aaps uses a default value of 3.0:

![2017-10-07 11 03 55](https://user-images.githubusercontent.com/24234385/31910735-c6d3fa12-b83e-11e7-870d-98eaf722f4ce.png)

but oaps suggests 8:

![2017-10-07 11 05 25](https://user-images.githubusercontent.com/24234385/31910757-d16d3b5a-b83e-11e7-9450-1f7d97ba459c.png)

which value should I best use?
Or how to calculate it?

Thanks
Gregory
Version: 1.5h

**Comment by AdrianLxM** [comment]
It uses the same default value as Oref0 at that point in time.

**Comment by gregorybel** [comment]
OK....

So what are your advices, should I keep it to 3 or something else?
