### ISSUE TITLE
release version or apk download?

### ISSUE THREAD

**Issue by xour** [MilosKozak/AndroidAPS#487]
Dear developers, 
First of all congrats for a great work! please excuses about my ignorance on this matter, but I'm not a developer myself. I only want to install AndroidAPS on my phone as I am a T1D for more than 30 years and I am since recently learning about these great software. I tried to follow the instructions with Android Studio but I'm getting some silly errors in the compilation due to my lack of experience. 
Is there any way I could only get a stable version of the code without having to compile it myself? i.e. any link to download a release version or an apk of the software? That would be great!!! I believe not only for me but for many other T1Ds in my situation.... thanks indeed for all your efforts, I will definitely contribute once I have the time to learn it and test it.
Best regards, 
Ling

**Comment by AdrianLxM** [comment]
Hello Ling,

I'm sorry, but AndroidAPS is strictly DIY (Do It Yourself)!
It is developed by the community, but it is not a medical product. In fact not a product at all.
You will therefore need to load it into a development environment (that is for free for almost all mayor desctop systems!!) and build it yourself.
With the help of the Wiki you should be able to learn what to do in a very short time. You don't need to know how to program and don't need be a developer when you start. Just take your time (a weekend is best) and learn the steps. When you run into errors, ask in the gitter channel (https://gitter.im/MilosKozak/AndroidAPS). There are always some users who already managed to set it up that are happy to help. This is a great community.

cheers,
Adrian

**Comment by MilosKozak** [comment]
you may try https://github.com/nightscout/AndroidAPSBuilder too
