### ISSUE TITLE
Build variants empty

### ISSUE THREAD

**Issue by xour** [MilosKozak/AndroidAPS#491]
Dear all, I am trying to build the project. Anybody knows why my Build Variants menu on the lower left corner in Android Studio might show: "Nothing to show". What am I doing wrong? I enclose a screen capture:
![build variants empty](https://user-images.githubusercontent.com/33124099/32146852-f38eea78-bcdd-11e7-8290-b6768da54978.jpg)
Thanks in advance for your help!

**Comment by AdrianLxM** [comment]
It looks like while unzipping you have created a directory `AndroidAPS-master` that contains the other `AndroidAPS-master`. It looks like, while importing the project, you have chosen the "outer" one, but should have used the subdirectory.

**Comment by xour** [comment]
Great!! I will try it out... Thanks a lot

**Comment by xour** [comment]
Wow, after rebuilding and plenty of updates, it seems to be working... however I now get this error:
Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html

Anybody can suggest anything?

**Comment by AdrianLxM** [comment]
You either need to use Android Studio 2 with `master` (redownload it if Android Studio3 has touched it!) or switch to `dev`

**Comment by xour** [comment]
Thanks again AdrianLxM! I do not fully get what you mean by "with master" and "switch to dev"... but can try uninstalling Android Studio and redownloading v2 if that's what you mean?
