### ISSUE TITLE
NS client 1.55

### ISSUE THREAD

**Issue by ellabellakaramella** [MilosKozak/AndroidAPS#510]
Hi Milos! Just updated to latest NS client. Has only gone 10 min but I don't seem to get pumpstatus or OAPSstatus, it's blank. Maybe something got wrong when building the app for me, but everything els works great, IOB, COB, SAGE, IAGE etc shows ok.

**Comment by MilosKozak** [comment]
this should be fixed (wrong ISO date parsing), reopen if needed
