### ISSUE TITLE
NPE in NSClient: info.nightscout.androidaps.plugins.Loop.LoopPlugin.isDisconnected()

### ISSUE THREAD

**Issue by andrew-warrington** [MilosKozak/AndroidAPS#514]
After compiling NSClient from latest dev, the app crashes every 10 minutes or so (not sure exactly how long) with the following error:

12-01 23:33:02.260 24992 24992 D AndroidRuntime: Shutting down VM
12-01 23:33:02.417 24992 24992 E AndroidRuntime: FATAL EXCEPTION: main
12-01 23:33:02.417 24992 24992 E AndroidRuntime: Process: info.nightscout.androidaps, PID: 24992
12-01 23:33:02.417 24992 24992 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver info.nightscout.androidaps.receivers.KeepAliveReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean info.nightscout.androidaps.plugins.Loop.LoopPlugin.isDisconnected()' on a null object reference
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3068)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.app.ActivityThread.-wrap18(ActivityThread.java)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1574)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean info.nightscout.androidaps.plugins.Loop.LoopPlugin.isDisconnected()' on a null object reference
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at info.nightscout.androidaps.receivers.KeepAliveReceiver.checkPump(KeepAliveReceiver.java:85)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at info.nightscout.androidaps.receivers.KeepAliveReceiver.onReceive(KeepAliveReceiver.java:55)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3061)
12-01 23:33:02.417 24992 24992 E AndroidRuntime: 	... 8 more
12-01 23:33:02.438  1705  1722 W ActivityManager:   Force finishing activity info.nightscout.androidaps/.MainActivity
12-01 23:33:02.445  1705  1722 W ActivityManager:   Force finishing activity info.nightscout.androidaps/.MainActivity
12-01 23:33:02.445  1705  1722 W ActivityManager: Duplicate finish request for ActivityRecord{8cb70af u0 info.nightscout.androidaps/.MainActivity t3919 f}
12-01 23:33:02.445  2173  8923 D ProcSpeedReader: Failed to read freq stats from null

**Comment by AdrianLxM** [comment]
Thank you @andrew-warrington.

For now could you try to disable "local alerts -> alert if pump unreachable" in the settings unit there is a fix please.
It is the alert system checking if the (local) pump is reachable that accesses a module that is not there in NSClient compile type.

cheers

**Comment by AdrianLxM** [comment]
Does this fix it?
https://github.com/MilosKozak/AndroidAPS/pull/515

**Comment by andrew-warrington** [comment]
@AdrianLxM that fixes it, yes. Thanks!!
