### ISSUE TITLE
NPE in PreferencesActivity.java when compiled as NSClient

### ISSUE THREAD

**Issue by andrew-warrington** [MilosKozak/AndroidAPS#517]
Am currently getting a NPE within the PreferencesActivity.java code when compiling NSClient from dev and testing https://github.com/MilosKozak/AndroidAPS/pull/494.

The message is:
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference`

The code is:
`            if (savedInstanceState != null && savedInstanceState.containsKey("id")) {
                id = savedInstanceState.getInt("id");
            }`

Looking at the code, I have no idea why this is happening -- the relevant check is in place before the attempt to .getInt.

Full stack trace:
`11-26 09:04:01.529 23349 23349 E AndroidRuntime: FATAL EXCEPTION: main
11-26 09:04:01.529 23349 23349 E AndroidRuntime: Process: info.nightscout.androidaps, PID: 23349
11-26 09:04:01.529 23349 23349 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{info.nightscout.androidaps/info.nightscout.androidaps.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2678)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2743)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4560)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.-wrap19(ActivityThread.java)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at info.nightscout.androidaps.PreferencesActivity$MyPreferenceFragment.onCreate(PreferencesActivity.java:123)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2336)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:949)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:2036)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.FragmentController.dispatchCreate(FragmentController.java:165)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Activity.onCreate(Activity.java:964)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:536)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at info.nightscout.androidaps.PreferencesActivity.onCreate(PreferencesActivity.java:47)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6687)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2631)
11-26 09:04:01.529 23349 23349 E AndroidRuntime: 	... 10 more`

**Comment by AdrianLxM** [comment]
Hm, @MilosKozak, any idea why `getIntent()` would return `null`?

@andrew-warrington are you compiling apks and install them on your phone or do you push things via android studio and use instant run or similar? After a restart of the phone, does it still behave like this?

**Comment by andrew-warrington** [comment]
I compile APKs and run them on my phone. I have rebooted my phone and the error appears after a couple of minutes.

**Comment by AdrianLxM** [comment]
@andrew-warrington thank you very much for working on that!

I (unfortunately) cannot reproduce it on my dev phone. Could you please do the following tests:

***1) Does it only happen, when the setting are called from the 3-dot menu, or also when long-pressing an element in the config-builder that has the settings icon (wear plugin)***

***2) Does it happen, when reverting the xml for the wear settings?***

***3) When changing the onCreate method to filter out intents that are null, do the settings then work as they should?***

info.nightscout.androidaps.PreferencesActivity
```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        myPreferenceFragment = new MyPreferenceFragment();
        Bundle args = new Bundle();
        Intent intent = getIntent();
        if (intent != null){
            args.putInt("id", intent.getIntExtra("id", -1));
        } else {
            args.putInt("id", -1);
        }
        myPreferenceFragment.setArguments(args);
        getFragmentManager().beginTransaction().replace(android.R.id.content, myPreferenceFragment).commit();
        PreferenceManager.getDefaultSharedPreferences(this).registerOnSharedPreferenceChangeListener(this);
    }
```

**Comment by andrew-warrington** [comment]
Hi @AdrianLxM , I also can only reproduce it intermittently. It actually hasn't happened for the last hour or so since I rebuilt following my git repository fiasco. Maybe I had broken something locally?

For your questions 1) and 2) - It was never linked to any particular user interaction.

For question 3), I propose that we keep this issue open for a couple of days. If the error re-appears I will grab the suggested code and see if it fixes the problem. If the issue does not come back we can close this and assume something had just gone wrong on my side. 

If it turns out to be nothing, then apologies for having taken up your time on this!

**Comment by andrew-warrington** [comment]
The app has been running for 24 hours without a crash now -- if you agree I will close this issue.

**Comment by AdrianLxM** [comment]
Please leave it open as a reminder. I'd like to fix it anyways, even if it only occurs in rare occasions.

**Comment by andrew-warrington** [comment]
Hi @AdrianLxM, no sign of this crash for weeks now. I suggest to close this. Do you agree? (While it was happening, it was happening at least once per day.)

**Comment by MilosKozak** [comment]
tested and no issue
