### ISSUE TITLE
Bug in showing treatment in Open Loop Mode

### ISSUE THREAD

**Issue by osodebailar** [MilosKozak/AndroidAPS#521]
Configuration:
- Samsung S7 Edge with Android Nougat
- Android APS Build: d1aec1ff-2017.11.29
- Nightscout Version: 0.10.2-release-20171109
- BG fom xdrip+ with Dexcom G5

Android APS is running in Open Loop Mode with virtual pump

Effect 1:
Treatment is read by xdrip and send to AAPS.
Straight after reading BG value treatment is shown in AAPS treatment field.
If you click ( touch ) in the field and the Acknowledge dialog open, the values
that are shown are others than in treatment field.

Effect 2:
Treatment is read by xdrip and send to AAPS.
Straight after reading BG value treatment is shown in AAPS treatment field.
Clicking ( touching) in treatment field to open Acknowledge dialog has no effect.
If you manual initiate recalculation about register 'LP' or 'OAPS' treatment is shown again
and often with other values. Sometimes touching in the treatment field open the acknowledge dialog,
but very often the situation is the same i explained above , nothing happened and no acknowledge dialog appears. 

Her a screenshot to show different values in treatment field and acknowledge dialog
![24282293_1595499873805853_31784499_n](https://user-images.githubusercontent.com/25795894/33540453-77f17a2a-d8cb-11e7-900a-b81b2c12f813.jpg)

**Comment by MilosKozak** [comment]
when you press "Accept ..." new calculation is always done to calculate with latest data (IOB etc)

**Comment by osodebailar** [comment]
Yes Millos , but it is ver confusing To See different values. 
And Effect 2 i explaned above is very comfusing.
You See a Treatment , Touch on it and nothing happend.
I will try To explain Theo Problem a Little Bit more detailed, so you can netter understand the problem.
