### ISSUE TITLE
Suspend for 1h set zero temp only for 30m

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#534]

**Comment by winni67** [comment]
Today I tried to "Disconnect pump for 30 min" and the temporary basalrate was not set to zero. I noticed this problem in my AAPS version from 11.11.2017. The update on Sunday (17.11.2017) does not solve this problem. Scince then there is another isue with NightScout "Invalid Date".

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/74abdc02712e3a4ba634d5f50456b8fa7c9e6c4f
