### ISSUE TITLE
Bug in setting temporary target

### ISSUE THREAD

**Issue by osodebailar** [MilosKozak/AndroidAPS#536]
In the "Action" dialog you can set a temporary target. The target will be shown in the main dialog and taken for calculation.
But if you go back to the Action dialog , you don't see anything in the button "temporary target" an you are not able to cancel the target. 

Android APS version: 1.56-dev
Build: 648b918e-2017.12.06

**Comment by AdrianLxM** [comment]
I cannot confirm that.
I've set a temporary target "eating soon" with target 80 for 60 minutes.
The button in the action tab is still there. If I press it, press "ok" and press confirm that (0-duration temp target), it will cancel the "eating soon" set before.

**Comment by osodebailar** [comment]
As i see now , you are right t stop the target in the way you did.
But it is a very strange behavior in usablity.

In my thoughts the behavior must be the same as it is in the "Temp basal" button.
You set a target, and after that the text in the button change in the way you see it in the "temp basal" button. So you can click again and the  settings will be canceled.

I think it would be a good idea that the behavior of the "temp target button" is the same as the "temp basal button".
In the moment it is not very intuitive.

**Comment by AdrianLxM** [comment]
Temp-basals cannot overlap.
Temp-Targets can overlap and if two are active, the most recent one counts. You can also schedule temp-targets in the future. This is a bit more powerful.

How about having a preset "cancel" like "eating soon", "activity", ... that alwalways fills the form with 0/0?

**Comment by osodebailar** [comment]
Ok that was a new information for me that i am able to set more than one target.

We can do this either in the way you describe  , or with a "cancel active target" button in the preset dialog , that will be available if a target is set.
