### ISSUE TITLE
Bug: Bolus calculator offers higher bolus for smaller BG if BG bellow targetBGLow 

### ISSUE THREAD

**Issue by kuchjir** [MilosKozak/AndroidAPS#543]
Bolus calculator result for BG 3.8 is 1.65u while for BG 4.8 is 1.5u. So it calculates higher bolus for a smaller blood glucose. All the other inputs are the same.

I believe the problem is caused by this code in BolusWizard.

        if (bg <= targetBGLow) {
            bgDiff = bg - targetBGLow;
        } else {
            bgDiff = bg - targetBGHigh;
        }
        insulinFromBG = bg != 0d ? bgDiff / sens : 0d;

assume targetBGLow 4.0 and targetBGHigh 8.0 then
when(bg = 3.8).then(bgDiff is -0.2)
when(bg = 4.8).then(bgDiff is -3.2)

**Comment by MilosKozak** [comment]
so what is missing is return 0 when in range ... right?

**Comment by AdrianLxM** [comment]
I think it depends on what we want to have:
Correct to range?
Correct to centre of range?

... in fact it should not matter much as most of the people have a single target nowadays anyway. Still the current logic would suggest that the branch with no insulin is needed if in range.

**Comment by kuchjir** [comment]
The extra branch returning 0 when in range make sense. 

I could make a code change. I would like to provide also unit test. But I am new to Android development and I do not know how to mock MainApp in BolusWizard when writing a test?

**Comment by MilosKozak** [comment]
@kuchjir try it

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/a5c4495a5d8bca9c2fa3c5d35f5e5ac9e1904c5b
@kuchjir writing a text would be nice
