### ISSUE TITLE
Entering low basal rates in Local Profile

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#550]
Using the +/- butons, reducing a basal rate < 0.10 is blocked (limit reached).
Entering the value manually, e.g. 0.01 works though.
Entering 0.00 and moving to another tab and back empties the full (still applied, but not displayed again).

So, either prevent manually entering a value < 0.10 or allowing values down to 0.00.

**Comment by AdrianLxM** [comment]
I would not allow 0.00 as this is a mistake that should not happen.
How about 0.05 as lower limit?

**Comment by MilosKozak** [comment]
i agree this should be changed according to PumpInfo
`TimeListEdit` must be refactored to accept min and max values too

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/771f9eac1aef8be77a8a0b87a14280b0b16cd75f
send PR if you think the values should be different
