### ISSUE TITLE
Invalid Date on NightScout treatments after AAPS update

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#554]
Hello,

after the AAPS update on Sunday (17.12.2017) I have only wrong NightScout treatments with the timestamp "Invalid Date". The last NightScout updates before where on 08.12.2017 and some days after the AAPS update on 19.12.2017. NightScout and AAPS are on the developer branch.

![fullsizerender](https://user-images.githubusercontent.com/6819067/34272189-a9a53d82-e68f-11e7-9d2d-f8324847841b.jpg)

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/6b23ba10bd49a59ceb29a97b8307293cc8951246
