### ISSUE TITLE
Use with Roche Accu-Chek

### ISSUE THREAD

**Issue by PatrickAPT** [MilosKozak/AndroidAPS#556]
Hi 
I read here http://www.diabettech.com/looping-a-guide/ that there was some Alpha-testing for using the AndroidAPS with the Roche Accu-Chek. However, i couldn't find informations about it when i got here. 
Any idea how this went? Is there a version that works with the Accu-Chek?

Thx for your reply

Patrick

**Comment by MilosKozak** [comment]
ask for join here
https://www.facebook.com/groups/127507891261169/
