### ISSUE TITLE
Date clash on two Care-Portal entries

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#559]
Martin experienced this today:

When two entries in Care Portal like sensor change an cannula change are made at the same minute, the second one overwrites the first one.

I guess it is due to the fact that the key is the date and without seconds/milliseconds they are considered identical/duplicates?

**Comment by MilosKozak** [comment]
probably yes. the dialog doesn't allow to enter seconds
is it an issue?

**Comment by AdrianLxM** [comment]
I don't think we need to change the interface, but how the data is stored.

If it indeed is the case, that only the time is used as key:
The quick fix would be to have a different offset of ms depending on what datatype it is. This way the entries would not have the same key and not overwrite themselves.
The more elegant way would be to update the database scheme.

That it is timestamps as keys that cause the problem is only an educated guess though. It might be something else that causes it.

**Comment by MilosKozak** [comment]
maybe add seconds would be enough.
btw NS doesn't store ms

**Comment by MilosKozak** [comment]
i'm doing too but it never happened to me .... strange

**Comment by blocklist** [comment]
Hi this is the ns-log and the screenshots from careportal:

I have set the time 1 hour earlier:
`GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  nIVdd2qRfUlfp1G1AACH  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00+0000',
     eventType: 'Site Change',
     glucose: 91,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514024089798 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:15:10.944Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:470, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:7, insulinchangeTreatments:21, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:122
WS: running websocket.update
delta changes found on treatments
lastData full size 1731602 bytes
WS: running websocket.emitData 1514024110944
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  nIVdd2qRfUlfp1G1AACH  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00+0000',
     eventType: 'Insulin Change',
     glucose: 91,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514024177846 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:16:18.133Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:471, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:7, insulinchangeTreatments:22, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:122
WS: running websocket.update
delta changes found on treatments
lastData full size 1726681 bytes
WS: running websocket.emitData 1514024178133
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00Z',
     eventType: 'Insulin Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514024991069 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:29:51.354Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:470, mbgs:2, cals:2, profiles:1, devicestatus:1308, food:2, sitechangeTreatments:8, insulinchangeTreatments:24, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1728755 bytes
WS: running websocket.emitData 1514024991354
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`

`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
tick 2017-12-23T10:30:21.658Z
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:30:22.659Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:470, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:24, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta calculation indicates no new data is present
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`
![screenshot_20171223-110848](https://user-images.githubusercontent.com/491321/34319029-9bca0da8-e7d6-11e7-944e-65e0b6c54a51.png)

`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:20:00Z',
     eventType: 'Insulin Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514025046860 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:30:47.156Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:471, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:25, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1726333 bytes
WS: running websocket.emitData 1514025047156
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`
![screenshot_20171223-111514](https://user-images.githubusercontent.com/491321/34319027-9369117c-e7d6-11e7-99f5-712a168a98f6.png)

`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
tick 2017-12-23T10:31:21.658Z
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:31:22.659Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:557, treatments:471, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:25, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta calculation indicates no new data is present
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`
![screenshot_20171223-111635](https://user-images.githubusercontent.com/491321/34319025-8d078de0-e7d6-11e7-8f61-822f84e57533.png)

`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00Z',
     eventType: 'Insulin Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514025109272 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:31:49.682Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:556, treatments:472, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:26, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1726795 bytes
WS: running websocket.emitData 1514025109682
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`

![screenshot_20171223-112937](https://user-images.githubusercontent.com/491321/34319017-4b99ffbe-e7d6-11e7-99f0-52b4953b503d.png)


`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T04:32:00Z',
     eventType: 'Insulin Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514025137922 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:32:18.211Z' } },
  sort: { created_at: 1 } }
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
Load Complete:
         sgvs:556, treatments:473, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:27, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1727111 bytes
WS: running websocket.emitData 1514025138211
tick 2017-12-23T10:32:21.658Z
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:32:22.659Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:556, treatments:473, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:8, insulinchangeTreatments:27, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta calculation indicates no new data is present
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`

![screenshot_20171223-113242](https://user-images.githubusercontent.com/491321/34319013-3f00ee98-e7d6-11e7-96a2-19e40e0eed9a.png)


`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00Z',
     eventType: 'Site Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514025177067 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:32:57.363Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:556, treatments:474, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:9, insulinchangeTreatments:27, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1727573 bytes
WS: running websocket.emitData 1514025177363
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`

![screenshot_20171223-113304](https://user-images.githubusercontent.com/491321/34319012-37402b10-e7d6-11e7-919c-8e8c1eb990f4.png)


`
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
WS: dbAdd client ID:  smLRczDb46NcNi_AAACM  data:  { collection: 'treatments',
  data:
   { created_at: '2017-12-21T05:17:00Z',
     eventType: 'Insulin Change',
     glucose: 95,
     glucoseType: 'Sensor',
     units: 'mg/dl',
     enteredBy: 'Pump',
     NSCLIENT_ID: 1514025196540 } }
DEDUPE: Adding new record
got data-received event, requesting reload
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:33:16.826Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:556, treatments:475, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:9, insulinchangeTreatments:28, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta changes found on treatments
lastData full size 1728029 bytes
WS: running websocket.emitData 1514025196826
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
tick 2017-12-23T10:33:21.658Z
searching treatments q { find: { created_at: { '$gte': '2017-12-15T10:33:22.659Z' } },
  sort: { created_at: 1 } }
Load Complete:
         sgvs:556, treatments:475, mbgs:2, cals:2, profiles:1, devicestatus:1304, food:2, sitechangeTreatments:9, insulinchangeTreatments:28, sensorTreatments:12, profileTreatments:99, tempbasalTreatments:120
WS: running websocket.update
delta calculation indicates no new data is present
GRANTED:  89.15.222.21 no-token api:pebble,entries:read default
`
![screenshot_20171223-113322](https://user-images.githubusercontent.com/491321/34319011-30f3da90-e7d6-11e7-98d5-fc28e62be943.png)

I hope i have the screenshot right sorted.
But you can see, i have only changed insulin-reservoir, but catheter age would changed.

**Comment by MilosKozak** [comment]
do you use AAPS online or offline?
When online it works like it should

**Comment by blocklist** [comment]
both. But it comes only, when the change-date is older then 1 Day.

**Comment by MilosKozak** [comment]
then yes .... NS doesn't send old data to save traffic but it should fix itself by merged nsoffline branch.
try dev build after 21.12.

**Comment by blocklist** [comment]
sorry for the late reply. Yes, for the same day it works online and offline. thx!
