### ISSUE TITLE
Careportal Entries not shown in Main Screen and not calculated

### ISSUE THREAD

**Issue by cheers2** [MilosKozak/AndroidAPS#569]
Hi Milos,
I am on dev 1.56 downloaded 27-Dec-2017 running a virtual pump. Any entry I do in the careportal is not being taken over to the main Screen and is not being considered for calculations. Same issue I had with 1.55 master so Adrian recommended to try dev 1.56. Attached is a log file. I did two entries in CP, one today 10:27am Snack Bolus "test carb cp", the other today 12:40pm I think Correction Bolus "test unit cp". Both entries are shown in Xdrip+ (Version 3c5568d-2017.12.22) and in NS.
[AAPS_log_dev156.txt](https://github.com/MilosKozak/AndroidAPS/files/1591165/AAPS_log_dev156.txt)

Any idea what could be missing in my Settings?

Many thanks.

**Comment by kehle** [comment]
Hi Milos,
We used master 1.55 and also found that carbohydrates entered retrospectiveley via careportal (as carb correction) are not shown in the main sreen and not calculated either. 

Thanks in advance Thomas

**Comment by MilosKozak** [comment]
tested right now in online mode and with paused NS: both working well
it doesn't work if nsclient is completly disabled because careportal is NS feature

**Comment by MilosKozak** [comment]
let me know your settings if you still have troubles

**Comment by AdrianLxM** [comment]
@MilosKozak: @cheers2 was online while that happened. The NSClient Tab even showed in the log that a new Treatment was received.

**Comment by MilosKozak** [comment]
then i'd need bigger part of log file

**Comment by cheers2** [comment]
[AndroidAPS[1].log](https://github.com/MilosKozak/AndroidAPS/files/1594763/AndroidAPS.1.log)

[AndroidAPSPreferences.txt](https://github.com/MilosKozak/AndroidAPS/files/1594766/AndroidAPSPreferences.txt)

I hope the log file is the right one. Settings I have exported just now but no changes done. 
Did I understand Adrian correctly that I don´t need to be online in order to get CP entries registered in AAPS as of version 1.56?

**Comment by MilosKozak** [comment]
it's because you have synchronization with NS disabled
but i think it should work even with this setting so i changed it in https://github.com/MilosKozak/AndroidAPS/commit/4643cdc3b9f1ec6d8d602dad2f1f5175ed89fc1a

**Comment by MilosKozak** [comment]
i've added a few small carb records around 7AM in your NS. delete it if needed
