### ISSUE TITLE
Ext. Bolus still running on disconnect

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#575]
I noticed that ext. bolus is still running when disconnecting pump. Build Version is: 259C7ABF-2017.12.27 
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1595425/AndroidAPS.log)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/f5a2c5bcd2e0319991d74d7e69bfdedb5e8d66ba
thanks!
