### ISSUE TITLE
Schedule boluses

### ISSUE THREAD

**Issue by winni67** [MilosKozak/AndroidAPS#584]
Sometimes I bolus after meal, because FIASP is very fast and I‘m low with my glucose level before meal. Then I only entered the carbs in AAPS and nothing remembers me to bolus in the next 5 to 15 minutes. A notification in AAPS and on the watch would be fine. Perhaps this notification can open the „Calculator“ wizzard“ on phone or watch after confirmation. Another approach is, to enter a delay time for the bolus in the „Calculator“ wizzard.

**Comment by 2flea** [comment]
Also for the extended bolus functionality it would be very helpful to be able to schedule something starting e.g. in 1 hour.

**Comment by TebbeUbben** [comment]
You should better bolus only partially and let the algorithm handle the remaining carbs.
