### ISSUE TITLE
NSClient keeps crashing after January 5 Security Patch

### ISSUE THREAD

**Issue by switch018** [MilosKozak/AndroidAPS#591]
Follower phone (Pixel XL) keeps crashing NSClient 1.55 after latest android security patch from January 5 2018. Deleting all data and cache and reinstalling app exhibits same behavior.

**Comment by MilosKozak** [comment]
Could you download logs?

**Comment by switch018** [comment]
Sure thing,
This one is from my Nexus 6P with the security patch installed and also
exhibiting the same behavior. The follower device is the pixel XL but not
available to gather logs right now.

Thanks,
Minh
