### ISSUE TITLE
not marked  profile update

### ISSUE THREAD

**Issue by RadoslavR** [MilosKozak/AndroidAPS#594]
![screenshot_20171231-091018](https://user-images.githubusercontent.com/18197106/34757608-066cde6c-f5db-11e7-8ce1-6260349d3b90.png)
When I set duration for profile and time expires, the change not marked on the main screen

**Comment by PoweRGbg** [comment]
Actually reverting back to the previous profile is not an profile switch event, that's why it's not shown on graph

**Comment by AdrianLxM** [comment]
Can we close this?

**Comment by RadoslavR** [comment]
If you think there is no need to mark the return to 100%, then you can close it
