### ISSUE TITLE
Max IOB gets reset to 0 prematurely

### ISSUE THREAD

**Issue by mrinnetmaki** [MilosKozak/AndroidAPS#595]
It seems verifying the completion of Objective 3 (Understanding your open loop) sets `max_iob` setting to 0. This is premature. The setting should be changed only after starting Objective 4 (Starting to close the loop with Low Glucose Suspend).

**Comment by mrinnetmaki** [comment]
Some more details and context available at https://gitter.im/MilosKozak/AndroidAPS?at=5a55ab7bb48e8c3566c07bdc

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/ef2a565c18d9bf1117a9f7a82119c8f2e5b1f26e
