### ISSUE TITLE
Enforce 30m is mininum for pump unreachable alert

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#599]
With lower values and keepalive kicking in only every 15m, a 20m threshold might raise a false alarm if the active TBR did need to be adjusted for >=20m.

**Comment by AdrianLxM** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/611

**Comment by jotomo** [comment]
Done via #611, thanks @AdrianLxM !
