### ISSUE TITLE
Fix false 'pump unreachable' alerts

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#603]
With the app potentially being restarted after being backgrounded (which occasionally causes false alert on start) and oref1 doing 120m TBRs, where no communication might happen for longer periods, without this being an error I think it would be useful to rewrite the logic to not check when the last connection to the pump was, but save the first **failed** connection attempt. Reset the marker upon a successful connection and check the marker in KeepAlive. Still requires a grace period when starting (like 2m to allow a connection and not raise an alert for a problem far in the past), but should simplify the logic and removes bugs, as a connection problem is no longer inferred from the last connection timestamp.
@AdrianLxM What am I overlooking? ;-)

**Comment by AdrianLxM** [comment]
Shouldn't be the READSTATUS every 15 minutes (actually: every 5 minutes as long as the last READSTATUS is older than 15 minutes) be enough. Even if a TBR is 120 minutes?

**Comment by jotomo** [comment]
You're right, I think I misinterpreted a genuine unreachable alert.
