### ISSUE TITLE
"Approaching insulin daily limit" alarm continuous to being triggered [DanaRS]

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#609]
@AdrianLxM

**Comment by jotomo** [comment]
👍  @AdrianLxM Upvoted ;-)

**Comment by MilosKozak** [comment]
you do this for combo already?

**Comment by AdrianLxM** [comment]
@MilosKozak he was sitting next to me. It is the DanaRS driver. I'll think of something.

**Comment by AdrianLxM** [comment]
Should be fixed here: https://github.com/MilosKozak/AndroidAPS/pull/1016
Closing, further discussion in the PR.
