### ISSUE TITLE
"Wrong Pump Password" keeps repeating

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#613]
... this alarm should be limited to maybe once every minute. If it wants to do things like update the basal rates, it is unbearable.

**Comment by MilosKozak** [comment]
let's convert it to notification

**Comment by AdrianLxM** [comment]
Should be fixed here: https://github.com/MilosKozak/AndroidAPS/pull/1016
Closing, further discussion in the PR.
