### ISSUE TITLE
Possible problem with AAPS reading from Nightscout

### ISSUE THREAD

**Issue by yeagerm** [MilosKozak/AndroidAPS#615]
I am using AAPS master branch in openloop mode and noticed an  issue. Over the last two days I did two 30 min extended (“Combo”) boluses for meals. I entered the data into my Nightscout site. Looking at the Treatments tab in AAPS for these boluses, it seems that AAPS is calculating double the amount of insulin actually administered and correctly recorded in Nightscout.

![image](https://user-images.githubusercontent.com/3998204/35304422-794167b8-0063-11e8-8fc3-e24075d89cb1.png)

**Comment by yeagerm** [comment]
Also, it appears that the AAPS graph display shows the same wrong information, but I think the IOB text display seems correct.

**Comment by yeagerm** [comment]
I tried another Combo bolus- this time I entered it via the Careportal tab in AAPS and it propagated to Nightscout properly, but again Extended Bolus record in the Treatments tab is all wrong.

This time I used dev build AndroidAPS 1.57-dev Build: de7789be-2018.01.23, Nightscout version: 0.10.2-release-20171201

![image](https://user-images.githubusercontent.com/3998204/35334201-8a094d00-00df-11e8-84f4-f529f3155733.png)
![image](https://user-images.githubusercontent.com/3998204/35334210-926282c8-00df-11e8-875d-6f43529b483f.png)
![image](https://user-images.githubusercontent.com/3998204/35334215-9c3e1b90-00df-11e8-8dd4-d6c81e7fed71.png)

**Comment by st0ber** [comment]
AAPS 1.58 incorrectly displays my Extended Bolus also. I use the Medtronic 640g and the 600SeriesAndroidUploader (V0.6.1). Nightscout correctly displays the values ​​that I entered via the Medtronic 640g's Bolus Wizard.

Mongodb:
{
    "_id": {
        "$oid": "5a75e2729d8647aeb7dde812"
    },
    "carbs": 60,
    "created_at": "2018-02-03T17:20:16+01:00",
    "duration": 180,
    "enteredinsulin": "6.0",
    "eventType": "Combo Bolus",
    "key600": "BOLUS81D81CC7",
    "notes": "Square Bolus: 6.0U, duration 180 minutes : carb 60g 6.0U, {81~180} 0.0U, iob 0.2 0.0U (10g/u, isf 75/u)",
    "relative": 2,
    "splitExt": "100",
    "splitNow": "0"
}
![screenshot_20180203-190127](https://user-images.githubusercontent.com/32514747/35770267-29c19c68-0918-11e8-9622-f1bd779974d0.png)

**Comment by ekazum** [comment]
Happens also with Medtronic 640G
I fixed a related issue in 600SeriesUploader that also sent wrong values to NS, but still AndroidAPS is taking double value from NS
