### ISSUE TITLE
Basal graph rendering issue with 0% TBR

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#630]
If the graph starts with a 0% TBR, the TBR line is not rendered until a >0%TBR or regular basal occurs

**Comment by jotomo** [comment]
![graph](https://user-images.githubusercontent.com/1732305/35619949-d9421492-067f-11e8-815d-0667ea542d96.png)

**Comment by MilosKozak** [comment]
the missing line on x axis?

**Comment by jotomo** [comment]
Exactly

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/d9cfe15b875d2ea6b5d226974749274d183c2b7b
