### ISSUE TITLE
BG Graph numbers bleed off screen on Pixel 2 XL

### ISSUE THREAD

**Issue by alexandergetty** [MilosKozak/AndroidAPS#641]
I have AndroidAPS installed on my Pixel 2 XL (8.1) running in Open Loop mode and the left side of the BG graph is missing and probably needs realigning.

AAPS 1.55 Build 2018.01.29

![screenshot_20180201-173309](https://user-images.githubusercontent.com/27236266/35713245-2eff3666-077b-11e8-8910-990ca53dbe9f.png)

Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
@jotomo ? you are in mgdl too

**Comment by jotomo** [comment]
Yes, I'm using mg/dl and I'm seeing this with a High PPI phone as well. The width of the label has a fixed size. Letting the graph lib set it automatically indends the lower part of the graph twice.
I was thinking we could maybe set the width based on screen dimensions, like we do for normal/small layout, or find out why the graph lib shows that behaviour. I'll look into it when I find some time.
