### ISSUE TITLE
Basal safety multiplier can only be an integer  - problems with TBR 250%

### ISSUE THREAD

**Issue by jamorham** [MilosKozak/AndroidAPS#643]
The Insight has a max TBR of 250%

During testing, AAPS would try to set it to 300%, this would cap at 250% but then AAPS would keep trying to set it again to 300% on each cycle.

To fix this it was suggested to set `openapsama_current_basal_safety_multiplier` to `2.5` This isn't possible however as the multiplier preference is stored as an integer.

To solve this temporarily I modified around like 209 in `DetermineBasalAdapaterAMAJS.java` to say:

`mProfile.put("current_basal_safety_multiplier", Math.min((double) SP.getInt("openapsama_current_basal_safety_multiplier", 4), 2.5));`

But this is just a hack and not a proper solution.

How should this be solved? Should the preference variable be migrated to a floating point type or is there somewhere else that this can be resolved by the Insight Plugin, eg the constraints interface?

**Comment by MilosKozak** [comment]
constraints interface and limit temp basal to 250%. the rest should be handled automaticaly

**Comment by jamorham** [comment]
Okay thanks, I will test the constraints interface here and submit a PR for it.

**Comment by AdrianLxM** [comment]
any update on this?

**Comment by jamorham** [comment]
Well the constraints interface is insufficien,t but this issue is resolved in this PR afaik:

https://github.com/MilosKozak/AndroidAPS/pull/721

**Comment by AdrianLxM** [comment]
Thanks, I couldn't find it, only remembered the chat on gitter!
