### ISSUE TITLE
Should the "AndroidAPS Started" message be enabled by default?

### ISSUE THREAD

**Issue by jamorham** [MilosKozak/AndroidAPS#644]
Whenever the AAPS app is unloaded and reloaded to memory it emits a note to Nightscout which is displayed on the local graph. The frequency of this message depends on type of phone and memory pressures from other apps.

If this happens frequently then it can significantly clutter the main chart. 

Is there an operational purpose to these messages beyond observing android memory management of the app?

Should the `@string/key_ns_logappstartedevent` preference item default be set to `android:defaultValue="false"` instead? So that new users don't experience confusion relating to this message?

**Comment by MilosKozak** [comment]
lot of people don't setup android properly to not kill app on backgroud. that's why it's there this message. if you have too many AAPS started events you should solve it. once solved you can turn it off in preferences
