### ISSUE TITLE
When opening AAPS, buttons below charts appear really slowly (bolus etc)

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#667]
AAPS running on Samsung A3 (2017) using
* Dana R pump
* Dexcom G5 (patched) app
* AAPS master v1.58, but the issue has been seen in earlier versions too

When starting the application it takes a very long time before the buttons appear in the overview. Switching to another app and back, the buttons are still there, but exiting or killing the app and restarting it causes this problem. It can take up to a minute or two before the buttons appear. If this is an initialization issue, can't the AAPS looping service report that it just talked to the pump and it is in fact initialized?

Thanks in advance!

**Comment by MilosKozak** [comment]
buttons appear once profile is loaded and pump initialized (with DanaX after first connection)

**Comment by MilosKozak** [comment]
it's necessary to load limits from pump

**Comment by Mackwe** [comment]
Not to be a smartass, but since the pump is looping, is must have been initialized and all limits/basal rates etc should be loaded already. My idea of enhancement would be to add "if talkedToPump < 17 mins, assume pump is initialized and show buttons". This is not how my system works. Even looping throughout a full night, the buttons can take a minute or two minutes to show up.

**Comment by MilosKozak** [comment]
can you confirm you see on dana tab last connection time but buttons are still not there?

**Comment by Mackwe** [comment]
T1 is currently at pre-school, so can't check right now. I will have a look this afternoon. But the NSClient follower and Nightscout pump pill shows current data..

**Comment by MilosKozak** [comment]
nsclient is not affected (it uses virtual pump internaly). AAPS just needs loaded maxbolus etc values from pump ...

**Comment by Mackwe** [comment]
My thought too. But since the looping service is running, it _should_ already have all info needed from the pump? Or does my "swiping" the app off the active apps list somehow reset the background service?

**Comment by MilosKozak** [comment]
no. it's only about having all need data

**Comment by Mackwe** [comment]
OverviewFragment.java #1286 says to show buttons if "pump.isInitialized() && !pump.isSuspended()"

DanaRPlugin.java #128 defines pump.isInitialized() as "pump.lastConnection > 0 && pump.isExtendedBolusEnabled && pump.maxBasal > 0" 

Where are these parameters stored? Memory? Could it be that something is lost when "killing" the Foreground app? Or if any of these are reset to 0/false when reloading?

**Comment by Mackwe** [comment]
Maybe change OverviewFragment.java #1286 to "pump.lastConnection > 0 && !pump.isSuspended()"? I have no way of overviewing what the consequenses might be..

**Comment by jotomo** [comment]
Those things are read from the pump, they're checked to ensure the pump is properly initialized. There were some issues where `maxBasal` wasn't read properly. Do you have extended boluses disabled on the pump, is that possible (don't have a DanaR pump myself)?

**Comment by Mackwe** [comment]
@jotomo No, I use extended boluses for faking high temps, so it definitely is enabled. And everything works, it just takes a looong time from opening the app until the Bolus/Calculator buttons appear. And the loop runs fine.

**Comment by MilosKozak** [comment]
overview fragment is updated immediately when pump status is read. check `EventInitializationChanged`

**Comment by Mackwe** [comment]
@MilosKozak Yes. But I think the overview fragment loads (takes some time), waits for 5000ms and then tried to connect to the pump (which takes time). My idea of improvement was to re-use the last connection made by the background service to determine if pump.isInitialized(). That would speed up things a lot (and save system resources too).

**Comment by jotomo** [comment]
I think the core problem is then that AAPS is restarted frequently, which it shouldn't. Check battery optimization is disabled.

**Comment by MilosKozak** [comment]
pump status is held in memory until app is closed or crashed

**Comment by Mackwe** [comment]
@jotomo : The issue only occurs when I start AAPS. If I leave the foreground app running, it works. If i switch to another app and back it works. I am not saying this is a big issue. It only happens when I close the foreground app ("swiping" it off the app list, leaving the background service running) and then open the foreground app again. It may be a minor issue on the whole, but I tend to run into it several times a day..

@MilosKozak Does closing the foreground app (leaving the background service on) count as closing it?

**Comment by MilosKozak** [comment]
if you switch to another app AAPS is still running on background

**Comment by Mackwe** [comment]
@MilosKozak And if i "swipe it" from the running apps list? I know the background service is still running, but would that count as "closed" and reset pump.isInitialized()?

**Comment by jotomo** [comment]
From what I've learned about Android so far, I'd say the system interprets the 'swipe left/right' as a hint that the user isn't currently interested in the app, so that the system can kill it at will, thus Android may kill AAPS (happens on my system about 5s after swiping the app away). The only way (I know off) to ensure an app is not killed is to register a foreground service through a notification. I have the "Ongoing Notification" plugin enabled which does exactly that, should work for you too. Or don't swipe AAPS away ;-)

**Comment by Mackwe** [comment]
@jotomo Sounds reasonable. I can see the logic in that. I do have a persistent notification on in the app, but suppressed in Android not allowing notifications from AAPS. That might be the issue then. Will check! Thank you!!  (Swiping the apps away is so rooted in me, I simply can't help myself..)

**Comment by Mackwe** [comment]
Tried all things above now. Video to illustrate it. Choosing "Dana" and "Refresh" current profile works. Then it becomes initialized, and the buttons appear. As the video shows, it takes ~100 secs to initialize the pump (and this is normal, no video re-takes). Warning; Video clip is 80Mb, so please don't download if you're on a pay-per-usage connection. https://www.dropbox.com/s/dil46rqfx6kadit/VID_20180212_191834.mp4?dl=0 And as you suggested, if the app is left in the background, it all works. So it's no big deal. Just very annoying if you, like me, always "swipe" all apps when done using the phone..

**Comment by MilosKozak** [comment]
do you have OLD firmware?

**Comment by Mackwe** [comment]
@MilosKozak Yes. I do unfortunately.

**Comment by MilosKozak** [comment]
with old firmware, initial connection has to be done twice. maybe that's your issue

**Comment by Mackwe** [comment]
Probably. But then again, the background service is still looping with an initialized pump.. I don't feel like nagging and if you wish to close this issue that's okay. I was just hoping there could be a simple solution to a simple problem.

**Comment by MilosKozak** [comment]
i'm not 100% sure but i think when you kill app, background services are killed too. AAPS wakes up again on next BG.
@AdrianLxM
