### ISSUE TITLE
Multiple loop invocations using xDrip as source and uploader to Nightscout, when NSClient is enabled

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#671]
When xDrip is used as a source for SGVs (receiving local broadcasts) and xDrip is also configured to upload SGVs to Nightscout, while AAPS uses NSClient the following happens:
AAPS receives the new SGV locally from xDrip, fires `EventNewBg`, which triggers IOB & COB calculations, which in turn trigger a loop run. xDrip uploads the SGV and NSClient receives that SGV shortly after. The existing SGV (received from xDrip) is updated with the record received via NSClient and `EventNewBg` is fired again, triggering the above again, 5-10s after the first run. 

Should the loop be invoked by SGV data coming in from a different source than what is configured as "BG source"?

**Comment by jotomo** [comment]
Same solution as with #694 via https://github.com/MilosKozak/AndroidAPS/commit/e9313c5b2849a646ca703b08bce32abae4f8bb8d.

**Comment by jotomo** [comment]
Not sure yet how to do this exactly (updating UI etc without triggering the loop), other than embedding the source in EventNewBg so that LoopPlugin can check if the BG comes from the active BG source. Should also check the retrieved BG is not older than 5m or so, so it won't trigger a loop run when retrieving back-filled data.

**Comment by MilosKozak** [comment]
I was thinking about recording bg time from last EventNewBg . what do you think?

**Comment by jotomo** [comment]
... local state that is lost on restart (negligible), but other plugins also need to differentiate between backfilled BGs and new BGs.
I like the straightforwardness of an Event providing the data needed to make an informed decision, hence my counter-proposal :-) : 
https://github.com/MilosKozak/AndroidAPS/compare/dev...jotomo:new-bg-processing?expand=1

**Comment by MilosKozak** [comment]
why not. make PR

**Comment by jotomo** [comment]
@MilosKozak I should have just listened to you ;-) #906
