### ISSUE TITLE
Unsupported version of Nighscout

### ISSUE THREAD

**Issue by tuzoenduro** [MilosKozak/AndroidAPS#672]
Hi,

Just updated Nighstcout to the latest Nightscout version via GitHub, also on the latest 0.6.1 version for the MM600 series app from Lennard.

Installed the Full AndroidAPS apk, although I only do an open loop.

androidAPS keeps saying that I'm running an unsupported version of Nighscout and don't know what to do? I mostly run offline, but whenever I connect to a wifi I get the message "Nightscout version not supported" again.

I have a MM640g, an S5 and no clue how to correct this.

Thanks!!

Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by tuzoenduro** [comment]
build b9b99917-2018.02.07 nightscout version 0.9.0-beta3

**Comment by AdrianLxM** [comment]
glad you found the problem. Update to 0.10.2

**Comment by tuzoenduro** [comment]
I checked my nightscout and it IS 0.10.2.... but androidaps is not reading it like this?

**Comment by tuzoenduro** [comment]
![ns-todate](https://user-images.githubusercontent.com/16446908/35914588-0db48334-0c04-11e8-8872-ba4c0c6bc01f.jpg)

**Comment by tuzoenduro** [comment]
@AdrianLxM if you have any ideas I'm all ears... 
I checked my nightscout and the page is up to date. Could I have somehow wrongly generated the APK? 
Thanks

**Comment by AdrianLxM** [comment]
You stated, your nightscout version is 0.9.0-beta3 that's an old one.
It does not count what is in github, but what is deployed ot your server.

**Comment by tuzoenduro** [comment]
ahhh, been a long time, did not know why I thought merging my github version would update also what is on the server.. got to check that.. thanks

**Comment by tuzoenduro** [comment]
Ok, works now thanks @AdrianLxM ... I had a little scare since the deployment would not work, had to redeploy about 5 times but it is all good now...

Thanks again
