### ISSUE TITLE
SMBs not delivered on DanaR

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#681]
Problem: SMB of 0.4 units gets issued, delivered only 0.0.
**This happened multiple times, afair over an hour - only a phone restart fixed it**

Here the combination of TBR and SMB gets issued
```
21:32:14.908 [Thread-3213] DEBUG [info.nightscout.androidaps.plugins.ConfigBuilder.ConfigBuilderPlugin:382]: applyAPSRequest: Rate: 0.00 U/h (0.00%) 
Duration: 30.00 min
SMB: 0.40 U
Reason: COB: 63.77024083689827, Dev: 46, BGI: -4, ISF: 47, CR: 8.36, Target: 100, minPredBG 226, minGuardBG 166, IOBpredBG 79, COBpredBG 370;  insulinReq 2.71; maxBolus 0.4; setting 30m low temp of 0U/h. Microbolusing 0.4U. 
```

...

And here the result in the QUEUE is "OK" but only 0.0 of 0.4 was given.
```
21:32:19.906 [Thread-3214] DEBUG [info.nightscout.androidaps.queue.commands.CommandTempBasalAbsolute:35]: setTempBasalAbsolute rate: 0.0 durationInMinutes: 30 success: true enacted: true
21:32:20.011 [Thread-3214] DEBUG [info.nightscout.androidaps.queue.QueueThread:120]: QUEUE: performing SMBBOLUS 0.4U
21:32:20.014 [Thread-3214] DEBUG [info.nightscout.androidaps.plugins.PumpDanaR.DanaRPlugin:145]: deliverTreatment: OK. Asked: 0.4 Delivered: 0.0
```

As SMB or replace basal insulin and TBRs are scheduled as if SMB would work, this is a rather bad situation. (ALARM?)

Full log:
[AndroidAPS._2018-02-09_22-07-46_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1713883/AndroidAPS._2018-02-09_22-07-46_.0.zip)

**Comment by AdrianLxM** [comment]
Disregarding the problem **WHY** delivering a treatment failed (@MilosKozak it would be nice if you could find a reason for that), there are a few more questions:

* Is it good to add to treatment even if the `result.success` is `false`
* With SMB we can no longer disregard if one of the two actions that are issued simultaneously failes and one has success. Only if both fail, we are in the failsafe state "plain old insulin pump delivering basal insulin".

**Comment by jotomo** [comment]
Related to your second point: we currently consider a TBR set if the same rate is running on the pump, with at least 5m remaining. With SMBs having delivered the insulin for up to 2h upfront, we might end up with a 0% TBR of just 10 min, which would deliver too much insulin if connection broke down. So maybe not extend a TBR every 5m, but maybe set a TBR anew if the requested time is >= 60 min and less than half of it it is remaining (or something like that).

**Comment by MilosKozak** [comment]
i'll update setting TBR for danas to reflect duration. and maybe set TBR every for RS where is not a battery issue.
i'll take care about splitting TBR and SMB too

**Comment by Rol71** [comment]
I also often have problems with undelivered SMB. Last time this morning.

![screenshot_2018-03-13-05-22-06](https://user-images.githubusercontent.com/28503031/37337904-00468b6c-26b6-11e8-8d26-a391fc0bb9d2.png)

Log: 
[AndroidAPS_2018-03-13_05-24-01.log](https://github.com/MilosKozak/AndroidAPS/files/1806600/AndroidAPS_2018-03-13_05-24-01.log)

**Comment by AdrianLxM** [comment]
Small update: https://github.com/MilosKozak/AndroidAPS/commit/c27ceb0a72907a7af70752c34799f8f4c54a18d6

... should now return false as success.

enacting the loop result atm looks like this:
```
                    MainApp.getConfigBuilder().applyTBRRequest(resultAfterConstraints, profile, new Callback() {
                        @Override
                        public void run() {
                            if (result.enacted || result.success) {
                                lastRun.tbrSetByPump = result;
                                lastRun.lastEnact = lastRun.lastAPSRun;
                            }
                            MainApp.bus().post(new EventLoopUpdateGui());
                        }
                    });
                    MainApp.getConfigBuilder().applySMBRequest(resultAfterConstraints, new Callback() {
                        @Override
                        public void run() {
                            if (result.enacted || result.success) {
                                lastRun.smbSetByPump = result;
                                lastRun.lastEnact = lastRun.lastAPSRun;
                            }
                            MainApp.bus().post(new EventLoopUpdateGui());
                        }
                    });
```

So I would propose the following changes:
1. Put the `applySMBRequest` in the callback of `applyTBRRequest` and only call it on success. This way we ensure that the SMB only gets delivered if the appropriate TBR gets set (safety in case of future connection loss)
2. If SMB delivery fails, re-trigger loop with a flag to disable all SMB/UAM. This way a TBR will get set that does not rely on SMB being delivered (often TBR=0 when expected to have SMB).

@jotomo @MilosKozak, what do you think?

**Comment by AdrianLxM** [comment]
#925 is the fallback.
