### ISSUE TITLE
SMB profile shows min_5m_carbimpact=0

### ISSUE THREAD

**Issue by ceben80** [MilosKozak/AndroidAPS#693]
I'm running SMB but `min_5m_carbimpact` is shown as `0` in the profile although it's defined in `SMBDefaults.java` with `8`

https://github.com/MilosKozak/AndroidAPS/blob/bf6e3a9061d1c9a49e03798dc80edf31bbcb6b8f/app/src/main/java/info/nightscout/androidaps/plugins/OpenAPSSMB/SMBDefaults.java#L43

![image](https://user-images.githubusercontent.com/12679825/36338696-22c1dfb0-13b6-11e8-9a96-8930d845667b.png)

**Comment by PoweRGbg** [comment]
Probably "min_5m_carbimpact" in your Settings is set to 0. SMBDefaults are default settings but not absolute.

**Comment by ceben80** [comment]
No, not set to zero

**Comment by RadoslavR** [comment]
Where are these settings?

**Comment by PoweRGbg** [comment]
![screenshot_1520001724](https://user-images.githubusercontent.com/21143443/36904155-9084e68c-1e38-11e8-8d41-2723a579bd66.png)

**Comment by RadoslavR** [comment]
I had chosen a weighted average and did not appear there. Is it not just about the autosense?

**Comment by ceben80** [comment]
afaik only hardcoded with the value 8

**Comment by PoweRGbg** [comment]
`        mProfile.put("min_5m_carbimpact", SP.getInt("openapsama_min_5m_carbimpact", SMBDefaults.min_5m_carbimpact));;`
that's on line 244 of https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/OpenAPSSMB/DetermineBasalAdapterSMBJS.java 
So it checks if there is such value in settings, and if not assigns the one in SMBDefaults(8)

**Comment by ceben80** [comment]
yes you're right, found this code line as well but the above screenshot shows zero, but nevertheless I am back at AMA ;)

**Comment by AdrianLxM** [comment]
@ceben80, what sensitivity model so you use?

The AAPS and WeightedAverage does not expose this setting but calculates it "dynamically". We need to make sure it is set to a correct value and synchronize those.

**Comment by AdrianLxM** [comment]
For what it's worth: this parameter is added to the profile, but never gets used. So it does not affect the logic in any ways.

**Comment by ceben80** [comment]
was using AAPS

**Comment by AdrianLxM** [comment]
mostly fixed in: https://github.com/MilosKozak/AndroidAPS/pull/730

Still the setting needs to be exposed for those using AAPS/WeightedAverage as parameter.

**Comment by ceben80** [comment]
I've been merging SMB again and now the "Zero issue" looks good to me (s. the underneath line in yellow)

![image](https://user-images.githubusercontent.com/12679825/36931959-bcf105be-1ec1-11e8-89c9-a4c03d10251e.png)
