### ISSUE TITLE
AAPS takes every value if  xDrip and Dexcom app mod are used at the same time

### ISSUE THREAD

**Issue by RadoslavR** [MilosKozak/AndroidAPS#694]
I use two transmitters with xdrip and DexcomG5 App patched. But AAPS takes every value from these two transmitters. 
I made these settings:
in AAPS - BG Source - DexcomG5 App patched
in xDrip - Broadcast locally is disabled
in AAPS - NS upload only (disabled sync) is on
in AAPS - Send BG data to xDrip+ is off
[AndroidAPS._2018-02-17_03-43-43_.2.txt](https://github.com/MilosKozak/AndroidAPS/files/1733667/AndroidAPS._2018-02-17_03-43-43_.2.txt)
![screenshot_20180217-110516](https://user-images.githubusercontent.com/18197106/36341154-7d3f31e0-13f2-11e8-8161-a9f498385536.png)

**Comment by jotomo** [comment]
Does xDrip upload SGVs to Nightscout?
From a quick look at the log, one reading is received at timestamp 08:17:20.509, which seems to come in again via Nightscout a few seconds later, at 08:17:24.980.
Sounds rather similar to the issue I had: https://github.com/MilosKozak/AndroidAPS/issues/671
See if pausing NSClient stops this behaviour.

**Comment by RadoslavR** [comment]
I wanted to compare the data from the two applications on NS site. xdrip was uploading to Nightscout, but I had chosen  NS upload only . I have tried many things and  I have more log files afther that, but since I got pretty low levels of BG due to incorrect data I stopped this experiment

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/e9313c5b2849a646ca703b08bce32abae4f8bb8d
