### ISSUE TITLE
Combo clean up tasks

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#696]
- [x] Remove CommandQueue.setProfile hack for initial profile switch
- [x] Properly fix QueueCommandTest.
- [x] (maybe) Integrate fragment history actions with queue and enable them
- [x] Switch Answer calls to FabricPrivacy.
- [x] Add to pumpdescription: `pumpDescription.tempDurationStep15mAllowed = true;
        pumpDescription.tempDurationStep30mAllowed = true;`
- [x] Produce a _Treatment_ object in _ComboPlugin.deliverTreatment_, when dispatching _EventOverviewBolusProgress_ (_isSMB_ flag is needed to suppress notifications on watch). #732 
- [x] #715

**Comment by MilosKozak** [comment]
@jotomo what is the last task?

**Comment by jotomo** [comment]
@MilosKozak Last open point is  about reading TDD and error history. TDD is now done via _CommandLoadTDDs_ thans to Adrian, but error history is still open. Currently, the Combo foregoes the queue to read that. I was pondering adding a generic _CommandCustom_ that would allow to run an arbitrary callback as part of the queue. That would allow pump drivers to run driver-specific stuff cleanly ...
