### ISSUE TITLE
AAPS shows 0% temp, but extended bolus with 3.1 is running

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#718]
AAPS is showing a zero temp, but on pump is running a extended bolus with 3.1 units.
Using dev from yesterday evening (22.02.) with the quickfix for Insight Plugin.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1753013/AndroidAPS.log)

**Comment by MilosKozak** [comment]
sorry i need more details, screenshots etc. there is nothing releant in log.
closing for now. please reopen if you will be able to reproduce this bug
