### ISSUE TITLE
SMB: Do we need DIA as parameter?

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#725]
`profile.dia` is no longer used in `determine_basal` itself (@scottleibrand it would be nice if you could confirm that).

Should we stop adding it to the `profile` parameter in AAPS? Opinions?

**Comment by scottleibrand** [comment]
DIA is still used in IOB calculations.

**Comment by AdrianLxM** [comment]
@scottleibrand I was just referring to `determine_basal`. It gets the IOB precalculated as parameter as well.

**Comment by scottleibrand** [comment]
Ok.  Is there any advantage to not passing it around if we still have to have it in the profile GUI etc?  Not sure if we'll end up using it in future or not, but if there's a good reason to remove from the data passed to determine-basal it I think that'd be ok.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/8219332a2cca41c6a6a37cb2af765c39adfd5023
