### ISSUE TITLE
AndroidAPS 1.58 shows "OLD" as firmware version in Dana R page

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#731]
AndroidAPS 1.58 (master) usually doesn't show the correct firmware version in the Dana R page. The pump is a new Dana R (I received it 02/07/2018).

After unpairing and pairing the pump, the version string (Model: 03 Protokoll: 03 Code B2) is shown in the Dana R page. At some time later this is replaced by OLD and the version string doesn't appear again until the pump is unpaired/paired again.
![screenshot_20180302-145014 1](https://user-images.githubusercontent.com/1267238/36932704-807689d6-1ecd-11e8-887d-734f6f7ba407.png)

**Comment by MilosKozak** [comment]
solved (hopefully) by https://github.com/MilosKozak/AndroidAPS/commit/4ff09a0125b4698ac4afe7099e88c559368bcaca
