### ISSUE TITLE
Automatically disable superboluses in the bolus wizard if SMB is selected

### ISSUE THREAD

**Issue by TebbeUbben** [MilosKozak/AndroidAPS#739]
This should be done as SMB already includes an improved version.

**Comment by MilosKozak** [comment]
could you be more detailed?

**Comment by TebbeUbben** [comment]
When using SMB, it will zero-temp when eating carbs and will slowly deliver the basal of the next two hours  as SMBs. This is actually a superbolus and as SMB already cares about that, the user shouldn't be able to issue a superbolus using the bolus wizard.

**Comment by MilosKozak** [comment]
why? IOB delivered by SMB will be added into wizard calculation along with zero TBR IOB

**Comment by TebbeUbben** [comment]
Doesn't SMB also keep track of upcoming glucose values and decides whether a superbolus would be useful or not? I thought, that this is one of SMBs main goals?

**Comment by MilosKozak** [comment]
SMB is borrowing insulin from the future (principle of superbolus).
but any situation can be (and is ) evaluated be wizard. So any previous SMBs will be added to IOB together with zero temps properly.

On the oposite side when you deliver superbolus from wizard, loop is stopped for next 2 hours at all

**Comment by MilosKozak** [comment]
@TebbeUbben what with this issue?

**Comment by TebbeUbben** [comment]
It's up to you :)

**Comment by MilosKozak** [comment]
closing as during superbolus loop is disabled at all
