### ISSUE TITLE
"current" in UAM prediction

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#742]
https://github.com/openaps/oref0/blob/master/lib/determine-basal/cob.js#L143...L168

Bucketed data must be sorted anti-chronologically.
Example:  a delta is calculated "new - old". In the sourcecode: `delta = (bg - bucketed_data[i+1].glucose);` with `bg = bucketed_data[i].glucose;` -> `bucketed_data[i]` must be newer than `bucketed_data[i+1]`.

Therefore from
```
        if (i==0) {
            currentDeviation = Math.round((avgDelta-bgi)*1000)/1000;
....
        }
```
follows that `currentDeviation` must be the most recent one.

*** Probable bug 1:***
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/IobCobCalculator/IobCobThread.java#L159
AndroidAPS on the other hand uses the deviation from one hour ago as "current" one:
`currentDeviation = hourAgoData.avgDeviation;`

*** Probable bug 2: ***
https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/IobCobCalculator/IobCobThread.java#L155
```
if (i < bucketed_data.size() - 16) { // we need 1h of data to calculate minDeviationSlope
```
... should guaranty that there is at least one hour of data, but in the for loop might calculate the same over and over again for each bucketed data that is newer than the 16th oldest. For 24 hours + 1 DIA of data, it might calculate the deviation slopes (23+DIA)*12 times? We only use the last one so this should not lead to wrong results, but older values are overwritten and/or calculated without need.

**Comment by AdrianLxM** [comment]
And coincidentially a few hours later a report in the german fb group:

On a high delta (tick is +10) ***with uam*** it recommends a low-temp
![uam2](https://user-images.githubusercontent.com/9692866/37208423-ac1436fa-23a1-11e8-85ce-55a9dad124d0.jpg)

In the same situation ***without uam*** it recommends a neutral-temp (would even go higher if it wasn't IOB restricted):
![uam1](https://user-images.githubusercontent.com/9692866/37208424-ac32fe1e-23a1-11e8-8745-4885d19b755b.jpg)

Apart from the calculation I believe we also need to take a look at the exclusion after a meal with bolus.

**Comment by MilosKozak** [comment]
`bucketed_data` has newest at index 0

**Comment by MilosKozak** [comment]
addressed 2 bugs. thx @AdrianLxM 
https://github.com/MilosKozak/AndroidAPS/commit/e134b94f13fba7ccc576a472849b0aa71503f26b

**Comment by AdrianLxM** [comment]
Thanks Milos. It looks like that the calculation part is fixed. :+1: 
The remaining meal absorptions issues I have bundled here: https://github.com/MilosKozak/AndroidAPS/issues/817
