### ISSUE TITLE
Related to closed issues #683 and #608: higher increasement of maxIOB for insulin resistant adults

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#752]
For the new SMB function the maxIOB value was increased to 12u (issue #683). I think that will be too low for people who are insulin resistant adults (issue #608). In my case, a bolus of 18u unfortunately is not uncommon. I think a special "maxIOB for resistant people" should be much higher than 12u, in my case around 22u maybe.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/30d12622f7369d4de6d0223ccccf4447c3f54c35

**Comment by typ1-brods** [comment]
Thank you so much 👍
