### ISSUE TITLE
"Ignore profile switches" sends changed basal profile to pump.

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#757]
When the option "Ignore profile switches" is set, and the active profile is adjusted (percentage/timeshift), the adjusted profile is sent to the pump (and the profile viewer shows it, but not the top bar on the home screen). When the next keep-alive is triggered, the adjustment is reverted.
With the option set, adjustments should be ignored as well, no?
Or maybe remove the option? Could that maybe simplify things, for devs and users?

**Comment by AdrianLxM** [comment]
I'm definitely in favour of removing this option.

Profile-Switches will get sent to the pump... but the profile is used. That's a very inconsistent state.

We then can also disable the fuction that a new Profile-Store form Nightscout will trigger writing to the pump and only do this on Profile-Switches.

**Comment by MilosKozak** [comment]
the goal of this option (not finished in history viewer yet) is to be able model AAPS behavior with different profile setting. Once you start using switches it's not possible without this option anymore.

I agree that this makes things more complicated.
If you don't have easy solution we should remove this option to prevent too much troubles in the future
