### ISSUE TITLE
Feature Request: Little changes around main screen (Overview)

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#763]
I am proposing few changes on Overview that could be beneficial for everybody.

1. Adding 4th button on lower edge called Config (or perhaps putting all following settings in main configuration), which would open small dialog for those checkboxes (Bas, Iob, Cob, Dev, ...) and configuration if other buttons could be seen Bolus, Calculator and Calibration (I for example always calibrate in Xdrip so for my that button is not needed)

2. On left side of Basal, IOB, COB text, icon showing status of pump communication (OK, Error)

3. On right side icon that is either visible or not, displaying Bluetooth symbol, when we are communicating with Pump.

**Comment by MilosKozak** [comment]
1. it's already configurable in preferences

**Comment by jotomo** [comment]
2./3. Combo doesn't trigger the green bars (indicating connection status and activity). It's all on the combo tab though. Aside from debugging issues, the connection state is IMHO pretty uninteresting.

**Comment by andyrozman** [comment]
2/3. It would help to know, before I click on Bolus/Calculator, if communication with Pump is working ok. I haven't checked it everytime today when I tried to give a bolus, so I had two failed boluses, that I had to retry after I got system back working.
1. What is already configurable?

**Comment by jotomo** [comment]
1. in next release it will be configurable which buttons are shown at the bottom
2. connection is closed between requests, failures to connect to pump can occur on every connect, so there is no way to determine if pump will react. if pump can't be reached frequently (which you seem to be getting) your phone isn't suited to work well with the Combo. That's not something AAPS should or even can work around.

**Comment by andyrozman** [comment]
1. Will it be also merged to combo branch?
2. Yes I know that. But in case that previous connection fails, that could be indicated on first page. (or red indicator on tab or something). My phone worked fine first 3 days, today it was starting to get little bit temperamental.

**Comment by AdrianLxM** [comment]
The checkboxes are in.

**Comment by AdrianLxM** [comment]
Connection loss can happen - mostly when you walk away from the pump. There is now an alarm when no connection is possible in a while. Also there is enhanced recovery logic if only a microboli or tbr does not come through.
