### ISSUE TITLE
Closed loop not running

### ISSUE THREAD

**Issue by infoneo** [MilosKozak/AndroidAPS#783]
After commit ad3bf19e4c2857d93f59614de3d8aeb8448d78bb (after change in the /plugins/IobCobCalculator/IobCobCalculatorPlugin.java - onEventNewBG function) loop is not starting automatically (only manually). I use xDrip + G5 with replaced batteries.

**Comment by jotomo** [comment]
Try to pause NSClient.
It seems the SGV from NS is processed first, but doesn't trigger the loop since it's not the active BG source, and when processing the original xDrip value next, the existing SGV is only updated, not triggering a loop run either (only new values do).
Duplicate of #782

**Comment by McHoffi** [comment]
When pausing NSClient it is working normally.

**Comment by jotomo** [comment]
@infoneo @McHoffi @swissalpine Fix ready for testing: https://github.com/MilosKozak/AndroidAPS/pull/786

**Comment by McHoffi** [comment]
Not working for me, still not enacted.
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1830344/AndroidAPS.log)

**Comment by infoneo** [comment]
For me, the fix has resolved problem - the loop is enacted periodically.

**Comment by jotomo** [comment]
@infoneo @McHoffi @swissalpine Thanks for testing! The proposed fix won't work in all scenarios. I've reverted the initial commit causing this issue (see https://github.com/MilosKozak/AndroidAPS/pull/787).

**Comment by infoneo** [comment]
Thanks!
