### ISSUE TITLE
Extended bolus not showing up in Nightscout correctly

### ISSUE THREAD

**Issue by nathanscrivener** [MilosKozak/AndroidAPS#790]
Affects:

Build 1.58 master
Also Dev build from 2 March 2018.

You can see on screenshot from AndroidAPS that extended bolus is 0.37u/hour. Total extra insulin is 2.2 units over 360 minutes. 

In Nightscout the basal pill shows C:2.930u. It says 2.2u/hr. That is incorrect as it has taken the total insulin over 6 hours and thinks that amount per hour is being delivered.

![img_7073](https://user-images.githubusercontent.com/35670110/37697199-58e4683a-2d40-11e8-844a-0919a6d282c8.PNG)
![img_7074](https://user-images.githubusercontent.com/35670110/37697201-592cdcdc-2d40-11e8-9470-d3c2be786309.JPG)

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/cb4b11715286ff64bab81e203e9ffed1130d0717
