### ISSUE TITLE
Crash on profile switch

### ISSUE THREAD

**Issue by TebbeUbben** [MilosKozak/AndroidAPS#792]
AndroidAPS crashes when I do a profile switch. Here's the stack trace: https://gist.github.com/TebbeUbben/9d9ee16c1df2b7bdcc18bb68a2642ccd

Build version (dev): 272fdb47-2018.03.22

**Comment by triplem** [comment]
Do you use NS? If so, could you try to delete all Profile Switches from NS and set one at a time before usage of AndroidAPS (eg. 1.3.2018). This at least worked for me.
