### ISSUE TITLE
Crash after NS profile change 

### ISSUE THREAD

**Issue by osodebailar** [MilosKozak/AndroidAPS#794]
Version: 1.60-dev Build 272fdb47-2018.03.21
Nightscout Version: 0.10.2-release-20171201

Behavior:

- Change ISF value in Nightscout profile named 'Opt7' via webbrowser .
- make a profile switch in main dialog to the same profile 'Opt7'
AAPS crash see log file at 06:07
- After the crash AAPS crashes again at 06:20
[AndroidAPS._2018-03-23_06-20-10_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1840456/AndroidAPS._2018-03-23_06-20-10_.0.zip)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1840457/AndroidAPS.log)

Logs attached

Greetings
Andi

Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by MilosKozak** [comment]
there are wrong formated data comming from NS. Any idea how this happened?
```
 {
    "_id": "dcfa4875f93949b9891995bf",
    "timestamp": 1519047216000,
    "eventType": "Profile Switch",
    "enteredBy": "AndroidAPS",
    "uuid": "dcfa4875-f939-49b9-8919-95bfc719103c",
    "created_at": "2018-02-19T13:33:36Z",
    "sysTime": "2018-02-19T14:33:36.000+0100",
    "mills": 1519047216000,
    "mgdl": 102
}
{
    "_id": "c92b546de9204112803a85e1",
    "timestamp": 1519060090000,
    "eventType": "Profile Switch",
    "enteredBy": "AndroidAPS",
    "uuid": "c92b546d-e920-4112-803a-85e119795051",
    "created_at": "2018-02-19T17:08:10Z",
    "sysTime": "2018-02-19T18:08:10.000+0100",
    "mills": 1519060090000,
    "mgdl": 102
}
```

**Comment by osodebailar** [comment]
From My side no idea.
I switch the profile often in the week to adapt parameters . 
It is the first time that this happens .
The Nightscout server is hosted by ns.10.be.de from Martin Schiftan
https://www.facebook.com/664242075

Maybe he has an idea

**Comment by MilosKozak** [comment]
try 1.60a-dev

**Comment by osodebailar** [comment]
Thx . If I am at home i compile to 1.60a and test against it .
