### ISSUE TITLE
Feature proposal: Button/suspend/resume - pump (loop+basal)

### ISSUE THREAD

**Issue by infoneo** [MilosKozak/AndroidAPS#796]
I have proposal - adding separate button on home screen or action panel "suspend/resume pump"

At least once per day it is necessary to disconnect the pump from body - shower/bath/sex etc. During such periods there is a need to (from aaps) suspend looping and setting pump basal to zero.
  
It would be nice to have separate button for such situations.

Moreover sometimes there is a need to suspend looping (and keeping pump basals on) - for example we see, that CGM measurements are not accurate (noisy).

It would be nice that suspend panel has following checkboxes

[x] zero temp
[x] suspend loop
suspend period [min]

Button: [Suspend/Resume]

**Comment by MasterPlexus** [comment]
Just press longer on the main screen on the blue closed loop button and enjoy ;)
So the function is there, but not as a separate button.
