### ISSUE TITLE
AAPS crashing

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#801]
AAPS is still crashing, tried also different versions, it is current dev can't access the accurate build.
Tell me if something other is needed.

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1844212/AndroidAPS.log)
[logcat.txt](https://github.com/MilosKozak/AndroidAPS/files/1844213/logcat.txt)

**Comment by McHoffi** [comment]
Also AAPS won't get the BG values, because it is always crashing

**Comment by AdrianLxM** [comment]
@MilosKozak from the logcat it is https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/plugins/IobCobCalculator/IobCobThread.java#L156 

`autosensDataTable.valueAt(initialIndex + past);` returning null? (deviation slope calculation).
Can this happen if no valeus are in for the last period of time?

**Comment by jotomo** [comment]
@AdrianLxM From what I've seen, NPEs at that location cause crashes when a profile switch is happening at the same time when IobCob calculations run...

**Comment by AdrianLxM** [comment]
@McHoffi did you do any Profile switch at that time?

**Comment by MilosKozak** [comment]
1.60b still?

**Comment by McHoffi** [comment]
Haven't updated yet, uninstalled the app and did a fresh install, and since then it didn't happen again. Is there anyway I could then try if it will crash again?
