### ISSUE TITLE
Loop not triggered for hours

### ISSUE THREAD

**Issue by PoweRGbg** [MilosKozak/AndroidAPS#803]
in 1.60-dev Loop-APS is not running for hours. BG is coming from xDrip+ but APS don't run and
doesn't request anything
![screenshot_20180324-012125_androidaps](https://user-images.githubusercontent.com/21143443/37863216-4c2119c0-2f63-11e8-994b-4260d7104412.jpg)
![screenshot_20180324-125151_androidaps](https://user-images.githubusercontent.com/21143443/37863218-4c3f0142-2f63-11e8-8e98-706f768b18a6.jpg)
![screenshot_20180324-125156_androidaps](https://user-images.githubusercontent.com/21143443/37863221-4c5c46e4-2f63-11e8-8e2e-733698529bf7.jpg)
![screenshot_20180324-125204_androidaps](https://user-images.githubusercontent.com/21143443/37863223-4c7b9404-2f63-11e8-9123-8232ba0d2fa7.jpg)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1844295/AndroidAPS.log)

**Comment by jotomo** [comment]
Looks like a dup of https://github.com/MilosKozak/AndroidAPS/issues/783

**Comment by PoweRGbg** [comment]
ok -- updating to see if the fix works. 
Thanks
