### ISSUE TITLE
Carbs on board miscalculation causes erroneous high temping

### ISSUE THREAD

**Issue by philipgo** [MilosKozak/AndroidAPS#804]
[Moto G5, SW3, XDrip+ with G5, Combo, AAPS combo branch 0fde2a67-2018.03.20)

We just encountered a serious error due to erroneous (too high) COB calculation.

We entered 45g of carbs at 09:46. These were the first carbs of the day, COB had been 0 for many hours. Carbs were entered on the phone, the watch was not used. Immediately afterwards COB was shown as 80g, then jumped to the correct amount of 45g.

As can be seen from the logs, at 09:51 COB was again wrongly calculated as 88,75g. It seems as if the 45g were doubled. From then on COB was calculated much too high causing high temping. The entries in treatments are correct (only 45g once), nothing was changed or corrected, there was only this one carb entry at the time.

There were a few missed CGM readings between 10:26 and 11:05, but the error occured before that.

The wrong COB calculation led to high temping and made a carb correction necessary.
[AndroidAPS._2018-03-24_00-00-06_.log](https://github.com/MilosKozak/AndroidAPS/files/1844311/AndroidAPS._2018-03-24_00-00-06_.log)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1844312/AndroidAPS.log)
![screenshot_20180324-112947](https://user-images.githubusercontent.com/29184757/37863480-cbf88944-2f5e-11e8-8180-7138554bf749.png)
![screenshot_20180324-112923](https://user-images.githubusercontent.com/29184757/37863485-cd106ac2-2f5e-11e8-892e-827dbce0865c.png)

**Comment by drnoname82** [comment]
At 12:35 I terminated AAPS and restarted it. COB was immediately calculated correctly as 1g, but then jumped back to 35g. (I did not enter the carb correction to avoid further high temping)

**Comment by AdrianLxM** [comment]
Could you please activate COB for the screenshot?

**Comment by AdrianLxM** [comment]
And do you please have a screenshot of the treatments tab?

**Comment by drnoname82** [comment]
Something is really off here, now COB is 28g again. I repeatedly check the Treatments tab after the error occured. There never was a duplicate entry.
![screenshot_20180324-130649](https://user-images.githubusercontent.com/29184757/37863814-e3a6f2dc-2f64-11e8-854f-207776b46d77.png)
![screenshot_20180324-130558](https://user-images.githubusercontent.com/29184757/37863815-e3c4b93e-2f64-11e8-9792-47f9edbeab0f.png)

**Comment by MilosKozak** [comment]
@AdrianLxM code is correct adding synchronized to treatments too

**Comment by MilosKozak** [comment]
should be fixed in dev branch. reopen if needed
