### ISSUE TITLE
Deactivate APS for time of Daylight Saving Time change  (TT +SMB = many microboluses)

### ISSUE THREAD

**Issue by RadoslavR** [MilosKozak/AndroidAPS#805]
![screenshot_20180325-060218 1](https://user-images.githubusercontent.com/18197106/37871313-f9793266-2ff3-11e8-97bc-08a1f52043f5.png)
![screenshot_20180325-055856 1](https://user-images.githubusercontent.com/18197106/37871306-aac42d88-2ff3-11e8-81f1-37f5b5aefcd3.png)
![screenshot_20180325-055909 1](https://user-images.githubusercontent.com/18197106/37871309-c3312376-2ff3-11e8-9e42-f3e7a4ad15ad.png)
![screenshot_20180325-055928 1](https://user-images.githubusercontent.com/18197106/37871307-b08f305a-2ff3-11e8-94c9-3317a3c102f8.png)
[AndroidAPS (5).log](https://github.com/MilosKozak/AndroidAPS/files/1844987/AndroidAPS.5.log)

**Comment by MilosKozak** [comment]
could you check pump what has been done ?

**Comment by RadoslavR** [comment]
The pump made these boluses. My cannula had to change and I was not worried. The records of the treatments are 1 hour back from the time the boluses were made. I'm happy, that I've activated "beep" at every bolus, even  SMB
