### ISSUE TITLE
2:00am is displayed instead of 1:00am in Local Profile

### ISSUE THREAD

**Issue by markflasher** [MilosKozak/AndroidAPS#806]
When creating a local profile the text displayed in the basal profile by 1:00am is instead 2:00am.

**Comment by Rol71** [comment]
I have a similar problem (v1.60). In my locale profile is since today (time change) 2:00 has been replaced by 3:00. Now 3:00 is displayed twice.

**Comment by MilosKozak** [comment]
daylight saving?
it's still there?

**Comment by AdrianLxM** [comment]
Had the same phenomenon due to DST, went away today!

**Comment by Rol71** [comment]
Here it is also gone :)

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/5ce184e67d002f5dc80c902a2190e0c54ecbaeea
