### ISSUE TITLE
Tempbasal delivery error during delivery superbolus

### ISSUE THREAD

**Issue by Rol71** [MilosKozak/AndroidAPS#820]
During delivery of a superbolus, AAPS reports "Tempbasal delivery error". After pressing OK Superbolus was completely delivered, but basal rate was not set to zero.
Shortly before, AAPS had stopped after adjusting and activating local profile.  

![screenshot_2018-04-01-05-28-53](https://user-images.githubusercontent.com/28503031/38169723-36602d28-3572-11e8-9f9b-2c6afec0c8c1.png)
![screenshot_2018-04-01-05-30-16](https://user-images.githubusercontent.com/28503031/38169725-39ec6fba-3572-11e8-9620-e3667aaa3df4.png)
![screenshot_2018-04-01-05-52-46](https://user-images.githubusercontent.com/28503031/38169792-100bb78a-3574-11e8-90ef-2da879780364.png)

Time: 05:29 AM
AAPS v1.60-dev

[AndroidAPS_2018-04-01_06-03-17.log](https://github.com/MilosKozak/AndroidAPS/files/1866105/AndroidAPS_2018-04-01_06-03-17.log)

**Comment by MilosKozak** [comment]
pump didn't reply and AAPS displayed message about it to take corrective action. this is expected behaviour. if this happen again reopen the issue

**Comment by MilosKozak** [comment]
thanks for reporting issue the corect way 👍
