### ISSUE TITLE
Bolus are not the same in the aps and the pump

### ISSUE THREAD

**Issue by jizhongwen** [MilosKozak/AndroidAPS#826]
Reporting bugs
--------------
- Bolus 5.0 U via androidaps , The bolus end unexpectedly, only 2.2 U are seen in the app, but when I check the pump, it has 5 U delivered.I check the log immediately , only the following logs are seen.
- 1.5.8 Build
[AndroidAPS._2018-03-31_10-49-15_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/1870345/AndroidAPS._2018-03-31_10-49-15_.1.zip)
![error_log](https://user-images.githubusercontent.com/25942874/38231701-560900e8-3746-11e8-8835-3cf9b0461f2f.jpg)

Can you help me resolve the issue, it has safety effects, I donated 500 Euro to the project, Your app is so good and helps me a lot. I hope it becomes better and better. My name is Zhongwen Ji . I am from China.
Thank you so much for developing this software for us.
My mail is  jizhongwen@gmail.com

**Comment by jizhongwen** [comment]
My pump model is Dana R

**Comment by jizhongwen** [comment]
I met this issue again. at 04-04 14:15 I delivered 2 U via aps, but it is not successful. I catch the screen in the pump and the log immediately. The Chinese word in the aps screen translate to Englishi is “ Waiting the bolus deliver finished, left:35 second. This is cirtiical bug, can you help me fix it. Thanks.
04-04 14:15:30.711  3859  3977 E NativeCrypto: ssl=0x7f98ffcd80 cert_verify_callback x509_store_ctx=0x7f64e96fa0 arg=0x0
04-04 14:15:30.712  3859  3977 E NativeCrypto: ssl=0x7f98ffcd80 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
04-04 14:15:31.525  3859  5631 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f99234930
04-04 14:15:34.280  3859  5631 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f98d06140
04-04 14:16:30.002  3859  5631 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f991294d0
04-04 14:16:54.333  3859  5631 E Surface : getSlotFromBufferLocked: unknown buffer: 0x7f99188520
04-04 14:16:55.185  3859 30155 E DanaRPlugin: [Thread-5706] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
04-04 14:16:55.190  3859 30155 E DanaRPlugin: [Thread-5706] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.DanaRPlugin:298]: setTempBasalAbsolute: Failed to set extended bolus
04-04 14:16:57.141  3859 30155 E DanaRPlugin: [Thread-5706] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.AbstractDanaRPlugin:305]: setExtendedBolus: Failed to extended bolus
04-04 14:16:57.146  3859 30155 E DanaRPlugin: [Thread-5706] ERROR [info.nightscout.androidaps.plugins.PumpDanaR.DanaRPlugin:298]: setTempBasalAbsolute: Failed to set extended bolus
[AndroidAPS._2018-04-04_07-35-10_.0(1).zip](https://github.com/MilosKozak/AndroidAPS/files/1874561/AndroidAPS._2018-04-04_07-35-10_.0.1.zip)
![1522823091595](https://user-images.githubusercontent.com/25942874/38292059-e39902b8-3814-11e8-9ed6-f68b3e15a0e5.jpg)
[AndroidAPS._2018-04-04_07-35-10_.0(1).zip](https://github.com/MilosKozak/AndroidAPS/files/1874563/AndroidAPS._2018-04-04_07-35-10_.0.1.zip)
![img_20180404_141614](https://user-images.githubusercontent.com/25942874/38292061-e4041e86-3814-11e8-8dfc-64bf8ef921cc.jpg)

**Comment by MilosKozak** [comment]
log ends at 14.11 :(
what was on the AAPS screen when this disppeared?

**Comment by jizhongwen** [comment]
No error was seen. The IOB is not increased.

**Comment by jizhongwen** [comment]
I will try to upload the new log file after the new log is generated

**Comment by jizhongwen** [comment]
[AndroidAPS._2018-04-04_07-35-10_.1.zip](https://github.com/MilosKozak/AndroidAPS/files/1876640/AndroidAPS._2018-04-04_07-35-10_.1.zip)

**Comment by MilosKozak** [comment]
pump replies an error to almost all requests. try to restart phone & pump
is this common or does thin happen rarely?

**Comment by MilosKozak** [comment]
do you have enabled extended boluses on pump?

**Comment by jizhongwen** [comment]
This issue occur several times, it is a common issue.  I enabled >200% extended bolus in the APS preference configuration.

**Comment by MilosKozak** [comment]
how is the status?

**Comment by jizhongwen** [comment]
I recorded a video when this issue occurred,  https://v.qq.com/x/page/a0622na6ls6.html
The bolus can deliver successfully in the most time, but several times may fail and encounter this issue

**Comment by jizhongwen** [comment]
I think this issue is related to the new code introduced by RS. When I used the RS, the same version, there was not any issue. But R has this issue. So I think R should use old code in 1.5.1 when delivering bolus , if use new coded introduced by RS related code, it will have this kind of issue.

**Comment by MilosKozak** [comment]
it't not possible to rollback 6 months. try the latest dev

**Comment by jizhongwen** [comment]
Not rollback 6 months. My idea is for the RS use new Rs bolus code. For the RN use the old bolus related code.  All the other code does not change. I will try the latest dev version. Thank you！
