### ISSUE TITLE
Verifying objectives before expected

### ISSUE THREAD

**Issue by Deksa** [MilosKozak/AndroidAPS#829]
Date: 01-04-2018 (April 1st)
AndroidAPS 1.58-combo-phantom-fusion

Is it intentional when in the objective 6 and on, you can verify them before the required time has passed? However, for instance the auto-sens will not be activated after verifying obj 6. So it is a bit confusing for a new user like me.

Notice the dates in the screenshot on objectives 6, 7 and 8.
![screenshot_20180403-093329](https://user-images.githubusercontent.com/22570897/38233510-6c292222-3723-11e8-9645-ff5dcc634168.png)

It's also a bit confusing, the wiki introduces seven objectives, but the app shows eight.

**Comment by triplem** [comment]
As mentioned, should be fixed with #842.
This should be fixed with PR #878. Please create a new issue if necessary.
