### ISSUE TITLE
Clear pump unreachable notification

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#830]

**Comment by aefy** [comment]
Could this be added to the APS app on watch as well?

**Comment by jotomo** [comment]
@aefy Wear uses normal Android notifications. If you enable the option _Use system notifications for alerts and notification_ you'll get such notifications on the watch. Clearing them will also clear the alarm.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/645e83b6e61fd925f82b505f8a67620838508f91
