### ISSUE TITLE
Nightscout will not be updated with threatments since 02.04.18

### ISSUE THREAD

**Issue by MasterPlexus** [MilosKozak/AndroidAPS#831]
The dev-Version seems to made no upload to Nightscout in the latest versions (build 02.04.18). 
The older versions up to 31.03. works properly. Also the AndroiddAPS start is not logged (nor in AndroidAPS and Nightscout).

What is not synced to Nightscout (as far as I could see) are Treatments (like boluses, carbs, and so on) and TBR's and start of androidAPS.

In Log no entry is visible with 
`[NSClientServiceHandler] DEBUG [info.nightscout.androidaps.plugins.NSClientInternal.UploadQueue$1:49]: QUEUE adding:  xxxx`
like it is if it has to work.

After switching back to version from 31.03. it works like expected.

I'll rebuild this evening clean, and check if it still is problematic.

I could provide Logs if needed.

**Comment by MasterPlexus** [comment]
Just to mentioned: Phone is a OnePlus 5 (cheeseburger with Android 8.0) as I see the other Issue #835 has also a OnePlus used.

**Comment by MilosKozak** [comment]
fixed by @triplem

**Comment by MasterPlexus** [comment]
Tested since yetsterday, and it works. Thanks!
