### ISSUE TITLE
No working "Ongoing Notifications" after commit > 30.03.2018

### ISSUE THREAD

**Issue by Matze1985** [MilosKozak/AndroidAPS#835]
Test on my:
--------------------------
* OnePlus 3, Android 8.1

Problem note:
----------------------------
* After updating commit bigger than 30.03.2018, no working "Ongoing Notifications"
* In addition, the same problems occur "https://github.com/MilosKozak/AndroidAPS/issues/831"

BR

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/8c303fd447c0d25879c121e480842f1ebc16b447
