### ISSUE TITLE
Feature request: 5hour Hypo TT

### ISSUE THREAD

**Issue by LongboatAline** [MilosKozak/AndroidAPS#837]
In the current dev, the carb button already includes a hypo target. Absolutely brilliant, and a great place to put that. The suggested duration is only 30 minutes though, which is a perfect if I'm just wanting to make sure that the rise after the low isn't countered with insulin too aggressively. 

When I've experienced a "real" (aka more severe) hypo though, I prefer to set the raised temp target for the entire period the liver may be trying to refill its emptied glycogen storage to prevent both subsequent lows and the pattern defined as "Pseudonormalisierung" by [Thomas et. al., p175](https://www.researchgate.net/profile/Andreas_Thomas2/publication/310248733_CGM_interpretieren_Grundlagen_Technologie_Charakteristik_des_kontinuierlichen_Glukosemonitorings/links/5832d6c908ae004f74c4d126/CGM-interpretieren-Grundlagen-Technologie-Charakteristik-des-kontinuierlichen-Glukosemonitorings.pdf).

Idea: depending on a low hypo threshold (I'm using 60), extend the duration of the raised temp target to 300minutes.

**Comment by jotomo** [comment]
@LongboatAline First off, I hope "real" hypos aren't that common for you ...
Some thoughts on your idea:
Automatically extending the TT is tricky to generalize. E.g. I have set target for HypoTT rather high (160m/30m) to avoid over-ambitious SMBs. Extending that to 5h would not be ideal.
In general, the idea behind the carbs and insulin button was to make common actions simpler, without cluttering up the dialog with every possible option (thus, defaults are used without the ability to change them in the dialog). If more specialized TTs are needed, they can still be set via the button the overview or the action (`dev` now also has the HypoTT preset which can be adjusted there).
The trickiest bit I see though is that just extending the duration would probably be confusing to most users which are unfamiliar with the concept of Pseudonormalisierung, so they wouldn't know they need a longer duration, nor why AAPS suggests it and would probably see it as a bug and manually reduce the duration. So AAPS would have to teach the concept to users, or they user already needs to know it, in which case he can apply it himself. An alert/notification to remind the user to consider a longer TT doesn't seem suited, at least personally I don't want alarms to annoy me when a hypo is already annoying me.
What might work though, would a preferences for "extended hypo TT" (or similiar), where a user familiar with the concept can configure a low threshold, target and duration, which is used when the current SGV is below that threshold. If the user hasn't configured that, it's not used.
I'm not sure though if that is satisfactory, the phenomena could still occur (I think) with a prolonged hypo of 65mg, so the user still needs to be the one to act and decide. Maybe add a note in the confirmation dialog, something like "SGV is below 70mg, consider a longer hypo TT to prevent further hypos"?
How often would you need that functionality?

**Comment by LongboatAline** [comment]
A huge thanks for implementing

-  user-definable Temp Targets in settings
-  #1173 automatic invocation of the Hypo TT when BG gets low. 

I'm closing this issue, since the implementation more than covers what I had in mind .  Thank you!
