### ISSUE TITLE
Profil change: Alert "Command is executed right now"

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#840]
I have an issue with profile changes:
- Nightscout sync enabled
- AAPS: Profil change from one percentage to another (f. e. 100% --> 110%)
- Profil change works as suggested
BUT I get sometimes an alert "Command is executed right now" immediatly after hitting "ok" in the confirmation dialog. Furthermore from time to time this alert restarts after confirmation. I don't get this alert if Nightscout Sync is disabled (upload only). Neverless the change is realised correctly. It seems that on certain circumstances the started profile change is restarted by the Nightscout Client.
- Workaround: Disable Nightscout sync
- AndroidAPS 1.60c-dev
- Log file: 08:29:11.696 -> start of the profile change process
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1878803/AndroidAPS.log)

**Comment by LongboatAline** [comment]
Same here, AndroidAPS 1.60c-dev 1dca255-2018-04-03, except that I get it on every (manual) profile change (%-ual). For automagic TBR changes, I usually do not get this alert, except tonight around 3:30 when the phone made a rather disruptive racket >)
I'll go through that logfile and get the relevant part later today (currently have a semi-bricked? SWR50 attached).

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/828b20e3581ebe87ee0ae81cb7dcadea2e4ab616
