### ISSUE TITLE
add note to "AndroidAPS started" what phone was it

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#841]

**Comment by LongboatAline** [comment]
Good idea for all of us who are testing different setups. You'll use the ID that's also visible with `adb devices`, I assume? (I'm usually using the same kind of phone, so if they're all called "Moto G", they'd still be hard to tell apart)

**Comment by PoweRGbg** [comment]
Should it be another note or just a string added to the AndroidAPS started ?

**Comment by MilosKozak** [comment]
thanks @PoweRGbg
