### ISSUE TITLE
You can finish Objective 7 and 8, without full time elapsing

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#842]
So when I entered objective 7 (and 8) I could proceed to finish without 20-something days to pass before (I am been using AAPS for time longer than that time required). I think problem is that objective doesn't look when you started it, but on full time you have been using AAPS. Same with 8.

Version: 1.58 Combo branch (I use my own fork, because I am working on adding translation, so build number won't be of much help, but if it does here it is - ad4795c 2018.03.18)

**Comment by LongboatAline** [comment]
See also #829. For the combo branch, I can confirm this behaviour for objectives 7 and 8 - 6 did require me to run the whole mile.

**Comment by pedroll** [comment]
same here. 1.58 combo prefs from openlooping in dev branch

**Comment by triplem** [comment]
This should be fixed with PR #878. Please create a new issue if necessary.
