### ISSUE TITLE
Giving Bolus via Watch triggers Bolus but does not store Treatment

### ISSUE THREAD

**Issue by triplem** [MilosKozak/AndroidAPS#845]
Dev Version e49d430a-2018.03.27

On giving a Bolus via Watch the Bolus is triggered and send to the pump, but not stored in the Treatments (there the Bolus is stored with 0IE). In NS you see a Meal Bolus without any IEs.

**Comment by swissalpine** [comment]
Have you also updated your wear app?
Afaik that isn't done automatic (at least not on my watch), you must delete and reinstall the wear app ...

**Comment by jotomo** [comment]
Watch might be a red herring? #681

**Comment by triplem** [comment]
Watch App is updated, and no SMB is used. Could still be a herring, though.

**Comment by triplem** [comment]
Difference to #681 is, that this Bolus was delivered but not reported in the treatments tab (bolus: 0.0 got reported). Browsing the logs seems to be fine. Since I cannot reproduce this right now, I will close this one.
