### ISSUE TITLE
The basal cannot be configured <0.1 at 8:00 or the time range contain 8:00 on the APS

### ISSUE THREAD

**Issue by jizhongwen** [MilosKozak/AndroidAPS#848]
Reporting bugs
--------------
- This issue can be reproduced very easily, set basal 0.09 at 8:00 in the local profile or nightscout profile, then syn profile to the pump, then this issue occurs. The error can be seen "Value max_daily_basal is out of hard limits 0.09 limited to 0.10. My basal step has been configured as 0.01 in the pump. Other time is ok, only 8:00 has this issue. 
- 1.51 
![_20180406093813](https://user-images.githubusercontent.com/25942874/38399729-ae2d9592-397e-11e8-9155-6b8c2c864912.jpg)
![_20180406093818](https://user-images.githubusercontent.com/25942874/38399730-ae84b07a-397e-11e8-9260-aa272308b6ac.jpg)
![_20180406094113](https://user-images.githubusercontent.com/25942874/38399731-aedb8576-397e-11e8-8dff-0061a7cd3631.jpg)

and 1.58 version

**Comment by triplem** [comment]
In your profile basal is set to 0.09 for the whole day, which is smaller then the lower limit 0.1. Could be that this is the issue?

**Comment by jizhongwen** [comment]
other time can be lower then 0.1. but 8:00 can not

**Comment by MilosKozak** [comment]
there is bug in master that at least one value must be greater that 0.1 or equal .
it fixed in dev branch
