### ISSUE TITLE
android studio win nothing showed under build

### ISSUE THREAD

**Issue by bryce2071** [MilosKozak/AndroidAPS#852]
Hi, 
i donwloaded android studio for windows.
donwloaded the zip with the androidaps from here, extracted it, loaded this project in androidstudio, 
i cant build, cause nothing is showed under build.

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/38464895-68871458-3b15-11e8-94a0-fce8ed75ea55.png)
you have to open directory with this content

**Comment by bryce2071** [comment]
Hi Milos, 

 

i do not understand what you mean.

I dont have this directory.

Maybe i downloaded a wrong zip?

 

i downloaded this:

 



 

 



 



 

--

Gruss

Peter Bohn

 

Von: Milos Kozak <notifications@github.com> 
Gesendet: Sonntag, 8. April 2018 10:13
An: MilosKozak/AndroidAPS <AndroidAPS@noreply.github.com>
Cc: bryce <bryce2071@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [MilosKozak/AndroidAPS] android studio win nothing showed under build (#852)

 

 <https://user-images.githubusercontent.com/11146458/38464895-68871458-3b15-11e8-94a0-fce8ed75ea55.png> 
you have to open directory with this content
