### ISSUE TITLE
Careportal Sensor and Battery Age

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#860]
These are the treatments from the 600SeriesAndroidUploader, but no values in AAPS. Is that a mistake of AAPS or 600SeriesAndroidUploader?

{
    "_id": {
        "$oid": "5ac87bca9d8647aeb7d6fffe"
    },
    "created_at": "2018-03-27T19:55:56+02:00",
    "eventType": "Note",
    "key600": "MISC800C4821",
    "notes": "Pump battery changed (lifetime 10 days 14 hours)"
}

{
    "_id": {
        "$oid": "5ac654a59d8647aeb7cd4311"
    },
    "created_at": "2018-03-30T17:32:03+02:00",
    "eventType": "Sensor Start",
    "key600": "MISC80101AE7",
    "notes": "Sensor changed (lifetime 6 days 1 hours)"
}
![screenshot_20180409-201224](https://user-images.githubusercontent.com/32514747/38515646-1805221a-3c35-11e8-9204-1b20a623bd54.png)

**Comment by jotomo** [comment]
First entry has generic event type "Note", this needs to be "Pump Battery Change" instead to be recognized.
Second entry is about sensor start, IIRC AAPS uses "Sensor Change" event for SAGE (thus the time the sensor was inserted, not the time the sensor was (re)started).

**Comment by st0ber** [comment]
OK, thank you.
