### ISSUE TITLE
Virtual pump support

### ISSUE THREAD

**Issue by MilosKozak** [MilosKozak/AndroidAPS#863]
PUMP TYPE:
Bolus step:
Extended bolus step:
Extended bolus duration step:
Extended bolus max duration:

Temp basal style: (percent or absolute)
Temp basal step:
Temp basal duration step:
Temp basal max value:
Temp basal max duration:

Base basal min value:
Base basal step:

**Comment by gempickfordwaugh** [comment]
PUMP TYPE: Animas Vibe https://www.animascorp.co.uk/insulin-pumps/vibe-insulin-pump
Bolus step: 0.05u
Extended bolus step: [not stated, assume as above]
Extended bolus duration step:  0.1 hr to 12 hrs, with 0.5 hr increments for 0.5 hr to 12 hrs
Extended bolus max duration: 12 hrs
Temp basal style: percent
Temp basal step: -90% to +200%, in 10% increments
Temp basal duration step: 0.0 hr to 24 hrs in 0.5 hr increments
Temp basal max value: 50u/hr (+200% of max basal rate 25u/hr)
Temp basal max duration: 24 hrs
Base basal min value: 0.025u/hr
Base basal step: 0.025u/hr steps

**Comment by slon77** [comment]
PUMP TYPE: Accu-Check-Spirit-Combo
Bolus step:  0,5
Extended bolus step:  0,1 
Extended bolus duration step:  15 min – 12 h
Extended bolus max duration:  12 h
Temp basal style:  0 – 250 %
Temp basal step:  10 %
Temp basal max value:  500 %
Temp basal max duration:  24
Base basal min value:  0.01
Base basal step:  0,01 (до 1,00 U / h),
                           0,05 (до 10,0 U / h) и
                           0,1 (до 50,0 U / h)

**Comment by gempickfordwaugh** [comment]
PUMP TYPE: Omnipod https://www.myomnipod.com/sites/default/files/inline-files/17845-5A%20Guide%2C%20Eros%20US%20User%20Guide%20Rev%20B.pdf
Bolus step: 0.05u
Extended bolus step: [not stated, assume as above]
Extended bolus duration step:  0.5hrs to 8 hrs, with 0.5 hr increments
Extended bolus max duration: 8 hrs
Temp basal style: percent
Temp basal step: 0u/hr to +95% in 5% increments
Temp basal duration step: 0.5hr increments
Temp basal max value: cannot exceed max basal rate 30u/hr
Temp basal max duration: 12hrs
Base basal min value: 0.05u/hr
Base basal step: 0.05u/hr steps

**Comment by scarral** [comment]
PUMP TYPE: Medtronic Minimed 640G
Bolus step: 0.025
Extended bolus step: 0.025
Extended bolus duration step: 15 minutes but minimum extended bolus duration is 30 min.
Extended bolus max duration: 8 hours

Temp basal style: (percent or absolute) both, but up to 200% when in %, so for AAPS absolute is better
Temp basal step: 0.025
Temp basal duration step: 15 minutes but min duration is 30 minutes. 
Temp basal max value: 2 (might be limited to this somewhere in the pump settings)
Temp basal max duration: 24 h

Base basal min value: 0.025
Base basal step: 0.025

**Comment by xour** [comment]
Hi! please note that in Omnipod, it can be selected whether you want your temp basals in % or in units/hr. If in units/hr, it goes up to 5 units/hr, with 0.05 units increment. Bolus and extended bolus steps also in 0.05 units increments.

**Comment by taylorfowler** [comment]
PUMP TYPE: Tslim https://www.tandemdiabetes.com/docs/default-source/product-documents/tslim-insulin-pump/t-slim-technical-specifications.pdf?sfvrsn=f94d3bd7_4
Bolus step: 0.01 unit
Extended bolus step: 0.01 unit (minimum 0.4 units)
Extended bolus duration step:1 minute (minimum 15 mins)
Extended bolus max duration: 8 hr

Temp basal style: percent
Temp basal step: 1%
Temp basal duration step: 1 min (minimum 15 min)
Temp basal max value: 250%
Temp basal max duration: 72 hr


Base basal min value: 0.1
Base basal step: 0.001

**Comment by swissalpine** [comment]
Correction for Accu Check Spirit Combo:
Bolus step: 0,1

**Comment by slon77** [comment]
Ok10.04.2018, 23:35, "swissalpine" <notifications@github.com>:Correction for Accu Check Spirit Combo:
Bolus step: 0,1

**Comment by dansuk** [comment]
PUMP TYPE: Cellnovo https://www.cellnovo.com/
Bolus step: 0.05
Extended bolus step: 0.05 (minimum 1 unit)
Extended bolus duration step: 0.5 hr to 8 hrs, with 0.5 hr increments for 0.5 hr to 12 hrs
Extended bolus max duration: 8 hrs

Temp basal style: percent
Temp basal step: 5%
Temp basal duration step: 30 mins
Temp basal max value: 200%
Temp basal max duration: 24 hrs

Base basal min value: 0.05
Base basal step: 0.05

**Comment by jroth-haj** [comment]
PUMP TYPE: Medtronic VEO 
https://www.medtronic-community.de/wp-content/uploads/Bedienungsanleitung-MiniMed-Veo_deutsch.pdf
https://www.medtronic-community.de/wp-content/uploads/Bedienungsanleitung-englisch-Stand-November-2013.pdf
Bolus step: configurable 0,1 - 2,0 IE / step
Extended bolus step: same as bolus step
Extended bolus duration step: 30min
Extended bolus max duration: 8h

dual bolus step: same as bolus step
dual bolus duration for extendedbolus step: 30min
dual bolus max duration: 8h

Temp basal style: (percent or absolute) both (percent or absolute)
Temp basal step: 30min
Temp basal duration step: 30min
Temp basal max value: 200% or configured max basal (35)
Temp basal max duration: 24h

Base basal min value: 0,025
Base basal step:  0,025

**Comment by LLSmurf** [comment]
PUMP TYPE: Medtronic VEO (corrections, maybe due to different firmware, here German VEO from 2012)

Bolus step (easy bolus) configurable: 0,1 - 2,0 IE / step
Bolus step (scroll bolus) configurable: 0.025 - 0,1 IE / step
Bolus max. value: configurable 0-75 IE

Temp basal style: (percent or absolute) BOTH, configurable
Temp basal step: 1% or 0.025 IE/h (above 1.0IE/h 0.05 IE steps) 
Temp basal duration step: 30 min
Temp basal max value: 200% or up to configured max. base basal rate (when using absolute)
Temp basal max duration: 24h

Base basal min value: 0.025 IE/h 
Base basal step: 0.025IE/h up to 1 IE/h, 0,05 IE/h above 1IE/h
Base basal max: Configurable up 35IE/h

**Comment by AdrianLxM** [comment]
@LLSmurf is this the 554/754?

**Comment by andyrozman** [comment]
I will start working on this.

**Comment by MilosKozak** [comment]
in dev now

**Comment by Paola2011** [comment]
Hi guys, i heard the accu-check insight is ready to be working in androidAPS, but not info is displayed here. Kindly give me an update on it :)

**Comment by andyrozman** [comment]
When I did this Virtual Pump extension Insight was not on list... You can open ticket to add it to the list and I will extend it... 

As for Insight implementation itself, author doesn't want his work visible until he is satisfied with it. We also had to remove it from documention (Future solutions). If you need more info ask on AAPS gitter room and people will point you to right direction.

But we can add it as VirtualPump option... Please open ticket and I will look at it.

**Comment by qq254344379** [comment]
@andyrozman
