### ISSUE TITLE
Feature request: BT watchdog for combo

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#867]
in case on BT connections issues with combo, it could be great that BT watchdog toggle BT on off on phone and then try to connect again. 

When I do it manually on my phone, it works fine.

if possible, it would be great to store an event in Careportal too showing when BT watchdog ran.

thanks!
@Gregorybel

**Comment by jotomo** [comment]
@gregorybel Try this: https://github.com/jotomo/AndroidAPS/tree/howling-at-the-moon

**Comment by gregorybel** [comment]
that's cool, thanks a lot, Will try it.

How do you detect there is no connection?

**Comment by jotomo** [comment]
Watch triggers if connect times out.

**Comment by jotomo** [comment]
@gregorybel Try this:  https://github.com/jotomo/AndroidAPS/tree/combo-prefs
Updated version where BT watchdog and debug stuff can be configured via preferences.

**Comment by jotomo** [comment]
@gregorybel IIRC this isnt' needed anymore, since you found the root cause elsewhere. If so, please close.

**Comment by gregorybel** [comment]
I did not find it but it is no longer an issue Indeed, hence closing.
