### ISSUE TITLE
Feature request: Longer duration of temp basals when open looping

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#871]
I am limited to open looping due to having an unsupported pump (Cellnovo). The Cellnovo is limited to only allow a maximum of 200% temporary basal rate. Sometimes I require more than 200% of the basal rate and it would be good if AAPS could take into account that I require more and increase the duration required as necessary instead of just saying 30 minutes. If for instance the duration could be increased to allow the full rate of missing insulin to be set (even if running for that total time would amount to excess insulin), AAPS would prompt when the temp basal should be cancelled. This would help everyone open looping enjoy the benefits without quite so much input.

**Comment by MilosKozak** [comment]
APS is producing recomendation only for max 30 min. But there is easy workaround for you. you don't need to follow exact recommendation. Simply set the temp basal as you wish and enter it into AAPS. It will be considered in next loop

**Comment by dansuk** [comment]
Thanks Milos, I will give that a try.
