### ISSUE TITLE
Crashing, maybe on pump connect

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#875]
https://github.com/MilosKozak/AndroidAPS/blob/263263daf17e4334802cbc018b3996d593ac4374/app/src/main/java/info/nightscout/androidaps/queue/QueueThread.java#L58

AAPS crashes, but can't reproduce it, logcat shows this error:

04-12 09:03:49.978 16823-16862/? E/AndroidRuntime: FATAL EXCEPTION: Thread-15
                                                   Process: info.nightscout.androidaps, PID: 16823
                                                   java.lang.NullPointerException: Attempt to invoke interface method 'boolean info.nightscout.androidaps.interfaces.PumpInterface.isConnected()' on a null object reference
                                                       at info.nightscout.androidaps.queue.QueueThread.run(QueueThread.java:58)

Build: e9ac979a-2018.04.10

[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/1901701/AndroidAPS.log)

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/80e81b1c25152bfae43fdf3d6b2e4ceb97ffaaed
but the main issue that should be solved is the phone, because it was not able to initialize app within 3 sec
