### ISSUE TITLE
Dev branch - temp targets in mg/dl while rest is in mmol

### ISSUE THREAD

**Issue by emielmiddel** [MilosKozak/AndroidAPS#880]
When setting a pre-set temp target (either eating soon, activity or hypo), the temp target is in mg/dl while everything else is in mmol/l. I instantly get an error for temp target out of hard limits. 

= Build version 1.60d-dev

[AndroidAPS._2018-04-14_00-02-24_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1910249/AndroidAPS._2018-04-14_00-02-24_.0.zip)

**Comment by MilosKozak** [comment]
did you setup your own values in prferences?

**Comment by emielmiddel** [comment]
Yes I have. Even a manual temp target is not possible  now, it automatic call calculates my input (mail) to mg/dl

Verstuurd vanaf mijn iPhone

**Comment by n3cro1** [comment]
Same problem here. TT in mmol/l is set to mg/dl. Then  i got an error.

**Comment by rhysjones** [comment]
I get this too.

**Comment by MilosKozak** [comment]
fixed in https://github.com/MilosKozak/AndroidAPS/commit/51530fbcf845c613aac712ca3752bf6ad3346a8a
