### ISSUE TITLE
"Could not get unknown property 'packageForR'" error while generating signed APK

### ISSUE THREAD

**Issue by alfiearthur** [MilosKozak/AndroidAPS#882]
This is my first bash at installing this amazing project, so please be lenient if I've not reported everything correctly, or have made a "Duh" error. I've added some of the messages I receveived, for whoever is next to install AndroidAPS. I can't generate the signed SDK, so I have no phone logs to submit. Can't wait to get it working.

**Error trying to Generate Signed SDK**
When I try to Build | Generate Signed SDK, I get the following error:
“Could not get unknown property 'packageForR' for task ':app:processFullDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.”
Google tells me this is probably something to do with the Butterknife plugin https://github.com/realm/realm-java/issues/5731 but I’m not sure what to do with that information.

**NDK was not installed automatically**
Just for future installers, NDK was not automatically installed when I installed Android Studio. You can
[logs-20180416-120000.zip](https://github.com/MilosKozak/AndroidAPS/files/1914963/logs-20180416-120000.zip)
 install it through Tools|SDK Manager|Appearance & Behaviour|Android SDK with the Tab “SDK Tools”.

**Expired configurations**
Just to note that the following configurations will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

•	Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.	
•	Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.	
•	Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.	
•	Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.	
•	Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.	
•	Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.	
•	Configuration 'provided' is obsolete and has been replaced with 'compileOnly'.	

**My Current Configuration**
Dell PC: i7, 3.6GHz, 24Gb RAM, 64bit OS
Windows 10 Home Version 1709 (OS Build 16299.371)
Android Studio Build: 3.1.1, AI-173.4697961, 201804040039, 
AI-173.4697961, JRE 1.8.0_152-release-1024-b02x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1680x1050, 1920x1200, 1280x1024
Android Gradle Plugin: 3.1.1
Gradle: 4.4
NDK: from local.properties: 16.1.4479499; latest from SDK: 16.1.4479499; 
LLDB: LLDB 3.1 (revision: 3.1.4508709)
AndroidAPS latest code was downloaded at 11:53 16/04/2018 (my birthday!)

T1D aged 13, diag aged 9, No Hypo-awareness
[logs-20180416-120000.zip](https://github.com/MilosKozak/AndroidAPS/files/1914958/logs-20180416-120000.zip)
; Omnipod, Libre and Blucon, Nightscout and XDrip+through Mongo

**Comment by jotomo** [comment]
The issue was introduced by Android Studio 3.1 / Gradle 4.4 and has only been fixed in the `dev` branch so far. Since your building the `master` branch (as recommended), can you try using Android Studio 3.0.1? It's available here: https://developer.android.com/studio/archive.html
To might have revert changes to `build.gradle` files (use the Version Control tool windows to do so).

**Comment by alfiearthur** [comment]
Thank you for your quick reply.

I will try reverting to Android Studio 3.0.1.

We are not looping, so maybe it’s worth installing the dev version. What do you think?

 

Many thanks,

 

Rob

 

Rob Arthur

  _____

**Comment by MilosKozak** [comment]
i was able to build master with lastest studio. only you must NOT allow upgrade gradle

**Comment by alfiearthur** [comment]
Thanks Milos,

Such an amazing piece of software.

We had a meeting with our diabetes consultant this morning and I was telling her how good your software is.

 

Rob

 

Rob Arthur

  _____
