### ISSUE TITLE
Wear: Couldn't bolus anymore

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#893]
Something seems broken with the bolus confirmation dialog on my watch (Polar M600). The dialog doesn't appear anymore, neither after a bolus nor after the wizzard.
Other dialogs pop ups (f. e. bolus progress when started a bolus with the smartphone).
Version: 7063F4DE-20, 18.04.2018

**Comment by swissalpine** [comment]
Probably stupid question: Has it to do with the following warning?
`Error:(171) Error: The com.google.android.gms.wearable.BIND_LISTENER action is deprecated. Please upgrade to the latest available version of play-services-wearable: 11.0.4 [WearableBindListener]`

**Comment by AdrianLxM** [comment]
Should be fixed in: https://github.com/MilosKozak/AndroidAPS/pull/894
If it persists, please reopen.

**Comment by swissalpine** [comment]
Fixes the issue!
Thanks a lot - you're so fast!
