### ISSUE TITLE
Error with delivering Carbs

### ISSUE THREAD

**Issue by McHoffi** [MilosKozak/AndroidAPS#917]
![screenshot_20180423-080125_androidaps](https://user-images.githubusercontent.com/24695277/39112093-b62149f4-46d7-11e8-9d06-98eeb46febb2.jpg)

When no delay for carbs is added, it will give an delivery error, but with a delay, f.e. 1 min, it doesn´t show anything.
Carbs are there, but the error is really annoying.
Using dev with 545b4a51
If logs are needed, I can upload them then.

**Comment by swissalpine** [comment]
I couldn't confirm this behaviour. The Carbs button works as it should.
Pump: Combo
AndroidAPS: dev f064f7fb-2018.04.22 (build yesterday)

**Comment by McHoffi** [comment]
Just tried it with entering carbs into the past, happens there too.

**Comment by MilosKozak** [comment]
it happens only without insulin?

**Comment by McHoffi** [comment]
It happens when using the new carb button, where you just add carbs, didn't try with wizard.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/c15a4b5efe9cc14da486269113c14fea036e9d51
