### ISSUE TITLE
SMBJS: Zero-temp gets cancelled due to IOB > max_iob

### ISSUE THREAD

**Issue by LongboatAline** [MilosKozak/AndroidAPS#922]
While writing up issue #923 , this popped up as well:
A zero temp was active after smb, and a subsequent run considered IOB to have exceeded max_iob, and thus cancelled the zero-temp.

In this case, shouldn't it cancel only high-temps, and leave (or even reduce) low-temps?

Complete log file will be with the other issue and be linked here as soon as that is posted.

`13:31:35.741 [pool-9-thread-1] DEBUG [info.nightscout.androidaps.plugins.OpenAPSSMB.DetermineBasalAdapterSMBJS:139]: Result:`
```json
{
  "temp": "absolute",
  "bg": 116,
  "tick": "+0",
  "eventualBG": 309,
  "insulinReq": 0,
  "deliverAt": "2018-04-21T11:31:35.606Z",
  "sensitivityRatio": 1,
  "predBGs": {
    "IOB": [
      116, 115, 113, 111, 107, 103, 98, 93, 87, 80, 73, 66,
      58, 50, 43, 39
    ],
    "ZT": [
      116, 116, 116, 116, 116, 116, 117
    ],
    "COB": [
      116, 116, 116, 115, 115, 115, 115, 114, 115, 115, 116, 117,
      119, 120, 123, 125, 128, 132, 136, 140, 145, 150, 156, 162,
      168, 175, 181, 188, 195, 203, 210, 217, 224, 231, 238, 245,
      252, 258, 264, 270, 276, 281, 287, 292, 296, 301, 305, 309
    ],
    "UAM": [
      116, 116, 115, 114, 113, 111, 110, 108, 106, 104, 103, 101,
      100, 99, 98, 97, 96, 96, 95, 95, 95, 95, 96, 96,
      97, 97, 98, 98, 99, 99, 100, 100, 100, 100, 100, 100,
      100, 100, 100, 100, 100, 100, 100, 100, 101, 101, 102
    ]
  },
  "COB": 35.77622222222222,
  "IOB": 3.15,
  "reason": "COB: 35.77622222222222, Dev: 59, BGI: -10,
             ISF: 90, CR: 8, Target: 90,
             minPredBG 136, minGuardBG 110,
             IOBpredBG 39, COBpredBG 309, UAMpredBG 102;
             IOB 3.15 > max_iob 3; setting current basal of 0.9 as temp. .
             Suggested rate is same as profile rate, a temp basal is active, canceling current temp",
  "duration": 0,
  "rate": 0
}
```

**Comment by MilosKozak** [comment]
this is correct. eventualBG is still above target therefore more insulin is needed but you hit the IOB limit

**Comment by LongboatAline** [comment]
But in the case of a low-temp, cancelling it increases (basal) IOB. That's why I wondered if that's really intentional.

**Comment by AdrianLxM** [comment]
Setting a neutral temp or cancelling a TBR will not increase the IOB. IOB will decrease as it ages out.

In this case it would have given you a high temp but as you are above maxIOB, the loop will not do more than a "plain old insulin pump" would do.
It is a safety feature, not a target that it tries to keep below.
