### ISSUE TITLE
[smb / Bolus Wizard]  insulin on hypo

### ISSUE THREAD

**Issue by LongboatAline** [MilosKozak/AndroidAPS#923]
Over the past two weeks, I've collected a few examples where the Bolus Wizard would suggest a rather (un)healthy dose of insulin. On a few of those occasions, smb kicked in as well and added insulin to a falling bg already below target. Reading the logs, it seems there's more than one possible problem involved:

1.  #922 A zero-temp from SMB gets canceled due to **IOB > max_iob** (cf. table and log at **13:31**:35.741)
1. smb adds insulin even though bg below target and sloping downward based on remaining COB 
1. Bolus Wizard suggests adding even more insulin.

So let's start with the latest documented example (AAPs 1.60d-dev, 7063f4de-2018-04-17), and add more in comments of their own.

## 2018-04-21 [1325-AndroidAPS.log.gz](https://github.com/MilosKozak/AndroidAPS/files/1942885/1325-AndroidAPS.log.gz)

Starting a late brunch at a bg of about 115, about 45 carbs altogether during the warm-up phase of a restarted sensor. About 1h after the meal (1:30 after bolus), a bg check reveals that despite the meal, the bg hasn't changed much (119). Looking good, checking bolus wizard (no screenshot). 
The Bolus wizard suggests adding an entire unit of insulin (ISF 100). Reducing by half, to check that suggestion. SMB also kicks in before the manual bolus goes through, zero-temp gets cancelled (#922).

Another hour later (14:28), and the bg (manual check, inserted as cgm via 600series uploader)  ist at 89 southeast arrow, slightly below target. 

![screenshot_20180421-142834](https://user-images.githubusercontent.com/35570803/39187791-7c09e6ca-47ce-11e8-9c89-b56eee428c7d.jpg) ![screenshot_20180421-142815](https://user-images.githubusercontent.com/35570803/39187928-d00a265e-47ce-11e8-86f8-3f39bf7fb187.jpg)

Target bg is 95, svg 89, last 15min falling by -12, ISF 100. There's still carbs on board, but obviously the insulin dosed for that meal was a little bit more than enough, at least according to the flattish/downward slope of the cgm graph. All predictions but COB agree on that - looks like the COB prediction overrides the others.

One more smb before things go further downhill (Bolus Wizard view just for illustration, no manual bolus given):
![screenshot_20180421-150404](https://user-images.githubusercontent.com/35570803/39189259-18823be4-47d2-11e8-8f2a-04d26dbcbb31.jpg) ![screenshot_20180421-150701](https://user-images.githubusercontent.com/35570803/39189150-de07db36-47d1-11e8-9022-eb7f5a2405ee.jpg)

And the resulting preview:
![screenshot_20180421-150857](https://user-images.githubusercontent.com/35570803/39189076-b05a1870-47d1-11e8-9035-bd04a4e3bd29.jpg)

Catching the downward slope with carbs.
![screenshot_20180421-142815](https://user-images.githubusercontent.com/35570803/39188991-6c2c6356-47d1-11e8-8702-fb951eea99b1.jpg)

Table through the logfile

| Timestamp  | Data | Event |
| ------------- | ------------- |------------- |
| **13:25**:38+02:00 | 119 | info.nightscout.client.NEW_SGV |
| **13:29**:15.377| smb 0.2U |
| **13:31**:02.679| 0.5U |CommandBolus from Bolus Wizard|
| **13:31**:35.741| 90%>30m| TBR because IOB > max_iob (cancelling 0-temp) (#922)| 
| **13:29**:15.100 |Thread-558110|OpenAPSSMB.DetermineBasalAdapterSMBJS:77|
| **14:27**:16.114 | Thread-558489|OpenAPSSMB.DetermineBasalAdapterSMBJS:77| 
| **14:27**:16.401 | 0%>60m| applyAPSRequest|
| **14:27**:16.470 | 89 ↘︎ | info.nightscout.client.NEW_SGV (Screenshot Home/Bolus Wizard)|
| **14:27**:18.628 |  | onHandleIntent |
| **14:32**:15.104| smb 0.1U | OpenAPSSMB.DetermineBasalAdapterSMBJS:139|
| **15:02**:16.114| 78 | smb 0.2U |  bolus wizard considers 1.3U necessary |
|1517| 68 | carbs |

#### **14:32**:15.104 Result smb 0.1U  OpenAPSSMB.DetermineBasalAdapterSMBJS:139
```json
{
  "temp": "absolute",
  "bg": 91,
  "tick": "+1",
  "eventualBG": 257,
  "insulinReq": 0.39,
  "deliverAt": "2018-04-21T12:32:14.949Z",
  "sensitivityRatio": 1,
  "predBGs": {
    "IOB": [
      91, 91, 90, 88, 86, 84, 81, 78, 75, 71, 66, 62,
      57, 52, 48, 44, 41, 39
    ],
    "ZT": [
      91, 91, 91, 91, 91, 92, 92, 93
    ],
    "COB": [
      91, 91, 92, 92, 93, 94, 96, 97, 99, 101, 104, 107,
      110, 113, 117, 121, 125, 129, 134, 138, 143, 148, 152, 157,
      162, 167, 172, 177, 182, 187, 192, 196, 201, 206, 210, 214,
      219, 223, 227, 231, 235, 238, 242, 245, 248, 251, 254, 257
    ],
    "UAM": [
      91, 91, 91, 90, 90, 89, 89, 88, 88, 87, 86, 85,
      85, 84, 83, 82, 81, 80, 79, 77, 76, 74, 72, 71,
      70, 69, 68, 68, 67, 67, 67, 67, 67, 67, 68, 68,
      68, 69, 69, 70, 71, 71, 72, 73, 73, 74, 75, 76
    ]
  },
  "COB": 26.295555555555563,
  "IOB": 1.7570000000000001,
  "reason": "COB: 26.295555555555563, Dev: 62, BGI: -10, 
             ISF: 100, CR: 8.89, Target: 95, 
             minPredBG 134, minGuardBG 81, 
             IOBpredBG 39, COBpredBG 257, UAMpredBG 76;  
             insulinReq 0.39; 
             setting 90m low temp of 0U/h. Microbolusing 0.1U. ",
  "units": 0.1,
  "rate": 0,
  "duration": 90
}
```

**Comment by LongboatAline** [comment]
## 2018-04-04
More of a hypo:
![screenshot_20180404-120209 png](https://user-images.githubusercontent.com/35570803/39190380-c67298d2-47d4-11e8-9363-18eeea24da3d.jpg) ![screenshot_20180404-120202 png](https://user-images.githubusercontent.com/35570803/39190396-ce9ae87a-47d4-11e8-8d0f-8dc86a41c3b0.jpg)


smb, Bolus Wizard suggests countering the rescue carbs with oodles of insulin:
![screenshot_20180404-123042 png](https://user-images.githubusercontent.com/35570803/39190490-fdab044c-47d4-11e8-8a53-d9e17bd91ad9.jpg) ![screenshot_20180404-123120 png](https://user-images.githubusercontent.com/35570803/39190498-06458ab4-47d5-11e8-999b-4bcbd10fb3f6.jpg)

rescue carb rise reined in successfully, the end of the high-temp gives smb a chance to kick in again:
![screenshot_20180404-144106 png](https://user-images.githubusercontent.com/35570803/39190921-e9d0c6ae-47d5-11e8-8d25-f6268b1571b2.jpg)

**Comment by AdrianLxM** [comment]
This should be fixed in RC2.0 with the ZT prediction now acting correctly as safety delimiter.
If it still happens, please open a new issue as the current data is still based on wrong IOB calculation for ZT.
