### ISSUE TITLE
On small displays (standalone watches, display sizes 240x240 or 320x320) some dialogs unusable.

### ISSUE THREAD

**Issue by dideldum** [MilosKozak/AndroidAPS#926]
Using master branch (1.58).

AndroidAPS installed on a standalone full Android watch (Finow M9, Android 6.0, display size 240x240).

The described problems occur only on this small display. For the time dialog there is a workaround to set the pixel density of the watch to a lower value. Then the whole content of the display will be smaller and more of the content will be shown. But this works only with the time dialog, not with the others.

The 2 dialogs on the overview page "Bolus" and "Calibration" don't show the OK button. The OK button seems to be fix to the right. Probably a FlowLayout for the button panel in the lower part of the dialog should solve it.

The date dialog (opened from all dialogs where a date and time can be entered) is shown complete, the date part is scrollable, but the 2 buttons "Cancel"/"OK" are only visible with there upper part. They can be selected, though, so the full functionality is there.

The time dialog is shown only half, the lower part is not visible. As this dialog is not scrollable, all lower times cannot be selected. Also no OK/cancel is visible.

The careportal dialogs are all fine, except the glucose source radio buttons. Only the first 2 are visible.

With all dialogs with date/time the weight for the time text should be maybe the same as the weight for the date text (the date text is shown normal, the time text has almost no place left and is splitted over several lines)

![bolus_and_calibration_dialog_without_ok](https://user-images.githubusercontent.com/1267238/39232552-fbb1b3fe-486d-11e8-816a-f35a79787e43.png)
![date_dialog_with_cut_buttons](https://user-images.githubusercontent.com/1267238/39232553-fbd42718-486d-11e8-9102-0676083d4945.png)
![glucose_source_partially_visible](https://user-images.githubusercontent.com/1267238/39232554-fbed20a6-486d-11e8-92c4-c62d8fb13032.png)
![time_dialog_cut_in_the_middle](https://user-images.githubusercontent.com/1267238/39232555-fc082004-486d-11e8-9d2a-db8febb68e41.png)

**Comment by cp491977** [comment]
Behavior same in 2.0 RC4
