### ISSUE TITLE
Overview page reports wrong temp bolus % when entered in Care portal. 

### ISSUE THREAD

**Issue by JohnArm** [MilosKozak/AndroidAPS#928]
Reporting bugs
--------------
- Note the precise time the problem occurred and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new

**Comment by JohnArm** [comment]
I've just started on open loop using AndroidAPS 1.58 2018.04.21 and feeling my way around. I tried entering a temp bolus in the care portal and noticed that the overview page reports it wrongley. 
Ie. It displays 80% entered as 180%.

**Comment by MilosKozak** [comment]
test it in RC2 and reopen if needed
please realize NS has different notation:
NS: -100% to +100%
AAPS: 0% to 200%
