### ISSUE TITLE
NSClientPlugin: add option to suppress log output

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#933]
When not updating the tab twice (send, ack response) for every record being send (using a synchronous message bus) the rate increases to ~1k/s.

**Comment by MilosKozak** [comment]
?? the event should be sent once for every WS message

**Comment by jotomo** [comment]
IIRC one EventNSClientUpdateUI is send when a record is dispatched and one when the server acknowledges the record. I have modified this locally, but I still need to find a way to update the queue size display without updating the UI for every acknowledgement before turning this into a PR.  Low prio.
