### ISSUE TITLE
[RC1] WIFI NSClient connection issue

### ISSUE THREAD

**Issue by typ1-brods** [MilosKozak/AndroidAPS#938]
Starting with RC1, NS client does not connect when WLAN is activated so that queues are rising high.

Connection settings:
- Use Wifi connection only: off or on (no different behaviour)
- Wifi SSID: myssid
- Allow connection in roaming: on

Smartphone settings:
WLAN active => No connection to NS although www connection works fine, treatments queuing
WLAN deactivated, connection via GSM => NS connection OK

**Comment by typ1-brods** [comment]
When deleting SSID name it is working again with wlan connection as well. The issue seems to depend on SSID entry

**Comment by AdrianLxM** [comment]
You will need to put the SSID in quotation marks for now: `"myssid"`

**Comment by typ1-brods** [comment]
OK, this is working so far
