### ISSUE TITLE
[RC1] Scheduled profile change is displayed without percentage

### ISSUE THREAD

**Issue by swissalpine** [MilosKozak/AndroidAPS#942]
Scheduling a profile switch over care portal (enhancement: I like to have it also on overview dialogue ;-) ) is realised including new programming the pump. - Only the percentage (if choosen) isn't shown, neither on overview tab nor in treatment > profile switch.
This is confusing because you think the demanded percentage wasn't realised. Looking at the pump and in the profile dialogue you see for each hour the right BR.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/e5ed63a46fb862f201090888c76466fc978001ca

**Comment by swissalpine** [comment]
Thanks!
