### ISSUE TITLE
Bolus steps seem to mismatch in NewInsulinDialog

### ISSUE THREAD

**Issue by Mackwe** [MilosKozak/AndroidAPS#960]
I noticed the bolussteps seem to mismatch between pump and app.

NewInsulinDialog.java uses "ConfigBuilderPlugin.getActivePump().getPumpDescription().bolusStep" to define steps. When using AAPS connected to a DanaR v2, I seem to get 0.1 bolussteps although pump is capable of 0.05. Also, how is this handled in NSClient? Since the NSClient is anaware of pump model?

Should this become a configuration setting instead?

**Comment by jotomo** [comment]
Works for me with RC2,with the VirtualPump when setting `PumpDescription.bolusStep` to 0.05d there like the DanaR v2 has it. What version are you on?

**Comment by Mackwe** [comment]
Also on RC2. Phone is at kindergarten, though. Will re-build and re-check when the phone is back, then. Do you also have .05 boluses visible in the graph, or .1 granularity?

**Comment by jotomo** [comment]
Graph shows 0.05 (all with regular build, not NSClient btw).
Regard NSClient mode: I think #863 will eventually allow to configure the type of virtual pump (which NSClient uses), so that would nicely solve that.

**Comment by Mackwe** [comment]
I haven't checked lately, but will Pump Type be an available option in NSClient, then?

**Comment by MilosKozak** [comment]
shoud be fixed in dev now https://github.com/MilosKozak/AndroidAPS/commit/243755d1b11eb49705a6f2236c78513bb5c12972
