### ISSUE TITLE
Some translations ignore Language setting in AAPS

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#961]
Some translations look at system to get their language instead of application settings.

Tested on combo branch (1.58)

Some samples: 
- Combo pump actions (when they show text)
- Nightscout - Android APS Started

**Comment by AdrianLxM** [comment]
Now everything goes through `MainApp.gs()`

https://github.com/MilosKozak/AndroidAPS/pull/963/files
