### ISSUE TITLE
freezing bolus-pop-up

### ISSUE THREAD

**Issue by soko78** [MilosKozak/AndroidAPS#970]
**Sometimes, when starting a bolus, the bolus-pop-up freezes. Sometimes it gives the bolus and then freezes and sometimes it even does not start to bolus but freezes. In the background TBR still seems to work. The only way to erase the freezed-pop-up is by opening the task manager, closing aaps and starting it again.

**Build: 2018.05.01

**this was at 09:18:44 on the 2.5.18

[AndroidAPS._2018-05-02_13-20-30_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1967558/AndroidAPS._2018-05-02_13-20-30_.0.zip)
![freez](https://user-images.githubusercontent.com/34250545/39527746-85addcf4-4e22-11e8-82a8-bd7154e42268.png)

**Comment by jotomo** [comment]
a) How was the bolus started?
b) Was the screen turned off or another app opened while bolus was (not) delivered?

**Comment by jotomo** [comment]
Related #939

**Comment by soko78** [comment]
answers to 
a)the bolus was started by the button "insulin" on the home tab.
b)yes, I started the bolus and turned off screen. Other apps were surely opened but in the background (means other apps were not closed in the task manager).

**Comment by bboi61** [comment]
a) Bolus Abgabe, ohne Probleme
b) Keine weitere App geöffnet. Bildschirm ging in Standby. Danach friert das Bolus-Pop-Up ein.
AndroidAPS 2.0 18.05.01

**Comment by MilosKozak** [comment]
@jotomo is this resolved?

**Comment by AdrianLxM** [comment]
Probable fix: #999 
Further discussion in: #939
