### ISSUE TITLE
aaps flat-lines data from xdrip

### ISSUE THREAD

**Issue by soko78** [MilosKozak/AndroidAPS#972]
**I do not use a transmitter for my libre. I scanned two or three times my libre in the night and aaps did get the data from xdrip but somehow flatlines them. The data are uploaded to Nightscout by xdrip but aaps does not download them from NS. Aaps gets the data by broadcast directly from xdrip.
The screenshot shows the same timeperiod in xdrip and in aaps-rc2.
**build:2018.05.01 
[AndroidAPS._2018-05-02_13-20-30_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1967584/AndroidAPS._2018-05-02_13-20-30_.0.zip)
![approximation](https://user-images.githubusercontent.com/34250545/39528116-85b2c6a0-4e23-11e8-99c0-4b13bbd59017.jpg)

**Comment by AdrianLxM** [comment]
Could you please install another app like NightWatch that receives the same broadcast and then try to reproduce that. This should show it it is the broadcast from xDrip or how it is handled in AAPS

**Comment by soko78** [comment]
Sure. I'll do that tonight and have a look at it till tomorrow/the next days. I'll get back here the next days with more infos.

**Comment by soko78** [comment]
yesterday I installed nightwatch and here are the results. On the first pic you can see xdrip(nightly from 30.4.18), nightwatch and aaps rc2. This morning at 8a.m. I installed an older version of xdrip (nightly from 03.03.18) because I thought the problem is because xdrip has a bug. But in both pics you can see that either nightwatch and aaps get somehow "wrong" data or interpret them wrong.

It seems, that for now I am the only one who has this problem. Maybe this is because I don't use any transmitter but just scan irregularly the libre. But xdrip should sent the correct values even if I scan just sometimes.

![new xdrip till 8 am](https://user-images.githubusercontent.com/34250545/39596961-42051876-4f14-11e8-8e3d-c8c1be84df8d.jpg)
![old xdrip from 8am](https://user-images.githubusercontent.com/34250545/39596978-47bef192-4f14-11e8-943e-cd6a5677ee83.jpg)

**Comment by AdrianLxM** [comment]
Could you please open this issue in the xDrip repostitory https://github.com/NightscoutFoundation/xDrip as well. It really looks like it is the data coming from xDrip :/

**Comment by soko78** [comment]
done issue#419
