### ISSUE TITLE
[RC2] No ExtendedBolus in AAPS

### ISSUE THREAD

**Issue by st0ber** [MilosKozak/AndroidAPS#978]
AAPS does not display an ExtendedBolus. In Nightscout you can see the ExtendedBolus.
![screenshot_20180502-211801](https://user-images.githubusercontent.com/32514747/39544740-4dd2d67c-4e4f-11e8-8d2f-71a316999ebc.png)
![img_20180502_212547_417](https://user-images.githubusercontent.com/32514747/39544798-826865d2-4e4f-11e8-90c9-b70c514ebc38.JPG)
{
    "_id": {
        "$oid": "5ae9e62e9d8647aeb7842a5c"
    },
    "carbs": 48,
    "created_at": "2018-05-02T18:20:57+02:00",
    "duration": 60,
    "enteredinsulin": "6.525",
    "eventType": "Combo Bolus",
    "insulin": 1.2,
    "key600": "BOLUS803BA7D4",
    "notes": "Dual Bolus: normal 1.2U, square 5.325U, duration 60 minutes : carb 48g 5.3U, {180~199} 1.2U, iob 0.0 0.0U (9g/u, isf 45/u)",
    "relative": 2,
    "splitExt": "82",
    "splitNow": "18"
}

**Comment by MilosKozak** [comment]
where was extended bolus entered? is it possible to repeat it?

**Comment by st0ber** [comment]
I entered the values in my pump. The values were then uploaded to Nightscout with the 600SeriesAndroidUploader.

**Comment by st0ber** [comment]
I repeat it. No ExtendedBolus in AAPS.

{
    "_id": {
        "$oid": "5aeb32fd9d8647aeb78b152c"
    },
    "carbs": 60,
    "created_at": "2018-05-03T18:02:32+02:00",
    "duration": 90,
    "enteredinsulin": "6.65",
    "eventType": "Combo Bolus",
    "key600": "BOLUS803CF502",
    "notes": "Square Bolus: 6.65U, duration 90 minutes : carb 60g 6.7U, {180~199} 0.0U, iob 0.0 0.0U (9g/u, isf 45/u)",
    "relative": 2,
    "splitExt": "100",
    "splitNow": "0"
}

**Comment by MilosKozak** [comment]
EB entered in NS works
do it too and compare JSONs

**Comment by st0ber** [comment]
OK, I have not tried it yet, but it worked under AAPS 1.58. That's why I have now assumed that it is the AAPS 2.0 RC2.

**Comment by st0ber** [comment]
Is there any news? I continue to use version 1.58 because it only works with this version. Unfortunately, because of my gastroparesis, I am dependent on the Extended Bolus. I also like to test the new version 2.0 RC4, but think the "error" has probably not been resolved there as well.

**Comment by AdrianLxM** [comment]
@st0ber am I seeing it right: You are not looping at all but just use AAPS as remot control? (Extemded boluses don't make any sense while looping).

Did you see ans difference when you did this?
> @MilosKozak: 
> EB entered in NS works
> do it too and compare JSONs

**Comment by st0ber** [comment]
Yes I know that. But since the Minimed 640g shuts off insulin too late for me, I still use it and come up with the suggestion of AAPS to set a temporary basal rate to 0 very well. It captures my imminent hypoglycemia even before the insulin shutdown of the Minimed 640g.
Unfortunately, the Minimed 640g for diabetics who additionally have a strong gastroparesis are not necessarily suitable, but in combination with AAPS I found a reasonably acceptable solution for me.

Yesterday I tried the proposed by Milos. Unfortunately it did not work. Unfortunately, it works only in the 1.58.

**Comment by st0ber** [comment]
I use Open Loop. :-)

**Comment by st0ber** [comment]
Between the change from the version 1.58 to 2.0 RC3 I did not change anything. In version 1.58 it does not work, in version 2.0 RC3 does not. That means for me, that the "error" in the version 2.0 RC must be stuck.

**Comment by st0ber** [comment]
Since the ExtendedBolus does not seem to make sense with Open / Closed Loop, I close the issue.

**Comment by st0ber** [comment]
@AdrianLxM

Here is the test with entering the ExtendedBolus directly in Nightscout.

{
    "_id": {
        "$oid": "5b1d39489d8647aeb7995f77"
    },
    "enteredBy": "Nightscout",
    "eventType": "Combo Bolus",
    "glucose": 100,
    "reason": "",
    "glucoseType": "Finger",
    "carbs": 10,
    "insulin": 0.3,
    "duration": 60,
    "units": "mg/dl",
    "splitNow": "30",
    "splitExt": "70",
    "enteredinsulin": "1",
    "relative": 0.7,
    "created_at": "2018-06-10T14:44:24.520Z"
}

Here is the test with the input of the ExtendedBolus on the Bolus expert of the Minimed 640g and the 600seriesAndroidUploader.

{
    "_id": {
        "$oid": "5afbcef29d8647aeb7ef47b3"
    },
    "carbs": 40,
    "created_at": "2018-05-16T08:22:36+02:00",
    "duration": 90,
    "enteredinsulin": "6.075",
    "eventType": "Combo Bolus",
    "insulin": 1.075,
    "key600": "BOLUS804D9093",
    "notes": "Dual Bolus: normal 1.075U, square 5.0U, duration 90 minutes : carb 40g 5.0U, {180~199} 1.1U, iob 0.0 0.0U (8g/u, isf 40/u)",
    "relative": 2,
    "splitExt": "83",
    "splitNow": "17"
}

Both do not show the ExtendedBolus in AAPS.

**Comment by st0ber** [comment]
No answer...CLOSE
