### ISSUE TITLE
[RC2] UAM interferes with sensitivity calculation

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#984]
When enabling UAM and eating carbs **without** recording them, UAM will detect them and bolus for them. UAM does this based on positive deviations. However, these deviations will lead sensitivity plugins to calculate a high insulin resistance since the sensitivity plugins don't see any carbs, nor do they infer them like UAM does.

**Comment by LongboatAline** [comment]
I think it should basically be stressed in the documentation that autosens can can only give sensible results if carbs (and externally applied insulin) are logged as meticulously as possible, even if AAPS is able to correct resulting highs without being explicitely told about the carbs.

Idea/Project on my to-do list (mid-may): graph sensitivity AGP-like to evaluate if it follows a circadian pattern that could be used to stabilize against errors in carb-estimation.

**Comment by scottleibrand** [comment]
There are two mitigations in place for this in oref0 autosens. It does detect unannounced meals, and excludes those deviations, showing u(xxxxxx) in the debug output. And when it misses them, autosens uses the median deviation over 8h and 24h, so each high deviation just shifts the median slightly. I’m not sure whether AAPS implements autotune in a way that takes advantage of those protections or not, but if not it could be adjusted to do so.

**Comment by AdrianLxM** [comment]
This should be fixed in Oref1 sensitivity plugin now.
