### ISSUE TITLE
unfinished bolus wizard logs carbs at the time insulin was given

### ISSUE THREAD

**Issue by LongboatAline** [MilosKozak/AndroidAPS#985]
More of a feature:

I got side-tracked when going through the bolus wizard menu, leaving the confirmation dialog unconfirmed. No insulin given, carbs consumed.
I didn't notice that until about an hour later when I wanted to correct that surprisingly steep incline in svg. Now the route to go would have been to cancel the bolus wizard and take care of the problem as it was presenting itself, but instead I hastily confirmed the dosing from an hour ago.

Both carbs and insulin got logged with the timestamp of the insulin.

Due to the potential of irritating autosens, it might be desirable to log the carbs relative to the time the bolus entry was started at.

**Comment by MilosKozak** [comment]
i think it's too specific situation to make a general conclusion from that. you can remove the record and create new if needed.
closing for now, reopen if needed pls
